### ISSUE TITLE
request for transfer of ownership of a pypi account/project `pycryptopan`

### ISSUE THREAD

**Issue by aaronkaplan** [pypa/pypi-support#1]
As discussed in pypa/warehouse#1506 , I'd like to ask you to transfer the ownership of https://pypi.org/project/pycryptopan/ to me. As written in pypa/warehouse#1506 the co-author of the code behind pycryptopan is unfortunately deceased. I have git admin and commit privs to the underlying gitub repo (https://github.com/FFM/pycryptopan) but not access to the pypi account. Hence I can't update the pypi page. However, I am continuing to maintain the pycryptopan project.

If needed, I can organise formal proof (certificates of death, written statements of the relatives that I may continue with the pypi page in the deceased' name).

Please advise on the neccessary steps.
Thanks,
aaron.

**Comment by yeraydiazdiaz** [comment]
Hi @aaronkaplan, are you still interested in transfering the project to yourself?

If so, I think we can move on with the transfer since it's clear you've been maintaining the GitHub repo recently.

**Comment by aaronkaplan** [comment]
> On 10.01.2020, at 11:21, Yeray Diaz Diaz <notifications@github.com> wrote:
> 
> Hi @aaronkaplan, are you still interested in transfering the project to yourself?
> 
> If so, I think we can move on with the transfer since it's clear you've been maintaining the GitHub repo recently.
> 

yes! Definitely!

It's really a matter of keeping the  original's author (and my best friend) memory alive via code which should live on and continue to evolve.
What would you need from me in order to complete this?

Thanks!
a.

**Comment by yeraydiazdiaz** [comment]
Great, we just need you to confirm your PyPI username.

**Comment by aaronkaplan** [comment]
> On 10.01.2020, at 11:29, Yeray Diaz Diaz <notifications@github.com> wrote:
> 
> Great, we just need you to confirm your PyPI username.

That would be "aaronkaplan".

Thanks!
a.

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by aaronkaplan** [comment]
Thanks everyone!
