### ISSUE TITLE
PEP 541 Request: kelp

### ISSUE THREAD

**Issue by LamarrD** [pypa/pypi-support#1000]
### Project to be claimed

`kelp`: https://pypi.org/project/kelp

### Your PyPI username

`lamarrd`: https://pypi.org/user/lamarrd

### Reasons for the request

I believe this project has been abandoned and furthermore was never even started. The namespace was claimed in 2015, by a user who only has this project listed under pypi. The project is not installable via pip (I don't think it was ever actually published). I have no means of contacting the maintainer as their email/homepage isn't publicly listed.

I like to use the namespace for a tool I am ready to publish that aims at automating the process of creating least privileged IAM roles in AWS serverless applications. kelp - keep everything least privileged.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/LamarrD/keLP

### Contact and additional research

I am not able to contact the owner as their information isn't public on the pypi registry and their is no hojmepage for the current project. I found a "Artur Matos" on linkedin, but I'm not sure he is the maintainer. As it was published and not touched since 2015, I don't think there is any active maintainer.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by bmorris3** [comment]
Heads up: this is a duplicate (independent request) of #452.

**Comment by LamarrD** [comment]
Ahh darn, he beat me to the name. I might have to just except kelp2 :(. Closing my request, thanks for the heads up
