### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by steve-the-bayesian** [pypa/pypi-support#1004]
### PyPI Username

steve.the.bayesian

### Reason for request

I had been using the Google authenticator app on my phone for 2FA.  Old phone died unexpectedly.

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
