### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by daefresh** [pypa/pypi-support#1007]
### PyPI Username

daefresh

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by daefresh** [comment]
Let me me know if you need any more information.

**Comment by daefresh** [comment]
Thanks guys. Let me know if you need anything else from me. I have an issue I need to address with a production package.

**Comment by daefresh** [comment]
Hi any questions? Thanks so much!

**Comment by daefresh** [comment]
@ewdurbin I'd greatly appreciate your help on this one, and I'd be happy to donate to any good cause you point me in the direction for as appreciation!

**Comment by ewdurbin** [comment]
Hi @daefresh, a reminder that you acknowledged that "it may take a significant amount of time to process my account recovery request." when filing this issue. Repeated responses and direct pings are part of the reason why high volume issue trackers like these can be very draining for those who tend to them, which lead to demoralization and burnout.

Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by daefresh** [comment]
@ewdurbin Yes, I totally understand, and I value and appreciate the time you and other take to maintain this, hence the reason why I'm offering to donate to w/e organization you guys run, to pay for any services that are needed, thank you!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
