### ISSUE TITLE
PEP 541 Request: cyipopt

### ISSUE THREAD

**Issue by moorepants** [pypa/pypi-support#1008]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/cyipopt

### Your PyPI username

`USER_NAME`: https://pypi.org/user/moorepants

### Reasons for the request

I'm the lead maintainer of https://github.com/mechmotum/cyipopt. The original author of cyipopt published it on PyPi at https://pypi.org/project/ipopt and since I've been maintainer the original author gave me permissions to upload new releases there. We did a major update to the software, calling it version 1.0 and want(ed) to publish it to PyPi under the `cyipopt` name so that `pip install cyipopt` is the preferred way to install the package. I tried to upload the package under `cyipopt` and it seems that the name is already registered but not in use.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/mechmotum/cyipopt

### Contact and additional research

I'm not sure how to figure out who the owner is because no page is displayed at https://pypi.org/project/cyipopt

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @moorepants, the name `cyipopt` has been placed in the prohibited project names list by @pypa/warehouse-admins, I do not have the permissions to remove it but one of the admins should be able to.

**Comment by moorepants** [comment]
Ok, if that could happen, we'd very much appreciate it!

**Comment by ewdurbin** [comment]
This project has been created with the `moorepants` User on PyPI as the Owner Role. You can now upload releases.

**Comment by moorepants** [comment]
Thanks!
