### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `nlp`

### ISSUE THREAD

**Issue by rlouf** [pypa/pypi-support#101]
**Project to be claimed**

`nlp`: https://pypi.org/project/nlp

**Your PyPI username**

`rlouf`: https://pypi.org/user/rlouf

**Reasons for the request**

The project is unmaintained and has been so since 2015. The associated [homepage](nlpy.org) does not exist.

**Maintenance or replacement?**

I intend to replace it with a different one: https://github.com/huggingface/transformers

**Contact and additional research**

I attempted to reach out to the current owner via the email on the project's page, as well as on the one specified on his [personal website](http://www.nlab.ci.i.u-tokyo.ac.jp/~shu/), to no avail. Since the project is not associated to any Github/Bitbucket/Gitlab page I was not available to raise an Issue.

**Comment by yeraydiazdiaz** [comment]
Hello @rlouf, I can confirm this project is invalid as it's got a single release with no files associated.

I will now ask an admin to perform this transfer for you.

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by rlouf** [comment]
Great, thank you for your help.
