### ISSUE TITLE
PEP 541 Request: rcognita

### ISSUE THREAD

**Issue by OsinenkoP** [pypa/pypi-support#1010]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/rcognita

### Your PyPI username

`USER_NAME`: https://pypi.org/user/OsinenkoP

### Reasons for the request

We would like to claim the name 'rcognita' on PIP. The project is being actively maintained by our [research team](https://github.com/AIDynamicAction) on Github. A former team member created this entry on PIP without our acknowledgment and is no longer maintaining it. The current release is on our organization Github and is by many commits beyond the version of the date the PIP entry was created. Furthermore, 'rcognita' package is MIT-licensed under my name, if that matters.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/AIDynamicAction/rcognita

### Contact and additional research

We are unable to contact the original creator of the PIP entry.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by OsinenkoP** [comment]
Is there anyone alive?

@ewdurbin It's been 3 months already, could you please transfer the name?

**Comment by yeraydiazdiaz** [comment]
Hello @OsinenkoP, PEP 541 requires us to attempt contact with the current owner which I believe is GitHub user @ebolotin6.

Ideally he should transfer the project to you himself, otherwise the process will be delayed until we get a response or until 6 weeks have passed without one.

**Comment by OsinenkoP** [comment]
Let's just wait 6 weeks. Thanks

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
