### ISSUE TITLE
Limit Request: SEDRo - 250 MB

### ISSUE THREAD

**Issue by anur0n** [pypa/pypi-support#1011]
### Project

https://test.pypi.org/project/sedro/

### Does this project already exist?

Yes

### Size of release/project

100

### Which indexes

TestPyPI

### Reasons for the request

I am working on a simulated environment for AI agents. I have to publish the environment with the package release. Though the current size is below 150MB. It might increase more in future.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `sedro` to 250 MB on TestPyPI.
