### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by law** [pypa/pypi-support#1012]
### PyPI Username

`law`

### Reason for request

Hello, I believe I've lost access to whatever email I used to register the username 'law' at pypi.org, apparently back in 2016.  Could I get it reassociated with the email address for the newly-created user `lwhalen`, please and thank you?

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This username is associated with an @gmail.com address that doesn't appear to include either of your handles or name.

There is no mechanism at this time for requesting a username, only restoring access to one where access is lost. If you are able to identify the gmail.com address associated with the user, please email support@pypi.org referencing this issue and we can reopen it.
