### ISSUE TITLE
PEP 541 Request: lakefs

### ISSUE THREAD

**Issue by nopcoder** [pypa/pypi-support#1013]
### Project to be claimed

`lakefs`: https://pypi.org/project/lakefs

### Your PyPI username

`treeverse`: https://pypi.org/user/treeverse

### Reasons for the request

a package name called 'lakefs' was created and owned by `barakamar`: https://pypi.org/user/barakamar.
would like this account to manage this project.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/treeverse/lakeFS

### Contact and additional research

Contacted the owner and he deleted the project (initial upload), need this user to manage it.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
There is no project with the name `lakefs`, no transfer is possible.
