### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by prabhakk-mw** [pypa/pypi-support#1014]
### PyPI Username

`prabhakk@mathworks.com`

### Reason for request

PyPi (Register new User) tells me that I already have an account with this email address. (prabhakk@mathworks.com)
However, I don't know my username, which prevents me from logging in.

I've been able to reset my password through "Forgot Password" but unable to find any means to recover the username.
Please help.

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please email support@pypi.org from that email address, referencing this issue, and we will respond with the username associated with the account.
