### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pokurt** [pypa/pypi-support#1015]
### PyPI Username

pokurt

### Reason for request

im dumb and lost my passwordd pls give access i wont hack any projects

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by pokurt** [comment]
lost the email i used to login too :v

**Comment by ewdurbin** [comment]
Hello, a password reset has been issued and was successfully delivered to the email address associated with the account.

If you are unable to access email sent to that address, please email support@pypi.org referencing this issue to determine next steps.
