### ISSUE TITLE
PEP 541 Request: brip

### ISSUE THREAD

**Issue by rayluo** [pypa/pypi-support#1018]
### Project to be claimed

`brip`: https://pypi.org/project/brip/

### Your PyPI username

`rayluo`: https://pypi.org/user/rayluo/

### Reasons for the request

The existing project is either squatting, or was just the author's attempt to experiment the upload-to-pypi procedure. Nonetheless, its PyPI project page contains no project homepage, no source code repo. And if you go ahead to [download its only release, the `0.1.0`](https://pypi.org/project/brip/#files), it contains no functionality. I believe these satisfy one of the criteria of [Invalid Projects](https://www.python.org/dev/peps/pep-0541/#invalid-projects):

> project is name squatting (*package has no functionality or is empty*);

### Maintenance or replacement?

Maintenance

### Contact and additional research

I reached out to its author's via email, which is the only information available from the existing project page, but I received no response. Besides, PEP541 does not require contacting current owner for claiming Invalid Project.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by rayluo** [comment]
By the way, I fully understand that, it would take months for the admins here to investigate and justify a PEP 541 transfer on the "abandoned project" ground. But, for  those [**Invalid Projects** - project is name squatting *(package has no functionality or is empty)*](https://www.python.org/dev/peps/pep-0541/#invalid-projects) requests, it is supposed to be much easier to investigate and justify.

I would suggest admins to process those "Invalid Projects" requests first. This is an easy way to crank through the current backlog. Just my 2 cents. :-)

**Comment by yeraydiazdiaz** [comment]
Hello @rayluo, I can confirm the project has no functionality and is therefore invalid. I will attempt to contact the owner and allow one week for replies before transferring the project.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
