### ISSUE TITLE
Limit Request: bse_ml - 200 MB

### ISSUE THREAD

**Issue by yanlong-sun** [pypa/pypi-support#1021]
### Project

https://pypi.org/project/bse-ml/

### Does this project already exist?

Yes

### Size of release/project

200MB

### Which indexes

PyPI

### Reasons for the request

This project implements a deep learning method to produce the mask of the input. So it includes the weights of the network, which will take a lot of space. 

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `bse-ml` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
