### ISSUE TITLE
PEP 541 Request: minian

### ISSUE THREAD

**Issue by phildong** [pypa/pypi-support#1022]
### Project to be claimed

`minian`: https://pypi.org/project/minian

### Your PyPI username

`denisecailab`: https://pypi.org/user/denisecailab/

### Reasons for the request

The project doesn't seem to exist anymore (link return 404), yet I can't seem to upload to this name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/DeniseCaiLab/minian

### Contact and additional research

Seem to be similar to this recent issue:
https://github.com/pypa/warehouse/issues/9145

I'd be willing to dive in more and potentially contact the previous owner once I can get some advice on where to start?

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @phildong, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
