### ISSUE TITLE
PEP 541 Request: msgrpc

### ISSUE THREAD

**Issue by dhagrow** [pypa/pypi-support#1024]
### Project to be claimed

`msgrpc`: https://pypi.org/project/msgrpc

### Your PyPI username

`dhagrow`: https://pypi.org/user/dhagrow

### Reasons for the request

I was unable to register a new package with the name `msgrpc`, but received the response: `400 The name 'msgrpc' isn't allowed`. It is not clear why this name is being rejected. There are no packages on PyPI with this name, and I can find no references to it in the standard library.

The only reference to the name that I can find is a module for the Metasploit framework that is only used internally, and is sometimes called `msfrpc` instead. The PyPI search engine does list [pymetasploit3](https://pypi.org/project/pymetasploit3/) in the search results for `msgrpc`, but apparently only because the name is referred to in the README for the package.

As it does not seem that the name has ever been used anywhere, I would like to stake a claim for it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://pypi.org/project/pymetasploit3/

### Contact and additional research

It is not clear who should be contacted in this case. pymetasploit3 is not demonstrating any intent to use the name for a package.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @dhagrow, `msgrpc` was placed in the prohibited projects names list by @pypa/warehouse-admins, I do not have permissions to remove it but an admin should be able to process the request soon.

**Comment by ewdurbin** [comment]
@dhagrow do you have an existing project that will use this name?

**Comment by dhagrow** [comment]
@yeraydiazdiaz Thanks.

@ewdurbin Yes, however it is not publicly available at the moment. I am in the process of seeking permission to open-source the project in question. I hope to receive authorization within the next month, and once I do, I will be happy to share the repository here.

For now, I can share some (out-of-date) blog posts that demonstrate the project (named simply "rpc"):

- https://immunityproducts.blogspot.com/2016/09/leveraging-innuendos-rpc-for-fun-and.html
- https://immunityproducts.blogspot.com/2016/12/innuendo-rpc-shell.html

Please let me know if there are any other considerations I should be aware of.

**Comment by ewdurbin** [comment]
This project will remain on the prohibited list until an existing active project with a public source code repository is available for review.
