### ISSUE TITLE
PEP 541 Request: SoftLayer   - test.pypi.org

### ISSUE THREAD

**Issue by allmightyspiff** [pypa/pypi-support#1025]
### Project to be claimed

`SoftLayer`: https://test.pypi.org/project/SoftLayer/

### Your PyPI username

`Christopher.Gallo`: https://test.pypi.org/user/Christopher.Gallo/

### Reasons for the request

I'm no longer able to get in touch with the user who created the SoftLayer project on test.pypi.org, and I would like to start using that test space.

I'm currently a maintainer on the main SoftLayer project ( https://pypi.org/project/SoftLayer/ ) and would like to get that set to match the test environment.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/softlayer/softlayer-python

### Contact and additional research

The only maintainer on the test pypi is sl-dsteinke, who hasn't worked at SoftLayer since 2018, and I don't have a personal contact information for him. His email isn't listed on his profile.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
