### ISSUE TITLE
Limit Request: botocore - 20 GB (in total)

### ISSUE THREAD

**Issue by kyleknap** [pypa/pypi-support#1026]
### Project

botocore, https://pypi.org/project/botocore/

### Does this project already exist?

Yes

### Size of release/project

20 GB (in total for project)

### Which indexes

PyPI

### Reasons for the request

This is the back-end package for the AWS SDK for Python (boto3). Our artifacts are only 7MB but we basically release daily and in today's release, we got this error:
```
Uploading botocore-1.20.52.tar.gz
  0%|          | 0.00/7.30M [00:00<?, ?B/s]
  0%|          | 8.00k/7.30M [00:00<02:37, 48.5kB/s]
  3%|2         | 208k/7.30M [00:00<00:09, 799kB/s]  
 16%|#5        | 1.16M/7.30M [00:00<00:01, 3.51MB/s]
 60%|#####9    | 4.35M/7.30M [00:00<00:00, 12.6MB/s]
100%|##########| 7.30M/7.30M [00:01<00:00, 4.35MB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: Project size too large. Limit for project 'botocore' total size is 10 GB. See https://pypi.org/help/#project-size-limit for url: https://upload.pypi.org/legacy/
```
Would it be possible to get a size update as soon as possible? I put down 20GB (10GB extra from what we currently have) in the request, which would give us roughly 4 years till we need another bump in size. Let us know if that is reasonable. We pushed up the tags for the release: https://github.com/boto/botocore/releases/tag/1.20.52 but were not able to release to PyPI because of this limit.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `botocore` to 20 GiB on PyPI.

**Comment by kyleknap** [comment]
Thanks!
