### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by apoclyps** [pypa/pypi-support#1027]
### PyPI Username

apoclyps

### Reason for request

I've lost my device with the 2FA authentication app & recovery codes for my account. I would like to reset 2FA on my account so I can login using my username and password before setting up 2FA again.

I am happy to be contacted via my primary email address to reset this.

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by apoclyps** [comment]
as it's been a number of months, is there any update on performing account recovery to reset my 2FA?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by apoclyps** [comment]
Branch created in https://github.com/apoclyps/reviews/tree/pM59f22C1GfSBLkD

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
