### ISSUE TITLE
PEP 541 Request: Transfer ownership of empty 'line_profiler' package

### ISSUE THREAD

**Issue by Erotemic** [pypa/pypi-support#103]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/line_profiler

**Your PyPI username**

I typically release packages under my personal username:
`USER_NAME`:  https://pypi.org/user/pyutils/ 

For this project, I created a github organization called pyutils so the project can have multiple maintainers (to prevent an issue like this from happening again). I created a corresponding pypi account https://pypi.org/user/pyutils/ which might be a better choice for a multiple-owner project. 

If organization pypi repos are frowned upon, then I'd also be ok with using my personal account: https://pypi.org/user/Erotemic but I'd prefer to use  https://pypi.org/user/pyutils/ 

I'm not sure what the standard practice is, so let me know if either way is preferred. 

**Reasons for the request**

As evidenced in this github thread: https://github.com/rkern/line_profiler/pull/153 the project has not been maintained in months. The pip install is broken on Python 3.7, and the current owner has not responded to the issue at all. 

**Maintenance or replacement?**

I intend to simply maintain the package as is. 

EDIT: I've contacted the author and received permission to take ownership of the repo: 

![image](https://user-images.githubusercontent.com/3186211/70731106-2ce3ea00-1cd4-11ea-9d16-bafc6d7184c6.png)

**Comment by Mogost** [comment]
@rkern please finish transferring.
https://github.com/pyutils/line_profiler/ is ready.

**Comment by Erotemic** [comment]
This has been resolved.
