### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jtprogru** [pypa/pypi-support#1031]
### PyPI Username

jtprog

### Reason for request

Lost 2FA authentication app and security token

### Code of Conduct

I agree to follow the PSF Code of Conduct

### Acknowledgement

I understand that it may take a significant amount of time to process my account recovery request.

**Comment by jtprogru** [comment]
I'm sorry, but how long to wait for access to be restored?

**Comment by jtprogru** [comment]
@ewdurbin please answer to my question: how long to wait for access to be restored?

**Comment by jtprogru** [comment]
Someone can answer: why is it taking so long for there to be no movements to restore access to my account?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
