### ISSUE TITLE
PEP 541 Request: tristan

### ISSUE THREAD

**Issue by benjaminhwilliams** [pypa/pypi-support#1034]
### Project to be claimed

`tristan`: https://pypi.org/project/tristan

### Your PyPI username

`benjaminhwilliams`: https://pypi.org/user/benjaminhwilliams

### Reasons for the request

I believe the project `tristan` has been abandoned.  I have tried to contact the project owner by email and by opening an issue (morgendave/tristan#1) and have received no response to either.  There have been no commits to the project since 2019-06-08 and no issues or pull requests have been opened or closed on the project's GitHub page in that time.

I would like to reuse the name `tristan` for an active project, currently using the name `tristan-dls`.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The source code for the new package, with which I intend to replace the existing package `tristan`, resides at [DiamondLightSource/python-tristan](https://github.com/DiamondLightSource/python-tristan) and is available via PyPI at https://pypi.org/project/tristan-dls/.

### Contact and additional research

- Attempted to contact the maintainer, Zhiwei Zhao (@morgendave), by email (as listed in the author field of [the package tristan](https://pypi.org/project/tristan/) on 2021-03-26, with no response to date.
- Opened an issue (morgendave/tristan#1) on 2021-04-12 with no response to date.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by benjaminhwilliams** [comment]
Six weeks have elapsed since I opened this ticket.  Do I need to do anything else to help you process it?

**Comment by yeraydiazdiaz** [comment]
Hello @benjaminhwilliams, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by benjaminhwilliams** [comment]
Many thanks @yeraydiazdiaz.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
