### ISSUE TITLE
PEP 541 Request: jade

### ISSUE THREAD

**Issue by ptillet** [pypa/pypi-support#1035]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/jade

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ptillet

### Reasons for the request

It seems like the project page yields an error 404, but trying to `twine upload` to it gives me 
"The user 'ptillet' isn't allowed to upload to project 'jade'"
Maybe the project is registered but all previous releases have been deleted?

### Contact and additional research

phil@openai.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @ptillet, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
