### ISSUE TITLE
PEP 541 Request: uncertain

### ISSUE THREAD

**Issue by icorbrey** [pypa/pypi-support#1038]
### Project to be claimed

`uncertain`: https://pypi.org/project/uncertain

### Your PyPI username

`icorbrey`: https://pypi.org/user/icorbrey

### Reasons for the request

The package maintainer has no way to view source code or report issues publicly. The source appears to be hosted on a closed university server, inaccessible to the public. I believe this to invalidate the package's participation on PyPi. Additionally, I have spent the last month building and testing a package to deal with uncertain numeric values that I believe to be 1) more publicly accessible and maintainable and 2) functionally superior to the package in question. I have a test publish at https://test.pypi.org/project/uncertain where I made it available for testing, and had been intending to publish under the package name `uncertain` on the official index.

### Maintenance or replacement?

Replacement

### Contact and additional research

Again, the repository is completely inaccessible to the public, and people cannot report issues to the maintainer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @icorbrey, the first release of `uncertain` was 3 days before your request on the 17th of April 2021. While I understand you may have doubts over the author's practices regarding the accessibility of source code, there is nothing that warrants a PEP 541 request at this point in time, i.e. the project has not been abandonded and has valid functionality.

I suggest contacting the author via the email in the project page.
