### ISSUE TITLE
PyPI package size limit for splice-beakerx (150MB)

### ISSUE THREAD

**Issue by Ben-Epstein** [pypa/pypi-support#104]
Hello,

I'm requesting a size increase for splice-beakerx
https://pypi.org/project/splice-beakerx/
https://test.pypi.org/project/splice-beakerx/

The file size is about 112MB, so 150MB or 200MB should do.

Thank you!

**Comment by jamadden** [comment]
The limit for `splice-beakerx` has been set to 150MB on pypi.org and test.pypi.org
