### ISSUE TITLE
PEP 541 Request: pin

### ISSUE THREAD

**Issue by nim65s** [pypa/pypi-support#1043]
### Project to be claimed

`pin`: https://pypi.org/project/pin

### Your PyPI username

`Nim65s`: https://pypi.org/user/Nim65s

### Reasons for the request

- The latest 0.1rc1 release is 10 years old
- The latest activity on the home page is almost as old
- The latest activity on its plugin is almost as old

We would like to publish https://github.com/stack-of-tasks/pinocchio/ on PyPI. Pinocchio is already available on AUR, conda, homebrew, robotpkg, and ROS under this name, but on PyPI the `pinocchio`name [is not available](https://github.com/mkwiatkowski/pinocchio/issues/28).

So we would like to use `pin`, as in python, [we usually shortcut `import pinocchio as pin`](https://github.com/stack-of-tasks/pinocchio/search?q=%22import+pinocchio+as+pin%22)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/dustinlacewell/pin
https://github.com/dustinlacewell/pin-venv

### Contact and additional research

https://github.com/dustinlacewell/pin/issues/4
https://pypistats.org/packages/pinvenv

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dustinlacewell** [comment]
PyPI project has been deleted and should be available to claim.

**Comment by nim65s** [comment]
Thanks a lot !
