### ISSUE TITLE
PEP 541 Request: recommenders

### ISSUE THREAD

**Issue by anargyri** [pypa/pypi-support#1044]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/recommenders

### Your PyPI username

`USER_NAME`: https://pypi.org/user/recodevteam

### Reasons for the request

The project name cannot be found on the pypi index. It seems it has been registered by someone and then deleted. 
`pip install recommenders` doesn't work either and throws this error:
ERROR: Could not find a version that satisfies the requirement recommenders
ERROR: No matching distribution found for recommenders
`python3 -m twine upload  dist/*` fails with the error:
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'recommenders' isn't allowed. See https://pypi.org/help/#project-name for more information.

We would like to request the name "recommenders" as our team is responsible for the Recommenders open source GitHub repo (https://github.com/microsoft/recommenders). This repo provides utilities that enable the community to apply algorithms for recommendation systems and evaluate the results. It is being used by many engineers and data scientists in the recommendations community (it has about 1700 forks and 9600 stars).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/microsoft/recommenders

### Contact and additional research

It was not possible to find the name "recommenders" on past issues on pypa. There is a cached version of a project with this name on Google https://webcache.googleusercontent.com/search?q=cache:WmjzeeCclS0J:https://pypi.org/project/recommenders/1.0.6/+&cd=2&hl=en&ct=clnk&gl=uk
Based on the contact info I found on this cached page, I have emailed the author asking if the project is abandoned. 
There is no associated homepage on the cached project page and the description is very short, so it is not clear what the project was about.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @anargyri, the name `recommenders` was placed in the prohibited project names list by @pypa/warehouse-admins, I do not have the permissions to unlist it but an admin should be able to do so soon.

**Comment by anargyri** [comment]
> Hello @anargyri, the name `recommenders` was placed in the prohibited project names list by @pypa/warehouse-admins, I do not have the permissions to unlist it but an admin should be able to do so soon.

Thank you @yeraydiazdiaz

**Comment by ewdurbin** [comment]
This project has been created with the recodevteam User on PyPI as the Owner Role. You can now upload releases.
