### ISSUE TITLE
PEP 541 Request: wombat

### ISSUE THREAD

**Issue by RHammond2** [pypa/pypi-support#1045]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/wombat

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rhammond

### Reasons for the request

I emailed the original owner of the project and they readily deleted their project as it didn't go anywhere, but I am now receiving the following error when I try to upload the bones of project while I transfer an internal code base to its long-term, public-facing repository.

I am receiving the following error message despite the project being deleted and no longer showing on PyPI
```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'rhammond' isn't allowed to upload to project 'wombat'. See https://pypi.org/help/#project-name for more information.
```

### Maintenance or replacement?

Replacement, completely new project from a completely new owner.

### Source code repositories URLs

https://github.com/WISDEM/WOMBAT

### Contact and additional research

I emailed the owner and they responded very quickly and were happy to hand it over because the project for the original PyPI listing never got off the ground.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by RHammond2** [comment]
Is there anything else I should be doing for this?

**Comment by pradyunsg** [comment]
> I emailed the owner and they responded very quickly and were happy to hand it over because the project for the original PyPI listing never got off the ground.

The owner should be able to perform the transfer themself, via the "Manage Proejct" button that'll show up for the project, when they're logged into PyPI.

Is there a reason that the owner is unable to perform such a transfer?

**Comment by RHammond2** [comment]
Thanks for getting back! The original owner deleted the project, so I was under the impression that I'd be able to claim the name, or do they have to both delete and transfer the ownership?

**Comment by pradyunsg** [comment]
No, you can directly upload to it if they've deleted the project (which is different from deleting the releases).

**Comment by RHammond2** [comment]
Perfect, thank you, this information was all very helpful in getting the issue settled, thank you again!
