### ISSUE TITLE
PEP 541 Request: Transform

### ISSUE THREAD

**Issue by nhandel** [pypa/pypi-support#1047]
### Project to be claimed

`Transform`: https://pypi.org/project/Transform

### Your PyPI username

`nick_handel`: https://pypi.org/user/nick_handel

### Reasons for the request

Yes, this package appears to have been a test that was abandoned more than 3 years ago. There have been no additional commits since the initial test commit.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

This package will be replaced by a package currently hosted privately on GitHub under a different name that is being actively developed.

### Contact and additional research

<img width="1245" alt="Screen Shot 2021-04-24 at 6 49 28 PM" src="https://user-images.githubusercontent.com/5322454/115977523-e50edd00-a52d-11eb-9289-aae51416f444.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nhandel** [comment]
Still no response:
![Screen Shot 2021-05-25 at 12 45 35 PM](https://user-images.githubusercontent.com/5322454/119559136-21b13c80-bd57-11eb-88bd-8009459af2d6.png)

**Comment by nhandel** [comment]
Still nothing:
![Screen Shot 2021-06-02 at 12 57 57 PM](https://user-images.githubusercontent.com/5322454/120544325-294d9280-c3a2-11eb-8d48-765f0d48043e.png)

**Comment by yeraydiazdiaz** [comment]
The project seems to have very limited functionality, I will attempt contact with the owner to clarify their position regarding it and hopefully we will hear back soon.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by nhandel** [comment]
Thanks for your help!
