### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by Warcaith** [pypa/pypi-support#1051]
### PyPI Username

`trinary`

### Reason for request

Hello!

Would it be possible to change the username to start with an uppercase, "Trinary" instead of "trinary"?

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This is complete.
