### ISSUE TITLE
PEP 541 Request: wurl

### ISSUE THREAD

**Issue by nschloe** [pypa/pypi-support#1055]
### Project to be claimed

`wurl`: https://pypi.org/project/wurl

### Your PyPI username

`nschloe`: https://pypi.org/user/nschloe

### Reasons for the request

The user [airdge](https://pypi.org/user/airdge/) has claimed a few packages and uploaded empty ones. [This has already been reported by me.](https://github.com/pypa/pypi-support/issues/1053) Since removing one package instead of a whole range may be easier, I'm opening this request.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/nschloe/wurl

### Contact and additional research

Contacted the package owner by e-mail on April 27, 2021.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nschloe** [comment]
Closing as https://github.com/pypa/pypi-support/issues/1053 has been closed.

**Comment by nschloe** [comment]
Reopening as uploading a new package by the same name still seems to be disallowed?
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'wurl' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

**Comment by nschloe** [comment]
@ewdurbin The packages of the name-squatting pypi user airdge have been removed 5 weeks ago, but the repository names are still blocked. Is this intended?

**Comment by ewdurbin** [comment]
Yes. When we remove project names reported as typo squatting or dependency confusion we prohibit them from re-registration.

**Comment by nschloe** [comment]
So all the user's projects have been removed with typo-squatting? That's too bad. I really only wanted to publish [my own wurl](https://github.com/nschloe/wurl). Is there anything that can be done about it?

**Comment by legau** [comment]
I second this for `kanon` which was also squatted by the same user.

**Comment by yeraydiazdiaz** [comment]
@legau please open a separate PEP 541 request for `kanon`. I believe @pypa/warehouse-admins are able to release prohibited project names to users now?

**Comment by nschloe** [comment]
I don't care about this anymore, I renamed my project.

**Comment by yeraydiazdiaz** [comment]
Ok, thanks for letting me know.
