### ISSUE TITLE
PEP 541 Request: gasp

### ISSUE THREAD

**Issue by jelkner** [pypa/pypi-support#1056]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/gasp

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jelkner

### Reasons for the request

I am the high school computer science teacher who worked with a group of students to originate the gasp project back in 2007.  I am again working with my students this year to port gasp from Python 2 to Python 3, and to move it from wrapping Pygame to wrapping Tkinter.

The new version (https://codeberg.org/GASP/GASP_Tkinter) will be of use to introductory programming courses and correspond with the integrated lessons (https://codeberg.org/GASP/GASP_Lessons).

Having students be able to: "python3 -m pip install gasp --user" will be a huge help in making these materials accessible on Linux, Mac OS, and Windows.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://codeberg.org/GASP/GASP_Tkinter

### Contact and additional research

I am currently listed on the project as a maintainer (https://pypi.org/project/gasp/), but I do not have the permissions I need to update the project or the current maintainers list.

I have emailed James Hancock, who is the current author on the project.  He emailed back saying:

Hey! Great to hear from you all. 
How do I know where I still have ownership and on what account?
Happy to transfer it, I may need help figuring out where and how to do it.

Cheers,
James

I can forward you that email if you like.  We emailed him back, but haven't heard from him yet.  It has been 14 years since he touched this project, way back when he was a student.  Easiest path forward would be for me to be able to take over.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ambv** [comment]
Since you are already the maintainer of the project, it seems the problem is with being able to log in to pypi.org, right?

**Comment by jelkner** [comment]
I can login to pypi, @ambv, but I am not sure how to make changes to the project. I want to update the maintainer list, to remove folks long gone from the project and add those who are currently working on it.  Are you suggesting I should be able to do that as maintainer?

I will continue to investigate and then post again when I understand this better.

**Comment by ambv** [comment]
Yes, Jeff, when you log in you have a list of your projects:
<img width="1056" alt="Screenshot 2021-05-12 at 14 46 41" src="https://user-images.githubusercontent.com/55281/117977375-08f55f80-b331-11eb-82ff-9e4abc99ccd1.png">

You can then click "Manage" and add/remove collaborators for each project you're an owner of.

**Comment by jelkner** [comment]
Ah, @ambv, then we have identified the problem. My "Manage" button is greyed out and has a line through it.

![Screenshot from 2021-05-12 09-07-15](https://user-images.githubusercontent.com/819114/117980290-d08a5d00-b301-11eb-9b5e-e98b1936822f.png)

**Comment by kjcole** [comment]
@ambv @jelkner 

One possible source of the troubles, perhaps? 

The site listed as hosting the Homepage (http://dc.ubuntu-us.org/bazaar/gasp) is "nailed to the bloody perch", "pushing up the daisies", etc., etc. -- though there is an ancient capture of it at http://web.archive.org/web/20070716174331/http://dc.ubuntu-us.org/bazaar/gasp/?C=N;O=D

Does that trigger any sort of lockout when the Homepage disappears?

**Comment by jelkner** [comment]
The problem is that I am a maintainer, but not an owner of this package.  The owner, James Hancock, hasn't touched the project since 2007, is no longer working in IT, and has no interest in figuring out how to log in again here to change anything.  I believe we need to resolve this without him.

In the mean time we have created a new package, gasp3, and I filed another issue #1056, since now the confusion is we have a working gasp3 package and a broken gasp package.

We want to move gasp3 to gasp.

Thanks!

**Comment by yeraydiazdiaz** [comment]
Hello @jelkner, the `gasp` project has 3 owners, https://pypi.org/user/mattva01/, https://pypi.org/user/lfaraone/, and https://pypi.org/user/jhancock/ though you mention this last one is unavailable. Any one of them should be able to upgrade you to an owner, otherwise I would have to attempt contact with them to allow the transfer.

**Comment by jelkner** [comment]
Thanks, @yeraydiazdiaz !  I did not realize mattva01 was an owner.  I am in regular contact with him, so we can hopefully resolve this on our own with his help.

**Comment by mattva01** [comment]
Apologies, didn't realize I was still an owner either. Should be resolved.

**Comment by jelkner** [comment]
You rock, Matt!  I can now close this issue.
