### ISSUE TITLE
PEP 541 Request: scarf

### ISSUE THREAD

**Issue by parashardhapola** [pypa/pypi-support#1059]
### Project to be claimed

`scarf`: https://pypi.org/project/scarf

### Your PyPI username

`parashardhapola`: https://pypi.org/user/parashardhapola

### Reasons for the request

Name squatting.
The project is invalid and not being used. 
Reaching https://pypi.org/project/scarf/ throws a 404 error.
It appears that this project was either deleted by original author or this a simple case of name squatting.

I get following error when trying to upload using Twine
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'parashardhapola' isn't allowed to upload to project 'scarf'. See https://pypi.org/help/#project-name for more information.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/parashardhapola/scarf

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no releases and is therefore considered invalid, I will attempt contact with the owner letting them know of this fact and allow one week for replies before proceeding with the transfer.

**Comment by parashardhapola** [comment]
Hi @yeraydiazdiaz 

Thanks for following up on this. Let's see how this goes.

**Comment by yeraydiazdiaz** [comment]
The owner replied and the project has now been transferred.
