### ISSUE TITLE
Limit Request: KOTLIN JUPYTER KERNEL - 100MB

### ISSUE THREAD

**Issue by ileasile** [pypa/pypi-support#106]
**Project**. Kotlin Jupyter Kernel.
https://pypi.org/project/kotlin-jupyter-kernel/0.7.11/
https://test.pypi.org/project/kotlin-jupyter-kernel/0.7.11/

**Size of release**: 100Mb

**Which indexes**: both

**Reasons for the request**. It's Kotlin Jupiter Kernel and it bundles the whole kotlin compiler obviously. Please increase the upload limit

**Comment by jamadden** [comment]
The limit for kotlin-jupyter-kernel has been set to 100MB on pypi.org and test.pypi.org
