### ISSUE TITLE
PEP 541 Request: PyCo

### ISSUE THREAD

**Issue by Duplexes** [pypa/pypi-support#1061]
### Project to be claimed

`PyCo`: https://pypi.org/project/pyco

### Your PyPI username

`Duplexes`: https://pypi.org/user/Duplexes

### Reasons for the request

Hello,
I am requesting the package name  "PyCo" as it seems to empty and falls under your squatting policy. The project that I would like to publish under this name is a command-line python package to make console development easier.  

Thank you,
Duplexes

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Duplexes/pyco

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by Duplexes** [comment]
Thank you.

**Comment by yeraydiazdiaz** [comment]
@Duplexes, I cannot find a PyPI user `Duplexes`, could you please double check your username?

**Comment by Duplexes** [comment]
Should work now. Had the account setup incorrectly.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
