### ISSUE TITLE
PEP 541 Request: ctrl-benchmark

### ISSUE THREAD

**Issue by TomVeniat** [pypa/pypi-support#1062]
### Project to be claimed

`ctrl-benchmark`: https://pypi.org/project/ctrl-benchmark/

### Your PyPI username

`TomVen`: https://pypi.org/user/TomVen

### Reasons for the request

The project currently uploaded under the name `ctrl-benchmark` does not contain any code (only placeholder files) and its homepage (https://github.com/aaaditisinghhhh/) does not exist. I think it is squatting the name since It has been created recently, right around the time we started to communicate about it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

This project would be replaced by https://github.com/facebookresearch/CTrLBenchmark.

### Contact and additional research

[The maintainer](https://pypi.org/user/ashishsingh/) only has one other project `pydaemon-runner`, which may also be name-squatting since it has the same description `xxx is a amazing package for data handling`, the same version 4.9.0, the same non-existent homepage and the archive contain the same kind of placeholders.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no funcionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
