### ISSUE TITLE
PEP 541 Request: til

### ISSUE THREAD

**Issue by kamyar** [pypa/pypi-support#1063]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/til

### Your PyPI username

`USER_NAME`: https://pypi.org/user/kamyar

### Reasons for the request

When I try to upload to `til` package it fails although pypi page returns 404 : https://pypi.org/project/til/
I specifically get
```
  HTTP Error 403: The user 'kamyar' isn't allowed to upload to project 'til'. See https://pypi.org/help/#project-name for more information.
```

I checked my credentials and they work for another project.
**The justification is:** It does not seem there is an active project project on pypi that uses this name and I want it to be easy to remember for ease of use and would rather use `til` instead of something like` til-cli` which is less user friendly.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Will be replace by: https://github.com/kamyar/til
Still work in progress though, just started it.

### Contact and additional research

Tried searching in Github for a project that has `til` in pyproject.toml or setup.py , did not find any project that uses it.
[https://pypi.org/pypi/til/json](https://pypi.org/pypi/til/json) also expectedly does not have any information.

Not sure how else to try to contact who has it.

[1] https://github.com/search?q=til+filename%3Apyproject.toml&type=code
[2] https://github.com/search?q=til+filename%3Asetup.py&type=code

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @kamyar, there is a `til` project in PyPI which contains no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by kamyar** [comment]
@yeraydiazdiaz thanks a lot, would appreciate it.

**Comment by kamyar** [comment]
@yeraydiazdiaz did you hear back from the owner of the package?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
