### ISSUE TITLE
PEP 541 Request: Augur

### ISSUE THREAD

**Issue by sgoggins** [pypa/pypi-support#1072]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/Augur/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/computationalmystic

### Reasons for the request

I am the owner of the Augur project at https://github.com/chaoss/augur 

A former student created the package with the long term goal of doing a pip install.  We are now ready to do that, but we need to regain access.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/chaoss/augur 

### Contact and additional research

Project originally under https://github.com/OSSHealth/augur and
https://github.com/OSSHealth/GHData 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Seems the project was placed under an admin controlled user a couple of years ago. Transfer complete.
