### ISSUE TITLE
PEP 541 Request: prototypes

### ISSUE THREAD

**Issue by kprzybyla** [pypa/pypi-support#1073]
### Project to be claimed

`prototypes`: https://pypi.org/project/prototypes

### Your PyPI username

`kprzybyla`: https://pypi.org/user/kprzybyla

### Reasons for the request

The name `prototypes` is not used anywhere on `pypi.org`. The page for `prototypes` package does not exists and pip cannot find any package to download when using this name. When I tried to upload my package with this name I get following error:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'prototypes' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

Since there is already a package named `prototype` I guess that the name `prototypes` should also be available and I would like to claim it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My package source code: https://github.com/kprzybyla/prototypes

### Contact and additional research

As far as I searched there is no indication that such package ever existed. There is no trace of it on `https://webcache.googleusercontent.com` or any other archive page.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
`prototypes` was placed in the prohibited project names list earlier this year, @pypa/warehouse-admins should be able to release it.

**Comment by ewdurbin** [comment]
Project name released to the `kprzybyla` User on PyPI.
