### ISSUE TITLE
Limit Request: qt-applications - 135 MB

### ISSUE THREAD

**Issue by altendky** [pypa/pypi-support#1074]
### Project

https://pypi.org/project/qt5-applications/

### Does this project already exist?

- [X] Yes

### Size of release/project

135MB

### Which indexes

PyPI

### Reasons for the request

qt-applications, the lowest layer of the pyqt5-tools family of packages, contains the actual Qt applications.  They are big.  Linux and Windows wheels both fit under the 100MB limit, but the new macOS wheels are 135MB each.  I already exclude the extra-massive web engine related applications, but it would be nice to not have to cut more out of the macOS wheels.

Thank you for your consideration.

Cheers,
-kyle

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by altendky** [comment]
Several files are still pretty close to the 100MB limit, but I did get under it.  I'll leave this open in case you are willing to pre-emptively bump the size to give me some breathing room.  I don't have anything I plan to add in, just nice to have it available when something comes up.  Or, just close this as resolved-by-requester.  `:]`  Either way, thanks for your time and for the service.

**Comment by di** [comment]
I've set the upload limit for `qt5-applications` to 200 MB on PyPI.
