### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SyedAhkam** [pypa/pypi-support#1075]
### PyPI Username

`SyedAhkam`

### Reason for request

I lost access to my account after my phone decided to factory reset itself for no reason.

These points could help verifying my ownership over the account:

- My github account `SyedAhkam` had the same username.
- I had one of my projects on pypi "discord-bot-generator" (code is on my github)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by SyedAhkam** [comment]
Could anyone please look into this? I needed to publish a new package but I can't until I have my account back..

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
