### ISSUE TITLE
PEP 541 Request: ogr2osm

### ISSUE THREAD

**Issue by roelderickx** [pypa/pypi-support#1077]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ogr2osm

### Your PyPI username

`USER_NAME`: https://pypi.org/user/roelderickx

### Reasons for the request

I will be the new maintainer as discussed in https://github.com/pnorman/ogr2osm/issues/58 and I am in the process of moving all links to my branch. I would also like to maintain a new PyPI package for this project.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/roelderickx/ogr2osm

### Contact and additional research

The project was never uploaded to PyPI before, but its name was added to the prohibited project names list as per #355. Please unblock this for me.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by roelderickx** [comment]
cc: @encukou, @di

**Comment by encukou** [comment]
This is legit, please unblock `ogr2osm`.
Thank you!

**Comment by yeraydiazdiaz** [comment]
@pypa/warehouse-admins should be able to release the project name

**Comment by roelderickx** [comment]
Can anyone of @pypa/warehouse-admins have a look please?

This namesquatting by Fedora is done with the best intentions, but not if it takes 3 months or more to perform transfers.

**Comment by encukou** [comment]
If it was just namesquatting, I (or someone from Fedora) would be able to transfer the name right away.
I've [posted](https://discuss.python.org/t/pypi-as-a-project-repository-vs-name-registry-a-k-a-pypi-namesquatting-e-g-for-fedora-packages/4045/24?u=encukou) on the original discussion about how to handle this. The current process of waiting for me **and** the PyPI admins is unfortunate.

**Comment by di** [comment]
I've released 'ogr2osm' to 'roelderickx', sorry for the delay.

**Comment by roelderickx** [comment]
Many thanks @encukou and @di, the package is uploaded succesfully.
