### ISSUE TITLE
PEP 541 Request: tito

### ISSUE THREAD

**Issue by FrostyX** [pypa/pypi-support#1079]
### Project to be claimed

`tito`: https://pypi.org/project/tito

### Your PyPI username

`FrostyX`: https://pypi.org/user/FrostyX

### Reasons for the request

When trying to access the `tito` project directly via https://pypi.org/project/tito it returns 404 therefore it seems that the project either doesn't exist or is claimed but doesn't have any sources.

As a maintainer of [rpm-software-management/tito][upstream], I want to publish the project to PyPI but get

    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
    The name 'tito' isn't allowed. See https://pypi.org/help/#project-name for more information

I believe this package name doesn't conflict with the standard library and that it isn't prohibited by administrators. The only remaining reason seems to be

> The project name has been registered by another user, but no releases have been created.

Therefore I contacted the former maintainer and original author of the [rpm-software-management/tito][upstream] project and we are not aware of anyone claiming this name on PyPI.

Since it is not used, I would like to ask you to transfer it to me.

[upstream]: https://github.com/rpm-software-management/tito/

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/rpm-software-management/tito

### Contact and additional research

Well, I don't know who the current _author_ is so I could only ask @dgoodwin as the former upstream maintainer, who hasn't claimed the project name, so we reached a dead end.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by roelderickx** [comment]
@encukou This is also because of #355

**Comment by yeraydiazdiaz** [comment]
@pypa/warehouse-admins should be able to release this project name

**Comment by encukou** [comment]
@dl, can you unblock this one too?

**Comment by roelderickx** [comment]
> @di, can you unblock this one too?
> 
> (Edit: `@dl`, Sorry for the typo!)

When mentioning someone after an edit, they do not receive notifications IIRC.
Can you have a look @di ? This is also a Fedora blocked package.

**Comment by di** [comment]
I've released `tito` to `FrostyX`.
