### ISSUE TITLE
Transfer ownership of Flask and Jinja2 on Test PyPI

### ISSUE THREAD

**Issue by davidism** [pypa/pypi-support#108]
I'm a core maintainer of the Pallets projects (@pallets), including Flask and Jinja (Jinja2). I would like to use **Test PyPI** to test out some packaging issues I'm working on, but these packages are owned by random users, not any of the maintainers. Please transfer ownership of these two projects to me. Thank you.

`PROJECT_NAME`: https://test.pypi.org/project/Flask
`PROJECT_NAME`: https://test.pypi.org/project/Jinja2
`USER_NAME`: https://test.pypi.org/user/davidism

**Comment by davidism** [comment]
I'm seeing other issues posted since this one get responses. Is there something else I need to provide to get this addressed?

**Comment by jamadden** [comment]
I'm not finding anywhere that guarantees anything about TestPyPI having the same packages and ownerships as production PyPI. I *do* see warnings about it [*not* having the same packages](https://packaging.python.org/tutorials/packaging-projects/#installing-your-newly-uploaded-package), and that [the database may be purged](https://packaging.python.org/guides/using-testpypi/#registering-your-account), leading to user accounts (and ownerships!) going missing. It seems that things are pretty laissez faire over there; even if ownership was changed now, it would be reset at the next database cleanup.

Perhaps to test you could just upload with a different package name?

**Comment by davidism** [comment]
There's precedent within the last month: #94 paramiko. cc @di

**Comment by davidism** [comment]
And given that the current versions from the Flask squatter are from 2016, I don't think a database purge affected that any time recently.

**Comment by ewdurbin** [comment]
Hi! Thanks for the mention.

If the maintainer of a project on pypi.org requests the project on test.pypi.org, it's certainly a valid request. The simplest criteria that we could have for verification is that the username and verified email addresses match across the instances.

I've verified the above and issued this transfer.

**Comment by davidism** [comment]
Thanks for the help, happy new year! :-)
