### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by xguo-prestolabs** [pypa/pypi-support#1080]
### PyPI Username

`xguo`

### Reason for request

I have lost access to my email address associated this my PYPI account, and I aslo forget my password.
I would like to use a new email address. Please help me.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I have attempted to contact the existing Primary email address associated with the account. If that email bounces or is not responded to in 7 days, we will proceed with further account recovery steps.
