### ISSUE TITLE
PEP 541 Request: `scenario`

### ISSUE THREAD

**Issue by diegoferigo** [pypa/pypi-support#1082]
### Project to be claimed

`scenario`: https://pypi.org/project/scenario

### Your PyPI username

`dgferigo`: https://pypi.org/user/dgferigo

### Reasons for the request

- The [existing project](https://pypi.org/project/scenario) has only one pre-alpha python-2 release uploaded in October 2016
- The only release contains no code and it cannot be installed in any system.
- The corresponding [github repository](https://github.com/corrni/scenario) no longer exists.
- The [documentation website](https://scenario.readthedocs.io/) is not reachable.
- The [author](https://github.com/corrni/) has no other projects in PyPI and he does not seem very active in GitHub.

I would like to use `scenario` for the new package that derives from the split from [gym-ignition](https://github.com/robotology/gym-ignition). Please check the pending https://github.com/robotology/gym-ignition/pull/346 and the new [`scenario` folder](https://github.com/robotology/gym-ignition/tree/feature/split_scenario/scenario) for further details.

Edit: I'm not sure how permissions transfer to TestPyPI, but also there I cannot upload the `scenario` package even though there is no other project with the same name. Maybe it checks the regular PyPI first and prevents other users to upload a package with the same name? (it would make sense!) In the meantime, to show the result, I uploaded the sdist to [`scenario1`](https://test.pypi.org/project/scenario1/).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://pypi.org/project/scenario/

### Contact and additional research

cc @corrni as second mean of contact. I already sent an email to iam@corrni.io.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by diegoferigo** [comment]
Is there any way to speed up the process for requests like this one? The existing project has only one alpha release 5 years old, no repository, no documentation, no website and, overall, the PyPI package cannot be installed since there are no files. I'm aware that that this process is mainly done by volunteers in their free time, much appreciated, however it would be really helpful if the most clear cases could be processed at a different speed with respect of packages that could still have some possible (even if unlikely) user base and double checks are necessary. cc @yeraydiazdiaz

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no releases and is therefore considered invalid. I will now attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by diegoferigo** [comment]
Awesome, thanks @yeraydiazdiaz!

**Comment by yeraydiazdiaz** [comment]
@diegoferigo it appears the owner deleted this project and did not notify me about it, you should be able to publish your project now.

**Comment by diegoferigo** [comment]
@yeraydiazdiaz yes I managed to upload to PyPI! Thanks a lot. Would it be possible to also get the same package in TestPyPI: [`scenario`](https://test.pypi.org/project/scenario/)? I'm reopening the issue for this reason.

**Comment by yeraydiazdiaz** [comment]
@diegoferigo there is no project `scenario` in TestPyPI at the moment and it's not in the prohibited project names list, you should be able to upload it.

**Comment by diegoferigo** [comment]
@yeraydiazdiaz Mmh ok something's going on, when I commented (few hours ago) the project was there. I still have the terminal I used to upload the package open, and I was receiving the following message:

```
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
The user 'dgferigo' isn't allowed to upload to project 'scenario'. See https://test.pypi.org/help/#project-name for more information.
```

Now the project is available, and I managed to upload it also to TestPyPI.

**Comment by yeraydiazdiaz** [comment]
The owner of the project deleted it on 2021-07-21 09:31:22.560408, maybe a reaction to you posting your comment or just a coincidence 🙂

**Comment by diegoferigo** [comment]
Than, thanks to the silent @corrni for that!
