### ISSUE TITLE
PEP 541 Request: `collie`

### ISSUE THREAD

**Issue by nathancooperjones** [pypa/pypi-support#1091]
### Project to be claimed

`collie`: https://pypi.org/project/collie/

### Your PyPI username

`shoprunner_data_science`: https://pypi.org/user/shoprunner_data_science

### Reasons for the request

Based on the discussion in issue #791 and reply from @yeraydiazdiaz, I am opening this separate issue specifically for the `collie` library currently uploaded to PyPI. 

Its author, `Collie` seems to be squatting on the names for 118 projects, all of which have been uploaded to PyPI in the span of a few months with the same naming scheme and all empty packages. 

`collie 0.0.0.0.0.0a0.dev20210120`, which was released January 19th, 2021 as an empty library, has no description nor repository, and the author has not provided an email address or any contact information. Since its initial release four months ago, the library has not been updated, meaning it is still an empty project. 

One month ago, on April 13th, 2021, the ShopRunner data science team open sourced our internal deep learning recommendations library (named `collie-recs` on PyPI) and have since made five separate releases (with more on the way) with fixes and improvements. 

It would be fantastic if we could replace the current `collie` library with ShopRunner's, officially taking over the name `collie`. Thank you!! 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

For `collie_recs`: 
* PyPI: https://pypi.org/project/collie-recs/ 
* GitHub: https://github.com/ShopRunner/collie_recs 
* Documentation: https://collie.readthedocs.io/ 

### Contact and additional research

I have been unable to contact the user `Collie` since they left no contact information in their PyPI account description. I have not been able to find a potential `collie` repo online that could match the one uploaded to PyPI. Since making issue #791 about the name squatting on so many repos by this user, they have not responded to that either. I'm not sure we will be able to get ahold of `Collie` in any way. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
