### ISSUE TITLE
PEP 541 Request: `ycm`

### ISSUE THREAD

**Issue by diegoferigo** [pypa/pypi-support#1096]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ycm

### Your PyPI username

`USER_NAME`: https://pypi.org/user/dgferigo

### Reasons for the request

- The [existing project](https://pypi.org/project/ycm/) is marked with alpha status and only supports the deprecated Python 2.
- Last releases have been uploaded in August 2017.
- The project's url cannot be reached.
- I couldn't find any git repository.
- It is the PyPI only package owned by the author.

I would like to use `ycm` for the new package proposed in https://github.com/robotology/ycm/pull/380.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The new `ycm` package would refer to https://github.com/robotology/ycm.

### Contact and additional research

I already sent an email to jack@d5research.com.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @diegoferigo, I will now start the reachability process for your request, hopefully we will hear back from the owner and proceed with the transfer.

**Comment by diegoferigo** [comment]
Thanks @yeraydiazdiaz!

**Comment by diegoferigo** [comment]
Ow I just realized I had to close this issue (I have other requests pending and it got lost in the crowd). Waiting this issue to be processed, the owner of the package replied and he told me that he's still using the package. For this package, I decided to use the `ycm-cmake-modules` as alternative. I guess I can close this issue. I had to do it after I received response, sorry for the noise.
