### ISSUE TITLE
Issue: Limit Request: ggtools 1.5 - 80.8MB

### ISSUE THREAD

**Issue by lcx366** [pypa/pypi-support#110]
**Project**

ggtools 1.5, https://pypi.org/project/ggtools/

**Size of release**

80.8MB

**Which indexes**

PyPI

**Reasons for the request**

The ggtools package is an archive of scientific routines that can be used to handle the GRACE(Gravity Recovery and Climate Experiment) and GRACE-FO(Follow-on) GSM data(RL06 Level-2 monthly solutions) and GLDAS grid data. For more details, please refer to GGTOOLS in GitHub.

The package contains two large files. one is the global terrain relief data with a resolution of 5'(about 18.7MB), and the other is eight GRACE DDK filter matrices (about 78.4MB), therefore hitting the upload file size limit. I expect to apply for more space so that this data can be used by this package, and I appreciate your approval.

**Comment by jamadden** [comment]
The limit for ggtools has been set to 100MB on pypi.org
