### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JnyJny** [pypa/pypi-support#1103]
### PyPI Username

`jnyjny`

### Reason for request

I am an idiot and have forgotten what 2FA method I chose months ago and have no idea how where I might have saved recovery codes (honestly I am not a fan of TOTP but I am bound and determined to learn a new trick). I have checked Authy, Google Authenticator and Duo Mobile but my PyPI account is nowhere to be found. I am very sorry to impose and grateful for your help. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
