### ISSUE TITLE
PEP 541 Requests for projects owned by user `etingof`

### ISSUE THREAD

**Issue by yeraydiazdiaz** [pypa/pypi-support#1104]
### Project to be claimed

See below

### Your PyPI username

`inexio`: https://pypi.org/user/inexio

### Reasons for the request

Grouping of 13 PEP 541 requests for projects:

- pysnmp-mibs
- pysnmp-apps
- pysnmpcrypto
- snmpfwd
- snmpreceiver
- snmpdiscoverer
- snmpresponder
- pysmi
- snmpsim-data
- snmpclitools
- pyasn1
- pyasn1-modules
- pysnmp

All of them owned by the same user.

### Maintenance or replacement?

Replacement

### Contact and additional research

Created on behalf of @LostBoi to avoid attempting contact with the owner 13 times separately.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by tiran** [comment]
Ilya Etingof (@etingof) is a co-worker of mine. His manager told me that Ilya is unavailable for personal reasons. He has been unable to respond for a while. I'm confident that he will be back in the future.

Please do **not** transfer ownership of his packages away from Ilya. I suggest that you keep Ilya as the owner of the PyPI packages and only add additional maintainers.

I also like to point out that Ilya's packages are used in security critical infrastructure. For example ``pyasn1`` is a core dependency of ``python-ldap``, which I co-maintain. python-ldap used by OpenStack, FreeIPA, Zimbra, Keycloak plugin and more to provide enterprise authentication. SNMP is typically used in enterprise environments to control and monitor hardware like routers and switches. I'm slightly worried that package ownership is requested by a new user account. https://pypi.org/user/inexio was created less than a year ago.

**Comment by yeraydiazdiaz** [comment]
Thanks for looking into this @tiran.

Given the projects are security related and are dependencies of other very popular projects (e.g. https://github.com/mpdavis/python-jose/) I don't feel comfortable transferring ownership or adding maintainers at this point in time.

This can be revisited at a later point if there's a more solid community effort for maintenance ideally blessed by Ilya. If unfortunately Ilya is not able to lead the hand over I would even prefer these projects not be transferred at all and have the dependant project migrate naturally to forks with different names since there's simply too many dependant project that can be affected.
