### ISSUE TITLE
PEP 541 Request: threedb

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [pypa/pypi-support#1105]
### Project to be claimed

`threedb`: https://pypi.org/project/threedb

### Your PyPI username

`GuillaumeLeclerc`: https://pypi.org/user/GuillaumeLeclerc/

### Reasons for the request

Here are the reasons I think this project has been abandoned:

- No commit since 2017
- No issues since 2017
- 0 dependent packages
- 0 dependent repositories
- No stars on the github repository
- No forks
- All the commits happened within a 2 weeks window
- Out of the two github accounts  that did commits on this repo (which seem to point to the same individual):
    - One has deleted his account
    - The other has not been active on github since early 2018

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/3db/3db

### Contact and additional research

- The author did not indicate an email address on the pip package
- I opened an issue on the original Github repository but I don't really expect and answer from an account with no activities in the past 4 years.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @GuillaumeLeclerc, I will attempt to contact @EvgenyAK starting the reachability process, hopefully we will hear back from him soon and proceed with the transfer.

**Comment by GuillaumeLeclerc** [comment]
Thank you!!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
