### ISSUE TITLE
PEP 541 Request: sirius

### ISSUE THREAD

**Issue by Jan-Willem** [pypa/pypi-support#1106]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/sirius

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jwsteeb

### Reasons for the request

Invalid projects: name squatting. The project has a single release on Feb 22, 2015, which is empty and has no description. Furthermore, the project home page http://www.hmesoprograming.com/ is offline. 

### Maintenance or replacement?

Replacement

### Contact and additional research

I tried to download the package and got "No matching distribution found for sirius". 
There is no matching project on github. 
There is no cached version of the project website http://www.hmesoprograming.com/.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt to contact the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
