### ISSUE TITLE
PEP 541 Request: pisi

### ISSUE THREAD

**Issue by examachine** [pypa/pypi-support#1107]
### Project to be claimed

`pisi`: https://pypi.org/project/pisi

### Your PyPI username

`examachine`: https://pypi.org/user/examachine

### Reasons for the request

Hi there,

I'm the original author and maintainer of the pisi package manager project. Somebody created a pisi package with a fake email address (the email name is a joke in Turkish) and a high version number (999.999), please remove this fraudulent package because we will upload the releases here.

Please see: https://github.com/examachine/pisi

Best Wishes,

Eray

On behalf of PISI and pisi linux projects.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/examachine/pisi

### Contact and additional research

It is an empty package, it has nothing in it. Somebody uploaded it as an apparent "joke" but it looks more like an attempt to hijack the name. I'm sorry to have you deal with this, there are irrational people.

Author can't be contacted, the fake email bounces, also uses a fake name apparently.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by friberk** [comment]
Related with https://github.com/pypa/pypi-support/issues/1109

**Comment by examachine** [comment]
Can you please take urgent  action? There is **nothing** in this package. And the author does  not exist.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
