### ISSUE TITLE
PEP 541 Request: pypi-release

### ISSUE THREAD

**Issue by jparise** [pypa/pypi-support#1108]
### Project to be claimed

https://pypi.org/project/pypi-release/

### Your PyPI username

https://pypi.org/user/jparise/

### Reasons for the request

`pypi-release` is a Pinterest open source project: https://github.com/pinterest/pinrepo

... but the only named owner of the project on PyPI is no longer an employee, and I (as a current Pinterest employee) would like to take over maintenance of the project.

I'm happy to provide any proof, etc. that's appropriate to facilitate the request. You can also note that my PyPI account has an active, verified `pinterest.com` email address.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/pinterest/pinrepo

### Contact and additional research

The listed maintainer is no longer a Pinterest employee, and we have not been able to reach them privately.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by varunkuar8789** [comment]
Product Researcher
