### ISSUE TITLE
pypi.org/user/deleted-user/ is name squatting or creating bad faith packages

### ISSUE THREAD

**Issue by abht** [pypa/pypi-support#111]
pypi.org/user/deleted-user/ has packages that are clearly not created in good faith. Aside from the questionable package names, each package is either empty or is nothing more than an empty template uploaded. 

The large number of packages listed suggests this is an attempt to grab names of interest for now. Currently, not an active security issue, but could be later on if some packages (e.g. rapidjson) are maliciously updated.

Please remove these packages and ban the user.

**Comment by yeraydiazdiaz** [comment]
Hello @abht, thank you for noticing and raising this issue.

I believe `deleted-user` is a fake user under the control of the administrators that is made owner of all dubious projects.

I will close this issue now but feel free to comment if you have any further questions.
