### ISSUE TITLE
PEP 541 Request: connectome

### ISSUE THREAD

**Issue by maxme1** [pypa/pypi-support#1110]
### Project to be claimed

`connectome`: https://pypi.org/project/connectome

### Your PyPI username

`memax`: https://pypi.org/user/memax

### Reasons for the request

According to `PEP 541` the project is clearly invalid (name squatting): 

- it didn't receive any updates for more than a year
- it only contains an `__init__.py` file with `print('Hello')` inside.
- moreover, by inspecting other projects by the same author, it becomes obvious that they all were automatically generated

Our lab (NeuroML) is developing a library for datasets management via directed acyclic graghs, hence the name: NeuroML + graphs = connectome. The project is maintained for almost a year, and we would love to publish it to pypi.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Our project: https://github.com/neuro-ml/connectome
Current project from pypi: not available

### Contact and additional research

A few months ago I found the repository [here](https://github.com/LinxiFan?tab=repositories), but apparently at this moment it is deleted/private. From the repo's commits I managed to get the author's email and contacted him ~3 months ago, but didn't receive any response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by maxme1** [comment]
Hello. Thanks!

**Comment by maxme1** [comment]
The owner responded to my email. It turns out it got marked as spam :slightly_smiling_face: 
The previous project is deleted and I managed to claim the name.
@yeraydiazdiaz thanks for your help!

**Comment by yeraydiazdiaz** [comment]
Great, thanks for letting me know @maxme1
