### ISSUE TITLE
PEP 541 Request: pylibxc

### ISSUE THREAD

**Issue by susilehtola** [pypa/pypi-support#1116]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pylibxc

### Your PyPI username

`USER_NAME`: https://pypi.org/user/susilehtola

### Reasons for the request

I am a lead author of the libxc project
https://gitlab.com/libxc/libxc/
and pylibxc is the name of our Python backend.

I was just informed by @mfkasim1 that the package name "pylibxc" is blocked in PyPi, so he had to package libxc and pylibxc under the name pylibxc2
https://pypi.org/project/pylibxc2/

We in the libxc development team (myself and @hyllios) do not know who has registered the name "pylibxc", and would therefore request that the name be transferred so that @mfkasim1's branch can have official status.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://gitlab.com/libxc/libxc/

### Contact and additional research

We have no idea who the current owner is, since the repository has not been created.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by roelderickx** [comment]
@encukou This is also because of #355

**Comment by susilehtola** [comment]
I am also the maintainer of libxc and pylibxc in Fedora.

**Comment by encukou** [comment]
Indeed. Please free up pylibxc for @mfkasim1. Thank you!

**Comment by yeraydiazdiaz** [comment]
The name `pylibxc` was placed in the prohibited project names list, @pypa/warehouse-admins could you please release it to @susilehtola ?

**Comment by ewdurbin** [comment]
released.
