### ISSUE TITLE
Lost 2FA

### ISSUE THREAD

**Issue by cybiere** [pypa/pypi-support#112]
Hi !
My phone with my authenticator was stolen, so I have no way to access my account back... Of course I don't have backup codes because that would be too easy... I've read in https://github.com/pypa/warehouse/issues/5758 that I had to create a new issue, so here it is :)
Thanks !

**Comment by ewdurbin** [comment]
Hello @cybiere, please email ernest@python.org from the primary email address associated with your PyPI user account.

**Comment by cybiere** [comment]
Just sent it ! I hope it won't end up in your spams ;)

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
