### ISSUE TITLE
Limit Request: spacy - 20 GB (in total)

### ISSUE THREAD

**Issue by adrianeboyd** [pypa/pypi-support#1121]
### Project

spacy, https://pypi.org/project/spacy

### Does this project already exist?

- [X] Yes

### Size of release/project

20 GB (in total)

### Which indexes

PyPI

### Reasons for the request

spaCy is a library for advanced Natural Language Processing in Python and Cython with releases going back to 2015 on PyPI. Primarily as a result of adding wheels to releases starting in 2019, the project has reached its total project size limit of 10 GB.

The sdist and individual wheels are not particularly large (~10 MB each), but with 12 wheels per release currently and plans to increase the number of supported architectures and versions of Python in the future, each release will be ~150-200 MB total.

An increase to 20 GB would allow us to continue at the current rate of ~2 releases per month for 2+ years in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total size limit for `spacy` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
