### ISSUE TITLE
Limit Request: PyKaldi - 500 MB

### ISSUE THREAD

**Issue by Alienmaster** [pypa/pypi-support#1122]
### Project

https://pypi.org/project/PyKaldi/

### Does this project already exist?

- [X] Yes

### Size of release/project

260

### Which indexes

PyPI

### Reasons for the request

The PyKaldi project is located here: https://github.com/pykaldi/pykaldi .
PyKaldi is a Python scripting layer for the Kaldi speech recognition toolkit. It provides easy-to-use, low-overhead, first-class Python wrappers for the C++ code in Kaldi(www.kaldi-asr.org) and OpenFst libraries

Due to the libraries it is difficult to get under the 100MB file limit (Google CLIF, protobuf, Kaldi).

The project has a new maintainer @bmilde and our goal is to make the project more easily accessible to more developers.

Best wishes,
Robert

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `PyKaldi` to 300 MB on PyPI for now, please make a new request if you need a higher limit in the future.

**Comment by Alienmaster** [comment]
Hi,
i made a mistake by measuring the size of the Wheel. The linuxx64 Wheel is 260MB and the manylinux Wheel is 330MB big as you can see here: http://ltdata1.informatik.uni-hamburg.de/pykaldi_tmp/ .

An increase of the Releases up to 400MB would be great.

Best wishes,
Robert
