### ISSUE TITLE
PEP 541 Request: geckopy

### ISSUE THREAD

**Issue by carrascomj** [pypa/pypi-support#1124]
### Project to be claimed

`geckopy`: https://pypi.org/project/geckopy

### Your PyPI username

`ginkgodev`: https://pypi.org/user/ginkgodev

### Reasons for the request

There was an agreement with the maintainers @BenjaSanchez and @IVANDOMENZAIN to transfer the namespace to https://github.com/ginkgobioworks/geckopy, whereas there would not be an interest in maintaining the old one.

t was not entirely clear to me from the PEP541 if this should be done this way or we could just remove the old one and upload the new one.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Old package hosted at https://github.com/SysBioChalmers/GECKO/tree/master/geckopy
New Package hosted at https://github.com/ginkgobioworks/geckopy

### Contact and additional research

The current owners agreed to the replacement.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by BenjaSanchez** [comment]
I agree with this!

**Comment by yeraydiazdiaz** [comment]
@BenjaSanchez as an owner you can to transfer the project to `ginkgodev` yourself in https://pypi.org/manage/project/ginkgodev/collaboration/

**Comment by BenjaSanchez** [comment]
@yeraydiazdiaz thanks for clarifying this! This issue can then be closed.

@carrascomj I have added you and @ginkgodev as maintainers in the project, I would suggest to start "fresh" with version 3.0.0, as it probably breaks BC and it would be nice if any old users of geckopy want to access versions 2.0.2 and older.

**Comment by yeraydiazdiaz** [comment]
Thank you @BenjaSanchez
