### ISSUE TITLE
PEP 541 Request: sleepy

### ISSUE THREAD

**Issue by cbrnr** [pypa/pypi-support#1126]
### Project to be claimed

`sleepy`: https://pypi.org/project/sleepy

### Your PyPI username

`cbrnr`: https://pypi.org/user/cbrnr

### Reasons for the request

This project has been abandoned. We are currently developing a Python package for sleep classification based on heart rate, and `sleepy` would be the perfect name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

We're sorting out the open source license, and once that's done I can provide the URL to the public GitHub repo.

### Contact and additional research

I tried to contact the current owner twice via email (November 2, 2020 and May 25, 2021), but received no response. The current package contains only one initial upload (dating back to May 13, 2011) and no further updates. It is very likely that the code will not work on recent Python versions. Furthermore, the [download statistics](https://pypistats.org/packages/sleepy) indicate that this package is very likely not used. Also, the source code doesn't seem to be hosted anywhere.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @cbrnr, I will start the reachability process for this project. Hopefully we will hear back from the owner and proceed with the transfer.

**Comment by helixbass** [comment]
Hi, first of all the description of contact made with me (the package author) is not accurate at least from my perspective - someone who either is @cbrnr or presumably a colleague reached out to me at one point and I replied and was considering letting them have the package name, but I didn't "pull the trigger" - I shouldn't have to defend my reasons but that package represents an interesting step forward in my history as a developer (and I'm proud of the clever double-pun on "RESTful"/"sleepy"/"Py", which is a much more clever usage of the name than the rather literal "sleep software" meaning that these guys so desperately crave this package name for). Then the contact attempts he's describing were multiple attempts to re-contact me which I consider a bit egregious given that I had in fact replied initially so clearly was aware of the request

So back off, stop asking, thx

**Comment by cbrnr** [comment]
@helixbass let's all stay friendly here, OK? I contacted you twice via email from my work account (which has my full name in it) on the two dates mentioned in my first comment. I never received a reply from you (and yes, I did check my junk folder). Therefore, I don't understand which "multiple attempts to re-contact" you are referring to. Second, claiming a package name solely for the purpose of being a clever pun is probably not sufficient if the project has not been updated and used in 10 years. That's basically name squatting. But I'll let the folks from PyPI make the decision here.

**Comment by helixbass** [comment]
> Therefore, I don't understand which "multiple attempts to re-contact" you are referring to

Ok looking back at the request I replied to, it was from "Caglar Cakan" - perhaps it happened to be an unrelated group from the Germanic world developing sleep-related software in Python that wanted to use that name

> Second, claiming a package name solely for the purpose of being a clever pun is probably not sufficient if the project has not been updated and used in 10 years

That is not _solely_ my grounds for "claiming" it (really, you're the one trying to "claim" it, not me). I still use this package for web projects that I maintain. I can run an old version of it against Python 2.x for as long as I want, it works fine. Package indexes aren't just for popular, well-maintained projects

**Comment by yeraydiazdiaz** [comment]
Since @helixbass has been reached and stated his intention to keep the project it cannot be considered abandoned and no transfer is possible under PEP 541.
