### ISSUE TITLE
2FA Reset

### ISSUE THREAD

**Issue by MysteryBlokHed** [pypa/pypi-support#113]
Username: MysteryBlokHed
Email: adamthompsonsharpe@gmail.com

I got a new phone and lost my 2FA codes because Google Authenticator doesn't back up codes. I accidentally released a broken package through twine (which didn't require a 2FA code to upload), but to delete it I need to log into PyPI, which does require a 2FA code.
Can 2FA be disabled on my account?

**Comment by MysteryBlokHed** [comment]
@ewdurbin I saw you on a couple of other similar issues about 2FA. Can you check this out when you get a chance?

**Comment by MysteryBlokHed** [comment]
I am still waiting for help. I'd like to get back into PyPI sooner rather than later, as I don't want to keep a broken package uploaded.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should now be able to regain access to your account.
