### ISSUE TITLE
Limit Request: ldcpy - 300MB (upload size)

### ISSUE THREAD

**Issue by pinarda** [pypa/pypi-support#1130]
### Project

ldcpy

### Does this project already exist?

- [X] Yes

### Size of release/project

232MB

### Which indexes

PyPI

### Reasons for the request

ldcpy is a utility for gathering and plotting metrics from NetCDF or Zarr files. We have a number of example datasets that are used in the documentation and tutorial, which hare taking up much of the space in the package. These are all necessary to showcase the different variables and file types the package supports.

I previously received a limit increase to 300MB, but upon trying to upload to PyPi I am getting an error that my file size is greater than my 200MB limit. I am not sure if this limit was increased for the upload or total project size, but I am requesting the 300MB size for each release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `ldcpy` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
