### ISSUE TITLE
Limit Request: Open3D - 304MB

### ISSUE THREAD

**Issue by ssheorey** [pypa/pypi-support#1131]
### Project

Open3D https://pypi.org/project/open3d/

### Does this project already exist?

- [X] Yes

### Size of release/project

304 

### Which indexes

PyPI

### Reasons for the request

Hello PyPI maintainers,

We are hitting the file size limit (300MB) for Open3D v0.13. You graciously increase our quota to 300MB file size limit for our 0.12 release in Dec. 2020 (#809), but we have unfortunately crossed it. Can you increase the quota to 400MB for us?

The main reason for the increase is increasing functionality in Open3D, especially with respect to both CUDA GPU and CPU implementations that are implemented as compiled modules. While we expect the file size to increase more for future releases, we will also look at ways to decrease our footprint.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `open3D` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by ssheorey** [comment]
Thank you. We are taking steps to reduce the wheel size in the future.
