### ISSUE TITLE
PEP 541 Request: pypyodbc

### ISSUE THREAD

**Issue by braian87b** [pypa/pypi-support#1133]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pypyodbc/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/braian87b

### Reasons for the request

Because community members tried to reach several times author with no luck, we were trying for long time.

I was set as maintainer long time ago by author in the old repository at:
https://github.com/jiangwen365/pypyodbc

I already migrated code to a community repository to:
https://github.com/pypyodbc/pypyodbc

_Please note README.md edited by me on both repositories._

some related:
https://github.com/jiangwen365/pypyodbc/issues/107#issuecomment-779649372
https://github.com/jiangwen365/pypyodbc/issues/79#issuecomment-397599666
https://github.com/jiangwen365/pypyodbc/issues/88#issuecomment-428948354

currently related:
https://github.com/jiangwen365/pypyodbc/issues/107#issuecomment-851756361

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/pypyodbc/pypyodbc

### Contact and additional research

https://pypi.org/user/jiangwen365/
https://github.com/jiangwen365
jiangwen365@gmail com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sodul** [comment]
Ping on this issue. We have to pin our requirements to an older release of pypyodbc and the currently assigned owner is not showing any sign of activity. We really think transferring ownership to an active maintainer is required here.

**Comment by yeraydiazdiaz** [comment]
Hello @braian87b, I will start the reachability process on this project, hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
