### ISSUE TITLE
PEP 541 Request: featureform

### ISSUE THREAD

**Issue by simba-git** [pypa/pypi-support#1136]
### Project to be claimed

`featureform`: https://pypi.org/project/featureform

### Your PyPI username

`featureform`: https://pypi.org/user/featureform

### Reasons for the request

The username created is a random string, and there is no email anywhere on the project. It was created around the time that we first started presenting what we were releasing. There project is completely empty and doesn't do anything. The user also created another project called feature-form, which is further implies that this is a malicious user trying to block off our project name. The current project doesn't even do anything or have docs so probably falls under the definition of [invalid projects](https://www.python.org/dev/peps/pep-0541/#invalid-projects): "package has no functionality or is empty".

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/featureform/embeddings

### Contact and additional research

There is no email anywhere associated with the user or the project to contact

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
