### ISSUE TITLE
PEP 541 Request: gbprocess

### ISSUE THREAD

**Issue by DriesSchaumont** [pypa/pypi-support#1137]
### Project to be claimed

`gbprocess`: https://pypi.org/project/gbprocess

### Your PyPI username

`dschaumont`: https://pypi.org/user/dschaumont

### Reasons for the request

I believe this project is invalid. The project consists of a single function (`binary_conv`) which IMO should not be released as a separate package.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://gitlab.com/dschaumont/GBprocesS

### Contact and additional research

At the time of writing, version 0.0.1 of the package contains just the following code. I believe it has hardly any functionality.

```
def binary_conv(inarg):
    def conv_str(arg1):
        return ''.join(format(i, 'b') for i in bytearray(arg1, encoding ='utf-8'))
    def conv_int(arg1):
        return bin(arg1).replace("0b", "")

    if isinstance(inarg,str):
        return conv_str(inarg)
    if isinstance(inarg,list) or isinstance(inarg,tuple):
        new_list = []
        for num in inarg:
            if isinstance(num,int):
                new_list.append(conv_int(num))
            elif isinstance(num,str):
                new_list.append(conv_str(num))
        return new_list
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @DriesSchaumont, I can confirm those are the contents of the project. However limited the project does have functionality so it cannot be classified as invalid. I will start the reachability process, hopefully we will hear back from the owner soon and move on with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied stating his intention to keep the project for further development, as such it cannot be considered abandoned and no transfer is possible.
