### ISSUE TITLE
Recover The Pypi account

### ISSUE THREAD

**Issue by suttisak-ponsri** [pypa/pypi-support#114]
Hi

I no longer have access to the email associated with my pypi account (Username: suttisak).
Could you please help me to recover my account.

Thank you

**Comment by ewdurbin** [comment]
Hello @suttisak-ponsri, can you confirm what address was associated with the account?

**Comment by suttisak-ponsri** [comment]
Hello @ewdurbin 
The email may be suttisak.pon@ascendcorp.com

**Comment by ewdurbin** [comment]
@suttisak-ponsri thanks, can you please email ernest@python.org from the new address you'd like to associate with the account?

**Comment by ewdurbin** [comment]
The primary email address for the account has been updated and a password reset initiated.

Please complete the reset to regain access to your account.
