### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yzernik** [pypa/pypi-support#1140]
### PyPI Username

yzernik

### Reason for request

Lost my phone with my authenticator code

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by yzernik** [comment]
@ewdurbin Thanks!
