### ISSUE TITLE
PEP 541 Request: neptune

### ISSUE THREAD

**Issue by Raalsky** [pypa/pypi-support#1141]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/neptune

### Your PyPI username

`USER_NAME`: https://pypi.org/user/neptune-deployer/

### Reasons for the request

We (Neptune Labs Inc. - https://neptune.ai/) are currently the maintainers of a project https://pypi.org/project/neptune-client/ (neptune-**client**) which consists of a package `neptune` (`import neptune`). At the time of package creation there were actually already created project under https://pypi.org/project/neptune (I suspect :wink:). Currently the project https://pypi.org/project/neptune seems to not exists (404 error - Page Not Found) but during uploading a package `neptune` to PyPI with Twine it terminates with an error:
`HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'neptune-deployer' isn't allowed to upload to project 'neptune'. See https://pypi.org/help/#project-name for more information.` We do think it's  some unexpected state. 

Our current name "with the suffix" constantly confuses our users in order they're actually try to `pip install neptune`. We would like to migrate to the package as itself (`neptune`) in addition to our current package (`neptune-client`) which should be treated as deprecated (in a long-term).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/neptune-ai/neptune
https://github.com/neptune-ai/neptune-client

### Contact and additional research

At https://pypi.org/project/neptune/ there is an 404 (Page Not Found) error so actually couldn't find any contact info.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Raalsky, I can confirm the project has no releases and is therefore considered invalid. I will attempt to contact the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
FYI the owner of the project is PyPI user [kamil-kaczmarek](https://pypi.org/user/kamil-kaczmarek/) whose email address has the neptune.ai domain and also recently release a [project](https://pypi.org/project/neptune-contrib/) related to your company.

**Comment by kamil-kaczmarek** [comment]
Hi @yeraydiazdiaz ,

I'm the owner of the aforementioned project on PyPI. I'm now in contact with @Raalsky, we will make changes early next week.

Regards,
Kamil

**Comment by yeraydiazdiaz** [comment]
Great, thanks for replying @kamil-kaczmarek, closing as contact has been made.
