### ISSUE TITLE
Limit Request: tensorflow-rocm - 600 MB

### ISSUE THREAD

**Issue by sunway513** [pypa/pypi-support#1142]
### Project URL

https://pypi.org/project/tensorflow-rocm/

### Does this project already exist?

- [X] Yes

### Size of release/project

512MB

### Which indexes

PyPI

### Reasons for the request

The size of the WHL package for tensorflow-rocm 2.5 release is now 512 MB. Need the PyPi maintainer's help to increase the limitation to 600 MB. 
The tensorflow-rocm project releases binary support for tensorflow on ROCm backend, for AMD GPUs. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sunway513** [comment]
cc @deven-amd

**Comment by sunway513** [comment]
Gentle ping.. can anyone from PyPi team help on this request? Thanks.

**Comment by di** [comment]
I've set the upload limit for `tensorflow-rocm` to 600 MB on PyPI. Please be mindful of the frequency of releases at that size.
