### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by plankthom** [pypa/pypi-support#1144]
### PyPI Username

`thomas_waylay`

### Reason for request

I lost 2FA authentication due to a device reset, and I cannot seem to find the recovery codes.

I still have a valid username/password, and a valid security token. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by plankthom** [comment]
@ewdurbin Many thanks, recovery codes are safely stored now! 

I wasn't aware that test.pypi.org uses a different user database, would it be possible to reset 2FA for this application too?

**Comment by ewdurbin** [comment]
Done.
