### ISSUE TITLE
Limit Request: intel-tensorflow - 10GB addition to the current project

### ISSUE THREAD

**Issue by justkw** [pypa/pypi-support#1148]
### Project URL

https://pypi.org/project/intel-tensorflow/

### Does this project already exist?

- [X] Yes

### Size of release/project

20GB

### Which indexes

PyPI

### Reasons for the request

We're hitting the project size limit and we're releasing for Intel Tensorflow 2.5.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `intel-tensorflow` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
