### ISSUE TITLE
PEP 541 Request: clingo

### ISSUE THREAD

**Issue by rkaminsk** [pypa/pypi-support#1149]
### Project to be claimed

`clingo`: https://test.pypi.org/project/clingo

### Your PyPI username

`kaminski`: https://test.pypi.org/user/kaminski

### Reasons for the request

The project seems to be abandoned and has not been updated in about 3 years. I want to replace the project with <https://test.pypi.org/project/clingo-cffi/>, which provides the latest clingo version and supports more platforms (the existing package calls gcc manually and thus is not very portable).

I am the developer of clingo and already maintain <https://pypi.org/project/clingo/>. Being able to use the same project name on both <http://pypi.org> and <http://test.pypi.org> would make testing much easier for me.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/potassco/clingo

### Contact and additional research

I tried to reach the author via email but did not get a reply. It looks like a university email account has been used, which the author probably is not using anymore. His last publication is from 2018, so I think he is not working in academia anymore.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
