### ISSUE TITLE
django-disposable-email-checker ownership transfer

### ISSUE THREAD

**Issue by jheld** [pypa/pypi-support#115]
**Project to be claimed**

`django-disposable-email-checker`: https://pypi.org/project/django-disposable-email-checker/

**Your PyPI username**

`snoopy1497`: https://pypi.org/user/snoopy1497/

**Reasons for the request**

The software is nearly naturally compatible with django 2.x (django 3.x potentially). However, there has not been a new release in years despite general compatibility with django with the code unchanged. Due to this (and as discussed further below), it appears the project has been abandoned.

**Maintenance or replacement?**

I intend to continue maintenance under the current project name/package on PyPI (using my fork on github).

Original project: https://github.com/aaronbassett/DisposableEmailChecker

My fork: https://github.com/jheld/DisposableEmailChecker

**Contact and additional research**

A couple members (including myself) have reached out to this author and have not heard any response, via github. I have _just_ emailed them today (github was 11 months ago), and if I do hear back I will promptly close this request, however given the lack of response so far, it is likely that this will not receive a response. (Hopefully it does!)

UPDATE re: the email I sent out:

![Screenshot from 2019-12-21 17-04-59](https://user-images.githubusercontent.com/828813/71314321-1fd1a400-2414-11ea-8bfc-291ad9828587.png)

**Comment by yeraydiazdiaz** [comment]
Hi @jheld, it seems @aaronbassett has been recently active in GitHub so hopefully he will get back to us regarding your request. It does seem like the domain `rawtech.io` is no longer active so the email but his GitHub profile includes an email address. I will try contacting him through that as well.

**Comment by jheld** [comment]
Thank you! I appreciate it (one way or the other).

**Comment by yeraydiazdiaz** [comment]
Hello @jheld, I have not received response on any of my attempts to contact the author so this package is now considered abandoned.

I will now ask an admin to perform the transfer to you.

**Comment by jheld** [comment]
thank you for your help so far, looking forward to it!

**Comment by ewdurbin** [comment]
transfer complete.
