### ISSUE TITLE
PEP 541 Request: Crappy

### ISSUE THREAD

**Issue by Dad0u** [pypa/pypi-support#1151]
### Project to be claimed

`crappy`: https://pypi.org/project/crappy

### Your PyPI username

`lamcube`: https://pypi.org/user/lamcube

### Reasons for the request

Dear PyPI team, 
The project entitled "crappy" on PyPI was created more than 4 years ago an not updated once. This project provides no functionality. I would like to use this name, so i tried contacting the author through the contact email address but got no reply. Since this package provides no functionality, i believe this falls in the category "name squatting" of the PEP 541.

I would like to use this name for the project "Crappy" (Command and Real-time Acquisition in Parallelized Python) hosted on github: https://github.com/LaboratoireMecaniqueLille/crappy
Is it possible to reclaim the name of the project ?
Thank you

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The project we would like to distribute using PyPI is hosted on Github: https://github.com/LaboratoireMecaniqueLille/crappy

### Contact and additional research

The following email was sent to the maintainer address found on PyPI on May 17th. There was no reply.

Dear Xiaolong Zeng,

I see that you have published on PyPI in 2017 a Python module for language processing named "Crappy" (https://pypi.org/project/crappy/). It seems that this distribution is not maintained and does not actually distribute the package files.

I am the lead developer for an other project named "Crappy" (Command and Real-time Acquisition in Parallelized PYthon: https://github.com/LaboratoireMecaniqueLille/crappy), a Python module for the development of experimental setups by the LaMcube, a laboratory specialized in solid mechanics based in Lille, France. To make the installation of Crappy easier, we would like to distribute it using PyPI, thus allowing the installation of the module with pip instead of manually calling setup.py.

Your currently unused module is reserving the name "Crappy" on PyPI, preventing us from distributing our package with the name "Crappy". If the PyPI reference for your module is unused, could you please delete the project from PyPI or rename it in order to allow us to use the name for our own package ?

Thank you for your understanding,

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
