### ISSUE TITLE
PEP 541 Request: sphinxcontrib.youtube

### ISSUE THREAD

**Issue by dham** [pypa/pypi-support#1157]
### Project to be claimed

`sphinxcontrib.youtube`: https://pypi.org/project/sphinxcontrib.youtube/

### Your PyPI username

`dham`: https://pypi.org/user/dham

### Reasons for the request

The last PyPI release is 2015. It does not, for example, support Python 3. This project forms part of sphinx-contrib, an official system of plugins for the Python documentation system, Sphinx. I took over as maintainer in 2017 and have periodically merged my or others' changes to, for example, fix bugs or support Python 3 see: https://github.com/sphinx-contrib/youtube/commits/master

More recently, there has been discussion about the desirability of the package on PyPI reflecting developments since 2015, see: https://github.com/sphinx-contrib/youtube/issues/9 . I now propose to do this.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The package is maintained from the official sphinx-contrib repository, here: https://github.com/sphinx-contrib/youtube

### Contact and additional research

The current maintainer is @shomah4a. They do not have an email address published on PyPI or GitHub. I tried to reach out to them last month by raising an issue on one of their repositories: https://github.com/shomah4a/sphinx-tweet-embed/issues/6 . I have also sent a Twitter DM to the account of the same name. There has been no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @dham, I will now start the reachability process for this project. Hopefully we will hear back from @shomah4a soon and proceed with the transfer.

**Comment by shomah4a** [comment]
I agree to transfer control of sphinxcontrib.youtube

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @shomah4a, transfer complete.
