### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by okorach** [pypa/pypi-support#1158]
### PyPI Username

okorach

### Reason for request

I apparently had 2FA activated in aug last year (2020) with TOTP app but I can't remember that (I would be surprised that I would not have picked SMS as 2FA, this seems possible on pypi.org).
I still have a valid token that allows me to upload my package updates but i cannot login in my account anymore.
Is there anything you can do for me?
Thank you

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
