### ISSUE TITLE
Lost my 2FA Application

### ISSUE THREAD

**Issue by wgzhao** [pypa/pypi-support#116]
Hi !

My authenticator was lost , so I have no way to access my account(wgzhao@gmail.com) back, I don't have recovery code , recording to [pypa/warehouse#5758](pypa/warehouse#5758) , I create a new issue, I hope to access my account as soon as possible .

Thanks !

**Comment by ewdurbin** [comment]
Hello @wgzhao, please email ernest@python.org from the primary email address associated with your PyPI account to proceed.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
