### ISSUE TITLE
PEP 541 Request: PySDL2

### ISSUE THREAD

**Issue by a-hurst** [pypa/pypi-support#1160]
### Project to be claimed

`PySDL2`: https://pypi.org/project/PySDL2/

### Your PyPI username

`a-hurst`: https://pypi.org/user/a-hurst

### Reasons for the request

I was brought on to PySDL2 as a co-maintainer in late 2019, since the original author (@marcusva) didn't have much time to maintain it anymore (you can see I'm listed as a maintainer in the package's `AUTHORS.TXT` [here](https://github.com/marcusva/py-sdl2/blob/master/AUTHORS.txt)). However, I never requested (and thus was never given) PyPI access to the project so I'm unable to make new releases.

Anyway, the last PyPI release of PySDL2 is now over a year old and is two versions out of sync with the latest SDL2 release. I've updated the code and merged several important bugfixes since then, but for the past month I've been unable to get in touch with Marcus through GitHub (no user activity in over a year) or via email where I've been able to reach him in the past. Assuming that I continue to get no response, would it be possible to add me as a PyPI maintainer for the project?

To be clear, I'm only requesting maintainer access and not a transfer of ownership: it's entirely possible that Marcus might find time in his life for PySDL2 again, I just want to make sure it's actively maintained for its userbase in the meantime.

Thanks in advance!

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/marcusva/py-sdl2

### Contact and additional research

I have pinged @marcusva repeatedly in [this issue](https://github.com/marcusva/py-sdl2/issues/184) regarding a new PyPI release, and additionally emailed him at his PyPI-associated address 3 weeks ago (May 26th) with no response. I also tried searching for any activity on any other platforms he might be on, but wasn't able to find anything.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @a-hurst, you appear as a maintainer of PySDL2 already, it seems the owner already granted your request.
