### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gjvc** [pypa/pypi-support#1163]
### PyPI Username

`gjvc`

### Reason for request

Lost access to email address, server offline down dead.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because this user has no projects associated with it, the email address has been updated to the address advertised on your GitHub public profile. You may proceed with a standard password reset request to regain access to your account.
