### ISSUE TITLE
Limit Request: mytensorflow - 620 MB

### ISSUE THREAD

**Issue by ssbuild** [pypa/pypi-support#1169]
### Project URL

https://pypi.org/project/mytensorflow/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

620 MB

### Which indexes

PyPI

### Reasons for the request

We're releasing for main tensorflow gpu package and we're hitting the project size limit at only some whl package ,hope you can increased mytensorflow project size to 620 MB , I will be carefully to do update not often. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ssbuild** [comment]
@di  dear master, why nobody process !

**Comment by di** [comment]
Hi, can you give us more details about what this package is? Are you affiliated with the Tensorflow team? Do you have a public source repo that corresponds to this project?

**Comment by ssbuild** [comment]
> Hi, can you give us more details about what this package is? Are you affiliated with the Tensorflow team? Do you have a public source repo that corresponds to this project?

thank you for your reply, this project mytensorflow is with different cudnn and cuda tensorflow recompiled version, I'm not sure if unofficial compiled versions can be released, if only limit state,  I give up ?

**Comment by pradyunsg** [comment]
Hi @ssbuild!

> different cudnn and cuda tensorflow recompiled version and it support more graphics card

Could you be a bit more specific, and provide details on these.

- Which versions of CuDNN and CUDA are you compiling with?
- How does that "support more graphics card"?

> Are you affiliated with the Tensorflow team? Do you have a public source repo that corresponds to this project?

Please answer these questions as well.

**Comment by pradyunsg** [comment]
Closing due to lack of a response.

**Comment by ssbuild** [comment]
> Hi @ssbuild!
> 
> > different cudnn and cuda tensorflow recompiled version and it support more graphics card
> 
> Could you be a bit more specific, and provide details on these.
> 
> * Which versions of CuDNN and CUDA are you compiling with?
> * How does that "support more graphics card"?
> 
> > Are you affiliated with the Tensorflow team? Do you have a public source repo that corresponds to this project?
> 
> Please answer these questions as well.

Sorry to reply now, mytensorflow is build by cuda 11.3.1 cudnn 8.2.1 nccl 2.9.9 nvidia Compute Capability 6.1 7.0 7.5 8.0 8.6 and it will support more new nvidia GPU , and it will build majar version of tensorflow, and it includes tf1.15 that widely used.
