### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by oshaughn** [pypa/pypi-support#1171]
### PyPI Username

`oshaughn`

### Reason for request

2FA authentication app wiped.  (Had to replace phone.)  Have access to username/password/email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This User on PyPI has recovery codes generated. Please use those recovery codes to regain access to your account.
