### ISSUE TITLE
Limit Request:  [multiple packages] -- 300-400 MB

### ISSUE THREAD

**Issue by prstrnn** [pypa/pypi-support#1173]
### Project URL

https://pypi.org/project/onednn-cpu-iomp/
https://pypi.org/project/intel-opencl-rt/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit
onednn-cpu-iomp  400 MB
intel-opencl-rt 300MB

### Which indexes

PyPI

### Reasons for the request

I'm from Intel corp. and we are releasing new software in PyPI.
IntelAutomationEngineering - PyPI account we will use to upload packages.
**Reasons for the request**
It's Intel's software that contains a lot of optimizations for the different hardware, that's why it has so big size.
Expected that future releases will be greater than current. Current size is 270MB, so 400MB is extra buffer for future releases

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by prstrnn** [comment]
@di @pjenvey @pradyunsg @ewdurbin  could you please assist with that?

**Comment by nikkidreamt** [comment]
@di @pjenvey @pradyunsg @ewdurbin could you please help?

**Comment by tomashek** [comment]
Note that this package is a renaming of the "opencl-rt" package. Opencl-rt already received the size exception. We will no longer be posting large files to the opencl-rt project.

Please extend the limit for this as soon as you can.

**Comment by tomashek** [comment]
@di @pjenvey @pradyunsg @ewdurbin 

Is there any update here? When can we expect this request to be fulfilled?

**Comment by tomashek** [comment]
@di @pjenvey @pradyunsg @ewdurbin

Is there any update here? Is there someone we ca talk with about how to more reliably address requests like this in the future? @ewdurbin, you had previously suggested sponsorship.

**Comment by di** [comment]
I've set the upload limit for `onednn-cpu-iomp` to 400MB and `intel-opencl-rt` to 300MB on PyPI. Please be mindful of the frequency of releases at that size.

In the future, please don't repeatedly @-mention folks with comments, it really only adds noise and doesn't speed up the process at all. This process is entirely handled by volunteers who have a finite amount of time to handle these requests.
