### ISSUE TITLE
PEP 541 Request: firefly

### ISSUE THREAD

**Issue by agurvich** [pypa/pypi-support#1177]
### Project to be claimed

`firefly`: https://pypi.org/project/firefly

### Your PyPI username

`agurvich`: https://pypi.org/user/agurvich

### Reasons for the request

According to the [removal policy](https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project):

> An abandoned project can be transferred to a new owner for purposes of reusing the name when ALL of the following are met:
> * the project has been determined abandoned by the rules described above;
> * the candidate is able to demonstrate their own failed attempts to contact the existing owner;
> * the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;
> * the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;
> * download statistics on the Package Index for the existing package indicate project is not being used; and
> * the maintainers of the Package Index don't have any additional reservations.

* I believe the project is abandoned. Its last release was in 2014. 

* Below, I document my attempts to contact the package maintainer so far. 

* My package is a novel visualization framework to render millions of points in a web-browser interactively using WebGL. We had previously developed a separate package as a Python based front-end but with further integration with flask the package is now a full fledged python application (and can be run entirely from within a jupyter notebook). [It exists](http://github.com/ageller/Firefly) and we believe it also meets the notability requirements.

* The packages are unrelated, so forking would not make sense. However, we are able to upload with a different name (firefly-vis ?) though we worry this will confuse users and would prefer to use the name firefly.

* See my research below, I am uncertain if the download statistics indicate that the existing project is not being used. I would be very surprised based off the rest of my research if the numbers as I would naively interpret them are correct (though perhaps I am wrong, and in which case this issue should be closed because this project is clearly still in use). 

Thanks for your time, I appreciate your help!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/9miao/Firefly

https://github.com/ageller/Firefly

### Contact and additional research

I have reached out to the project owner at the email address listed on the project's PyPi project page (see attached pdf below; 7 days ago) but have not heard back. 

I investigated the package's [Library.io page](https://libraries.io/pypi/firefly) and it seems to indicate there are 2 projects dependent on it, the most recent of which was updated in 2018. It points to [a github repository](https://github.com/9miao/Firefly) that was last pushed to in 2014, owned by a user that has the same profile picture as the one on PyPi so I believe this is the source repository for the PyPi project. 

On that repository's github page [a homepage](http://firefly.9miao.com/) is listed but the website seems to be dead. A [different url](http://9miao.com) also listed as a homepage does resolve but redirects to what seems to be a website for online games(?). 

Despite all indications that the user has abandoned this particular project the BigQuery results for firefly indicate that it is receiving an astonishing number of weekly and annual downloads (I think? See screenshots below). 

I've just now emailed the 9miao github user to ask if they would be willing to transition the name. 

[Gmail - Firefly pypi name.pdf](https://github.com/pypa/pypi-support/files/6704308/Gmail.-.Firefly.pypi.name.pdf)

## Annual installs
![firefly_year_installs](https://user-images.githubusercontent.com/7799423/123157024-a4e5b100-d42f-11eb-9fb1-f9aa16a5a9ff.png)

## Weekly installs
![firefly_week_installs](https://user-images.githubusercontent.com/7799423/123157109-bfb82580-d42f-11eb-89d8-8f28c169df1d.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by agurvich** [comment]
I just wanted to touch base about the timeframe that this could be resolved in as we are essentially ready to upload our package and would really appreciate if we could use the name `firefly`. 

We are currently waiting to resolve a bug in an unrelated code base until this naming issue can be resolved: 
https://github.com/yt-project/yt/issues/3415

**Comment by yeraydiazdiaz** [comment]
Hello @agurvich thanks for the detailed report. The project does look abandoned however we're obliged by PEP 541 to start the reachability process before proceeding with your request. This process takes up to 6 weeks if we receieve no reply from the owner.

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @9miao as part of the reachability process.

**Comment by agurvich** [comment]
Just checking in to inquire about the process here. According to the [reachability section of PEP 541](https://www.python.org/dev/peps/pep-0541/#reachability) there is a 6 week window. It also says there would be 3 attempts to contact the project owner (in this case @9miao). Does that mean we should try twice more (and wait 6+6 weeks)? Happy to do whatever y'all would like me to do.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
