### ISSUE TITLE
Removal request of Django42 from PyPi

### ISSUE THREAD

**Issue by apollo13** [pypa/pypi-support#118]
Hi there,

I'd like to request the removal of Django42 from PyPI. It currently lists third when searching for Django (a few days ago it was the first result, not sure what the search algorithm does :)) and might trick users into downloading an old release of Django if they do not look closely. Personally I do not think that the package contains malicious code, but I didn't look very closely either.

Please let me know if you need anything else from me.

Thanks,
Florian

**Comment by jamadden** [comment]
The PyPI owner of that project is https://pypi.org/user/tgates42/. That account also owns a number of other projects, many of which appear to be forks of existing projects with "42" added to their name. 

Based on following the links and other public information, it appears that PyPI user `tgates42` may be github user @timgates42 (some projects link to that account, and that account has many repositories forked from upstream with names changed to include the trailing '42'). 

@timgates42, could you please take a moment to explain the purpose for publishing these forks, specifically the purpose for publishing `Django42`? Thank you!

**Comment by timgates42** [comment]
Well its an interesting problem actually and I'd be open to an alternative solution since I seem to have attracted some attention (sorry about that). If a library has an open or even closed pull request adding python 3.9 support (generally the collections.abc deprecation) and I want to use a patched version I publish a new one with the 42 suffix, along with patching any libraries that use those libraries which in one case hit django. I could perhaps add a prefix like not to avoid confusion further?

**Comment by timgates42** [comment]
Actually perhaps an even easier solution is for me to just change the description being published with an explanation of the purpose behind what I am doing and then google won't index it so highly and anyone stumbling on it will understand my intentions. When I get back to work I'll fix all my published libraries descriptions to reduce their google rankings. Unless of course I am missing a better alternative and then please enlighten me otherwise sorry for the inconvenience.

**Comment by apollo13** [comment]
> I'd be open to an alternative solution

Generally people in your situation use custom PyPI registries/mirrors. One example would be https://devpi.net/ -- though there are probably more (and simpler? solutions). The obvious benefit of using a custom server is that you do not have to patch the whole dependency chain, which could easily result in a rather big number of packages (especially if the package is Django or even more low-level like pytz/requests).

>  I could perhaps add a prefix like not to avoid confusion further?

Speaking with my Django hat on I think everything aside from `foo-django` and `django-foo` might be a potential trademark violation (see point two in https://www.djangoproject.com/trademarks/).

But even if you were uploading `django-patched-by-timgates` I cannot guarantee that it wouldn't be a trademark violation. After all what you are shipping on PyPI is a potentially modified Django source code while the PyPI page still clearly lists the DSF as author, which it is not… Not that this is just me thinking out loud, I do not have much knowledge of trademark violations -- just wanted to point out potential issues with either of the approaches.

**Comment by timgates42** [comment]
Interestingly looks like Google might have already fixed the indexing issue, I can't see my package any more which is for the best. Thanks for the information @apollo13 sounds like if I include a minus sign it and fix the author it will be more like a django library. I had a quick look at the alternative PyPI registries and it didn't look super appealing but will see what I can do.

**Comment by apollo13** [comment]
Just to clarify, I never ment Google search but the search box on pypi itself. Thank you for your help in resolving this Tim, much appreciated!

**Comment by yeraydiazdiaz** [comment]
@timgates42 publishing forks of projects in PyPI generates quite a bit of confusion and unnecessary overhead on your part as you need to remember to pull, amend and publish the project under your name on each update.

I suggest using [pip's git feature](https://pip.pypa.io/en/stable/reference/pip_install/#git) to install projects directly from the branches with support for Python 3.9, note you can also specify commit hashes if necessary to keep them stable.

If this approach works for you I would ask you to remove all these projects as they will inevitably become stale and will simply create more confusion for admins and users.

**Comment by timgates42** [comment]
Oh nice one! Thanks @yeraydiazdiaz will look into that - it sounds perfect.

**Comment by timgates42** [comment]
Thanks a lot @yeraydiazdiaz this works great even in the much maligned https://github.com/pypa/pipenv/ - I've removed Django42 and I'll work on fixing my other crimes against PyPi.

**Comment by yeraydiazdiaz** [comment]
That's great news @timgates42, thanks!
