### ISSUE TITLE
PEP 541 Request: arroyo

### ISSUE THREAD

**Issue by lynnagara** [pypa/pypi-support#1180]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/arroyo

### Your PyPI username

`USER_NAME`: https://pypi.org/user/lynnagara

### Reasons for the request

No project appears to actually exist here (https://pypi.org/project/arroyo gives 404). For some reason I am unable to register this project.

### Source code repositories URLs

https://github.com/getsentry/arroyo

### Contact and additional research

none

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
