### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by supersonictw** [pypa/pypi-support#1181]
### PyPI Username

supersonictw

### Reason for request

I'm sorry my Google Pixel 1 was dead, and my Google Authenticator is lost too.
I have recovered several accounts by the recovery codes, but except my account of PyPI because the "recovery code" was not set up, and I didn't notice it. So I loss my account...Can you help me?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by supersonictw** [comment]
OK :smiley:

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
