### ISSUE TITLE
Limit Request: BayesBoom - 150 MB

### ISSUE THREAD

**Issue by steve-the-bayesian** [pypa/pypi-support#1183]
### Project URL

https://pypi.org/project/BayesBoom/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

150MB

### Which indexes

PyPI

### Reasons for the request

BayesBoom is a python interface to the BOOM C++ library.  I'm not sure why, but when I try building the "manylinux" wheel for this project, it is a whopping 120MB.  I'll need to increase both the per-file and total-project limits if I am to publish the manylinux wheels.  Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `BayesBoom` to 200 MB on PyPI.
