### ISSUE TITLE
PEP 541 Request: zeno

### ISSUE THREAD

**Issue by archibate** [pypa/pypi-support#1184]
### Project to be claimed

`zeno`: https://pypi.org/project/zeno

### Your PyPI username

`archibate`: https://pypi.org/user/archibate

### Reasons for the request

The latest release of this project is at `Apr 22, 2018` according to its PyPI page.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Oh sorry our `zeno` hadn't been open-source yet. Here's the link to this private (yet) repository:
https://github.com/zensim-dev/zeno
Yes, you will see 404 at this moment.. But it will soon become open-source hopefully after this issue is resolved.

### Contact and additional research

I tried to find the E-mail address of the user [apldx](https://pypi.org/user/apldx/) who own the project. But it seems that they didn't provide their E-mail address in the project's `Meta` section...
I also tried to search for `apldx` on GitHub, and find @apldx, but it seems they also didn't provide E-mail address on GitHub as well, and no repository named `zeno` is found under this account (not sure if they are the same person after all).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I will attempt to contact the owner and allow one week for replies before proceeding with the transfer.

**Comment by apldx** [comment]
Hey! I'm also in private mode and have updated the project recently with the start of a packaging system. This project is not abandoned.

**Comment by apldx** [comment]
Project is not abandoned! The full version is still in progress, but the first of the Paradoxes (the Dichotomy) is there.

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @apldx.
