### ISSUE TITLE
PEP 541 Request: google-colab

### ISSUE THREAD

**Issue by crwilcox** [pypa/pypi-support#1185]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/google-colab

### Your PyPI username

`USER_NAME`: https://pypi.org/user/google_opensource

### Reasons for the request

As this package claims affiliation to Google LLC, we are requesting ownership of this package for future maintenance be transferred to `google_opensource`. I am unaware of the current publisher and their relationship to Google. 

1) The package states `google` within the name
2) The package claims to be authored by the Google Collaboratory Team
3) The package installs within the google namespace.

```
setup(
    name='google-colab',
    version='1.0.0',
    author='Google Colaboratory team',
    author_email='colaboratory-team@google.com',
    description='Google Colaboratory tools',
    long_description='Colaboratory-specific python libraries.',
    url='https://colaboratory.research.google.com/',
 ```
 
 Thank you for your assistance.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The source is at https://github.com/googlecolab/colabtools. The package is included as part of the Google Managed Colab environment. As it isn't generally usable outside of the colab environment it is not published on PyPI.

### Contact and additional research

I do not have contact information for the current owner, `xixi`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @crwilcox, it seems the projects contents match that of `colabtools` so I would guess the owner simply forked the repo and uploaded it, however, I do think this poses a significat security risk.

The owner's email address is not indicative of any affiiliation to Google and I have not found and details about the owner so I have transferred the project to `google_opensource`.

I will communicate this to the owner's email addres to let them know in case there has been a misunderstanding.

**Comment by crwilcox** [comment]
We just looked and it seems the package is still held by xixi?

**Comment by di** [comment]
Looks like the transfer never happened, I just completed it, sorry for the delay.
