### ISSUE TITLE
PEP 541 Request: db

### ISSUE THREAD

**Issue by el1s7** [pypa/pypi-support#1186]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/db

### Your PyPI username

`USER_NAME`: https://pypi.org/user/elis-k

### Reasons for the request

The project last update was 8 years ago.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/el1s7/simplemysql

### Contact and additional research

No reply from authors

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @el1s7, having a look at the project it does look like it has not been updated for a long time. However, the [stats](https://pepy.tech/project/db) show the project is still quite popular with an average if 1.5k and more in recent days.

Given your intention is a complete replacement of the project I do not feel comfortable moving forward with your request.

I will tag the owner, GitHub user @lgastako, in case they voluntarily would like to transfer the project.

Other moderators can pitch in here if they believe this is not the best course of action but I am closing this request for now.
