### ISSUE TITLE
Limit Request: awkward - 30000 MB

### ISSUE THREAD

**Issue by jpivarski** [pypa/pypi-support#1187]
### Project URL

https://pypi.org/project/awkward/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

30000

### Which indexes

PyPI

### Reasons for the request

[Awkward Array](https://github.com/scikit-hep/awkward-1.0) is a widely used library among particle physicists, but its C++ core and many platforms (35 artifacts) makes each release cost 427 MB. We've even adopted a policy of deleting release candidates, but some bugs are critical and need a patch release, which can never be deleted because data analyses may be pinned to them.

We've even started an [effort to translate most of the C++ code into Python](https://github.com/scikit-hep/awkward-1.0/pulls?q=is%3Apr+%22C%2B%2B+refactoring%3A+%22+) (taking care to not lose performance), which will reduce the sizes of the binaries, but that will take many months to finish.

Increasing our limit from 10 GB to 30 GB will help us to avoid hitting the total project size wall before finishing this translation effort.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `awkward` to 20 GB on PyPI. Given the current total project size of 6 GB, this should give you roughly 28 more releases before you need the limit raised again, at which point we can revisit.

**Comment by jpivarski** [comment]
Thank you!

(It's 6 GB now because I deleted a bunch of release candidates right before opening this issue. The breathing room is necessary before a release.)
