### ISSUE TITLE
PEP 541 Request: geoutils

### ISSUE THREAD

**Issue by erikmannerfelt** [pypa/pypi-support#1188]
### Project to be claimed

`geoutils`: https://pypi.org/project/geoutils

### Your PyPI username

`eriksh`: https://pypi.org/user/eriksh

### Reasons for the request

As previously described in #1101, the user "SrinivasChoudhury" has name-squatted multiple `*utils` names, with practically empty contents.

`geoutils` in question has only one file, `__init__.py`, with the content:

```python
def geoutils():
    print('Thanks For Using Geoutils !!!')
def main():
    geoutils()
```

I and the "GlacioHack" organization request to claim the name for our package [geoutils](https://github.com/GlacioHack/GeoUtils) (which is already published under this name on conda-forge), a tool for geospatial analysis of raster and vector data.

This is a collaboration with @adehecq, @atedstone, @rhugonnet and others.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/GlacioHack/GeoUtils

### Contact and additional research

The owner has no email address, and their source URLs link to GitHub 404s. We have therefore not come in contact with the current owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
