### ISSUE TITLE
Claim package shogun

### ISSUE THREAD

**Issue by vigsterkr** [pypa/pypi-support#119]
I'm one of the maintainers of the shogun project (https://github.com/shogun-toolbox/shogun). From the very beginning we support python bindings,  but the name 'shogun' is claimed so we were forced to take 'shogun-ml'. For our users it would be much easier if we could say 'pip install shogun' instead of 'pip install shogun-ml'.

I'd like to claim 'shogun' under PEP 541, since I was not able to contact the package maintainer, and the package has seen no development or updates in many months.

I know the process is not ready yet, and I am not in a hurry, but I wanted to open this issue so that when the PEP 541 process is implemented, this can be handled.

Thanks! (and of course let me know if any more information is needed)

**Comment by jamadden** [comment]
https://pypi.org/project/shogun/ links to https://www.portantier.com which links to the github profile https://github.com/fportantier @fportanier can you please comment on this discussion?

**Comment by vigsterkr** [comment]
@jamadden what's the usual waiting time for a reply in these cases?

**Comment by jamadden** [comment]
Normally PEP 541 specifies a 6 week waiting time for contact to be established. However, this particular project contains no installable files, so it falls under the PEP definition of a name squatting project and can be removed/transferred immediately. (Also, the GitHub repo it points to no longer exists.) I'll get in touch with the admins.

**Comment by jamadden** [comment]
@vigsterkr Could you confirm your PyPI username please?

**Comment by vigsterkr** [comment]
@jamadden sure thing! it's `wiking`. ta!

**Comment by fportantier** [comment]
The name shogun it's used for a project that we're development. But I don't have problem to change it. So, I can free the name.

**Comment by fportantier** [comment]
Done, the project has been deleted, so, the name will be free. Regards! :)

**Comment by jamadden** [comment]
@fportantier Thanks!

@vigsterkr I confirm the project has been deleted. It's up to you to upload your new project to secure the name.
