### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by shahsad-klr** [pypa/pypi-support#1191]
### PyPI Username

Lost 2FA authentication app

### Reason for request

Lost 2FA authentication app when formated my photo data

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This request cannot be processed without supplying your PyPI username.
