### ISSUE TITLE
PEP 541 Request: kanon

### ISSUE THREAD

**Issue by legau** [pypa/pypi-support#1194]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/kanon

### Your PyPI username

`USER_NAME`: https://pypi.org/user/lgauffier

### Reasons for the request

As suggested by @yeraydiazdiaz, I am opening this PEP 541 issue to request `kanon` which has been removed for typo squatting.

### Maintenance or replacement?

Replacement

### Contact and additional research

#1055

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @legau, this project has been placed in the prohibited projects names list, @pypa/warehouse-admins will need to release if for you.

**Comment by ewdurbin** [comment]
Project has been released to the `lgauffier` User on PyPI.
