### ISSUE TITLE
PEP 541 Request: snapshot

### ISSUE THREAD

**Issue by gemerden** [pypa/pypi-support#1195]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/snapshot

### Your PyPI username

`USER_NAME`: https://pypi.org/user/gemerden

### Reasons for the request

User seems to be name squatting. As far as I can see no (real) package has ever been uploaded (pip install does not work, there is no homepage, no license, no description). The package was created in 2013 and has not changed since.

My own repo to replace the current package can be found at: https://github.com/gemerden/snapshot

### Maintenance or replacement?

Replacement

### Source code repositories URLs

None

### Contact and additional research

The only user email (from the PyPi page) I could find is blocked:

darshan.bhoir@eclinicalworks.com

gives:

550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM6NAM12FT039.eop-nam12.prod.protection.outlook.com]

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The email associated with the owner is not functional, transfer complete.

**Comment by gemerden** [comment]
Great, thank you
