### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by raprasad** [pypa/pypi-support#1197]
### PyPI Username

`raman.prasad`

### Reason for request

Hi, my phone with Google Authenticator died last week and the Authenticator app was not backed up/didn't restore with the PyPI settings.

Next time, I'll definitely generate recover codes. I have several package permissions related to the "opendp" project including "opendp-smartnoise" and "opendp-smartnoise-core"

Within the GitHub org "OpenDP", my name (Raman Prasad/raprasad) may be found on GitHub as one of the organization owners: https://github.com/orgs/opendp/people

I very much appreciate the assistance. 

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
