### ISSUE TITLE
PEP 541 Request: adapt

### ISSUE THREAD

**Issue by antoinedemathelin** [pypa/pypi-support#1198]
### Project to be claimed

`adapt`: https://pypi.org/project/adapt

### Your PyPI username

`demat`: https://pypi.org/user/demat

### Reasons for the request

I would like to upload a package named `adapt` to PyPI but it appears like one of the following reasons is the issue

```
1. The project name conflicts with a Python Standard Library module from any major version from 2.5 to present.
2. The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.
3. The project name has been registered by another user, but no releases have been created.
```

`adapt` does not appear in the standard library so I would assume this is either because of 2. or 3. Assuming this is because of 3., I do not see any project available, https://pypi.org/search/?q=adapt, and as a result I would like to claim it. Assuming this is because of 2. then this can be ignored and closed, but I could find no reference of the prohibited names.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/adapt-python/adapt

### Contact and additional research

I cannot find any reference to the package `adapt` blocking the namespace.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by antoinedemathelin** [comment]
Sorry, I realize in following this link : https://pypi.org/project/adapt that someone already use the name `adapt` although I wasn't able to find it with https://pypi.org/search/?q=adapt. I will contact the author and ask him if he is willing to let me use the `adapt` name.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by antoinedemathelin** [comment]
Thank you a lot!
