### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Perzan** [pypa/pypi-support#1199]
### PyPI Username

`Perzan`

### Reason for request

- Recently reset phone with 2FA app on it
- Lost recovery codes
- Have access to email still
- Have password to log in

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This User on PyPI has recovery codes generated. Please use those recovery codes to regain access to your account.

**Comment by Perzan** [comment]
> This User on PyPI has recovery codes generated
Is there no other way I can get my account back?

**Comment by Perzan** [comment]
@ewdurbin

**Comment by Perzan** [comment]
@ewdurbin 
> This User on PyPI has recovery codes generated

I have lost those codes though...

Is there no other way I can get my account back?
