### ISSUE TITLE
PEP 541: Transfer ownership of rocketchat package

### ISSUE THREAD

**Issue by bpabel** [pypa/pypi-support#12]
I've had a PEP 541 transfer request open on the old issue tracker for over a year.

https://sourceforge.net/p/pypi/support-requests/801/

I'd like to take ownership of the pypi rocketchat package

https://pypi.python.org/pypi/rocketchat/0.1

I believe this project is both abandoned and invalid. The links in the pypi project are broken, but I believe this is the project page.

github - https://github.com/SKantar/rocketchat-api

The project appears to be almost a direct copy/paste of an old version of this project

pypi - https://pypi.python.org/pypi/rocket-python/1.2.2
github - https://github.com/dstegelman/rocket-python

However, the lone source distribution on pypi is broken and unusable (it only contains about half the code in the original project) and has no functionality (hence my claim of an invalid project)

Here are my unsuccessful attempts to contact who I think may be the project owner

https://github.com/SKantar/rocketchat-api/issues/1

Here is the project page and the pypi account that I would like the pypi package transferred to

pypi Account: bpabel
github - https://github.com/bpabel/rocketchat

**Comment by yeraydiazdiaz** [comment]
Hello @bpabel, I've emailed @SKantar and asked him to clarify his position in regards to this package. Hopefully we'll hear back soon and proceed with your request.

**Comment by bpabel** [comment]
Hello @yeraydiazdiaz, have you heard back from @SKantar yet?  I saw that he closed some issues on Github recently, but I haven't heard from him.

**Comment by yeraydiazdiaz** [comment]
Hi @bpabel, I have not received response from the owner of the project so it is now considered abandoned. I will now ask an admin to perform the transfer to you.

**Comment by SKantar** [comment]
Hi all,

I created this package while I was working for an company called Modoolar. I think they have been using this package actively and also I think it's not cool from your side to take the ownership of this package and change it (only because you like 'naming')...

Thanks.

**Comment by yeraydiazdiaz** [comment]
Hi @SKantar, thanks for replying. Just to clarify, no-one's "taking ownership" of the project, @bpabel and myself have tried contacting you several times as outlined by [PEP 541](https://www.python.org/dev/peps/pep-0541/) but recieved no response.

I will ask the admin to hold off on the transfer for now, but I encourage you and @bpabel to come to an agreement over the future of the project, ideally in https://github.com/SKantar/rocketchat-api/issues/1 to reduce the amount of noise in this repo.

If you do not come to an agreement you are on your right to keep the PyPI project under your control.

**Comment by bpabel** [comment]
Hi @yeraydiazdiaz , I don't think @SKantar's 11th-hour reply really changes much about the original request.  

The pypi project is still invalid per [PEP 541](https://www.python.org/dev/peps/pep-0541/#invalid-projects) as I believe it meets the following criteria.

> - project is name squatting (package has no functionality or is empty);

The pypi project is mostly empty except for a single release, and while there are python files in that release, it doesn't work and isn't importable by any version of python, ergo it has "no functionality" and qualifies as an invalid project and should be removed from the index.

**Comment by yeraydiazdiaz** [comment]
Hi @bpabel, I've had a deeper look. @SKantar mentioned:

>  I created this package while I was working for an company called Modoolar. I think they have been using this package actively

The project is installable but the package is built incorrectly and causes import errors, thus has no functionality. Additionally there's been no releases or commits in the source repo since the very first one three years ago.

In light of that I agree with @bpabel that the project can be considered invalid and abandoned at this point in time. @SKantar, given the state of the package and repo it seems you or the company have no plans to work on the project so I'm going to grant @bpabel the request.

**Comment by SKantar** [comment]
@bpabel don't be so aggressive, it's Christmas time here in Serbia (we celebrate Christmas at January 7th) and I do not work for Christmas and I have a reason why I haven't answered.

I'm no more part of that company as you can see. As I remember, they have been using RocketChat as a internal communication tool and I connected it with git so when someone commit something other related contacts get message related to that commit. I'm pretty sure it worked correctly when I left company (before year and a half)

Thanks,
Sladjan

**Comment by yeraydiazdiaz** [comment]
Hi @SKantar, I don't think @bpabel is trying to be aggressive, he's acting in the spirit of the PEP which establishes guidelines to deal with these situations.

The fact is that when users install `rocketchat` they get a non-functional package. This has been verified by both of us. It's also clear you have not been maintaining the project, do you have plans on doing so? If not, what exactly are your reservations to allow the transfer?

**Comment by SKantar** [comment]
I gave Owner permissions for rocketchat package to bpbabel.

Best,
Sladjan

**Comment by yeraydiazdiaz** [comment]
Great, thanks @SKantar!

**Comment by bpabel** [comment]
Thanks @SKantar !! @yeraydiazdiaz , I'm currently locked out of pypi because of a 2FA issue (#146), not sure if you're able to do anything about that as well.  Thanks!

**Comment by yeraydiazdiaz** [comment]
No worries @bpabel. 2FA requests are not handled by moderators, sorry. I'm sure an admin will sort it out soon.
