### ISSUE TITLE
PEP 541 Request: streams

### ISSUE THREAD

**Issue by tylercrompton** [pypa/pypi-support#1203]
### Project to be claimed

`streams`: https://pypi.org/project/streams/

### Your PyPI username

`tylercrompton`: https://pypi.org/user/tylercrompton/

### Reasons for the request

The project is ~~abandoned~~ invalid as defined by PEP 541. There are no true releases. The only "release" was to claim the name on PyPI over seven years ago and it has since remained untouched and unused.

The package owner Antti Haapala created [a corresponding Git repository](https://github.com/ztane/streams) but it's incomplete, hasn't been touched in over six years, and hasn't been added to the PyPI project.

According to Libraries.io, the following three projects are the only projects known to "depend" on this package:

- [dask/pandas-streaming](https://libraries.io/github/dask/pandas-streaming): This has a typo in its "requirements.txt" file. Looking at the source, it appears to actually depend on [python-streamz/streamz](https://libraries.io/pypi/streamz)―not this package.
- [adamroach/standards](https://libraries.io/github/adamroach/standards): This doesn't even use Python, so I'm not sure why it is listed on Libraries.io.
- [elfinhuangcat/neuCS6200](https://libraries.io/github/elfinhuangcat/neuCS6200): This is an abandoned homework repository from five years ago. Libraries.io incorrectly reports it as dependent, as it makes no use of this package.

In summation, no one is known to be using or to have ever used this package. Again, the PyPI listing doesn't mention this abandoned GitHub repository. The PyPI package is effectively a name-squatting situation.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/tylercrompton/streams

### Contact and additional research

On June 28, I sent the package owner, Antti Haapala, the following email message (which is publicly available on their GitHub profile):

> Hi, Antti, I've been working on a Python project called Streams (https://github.com/tylercrompton/streams). and I'm looking to release it on PyPI. I noticed that you control the similarly named package on PyPI (https://pypi.org/project/streams/) and that it's both undeveloped and inactive. I am curious as to whether you still have plans for this project. If not, then is there any chance that you would be willing to transfer ownership to me? I look forward to hearing back from you.
>
> Regards,  
> Tyler Crompton

After six days, I had not received a response, so [I followed up via Twitter](https://twitter.com/tylercrompton/status/1411733716146307079) on July 4. Another six days have passed and I've still yet to receive a response (via any medium).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by tylercrompton** [comment]
I've also reached out to him in [a StackOverflow chat room](https://chat.stackoverflow.com/rooms/235261/room-for-tyler-crompton-and-antti-haapala) as I saw [him show up](https://chat.stackoverflow.com/transcript/message/52690892#52690892) in the Python chat room.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
