### ISSUE TITLE
Manual Reset of 2FA

### ISSUE THREAD

**Issue by michaelbukachi** [pypa/pypi-support#121]
Hi,
username: michaelbukachi
email: michaelbukachi@gmail.com

Request: a reset of the 2FA for the above account info.
Reason: Lost phone so lost my key

**Comment by michaelbukachi** [comment]
Done.

**Comment by ewdurbin** [comment]
Thanks for validating. 2FA has been reset and a password reset issued, complete it to regain access to your account.
