### ISSUE TITLE
Limit Request: pynini - 180 MB

### ISSUE THREAD

**Issue by kylebgorman** [pypa/pypi-support#1210]
### Project URL

https://pypi.org/project/pynini/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

180

### Which indexes

PyPI

### Reasons for the request

I have developed manylinux wheels for this package for CPython 3.6-9 but are unable to upload them. These are approximately 160 MB so I have requested 180 MB. I do not anticipate them growing in size much beyond this since this is a mature project and most of the size/bloat comes from an upstream C++ library.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `pynini` to 200 MB on PyPI.
