### ISSUE TITLE
PEP 541 Request: sling

### ISSUE THREAD

**Issue by flarco** [pypa/pypi-support#1211]
### Project to be claimed

`sling`: https://pypi.org/project/sling

### Your PyPI username

`flarco`: https://pypi.org/user/flarco

### Reasons for the request

It appears that the project has been abandoned:
- Last commit to Github repo is in 2015.
- Last release on Pypi is in 2015
- I attempted to email the author (support@slinghq.com) but got the following error:
  - `Your message couldn't be delivered to support@slinghq.com because the remote server is misconfigured. See technical details below for more information.`
- The author's company seems to be out of business, as the domain isn't working (http://slinghq.com)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/slinghq/sling

### Contact and additional research

- I attempted to email the author (support@slinghq.com) but got the following error:
  - `Your message couldn't be delivered to support@slinghq.com because the remote server is misconfigured. See technical details below for more information.`
- The author's company seems to be out of business, as the domain isn't working (http://slinghq.com)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by flarco** [comment]
Hi @yeraydiazdiaz could you please take a look, hopefully this is a clear case for proceeding.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @jpanganiban as well

**Comment by flarco** [comment]
Hi @yeraydiazdiaz, any progress on this?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
