### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rowanbarrie** [pypa/pypi-support#1212]
### PyPI Username

linz

### Reason for request

Hi there,

I am a developer at [Land Information New Zealand / Toitū Te Whenua](https://www.linz.govt.nz/) and would like to claim the username [linz](https://pypi.org/user/linz/) for our organisation.

It's unclear whether this user already belongs to a LINZ email address (...@linz.govt.nz) or not - if not would it be possible to claim it anyway? I can't see how old the account is but it appears they haven't uploaded any projects to PyPI.

Thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by yeraydiazdiaz** [comment]
Hi @rowanbarrie, I can confirm the username `linz` does not have an email address under that domain.

There is no process for claiming usernames in PyPI at the moment, I'm afraid you'll have to pick a different username.
