### ISSUE TITLE
Account recovery request to https://test.pypi.org/

### ISSUE THREAD

**Issue by moshe-shahar** [pypa/pypi-support#1214]
### PyPI Username

`moshe-shahar`

### Reason for request

I have lost my 2FA authentication app and therefor can't access my account on https://test.pypi.org/.
I have the access to my email, the password to the site and even the api-key to upload files, but I forgot to generate recovery codes to the https://test.pypi.org/.
Please help me recover that account.

Thank you in advance,
Moshe

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA reset for moshe-shahar User on test.pypi.org

**Comment by moshe-shahar** [comment]
@ewdurbin, thank you very much!
