### ISSUE TITLE
PEP 541 Request: Flask -Images

### ISSUE THREAD

**Issue by lalarustamli** [pypa/pypi-support#1215]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/Flask-Images/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/lalarustamli

### Reasons for the request

The package is not compatible with latest version of itsdangerous and produces errors. It hasn't been upgraded for a long time and I tried to contact with the owner through github and mail, but he doesn't repond. 

We have been successfully using our version from Github repo(https://github.com/mikeboers/Flask-Images/pull/58) in our project

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/mikeboers/Flask-Images
https://github.com/mikeboers/Flask-Images/pull/58

### Contact and additional research

I have emailed webinquiry@mikeboers.com and flask_images@mikeboers.com but didn't get any response

![image](https://user-images.githubusercontent.com/23105462/126310032-d4a8af13-3a95-4c7f-87da-03633bd2c8f5.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I will now start the reachability process with the owner

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @mikeboers

**Comment by mikeboers** [comment]
Hi folks.

First, I'm sorry for not being responsive. I meant to get around to it (@lalarustamli's emails are some of the few that have lived in my inbox keeping me from inbox-zero for quite a while), but I didn't. They had good intentions, made a lot of effort to contact me, and I didn't do anything publicly in response.

Thank you @yeraydiazdiaz for going through this process as well. I'm sorry to have made this difficult for everyone.

I'm not sure what I want to do here. I do assert that the project is not abandoned, but also accept I've not been a good maintainer.

What I see as my options are:

1. Put the effort in to vet and merge the various PRs, and commit to being responsive in the future to this sort of thing.
2. Fully relinquish the project to @lalarustamli
3. Some sort of middle ground, where @lalarustamli is a maintainer with commit access on the repo and upload on PyPI.

I'll think about it and do something reasonably soon, but I very much welcome feedback.

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @mikeboers, I will now close this issue as contact has been made.

**Comment by lalarustamli** [comment]
Thanks for reply @mikeboers, and thanks for helping this @yeraydiazdiaz 
All your solutions work for me, as we use this package actively in our project, we get a great value from it, and prefer to use it from pypi instead of our repo in future. But option 3 seems like the safest bet.
You can contact me through mail (rustamlilala@gmail.com) whenever it is possible to solve this.
