### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AlexFrid** [pypa/pypi-support#1216]
### PyPI Username

`AlexFrid`

### Reason for request

Lost 2FA authentication app or security token: changed phones and forgot to migrate codes to new phone
I've added a picture of the email for when I set up the 2FA, if that helps in the recovery process

![image](https://user-images.githubusercontent.com/11931107/126323771-5be9ce71-6f31-4dab-9c1b-68063c9acad2.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
