### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by robertkowalski** [pypa/pypi-support#1218]
### PyPI Username

`Bitfinex`

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by robertkowalski** [comment]
any news on this?

**Comment by robertkowalski** [comment]
//cc @vigan-abd

**Comment by pradyunsg** [comment]
Hi there! This issue tracker (much like _most_ of PyPI) is maintained and managed by volunteers, who have limited availability. Please don't create duplicate issues, increasing the amount of work that the volunteers (such as myself) have to do.

It usually takes quite a while for the relevant folks to catch up to the backlog of account recovery issues. I'd appreciate if you could be patient here. Each request requires a round of identity verification, via the emails, to make sure we don't reset the auth upon request of not-the-account-owner).

I'll note that neither Yeray nor myself have the required access on PyPI to trigger an authentication reset (which is what is necessary here).

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
It appears that the primary email address associated with the `Bitfinex` User is bouncing. Please contact support@pypi.org including a link to this GitHub issue to discuss alternative steps for Account Recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. Email address has been updated and you should be able to regain access to your account after completing the password reset and verifying the new address.
