### ISSUE TITLE
PEP 541 Request: tests

### ISSUE THREAD

**Issue by Endercheif** [pypa/pypi-support#1219]
### Project to be claimed

`tests`: https://pypi.org/project/tests

### Your PyPI username

`endercheif`: https://pypi.org/user/endercheif

### Reasons for the request

I assume that this project was used as a test repository to publish test out uploading to pypi. 
The only code in the project:
```python
# MyApp.py
print("Hello Burton and Marty!")
gone=input("Enter to close: ")

```
This project was never meant to be maintained or used publicly. The username is `testing9812`. The website which is linked as the [homepage](https://propython.com) is for sale and the authors' email has the same expired domain. There is no contact information on the project that can be used.

### Maintenance or replacement?

Replacement

### Contact and additional research

- The website which is linked as the [homepage](https://propython.com) is for sale 
- The authors' email (authors@propython.com) has the same expired domain. 
- There is no other contact information on the project page.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @Endercheif, I can confirm the project has no funcionality and is therefore considered invalid. I will attempt contact with the owner letting them know of this fact and allow one week for replies before proceeding with the transfer.

**Comment by Endercheif** [comment]
@yeraydiazdiaz Is there any update?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
