### ISSUE TITLE
2FA beta user needs account recovery

### ISSUE THREAD

**Issue by letuananh** [pypa/pypi-support#122]
Dear PyPI team,

I'm a package maintainer on PyPI and I have opted to use 2FA method for my account. Recently when I tried to access my account via the web interface the 2FA code stopped working suddenly. 

The generator app on my phone is still running fine and generating new codes, but the website keeps prompting `Invalid TOTP code`. This seems to affect only the web interface. It seems that I can still update my packages via twine on my terminal. 

I'd really appreciate your help and hope that someone will guide me on how to regain access to my account via the web-based interface. Thank you very much.

**Comment by ewdurbin** [comment]
Hello @letuananh, please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by letuananh** [comment]
Hi @ewdurbin thanks so much for your help. I have sent the email to the mentioned address. Please let me know if there is something else that needs to be done.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

**Comment by ocefpaf** [comment]
Sorry for commenting on a closed issue but it seems that I have the same issue as @letuananh. What can I do to recover my account.

PS: somehow I can reset the password, but the code still does not verify.

**Comment by ewdurbin** [comment]
@ocefpaf please [open a new issue](https://github.com/pypa/pypi-support/issues/new/choose) and select the Account Recovery type.
