### ISSUE TITLE
Limit Request: grpcio - 50000MB

### ISSUE THREAD

**Issue by gnossen** [pypa/pypi-support#1220]
### Project URL

https://pypi.org/project/grpcio/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

50000MB

### Which indexes

PyPI

### Reasons for the request

gRPC (`grpcio` on PyPI) is a highly popular project with many users, including `tensorflow`. Since our project is a C extension supporting many platforms, each release takes up quite a bit of space. The latest release is 123 artifacts totalling 745 MB. As of this release, we are hitting our current 20GB limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by gnossen** [comment]
@di

**Comment by gnossen** [comment]
CC @lidizheng @srini100

**Comment by di** [comment]
I've increased the total project size limit for `grpcio` to 30GB, for now, and we can revisit when the project gets close to the limit again.

I see that `grpcio` is currently publishing releases for Python 2 and 3.5, is there any plan to drop support for these EOL Python versions?
