### ISSUE TITLE
Limit Request: PyKaldi - 400 MB

### ISSUE THREAD

**Issue by Alienmaster** [pypa/pypi-support#1221]
### Project URL

https://pypi.org/project/PyKaldi/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

400

### Which indexes

PyPI

### Reasons for the request

Hi,
i made a mistake by measuring the size of the Wheel. The linux x64 Wheel is 260MB and the manylinux Wheel is 330MB big as you can see here: http://ltdata1.informatik.uni-hamburg.de/pykaldi_tmp/ .

An increase of the Releases up to 400MB would be great.

Best wishes,
Robert

See also: #1122 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `PyKaldi` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by bmilde** [comment]
Thanks!
