### ISSUE TITLE
PEP 541 Request: django-iam

### ISSUE THREAD

**Issue by keyvanm** [pypa/pypi-support#1222]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/django-iam

### Your PyPI username

`USER_NAME`: https://pypi.org/user/keyvanm

### Reasons for the request

It seems like the package `django-iam` has been abandoned by its current owner:

- Going to https://pypi.org/project/django-iam returns a 404
- Not possible to install the package using pip
```
$ pip install django-iam
ERROR: Could not find a version that satisfies the requirement django-iam (from versions: none)
ERROR: No matching distribution found for django-iam
```
- No results for `django-iam` in https://pypi.org/search/?q=django-iam
- A result shows up on https://libraries.io/pypi/django-iam/ but
    - The homepage link (https://www.digitalcitizen.nl/) goes to a coming soon page and is just a bootstrap theme called [Front](https://themes.getbootstrap.com/product/front-multipurpose-responsive-template/)
    - The last release is Nov 2019
    - Cannot find the author's name or contact information. Whois lookup for their website returns a privacy protected entry
- I couldn't find the source code for this package. It seems like the author has completely removed their releases from PyPI and the internet.  

I would like to publish https://github.com/kaoslabsinc/django-iam/ to PyPI under the name `django-iam`, since the current owner of this package name has abandoned and removed their releases from PyPI. 

Thanks for taking the time to read my request!

P.S. I have already published some pre-release versions to Test PyPI under the same name https://test.pypi.org/project/django-iam/

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/kaoslabsinc/django-iam

### Contact and additional research

I couldn't find the current owner for the following reasons:

- Going to https://pypi.org/project/django-iam returns a 404
- No results for `django-iam` in https://pypi.org/search/?q=django-iam
- A result shows up on https://libraries.io/pypi/django-iam/ but
    - Cannot find the author's name or contact information. Whois lookup for their website returns a privacy protected entry (https://www.sidn.nl/en/whois?q=digitalcitizen.nl&lang=en)
- Googling "django-iam" doesn't return anything related to this PyPI package

Thus I could not find the current owner and contact them.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @keyvanm , I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner letting them know of this fact and allow one week for replies before proceeding with the transfer.

**Comment by keyvanm** [comment]
Hi @yeraydiazdiaz, wondering since it's been more than a week, if you heard anything back and if we can move forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
