### ISSUE TITLE
Limit Request: cmdstan-builder - 180MB

### ISSUE THREAD

**Issue by ParthivNaresh** [pypa/pypi-support#1226]
### Project URL

https://pypi.org/project/cmdstan-builder

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

180 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

I'm attempting to upload a wheel that contains a fairly large package called `Stan`. This package is a library responsible for providing many of the math functions that we rely on for inferencing and optimization. It's meant to support one of our dependencies that requires access to the Stan package through `cmdstanpy` which is a python interface to `cmdstan`, which in turn is a shell interface to Stan. Currently the compiled wheel reaches 171.2 MB.

So far I've tried numerous approaches to this, such as attempting to break up the installation procedure into multiple steps in our main project, or uploading it as a tarball. Unfortunately this brings the installation overhead downstream to the user and increases the installation time for our main project tremendously. Using alternative libraries such as `PyStan` causes us to run into a licensing issue as it is GPL v3 and `CmdStanPy` is BSD-3 Clause.

We're trying to find a solution that can fix our dependency issue as well as provide the open source community with a workaround for the same problem we're facing. I believe uploading a wheel to PyPI fixes this by providing an alternative that would be beneficial to both objectives.

This project will have fairly infrequent releases, most likely one every 3 or 4 months.

This project is meant to support the company Alteryx (of which I am an employee).
Alteryx GitHub: https://github.com/alteryx

I've uploaded a tarball of the project at https://pypi.org/project/cmdstan-builder.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ParthivNaresh** [comment]
@di Hi, any help with this would be greatly appreciated :)

**Comment by di** [comment]
I've set the upload limit for `cmdstan-builder` to 200 MB on PyPI and TestPyPI.
