### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by genesisthomas** [pypa/pypi-support#1229]
### PyPI Username

genesist

### Reason for request

Lost 2FA authentication app in my new phone as I forgot to take backup of Authenticator app in iCloud. Hence requesting re-setting of Authentication app. I have access to my account for uploading newer versions of my pip libraries using my username and password but unable to login via UI in order to make changes to other pip packages. Please help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
