### ISSUE TITLE
Lost 2FA Application

### ISSUE THREAD

**Issue by rmorshea** [pypa/pypi-support#123]
I'm unable to access https://pypi.org/user/rmorshea/ because I lost my 2 factor authentication application after my phone died. I saw in pypa/warehouse#5758 that I had to create a new issue until there are better options for account recovery. Just let me know what's required in order to get back in. Thanks!

*In the future I'll be sure to set up recovery codes (not sure if that was available at the time I set it up)*

**Comment by ewdurbin** [comment]
Hello @rmorshea, please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
