### ISSUE TITLE
Change username (case sensitivity only)

### ISSUE THREAD

**Issue by honno** [pypa/pypi-support#1230]
### PyPI Username

Honno

### Reason for request

I would like to change my PyPI username [Honno](https://pypi.org/user/Honno/) to the fully lowercase "honno", if this is still possible ala pypa/pypi-support#73. Thanks :)

(I apologise for using this template but there is no appropriate template and seemingly no way to omit using these.)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
done.

**Comment by ewdurbin** [comment]
Note: Unfortunately it seem that these kinds of changes are no longer as easily accomplished, especially for users with many projects or a long history on PyPI. Changes to our schema have made it so the necessary update cascades through all JournalEntry objects for all Projects owned by the user.
