### ISSUE TITLE
PEP 541 Request: koan

### ISSUE THREAD

**Issue by SchoolGuy** [pypa/pypi-support#1231]
### Project to be claimed

`koan`: https://pypi.org/project/koan

### Your PyPI username

`SchoolGuy`: https://pypi.org/user/SchoolGuy

### Reasons for the request

There is no release created for that project `koan`.

I do get [this](https://github.com/cobbler/koan/runs/3170319992?check_suite_focus=true#step:9:21) error message from PyPi. I am using a token valid for all projects.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Github Project: https://github.com/cobbler/koan

### Contact and additional research

I did not find any project with the name `koan` on PyPi, so I don't know whom to contact.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by SchoolGuy** [comment]
I did also try this manually on my local machine and I get the same results as the CI shows:

```
(venv) [13:16:41] enno@bussybox /home/enno/Sources/PyCharm_Projects/koan (1) 
> twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: __token__
Enter your password: 
Uploading koan-3.0.1.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.3k/48.3k [00:00<00:00, 69.9kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'koan' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

**Comment by encukou** [comment]
`koan` was reserved in #355 for https://github.com/cobbler/koan and @ShoolGuy is the main developer there.
@di, could you unblock the name?

**Comment by di** [comment]
I've released `koan` to `SchoolGuy.
