### ISSUE TITLE
PEP 541 Request: spectro

### ISSUE THREAD

**Issue by nschloe** [pypa/pypi-support#1232]
### Project to be claimed

`spectro`: https://pypi.org/project/spectro

### Your PyPI username

`nschloe`: https://pypi.org/user/nschloe

### Reasons for the request

When trying to upload to `spectro`, one gets
```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'nschloe' isn't allowed to upload to project 'spectro'. See https://pypi.org/help/#project-name for more information.
```
It is unclear to me why that happens. The help page lists as possible reasons:

> * The project name conflicts with a Python Standard Library module from any major version from 2.5 to present.
> * The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.
> * The project name has been registered by another user, but no releases have been created.

I'm not aware of any Python packages with a similar name, don't see why the name should be prohibited, nor can I see a user registration.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/nschloe/spectro

### Contact and additional research

The project has apparently not been claimed.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @nschloe, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner letting them know of this fact and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
