### ISSUE TITLE
PEP 541 Request: dexter

### ISSUE THREAD

**Issue by igormagalhaesr** [pypa/pypi-support#1233]
### Project to be claimed

`dexter`: https://pypi.org/project/dexter

### Your PyPI username

`igormagalhaesr`: https://pypi.org/user/igormagalhaesr

### Reasons for the request

I'm requesting the name for a project of mine since the name is abandoned.

Tried reaching the owner without success 
There hasn't been new releases for the past 9 years (actually even the first release has no description of any sort)
There hasn't been any activities on the project's home page
There hasn't been any issues requesting this name

So, by PEP 541 standards, I'd like to request this abandoned name. 

### Maintenance or replacement?

Replacement

### Contact and additional research

I tried contacting the owner even on social network (couldn't find email) and he didn't answer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @igormagalhaesr, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner letting them know of this fact and allow one week for replies before proceeding with the transfer.

**Comment by igormagalhaesr** [comment]
Hey, @yeraydiazdiaz 
Any update?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
