### ISSUE TITLE
PEP 541 Request: PYJAMAS

### ISSUE THREAD

**Issue by rfg-lab** [pypa/pypi-support#1234]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/Pyjamas/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rodrigofg

### Reasons for the request

We are a research laboratory at the University of Toronto. We develop a software package for microscopy image analysis. We used to develop the software in Matlab/C (SIESTA-Scientific ImagE SegmenTation and Analysis), but a couple of years ago we moved it to Python and we renamed the package PyJAMAS (PYjamas is Just A More Awesome Siesta). The package is available on PyPI as pyjamas-rfglab (https://pypi.org/project/pyjamas-rfglab/) and on bitbucket (https://bitbucket.org/rfg_lab/pyjamas). We would like to use the "pyjamas" name on PyPI, as that would facilitate google searches, etc.

The "pyjamas" name on PyPI belongs to a package that was renamed to pyjs in 2012. We contacted the maintainers listed on the PyPI site and they all confirmed that the project is not active any more. The last release of "pyjamas" on PyPI was on April 2012. The last release of pyjs (pyjs.org) was in May 2012. They confirmed that they were OK with the name transfer (correspondence provided below). There was some confusion as to who "owned" the name, so they suggested going directly through PyPI for a name transfer. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Our code is available here: https://bitbucket.org/rfg_lab/pyjamas

### Contact and additional research

**Email exchange with Luke Kenneth Casson Leighton (listed as maintainer https://pypi.org/project/Pyjamas):**

Begin forwarded message:

From: Luke Kenneth Casson Leighton <lkcl@lkcl.net>
Subject: Re: pyjamas pypi package
Date: July 13, 2021 at 15:46:18 EDT
To: Rodrigo Fernandez-Gonzalez <rodrigo.fernandez.gonzalez@utoronto.ca>
Cc: "anthon.van.der.neut@ruamel.eu" <anthon.van.der.neut@ruamel.eu>, "c@anthonyrisinger.com" <c@anthonyrisinger.com>

EXTERNAL EMAIL:

hi rodriguo,

the domain was hijacked and the user database criminally transferred
out of the UK without consent by Risinger.

i do not recommend getting involved with him or contacting him fir any purpose.

l.

On 7/13/21, Rodrigo Fernandez-Gonzalez
<rodrigo.fernandez.gonzalez@utoronto.ca> wrote:
Hi!

My name is Rodrigo, I am a prof at the University of Toronto. My lab
develops a software package for microscopy image analysis. We used to
develop the software in Matlab/C (SIESTA-Scientific ImagE SegmenTation and
Analysis), but a couple of years ago we moved it to Python and we renamed
the package PyJAMAS (PYjamas is Just A More Awesome Siesta).

So you probably see where I am going. I notice that your pyjs project used
to be named pyjamas, and still retains the pypi name. I was wondering if you
would consider giving up the pyjamas name on pypi? There is a process for
this, outlined in PEP 541
(https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer).
I am happy to explore that process, but only if you are OK with this. No
pressure, we currently have the package on pypi as pyjamas-rfglab, and that
is OK. Having the pypi name would make pypi and google searches a bit less
frustrating for some of our users, who run into the old version of your
package instead of ours.

Thanks for considering!

Rodrigo
--
Rodrigo Fernandez-Gonzalez
Associate Professor
Canada Research Chair in Quantitative Cell Biology and Morphogenesis (Tier
II)
Institute of Biomedical Engineering
Department of Cell and Systems Biology
Ted Rogers Centre for Heart Research
University of Toronto
MaRS 2 - West Tower
661 University Ave. 14th Floor
Toronto, ON
M5G 1M1
Canada

p. 416-978-7368
w. quantmorph.ca

**Email exchange with C. Anthony Risinger (listed as responsible for the project pyjs.org)**

Apologies! This slipped my mind, and when I tried to take care of it for you, I [re]discovered that we never did wrest control of that name from him. That was some of the impetus for moving to "pyjs".

So it looks like you'll need to reach out to Luke again, or just go directly to PyPI. I know which one I would choose. I truly am sorry for whatever comes next, but I do hope you get it worked out! They probably remember him and/or the situation. They offered to take control of the domain, and host things there, but by then he had already spun serious lies and it wasn't clear to everyone until later. He has a long-standing... uhm, history, in the Python community and elsewhere, it doesn't take too many searches to find it. Luke to this day is the only person to ever be ejected from the WebKit project and banned from all communication channels; he is a difficult character to say the least.

Good luck!

On Tue, Jul 13, 2021 at 9:13 PM Rodrigo Fernandez-Gonzalez <rodrigo.fernandez.gonzalez@utoronto.ca> wrote:
Thanks Anthony, sorry to hear about the situation with your project, I was just reading a bit about it. 

My user name in pypi is rodrigofg.

You can checkout our pyjamas repository here https://bitbucket.org/rfg_lab/pyjamas/ 

And the documentation is here pyjamas.readthedocs.io.

Thanks again!

Rodrigo
-- 
Rodrigo Fernandez-Gonzalez
Associate Professor
Canada Research Chair in Quantitative Cell Biology and Morphogenesis (Tier II)
Institute of Biomedical Engineering
Department of Cell and Systems Biology
Ted Rogers Centre for Heart Research
University of Toronto
MaRS 2 - West Tower
661 University Ave. 14th Floor
Toronto, ON
M5G 1M1
Canada

p. 416-978-7368
w. quantmorph.ca

> On Jul 13, 2021, at 22:03, C Anthony Risinger <c@anthonyrisinger.com> wrote:
> 
> EXTERNAL EMAIL:
> It's definitely not in use. And no worries at all. If anything, you have given me impetus to archive the thing and be done with it once and for all, instead of paying for all the domains and whatnot for another 10 years.
> 
> We don't necessarily have to go through PyPI admin to transfer ownership, I think I can just give you ownership through the web interface, I'll look. Send me any administrative emails or usernames you use on PyPI and I'll take a peek.
> 
> Can you send me any links you might think important on your Pyjamas? I should probably do a tiny bit of due diligence on your project, but this day and age it almost certainly has more relevancy than what I used to call Pyjamas. I'm not sure the code functions anymore, and if it does, I'm not sure how much I care.
> 
> Thanks,
> 
> 
> 
> On Tue, Jul 13, 2021, 8:57 PM Rodrigo Fernandez-Gonzalez <rodrigo.fernandez.gonzalez@utoronto.ca> wrote:
> Hmmm, yes, sorry about that, I was not sure who was the owner of the pypi name, as all of those emails appear associated with the project in one place or another. Apologies for that.
> 
> Anyway, yes, I’d be interested in exploring the transfer of the pypi name (I say exploring because apparently it is not trivial for them to approve). To get started, I would need confirmation of your willingness to accept the transfer (an email is probably sufficient). As I mentioned, we are OK with the status quo if you are still using the old name for your package, but if you are not, we will check with pypi. Just let me know.
> 
> Thanks!
> 
> Rodrigo
> 
> 
> > On Jul 13, 2021, at 21:17, C Anthony Risinger <c@anthonyrisinger.com> wrote:
> > 
> > EXTERNAL EMAIL:
> > I'm not going to launch into a backstory, but needless to say, the actual owner of the domain (which was not Luke) gave it to me. Luke was in the process of being ejected by a project's own community, but he has long-blamed me personally for it. There was no concealment of anything, and it was entirely public, and documented elsewhere on the Internet.
> > 
> > I am happy to talk about transferring the PyPI name, but you'll need to reach out to me on this thread and not the other one because you kind of opened up a canna worms 😅
> > 
> > To be clear though, I am the owner and controller of everything related to the project, from the domain to the PyPI names, and I would not work with Luke much further on this endeavor unless you want to go in circles.
> > 
> > Thanks,
> > 
> > 
> > On Tue, Jul 13, 2021 at 2:08 PM Rodrigo Fernandez-Gonzalez <rodrigo.fernandez.gonzalez@utoronto.ca> wrote:
> > Hi!
> > 
> > My name is Rodrigo, I am a prof at the University of Toronto. My lab develops a software package for microscopy image analysis. We used to develop the software in Matlab/C (SIESTA-Scientific ImagE SegmenTation and Analysis), but a couple of years ago we moved it to Python and we renamed the package PyJAMAS (PYjamas is Just A More Awesome Siesta). 
> > 
> > So you probably see where I am going. I notice that your pyjs project used to be named pyjamas, and still retains the pypi name. I was wondering if you would consider giving up the pyjamas name on pypi? There is a process for this, outlined in PEP 541 (https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer). I am happy to explore that process, but only if you are OK with this. No pressure, we currently have the package on pypi as pyjamas-rfglab, and that is OK. Having the pypi name would make pypi and google searches a bit less frustrating for some of our users, who run into the old version of your package instead of ours.
> > 
> > Thanks for considering!
> > 
> > Rodrigo 
> > -- 
> > Rodrigo Fernandez-Gonzalez
> > Associate Professor
> > Canada Research Chair in Quantitative Cell Biology and Morphogenesis (Tier II)
> > Institute of Biomedical Engineering
> > Department of Cell and Systems Biology
> > Ted Rogers Centre for Heart Research
> > University of Toronto
> > MaRS 2 - West Tower
> > 661 University Ave. 14th Floor
> > Toronto, ON
> > M5G 1M1
> > Canada
> > 
> > p. 416-978-7368
> > w. quantmorph.ca
> > 
> > 
> > 
> > -- 
> > 
> > C Anthony
> 

-- 

C Anthony

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @rfg-lab, thanks for the details report. Moderators must attempt contact with the current owner, so I'm starting the reachability process for the project. Hopefully we will hear back from him soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied stating they will do not accept the transfer, PEP 541 explicitly states transfer must not be performed against the owner's whishes.

**Comment by rfg-lab** [comment]
Thanks Yeray, may I know who the official owner of the name is? We contacted everyone listed on the pypi site and they all referred to each other, and yet, seemed to be OK with the transfer, so their response now is quite surprising.

Thanks again!

Rodrigo
-- 
Rodrigo Fernandez-Gonzalez
Associate Professor
Canada Research Chair in Quantitative Cell Biology and Morphogenesis (Tier II)
Institute of Biomedical Engineering
Department of Cell and Systems Biology
Ted Rogers Centre for Heart Research
University of Toronto
MaRS 2 - West Tower
661 University Ave. 14th Floor
Toronto, ON
M5G 1M1
Canada

p. 416-978-7368
w. quantmorph.ca

**Comment by yeraydiazdiaz** [comment]
The owner of the `pyjamas` project in PyPI is user [`lkcl`](https://pypi.org/user/lkcl/) and that is the point of contact for moderators as per PEP 541. I understand you have been in contact with the owners of pyjs and they may be happy with the transfer, but unfortunately they don't control the `pyjamas` project in PyPI.

Of course, this is my interpretation of the request, if any other moderators or @pypa/warehouse-admins think differently they're welcome to re-open this request.

**Comment by rfg-lab** [comment]
Thanks Yeray, that is useful to know. 

Rodrigo
-- 
Rodrigo Fernandez-Gonzalez
Associate Professor
Canada Research Chair in Quantitative Cell Biology and Morphogenesis (Tier II)
Institute of Biomedical Engineering
Department of Cell and Systems Biology
Ted Rogers Centre for Heart Research
University of Toronto
MaRS 2 - West Tower
661 University Ave. 14th Floor
Toronto, ON
M5G 1M1
Canada

p. 416-978-7368
w. quantmorph.ca
