### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by martinbagic** [pypa/pypi-support#1238]
### PyPI Username

`martinbagic`

### Reason for request

I lost the access to my 2FA. I still have access to my email and the password. I also have access to PyPI-Recovery-Codes. Can you help me restore my account? Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
