### ISSUE TITLE
PEP541: Transfer ownership of empty "pyharp" package

### ISSUE THREAD

**Issue by luminoctum** [pypa/pypi-support#124]
**Project to be claimed**

`pyHarp`: https://pypi.org/project/pyHarp

**Your PyPI username**

`cli`: https://pypi.org/user/cli

**Reasons for the request**

The project has remained empty since 2013. I would like to use the name for packaging my software, whose description is detailed in my published journal article: https://www.sciencedirect.com/science/article/abs/pii/S0022407318300554 

**Maintenance or replacement?**

The current package is empty. I would like to wrap my existing software and publish it to python. Here's the repository for my existing software: https://github.com/luminoctum/athena-harp

**Contact and additional research**

I have contacted the owner and received permission to take ownership of the package
![image](https://user-images.githubusercontent.com/4010653/71646881-b6774e00-2cbb-11ea-811b-192306e7ee2f.png)

**Comment by yeraydiazdiaz** [comment]
Hi @luminoctum, thanks for the screenshot of the email

However, there is _some_ functionality in the project so I'll need confirmation from @HarpB to move on with your request. I will email him myself as well.

**Comment by harpb** [comment]
I approve the transfer. Do you need anything else fro me?

**Comment by yeraydiazdiaz** [comment]
Hi @harpb thanks for confirming.

We'd appreciate it if you could perform the transfer yourself to reduce the load on our admins. You can do that by logging into PyPI and navigating to [`pyHarp`'s collaboration settings](https://pypi.org/manage/project/pyHarp/collaboration/), then fill in the "Add collaborator" form at the bottom with `cli` as the username and "Owner" as the role.

**Comment by yeraydiazdiaz** [comment]
@harpb could you take a minute to perform this transfer yourself please?

**Comment by luminoctum** [comment]
Hi, I got denied by using my log in credentials. Here's what I got.
![image](https://user-images.githubusercontent.com/4010653/74900158-c32b3080-5353-11ea-81e8-0d2e622cf855.png)

**Comment by ewdurbin** [comment]
transfer complete.
