### ISSUE TITLE
PEP 541 Request: aws-access

### ISSUE THREAD

**Issue by allenliu70** [pypa/pypi-support#1242]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/aws-access

### Your PyPI username

`USER_NAME`: https://pypi.org/user/allenliu

### Reasons for the request

This project hasn't been maintained for over a year (since June 2020). I tried to reach the maintainer, Rajib Deb, but received no response. Rajib Deb was working for my team in Cisco but had left the job for a while. We still use this project, aws-access, and need to update it in order to keep things running. Please transfer the ownership of this project to me so that my team can continue to maintain it. Thanks!

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/CON/repos/hyperloop/browse

### Contact and additional research

From: Allen Liu (allliu) <allliu@cisco.com> 
Sent: Thursday, July 29, 2021 11:01 AM
To: Tony Lin (dtlin) <dtlin@cisco.com>; rajib76@yahoo.com
Cc: Suhas Talathi -X (stalathi - INFOSYS LIMITED at Cisco) <stalathi@cisco.com>; Mounika Gorintla -X (mgorintl - INFOSYS LIMITED at Cisco) <mgorintl@cisco.com>
Subject: Re: FBN - Proxy Testing and debug on FBNTMGNGPPAD1

Hi Rajib,

We’re working on updating aws-access in Pypi.

Could you please add me, Tony, and/or Pranav as the project owners?

Thanks & Regards,
Allen

From: "Tony Lin (dtlin)" <dtlin@cisco.com>
Date: Tuesday, July 27, 2021 at 2:26 PM
To: "Mounika Gorintla -X (mgorintl - INFOSYS LIMITED at Cisco)" <mgorintl@cisco.com>, "Allen Liu (allliu)" <allliu@cisco.com>, "Pavan Vemulakonda (pavemula)" <pavemula@cisco.com>
Cc: "Suhas Talathi -X (stalathi - INFOSYS LIMITED at Cisco)" <stalathi@cisco.com>
Subject: Re: FBN - Proxy Testing and debug on FBNTMGNGPPAD1

Do you have Rajib’s current email? I got rajib76@yahoo.com from linkedin.
Maybe you can reach out to him to see if he can add additional maintainers?

Thanks,
Tony

From: "Mounika Gorintla -X (mgorintl - INFOSYS LIMITED at Cisco)" <mgorintl@cisco.com>
Date: Tuesday, July 27, 2021 at 1:05 PM
To: "Allen Liu (allliu)" <allliu@cisco.com>, "Tony Lin (dtlin)" <dtlin@cisco.com>, "Pavan Vemulakonda (pavemula)" <pavemula@cisco.com>
Cc: "Suhas Talathi -X (stalathi - INFOSYS LIMITED at Cisco)" <stalathi@cisco.com>
Subject: RE: FBN - Proxy Testing and debug on FBNTMGNGPPAD1

Hi Tony Lin,

We can’t be able to update aws-access package on pypi test server (https://test.pypi.org/legacy/) as Rajib Deb is the maintainer of this package so, he can only update this package using his https://test.pypi.org account API Token.

Regards
G. Mounika

**Comment by yeraydiazdiaz** [comment]
Hello @allenliu70 and @mounika-gorintla I will start the reachability process for your request which can take up to 6 weeks.

The project does have an additional owner https://pypi.org/user/lindaoi/ whose email address is associated with Cisco, it might be worth attempting internal contact if you can to speed things up.

**Comment by lindaoi** [comment]
Allen,

You should have access to the package, please verify.
Thanks,
Tony

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @lindaoi, I can see you've added @mounika-gorintla and @allenliu70 as maintainers, ideally they should be owners so they would have full control over the project.

Closing as contact has been made.
