### ISSUE TITLE
PEP 541 Request: gym-PBN

### ISSUE THREAD

**Issue by evangelos-ch** [pypa/pypi-support#1243]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/gym-PBN

### Your PyPI username

`USER_NAME`: https://pypi.org/user/evangelos-ch

### Reasons for the request

I wish to publish a package under this name and it seems that no package exists. Yet: 

```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'evangelos-ch' isn't allowed to upload to project 'gym-PBN'. See https://pypi.org/help/#project-name for more information.
```

I am not sure why this occurs. I did consult the FAQ but it definitely doesn't conflict with an internal Python library, neither does it seem to have any other package under that name on the website. Perhaps someone registered it but never made any releases?

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/evangelos-ch/gym-pbn

### Contact and additional research

There does not seem to be any current owner as the package 404s on PyPI. However... a team member of mine did originally author the package internally, put it on a GitHub repo at some point, then deleted the repo, and I have since taken over his code (which belongs to my team), cleaned it up and now wish to publish it. I suspect maybe he originally claimed the package name on PyPI, Hence why I am filing this under `Maintenance`. To my knowledge he currently has no internet access and is unreachable, so I cannot contact him about it.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @evangelos-ch, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner letting them know of this fact and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
