### ISSUE TITLE
Forgot the mail and its passwords i used to create account 5 years ago

### ISSUE THREAD

**Issue by bala** [pypa/pypi-support#1247]
### PyPI Username

ai

### Reason for request

Hi,
I had created an account pypi during my UG course but left the account unused. Recently i am trying to remember the email and passwords i used earlier but i couldn't remember. I am in need of this URL for my current opensource project use to publish some Machine Learning tools.
I request you to help me acquire it.
Regards
Balaji 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This account is associated with an @gmail.com address and was registered in April 2016. If you need additional information to try to remember your email address, please contact support@pypi.org and include a link to this issue.
