### ISSUE TITLE
Some packages visible in https://pypi.org/simple but otherwise vanished.

### ISSUE THREAD

**Issue by sbidoul** [pypa/pypi-support#1248]
I noticed today (Aug 7th 2021) that a few projects published by the Odoo Community Association (PyPi user OCA) seem to have partially vanished from PyPi, in the last 24h or so.

It looks like they are present in `https://pypi.org/simple` but otherwise not visible anymore:

-  they are not visible in our account page
-  they do not seem to be part of search results
- `https://pypi.org/simple/{project}` (which is present as a `href` in the simple index page) returns a 404
- `https://pypi.org/project/{project}` returns a 404 as well.
- trying to upload these with twine returns a 400 with `The name '{projecŧ}' isn't allowed.`.

I am not sure this is relevant, but these projects seem to have common that we created them for the first time around July 19th 2021.

I also see evidence in our logs that these projects were correctly reachable at least until around Aug 6th 2021 8:00 UTC.

Here is the list of projects exhibiting this strange behavior:

```
odoo12-addon-account-early-payment-discount
odoo12-addon-calendar-event-link-base
odoo12-addon-calendar-event-link-project-task
odoo12-addon-stock-move-packaging-qty
odoo13-addon-product-list-pricelist-price
odoo13-addon-project-duplicate-subtask
odoo13-addon-sale-automatic-workflow-delivery-state
odoo13-addon-sale-delivery-state
odoo13-addon-sale-order-line-input
odoo14-addon-account-payment-multi-deduction
odoo14-addon-agreement-stock
odoo14-addon-fetchmail-incoming-log
odoo14-addon-partner-aging
odoo14-addon-pos-margin
odoo14-addon-product-uom-updatable
odoo14-addon-purchase-minimum-amount
odoo14-addon-purchase-order-approval-block
odoo14-addon-purchase-order-approved
odoo14-addon-purchase-request-type
odoo14-addon-sale-order-general-discount
odoo14-addon-stock-partner-delivery-window
```

**Comment by di** [comment]
Hi, these were erroneously removed as part of an effort to prohibit project names declared as sub-dependencies of projects on PyPI that didn't actually exist. It looks like our analysis missed some legitimate namesquats like these. Sorry for the trouble! I've restored the following to the `OCA` user:

```
odoo12-addon-account-early-payment-discount
odoo12-addon-calendar-event-link-base
odoo12-addon-calendar-event-link-project-task
odoo12-addon-stock-move-packaging-qty
odoo13-addon-product-list-pricelist-price
odoo13-addon-project-duplicate-subtask
odoo13-addon-sale-automatic-workflow-delivery-state
odoo13-addon-sale-delivery-state
odoo13-addon-sale-order-line-input
odoo14-addon-account-payment-multi-deduction
odoo14-addon-agreement-stock
odoo14-addon-fetchmail-incoming-log
odoo14-addon-partner-aging
odoo14-addon-pos-margin
odoo14-addon-product-uom-updatable
odoo14-addon-purchase-minimum-amount
odoo14-addon-purchase-order-approval-block
odoo14-addon-purchase-order-approved
odoo14-addon-purchase-request-type
odoo14-addon-sale-order-general-discount
odoo14-addon-stock-partner-delivery-window
```

Just an FYI, we also prohibited the following names as well, which weren't being squatted by the OCA user, but are declared as dependencies of other packages on PyPI:

```
odoo10-addon-account-bank-statement-import-camt-oca
odoo10-addon-cmis-web
odoo10-addon-openeducat-activity
odoo10-addon-openeducat-admission
odoo10-addon-openeducat-assignment
odoo10-addon-openeducat-attendance
odoo10-addon-openeducat-core
odoo10-addon-openeducat-exam
odoo10-addon-openeducat-library
odoo10-addon-openeducat-parent
odoo10-addon-openeducat-timetable
odoo10-addon-payment-gateway-adyen
odoo10-addon-payment-gateway-paypal
odoo11-addon-runbot
odoo11-addon-storage-backend-sftp
odoo12-addon-muk-saas-branding
odoo12-addon-stock-location-attribute
odoo12-addon-stock-location-bin-name
odoo12-addon-stock-move-location-dest-constraint-empty
odoo12-addon-stock-move-location-dest-constraint-tag
odoo12-addon-stock-picking-type-routing-operation
odoo12-addon-stock-putaway-abc
odoo12-addon-stock-putaway-abc-move-location-dest-constraint
odoo12-addon-stock-putaway-recursive
odoo12-addon-stock-putaway-rule
odoo12-addon-stock-vertical-lift
odoo13-addon-muk-utils
odoo14-addon-account-invoice-import-facturx
odoo8-addon-jasper-reports
odoo8-addon-l10n-ar-perceptions
odoo8-addon-l10n-base
odoo8-addon-report-aeroo
odoo8-addon-report-hotel-reservation
odoo8-addon-runbot
odoo8-addon-shopinvader
odoo8-addon-web-action-request
odoo9-addon-runbot
odoo9-addon-web-action-request
```

I'd prefer to leave them on the prohibited list if you aren't planning to use them. If there's a subset you are planning to use, I can transfer these to the `OCA` user as well.

**Comment by sbidoul** [comment]
Hi Dustin, thanks a lot for the swift reaction and the efforts to protect PyPI users. I'll examine these other names and get back to you as some of them indeed belong to OCA.

**Comment by sbidoul** [comment]
@di, can you assign these to PyPI user `OCA` as they have siblings already in OCA ?

```
odoo8-addon-report-hotel-reservation
odoo10-addon-account-bank-statement-import-camt-oca
odoo10-addon-openeducat-activity
odoo10-addon-openeducat-admission
odoo10-addon-openeducat-assignment
odoo10-addon-openeducat-attendance
odoo10-addon-openeducat-core
odoo10-addon-openeducat-exam
odoo10-addon-openeducat-library
odoo10-addon-openeducat-parent
odoo10-addon-openeducat-timetable
odoo11-addon-storage-backend-sftp
odoo12-addon-stock-location-bin-name
odoo12-addon-stock-vertical-lift
odoo14-addon-account-invoice-import-facturx
```

<details>
  <summary>Here are the GitHub links to the sibling names, as evidence:</summary>
<pre>
 account_bank_statement_import_camt_oca | https://github.com/OCA/bank-statement-import/tree/10.0/account_bank_statement_import_camt_oca
 account_bank_statement_import_camt_oca | https://github.com/OCA/bank-statement-import/tree/12.0/account_bank_statement_import_camt_oca
 account_bank_statement_import_camt_oca | https://github.com/OCA/bank-statement-import/tree/11.0/account_bank_statement_import_camt_oca
 account_bank_statement_import_camt_oca | https://github.com/OCA/bank-statement-import/tree/13.0/account_bank_statement_import_camt_oca
 account_invoice_import_facturx         | https://github.com/OCA/edi/tree/12.0/account_invoice_import_facturx
 openeducat_activity                    | https://github.com/OCA/vertical-education/tree/9.0/openeducat_activity
 openeducat_admission                   | https://github.com/OCA/vertical-education/tree/9.0/openeducat_admission
 openeducat_assignment                  | https://github.com/OCA/vertical-education/tree/9.0/openeducat_assignment
 openeducat_attendance                  | https://github.com/OCA/vertical-education/tree/9.0/openeducat_attendance
 openeducat_core                        | https://github.com/OCA/vertical-education/tree/9.0/openeducat_core
 openeducat_exam                        | https://github.com/OCA/vertical-education/tree/9.0/openeducat_exam
 openeducat_library                     | https://github.com/OCA/vertical-education/tree/9.0/openeducat_library
 openeducat_parent                      | https://github.com/OCA/vertical-education/tree/9.0/openeducat_parent
 openeducat_timetable                   | https://github.com/OCA/vertical-education/tree/9.0/openeducat_timetable
 report_hotel_reservation               | https://github.com/OCA/vertical-hotel/tree/6.1/report_hotel_reservation
 report_hotel_reservation               | https://github.com/OCA/vertical-hotel/tree/7.0/report_hotel_reservation
 report_hotel_reservation               | https://github.com/OCA/vertical-hotel/tree/10.0/report_hotel_reservation
 report_hotel_reservation               | https://github.com/OCA/vertical-hotel/tree/11.0/report_hotel_reservation
 report_hotel_reservation               | https://github.com/OCA/vertical-hotel/tree/12.0/report_hotel_reservation
 report_hotel_reservation               | https://github.com/OCA/vertical-hotel/tree/13.0/report_hotel_reservation
 stock_location_bin_name                | https://github.com/OCA/stock-logistics-warehouse/tree/13.0/stock_location_bin_name
 stock_vertical_lift                    | https://github.com/OCA/stock-logistics-warehouse/tree/13.0/stock_vertical_lift
 storage_backend_sftp                   | https://github.com/OCA/storage/tree/10.0/storage_backend_sftp
 storage_backend_sftp                   | https://github.com/OCA/storage/tree/12.0/storage_backend_sftp
 storage_backend_sftp                   | https://github.com/OCA/storage/tree/14.0/storage_backend_sftp
 storage_backend_sftp                   | https://github.com/OCA/storage/tree/13.0/storage_backend_sftp
</pre>
</details>


Could you also assign

-  `odoo8-addon-shopinvader` to PyPI user [shopinvader](https://pypi.org/user/shopinvader/) as its siblings belong there ?
-  `odoo12-addon-muk-saas-branding` and `odoo13-addon-muk-utils` to PyPI user [mukit](https://pypi.org/user/mukit/)
- `odoo10-addon-cmis-web` to me (PyPI user [acsbidoul](https://pypi.org/user/acsbidoul/)) as this one is from my own company (https://github.com/acsone/alfodoo/tree/10.0/cmis_web), and we plan to publish them to PyPI in the near future

In OCA I'll see if we can add a check to avoid publishing packages with missing dependencies to PyPI.

In the longer term we'll also see if we can avoid these "Odoo version in package name", although it may not yet be possible with the current state of the pip resolver.

Finally, can you confirm to me it is *not* possible to manage these name reservation ourselves (such as, e.g. reserving odoo15-addon-{name}` when we publish `odoo14-addon-{name}` ?

Thanks again!

**Comment by di** [comment]
Done!

> Finally, can you confirm to me it is not possible to manage these name reservation ourselves (such as, e.g. reserving `odoo15-addon-{name}` when we publish `odoo14-addon-{name}`?

What you had been previously doing to reserve the names was fine (making a high release and deleting it), there is not currently a better way.

**Comment by sbidoul** [comment]
@di sorry to bother you again. There seems to be something wrong.

The projects in the initial list still seem to be invisible (e.g. https://pypi.org/project/odoo12-addon-account-early-payment-discount/ returns a 404). And I'm sure there where released files in (most of) these projects before.

> What you had been previously doing to reserve the names was fine (making a high release and deleting it), there is not currently a better way.

Also this is making me wonder if there is some sort of misunderstanding, because to the best of my knowlege OCA has never deleted releases on PyPI.

**Comment by di** [comment]
Hi @sbidoul, no worries, and my apologies because it looks like you're right. I'm not sure how our analysis missed that these packages had published releases, but it did. I'll review and ensure this won't happen again.

The good news is that the release files themselves are not gone. I've enumerated them [here](https://gist.github.com/di/1ce2e01433dbcfa5ba4cd8e185469c24), and anyone who's currently blocked on one of these missing can install directly from these URLs instead.

The bad news is that it's not as easy as a one-click restore on my end to bring these releases back on PyPI.

The easiest thing would be to do the following:
1. Whoever controls the `OCA` PyPI user account downloads all the wheels from the above URLs;
2. The file names are modified to add the optional [build tag](https://www.python.org/dev/peps/pep-0427/#file-name-convention) (the contents remain unchanged);
3. The new files are uploaded as usual.

This will have the effect of publishing the same files with the same hashes to the same versions and should restore anyone using these projects without needing to change anything.

If that won't work for some reason, we might have some other options, but that would be my preference.

**Comment by sbidoul** [comment]
Thanks. I confirm I can restore the affected releases with the proposed procedure. I'll close when I'm done.
