### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mangoess** [pypa/pypi-support#1249]
### PyPI Username

'mangoess'

### Reason for request

I have lost 2fa access to my pypi account, if it is not possible for my account to be given back, I'd also like it terminated so I can use my existing email for the new account.

The reason I'm writing this is because I have recently got a new phone, my previous phone with the authentication app with the pypi 2fa, Has been wiped and I no longer have access to it, the original phone isn't accessible for me anymore.
Now I can't get access to it as I don't have my recovery code on my laptop that I'm working on right now, I'd appreciate any support you have.

If you need to verify my identity please reply and let me know how I should do this

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mangoess** [comment]
Thank you! don't get me wrong, your feedback is incredible, but I hoped it'd take a little less then 90 days, but I bet you get a lot of account recoveries, I am forever grateful, will check now!

**Comment by ewdurbin** [comment]
I too wish it had taken less than 90 days.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
