### ISSUE TITLE
Account recovery: btskinner

### ISSUE THREAD

**Issue by btskinner** [pypa/pypi-support#125]
Hi team,

I have an application, [grm](https://pypi.org/project/grm/0.2.2/), that I've not updated in a while, but am looking to get back into. Unfortunately, I've changed institutions since I last updated it and no longer have access to the original contact email necessary to update my password (which I also no longer have). You can see that I maintain the [project's GitHub repo](https://github.com/btskinner/grm).

Can you update my email to my current? btskinner@coe.ufl.edu. This is the same email I use for GitHub.

Happy to send along any other information. Thanks for your help.

**Comment by btskinner** [comment]
Gentle reminder. If anyone can help, I'd appreciate it.

**Comment by ewdurbin** [comment]
Hello @btskinner. There is a second verified email address associated with your user account.

I've updated it to be the primary email address and issued a password reset, which should allow you to regain access to your account.

**Comment by btskinner** [comment]
That worked. Thanks for your time and help.
