### ISSUE TITLE
PEP 541 Request: secp256k1

### ISSUE THREAD

**Issue by rustyrussell** [pypa/pypi-support#1251]
### Project to be claimed

`secp256k1`: https://pypi.org/project/secp256k1

### Your PyPI username

`rusty`: https://pypi.org/user/rusty

### Reasons for the request

Abandoned: contacting author failed, no GH activity since 2017.

It's a wrapper around the C library libsecp256k1: https://github.com/bitcoin-core/secp256k1 which is actively developed and (finally!) approaching 1.0.  It would be great to actually get this package updated to match.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://pypi.org/project/secp256k1

### Contact and additional research

Emailed GH maintainer email "lud@tutanota.com" on 25-July-2021, no response (CC'd Jonas Nick <jonas@blockstream.com> one of the currently libsecp256k1 maintainers).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jarret** [comment]
I would like to assist @rustyrussell in doing some modernization.

**Comment by renepickhardt** [comment]
Concept ACK.

**Comment by darosior** [comment]
I confirm the `secp256k1` package is unusable, as i needed it several times in the past and had to fallback to alternatives. I also believe that Rusty would be a great maintainer for this package.
Concept ACK.

**Comment by fametrano** [comment]
Concept ACK

**Comment by yeraydiazdiaz** [comment]
Please stop posting empty comments on this issue, it will not help processing it faster.

**Comment by rustyrussell** [comment]
Note: Apparently Christian Decker attempted contact in Feb 2020, similarly with no response: https://twitter.com/Snyke/status/1424298514394370054?s=20

**Comment by yeraydiazdiaz** [comment]
I have started the reachability process for this request, hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The email address is no longer active and I can't seem to find reliable ways of contacting the author. Given the transfer if for maintenance I have added @rustyrussell  as an owner to the project.
