### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thatandromeda** [pypa/pypi-support#1253]
### PyPI Username

`thatandromeda`

### Reason for request

I lost access to my 2FA app. (My old phone bricked itself.) I don't have recovery codes.

I still have access to my email account, and my password still works on the command line (I just twine-uploaded something).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
