### ISSUE TITLE
Limit Request: dependency-injector - 20 000 MB

### ISSUE THREAD

**Issue by rmk135** [pypa/pypi-support#1254]
### Project URL

https://pypi.org/project/dependency-injector/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20 000MB

### Which indexes

PyPI

### Reasons for the request

Hey PyPI Support Team,

It's Roman, the creator of [Dependency Injector](https://github.com/ets-labs/python-dependency-injector).

I'm working the project since 2015 and did a lot of releases. 317 if count by tags on GitHub. Early versions of the project were on pure Python, but version 3 and version 4 are in Cython. Since Jul 1, 2020 I started to provide wheels for all supported Python versions. Seems like that it increased the size of each release. Today I hit project size of 10 GB and wasn't able to release a new version. I dropped some of very old versions, but this doesn't help a lot.

If that's possible, please increase project size to 20 GB or to any other amount that you think is reasonable.

Respectfully,
Roman

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `dependency-injector` to 20 GB on PyPI. I would strongly recommend working towards dropping support for Python versions that are past EOL (2.7, 3.5).

**Comment by rmk135** [comment]
Thank you @di . Yes, that's on my list now. I'm also going to limit number of releases by introducing a stricter release schedule. I never had an idea that PyPI volume is a limited resource. Will treat it accurately from now. Thanks!
