### ISSUE TITLE
Limit Request: MegEngineLite - 20GB

### ISSUE THREAD

**Issue by chenqy4933** [pypa/pypi-support#1256]
### Project URL

https://pypi.org/project/MegEngineLite/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20G

### Which indexes

PyPI

### Reasons for the request

Just like https://pypi.org/project/MegEngine/ ，
* MegEngineLite also contain the same CUDA GPU code which will be built with many sm，like sm 6.1，7.5.... so the whl package reach 1G per one python version and one release.
* Except the whl contain CUDA，the whl package is so tiny，just 15M
* The reason why need 20G is same as https://github.com/pypa/pypi-support/issues/767 ，list below：

         There are 12 files in one version, around 6.7GB in total.

         4 of them are Linux package for 3.6 - 3.8, each one's size is around 820MB
         4 of them are macOS package for 3.6 - 3.8, each one's size is around 15MB (No CUDA support)
         4 of them are Windows package for 3.6 - 3.8, each one's size is around 820MB

In order to convenient use MegEngineLite to inference MegEngine model，we need upload the MegEngineLite whl with the same step of MegEngine.

MegEngine Team will appreciate it， thanks very much！！！！！！

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by chenqy4933** [comment]
@di please consider this Request， megengine lite really need it，thanks！

**Comment by di** [comment]
Hi, does this project have plans to begin using CUDA Python (https://developer.nvidia.com/blog/unifying-the-cuda-python-ecosystem/) to reduce distribution size? If so, when? Can you share a link to a public issue, bug report, etc where this work is planned?

**Comment by chenqy4933** [comment]
thanks，now we merge MegEngine Lite to MegEngine whl， this issue is not need.
