### ISSUE TITLE
PEP541: Transfer ownership of dli package

### ISSUE THREAD

**Issue by amatos-ihsmarkit** [pypa/pypi-support#126]
**Project to be claimed**

`dli`: https://pypi.org/project/dli/

**Your PyPI username**

`markit-datalake`: https://pypi.org/user/markit-datalake/

**Reasons for the request**

The dli package is implemented and maintained by IHS Markit (https://ihsmarkit.com/index.html). 
 The current owner of the project is set to `ashic` (https://pypi.org/user/ashic/) who doesn't work at the company anymore. I would like to transfer ownership to `markit-datalake` - this is a generic account owned by the dli development team and not tied to a specific developer.

**Maintenance or replacement?**

Maintenance

**Contact and additional research**

I have attempted to contact ashic repeatedly to no avail. `markit-datalake` is already a maintainer and we just want to promote the user to be the owner. If required, I can send you a confirmation email from DataLake-Support_L1@ihsmarkit.com which is set up as the package author.

**Comment by yeraydiazdiaz** [comment]
Hello @amatos-ihsmarkit, before moving forward I'm required to have confirmation from the owner.

I did some research and found a GitHub profile: @ashic, that could be the owner's, apologies if that is not the case.

**Comment by amatos-ihsmarkit** [comment]
Hi Yeray,

Thanks. That’s indeed him, but I’ve tried to reach out to him with no avail. Can you please advise on how to proceed?

Artur

**Comment by yeraydiazdiaz** [comment]
The next steps are to wait for him to reply either here or to one of my emails in the coming weeks. If he does not we can consider the package abandoned and move forward with the request.

**Comment by amatos-ihsmarkit** [comment]
Fantastic, thanks.

**Comment by amatos-ihsmarkit** [comment]
Hi Yeray,

Hope you are well. Have you heard anything back from Ashic? Can you please go ahead and transfer ownership to us?

Thanks,

Artur
________________________________
From: Artur Matos
Sent: 20 January 2020 17:43
To: pypa/pypi-support <reply@reply.github.com>; pypa/pypi-support <pypi-support@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [pypa/pypi-support] PEP541: Transfer ownership of dli package (#126)


Fantastic, thanks.

**Comment by yeraydiazdiaz** [comment]
Hi @amatos-ihsmarkit, I did hear back from Ashic and he's agreed to the transfer.

I will now ask an admin to perform it for you.

**Comment by ewdurbin** [comment]
transfer complete.
