### ISSUE TITLE
PEP 541 Request: swig

### ISSUE THREAD

**Issue by nightlark** [pypa/pypi-support#1262]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/swig

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rmast

### Reasons for the request

A package named `swig` doesn't seem to be in use on `pypi.org` (https://pypi.org/project/swig/ gives a 404). When I tried to upload a package with the name, I get the following error:

```
The name 'swig' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

Based on other  PEP541 requests, I think it is likely on the prohibited names list.

I have a python package I've created at https://github.com/nightlark/swig-pypi that bundles https://github.com/swig/swig into Python wheels, and using `swig` as the name seems like the most logical choice given that other package managers including Chocolatey, Anaconda, Homebrew, and Spack have similar packages named `swig`.

Overall, what the package does is pretty similar to the CMake and Ninja PyPI packages created by scikit-build:
https://github.com/scikit-build/cmake-python-distributions 
https://github.com/scikit-build/ninja-python-distributions

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/nightlark/swig-pypi
https://github.com/swig/swig

### Contact and additional research

https://libraries.io/pypi/swig/0.1.0 seems to indicate that someone claimed the name as part of mass attempt to raise awareness of supply chain risks, likely resulting in it getting added to the prohibited names list.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nightlark** [comment]
@encukou I noticed a number of project names are blocked due to #355, would `swig` happen to be one of them and if so can the name get released?

**Comment by encukou** [comment]
No, `swig` is not one of them. (The list is hidden under *Details* at the end of the first post there.)

**Comment by nightlark** [comment]
Ah thanks for the pointer to the hidden `Details` section. 😄

**Comment by nightlark** [comment]
@yeraydiazdiaz is there anyone I should ping to move this forward?

**Comment by yeraydiazdiaz** [comment]
Hello @nightlark, `swig` was placed in the prohibited projects list, @pypa/warehouse-admins could you release the project, please?

**Comment by ewdurbin** [comment]
Project name released to the `rmast` User on PyPI.

**Comment by nightlark** [comment]
Thanks!

**Comment by nightlark** [comment]
Thanks! 😃
