### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bnewbold** [pypa/pypi-support#1263]
### PyPI Username

`bnewbold`

### Reason for request

Hi there! I seem to have locked myself out of my pypi.org account by enabling 2FA, not generating/saving recovery codes, and then losing/replacing my hardware token (yubikey).

I think this all happened years ago, and I haven't tried to login until recently. I suspect that I may have enabled 2FA during some testing/beta period which might be why I didn't get recovery codes? But probably I just messed up on my end.

Anyways, not sure how to proceed. This isn't particularly urgent but would be good to resolve in the next few weeks. Some active accounts I control that could be used for cross-verification or recovery:

* https://github.com/bnewbold
* https://gitlab.com/bnewbold
* https://crates.io/users/bnewbold
* https://bnewbold.net (homepage) and bnewbold@robocracy.org (primary email)
* bnewbold@gmail.com (Google account)
* employed at Internet Archive (archive.org)

I do not social media (eg, twitter, facebook, linkedin)

Sorry for the hassle, thank you for maintaining pypi.org!

--bryan

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
