### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by marcus-suresh** [pypa/pypi-support#1265]
### PyPI Username

MES1605

### Reason for request

Dear PyPi,

I have not logged into PyPi for a long time. I am trying to log in for the first time in about 1 year and I have realised that I no longer have the Microsoft Authenticator app on my phone. As such I am no longer able to log into my PyPi account. 

My user name is MES1605. 

Can you please help? I am able to provide any ID or documentation needed. 

Kind regards

Marcus Suresh
MES1605

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by marcus-suresh** [comment]
Hi,

Yes I would like help to access my pypi account.


Marcus Suresh

m: +61 407 606 172
e: ***@***.***
Sydney, NSW
Australia
￼
________________________________

**Comment by ewdurbin** [comment]
Please respond to the email with subject line "PyPI Account Recovery Request: MES1605" not this issue.

**Comment by marcus-suresh** [comment]
Hi,

I am responding as requested to gain access to my PyPi Account.



Marcus Suresh

m: +61 407 606 172
e: ***@***.***
Sydney, NSW
Australia
￼
________________________________

**Comment by ewdurbin** [comment]
A separate email was sent from an @pypi.org email address. Please read that and follow the instructions.

**Comment by marcus-suresh** [comment]
Sorry for my delay, I will try action this today.

Thanks

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
