### ISSUE TITLE
PEP 541 Request: appdir

### ISSUE THREAD

**Issue by domdfcoding** [pypa/pypi-support#1266]
### Project to be claimed

`appdir`: https://pypi.org/project/appdir

### Your PyPI username

`DomDF`: https://pypi.org/user/DomDF

### Reasons for the request

The package is an imitation of [appdirs](https://github.com/ActiveState/appdirs), but on import attempts to call out to a hardcoded IP address (presumably a command and control server) for instructions, which are then executed using the subprocess module. This could be utilised to execute malicious code on users' computers.

The IP address and port are hardcoded on lines 25 and 26 of appdir.py in the source distribution, and the code for retrieving instructions from the remote server begins on line 555.

### Contact and additional research

Forum thread: https://discuss.python.org/t/appdir-package-on-pypi-seems-to-be-a-fraudulent-mistaken-re-release-of-appdirs/10165

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by layday** [comment]
This is malware. @pypa/warehouse-admins

**Comment by ewdurbin** [comment]
This project has been removed (along with other uploads from the user).
