### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mducle** [pypa/pypi-support#1267]
### PyPI Username

mducle

### Reason for request

I don't seem to be getting the password recover email - I've asked for a reset email multiple times but it doesn't seem to get through.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Can you please try again and let me know the result here? Our email delivery logs are only kept for a short period of time.

**Comment by mducle** [comment]
@ewdurbin Sorry but I seem to be able to log in again - I had an issue where I tried to log in with what I thought was the password and it failed so I thought I must have used another password and forgot that hence the recovery but the original password worked when I just logged in now...

So I think this can be closed. Thanks for getting back to me.
