### ISSUE TITLE
PEP 541 Request: mouser

### ISSUE THREAD

**Issue by eeintech** [pypa/pypi-support#1268]
### Project to be claimed

`mouser`: https://pypi.org/project/mouser/

### Your PyPI username

`eeintech`: https://pypi.org/user/eeintech/

### Reasons for the request

I would like your help deleting the package named "mouser" from PyPI: https://pypi.org/project/mouser/

Reasons to delete:
1. this packaged doesn't do anything other than copying-pasting some of the `django-admin` tools from the Django framework project

Example: the file `core/management/base.py`
``` python
# -*- coding: utf-8 -*-
"""
Base classes for writing management commands (named commands which can
be executed through ``django-admin``).
"""
from __future__ import unicode_literals

import os
import sys
from argparse import ArgumentParser

import mouser
from mouser.core.management.color import color_style, no_style
from mouser.utils.encoding import force_text

class CommandError(Exception):
    """
    Exception class indicating a problem while executing a management
    command.

    If this exception is raised during the execution of a management
    command, it will be caught and turned into a nicely-printed error
    message to the appropriate output stream (i.e., stderr); as a
    result, raising this exception (with a sensible description of the
    error) is the preferred way to indicate that something has gone
    wrong in the execution of a command.
    """
    pass
```

is an older copy of: https://github.com/django/django/blob/main/django/core/management/base.py

2. There were no update since 2016 (stale since the first upload)
3. The original repository has been deleted from Github: https://github.com/bristy/mouser

I have contacted the [main author](https://github.com/bristy/) to delete the project from PyPI, but no answer...

I am maintaining a similarly named package which is based on a existing electronics supplier API: https://github.com/sparkmicro/mouser-api/

And I would like to use the name "mouser" to publish my package to PyPI.

Can you please help with the removal?
Thank you!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Old repository (was removed): https://github.com/bristy/mouser
New repository: https://github.com/sparkmicro/mouser-api/

### Contact and additional research

![image](https://user-images.githubusercontent.com/4020546/129800161-8ee0dccd-a0a9-4637-8543-985bee63917d.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by eeintech** [comment]
FYI @bristy if you see this, help me out please :wink:

**Comment by yeraydiazdiaz** [comment]
Hi @eeintech, even though the project has very limited functionality I cannot consider it invalid so I will start the reachability process with the owner. Hopefully we will hear back soon and move forward with the transfer.

**Comment by eeintech** [comment]
Hi @yeraydiazdiaz and thanks for the prompt response.

Please do let me know if you hear from the author, I have not since I contacted him weeks ago.

**Comment by bristy** [comment]
Hello Team,
What is the action from my side? How can I delete my old repository?

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @bristy, the best thing would be for you to log into PyPI and navigate to https://pypi.org/manage/project/mouser/collaboration/, then you can add `eeintech` as an owner to the project after which he will full control over the project.

**Comment by bristy** [comment]
I;ve deleted my project. You should be able to use the name now. Cheers!

**Comment by eeintech** [comment]
Thanks @bristy confirmed it works!

https://pypi.org/project/mouser/
