### ISSUE TITLE
Reset of 2FA on my PyPi account

### ISSUE THREAD

**Issue by pedrofran12** [pypa/pypi-support#127]
username: pedrofran12
email: pedrofran.oliveira@hotmail.com

Request: reset of 2FA on my PyPi.org account.
Reason: I had to format my phone.

Thank you.

**Comment by ewdurbin** [comment]
Hello @pedrofran12, please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by ewdurbin** [comment]
2FA reset and password reset issued.
