### ISSUE TITLE
Limit Request: dataqa - 150 MB

### ISSUE THREAD

**Issue by dataqa** [pypa/pypi-support#1273]
### Project URL

https://pypi.org/project/dataqa

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

150MB

### Which indexes

PyPI

### Reasons for the request

This project is a labelling interface, which has a search engine running. I have included binaries of a modified version of elasticsearch (which I made as small as I could), as well as a NLP (natural language processing model). These two binaries combined takes the project above the limit.

Is the limit above for each single file (wheel and tar.gz) or the whole of the dist/ folder? If it's for the folder, then I would need 300MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `dataqa` to 200 MB on PyPI.
