### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by PFaurel** [pypa/pypi-support#1274]
### PyPI Username

`pierre.faurel`

### Reason for request

I can acces to my account on pypi.org but not on test.pypi.org because I lost two factor authentication.
then I want to recover my account on test.pypi.org  

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
