### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by khanhncm** [pypa/pypi-support#1276]
### PyPI Username

'xyou'

### Reason for request

Lost 2FA authentication app  cause my android phone broken

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by khanhncm** [comment]
Hi Ee Durbin,

I posted an Account recovery request #1276
I don't find any instruction email at all, just this email. Is something wrong

Thanks

________________________________

**Comment by khanhncm** [comment]
This is the email I received. I feel missed out. I received no instruction email at all. You send it to khanhncm@outlook.com, right? Or I missed something here 

![image](https://user-images.githubusercontent.com/76054890/143669219-edbf2e63-5769-4eb0-8da3-330b28fe0d1a.png)

**Comment by ewdurbin** [comment]
An email with subject `PyPI Account Recovery Request: xyou` was sent from an email address on the `@pypi.org` domain to an `@outlook.com` address associated with your account. I have resent this email.

**Comment by khanhncm** [comment]
Thank Durbin for the resent. Maybe I mistakenly deleted it somehow. I've made a reply to confirm

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
