### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dbinger** [pypa/pypi-support#1277]
### PyPI Username

`dbinger`

### Reason for request

Lost both.  I used this account when I was dbinger@mems-exchange.org and created several projects prior to 2013.
I'm wanting access to this account because I made a project called "qp" that is quite obsolete now and there is another developer (Alex Malz <almalz@nyu.edu) that has a project with the same name that he wants to put into PyPi.

My current email is davidbinger@gmail.com.
I'm also dbinger@forcedphysics-dct.com, David Binger, CTO of Forced Physics DCT.
571-243-7567

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The email associated with this account still shows as being successfully deliverable. Do you have some mechanism of proving ownership of any of the projects on the account, perhaps via a homepage or source code repository?

**Comment by dbinger** [comment]
Thanks for writing, Ee.

I’ll see if I can contact the sysadmin at mems-exchange.org to help.
