### ISSUE TITLE
PEP 541 Request: runmany

### ISSUE THREAD

**Issue by discretegames** [pypa/pypi-support#1278]
### Project to be claimed

`runmany`: https://pypi.org/project/runmany

### Your PyPI username

`discretegames`: https://pypi.org/user/discretegames

### Reasons for the request

Just a bit ago I uploaded my package "RunMany" version 0.0.1 to PyPI for the first time.

I realized I didn't put it in lowercase "runmany" like I wanted so based on of https://stackoverflow.com/a/17750711 I deleted the entire project from PyPI and attempted to reupload.

I received the error
> This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for more 

though of course it had been me who had used that names minutes before.

So I mistakenly deleted my package "RunMany" based on bad advice and would love to have the name "runmany" back. 

### Source code repositories URLs

https://github.com/discretegames/runmany

### Contact and additional research

I am/was the original owner and only mistakenly deleted the project from PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @discretegames, as the error suggests the solution is to change the version number, as outlined in the [help section](https://pypi.org/help/#file-name-reuse), PyPI stores release files permanently even after a project has been deleted.

Closing as it is not a PEP 541 request, but feel free to comment if you're still having problems.
