### ISSUE TITLE
Reset of 2FA on my PyPi account

### ISSUE THREAD

**Issue by gallochri** [pypa/pypi-support#128]
username: gallochri
email: chri@gallochri.com

Request: reset of 2FA on my PyPi.org account.
Reason: Changing broken phone.

Thank you.

**Comment by ewdurbin** [comment]
Hello @gallochri, please email ernest@python.org from the primary email associated with your account.

**Comment by gallochri** [comment]
Ok, thanks

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
