### ISSUE TITLE
PEP 541 Request: skyline-apiserver

### ISSUE THREAD

**Issue by SeanGol** [pypa/pypi-support#1282]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/skyline-apiserver/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/99cloud/

### Reasons for the request

A package named `skyline-apiserver` doesn't seem to be in use on pypi.org (https://pypi.org/project/skyline-apiserver/ gives a 404). 
But when I use `poetry` publish, I get 400 error (`HTTP Error 400: The name'skyline-apiserver' isn't allowed. See https://pypi.org/help/#project-name for more information.`).
Based on other PEP541 requests, I think it is likely on the prohibited names list.
Can you please help us and allow us to use `skyline-apiserver` as our Pypi package name?? Thank you!

**To Reproduce**

```bash
$ git clone https://opendev.org/skyline/skyline-apiserver.git
$ cd skyline-apiserver/libs/skyline-apiserver
$ poetry build -f wheel
$ poetry publish -u <my_username> -p <my_password>
Publishing skyline-apiserver (0.1.0) to PyPI
 - Uploading skyline_apiserver-0.1.0-py3-none-any.whl 100%

  UploadError

  HTTP Error 400: The name 'skyline-apiserver' isn't allowed. See https://pypi.org/help/#project-name for more information.

  at ~/.poetry/lib/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│
    → 216│             raise UploadError(e)
      217│
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None
```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

[skyline-apiserver](https://opendev.org/skyline/skyline-apiserver/src/branch/master/libs/skyline-apiserver)

### Contact and additional research

Please feel free to contact us at: gao.hanxiang@99cloud.net or wu.wenxiang@99cloud.net

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @SeanGol, the name `skyline-apiserver` was placed in the prohibited project names list, @pypa/warehouse-admins could you release the name, please?

**Comment by ewdurbin** [comment]
Project released to the `99cloud` User on PyPI.

**Comment by SeanGol** [comment]
@ewdurbin  thank you.
