### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by amplifilo** [pypa/pypi-support#1284]
### PyPI Username

'fajro'

### Reason for request

I lost access to email associated with accoutn (dataxray@tuta.io). 
I am registered as lead developer of 'data-xray' (Petro Maksymovych, pmax20@gmail.com).
I would like to regain access to 'data-xray', to update development status and fix the repository (moved to github).
Thank you very much for you help! Please contact me directly at pmax20@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account as well as requested email, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Recovery complete.
