### ISSUE TITLE
PEP 541 Request: logicnets

### ISSUE THREAD

**Issue by nickfraser** [pypa/pypi-support#1286]
### Project to be claimed

`logicnets`: https://pypi.org/project/logicnets

### Your PyPI username

`nickfraser`: https://pypi.org/user/nickfraser

### Reasons for the request

An ethical hacker claimed this project name to make us aware of a [potential security flaw](https://github.com/Xilinx/logicnets/commit/c633ca0056eb2e4ef7e5a03452c2c26f1b996647). The hacker has now removed their logicnets release, but I'm still unable to upload my package to this project name. I suspect it's still tied to the hacker's account.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Xilinx/logicnets

### Contact and additional research

We negotiated with the hacker to delete their release from PyPI, but now we would like to claim the project name.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @nickfraser, `logicnets` was placed on the prohibited project names list, @pypa/warehouse-admins could you release the name, please?

**Comment by ewdurbin** [comment]
Project released to the `nickfraser` User on PyPI.

**Comment by nickfraser** [comment]
Thank you!
