### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gabe-l-hart** [pypa/pypi-support#1288]
### PyPI Username

`gabegoodhart`

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by gabe-l-hart** [comment]
Hi PyPI maintainers, thanks for considering my recovery request! This is a classic case of all-eggs-in-one-basket where my 2FA device bricked before I'd realized that the creation of backup codes was not automatic. I will absolutely do better next time!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
