### ISSUE TITLE
PEP 541 Request: etna

### ISSUE THREAD

**Issue by diadorer** [pypa/pypi-support#1289]
### Project to be claimed

`etna`: https://pypi.org/project/etna

### Your PyPI username

`diadorer`: https://pypi.org/user/diadorer

### Reasons for the request

My team are planning to make an open source package named "etna" and now we found that it matches project https://pypi.org/project/etna.

Project https://pypi.org/project/etna is looks like abandoned, because of: 
1) maintainers email (simon.mcintosh@ukaea.uk) is not working
2) there is no releases past 5 years
3) there is no homepage (https://github.com/twistersi/Etna — now returns 404)

Also this project has no files.

And we want to reuse this package name to make the world prettier!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/tinkoff-ai/etna-ts

### Contact and additional research

Email of maintainer is not working — response from gmail mailer daemon:
<img width="1400" alt="Screenshot 2021-08-27 at 17 00 59" src="https://user-images.githubusercontent.com/33423367/131139769-f65bd35c-307e-4021-9a1b-6939ab7fe6c9.png">

Also I could not found some relevant account in social networks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @diadorer, I can confim this project has a single release with no associated files and is therefore considered invalid. I attempted contact with the owner last week but have not heared back so I've transfered the project to you.
