### ISSUE TITLE
Reset of 2FA on my PyPi account

### ISSUE THREAD

**Issue by RatanShreshtha** [pypa/pypi-support#129]
username: RatanShreshtha
email: ratan.shreshtha@gmail.com

Request: Reset of 2FA on my PyPi.org account.
Reason: Changing broken phone.

Thank you.

**Comment by ewdurbin** [comment]
Hello @RatanShreshtha, please email ernest@python.org from the primary email associated with your account.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

**Comment by RatanShreshtha** [comment]
Thanks @ewdurbin
