### ISSUE TITLE
Limit Request: dataqa_es - 150 MB

### ISSUE THREAD

**Issue by dataqa** [pypa/pypi-support#1290]
### Project URL

https://pypi.org/project/dataqa-es

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

150MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

I recently requested a limit increase for the project https://pypi.org/project/dataqa ([github ticket](https://github.com/pypa/pypi-support/issues/1273)). However, I decided to split this project into two. I would like to have the project `dataqa-es` have the larger limit, and I don't mind having `dataqa` go back to its original 100MB as it will be a much smaller project.

Either that or renaming `dataqa` to `dataqa-es`, but I read that this is not possible.

Sorry for these changes, I am relatively new to pypi and open-source and learning the ropes!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dataqa** [comment]
Hi @di, I would really appreciate your help, I’m a bit stuck with this issue.

**Comment by pradyunsg** [comment]
Could you provide a link to the source repository of this project?

Also, on a slightly unrelated note:

- based on https://pypi.org/project/dataqa/1.0.4/#files -- it seems like you aren't publishing source distributions for the project. Is there a specific reason for that? If not, I'd recommend publishing source distributions as well.
- It would be a good idea to provide project-related URL information in future releases, by adding [project_urls](https://github.com/pypa/pip/blob/0de0b8dd9f21642dc6d0e00bfa8913f4964b1706/setup.py#L49) to your setup.py file.

**Comment by pradyunsg** [comment]
Bumped the limit on PyPI to 200 MB, since this is a small-enough request and dataqa has that limit already.

https://test.pypi.org/project/dataqa-es/ does not exist, and hasn't been handled.
