### ISSUE TITLE
PEP 541 Request: prisma

### ISSUE THREAD

**Issue by RobertCraigie** [pypa/pypi-support#1291]
### Project to be claimed

`prisma`: https://pypi.org/project/prisma

### Your PyPI username

`craigie`: https://pypi.org/user/craigie

### Reasons for the request

- The `prisma` project has not been updated in nearly 4 years.
- The creator of the package is not contactable.
- One of the original creators of this project has confirmed that it is abandoned, see below.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

[https://github.com/RobertCraigie/prisma-client-py](https://github.com/RobertCraigie/prisma-client-py)

### Contact and additional research

I tracked down the source code repository for the `prisma` package to [https://github.com/oyasniy/prisma-core](https://github.com/oyasniy/prisma-core).

The owner of the repository has no email address listed and the no issues can be created.

The repository has been forked by [@neilkakkar](https://github.com/neilkakkar/prisma-core), whom I then contacted asking if the owner can be contacted and he responded with:

```
Hey Robert,

That's a shame. Yeah, our Prisma project has long since been abandoned.

The original author likes keeping a low profile, and the old email address I have doesn't work anymore. So, afraid I can't help.

Good luck,
```
[screenshot](https://i.gyazo.com/1f4308ec995ecc50fcd33d3722d321ef.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @RobertCraigie, I will now start the reachability process for your request. Hopefully we will hear back soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The registered email address for the owner is not functional, tagging GitHub user @oyasniy who seems to own the project's repository.

**Comment by RobertCraigie** [comment]
Great news, thank you!

**Comment by RobertCraigie** [comment]
Thank you @yeraydiazdiaz, just wondering what is the time required before a user is considered uncontactable?

**Comment by pradyunsg** [comment]
6 weeks.

See https://www.python.org/dev/peps/pep-0541/#reachability for the details of the process.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
