### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tgulacsi** [pypa/pypi-support#1292]
### PyPI Username

gthomas

### Reason for request

Lost access to email address

I want to release the "Mosaic" (https://pypi.org/project/Mosaic/) package name as requested by https://twitter.com/davisblalock .

I don't know what is my registered email address, it could be gthomas@fw.hu, gthomas@citromail.hu, sth with @gthomas.eu.
I don't have access to those addresses anymore.

My new email is tamas@gulacsi.eu

Thanks in advance!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The email address associated with this account is an `@ludens.elte.hu` address. If you no longer have access to this email address please contact support@pypi.org including a link to this issue for next steps.

**Comment by tgulacsi** [comment]
On Fri Nov 5, 2021 at 5:57 PM CET, Ee Durbin wrote:
> The email address associated with this account is an ***@***.***`
> address. If you no longer have access to this email address please
> contact ***@***.*** including a link to this issue for next steps.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pypa/pypi-support/issues/1292#issuecomment-962059336

I no longer have access to that address, sorry.
What shall I do?

Thanks, Tamás Gulácsi

**Comment by ewdurbin** [comment]
Complete.
