### ISSUE TITLE
PEP 541 Request: validation

### ISSUE THREAD

**Issue by bwhmather** [pypa/pypi-support#1298]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/validation

### Your PyPI username

`USER_NAME`: https://pypi.org/user/bwhmather

### Reasons for the request

This is a retroactive request for blessing a replacement that was made before the restrictions were added.

I've been maintaining a project with under the pypi name `validation` since 2017.

I discovered that there was a different project published under the same name and then deleted when I ran into filename collisions while trying to publish new versions of the same file.  This was a  while ago, and I took no action at the time beyond uploading zips instead of tarballs

I've noticed that libraries.io marks the project as "removed from pypi", and would like to know if there's anything I can do to make the transfer official.

### Source code repositories URLs

https://github.com/bwhmather/python-validation/

### Contact and additional research

https://pypi.org/simple/validation/validation-0.1.0.tar.gz used to point to a package for the old project.  I believe that it did have sufficient metadata to be able to track down the original author.   Sensibly, but unfortunately for this purpose, it seems to have been removed.

Haven't been able to find anything in duckduckgo, archive.org, or by clicking around in the pypi web interface.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bwhmather, I can see you are already the owner of the package so for PyPI's side the transfer is "official", we have no control over what is displayed in libraries.io.

However, [version 0.1.0 is available in PyPI](https://pypi.org/project/validation/0.1.0/#files). Its setup.py contains the following:

```
....
setup(
    name='validation',
    url='https://github.com/JOIVY/validation',
    version='0.1.0',
    author='Ben Mather',
    author_email='bwhmather@bwhmather.com',
...
```

Note https://github.com/JOIVY/validation appears as the URL, so @JOIVY can clarify the situation.

But in any case you, as the owner, can delete the release entirely but you will _not_ be able to reupload the version with different contents as it's not permitted by PyPI.

I'm closing the request as there's nothing to transfer but feel free to comment if you have any additional questions.

**Comment by bwhmather** [comment]
Hi @yeraydiazdiaz - The 0.1.0 release is of the same package and was released by me while I was working at Joivy.  Problem was a previous project that was deleted from pypi, releasing the name for anyone (in this case me) to use.

If you can't find any evidence of it either then I agree that closing makes sense.  I'll link on the libraries.io issue tracker and see if they have any ideas.

Thank you for your help.
