### ISSUE TITLE
Claim of keyring-vault-backend

### ISSUE THREAD

**Issue by jynolen** [pypa/pypi-support#13]
Hello,

I would like to claim the following package:
https://pypi.org/project/keyring-vault-backend/

I opened a PR long time ago with no answer
I tried to contact @pschmitt by email specify in the setup.py with no success

For reference:
Owner Pypi package: keyring-vault-backend
Owner Pypi username: pschmitt
My Pypi username: jynolen

Thank you

**Comment by yeraydiazdiaz** [comment]
I'm closing this issue since the author has requested changes to [the mentioned PR](https://github.com/pschmitt/keyring-vault-backend/pull/5) and got no reply. Nothing suggests this project is not being actively maintained.
