### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by florimondmanca** [pypa/pypi-support#1300]
### PyPI Username

florimondmanca

### Reason for request

**Lost 2FA authentication app or security token**

Hi folks, I am filing this issue as I'm unable to log in now due to 2FA mishaps. I changed password managers recently, I had setup 2FA via the old one and didn't store recovery codes offline (they were _also_ in the manager password manager). So when I cancelled the old subscription I lost it all…

Could you help me out? Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by aljinovic** [comment]
Hello, any news here maybe?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
