### ISSUE TITLE
PEP 541 Request: aqueduct

### ISSUE THREAD

**Issue by bugrimov** [pypa/pypi-support#1301]
### Project to be claimed

`aqueduct`: https://pypi.org/project/aqueduct

### Your PyPI username

`bugrimov`: https://pypi.org/user/bugrimov

### Reasons for the request

The project has been empty for 6 years. I think it squated or just forbidden and abandomed.
It's not appeared in search https://pypi.org/search/?q=aqueduct so when creating and presenting our new library we thinking that this name is available. We start uploading our new library to pypi and find out what name `aqueduct` is busy by empty project.
Our team developed a new python library (https://github.com/avito-tech/aqueduct) for efficiently deploying machine learning to production.
We called it `aqueduct` and presented it to other developers under that name. We make it open source, so other developers can use and contribute.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Project haven't any repositories urls as well as haven't package itself and documentation and source codes.

### Contact and additional research

I found the author and tried to contact, but did not receive an answer.
Author is https://github.com/harlowja, this user haven't repositories named `aqueduct`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bugrimov, I can confirm the project has a single release with no associated files. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by bugrimov** [comment]
@yeraydiazdiaz is there any news?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by bugrimov** [comment]
Great news, thank you!
