### ISSUE TITLE
PEP 541 Request: tin

### ISSUE THREAD

**Issue by explody** [pypa/pypi-support#1303]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/tin

### Your PyPI username

`USER_NAME`: https://pypi.org/user/explody

### Reasons for the request

Formerly known as 'apeye', this is a project that has expanded and contracted over the years, which despite looking ramshackle, has been in prod use at a number of employers for a long time.

Recently, I decided to completely revamp it and publish it properly.

But, while I was busy not maintaining this publicly, another fellow created a project last year called "Apeye".  It looks quite nice, and active and I don't want to intrude on his space by doing something like "pyapeye" so I went looking for a new name.  The package is a thin wrapper around REST APIs, with "canned" API definitions in YAML, for APis that don't yet have OpenAPI info published. So I went looking for new names and landed on variations of 'thin' (tynn, tunn, various languages) before noticing that "tin" - which fits nicely for "thin" and for "canned" was not actually in use on PyPI, or so it seemed.

This doesn't actually go anywhere: https://pypi.org/project/tin and this has no artifacts: https://pypi.org/simple/tin

I'm not sure what was there, but it doesn't seem to be there any longer (or is this reserved for some reason?).

Hopefully this can be freed up, but if not for some reason, just let me know :)

Thanks in advance!

-Mike

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://gitlab.com/explody/tin  (a bit sparse, I'm refactoring/rebuilding everything)

### Contact and additional research

I've looked around in Github, Gitlab, Google, etc, and can't find another Python project called "tin"

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @explody, I can confirm the `tin` project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer and it is now complete.
