### ISSUE TITLE
Limit Request: Jaxlib - 50 GB

### ISSUE THREAD

**Issue by yashk2810** [pypa/pypi-support#1304]
### Project URL

https://pypi.org/project/jaxlib/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

50 GB

### Which indexes

PyPI

### Reasons for the request

Jaxlib is XLA library for JAX.

Every couple of releases of the jaxlib package, we need to delete the previous releases so that we have space for new releases. We archive all of our builds on GCP and store GPU builds on GCP only installable via (`pip install -f`).

The builds we upload on PyPI are non-cuda wheels and mac wheels. We don't upload CUDA wheels because we run out of space.

We want to host GPU packages on PyPI too making the installation process more smoother and possibly nightly packages too.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Have you investigated whether you can use [CUDA Python](https://github.com/NVIDIA/cuda-python) or [CuPy](https://cupy.dev/) to avoid the need for bundling your own CUDA bindings in the package?

This limit request would make this one of the largest projects on PyPI. As of [right now](https://pypi.org/stats/), only 20 projects have a size of 50 GB or greater on PyPI. The original request of 250 GB would've made this the 4th largest projects on PyPI.

**Comment by yashk2810** [comment]
The 50 GB is only the limit. We won't reach the limit soon (but within a year).

How much space can you give us? We are currently releasing cuda enabled JAX on GCP only and can continue to do that. We just wanted to make the experience a bit smoother for users.

**Comment by pradyunsg** [comment]
> Have you investigated whether you can use [CUDA Python](https://github.com/NVIDIA/cuda-python) or [CuPy](https://cupy.dev/) to avoid the need for bundling your own CUDA bindings in the package?

Please answer the question. It would help guide the decision making process on this ticket.

> How much space can you give us?

I don't make the final call for requests of this magnitude -- that's a decision for the PyPI admins to make. My educated guess is that if the project is going to use >50 GB/year, that's not going to sustainable -- you'll need to work to reduce the size of the releases.

**Comment by yashk2810** [comment]
> if the project is going to use >50 GB/year, that's not going to sustainable

I just need 50 GB (not 50 GB/year).

> Please answer the question

I don't think I understand the question. I looked at cuda-python and it supports Cuda 11.0-11.4. JAX doesn't want to be restricted by what cuda-python or other libraries support. We have our own release criteria and we can support out-of-band CUDA versions.

**Comment by yashk2810** [comment]
I don't think even TensorFlow or Pytorch uses Cuda Python or CuPy yet, but that being said, we'll (JAX) look into it.

**Comment by di** [comment]
I've increased the limit for `jaxlib` to 20GB for now. Please reach out with a new request if you need this raised higher in the future.
