### ISSUE TITLE
Limit Request: sen2vec - 1500 MB

### ISSUE THREAD

**Issue by xczcx11** [pypa/pypi-support#1305]
### Project URL

https://pypi.org/project/sen2vec/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

1500 MB

### Which indexes

PyPI

### Reasons for the request

Hi,

The name of this project is sen2vec, latest version==1.19 which can transform text(in Chinese) to vector.
It's mainly used in Finance text, further version will be upload which can be used in more areas.
Now I an uploading new version==1.20, and PyPI warns 'no larger than 100MB'.
The reason:
    sen2vec 1.19 only contain code, no model.
    sen2vec 1.20 contain 2 models, but the models are too large.
    model1 named bert.ckpt, about 400-1000MB, depends on the version.
    model2 named pytorch_model.bin, about 400MB.
Both models need upload. Without models, the preject cannot function well.
Please increase total preject size up to 1500MB and increase per release file size up to 1000MB for me.
Thank you!~

I write long_description in setup.py:
                     '- Put the sentences which need transform in the column title of data, must be DataFrame.\n'
                     '- Model_name and model_path can be self-trained and self-defined. We offer one default option.\n'
                     '- HOW TO USE: \n'
                     '  1. Activate CLASS sen2vec:\n'
                     '     s = sen2vec(None, False)\n'
                     '  2. Define model_config by self with format:\n'
                     '     model_config = (model_name, vec_dim, num_class, model_path)\n'
                     '     s = sen2vec(model_config)\n'
                     '  3. Transform data with title:\n'
                     '     new_df = s.sen2vec_fi(data, title)\n'
                     '- Vec_dim and num_class are dims and classes of the vector transformed.\n'
                     '- For more information: Please contact author.',

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hello hello! We do not increase upload limits for situations like this, at this time.

As per our [guidelines for upload limit requests](https://github.com/pypa/pypi-support#guidelines-for-upload-limit-requests):

> Upload limits are generally denied for the following reasons: [snip] project contains large pre-trained machine learning models

I would recommend hosting your models in a different location, and providing the users a way to download those models from there. I think `nltk` [does a pretty good job](https://www.nltk.org/data.html) for making it straightforward for their users to download their large corpus of data and models.

**Comment by pradyunsg** [comment]
Gonna close this out, since this request is for increasing the limit to enable distributing large pre-trained models -- something that we explicitly spell out as something we deny.

**Comment by xczcx11** [comment]
Thanks for the reply and the advice.



---Original---
From: "Pradyun ***@***.***&gt;
Date: Wed, Sep 15, 2021 19:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pypa/pypi-support] Limit Request: sen2vec - 1500 MB (#1305)




 
Gonna close this out, since this request is for increasing the limit to enable distributing large pre-trained models -- something that we explicitly spell out as something we deny.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
