### ISSUE TITLE
PEP 541 Request: netrunner

### ISSUE THREAD

**Issue by rbraddev** [pypa/pypi-support#1306]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/netrunner

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rbdev

### Reasons for the request

The package name was released in November 2014, and nothing has been published to it.

Also, the repo to which this package is linked can no longer be found: https://github.com/dimka665/iec104.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/rbraddev/netrunner

### Contact and additional research

I have emailed Dmitry twice with no response:
![Screenshot from 2021-09-10 16-49-44](https://user-images.githubusercontent.com/40888255/132881642-0734b6c6-1176-4203-a323-8973f6109ad2.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @rbraddev, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by voronind** [comment]
I am ready to transfer project. I invited `rbdev` to be owner.

**Comment by rbraddev** [comment]
Thank you @yeraydiazdiaz and @voronind

**Comment by yeraydiazdiaz** [comment]
Thanks @voronind.
