### ISSUE TITLE
Limit Request: pandas - (project) 20000 MB

### ISSUE THREAD

**Issue by jreback** [pypa/pypi-support#1307]
### Project URL

https://pypi.org/manage/project/pandas/settings/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20000MB

### Which indexes

PyPI

### Reasons for the request

we are bumping up against the limit even after removing older releases. thanks. at 8.9GB now.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Can you confirm what error you're seeing when attempting an upload and how big the file that you're uploading is?

**Comment by jreback** [comment]
thanks for the quick response @pradyunsg no issue right now. we had to delete all rc & beta releases to stay under the limit. its going to hit pretty soon though as our releases tend to be 200+mb in total with all the wheels.

**Comment by pradyunsg** [comment]
I've gone ahead and raised the overall project size limit to 20 GiB for `pandas`, on PyPI.

Please be mindful of the individual release sizes and your release frequency with this limit. I'm expecting you won't need another limit increase like this for... quite a while. :)

**Comment by jreback** [comment]
thanks @pradyunsg
