### ISSUE TITLE
Project Limit Request: pyre-check-nightly - 15 GB

### ISSUE THREAD

**Issue by shannonzhu** [pypa/pypi-support#1314]
### Project URL

https://pypi.org/project/pyre-check-nightly

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

15 GB

### Which indexes

PyPI

### Reasons for the request

This project is used to hold nightly release versions which are frequently used as pinned versions for some projects. 

We ran up on the 10GB limit and would like a small increase for a better buffer on our expiration SLA for these nightly releases. 

That said, to keep this sustainable we'll have to start programmatically deleting older versions. Is there a recommended API to use for this? I imagine this is probably a commonly needed feature for any project with very frequent or nightly releases, but couldn't find anything documented. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I'm leaning toward rejecting this request, following the guidelines listed in the README.

> Upload limits are generally denied for the following reasons:
>
> - project makes nightly releases and/or is published frequently

I'll let another moderator or an admin chip in before closing this.

**Comment by pradyunsg** [comment]
Beyond that, the project seems to have deleted a lot of the files, and is at 5.7 GB at this time.

**Comment by pradyunsg** [comment]
There was a decently large cleanup of old releases done on 2021-10-15, in case someone else is looking more closely at this.

**Comment by shannonzhu** [comment]
@pradyunsg  Thanks for looking into this! I had to delete a lot of files in order to cope with the size limit while this issue remained open, but would like to avoid having to do so as aggressively in the future. 

I'm seeing a lot of nightly projects with large sizes on PyPi: https://pypi.org/stats/ probably with similar use cases, but I'm not familiar with whether they jumped through any extra hoops.

**Comment by pradyunsg** [comment]
> I'm seeing a lot of nightly projects with large sizes on PyPi: [pypi.org/stats](https://pypi.org/stats/) probably with similar use cases, but I'm not familiar with whether they jumped through any extra hoops.

If my understanding and memory is correct...

The reason these limits were introduced was because precisely because those projects became so big. I imagine that, if any of those come around to requesting any more storage than they have[^1], it's certainly likely that we'd ask them to reduce how much impact they have on PyPI. :)

[^1]: Their current limits were set according to what their size was, when the limits were introduced.

**Comment by pradyunsg** [comment]
> That said, to keep this sustainable we'll have to start programmatically deleting older versions. Is there a recommended API to use for this? I imagine this is probably a commonly needed feature for any project with very frequent or nightly releases, but couldn't find anything documented.

I've seen multiple projects use https://pypi.org/project/pypi-cleanup/, but this isn't an endorsement of the project.

**Comment by shannonzhu** [comment]
@pradyunsg  Just following up here! I already do have an aggressive automatic cleanup script set up, which is why we aren't hitting the limit currently and aren't blocked from further releases.

It's totally reasonable that further/indefinite growth isn't sustainable for large projects, and I understand why there is a limit in place. I'm confident that we will not approach the size of those projects, and in fact won't even need to ask for another size bump in the future, as we'll continue to use our cleanup script after the one-time limit change. This is just so we have a more reasonable TTL (we're aiming at 6-8 months) before a user quietly experiences a flat out breakage due to not upgrading. 

I hope that makes sense, let me know if there's anything else you might need from me to process this request! I really appreciate the help.

**Comment by pradyunsg** [comment]
Approved, and bumped the limit to 15.0 GB on PyPI.
