### ISSUE TITLE
Limit Request: Gensim - 100 GB

### ISSUE THREAD

**Issue by piskvorky** [pypa/pypi-support#1315]
### Project URL

https://pypi.org/project/gensim/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

100 GB

### Which indexes

PyPI

### Reasons for the request

Gensim is a popular library, so we provide multiple binary wheels to users: 4 different platforms x 4 Python versions, per release. Although each wheel isn't large, this adds up quickly and we already hit the current PyPI limit of 10 GB total: https://github.com/RaRe-Technologies/gensim/issues/3237

Is it possible to increases the limit?

Our other option is to start deleting old releases from PyPI to free up space… which isn't great for users, nor for maintainers.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hiya! How long do you expect this limit to last? Would a smaller limit be sufficient for your needs here?

At a 100 GB limit, this project would be able to become the 12th largest project on PyPI today (https://pypi.org/stats/).

**Comment by piskvorky** [comment]
@mpenkov WDYT?

**Comment by mpenkov** [comment]
We could ask for a smaller limit (e.g. 20GB) and then reduce the size of each wheel by removing test data.

**Comment by pradyunsg** [comment]
Hiya folks! Let me know once you have consensus on what limit you'd like! I'll keep this open for another 4 weeks, and then if there's no updates by then, close this out.

**Comment by pradyunsg** [comment]
Closing this, due to a lack of a response. Please feel free to open a new ticket with the changed limit request! :)
