### ISSUE TITLE
PEP 541 Request: django-import-export (test.pypi.org)

### ISSUE THREAD

**Issue by matthewhegarty** [pypa/pypi-support#1316]
### Project to be claimed

`PROJECT_NAME`: https://test.pypi.org/project/django-import-export

### Your PyPI username

`USER_NAME`: https://test.pypi.org/user/matthewhegarty

### Request for transfer on **test.pypi.org**

I am an admin on [django-import-export](https://github.com/orgs/django-import-export/people/matthewhegarty).
I would like to be able to test upload of packages to test.pypi.org.

There is an [existing account](https://test.pypi.org/project/django-import-export/) which appears abandoned, with only one release in December 2018.

There is no public contact information for the current maintainer [matheusm_santana](https://test.pypi.org/user/matheusm_santana/).  I have checked our [authors](https://github.com/django-import-export/django-import-export/blob/main/AUTHORS) and it seems that this gentleman has not been a previous contributor to `django-import-export`, although I cannot say that for sure.

It would be ideal if we could reclaim this project on test.pypi.org to enable us to test our releases.

Note I am not requesting this for the live pypi.org site, because we do have permissions to publish to live.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/django-import-export/django-import-export

### Contact and additional research

I have googled for the username, but cannot find any definite matches, or any publicly available contact details.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Owners of projects in PyPI are automatically granted ownership of the corresponding projects in Test PyPI.

Transfer complete.
