### ISSUE TITLE
PEP 541 Request: pycryptosat

### ISSUE THREAD

**Issue by msoos** [pypa/pypi-support#1318]
### Project to be claimed

`pycryptosat`: https://pypi.org/project/pycryptosat

### Your PyPI username

`msoos`: https://pypi.org/user/msoos

### Reasons for the request

Hi,

I am Mate Soos, the author of [CryptoMiniSat](https://github.com/msoos/cryptominisat), as per my GitHub profile, and as per how the original PyPi maintainer put together the [pycryptosat PyPi project](https://pypi.org/project/pycryptosat/). Check out the homepage (www.msoos.org), the Maintainer (clearly set to me), etc. The "pycryptosat" is the python module that CryptoMiniSat builds&installs when built using `cmake` and python2/3 is present.

The issue is, the version on PyPi very outdated. I tried reaching out the maintainer, but I couldn't get any response. There is no official email address listed for her/him, so I tried searching around. I sent a few emails to what I would guess to be her/his email, but no response. I'd like to get control over the PyPi project. It's currently very outdated, and I believe I would be in a good position to maintain it. Furthermore, I'd like to release some research projects in the long term (I work in academia sometimes), and having control over pycryptosat would be invaluable for this.

Basically, the best would be if you have access to her/his email address, could you please write an email to them? I have a feeling they'd be happy to give the project to me, to be honest -- there is no reason to believe they wouldn't trust me :) If they also don't respond to you, would it be possible to give me the project after some waiting & discussion?

Thanks so much in advance,

Mate

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/msoos/cryptominisat

### Contact and additional research

I have sent 3 emails to what I believe to be Pierre Vignet, working at IRISA (pierre.vignet@irisa.fr), the current maintainer (see INRISA webpage: https://www-dyliss.irisa.fr/team-members/, a bioinformatics team), back in 2019:
![image](https://user-images.githubusercontent.com/1334841/133995470-594636d3-77ea-4614-8225-694dbede60cd.png). Two in February with a 10 day delay, and one in May of the same year. I did not get a response. I strongly believe pierrev to be Pierre Vignet, I even put him on the authors of [pycryptosat.cpp.in](https://github.com/msoos/cryptominisat/blob/master/python/src/pycryptosat.cpp.in): `(2017, Pierre Vignet)`. He also maintains the https://pypi.org/project/cadbiom-cmd/ and other `cadbiom`-related packages, with is for `Computer Aided Design of Biological Models`. So that matches up with the bioinformatics team above.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
