### ISSUE TITLE
Please reset 2FA on my account

### ISSUE THREAD

**Issue by helto4real** [pypa/pypi-support#132]
Hi,

Please reset 2FA on my account. My phone was stolen and I cant get into my account now.

username: helto4real
e-mail: tomas.hellstrom@yahoo.se

I can provide details in a e-mail conversation.

Thanks
Kind regards
Tomas Hellström

**Comment by helto4real** [comment]
Possible to help me out please ?

**Comment by ewdurbin** [comment]
Hello @helto4real, please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by helto4real** [comment]
Thanks, I realized I had erased the info@joysoftware.org. I had to recreate it. 

Can I please ask you to send it again? Sorry for the inconvenience.

Kind Regards
Tomas

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

**Comment by helto4real** [comment]
You guys are the best! Thanks!
