### ISSUE TITLE
Limit Request: PyTorch-DirectML - 82MB

### ISSUE THREAD

**Issue by Adele101** [pypa/pypi-support#1322]
### Project URL

https://pypi.org/project/PyTorch-DirectML/0.0/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

82

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Microsoft is adding support for cross-vendor hardware acceleration for PyTorch using DirectML in Windows and the Windows Subsystem for Linux.

We've kept our initial release as small as possible. Torch wheels are around 200MB, while our distribution is 82MB.  Release sizes will likely increase slightly as we add additional features, but we expect our release size to always be smaller than the upstream releases of PyTorch.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Adele101** [comment]
Hi @pradyunsg would you be able to help get this through? We need to release but are stuck on this issue.

**Comment by ewdurbin** [comment]
File upload size limit increased to 250MiB. Project total size limit remains 10 GiB.
