### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Soroosh129** [pypa/pypi-support#1329]
### PyPI Username

`Soroosh129`

### Reason for request

I have lost access to my 2FA authentication app and don't have recovery codes unfortunately.

The reason I have lost access is that I have changed my phone and the data transfer has not transferred my 2FA app data. I have realized this now, a few months after upgrading because I wanted to update our LinguaFrancaBase package to 1.0.4 and add a project description. I would truly appreciate your help with this.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by Soroosh129** [comment]
Thanks!
