### ISSUE TITLE
PEP 541 Request: tflite-runtime

### ISSUE THREAD

**Issue by scottamain** [pypa/pypi-support#1333]
### Project to be claimed

`tflite-runtime`: https://pypi.org/project/tflite-runtime

### Your PyPI username

`coral-support`: https://pypi.org/user/coral-support/

### Reasons for the request

There is no active project using the "tflite-runtime" name, but I still get refused:

```
Uploading tflite_runtime-2.5.0-cp35-cp35m-linux_aarch64.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 996k/996k [00:03<00:00, 311kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'tflite-runtime' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

However, it appears somebody else *has* used this name on test.pypi.org. Is that the problem?

### Maintenance or replacement?

Maintenance

### Contact and additional research

I see no current owner. Can you please explain why I'm refused?

I have not attempted to contact the owner for [the package on test.pypi.org](https://test.pypi.org/project/tflite-runtime/) because [your documentation about naming (PEP 423)](https://www.python.org/dev/peps/pep-0423/#how-to-check-for-name-availability) has no concern for names on the test server, and those test packages are [supposed to be deleted](https://packaging.python.org/tutorials/packaging-projects/#next-steps).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
`tflite-runtime` was placed in the prohibited project names list, @pypa/warehouse-admins could you release the project to @callumforrester, please?

**Comment by callumforrester** [comment]
@yeraydiazdiaz I think you tagged me twice, once in #1327 and once here. Did you mean to ask for `tflite-runtime` to be released to @scottamain?

**Comment by yeraydiazdiaz** [comment]
Yes, sorry about that 🙂

**Comment by scottamain** [comment]
Great, thank you!

**Comment by scottamain** [comment]
@callumforrester Can you please release `tflite-runtime` for user coral-support?

**Comment by scottamain** [comment]
Gotcha, thanks. @yeraydiazdiaz can you please provide an update?

**Comment by scottamain** [comment]
Got it, thank you!
