### ISSUE TITLE
PEP 541 Request: suds

### ISSUE THREAD

**Issue by phillbaker** [pypa/pypi-support#1338]
### Project to be claimed

`suds`: https://pypi.org/project/suds

### Your PyPI username

`phillbaker`: https://pypi.org/user/phillbaker

### Reasons for the request

We believe the project has been abandoned:
* The pypi package has not had a release in over 10 years
* The git repo for the owner has not had a commit in 6 years (https://github.com/jortel/suds)

A community based maintenance fork has been going for several years now: https://github.com/suds-community/suds/. See discussion here with list of forks: https://github.com/suds-community/suds/issues/1 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

* original SVN: http://svn.fedorahosted.org/svn/suds (no longer accessible)
* import: https://github.com/jortel/suds

### Contact and additional research

* https://github.com/suds-community/suds/issues/1
* https://github.com/suds-community/suds/issues/6

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Other reasons to restore a maintenance team for this project:

- Because it's been unmaintained, it's had a series of forks exposing the same Python package ("suds"), leading to lots of toil and a poor experience for users.

**Comment by yeraydiazdiaz** [comment]
I will now start the reachability process, as part of it I'm tagging GitHub user @jortel who I believe is the owner of the project.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
