### ISSUE TITLE
PEP 541 Request: tformat

### ISSUE THREAD

**Issue by cartertemm** [pypa/pypi-support#1341]
### Project to be claimed

`tformat`: https://pypi.org/project/tformat

### Your PyPI username

`cartertemm`: https://pypi.org/user/cartertemm

### Reasons for the request

It looks to me like the project has been abandoned, or was never uploaded to the index to begin with seeing as no releases have been posted. Also, the only version to be had was created over five years ago.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

`tformat`: https://github.com/cartertemm/tformat

### Contact and additional research

I tried tracking down the project's maintainer, but unfortunately wasn't able to find anything of substance.

* There is no email address listed on the  maintainer's profile.
* The repository linked to in the project description (https://githib.com/Inori-Y/tFormat) appears to have a typo in both the domain and username. Multiple variations have been attempted with no success.
* A [Github search](https://github.com/search?q=tformat) yielded nothing of use

Though best case would be to get the name, if someone had any further ideas about how to best get a hold of the original maintainer I would certainly appreciate them.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
