### ISSUE TITLE
Limit Request: PySide6 - 400 MB

### ISSUE THREAD

**Issue by cmaureir** [pypa/pypi-support#1342]
### Project URL

https://pypi.org/project/pyside6

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

400 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Qt for Python (a.k.a PySide) reached the 6.2.0 release, with that, Qt included modules that were not ported in the previous releases (6.0 and 6.1) which we had in the past for https://pypi.org/project/pyside2 (equivalent to Qt 5.15) increasing the wheel size.
Additionally, the latest Qt release is compatible with universal binaries, which enlarged the size of our macOS wheels.

With the current release, the largest wheel is around 300 MB

We were unable to upload the Linux and macOS wheels due to the limit we have requested in the past (250 MB), and only Windows was able to be uploaded.

Once we have our first set of macOS wheels compatible with M1 processors, the wheel size might get larger again, that's way I'm requesting 400 MB, just to be safe. In case PyPi administrators prefer us to do another request when we face the problem, I'm totally fine with that approach too :)

I hope the argumentation is enough to justify an increase in our wheel size limits, if something is not clear, please let me know.
Thanks for your time and work.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! I've gone ahead and bumped up the file size limit to 400 MB, on PyPI and TestPyPI, for `pyside6`.

Please be mindful of the frequency of your releases at this size. I'll also use this as an opportunity to remind/inform you that there's a total project size limit of 10 GB on the project. So, if the size of the individual assets hits 400 MB OR the project hits 10 GB, the upload will be rejected.
