### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kobayashi69** [pypa/pypi-support#1343]
### PyPI Username

datarobot

### Reason for request

I believe the email associated with this account is info@datarobot.com but when I try to initiate a password reset for the email address it has no record of the email address.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I see that this account has been accessed as recently as October 12, 2021. If you still need help with account recovery please reopen this ticket.
