### ISSUE TITLE
PEP 541 Request: cadbiom

### ISSUE THREAD

**Issue by JeanCoquet** [pypa/pypi-support#1344]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/cadbiom

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jeancoquet

### Reasons for the request

We would like to request access to the maintenance of the "cadbiom" project and the sub-projects "cadbiom-cmd" and "cadbiom-gui". Cadbiom is an academic project developed by the French research institutes Inria, Irisa and Genouest ([http://cadbiom.genouest.org](http://cadbiom.genouest.org)). The previous maintainer of the project, Pierre Vignet (username: `pierrev`), has left the project and does not answer emails and phone calls anymore. In addition, his email address associated with his PyPI account has been deactivated. 

In conclusion, we have no more solution to maintain the PyPI repository. We want to transfer the ownership of my username `jeancoquet` and to update the PyPI repository with the latest version of Cadbiom ([https://gitlab.inria.fr/pvignet/cadbiom/-/tree/dev](https://gitlab.inria.fr/pvignet/cadbiom/-/tree/dev)).

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://gitlab.inria.fr/pvignet/cadbiom/-/tree/dev

### Contact and additional research

In 2020, Pierre Vignet, the previous maintainer of the project, left the academic team and does not answer emails and phone calls anymore. We tried to contact him through his friends, without success.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by JeanCoquet** [comment]
Dear PyPI support,

I would like to follow-up if you had the chance to consider our request.
Do I need to provide any additional information?

Thank you very much,
Jean

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
