### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by d4rk-lucif3r** [pypa/pypi-support#1345]
### PyPI Username

d4rk-lucif3r

### Reason for request

My phone got lost and i don't have any backup codes for my 2FA app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by d4rk-lucif3r** [comment]
Please respond @jamadden @ewdurbin. Please help

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by d4rk-lucif3r** [comment]
Done

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
