### ISSUE TITLE
Limit Request: Accera - 300 MB

### ISSUE THREAD

**Issue by lisaong** [pypa/pypi-support#1346]
### Project URL

https://pypi.org/project/accera

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

300MB

### Which indexes

PyPI

### Reasons for the request

Accera is a programming model, a domain-specific programming language embedded in Python, and an optimizing cross-compiler for compute-intensive code.

We currently support 9 configurations/platforms:
* 64-bit Python 3.7, 3.8, and 3.9 on ManyLinux, Windows, macOS

The reason for the additional size: 
Accera is a toolchain that generates optimized binary code at runtime, driven by the Python frontend. We rely on LLVM to produce binary code that is compatible to most platforms. The binaries include custom versions of some LLVM/MLIR tools.

Here are the uncompressed sizes of the largest files:

|binary file|size (MB)|short description|
|--|--|--|
| rc-opt | 278 | cross-compiler frontend |
| _lang_python.cython-3.8-x86_64-linux-gnu.so | 246 | Python bindings |
| argo-translate | 105 | GPU code generator (may increase to 250MB) |
| llc | 91 | byte code generator (modified from LLVM) |
| opt | 91 | binary code optimizer (modified from LLVM) |

Current whl size: 255MB
We are still working on GPU support which can add another 100-150MB. The current requested size is 300MB after extrapolation using the same compression rate.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by lisaong** [comment]
Source url can be provided upon request. This is a private Github repository while we are going through some internal processes to get the source code released.

**Comment by pradyunsg** [comment]
This request seems somewhat... large. It is associated with an established organisation (Microsoft) and the main reason for the size is compiled binaries. However, there's an overall limit on total project size as well (defaults at 10 GB), which would mean that this project will hit that limit in the 6th release (assuming 9 files, each at ~200 MB).

I'll let someone else chip in. :)

**Comment by lisaong** [comment]
Thanks for the feedback. We’ve split up the packages to reduce the size for each to under 100MB. I think we can close this request for now and raise it if/when we can’t make the split packages fit. 

https://pypi.org/project/accera/
https://pypi.org/project/accera-compilers/
https://pypi.org/project/accera-gpu/
https://pypi.org/project/accera-llvm/

**Comment by pradyunsg** [comment]
Closing per the comment above!
