### ISSUE TITLE
PEP 541 Request: django-object-permissions

### ISSUE THREAD

**Issue by jeremystretch** [pypa/pypi-support#1347]
### Project to be claimed

`django-object-permissions`: https://pypi.org/project/django-object-permissions

### Your PyPI username

`jeremystretch`: https://pypi.org/user/jeremystretch

### Reasons for the request

I am requesting ownership of this name as I believe the original project has been abandoned for quite some time. PyPI indicates that its last release was in June 2013, and it currently has [no dependent packages](https://libraries.io/pypi/django-object-permissions). Additionally, the source repository no longer seems to be available.

My intention is to publish a new package enabling object-based permissions for the [Django](https://www.djangoproject.com/) web framework as a spin-off from an existing open source project called [NetBox](https://github.com/netbox-community/netbox). That initiative is being tracked [here](https://github.com/netbox-community/netbox/issues/6439).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ns1labs/django-object-permissions

### Contact and additional research

I have emailed the two listed maintainers for whom an email address could be located ([kreneskyp](https://pypi.org/user/kreneskyp/) and [MostAwesomeDude](https://pypi.org/user/MostAwesomeDude/)), however given the age of the project I'm not optimistic about hearing back.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Thanks for the replies, I have transfered the project to @jeremystretch. Please keep in mind you will not be able to upload new artifacts for the versions listed in https://pypi.org/project/django-object-permissions/#history.

**Comment by jeremystretch** [comment]
Thanks, everyone! I really appreciate the assistance!
