### ISSUE TITLE
Limit Request: DYSTS - 120 MB

### ISSUE THREAD

**Issue by williamgilpin** [pypa/pypi-support#1348]
### Project URL

https://pypi.org/project/dysts/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

200

### Which indexes

PyPI

### Reasons for the request

This is a repository for training large neural networks on time series. The large file size is due to a large number of time series datasets that are stored and used for pretraining. Given the nature of the project, a larger limit will reduce the amount of compute required by users. Thank you very much for considering my request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! Could you clarify what the exact limit is that you wish to request? Is it 200 MB or 120 MB?

**Comment by williamgilpin** [comment]
Hi! Could we go for **200 MB**? 

The current size is ~120 MB, but I want to leave some margin, since I might gradually add additional models and datasets over time. Thank you very much!

**Comment by pradyunsg** [comment]
Set the upload limit to 200 MB on 'dysts'. :)

**Comment by williamgilpin** [comment]
Thank you!
