### ISSUE TITLE
Limit Request: napalytics-dependencies - 120 MB

### ISSUE THREAD

**Issue by jeffrey990macharia0** [pypa/pypi-support#1351]
### Project URL

https://pypi.org/project/napalytics-dependencies/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

120 MB

### Which indexes

PyPI

### Reasons for the request

The package is required to be installed in a no internet environment which means that all third party package need to be included in this project with the total size of these third party packages reaching 120MB. pypi in this case  will only be used once to fetch this package with all its dependencies in this project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Looked into this, and it's unclear to me what napalytics is for. The package source code link (https://github.com/ert068001/napalytics) is a 404, and there's no real documentation site that can be found.

**Comment by pradyunsg** [comment]
Hi @jeffrey990macharia0, is this still relevant? If there's no response on this in the next 4 weeks, I'll close this ticket.

**Comment by jeffrey990macharia0** [comment]
Hello, apologies for the late reply on this, this project was closed by the
client who needed it therefore it is not relevant anymore.

**Comment by pradyunsg** [comment]
Closing since this is not relevant! :)

**Comment by jeffrey990macharia0** [comment]
No problem. Thank you for reaching out.
