### ISSUE TITLE
Limit Request: pgadmin4 - 150 MB

### ISSUE THREAD

**Issue by dpage-edb** [pypa/pypi-support#1356]
### Project URL

https://pypi.org/project/pgadmin4/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

150 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Recent releases of pgAdmin have steadily increased in size to around the 100MB mark. The v6.0 release (being published today) includes some major changes that bring it in at around 113 MB. Future releases are likely to grow further as new features are added.

Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by FrankyBoy** [comment]
Would be great if anyone could look into not just this but the many limit requests that seem to be open [since mid of september](https://github.com/pypa/pypi-support/issues?page=2&q=is%3Aissue+is%3Aopen+limit+request) :/

**Comment by pradyunsg** [comment]
@FrankyBoy That's because PyPI's support tickets are primarily handled by volunteers. You can read more about how PyPI is maintained/run here: https://dustingram.com/articles/2021/04/14/powering-the-python-package-index-in-2021/.

**Comment by pradyunsg** [comment]
Increased the limit on PyPI and TestPyPI to 200 MB.
