### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dbinger** [pypa/pypi-support#1362]
### PyPI Username

dbinger

### Reason for request

I created the PyPI qp project over a decade ago, when I worked at CNRI.
I no longer have access to the email I used when I created the qp project.
https://pypi.org/project/qp/

I would like to get access to my account again.
I've made this request earlier this year and there has been no response.
Please respond.

David Binger
dbinger@forcedphysics.com
https://www.linkedin.com/in/david-binger-77162650/
571-243-7567

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
duplicate: #1277
