### ISSUE TITLE
PEP 541 Request: mermaid

### ISSUE THREAD

**Issue by HastingsGreer** [pypa/pypi-support#1365]
### Project to be claimed

`mermaid`: https://pypi.org/project/mermaid

### Your PyPI username

`hastings.greer`: https://pypi.org/user/hastings.greer

### Reasons for the request

I believe that the project at https://pypi.org/project/mermaid/ is invalid. It has not been modified since it was created in 2016, and has no associated repository, files or releases. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/uncbiag/mermaid

### Contact and additional research

I have not been able to find contact information for the current owner. The only public information available to contact them is their username, helali, which is a common surname. Googling "helali" and "helali mermaid" did not return useful results.

I have not been able to find another python package named mermaid:
 
- https://mermaid.readthedocs.io refers to our project and is maintained by us, so this is not a conflict.
- https://anaconda.org/uncbiag/mermaid refers to our project

    

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by HastingsGreer** [comment]
@helali Are you by any chance the owner of the package mermaid on pip?

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
