### ISSUE TITLE
PEP 541 Request: poof

### ISSUE THREAD

**Issue by pr3d4t0r** [pypa/pypi-support#1369]
### Project to be claimed

`poof`: https://pypi.org/project/poof

### Your PyPI username

`ciurana`: https://pypi.org/user/ciurana

### Reasons for the request

The original `poof` package owner, Andrew Hoskins, **granted us permission to claim the name for our project**.  There are no known users of the original `poof` package other than the original owner - see https://libraries.io/pypi/poof

Per PEP 541:

1. The project has been abandoned for 5 years
2. The existing owner has granted permission to reclaim the name
3. The `poof` name fits with the new project's goals and objectives of providing an efficient and secure backup mechanism for directories and files to a remote cloud drive with minimum fuss and with an easy to understand command set
4. The poof backup project installs its end-user executable to `/usr/local/bin/poof` or to `$VIRTUALENV/bin/poof` and conflicts with the abandoned `poof` executable
5. Download stats:  https://pypistats.org/packages/poof - the downloads from the last 30 days are most likely the ones that I did to have a look at the package, and come from our gateway at `varenka.cime.net` or `betty.cime.net` (`50.211.203.180`, `50.211.203.178`)
6. As indicated in the intro to this request, original owner Andrew Hoskins has no additional reservations re: the name change

Thanks for your consideration.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ahoskins/poof

### Contact and additional research

We have email exchanges with Andrew Hoskins of our request, and his reply.  These emails are attached as .eml sources, .zipped.  I contacted Andrew via his Gmail address and via a GitHub issue:  https://github.com/ahoskins/poof/issues/3 -- the contact messages via Gmail and GitHub issue were identical.

[poof-PyPI-msgs.zip](https://github.com/pypa/pypi-support/files/7325523/poof-PyPI-msgs.zip)

Thanks again for your consideration.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @pr3d4t0r, thanks for the detailed description, I do require confirmation from @ahoskins so I will attempt contact with him before I move on with the transfer.

**Comment by pr3d4t0r** [comment]
@yeraydiazdiaz - Awesome, thanks.  You have his email address in the messages I attached, please let me know if you need anything else.  Have a successful week!

**Comment by ahoskins** [comment]
Hi, confirmed you can take the poof name. Apologies for the delays! 

- Andrew

**Comment by pr3d4t0r** [comment]
@yeraydiazdiaz - here we go, from Mr. Hoskins himself.  Yey!

@ahoskins - Thanks again, mate.  Have a great end-of-the-year.

What are the next steps?

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @ahoskins. Transfer complete.

**Comment by pr3d4t0r** [comment]
@yeraydiazdiaz - Thank you very much!  Have a great week.
