### ISSUE TITLE
Limit Request: bigdl-dllib - 120 MB

### ISSUE THREAD

**Issue by jason-dai** [pypa/pypi-support#1370]
### Project URL

https://pypi.org/project/bigdl-dllib/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

120 MB

### Which indexes

PyPI

### Reasons for the request

We plan to migrate the original [BigDL](https://github.com/intel-analytics/BigDL) project (distributed deep learning library for Apache Spark) to `bigdl-dllib`.

The original BigDL project at Pypi (https://pypi.org/project/BigDL/) has a size limit of 120MB, as it contains native libraries (MKL, openMP, etc.) for CPU accelerations, and we would like to increase the limit of bigdl-dllib (https://pypi.org/project/bigdl-dllib/) to 120Mb as well.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jason-dai** [comment]
@ewdurbin @pradyunsg Sorry for interrupting, but I wonder if you can take a look at this issue?

**Comment by ewdurbin** [comment]
Hi @jason-dai it appears that [bigdl-dllib/](https://pypi.org/project/bigdl-dllib/) is performing nightly releases to PyPI. With large distribution files, you will find that nightly releases will quickly consume your project total size limit, and reduce your chances of receiving such a limit increase when it is reached.

File size limit increased to 120MiB, with a recommendation of disabling nightly releases.
