### ISSUE TITLE
Limit Request: bigdl-orca - 200 MB

### ISSUE THREAD

**Issue by jason-dai** [pypa/pypi-support#1371]
### Project URL

https://pypi.org/project/bigdl-orca/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

200 MB

### Which indexes

PyPI

### Reasons for the request

We plan to migrate the original [Analytics Zoo](https://github.com/intel-analytics/analytics-zoo) project (distributed TensorFlow, PyTorch, OpenVINO & Ray on Apache Spark) to `bigdl-orca`.

The original Analytics Zoo project at Pypi (https://pypi.org/project/analytics-zoo/) has a size limit of 200MB, as it contains native libraries (tensorflow, openvino, etc.) for deep learning accelerations on CPU, and we would like to increase the limit of bigdl-orca (https://pypi.org/project/bigdl-orca/) to 200Mb as well.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jason-dai** [comment]
@ewdurbin @pradyunsg Sorry for interrupting, but I wonder if you can take a look at this issue?

**Comment by ewdurbin** [comment]
Hi @jason-dai it appears that [bigdl-orca/](https://pypi.org/project/bigdl-orca/) is performing nightly releases to PyPI. With large distribution files, you will find that nightly releases will quickly consume your project total size limit, and reduce your chances of receiving such a limit increase when it is reached.

File size limit increased to 200MiB, with a recommendation of disabling nightly releases.
