### ISSUE TITLE
Limit Request: dearpygui - 20 GB

### ISSUE THREAD

**Issue by hoffstadt** [pypa/pypi-support#1373]
### Project URL

https://pypi.org/project/dearpygui/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20 GB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

We continually hit the 10gb limit. As a large C extension, the wheels are relatively large. We are working to decrease the size but until then, we'd like a limit increase.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I see that the project is at 1.2 GB right now. Has something changed?

**Comment by pradyunsg** [comment]
If there's no response in the next 4 weeks, I'll close this when I come back around.

**Comment by hoffstadt** [comment]
Hi, just say this. We removed most of our beta wheels to reduce the size. We also changed the build process up to reduce the size. further. I still think an increase to 20 GB would be beneficial for the future.

**Comment by pradyunsg** [comment]
Alright, I've bumped the limit to 20 GiB.
