### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wsapiens** [pypa/pypi-support#1375]
### PyPI Username

wsapiens

### Reason for request

Lost 2FA authentication app while upgrading my mobile device.
When I upgrade my mobile device OS, Google Authenticator duplicated the tokens many times. Deleing one of duplicated one caused all gone. 

I forgot to generate any recovery code, so now I lost access to my PyPI account.
Would you please help me access my account?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
duplicate: #1325
