### ISSUE TITLE
Limit Request: `pantsbuild.pants` - 40 GB

### ISSUE THREAD

**Issue by stuhood** [pypa/pypi-support#1376]
### Project URL

https://pypi.org/project/pantsbuild.pants/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

40 GB

### Which indexes

PyPI

### Reasons for the request

Hey folks!

The https://www.pantsbuild.org/ project has been releasing to PyPI for 7 years, initially with weekly stable releases, briefly with quarterly stable releases, and for the last few years with monthly stable releases. We've accumulated a lot of releases as a result.

We have used the `pypi-cleanup` tool to delete as many of our `dev` and `rc` releases as possible, but we're getting into the danger zone of considering whether some releases are too recent to delete, and we're probably a few months away from needing to delete stable releases. See https://github.com/pantsbuild/pants/issues/11614 for more backstory.

Our wheel(s) contain 30% native code (which makes up most of the total volume on disk) and 70% python. Unfortunately, we are not able to publish a universal wheel (because APIs are not stable enough across 3.x minor versions), so we end up needing to publish across multiple Python versions.

We're asking for our limit to be increased from 20GB to 40GB (doubled) in order to avoid needing to bug you all again in the next few years (*fingers crossed*).

Thank you for your consideration!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Question for @stuhood: What's the story with the 60 MB manylinux wheel vs the 9 MB MacOS? What makes it so much bigger than the MacOS wheels?

**Comment by pradyunsg** [comment]
> This is a big enough request though, that I'd like to wait on at least one more moderator / admin to comment before actioning on this. :)

This is basically what we're waiting on now. I've pinged the relevant people, who might be able to take a closer look when they have time.

**Comment by ewdurbin** [comment]
Project total size for `pantsbuild.pants` increased to 40GiB.

**Comment by stuhood** [comment]
Thank you!
