### ISSUE TITLE
Limit Request: pycbc - 20 GB

### ISSUE THREAD

**Issue by ahnitz** [pypa/pypi-support#1379]
### Project URL

pycbc

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20000 MB

### Which indexes

TestPyPI

### Reasons for the request

First, I don't actually want to request the limit be increased, though that would solve our issue. Alternatively, we'd just like the *testpypi* server (not regular pypi) to have all our files removed. We had been using  testpypi it as part of the CI infrastructure to make sure releases could be uploaded, but this apparently was too often and we've filled up the test server allotment of 10GB. I'ts a pain to have to go manually through the server and delete entries one-by-one. If there were a 'purge everything' button or some way to do a mass purge we would definitely use that. We are working to limit the uploads to testpypi so hopefully this should not occur again. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
There is https://pypi.org/project/pypi-cleanup/, which might be what you're looking for. :)

**Comment by pradyunsg** [comment]
Closing since they can run a cleanup script, like the one linked above.
