### ISSUE TITLE
PEP 541 Request: funfact

### ISSUE THREAD

**Issue by yhtang** [pypa/pypi-support#1380]
### Project to be claimed

`funfact`: https://pypi.org/project/funfact

### Your PyPI username

`maxin`: https://pypi.org/user/maxin

### Reasons for the request

- Abandoned project: the current `funfact` project was created in Jan 2017 and was never updated since then.
- Name squatting: excluding boilerplate files, the package contains a single `__init__.py` with 2 lines of content:
```python
def fact():
	return('Banging your head against a wall burns 150 calories an hour')
```

A Google search with the name of author and package name leads to a GitHub repo at [Shivams334/funfact](https://github.com/Shivams334/funfact), which is a fork of [Pradhvan/funfact](https://github.com/Pradhvan/funfact). Neither repos received updates since Oct 2018. The `README.md` file indicates that this is a package for testing purposes only.

We propose to reuse the name for the `FunFact` package [1](https://github.com/yhtang/FunFact),[2](https://www.osti.gov/biblio/1821449-funfact-v0) that is been developed by a team here at Lawrence Berkeley National Laboratory. The proposed package is a linear algebra/machine learning package that can be used to compute **fun**ctional **fact**orization of algebraic tensors. The package is undergoing active development, which is funded by the Berkeley Lab through a Laboratory Directed Research and Development Program (LDRD) project. The source code is released under a BSD license. Renaming the package on our end is very difficult due to the package and the name `FunFact` has already gone through the Department of Energy software disclosure process.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Source and fork repositories of the current package:
- https://github.com/Pradhvan/funfact
- https://github.com/Shivams334/funfact
- https://github.com/yhtang/funfact-1 (I made a fork of it for archiving purposes)

Repository of the proposed replacement `FunFact` package:
- https://github.com/yhtang/FunFact
- https://www.osti.gov/biblio/1821449-funfact-v0

### Contact and additional research

I have reached out to shivams334@gmail.com, which is listed on the current package's PyPI page. No response was received. The [source code repo](https://github.com/Shivams334/funfact) does not have the "Issues" section enabled.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yhtang** [comment]
> I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

Many thanks!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by yhtang** [comment]
Wonderful. Thanks again!
