### ISSUE TITLE
Limit Request: qt6-applications - 200 MB

### ISSUE THREAD

**Issue by altendky** [pypa/pypi-support#1382]
### Project URL

https://pypi.org/project/qt6-applications/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

200

### Which indexes

PyPI, TestPyPI

### Reasons for the request

The limit has already been increased for the Qt5 edition of this project (https://github.com/pypa/pypi-support/issues/1074).  The builds for the new Qt versions have doubled in size to about 150MB.  This is due to Qt creating universal binaries to cover both Intel and ARM.  Speaking of which, I need to go learn how to mark the wheels accordingly...

Thanks for your consideration.

Cheers,
-kyle

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by altendky** [comment]
Just a gentle bump on this.  And I swear, I just happened back here exactly a month later.  `:]`

**Comment by pradyunsg** [comment]
Limit on PyPI has been bumped to 200 MB. https://test.pypi.org/project/qt6-applications/ does not exist, and hasn't been touched by me. :)

**Comment by altendky** [comment]
Sorry for mislisting test pypi.  Thanks for the bump!
