### ISSUE TITLE
PEP 541 Request: Mail

### ISSUE THREAD

**Issue by SunPodder** [pypa/pypi-support#1386]
### Project to be claimed

`Mail`: https://pypi.org/project/Mail

### Your PyPI username

`SunPodder`: https://pypi.org/user/SunPodder

### Reasons for the request

The project is not maintained anymore since last 10 years. The project maintainer also hasn't any git repo associated with it.

I made a new package that requires this project name. You can check it at https://github.com/SunPodder/Mail.py .

### Maintenance or replacement?

Replacement

### Source code repositories URLs

No git repo found of the current package. 

My new package repo: https://github.com/SunPodder/Mail.py

### Contact and additional research

I didn't found any contact info of the current owner. I found his github profile and opened an issue there about the name transfer. But hasn't received any response yet.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @SunPodder, while it is true that the project seems abandoned, it's been downloaded [1,590 downloads last week](https://pypistats.org/packages/mail).

Given your request is for replacement I think the best course of action would be for you to consider a different name for your project, as the risk of breakage for end users is too large.
