### ISSUE TITLE
PEP 541 Request: plexsim

### ISSUE THREAD

**Issue by cvanelteren** [pypa/pypi-support#1387]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/plexsim

### Your PyPI username

`USER_NAME`: https://pypi.org/user/cvanelteren

### Reasons for the request

I wrote a module that I wish to upload but the name is rejected. I cannot seem to find a project with a similar name on pypi, nor is it part of the standard library. Can I please claim this name?

Best,
C

### Source code repositories URLs

https://github.com/cvanelteren/Plexsim

### Contact and additional research

I cannot find a project with a similar name.

![image](https://user-images.githubusercontent.com/19485143/137495381-a023089c-53b2-4658-b3f9-cf7ee7511f75.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @cvanelteren, `plexsim` was placed in the prohibited project names list, @pypa/warehouse-admins could you please release the name to user `cvanelteren`?

**Comment by ewdurbin** [comment]
`plexsim` Project has been released to the `cvanelteren` User on PyPI.
