### ISSUE TITLE
PEP 541 Request: mode-streaming

### ISSUE THREAD

**Issue by taybin** [pypa/pypi-support#1394]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mode-streaming

### Your PyPI username

`USER_NAME`: https://pypi.org/user/taybinrutkin

### Reasons for the request

mode-streaming is a fork of mode under the umbrella of faust-streaming, a fork of faust. The person who originally published mode-streaming to pypi, max-k (https://pypi.org/user/max-k/), has disappeared and we want to make a new release of the library.

We have emailed him and tagged him in github issues.  He has not responded to any attempts.  We have also noticed that his personal website is offline.

I would like ownership of the pypi project for mode-streaming so that I can:
1) publish a new release
2) grant some other people permissions so this situation doesn't happen again

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/faust-streaming/mode

### Contact and additional research

His email address is: max-k@post.com.  He hasn't responded to that.  His website is https://blog.max-k.org, but that appears to be offline.  I googled his name (Thomas Sarboni) and location (Antibes, France) and didn't see any news about him.  His last public commit on github was 2021-04-28.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @taybin, I will now start the reachability process for your request, hopefully we will hear back from the owner and move forward with your request.

**Comment by patkivikram** [comment]
Any update on this?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
