### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yellowshippo** [pypa/pypi-support#1396]
### PyPI Username

ricos

### Reason for request

Due to my device change, somehow I lost my 2FA authentication. I still have access to my email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by yellowshippo** [comment]
Thank you very much!
