### ISSUE TITLE
Limit Request: h2o - 20 GB

### ISSUE THREAD

**Issue by sebhrusen** [pypa/pypi-support#1403]
### Project URL

https://pypi.org/project/h2o/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20000

### Which indexes

PyPI

### Reasons for the request

H2O is a popular open-source ML platform (https://github.com/h2oai/h2o-3/).
The python package comes with an embedded backend packaged as a jar: we're thinking about splitting the wheel to keep some of the more stable dependencies included in the jar as a separate artifact, but even so, we need the total project size to be increased to be able to push future releases.
Thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mn-mikke** [comment]
Hello, any update on this issue?  H2O-3 project is not able to publish any new released artifacts to PyPi because of the current limit.

Thanks a lot for your help!

cc @di @pradyunsg

**Comment by ledell** [comment]
Hi there, @pradyunsg @di.  With respect for all the work you're doing and time you're spending to keep PyPI operational, we are wondering if you can provide us an update on this?  

We have been waiting 3 months with no response, and are blocked from publishing new h2o releases.  We had a new release (v3.36.0.1) at the end of 2021 and still nobody can download it from PyPI.  Can you tell us if there's something we need to do on our end, or let us know what's happening?  We have a [second request](https://github.com/pypa/pypi-support/issues/1400) open for 3 months as well.  I appreciate your help, in advance.

**Comment by sebhrusen** [comment]
Thanks a lot @ewdurbin ! We'll keep our promise on our side and will publish smaller wheels soon.

**Comment by ledell** [comment]
@ewdurbin Thank you so much for your help.  Truly appreciated!!
