### ISSUE TITLE
PEP 541 Request: cinnamon

### ISSUE THREAD

**Issue by YohannLeFaou** [pypa/pypi-support#1404]
### Project to be claimed

https://pypi.org/project/cinnamon

### Your PyPI username

https://pypi.org/user/YohannLF

### Reasons for the request

The project name "cinnamon" is already taken by an empty project : https://pypi.org/project/cinnamon/0.0.1/

I would like to publish my company project also called cinnamon on PyPi.

Thanks.

### Source code repositories URLs

https://github.com/zelros/cinnamon

### Contact and additional research

I tried to reach Dan by email. 

<img width="691" alt="Capture d’écran 2021-10-20 à 18 21 50" src="https://user-images.githubusercontent.com/13356017/138132334-d5d029a3-2417-43a5-8cac-41874081e422.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by YohannLeFaou** [comment]
Thanks!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
