### ISSUE TITLE
PEP 541 Request: peloton-client

### ISSUE THREAD

**Issue by kotko** [pypa/pypi-support#1405]
### Project to be claimed

peloton-client

### Your PyPI username

kotko

### Reasons for the request

As far as I understand, the project has no releases

### Contact and additional research

I don't know how to contact him

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by kotko** [comment]
hi @yeraydiazdiaz, do you have some news for me?

**Comment by yeraydiazdiaz** [comment]
The owner, a security engineer at Uber, replied and requested this project not to be transferred as it was used as a dependency attack to Uber's infrastructure.
