### ISSUE TITLE
PEP 541 Request: `smithers`

### ISSUE THREAD

**Issue by ndem0** [pypa/pypi-support#1406]
### Project to be claimed

`smithers`: https://pypi.org/project/smithers

### Your PyPI username

`ndemo`: https://pypi.org/user/ndemo

### Reasons for the request

No activities in the last 3 years, no activities after the initial deploy, homepage of the project is not available, package stucked to 0.0.0 version.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

[https://github.com/mathLab/Smithers](https://github.com/mathLab/Smithers)

### Contact and additional research

Unable to find any contact of the current owner of the PyPI project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
