### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jbiggsets** [pypa/pypi-support#1407]
### PyPI Username

jbiggs_ets

### Reason for request

Lost access to my primary email (jbiggs@ets.org), and would like to transition to my personal email address (jeremy.m.biggs@gmail.com). 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
As this email address was already associated with the account, it has been set to the primary address.
