### ISSUE TITLE
Limit Request: opencv-contrib-python - 45 GB

### ISSUE THREAD

**Issue by asmorkalov** [pypa/pypi-support#1413]
### Project URL

https://pypi.org/manage/project/opencv-contrib-python

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

46080

### Which indexes

PyPI

### Reasons for the request

OpenCV is puplic Open Computer Vision Library. It's written in C++ and Python interface is just bindings for the C++ code. OpenCV-Contrib package contains core OpenCV library + community contributed algorithms and modules. As soon as we increase number of supported configurations (+Mac M1, Python 3.10, added LAPACK) the storage footprint grows significantly. The OpenCV team discusses deprecation and removal strategy for Python packages. So hopefully, the new requests will not be required in future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hiya! Thanks for your patience. PyPI is maintained by volunteers, so these tickets take a while to be processed.

This project current has a total size of 39.5 GiB. I can't tell when the limit was raised to 40 GiB (it might've been grandfather'd in, when the limits were introduced) so I'll defer to the PyPI admins on this one. :)

**Comment by pradyunsg** [comment]
> So hopefully, the new requests will not be required in future.

Granting this, on this basis. If this comes up again, I'll let the admins decide. :)

---

Project size limit bumped to 45 GB.
