### ISSUE TITLE
PEP 541 Request: speedyxml

### ISSUE THREAD

**Issue by kilroy42** [pypa/pypi-support#1415]
### Project to be claimed

`speedyxml`: https://pypi.org/project/speedyxml

### Your PyPI username

`kilroy42`: https://pypi.org/user/kilroy42

### Reasons for the request

The project is mine, I just cannot reach it anymore because the login was deleted (kilroy@uni-koblenz.de). I still have the password, but I do no longer own the email address (I am no longer in this university).

I can provide the password to prove I am "me" if the old account is somewhere around there.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://pypi.org/project/speedyxml/

### Contact and additional research

I am the owner myself, so no contact is needed.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
In this case the best course of action is to open a [recovery account issue](https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.md&title=Account+recovery+request) rather than transferring the project.
