### ISSUE TITLE
Account recovery request TestPyPI

### ISSUE THREAD

**Issue by zoncrd** [pypa/pypi-support#1417]
### PyPI Username

zoncrd

### Reason for request

I get an "Internal Server Error" page when I try to login to Test PyPI, after I insert my 2FA token.

The 2FA token is generated with Google Auth android app that I registered through QR code recently.

![immagine](https://user-images.githubusercontent.com/6806779/139270458-bd4a7b32-2dbb-4527-98d5-c6af7ca88f92.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This was due to a transient error that is now resolved.
