### ISSUE TITLE
Limit Request: RapidWright - 120MB

### ISSUE THREAD

**Issue by clavin-xlnx** [pypa/pypi-support#1418]
### Project URL

https://pypi.org/project/rapidwright/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

120

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Our project packages several Java capabilities into a standalone jar that exceeds the existing limit (~100MBs).  The file is already compressed, so there isn't much else we can do to shrink the file.  Currently, to work around this, we have to download the file after `pip install` which is not a clean way to proceed. It would be great if we could get the file packaged directly and that would be enabled with a file size limit increase.  Thanks for your consideration!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limit raised to 200 MB for PyPI and TestPyPI.

I don't imagine we'd increase the limit further though, and you'd likely need bring back the current approach then -- handling the JAR file in a manner similar to how NLTK handles data: https://www.nltk.org/data.html.
