### ISSUE TITLE
PEP 541 Request: igraph-python

### ISSUE THREAD

**Issue by vtraag** [pypa/pypi-support#1420]
### Project to be claimed

`igraph-python`: https://pypi.org/project/igraph-python

### Your PyPI username

`vtraag`: https://pypi.org/user/vtraag

### Reasons for the request

The development team of @igraph is providing a Python interface of its C library under the name [`python-igraph`](https://pypi.org/project/python-igraph/). This is currently being transitioned to [`igraph`](https://pypi.org/project/igraph/) to avoid [previous difficulties](https://github.com/igraph/python-igraph/issues/412) and make it easier for users to install `igraph` simply using `pip install igraph`. 

At some point, some other people made available a release under the name [`igraph-python`](https://pypi.org/project/igraph-python/). This causes confusion for some users, who accidentally try to install `igraph-python` instead of `python-igraph` (which is now being transitioned to `igraph`). The release that was made available under `igraph-python` is outdated (it is now more than 3 years old) and should not be used.

We preferably would like to request removal of `igraph-python`. I understand that PEP 541 is mainly about the transfer of ownership, not the removal of packages. The conditions for invalid packages or for intellectual property may not apply, I am not sure. If removal of `igraph-python` would not be possible, an alternative possibility with a transfer of ownership, is that we could make sure that `igraph-python` is a stub towards the correct version of `igraph`, similar to what `igraph-python` does at the moment.

@ntamas is the owner of `python-igraph` and `igraph` on PyPI and the main developer of the Python interface: https://pypi.org/user/ntamas/.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The Python interface of `igraph` is maintained at https://github.com/igraph/python-igraph, the `igraph` C core is maintained at https://github.com/igraph/igraph.

### Contact and additional research

The user account [`zhaomingming`](https://pypi.org/user/zhaomingming/) is listed as maintainer for `igraph-python`. I have reached out to the email addresses listed in `igraph-python` twice, but after my latest attempt the email addresses were reported to no longer exist. 

I have tried to identify alternative mail addresses, looking at other packages made available by `zhaomingming`. I tried to contact them on these alternative mail addresses (26 may 2021), but I never received any reply. 

The latest update of any package on PyPI by `zhaomingming` dates from December 2018. Possibly, the user is no longer active.

There is a website referenced in one of the packages: http://www.zhaomingming.cn/. I am also unable to obtain any contact information from that website.

I cannot identify the users on GitHub, nor have I found any other way of contacting them. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @vtraag, thank you for the detailed description. While I agree the project would be best placed under the prohibited project names list or be transferred to you, PEP 541 states we cannot transfer a project against the wishes of the owner. As such I have started the reachability process for your request, hopefully we will hear back from the owner and proceed with the transfer soon.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by vtraag** [comment]
Great, thank you @yeraydiazdiaz !
