### ISSUE TITLE
PEP 541 Request: pystache

### ISSUE THREAD

**Issue by bakert** [pypa/pypi-support#1422]
### Project to be claimed

`pystache`: https://pypi.org/project/pystache

### Your PyPI username

`USER_NAME`: https://pypi.org/user/bakert

### Reasons for the request

https://github.com/defunkt/pystache/ no longer builds with latest setuptools. There has been no release since 2014. An updated fork exists at https://github.com/PennyDreadfulMTG/pystache/ which would like to become the official pypi version. It passes all of the same tests and is in all ways an upgrade not a sidegrade.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/defunkt/pystache/ - old repo
https://github.com/PennyDreadfulMTG/pystache/ - new repo

### Contact and additional research

https://github.com/PennyDreadfulMTG/pystache/issues/192 is one of many attempts to contact the author about the status of the project in the last 8 years that has not been successful.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bakert, I have started the reachability process for your request. Hopefully we will hear back soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owners replied accepting the transfer which is now complete.

**Comment by bakert** [comment]
Hurray! Thank you!
