### ISSUE TITLE
PEP 541 Request: pytest-sugar

### ISSUE THREAD

**Issue by graingert** [pypa/pypi-support#1424]
### Project to be claimed

`pytest-sugar`: https://pypi.org/project/pytest-sugar

### Your PyPI username

`Thomas.Grainger`: https://pypi.org/user/Thomas.Grainger

### Reasons for the request

It's a popular project used by celery and others. I plan to move it into the @pytest-dev organisation

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/Teemu/pytest-sugar

### Contact and additional research

There's a few open issues requesting adoption eg
https://github.com/Teemu/pytest-sugar/issues/184
https://github.com/Teemu/pytest-sugar/issues/224
https://github.com/pytest-dev/meta/issues/5

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @graingert, I started the reachability process for your request, also tagging GitHub user @Teemu, hopefully we will hear back soon and proceed with the transfer.

**Comment by graingert** [comment]
> Hello @graingert, I started the reachability process for your request, also tagging GitHub user @Teemu, hopefully we will hear back soon and proceed with the transfer.

Great, thanks a bunch!

**Comment by yeraydiazdiaz** [comment]
The owner replied not accepting the request, closing as per PEP 541.
