### ISSUE TITLE
PEP 541 Request: export

### ISSUE THREAD

**Issue by tombulled** [pypa/pypi-support#1425]
### Project to be claimed

`export`: https://pypi.org/project/export

### Your PyPI username

`tbulled`: https://pypi.org/user/tbulled

### Reasons for the request

I believe the current `export` package constitutes an _Invalid Project_ as the project contains no functionality.
The project contains the following code:
```python
from __future__ import print_function, unicode_literals

__version__ = "0.1.2"

# TODO: come up with something less lame
print("import export")
```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/zsiciarz/export

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @tombulled, you've state you'd like to replace the project but haven't supplied a project of your own, would you mind providing one?

**Comment by tombulled** [comment]
Hi @yeraydiazdiaz, no problem! I would be interested in replacing the `export` project with [tombulled/export](https://github.com/tombulled/export)

**Comment by yeraydiazdiaz** [comment]
Hello @tombulled, apologies, I must've not tagged this request properly and only just now realised it was still open. I noticed you're now using a different project name, are you still interested in `export`?

**Comment by tombulled** [comment]
Hi @yeraydiazdiaz, I can confirm that I am indeed still interested in `export` 🙂

**Comment by yeraydiazdiaz** [comment]
Thanks @tombulled, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by tombulled** [comment]
Thanks very much @yeraydiazdiaz for all of your help :slightly_smiling_face:
