### ISSUE TITLE
PEP 541 Request: ua

### ISSUE THREAD

**Issue by tombulled** [pypa/pypi-support#1426]
### Project to be claimed

`ua`: https://pypi.org/project/ua

### Your PyPI username

`tbulled`: https://pypi.org/user/tbulled

### Reasons for the request

I believe the current package constitutes an _Invalid Project_ as it contains no functionality.
The project only consists of a **setup.py** file with the following contents:
```python
from setuptools import setup

setup(
    name="ua",
    version="0.0.1"
)
```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

N/A

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @tombulled, you've stated you'd like to replace the project but haven't supplied a project of your own, would you mind providing one?

**Comment by tombulled** [comment]
Hi @yeraydiazdiaz, no problem! I would be interested in replacing the `ua` project with [tombulled/useragent](https://github.com/tombulled/useragent)

**Comment by yeraydiazdiaz** [comment]
Apologies again for the delay @tombulled, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by tombulled** [comment]
Thanks @yeraydiazdiaz, much appreciated :slightly_smiling_face:
