### ISSUE TITLE
PEP 541 Request: roster

### ISSUE THREAD

**Issue by tombulled** [pypa/pypi-support#1427]
### Project to be claimed

`roster`: https://pypi.org/project/roster

### Your PyPI username

`tbulled`: https://pypi.org/user/tbulled

### Reasons for the request

I believe that this package constitutes an _Invalid Project_ as it contains no functionality.
The project appears to only consist of a single **setup.py** file.

### Source code repositories URLs

https://github.com/soham96/chum

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @tombulled, you've stated you'd like to replace the project but haven't supplied a project of your own, would you mind providing one?

**Comment by tombulled** [comment]
Hi @yeraydiazdiaz, no problem! I would be interested in replacing the `roster` project with [tombulled/register](https://github.com/tombulled/register)

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid, I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by tombulled** [comment]
Thanks @yeraydiazdiaz, much appreciated :slightly_smiling_face:
