### ISSUE TITLE
Limit Request: Ray - 150 MB

### ISSUE THREAD

**Issue by xwjiang2010** [pypa/pypi-support#1428]
### Project URL

https://pypi.org/project/ray

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

150 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

We may want to add some debug symbols which increase our linux wheel size by 50MB.
Thanks so much for the help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by xwjiang2010** [comment]
@mwtian @scv119 Can you add more details and justification?

**Comment by mwtian** [comment]
Ray's manylinux wheels are currently slightly above 50MB, with compiled binaries. We want to include the minimal C++ debug info with the compiled binaries, but the manylinux wheel sizes would increase to become above 100MB. The debug info are pretty helpful for user debugging or reporting issues to us.

**Comment by pradyunsg** [comment]
Limits raised to 200 MB on PyPI and TestPyPI.
