### ISSUE TITLE
Limit Request: robosuite - 150 MB

### ISSUE THREAD

**Issue by yukezhu** [pypa/pypi-support#1432]
### Project URL

https://pypi.org/project/robosuite/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

150 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Our project (https://robosuite.ai/) is an open-source simulation framework that supports academic research on AI and Robotics. Our new release consists of new robot models that are essential for instantiating and running the simulations.

Adding these robot models exceeds the current package limit. We kindly ask to increase the current size limit to 150MB such that our users can install and run our framework with these robot models without the need of downloading them from a separate source. Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limits raised to 200 MB on PyPI and TestPyPI.
