### ISSUE TITLE
PEP 541 Request: data-pipeline-api

### ISSUE THREAD

**Issue by RyanJField** [pypa/pypi-support#1436]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/data-pipeline-api

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ryanjfield

### Reasons for the request

The original maintainer is no longer working on the project and is not reachable. The project has been stale for over a year but has been restarted with new project maintainers.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Original (now archived) repo: [data_pipeline_api](https://github.com/ScottishCovidResponse/data_pipeline_api)

Continued development of the project: [pyDataPipeline](https://github.com/FAIRDataPipeline/pyDataPipeline)

### Contact and additional research

Several emails have been sent to the original maintainer over the past months with no response. The new maintainers have access to the author email but this is no longer associated with the original maintainer. The new maintainers have access to both the original repository and the new repository on GitHub.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @RyanJField, I will now start the reachability process for your request. I believe the owner of the project is GitHub user @aflag, who I will attempt contact with also via email and allow replies for up to 6 weeks. Hopefully we will hear back soon and move forward with the transfer.

**Comment by RyanJField** [comment]
Hi @yeraydiazdiaz Thank you for processing the reachability request, I believe it has been 6 weeks could you please confirm the next steps.

Many Thanks.

Ryan

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
