### ISSUE TITLE
PEP 541 Request: pycord

### ISSUE THREAD

**Issue by BobDotCom** [pypa/pypi-support#1438]
### Project to be claimed

`Pycord`: https://pypi.org/project/pycord

### Your PyPI username

`BobDotCom`: https://pypi.org/user/BobDotCom

### Reasons for the request

*After reading through this, it seemed somewhat confusing, so here is a clarification. The project in dispute will be referred to as "The project", "Their project", "The package", "Their package", and "Current package." The project I own will be referred to as "Our project", "My project", "Our package", and "My package."*

The project in question is *not* abandoned as per PEP 451. While the last commit was [over a year ago](https://github.com/alesanfra/pycord/commits/master), I contacted the owner and they did respond. They declined my request to transfer the name via a GitHub Issue, alesanfra/pycord#2. The stated reason here was that the project was "still active" and that "any change to the name would break all projects which relies on it." Even though I proposed giving them the package name `py-cord` in exchange, they still declined.

![Screen Shot 2021-11-01 at 10 38 31 AM](https://user-images.githubusercontent.com/71356958/139699185-6dd33f41-3e08-4729-8a7d-dda4b898793f.png)

However, it can easily be seen in the download statistics that our users are very frequently confusing their package name with ours. Here is a visual of the download statistics of this package before and after ours was created. Averaging about 1 download per 3 days prior to creation of our project and clocking in yesterday at almost 1.3 thousand, it's clear there was a misunderstanding made by our users because of the confusing package naming.

![Screen Shot 2021-11-01 at 10 41 10 AM](https://user-images.githubusercontent.com/71356958/139699121-5b4e5f40-6aad-4717-92b3-d134273eb3fb.png)

Our project has not yet even been fully released to PyPi as it is a fork of [discord.py](https://pypi.org/project/discord.py), and we have not yet finished a new release. We uploaded a mirror of discord.py's latest version as a placeholder but are working on our alpha via GitHub. Alpha releases are downloaded through there, so our current 93k/month downloads are only a fraction of our actual downloads. 

![Screen Shot 2021-11-01 at 10 47 59 AM](https://user-images.githubusercontent.com/71356958/139700030-25485209-0035-427b-a851-e0f553b479fc.png)

As for the original owner's claims that "any change to the name would break all projects which relies on it," I reviewed the [listed dependents](https://github.com/alesanfra/pycord/network/dependents) on GitHub. From the code in each of these repositories it is clear that all of them depend on my project, not the current project. I could not find any evidence of any repositories that depend on the current project, across all of GitHub. However, I did come across [an archive](https://github.com/tzpBingo/github-trending) of the GitHub trending page. [This archive shows](https://github.com/tzpBingo/github-trending/search?q=pycord) that we have been listed on trending 5 times in the past two months, including today (Nov. 1st). 

![Screen Shot 2021-11-01 at 1 07 46 PM](https://user-images.githubusercontent.com/71356958/139719422-b1da7e3c-1850-4bd0-9da5-50cb6b5b30fb.png)

#### Miscellaneous 

 - The reason we named our project Pycord is simply because it's a catchy combination of the words **Py**thon and dis**cord**. As our project is an api wrapper for discord, it seemed a fitting name. It is in no way affiliated with the current package.
 - Our project, [Pycord](https://github.com/Pycord-Development/pycord/), is currently named [py-cord](https://pypi.org/project/py-cord) on PyPi.
 - Mentioning @alesanfra so they can comment if they want.
 - For what it's worth, the current project has just 57 lines of meaningful code, while my project has thousands.
 - I can also be reached via
     - [pycorddev@gmail.com](mailto:pycorddev@gmail.com?subject=Regarding%20PEP%20451%20Request)
     - `BobDotCom#4428` on discord
     - [Creating a new discussion on my GitHub](https://github.com/Pycord-Development/pycord/discussions/new)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: https://github.com/alesanfra/pycord

My project: https://github.com/Pycord-Development/pycord/

### Contact and additional research

This can be found in the "Reasons for the request" section. My contact with the current owner is documented at the beginning. Other research can be found in the rest of the content.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by vcokltfre** [comment]
> For what it's worth, the current project has just 57 lines of meaningful code, while my project has thousands.

I don't think package names on PyPI should be valued based on LOC, since that's a largely meaningless measurement of a project. Furthermore if the developer has already responded and denied to transfer the name to you, why is there an issue here requesting the name? The answer given by the developer was no, and that should be respected in my opinion, since nothing else such as trademark infringement is at play here.

**Comment by BobDotCom** [comment]
> > For what it's worth, the current project has just 57 lines of meaningful code, while my project has thousands.
> 
> I don't think package names on PyPI should be valued based on LOC, since that's a largely meaningless measurement of a project. Furthermore if the developer has already responded and denied to transfer the name to you, why is there an issue here requesting the name? The answer given by the developer was no, and that should be respected in my opinion, since nothing else such as trademark infringement is at play here.

The issue I saw was the download rate, which was next to 0 before our package existed. Since we've had many users come to our support server asking for help after doing `pip install pycord`, while we've been able to help the users that come to us, there are undoubtedly many more that haven't come to us after making this mistake and are simply stuck.

**Comment by yeraydiazdiaz** [comment]
Hello @BobDotCom, PEP 541 does not cover situations like you're describing, the project is not abandoned and the owner is reachable and explicitly declined the transfer. Unfortunately there's nothing we can do, as outlined in https://www.python.org/dev/peps/pep-0541/#name-conflict-resolution-for-active-projects we encourage communication between the owners to resolve this issue.
