### ISSUE TITLE
PEP 541 Request: django-freeipa-auth

### ISSUE THREAD

**Issue by kris-anderson** [pypa/pypi-support#1439]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/django-freeipa-auth

### Your PyPI username

`USER_NAME`: https://pypi.org/user/kris-anderson

### Reasons for the request

Jerry Aujla is the current Author of this package, and Richard and Tore are both maintainers. Jerry created and pushed this package to PyPi while employed by our company (Enervee), but he is no longer with us. Richard and Tore are both still with us, but only the author of the project can manager users. Richard and Tore are therefor the only two users in our org that can update this package, and I'd like more of our team to be involved in this project.

I have reached out to Jerry via his personal email address but have not heard back from him. 

We just moved this repo from our private Bitbucket repo to a public GitHub repo here:
https://github.com/enervee/django-freeipa-auth

We are still maintaining this repo and pushing updates to it, and I'd like our team at Enervee to be able to manage this existing project of ours through PyPi.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/enervee/django-freeipa-auth

Screenshots from our private Bitbucket (Stash) repo where we used to host this. It's now been moved to GitHub to we can fully open source this and make it public.
![image](https://user-images.githubusercontent.com/1562427/139727011-d67189fc-ff2c-46f7-b8f7-fdf153b05f08.png)

![image](https://user-images.githubusercontent.com/1562427/139727165-a6350f37-24d7-4aed-be6d-6be2fa82e99b.png)

### Contact and additional research

I did try to reach out to Jerry via his personal email address on October 22nd.

I tried resetting the PyPi password for jerry@enereve.com, but this project was created using Jerry's personal email account and not his Enervee account, and therefor I can't transfer this on my own.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @kris-anderson, I will start the reachability process for your request. Hopefully we will hear back soon and move forward with the request.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
