### ISSUE TITLE
Transfer : courseraprogramming to the user : eng-tech-content

### ISSUE THREAD

**Issue by sashi-coursera** [pypa/pypi-support#144]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/courseraprogramming/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/eng-tech-content/

**Reasons for the request**

Brennan Saeta (Original author who used to work at Coursera) is no longer at coursera. Since then the courseraprogramming has not been updated. We have some important updates to this project which we need to publish so the users get the latest. Pretty much existing version on pyp is not usable.

**Maintenance or replacement?**

Yes, our team intend to update and continue maintenance of this package.

**Contact and additional research**

We do not have the email address of the current owner.

**Comment by jamadden** [comment]
I suspect that the github user @saeta is the current owner of the PyPI project https://pypi.org/project/courseraprogramming/. That account appears to be active, hopefully it will see this ping and reply.

**Comment by sashi-coursera** [comment]
Thank you Jason. Is @saeta copied in this email?

**Comment by jamadden** [comment]
@saeta should receive a github notification based on their configuration. If we don't get a response in a few days, we have an unverified email in PyPI's records that I will attempt to contact. (I may need to be reminded.)

**Comment by sashi-coursera** [comment]
Sounds good. Thanks for the help.

Sashi.

**Comment by jamadden** [comment]
The next step was to escalate to email to attempt to contact @saeta. I've done so using the email address we have on file (which differs from the public email listed for the project). 

This is another contact attempt under PEP 541. Hopefully we'll hear back quickly so we don't have to wait for the (just under 5 weeks) waiting period to expire.

**Comment by sashi-coursera** [comment]
Hi, It has been quite some time now. Wondering if it is a good time to transfer? Appreciate help on this. Thanks.

**Comment by saeta** [comment]
Sorry, just seeing this now. (Note: I don't have the machine I originally used, and doubt I have the credentials.) That said, if there's anything I can do to help transfer, please do let me know! (This should definitely be transferred. :-) )

**Comment by Jens-G** [comment]
Congrats, you're only 4 weeks away from one full year of waiting time! </irony>

**Comment by ewdurbin** [comment]
Transfer complete.
