### ISSUE TITLE
PEP 541 Request: cloudpipe

### ISSUE THREAD

**Issue by eshza** [pypa/pypi-support#1440]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/cloudpipe

### Your PyPI username

`USER_NAME`: https://pypi.org/user/eshnasengupta

### Reasons for the request

The current cloudpipe project was created in September 2015. This project is no longer maintained and has no releases since 2015. My organisation has a project with this name that we wish to publish. We have reached out to the maintainer via email and he has agreed to transfer the name to us. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/rgbkrk/cloudpipe

### Contact and additional research

We have contacted the maintainer, Kyle Kelley, via email and he has agreed to transfer the name to us.  

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @eshza, the project's releases have no associated files so the project is actually invalid. I will attempt contact with the owner GitHub user @rgbkrk and allow one week for replies before proceeding with the transfer.

**Comment by rgbkrk** [comment]
All set, they can have the project.

**Comment by rgbkrk** [comment]
Original context on this project -- we thought we'd be moving `multyvac` into cloudpipe. The only lasting work to come out of cloudpipe (https://github.com/cloudpipe) was [cloudpickle](https://github.com/cloudpipe/cloudpickle)

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @rgbkrk, transfer complete.
