### ISSUE TITLE
PEP 541 Request: messari

### ISSUE THREAD

**Issue by KremerMichael** [pypa/pypi-support#1442]
### Project to be claimed

`messari`: https://pypi.org/project/messari

### Your PyPI username

`KremerMichael`: https://pypi.org/user/KremerMichael

### Reasons for the request

Hello, currently the messari project name is being used as an unofficial wrapper for our API. I'm reaching out from the Messari team to claim this name so we can publish our official Messari API under the name. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/messari/messari-python-api

### Contact and additional research

[email.pdf](https://github.com/pypa/pypi-support/files/7462998/email.pdf)

I've attached an email where we reached out to the current project owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @KremerMichael, I will now start the reachability process for your request. I believe the owner of the project is GitHub user @itzmestar. Hopefully we will hear back soon and move forward with the request.

**Comment by KremerMichael** [comment]
@yeraydiazdiaz thank you!!

**Comment by yeraydiazdiaz** [comment]
The owner replied stating they would like to retain ownership of the project.

**Comment by KremerMichael** [comment]
@yeraydiazdiaz , Bringing this back up. I am reaching out as an employee of Messari. This project is an unofficial wrapper around our API and an infringement on our trademark. We would like to take ownership of this project name so we can publish our official wrapper around our API within our own trademark.
