### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by entangly** [pypa/pypi-support#1445]
### PyPI Username

`entangly`

### Reason for request

Lost access to email address `connor@bradingsoftware.co.uk` 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
The primary email address associated with this account bounced, so we will proceed with another verification step.

**Comment by ewdurbin** [comment]
Please contact support@pypi.org including a link to this issue to proceed.

**Comment by ewdurbin** [comment]
Hi! If you would like to recover this account please open a new issue.
