### ISSUE TITLE
PEP 541 Request: mitm

### ISSUE THREAD

**Issue by synchronizing** [pypa/pypi-support#1446]
### Project to be claimed

`mitm`: https://pypi.org/project/mitm

### Your PyPI username

`synchronizing`: https://pypi.org/user/synchronizing

### Reasons for the request

User has claimed `mitm` and various other PyPi projects with nothing in them other than a `README` stating "Develop soon." User has also claimed:

* `adsl`
* `kwai`
* `ida`
* `cover`
* `trends`
* `netease`
* `beta`
* `enc`
* `am`
* `break`
* `admin`
* `kol`
* `leetcode`
* `xposed`
* `refer`
* `zan`
* `edu`
* `dell`
* `del`
* `night`
* `bcc`
* `nick`
* `adidas`
* `ticket`
* `come`
* `ol`
* `cert`
* `ali`
* `cia`
* `media`
* `alive`
* `gbg`
* `Tyche`
* `Bellona`
* `employ`
* `figlet`
* `ollybd`
* `nintendo`
* `waf`
* `mikufans`
* `ipool`
* `ins`
* `gayhub`

### Maintenance or replacement?

Replacement

### Source code repositories URLs

None. There are no projects posted on `mitm`. 

### Contact and additional research

I did not contact the owner of the repo. According to PEP541 "package name squatting is prohibited."

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by synchronizing** [comment]
Thank you!
