### ISSUE TITLE
PEP 541: transfer ownership of unmaintained 'hubspot' package

### ISSUE THREAD

**Issue by zman81988** [pypa/pypi-support#145]
**Project to be claimed**

`HubSpot`: https://pypi.org/project/hubspot

**Your PyPI username**

`zwolfson `: https://pypi.org/user/zwolfson

**Reasons for the request**

I believe this project has been abandoned for two reasons.  First is the last release was in June of 2014. The second is that the author of the project has been set to UNKNOWN. 

**Maintenance or replacement?**

We (HubSpot) intended to publish a different package under the name of this package. 

**Contact and additional research**

I have not been successful in finding contact information for the current owner. The two contributors listed on the package didn't have any contact information https://pypi.org/user/brad.decker/ and https://pypi.org/user/rkwas/  Google searching their usernames didn't yield anything helpful, unfortunately. 

Let me know if you need anything else from my end.

**Comment by jamadden** [comment]
PyPI has unverified email addresses on file for the two project maintainers. I've emailed them to attempt contact. I have been unable to discover any other means of contact.

I've confirmed that the PyPI account `zwolfson` has a verified `@hubspot.com` email address.

**Comment by zman81988** [comment]
Hi @jamadden I wanted to follow up and see if you had heard from the previous two contributors on this.  Is there a set time we are waiting to hear back from them?  No rush on my end, I just don't want to follow up in 30 days if we are waiting for 90 days or something like that.

**Comment by jamadden** [comment]
PEP 541 specifies a six-week timeout.

**Comment by zman81988** [comment]
Hi @jamadden Just wanted to follow up here since we are now well past the 6 week timeout period to see if this is something we can close out and transfer ownership of the Hubspot project?

**Comment by yeraydiazdiaz** [comment]
Temptatively tagging GitHub user @brad-decker who might be PyPI user [`brad.decker`](https://pypi.org/user/brad.decker/) as a second means of contact. Apologies if unrelated.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
