### ISSUE TITLE
PEP 541 Request: MinAtar

### ISSUE THREAD

**Issue by JesseFarebro** [pypa/pypi-support#1450]
### Project to be claimed

`MinAtar`: https://pypi.org/project/MinAtar

### Your PyPI username

`jessefarebro`: https://pypi.org/user/jessefarebro

### Reasons for the request

The project doesn't seem to exist and I'm unable to register the project. I get a 400 error saying the name minatar isn't allowed. It would be great to get more information on this and hopefully get the name transferred.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

[https://github.com/kenjyoung/MinAtar](https://github.com/kenjyoung/MinAtar)

### Contact and additional research

N/A. The package doesn't currently exist.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @JesseFarebro, this project was placed in the prohibited projects names list, @pypa/warehouse-admins could you release the project name please?

**Comment by ewdurbin** [comment]
`minatar` Project on pypi.org released to `jessefarebro` User.
