### ISSUE TITLE
PEP 541 Request: `grape`

### ISSUE THREAD

**Issue by ndem0** [pypa/pypi-support#1451]
### Project to be claimed

`grape`: https://pypi.org/project/grape

### Your PyPI username

martinateruzzi: https://pypi.org/user/martinateruzzi (or `ndem0`: https://pypi.org/user/ndemo)

### Reasons for the request

I reopen the issue #1125, since after the reply of the current maintainer @LucaCappelletti94 there are still no package at all on PyPi: there is no link at the Github repository (even searching it directly on Github I'm not able to find any `grape` package) and the release on PyPI is just empty directories with some init files. Description is just one-line sentence and no other resources are available, to the best of my knowledge.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/mathLab/GRAPE

### Contact and additional research

The maintainer replied 2 months ago in the other issue, but he has not any repository linked to the PyPI project. Release history lasts 5 days, no other activities.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ndem0** [comment]
@martinateruzzi

**Comment by ndem0** [comment]
I would make the links avaialble also from the PyPI portal (otherwise is almost impossible find the repo).

**Comment by yeraydiazdiaz** [comment]
Clsing as the owner has replied and intends to continue with development.
