### ISSUE TITLE
Account recovery request (conflict with testPyPi)

### ISSUE THREAD

**Issue by jochym** [pypa/pypi-support#1452]
### PyPI Username

jochym

### Reason for request

I lost 2FA authentication app functionality. 
I wanted to enable 2FA on testPyPi and the FreeOTP+ added a new account but also somehow reset parameters on other account (PyPi). Now both accounts show the same code and I cannot login to pypi any more. I do not know if this is an error in FreeOTP+ or in (test)PyPi handling of the 2FA. Unfortunately, I had no chance to generate recovery codes so my only hope is this procedure. I still can login to my testPyPi account but my PyPi shows "wrong OTP" message. 
I have access to all my (3) e-mails used on both accounts and I can still access testPyPi with 2FA. Also, my github account is fairly old, uses 2FA and you can easily see the connection between packages on my account and my repositories. 
I hope you can restore my access. 
Looking forward to hearing from you,
P. Jochym

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by jochym** [comment]
Done

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by jochym** [comment]
Thanks for your help @ewdurbin !
