### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jsbmg** [pypa/pypi-support#1455]
### PyPI Username

picardythird

### Reason for request

I have lost the email address and possibly also the 2FA app token, if I had that enabled. I tried reactivating the email address on my ProtonMail account (jsbmgcontact@protonmail.com), but am not receiving the password recovery email after several attempts. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by jsbmg** [comment]
It's possible, that after reactivating the ProtonMail account, that it took a certain amount of time before the account was able to receive emails again and I tried too soon. So if I could try again to receive the email it might work.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
OK, that email bounced. Please contact support@pypi.org including a link to this issue and we'll perform another method of verification.

**Comment by ewdurbin** [comment]
Confirmation complete. Primary email has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
