### ISSUE TITLE
Limit Request: pygame - 20 GB

### ISSUE THREAD

**Issue by illume** [pypa/pypi-support#1456]
### Project URL

https://pypi.org/project/pygame

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20 000MB

### Which indexes

PyPI

### Reasons for the request

pygame description in project URL: https://pypi.org/project/pygame

Ran out of space.

I expect the total size will increase in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by illume** [comment]
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Project size too large. Limit for project 'pygame' total size is 10 GB. See https://pypi.org/help/#project-size-limit
```

**Comment by pradyunsg** [comment]
Bumped the total project size limit to 20 GB. The individual releases are ~700 MB, and releases are somewhat infrequent.

Please be mindful of how often you make releases with the current limits, and consider trimming your development releases more frequently! :)

**Comment by illume** [comment]
> Bumped the total project size limit to 20 GB. The individual releases are ~700 MB, and releases are somewhat infrequent.

Thanks.

> Please be mindful of how often you make releases with the current limits, and consider trimming your development releases more frequently! :)

Respectfully, the package host should not dictate release processes of projects.
