### ISSUE TITLE
Limit Request: addrmatcher - 700MB

### ISSUE THREAD

**Issue by HninPwint** [pypa/pypi-support#1458]
### Project URL

https://pypi.org/project/addrmatcher/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

700MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Hi PyPi Support Team,

The reference dataset intended to integrate in our _addrmatcher_ package was 608MB.  The package sized 18KB without the reference data. So we would like to request to increase to 700MB to be able to integrate data in the package. 

Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! :)

Would it be feasible to do something similar to what [NLTK](https://www.nltk.org/data.html) or [scikit-image](https://gitlab.com/scikit-image/data) do, and host the dataset externally from the Python source code which is shipped as part of this package? If not, could you elaborate on why that wouldn't be technically feasible?

**Comment by pradyunsg** [comment]
Closing due to lack of response.
