### ISSUE TITLE
PEP 541 Request: isodate

### ISSUE THREAD

**Issue by hugovk** [pypa/pypi-support#1459]
### Project to be claimed

`isodate`: https://pypi.org/project/isodate

### Your PyPI username

`hugovk`: https://pypi.org/user/hugovk

### Reasons for the request

I believe the project has been abandoned.

The original package hasn't had a commit in three years and no release in four years.

* https://github.com/gweis/isodate (August 2018)
* https://pypi.org/project/isodate/#history (October 2017)

It is incompatible with the recent Python 3.10 release (October 2021), as reported in multiple issues:

* https://github.com/gweis/isodate/issues/58 (June 2019)
* https://github.com/gweis/isodate/issues/67 (April 2021)

And there are multiple unmerged PRs to fix it:

* https://github.com/gweis/isodate/pull/60 (July 2019)
* https://github.com/gweis/isodate/pull/68 (September 2021)

An issue asking if the project is still unmaintained or needs new maintainers hasn't been answered by the maintainers:

* https://github.com/gweis/isodate/issues/65 (March 2021)

I have created a fork at https://github.com/isodate/isodate/ and uploaded to PyPI temporarily as https://pypi.org/project/isodate2/. I've fixed it for Python 3.10, plus some other issues. I've modernised things: dropped EOL Python, added automated release notes and deploys, converted all the tests to pytest, formatted with Black and isort, added pre-commit and linters.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Original: https://github.com/gweis/isodate

Fork: https://github.com/isodate/isodate

### Contact and additional research

On 13th September, I commented on https://github.com/gweis/isodate/issues/65 asking for a new release and offering to help.

On 15th September, I emailed the maintainer's address listed at https://pypi.org/project/isodate/ but it bounced: "user unknown".

On 16th September, I found and emailed a potential, alternative address but got no reply.

On 25th October, I sent a follow-up, but no reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @hugovk, I've started the reachability process for your request. Hopefully we will hear back soon and proceed with the transfer.

**Comment by hugovk** [comment]
The good news is the original maintainer has returned and made a new release. 🚀

So the fork and this transfer request is no longer needed.

Thanks!
