### ISSUE TITLE
Reset of 2FA on my PyPi account

### ISSUE THREAD

**Issue by bpabel** [pypa/pypi-support#146]
username: bpabel
email: 007brendan@gmail.com
Request: Reset of 2FA on my PyPi.org account.
Reason: Reset phone

Thank you.

**Comment by bpabel** [comment]
@ewdurbin, I saw you were able to fix this on a few other tickets.  Thanks in advance!

**Comment by bpabel** [comment]
Hi @ewdurbin , just pinging again to see if this can be reset sooner than later. I just finished up a PEP 541 transfer and I'd like to make sure the project is updated and has new releases. Thanks!

**Comment by bpabel** [comment]
@yeraydiazdiaz @jamadden Do you know any other admins besides @ewdurbin ?

What's the plan for these 2FA reset tickets?  I see some that are still open after 2 months?

**Comment by ewdurbin** [comment]
Verified request, 2FA reset has been completed and a password reset issued.
