### ISSUE TITLE
PEP 541 Request: sqlfmt

### ISSUE THREAD

**Issue by tconbeer** [pypa/pypi-support#1460]
### Project to be claimed

`sqlfmt`: https://pypi.org/project/sqlfmt

### Your PyPI username

`tedconbeer`: https://pypi.org/user/tedconbeer

### Reasons for the request

This project is eligible for a name transfer, per PEP541, because it is an Invalid Project, due to Name Squatting:
1. sqlfmt version 0.0.0 was published in April 2020, with no updates since
2. sqlfmt version 0.0.0 is a completely empty package, with no functionality (or code) whatsoever

Furthermore, the existing sqlfmt project meets the criteria of an Abandoned Project:
1. The owner has not been reachable in spite of multiple emails to email address on PyPI (on Jul 20 and Jul 26, 2021)
2. There have been no releases in over 12 months (since April 2020)
3. The listed project homepage returns a 404 (Github repo doesn't exist or is private)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

On PyPI, https://github.com/HH-MWB/sqlfmt is listed as the project homepage, but I get a 404 trying to access that page today (404 since at least July 2021)
![image](https://user-images.githubusercontent.com/705906/140807965-8ebabeb0-a599-4ac5-a4f8-1fe03da39a22.png)

### Contact and additional research

Unreturned emails from July, 2021:
![image](https://user-images.githubusercontent.com/705906/140808102-9c2776aa-1764-43bf-9f37-71e919df7856.png)

Empty source tree from PyPI (sqlfmt v 0.0.0) attached
[sqlfmt-0.0.0.tar.gz](https://github.com/pypa/pypi-support/files/7499704/sqlfmt-0.0.0.tar.gz)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @tconbeer, `sqlfmt` has seen [two recent releases](https://pypi.org/project/sqlfmt/#history), while it does seem the code has limited functionality I don't think this warrants a PEP 541 request as it's clear the project is still in development.
