### ISSUE TITLE
PEP 541 Request: jpt

### ISSUE THREAD

**Issue by kjozsa** [pypa/pypi-support#1462]
### Project to be claimed

`jpt`: https://pypi.org/project/jpt

### Your PyPI username

`kjozsa`: https://pypi.org/user/kjozsa

### Reasons for the request

https://pypi.org/project/jpt/ currently stands for Jake’s Python Tools and looks like a personal project. It was last updated in 2015, lacks a license and an author link, and there looks to be no way to find out and contact the original owner of this project.

I'd like to take over the name of this abandoned project to let PyPI host my new CLI tool project, named JPT (as JsonPath Tools - https://github.com/kjozsa/jpt). Please kindly review my request and approve it if possible.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/kjozsa/jpt

### Contact and additional research

The Homepage link is broken. The username "jakeyjdavis" can not be found on github, nor on google (I only found a Spotify user by this name). I see no way of finding out who the original author was or how to get to him.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @kjozsa, I have started the reachability process for your request, hopefully we will hear back from the owner and proceed with the transfer soon.

**Comment by yeraydiazdiaz** [comment]
The owner accepted the request, transfer complete.
