### ISSUE TITLE
PEP 541 Request: `tests` (blocklist candidate)

### ISSUE THREAD

**Issue by webknjaz** [pypa/pypi-support#1464]
### Project to be claimed

`tests`: https://pypi.org/project/tests

### Your PyPI username

`webknjaz`: https://pypi.org/user/webknjaz (not really applicable here)

### Reasons for the request

Somebody mentioned that this project exists during PackagingCon yesterday (I think it was @hroncok or @encukou) and I thought that this may be harmful to the users typing in `pip install tests` (for whatever reason).

I've downloaded the published zip file (yes! it's a `.zip` archive, not a tarball, not a wheel, not an egg, uploaded like 5 years ago). The contents don't seem to be particularly useful:
```console
$ unzip tests-0.007.zip
Archive:  tests-0.007.zip
  inflating: tests-0.007/PKG-INFO    
  inflating: tests-0.007/setup.py    
  inflating: tests-0.007/docs/lol.txt  
  inflating: tests-0.007/tests/myapp.py  

$ for f in $(find tests-0.007); do echo Contents of "$f":; cat "$f"; done
Contents of tests-0.007:
cat: tests-0.007: Is a directory
Contents of tests-0.007/PKG-INFO:
Metadata-Version: 1.0
Name: tests
Version: 0.007
Summary: UNKNOWN
Home-page: http://www.propython.com/
Author: Alchin and Browning
Author-email: authors@propython.com
License: UNKNOWN
Description: UNKNOWN
Platform: UNKNOWN
Contents of tests-0.007/setup.py:
from distutils.core import setup
setup(name='tests',
version='0.007',
author='Alchin and Browning',
author_email='authors@propython.com',
url='http://www.propython.com/',
packages = ['tests']
)
Contents of tests-0.007/docs:
cat: tests-0.007/docs: Is a directory
Contents of tests-0.007/docs/lol.txt:
Contents of tests-0.007/tests:
cat: tests-0.007/tests: Is a directory
Contents of tests-0.007/tests/myapp.py:
# MyApp.py
print("Hello Burton and Marty!")
gone=input("Enter to close: ")
```

It's notable that the linked website propython.com is squatted and is directly linked from PyPI.

### Source code repositories URLs

There are zero pointers to what the source may be.

### Contact and additional research

I haven't attempted contacting the person because I believe that the action that needs to be taken is adding this name to the blocklist.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I agree this project should be be place in the prohibited project names list, however only @pypa/warehouse-admins can add project to it.

**Comment by ewdurbin** [comment]
I agree, as it's currently in an invalid state. Added to prohibited project name list.
