### ISSUE TITLE
Project Limit Request: jiminy-py - 40 GB

### ISSUE THREAD

**Issue by duburcqa** [pypa/pypi-support#1465]
### Project URL

https://pypi.org/project/jiminy-py/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

40000MB

### Which indexes

PyPI

### Reasons for the request

jiminy-py core and its dependencies are implemented in C++, for which python bindings are provided. 18 wheels must be uploaded on Pypi for each release because Linux, Windows, and Mac platforms are supported for Python 3.6, 3.7, 3.8 and 3.9. As a result, the total size of each release is around 800Mb. About one or two versions is released every month. It would be beneficial to this project to be allowed to store the last releases over the last two years on pypi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
12 * 2 * 800 MB = 19.2 GB

I guess this limit request is assuming two releases a month and/or larger individual release sizes. Overall though, this seems like a reasonable request, but I'd like another moderator to chip in before increasing this limit. :)

**Comment by duburcqa** [comment]
Yes you are right! And in the meantime, I also managed to reduce the total size of z release to about 500go using shared libraries instead of linking statically for some dependencies. I'm already at the limit of the 10go quota, so I think 30go instead of 40go should be more than enough for the next 2 years!

**Comment by duburcqa** [comment]
@pradyunsg Any update ? Sorry to bother you :persevere:

**Comment by pradyunsg** [comment]
> I'd like another moderator to chip in before increasing this limit. :)

I'm basically waiting on this.

**Comment by pradyunsg** [comment]
I've bumped the limit to the requested 40 GB. You should consider reducing the project's release cadence, to avoid hitting this new limit soon. If you request another limit increase, please make sure to reference this issue in that request!

I see that there's a few periods where the release cadence is closer to weekly rather than the monthly that you've noted in the issue.
