### ISSUE TITLE
File Limit Request: cloudViewer - 320 MB

### ISSUE THREAD

**Issue by Asher-1** [pypa/pypi-support#1466]
### Project URL

https://pypi.org/project/cloudViewer

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

320 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

I can't upload my project's release to PyPI because I am hitting the upload file size limit and the project total size
limit. I expect my release sizes/total project size to increase in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! Thanks for your patience here!

Could you clarify the following:

- What the project is and how long it has been active.
- If you expect your release sizes/total project size to increase in the future.
- If you have made efforts to reduce the size of your PyPI releases.
- If you bundle other packages in your project.
- If you bundle example data in your project.
- How frequently do you make a release?

If there's no response in the next 4 weeks, I'll close this when I come back around. You can file a new ticket (which will need to include this information).

**Comment by pradyunsg** [comment]
Closing this due to lack of a response.
