### ISSUE TITLE
Project Limit Request: cloudViewer - 20 GB

### ISSUE THREAD

**Issue by Asher-1** [pypa/pypi-support#1467]
### Project URL

https://pypi.org/project/cloudViewer

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20000 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

cloudViewer and its dependencies are implemented in C++, for which python bindings are provided. 6 wheels must be uploaded on Pypi for each release because Linux and Windows platforms are supported for Python 3.6, 3.7 and 3.8. As a result, the total size of each release is around 2000MB. About one or two versions is released every month. It would be beneficial to this project to be allowed to store the last releases over the last two years on pypi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
The project is at 434.1 MiB in size, so a bump up to 20 GB does not seem necessary. This is the same project as https://github.com/pypa/pypi-support/issues/1466.

I'll close this one for now, since the upload was likely not blocked due to the project size limit.
