### ISSUE TITLE
ntlk -- typosquat was removed

### ISSUE THREAD

**Issue by tweedge** [pypa/pypi-support#1468]
### Project to be claimed

`ntlk`: https://pypi.org/project/ntlk

### Your PyPI username

`tweedge`: https://pypi.org/user/tweedge

### Reasons for the request

Hi there. Might be a fun case for you today, might not.

For several months, I held the package name `ntlk`. This is because the package `nltk` is remarkably easy to typo. My package would report the installation attempt, and then throw this error message:

> You probably meant to install NLTK (the Natural Language Toolkit).
> You have attempted to install NTLK instead. This is an empty package
> to help prevent typosquatting. To install NLTK, try this instead:
> pip install nltk
> 
> Stay safe,
> tweedge <3

I see now that my package has been deleted from PyPI, and when attempting to upload a new version, it's being blocked with:

> HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
> The name 'ntlk' isn't allowed. See https://pypi.org/help/#project-name for more information.

Which resolves this vulnerability. However if it's possible, I'd appreciate being able to continue using this package, as I was working on research to identify more opportunities for preventative typosquatting, including trying to figure out if there could be regional biases towards or against specific typos (such as keyboard layout, language, etc.).

I see that similar typosquatting packages are allowed as well, such as Python Lulz Authority's package here: https://pypi.org/project/requirements-dev.txt/

I don't believe any of this violates the PSF Code of Conduct but please let me know if I've made any infraction - I would be happy to correct it. If reinstating ntlk is not possible, I would further like to inquire if new packages could be made to continue this research, or how I could surface the most potent typosquatting opportunities to PSF so these can be blocked in advance, if that's of interest?

Looking forward to your thoughts. Thanks!

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

[https://github.com/tweedge/ntlk](https://github.com/tweedge/ntlk)

### Contact and additional research

N/A, I am original owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi! As a general note (from someone who's not a PyPI admin) -- it's a good idea to reach out to admin@pypi.org to let them know about potential typosquats, so that they can be blocked.

**Comment by tweedge** [comment]
Neat! I'll keep that in mind, thank you for the information Pradyun! Original question on getting ntlk reinstated remains though for whenever an admin is around :grin:

**Comment by di** [comment]
Our policy is to permanently remove namesquats/typosquats from the index, to reduce user confusion and potential for compromise.
