### ISSUE TITLE
Asking for package name consistency on Pypi and test-Pypi

### ISSUE THREAD

**Issue by Didou09** [pypa/pypi-support#147]
**Project to be claimed**

`tofu`: https://pypi.org/project/tofu/

**Your PyPI username**

`Didou09`: https://pypi.org/user/Didou09

**Reasons for the request**

We already claimed the package name tofu, via private email with a previous owner, it went fine.
Now we would like to use the same name 'tofu' on test-pypi, but it does not seem to work.

We suspect that someone else is already using that name on test-pypi.
But the original owner of tofu on Pypi told us that it was not him.

Any chance to check whether someone else is using it (or has been using it) on test-pypi ?
We would very much like to preserve the same name on Pypi and test-Pypi, as we wanty to include deployment on test-Pypi as a part of our CI workflow via Travis, for regular checks before official releases.

**Maintenance or replacement?**

If transfer is successfull, we want to use the name for our own project, consistently with the name on Pypi.

**Contact and additional research**

The original owner of the name tofu on Pipy has been contacted, and he kindly agreed to transfer the name to us some years ago, but he is apparently not the owner of that name on test-Pypi.

We are @lasofivec and @didou09

**Comment by jamadden** [comment]
The project `tofu` on test-PyPI was created and then immediately deleted about a year ago. Thus it appears to be an empty, invalid procjet that's name squatting at this point.

The owner in test-pypi appears to be @shalomb and the repository appears to be https://github.com/shalomb/tofu. I can ask an admin to remove the project from test-pypi, but hopefully @shalomb is the correct owner, gets this notification, and responds here.

**Comment by shalomb** [comment]
Hi @jamadden, @Didou09 , @lasofivec - I've deleted `tofu` on test.pypi.org - you may now claim it.
