### ISSUE TITLE
[test.pypi.org] Account recovery request

### ISSUE THREAD

**Issue by abhinavsingh** [pypa/pypi-support#1472]
### PyPI Username

abhinavsingh

### Reason for request

Lost 2FA authentication app and never generated recovery codes for `test.pypi.org` account :(

I need to recover my test account because we are setting up release automation for https://github.com/abhinavsingh/proxy.py , as part of which we must first release to test pypi before pushing to production.  Thank you!!!

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA has been reset for the `abhinavsingh` User on test.pypi.org

**Comment by abhinavsingh** [comment]
@ewdurbin Thanks a ton 🙏
