### ISSUE TITLE
Limit Request: mindspore-ascend-dev, mindspore-cuda11-dev - 200 MB

### ISSUE THREAD

**Issue by nicholasyanghaoran** [pypa/pypi-support#1474]
### Project URL

https://pypi.org/project/mindspore-cuda11-dev/ https://pypi.org/project/mindspore-ascend-dev/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

200 MB

### Which indexes

PyPI

### Reasons for the request

MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios. MindSpore is providing a preview build for users willing to try latest features and receive latest bugfixes.

MindSpore would be publishing preview versions for multiple hardware backends weekly, among which, `mindspore-cuda11-dev` (160MB per package) and `mindspore-ascend-dev` (110MB per package) are exceeding the default package size limit of 100MB, and may continue to grow as more features are being added.

Could you please help increase the size limit of these projects to 200MB? Thank you very much!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nicholasyanghaoran** [comment]
@ewdurbin @pradyunsg I'm very sorry for interrupting, but could you please help look into this issue? We are trying to provide our latest builds to the community by the most efficient means, which we believe is through PyPI. We will be uploading packages weekly and frequently trimming the outdated ones, and will not be occupying too much storage space overall. Thanks for considering my request.

**Comment by pradyunsg** [comment]
I've gone ahead and increase the limit for both projects to 200 MB. If you make a request for either project in the future, please include a reference to this ticket when you do so.

**Comment by nicholasyanghaoran** [comment]
Thank you very much for your response! We will try our best controlling the pacakge sizes as small as possible :)
