### ISSUE TITLE
PEP 541 Request: PyMAL

### ISSUE THREAD

**Issue by Scrumpyy** [pypa/pypi-support#1475]
### Project to be claimed

`pymal`: https://pypi.org/project/pymal/

### Your PyPI username

`ScrumpyGG`: https://pypi.org/user/ScrumpyGG

### Reasons for the request

The repository it links to has been deleted and it appears to have not been updated since 2014.
I wish to take on this project and develop a Python MyAnimeList API wrapper (what the currently existing project promises to deliver but fails to provide).

### Contact and additional research

Original repository (deleted & moved): https://bitbucket.org/pymal-developers/pymal/
Moved to: https://github.com/pymal-developers/pymal 

'New' repository hasn't been updated in 7 years and is no longer functional with the current MyAnimeList API.
Both contributors to the 'new' repository have near-zero (if any) activity on Github.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by JustGamma** [comment]
+1

**Comment by DavidSenpai** [comment]
+1

**Comment by conqr2** [comment]
+1

**Comment by yeraydiazdiaz** [comment]
Hello @Scrumpyy, you have not specified if you intend to replace the current project or maintain it, would you mind providing that information?

Tagging GitHub user @tomerghelber whose username matches the owner of the PyPI project.

**Comment by Scrumpyy** [comment]
> Hello @Scrumpyy, you have not specified if you intend to replace the current project or maintain it, would you mind providing that information?
> 
> 
> 
> Tagging GitHub user @tomerghelber whose username matches the owner of the PyPI project.

Heya, I intend to replace the current project. The current one is completely inactive and doesn't function as intended.

**Comment by tomerghelber** [comment]
Hey,
The old repo sits [here](https://github.com/pymal-developers/pymal/).

It really wasn't updated because we understood the scrapping way might be bad for the MAL and it had a new API.

I support giving the project to someone else. and wish you all the luck.
If you need some other help I will be happy to help.

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @tomerghelber, transfer complete.
