### ISSUE TITLE
PEP 541 Request: magicpy

### ISSUE THREAD

**Issue by 0nu** [pypa/pypi-support#1479]
### Project to be claimed

`magicpy`: https://pypi.org/project/magicpy/

### Your PyPI username

`num_ole`: https://pypi.org/user/num_ole

### Reasons for the request

The only release is from 2014, with no project description and the homepage link http://sprymix.com/ forwards to a different webpage (http://magic.io/, © 2016). I don't see any available code.
The maintainer, https://pypi.org/user/Elvis.Pranskevichus/ , seems to be still active on pypi for different projects.

I think this project just squats on the (amazing) name. 

I need this name for a scientific toolbox to control certain brain stimulation hardware. It based on an existing matlab toolbox, which is call [MAGIC](https://github.com/nigelrogasch/MAGIC), therefore making MAGICpy a reasonable choice.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://gitlab.gwdg.de/tms-localization/utils/magicpy

### Contact and additional research

I wrote an email to hello@magic.io and didn't get an answer. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @0nu, I can confirm the project has a single release with no associated files and is therefore considered invalid.

Its owners are GitHub users @elprans and @1st1, both of which seem quite active, hopefully they can clarify the situation for this project.

**Comment by elprans** [comment]
@yeraydiazdiaz, no problem, @0nu can claim the name.  We had plans to release a tool under that name, but those had since been abandoned.  I must have overlooked @0nu's email about it.

**Comment by elprans** [comment]
I deleted the `magicpy` project from PyPI just now.

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @elprans.
