### ISSUE TITLE
Reset of 2FA on my PyPi account

### ISSUE THREAD

**Issue by radomsak** [pypa/pypi-support#148]
Hello,

My phone was stolen and I lost the ability to log in to pypi with 2FA.

username: radomsak
email: adamradomski4@gmail.com

Request: Reset of 2FA on my PyPi.org account.
Reason: Stolen phone.

Thank you.

**Comment by ewdurbin** [comment]
Hello @radomsak, please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
