### ISSUE TITLE
Limit Request: ctranslate2 - 20 GB

### ISSUE THREAD

**Issue by guillaumekln** [pypa/pypi-support#1480]
### Project URL

https://pypi.org/project/ctranslate2/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

20000 MB

### Which indexes

PyPI

### Reasons for the request

[CTranslate2](https://github.com/OpenNMT/CTranslate2) is a C++ inference engine for neural machine translation models. We publish wheels for all supported Python versions on Linux, macOS, and Windows. The library supports execution on GPU and includes compiled CUDA kernels for multiple architectures.

The project is close to the 10GB limit and we'd like to double this limit to 20GB.

The current size of a release is 430MB, but we recently re-worked how we link against a dependency and the future release size should be about 160MB. With a rate of 2 releases per month, the additional 10GB would last more than 30 months. After that, we first plan to delete old versions that are no longer relevant.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by guillaumekln** [comment]
I updated the description to include the current release size, the future release size (following a recent improvement), and our deletion policy when/if the project reaches the 20GB limit.

**Comment by guillaumekln** [comment]
Recent releases have a total size of 170MB, down from 430MB.

In the meantime, we had to move some wheels to a S3 bucket to make room for recent releases. Bumping the total project size to 20GB would allow us to keep a larger release history on PyPI.

Thanks!

**Comment by pradyunsg** [comment]
Increased the limit to 20 GB. :)

**Comment by guillaumekln** [comment]
Thanks!
