### ISSUE TITLE
PEP 541 Request: OpenEXR

### ISSUE THREAD

**Issue by sanguinariojoe** [pypa/pypi-support#1486]
### Project to be claimed

`OpenEXR`: https://pypi.org/project/OpenEXR

### Your PyPI username

`sanguinariojoe`: https://pypi.org/user/sanguinariojoe

### Reasons for the request

The last release was uploaded in 2018. In its current state the project fails to compile (for several reasons), which can be fixed with the following patch:

```
diff -r OpenEXR-1.3.2/OpenEXR.cpp OpenEXR-1.3.3/OpenEXR.cpp
35a36
> #include <ImathConfig.h>
49a51
> #include <ImfFrameBuffer.h>
75a78,87
> #include <fstream>
> 
> #define IMATH_VERSION IMATH_VERSION_MAJOR * 10000 + \
>                       IMATH_VERSION_MINOR * 100 + \
>                       IMATH_VERSION_PATCH
> 
> #if IMATH_VERSION >= 30001
> #define Int64 uint64_t
> #define SInt64 int64_t
> #endif
diff -r OpenEXR-1.3.2/setup.py OpenEXR-1.3.3/setup.py
20c20,21
<               include_dirs=['/usr/include/OpenEXR', '/usr/local/include/OpenEXR', '/opt/local/include/OpenEXR'],
---
>               include_dirs=['/usr/include/OpenEXR', '/usr/local/include/OpenEXR', '/opt/local/include/OpenEXR',
>                             '/usr/include/Imath', '/usr/local/include/Imath', '/opt/local/include/Imath'],
22c23
<               libraries=['Iex', 'Half', 'Imath', 'IlmImf', 'z'],
---
>               libraries=['Iex', 'Imath', 'OpenEXR', 'z'],
```

I already wrote to James Bowman with no reply at all. There is not an associated repository to open an issue.

### Maintenance or replacement?

Maintenance

### Contact and additional research

I mailed the following to James Bowman:

> Hey James!
> 
> I tried to install your OpenEXR pip package in Manjaro, with IMath 3.1.3 and OpenEXR 3.1.1, and it failed.
> 
> Enclosed you can find a patch to fix it.  Please, let me know.
> 
> Best,
> Jose Luis Cercos Pita

I double checked the patch was enclosed. Unfortunately, I have not got reply, and no further action has been taken on the package.

As far as I know, there is not an associated repo, or any other way to contact him.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @sanguinariojoe, I will start the reachability process for your request. I believe GitHub user @jamesbowman is the owner of the project but I will also attempt contact via email. Hopefully we will hear back soon and proceed with the transfer.

**Comment by sanguinariojoe** [comment]
Sure! Thank you!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
