### ISSUE TITLE
Limit Request: stable-retro - 200 MB

### ISSUE THREAD

**Issue by MatPoliquin** [pypa/pypi-support#1488]
### Project URL

https://github.com/MatPoliquin/stable-retro

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

200MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

stable-retro supports AI researchers for training models on retro games. There is many state files needed for each game (but not the game rom itself of course)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
https://pypi.org/project/stable-retro/ does not exist.

**Comment by pradyunsg** [comment]
Closing due to a lack of a response to the comment above, that project doesn't seem to exist on PyPI.
