### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pbelskiy** [pypa/pypi-support#1496]
### PyPI Username

pbelskiy

### Reason for request

I've changed my mobile device, and I lost PyPI 2FA keys

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by pbelskiy** [comment]
Here is the proof that's is my account by listening my GitHub projects and PyPI packages of them.
I hope you just disable 2FA and I will reconfigure it again with recovery keys :-)

https://github.com/pbelskiy/ujenkins - https://pypi.org/project/ujenkins/
https://github.com/pbelskiy/quickbuild - https://pypi.org/project/quickbuild/
https://github.com/pbelskiy/helix-swarm - https://pypi.org/project/helix-swarm/
https://github.com/pbelskiy/aiojenkins - https://pypi.org/project/aiojenkins/

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
