### ISSUE TITLE
Limit Request: ViNeSeg - 200 MB

### ISSUE THREAD

**Issue by ISyN-Mainz** [pypa/pypi-support#1498]
### Project URL

https://pypi.org/project/ViNeSeg/

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

200

### Which indexes

PyPI

### Reasons for the request

Hey,

we want to upload a project for automatic segmentation of neurons in neurobiology experiments.
The weights of the model we trained are about 110 MB currently - we would like to distribute the model with our adapted labelme code so that the user can directly use the model for his/her own data.

So a little increase in the file size would be great and make everything easier to use!

Best,
Nicolas

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limit increase to 200 MB. :)
