### ISSUE TITLE
Transfer ownership of Click on Test PyPI

### ISSUE THREAD

**Issue by davidism** [pypa/pypi-support#150]
Follow up to #108 for Click.

I'm a core maintainer of Click. I would like to use **Test PyPI** to test out some packaging issues I'm working on, but it is currently taken with a placeholder by @encukou. Please transfer ownership of this project to me. Thank you.

`PROJECT_NAME`: https://test.pypi.org/project/click
`USER_NAME`: https://test.pypi.org/user/davidism

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by davidism** [comment]
Thanks for your help once again! :-)
