### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SeanMooney** [pypa/pypi-support#1500]
### PyPI Username

sean-k-mooney

### Reason for request

hello
i moved company from intel to redhat a little over 3 years ago but as part of that process i neglected to update my pypi email form
sean.k.mooney@intel.com to sean@seanmooney.info(main email) or seanmooney8202@yahoo.ie (old  personal email i used at the time i created the pypi account)
since that time my password has been leaked and is no in your database of insecure passwords

"""This password appears in a security breach or has been compromised and cannot be used. See this FAQ entry for more information."""

As my registered email is still sean.k.mooney@intel.com  i have not been able to use the forgot passward link to reset my password.

https://opendev.org/x/stackalytics/src/branch/master/etc/default_data.json#L29587-L29606

in prefercial order can the recovery email addess be updated to sean@seanmooney.info (personal email), work@seanmooney.info (alias of personal email) or smooney@redhat.com (actual work email)

sean@seanmooney.info is my primary github email too and is the one i am moving most things too over time.

regards
sean.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by SeanMooney** [comment]
thanks for the response i have have just sent an email with subject "[Account Recovery][issue:1500] recoveray of sean-k-mooney pypi accont" which appently i typod hehe to support@pypi.org

**Comment by SeanMooney** [comment]
@ewdurbin hi I would guess that many people will be away on PTO over the next few weeks.
ill try and keep an eye out for a response from support@pypi.org but I likely will be delayed in responding if
I do not receive a response to my original email by the end of the week.

please let me know if I need to do anything else, if not ill wait for the reply from support@pypi.org

**Comment by ewdurbin** [comment]
Recovery complete.

**Comment by SeanMooney** [comment]
thank you i have reset my password to a strong generated one and verified my email
