### ISSUE TITLE
File Limit Request: emc2 - 250 MB

### ISSUE THREAD

**Issue by rcjackson** [pypa/pypi-support#1501]
### Project URL

https://pypi.org/project/emc2

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

per release file

### New limit

250

### Which indexes

PyPI

### Reasons for the request

We need to expand the storage limit to 250 MB since we have to store lookup tables that are needed for EMC^2's calculations. These lookup tables take up dozens of megabytes. We may need to add more lookup tables in the future which may involve another size increase.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rcjackson** [comment]
Hello, what is the status of this request?

**Comment by pradyunsg** [comment]
I'm slowly catching up on the backlog of tickets. :)

Bumped individual file size limit to 250.0 MiB.
