### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dheww5** [pypa/pypi-support#1502]
### PyPI Username

dheww5

### Reason for request

I wrote the wrong email adress when creating the account at https://test.pypi.org/. I then added the correct email and when attempting to delete the wrong email it instead deleted the correct email. I couldn't re-add the correct email. So I deleted the account in hope to create a new one with the correct email but I recieve,:

429 Too Many Requests
The action could not be performed because there were too many requests by the client.

Too many emails have been added to this account without verifying them. Check your inbox and follow the verification links. (IP: 138.106.57.132)

So could you please help with this.
Best Regards
David Hemlin
david.hemlin@scania.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
@dheww5 the rate limiter should have reset by now. If you are still unable to register please reopen this issue.
