### ISSUE TITLE
PEP 541 Request: mclauncher

### ISSUE THREAD

**Issue by BobDotCom** [pypa/pypi-support#1503]
### Project to be claimed

`mclauncher`: https://pypi.org/project/mclauncher

### Your PyPI username

`BobDotCom`: https://pypi.org/user/BobDotCom

### Reasons for the request

Not particularly a PEP 541 request, but I was unable to upload under this package name and was wondering if it was possibly banned/blacklisted somehow? And if so, am I able to claim it at all? I have a project called [mclauncher](https://github.com/BobDotCom/mclauncher) and I'd like to upload it to pip. I'm going to upload it under a different name for now but it would be much appreciated if I could use the package name. 
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'mclauncher' isn't allowed. See https://pypi.org/help/#project-name for more information.
```
(FYI: If anyone is questioning whether my package is a "cracked" launcher for minecraft, it's not. It requires authentication with a microsoft account and uses the access token to get a session token from mojang. More information on the repo.)

### Source code repositories URLs

n/a

### Contact and additional research

n/a

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @BobDotCom, the project has been placed in the prohibited project names list. @pypa/warehouse-admins could you release the project, please?

**Comment by ewdurbin** [comment]
Project `mclauncher` released to User `BobDotCom`
