### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dave-doty** [pypa/pypi-support#1505]
### PyPI Username

pexatus

### Reason for request

reason: Lost 2FA authentication app or security token

I did not lose access to my account's email, but I simply don't see an option to do the two-factor authentication using my account's email. If there's a way to log in using my email for two-factor authentication, please let me know how to do that. 

I traded in my phone, and I didn't remember to transfer the Google Authenticator information from the old phone to the new phone. I have the Google Authenticator app on my new phone, but it doesn't appear to be associated with my PyPI account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
