### ISSUE TITLE
PEP 541 Request: hume

### ISSUE THREAD

**Issue by gregorybchris** [pypa/pypi-support#1506]
### Project to be claimed

`hume`: https://pypi.org/project/hume

### Your PyPI username

`gregorybchris`: https://pypi.org/user/gregorybchris

### Reasons for the request

- The current hume package has not been released since 2019
- All existing releases are tagged `PRE-RELEASE` and happened over just two days
- The original repository has been deleted from GitHub (https://github.com/SHxKM/hume)
- The project owner has not responded to any emails

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The [new source](https://github.com/HumeAI/hume) is not public yet, but the Hume website (https://hume.ai/) should fulfill the PEP 541 notability requirements.

### Contact and additional research

<img width="757" alt="Hume Attempt 1" src="https://user-images.githubusercontent.com/8800689/144506464-9d7c045d-9d66-426d-935f-736f3c8610ad.png">

<img width="753" alt="Hume Attempt 2" src="https://user-images.githubusercontent.com/8800689/144506468-6c5e2c90-5dfd-44c9-849a-3e81e9a31ad2.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @gregorybchris, I will now start the reachability process for your request. Tagging GitHub user @SHxKM and will attempt contact via email as well. Hopefully we will hear back soon and proceed with the transfer.

**Comment by SHxKM** [comment]
Hi @yeraydiazdiaz @gregorybchris - thanks for getting in touch.

For some reason @gregorybchris' emails have arrived in my spam folder so I was never aware of the contact-attempt. This is an excellent workflow to notify the "owner" of a library in another method before forcibly transferring ownership.

In fact, even though the original idea for `hume` was shelved (hence the deleted repository), I've been working on and off on a repurpose, and I would like **to keep** the ownership of this package name. However, I understand that simply "parking" a package name forever can be kinda sucks (even though totally within my rights) - so @gregorybchris let's agree that if I don't publish anything under `hume` within 9 months, you'll get in touch again and we'll do the transfer.

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @SHxKM, I will close this transfer for now. If you decide to transfer the project later on you can do so yourself in the [collaborators section of the project management panel](https://pypi.org/manage/project/hume/collaboration/).

**Comment by gregorybchris** [comment]
Thanks for your understanding @SHxKM! Your proposal is very reasonable. Please feel free to email me in the meantime if you happen to change your mind!
