### ISSUE TITLE
Limit Request: scikit-image - 25 GB

### ISSUE THREAD

**Issue by grlee77** [pypa/pypi-support#1509]
### Project URL

https://github.com/scikit-image/scikit-image

### Does this project already exist?

- [X] Yes

### Which limit do you want increased?

total project size

### New limit

25000 MB

### Which indexes

PyPI

### Reasons for the request

scikit-image is a popular library for image processing that has been releasing on PyPI for several years now.

We recently exceeded the 10 GB limit and were unable to upload our 0.19.0 release. By removing all but the most recent release candidate we were able to make space this time around, but we are still very near the limit (currently at 9.5 GB).

We typically release 1-2 major releases and a handful of point releases per year. It took ~5 years of releases to reach the 10 GB limit. We are currently around 1GB per release (30-60 MB / wheel and ~20 wheels across platforms), so could easily grow by 5 GB / year going forward.

I have requested an increase in total space to at least 25 GB which should be sufficient for the next few years. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by grlee77** [comment]
I should mention that we do try to be mindful of resource usage and have taken steps such as hosting example data in an external repository where it can be downloaded on-demand at run time. This has helped avoid having to increase the wheel size as our example datasets have grown.

**Comment by pradyunsg** [comment]
Hi there! 👋🏽 

I've gone ahead and bumped the limit to 25 GB, since this is a well-established project and this limit should last for a few years.

Please be mindful of how frequently you make releases at the current size of your releases. I'll also encourage you to investigate how the size of individual wheels can be reduced, especially if there's compiled artifacts in them that aren't being used upon installation (wheels are only supposed to hold files that need to be installed).

**Comment by grlee77** [comment]
> I've gone ahead and bumped the limit to 25 GB, since this is a well-established project and this limit should last for a few years.

Fantastic, thanks @pradyunsg

> Please be mindful of how frequently you make releases at the current size of your releases. I'll also encourage you to investigate how the size of individual wheels can be reduced, especially if there's compiled artifacts in them that aren't being used upon installation (wheels are only supposed to hold files that need to be installed).

Sure, we are currently investigating a recent increase in wheel size to see to what extent we can reduce it.

**Comment by grlee77** [comment]
Re: 
> investigate how the size of individual wheels can be reduced

I found today that our recent switch from deprecated `from distutils.command.build_py import build_py` to `setuptools.command.build_py import build_py` has resulted in wheels growing by ~50% in size. This is because the setuptools variant seems to end up automatically including all Cython and generated C/C++ files into the wheel while the older distutils one does not. Not sure yet if this was an intended change on the part of `setuptools` or a bug?

Cython's generated source code files tend to be very large (multiple MB uncompressed), so this causes a substantial increase in wheel size.
