### ISSUE TITLE
Issue: PEP 541 Request: duplicity

### ISSUE THREAD

**Issue by kwloafman** [pypa/pypi-support#151]
**duplicity**
PROJECT_NAME: https://pypi.org/project/duplicity
USER_NAME: https://pypi.org/user/FirstPrime

**Reasons for the request**
The project has been abandoned, last update was in 2017

**Maintenance or replacement?**
I plan to maintain the project and keep it up to date.  I am the primary maintainer for duplicity.

**Contact and additional research**
I looked for an email address and could not find one.

**Comment by yeraydiazdiaz** [comment]
Hello @kwloafman, I've emailed the owner regarding your request.

In the meantime, could you add a link to the repository you're maintaining? Also, are you publishing your version of duplicity with another name?

**Comment by kwloafman** [comment]
Hi Yeray,

Thanks for following up!

I'm not publishing duplicity under another name.

I'm maintaining duplicity on Launchpad duplicity
<https://launchpad.net/duplicity>.  The current repository is 0.8-series
<https://code.launchpad.net/~duplicity-team/duplicity/0.8-series>.  I've
been the maintainer since 2007.

...Ken

**Comment by yeraydiazdiaz** [comment]
I just heard back from the owner accepting the transfer. I will now ask an admin to perform it for you.

**Comment by ad-m** [comment]
Owner access rights for FirstPrime granted.  Feel free to remove me as owner & clean up package. I reserved the name with the intention of publishing duplicity on pypi by self, since it is open-source. Energy was not enough to automate the process and actually do it. Look at my comment: https://answers.launchpad.net/duplicity/+question/654243

**Comment by yeraydiazdiaz** [comment]
Excellent, thanks @ad-m!

**Comment by kwloafman** [comment]
Thank you very much!  I'll get on it.

...Ken
