### ISSUE TITLE
PEP 541 Request: python-libtorrent (test-pypi)

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [pypa/pypi-support#1513]
### Project to be claimed

`python-libtorrent`: https://test.pypi.org/project/python-libtorrent/

### Your PyPI username

`arvidn`: https://test.pypi.org/user/arvidn/

### Reasons for the request

This is a follow-up of #1299, on test-pypi.

Copypasta from that ticket:

@arvidn is the owner of libtorrent (aka libtorrent-rasterbar).

The project has python bindings, but Arvid isn't very familiar with the python ecosystem, and never published builds to pypi.

I'm helping Arvid with better python integration, and making this request on his behalf.

Someone uploaded builds to https://test.pypi.org/project/python-libtorrent several years ago, without authorization, input or contact to the project owners.

We are in discussion to change libtorrent's official distribution name to just `libtorrent` instead of `python-libtorrent`, and we already have registered https://pypi.org/project/libtorrent and https://test.pypi.org/project/libtorrent . 

Whether or not we decide to commit to this change, we would like to recover https://test.pypi.org/project/python-libtorrent to arvid's ownership, to reduce confusion among users.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/arvidn/libtorrent

### Contact and additional research

https://pypi.org/user/robalar does not provide a public email address.

There is a github user of the same name, but they do not appear actively involved in libtorrent/bittorrent development and do not appear to be very active, so I have not tried to contact them.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
