### ISSUE TITLE
PEP 541 Request: vkit

### ISSUE THREAD

**Issue by huntzhan** [pypa/pypi-support#1515]
### Project to be claimed

`vkit`: https://pypi.org/project/vkit

### Your PyPI username

`huntzhan`: https://pypi.org/user/huntzhan

### Reasons for the request

The `vkit` project is squat by user: `Collie` as mentioned in [this issue](https://github.com/pypa/pypi-support/issues/791). This project is empty and contain no code, and has been inactive for almost a year (Dec 17, 2020). I have tried to contact `Collie`, but unfortunately there's no way to do that.

I'm the author of [vkit-dev/vkit](https://github.com/vkit-dev/vkit), which is in active and fast development cycle. Currently I'm using the project name `python-vkit` and `python-vkit-nightly`, and would like to use the project name `vkit` in the future. I'm wondering if you can help to transfer this me to my account.

Thank you!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/vkit-dev/vkit

### Contact and additional research

1. No contact in pypi.org user page.
2. Cannot google this user.
3. Have searched in GitHub and cannot find this user.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
