### ISSUE TITLE
PEP 541 Request: sagetex

### ISSUE THREAD

**Issue by dimpase** [pypa/pypi-support#1516]
### Project to be claimed

`sagetex`: https://pypi.org/project/sagetex

### Your PyPI username

`dimpase`: https://pypi.org/user/dimpase

### Reasons for the request

It appears (from the twine error message) that `sagetex` name is "taken".
```
The name 'sagetex' isn't allowed. See https://pypi.org/help/#project-name for more information.
```
However I cannot find any information on such a project on PyPI. Note that `sagetex` is a long established name of a component 
[sagetex](https://github.com/sagemath/sagetex)  of [sagemath](https://github.com/sagemath/sage), parts of which are on PyPI.

We would like to make `sagetex` into a proper PyPI package, but the name seems to be reserved, with no traces to be found.

## EDIT 

it is squatted by Fedora in #355 - to distribute our project... 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

/dev/null - replaced with
https://github.com/sagemath/sagetex

### Contact and additional research

https://pypi.org/project/sagetex/ gives 404

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dimpase** [comment]
PS. I am able to upload the package to `testpypi` repository just fine.

**Comment by dimpase** [comment]
The name is squatted by Fedora - please release it to us, the upstream of this package!

**Comment by encukou** [comment]
Yes, please do!
Thanks for planning to release on PyPI, @dimpase!

**Comment by encukou** [comment]
@di, could you unblock `sagetex`?

**Comment by di** [comment]
I've transferred the project `sagetex` to the user`dimpase`.

**Comment by dimpase** [comment]
Thanks!
