### ISSUE TITLE
PEP 541 Request: twin

### ISSUE THREAD

**Issue by bleib1dj** [pypa/pypi-support#1518]
### Project to be claimed

`twin`: https://pypi.org/project/twin

### Your PyPI username

`bleib1dj`: https://pypi.org/user/bleib1dj

### Reasons for the request

The https://pypi.org/project/twin/ project has not had any activity since April 2016 and never had any contributions other than to take the package name. It appears bhoffman has done this for multiple package names, not just twin.

I am submitting this request because our team at fetch.ai is working on our digital twin framework and want to call our package "twin".

### Maintenance or replacement?

Replacement

### Contact and additional research

Since bhoffman is squatting on multiple package names such as:

- creator https://pypi.org/project/creator/
- asemble https://pypi.org/project/asemble/
- objectify https://pypi.org/project/objectify/
- limb https://pypi.org/project/limb/
- jschem https://pypi.org/project/jschem/
- JsonArchitect https://pypi.org/project/jsonarchitect/

we have not reached out directly. We have investigated these packages and it appears the majority of them were spun up on the same day, Jun 9, 2017, in an attempt to block usage of those package names. None of the projects have descriptions, links to a repository, or useful information for the community.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
