### ISSUE TITLE
github form "Size Limit Request" 400 error

### ISSUE THREAD

**Issue by deshantm** [pypa/pypi-support#1521]
I've been trying to fill out the form:

https://github.com/pypa/pypi-support/issues/new?assignees=&labels=limit+request&template=limit-request-file.yml&title=File+Limit+Request%3A+aihwkit+-+400+MB

and getting HTTP 400 error for the last two days. Is it just me?

Mac OS X, Google Chrome Browser.

**Comment by ewdurbin** [comment]
I'm able to reproduce this. It may have something to do with #1511, but it's not clear to me what.

**Comment by pradyunsg** [comment]
Huh. Quite interesting. I can reproduce this too.

**Comment by pradyunsg** [comment]
Okay, there's a key that seems like it's auto-generated, and doesn't have the required value.

| required_field_856d | "" |
-- | --

**Comment by pradyunsg** [comment]
Alrighty, fixed in #1523 and tested in #1524. :)

**Comment by deshantm** [comment]
Thank you! Works for me too! #1525
