### ISSUE TITLE
PEP 541 Request: pygments-style-solarized

### ISSUE THREAD

**Issue by ickc** [pypa/pypi-support#1522]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pygments-style-solarized

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ickc

### Reasons for the request

Previously, the PyPI package `pygments-style-solarized`
is from <https://github.com/shkumagai/pygments-style-solarized>.

This GitHub repo is marked as archived and mentioned it as not maintained anymore.

Recently, `buggs-funny` released a version `100.10.7` on PyPI, with no description and has a very strange email address.
I speculate that this is malicious.

Please investigate further. I'm willing to claim the namespace and maintain this PyPI package
and just release the last version at <https://github.com/shkumagai/pygments-style-solarized>
and properly communicate about the deprecation.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/shkumagai/pygments-style-solarized

### Contact and additional research

No attempt to contact this seemingly fake email: sdfsdfsfsd@sdfsdfs.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ickc** [comment]
Another sign that this package is malicious:
it is failing the test on our conda-forge feedstock at
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=426012&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d
which pulls this package to conda.

**Comment by yeraydiazdiaz** [comment]
Hello @ickc, this project was placed in the prohibited project names list by an admin.

I am closing this issue now, but if you would like to continue maintenance of the project, admins can release the project to you.
