### ISSUE TITLE
File Limit Request: aihwkit - 400 MB

### ISSUE THREAD

**Issue by deshantm** [pypa/pypi-support#1525]
### Project URL

https://pypi.org/project/aihwkit/

### Does this project already exist?

- [X] Yes

### New Limit

400

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

For our next release we want to add Cuda/GPU support. 

Much of the size comes from the libraries needed for Cuda support, but even our binary with GPU support is over the limit by itself because we want to add support for more GPU architectures
libcublas, libcublas, openblas93M aihwkit.libs/libcublas-8e09e770.so.11.2.0.252

168M aihwkit.libs/libcublasLt-e21cb9f9.so.11.2.0.252

 69M aihwkit.libs/libcurand-ca1dedca.so.10.2.1.245

36M aihwkit.libs/libopenblas-r0-f650aae0.3.3.so

our aihwkit library
182M rpu_base.cpython-39-x86_64-linux-gnu.so

### Reasons for the request

For our next release we want to add Cuda/GPU support. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by todd-deshane** [comment]
was this done? I'm getting HTTPError: 503 Server Error: first byte timeout for url: https://test.pypi.org/legacy/

**Comment by pradyunsg** [comment]
Limit request granted. The new per-file limit on PyPI is 400 MB.

https://test.pypi.org/project/aihwkit/ does not exist. If you need a limit increase on that, please create that and file a new ticket.
