### ISSUE TITLE
File Limit Request: block2 and block2-mpi - 250 MB

### ISSUE THREAD

**Issue by hczhai** [pypa/pypi-support#1526]
### Project URL

https://pypi.org/project/block2/ https://pypi.org/project/block2-mpi/

### Does this project already exist?

- [X] Yes

### New Limit

250 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The block2 code provides an efficient highly scalable implementation of the Density Matrix Renormalization Group (DMRG) for quantum chemistry [https://github.com/block-hczhai/block2-preview].
The public version of our project is very young, but we have spend almost two years in optimizing the code. We hope that we can get slightly larger file size limit so that the binaries can be easily distributed to users.

### Reasons for the request

To get the highest possible efficiency, most part of the code is written in C++ and we need to use low level templates to support different kinds of symmetry classes and complex/real floating point types. The instantiation of these templates (using pybind11) makes the compiled binary size large. Without affecting efficiency, we found it hard to reduce the binary size. But the efficiency is the very important thing for our project (it has consumed millions of CPU hours!).

Thanks for your kind consideration!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! Is this still relevant? I see that the project has been making regular releases, and I haven't looked deeply into what changed such that this newer limit isn't required.

This request seems reasonable overall, so if in the next four weeks, there's a response that says that this would still be useful, I'm happy to bump this limit. Otherwise, I'll close this when I come back around to triaging these tickets. :)

**Comment by hczhai** [comment]
@pradyunsg Thanks very much for your response! Yes this is still relevant and the newer limit is still required.

> I see that the project has been making regular releases, and I haven't looked deeply into what changed such that this newer limit isn't required.

After reaching the size limit, we still need to fix some old bugs. In order to not exceed the current 100 MB size limit, we temporarily removed some less used features (such as the K point symmetry support) in the binary. But the user has to compile the source code themselves if those features are required.

After the package size limit is increased, we will be able to publish full-feature binaries and keep improving the project. We will use the pip storage carefully and we will delete some old releases once we have a stable version, so that the size of the overall project is reasonable and under the limit.

Thanks very much for your consideration and time!

**Comment by pradyunsg** [comment]
Thanks for the detailed response, and for your patience here. I've bumped limits for both projects to 300 MB. :)
