### ISSUE TITLE
File Limit Request: SciPy - 125 MB

### ISSUE THREAD

**Issue by tylerjereddy** [pypa/pypi-support#1527]
### Project URL

https://pypi.org/project/scipy/

### Does this project already exist?

- [X] Yes

### New Limit

125

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

SciPy is pretty well known I think, has been around for many years. I believe we do try to strip binaries/reduce size where possible, perhaps there are other measures we could take.

I don't think we could remove anything we vendor with the wheel though (OpenBLAS, etc.).

### Reasons for the request

I'm trying to release SciPy `1.8.0rc1` and our `universal2` wheels are hitting the limit, with `twine` returning:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File too large. Limit for project 'scipy' is 100 MB. See https://pypi.org/help/#file-size-limit for more information.
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by tylerjereddy** [comment]
cc @rgommers

**Comment by pradyunsg** [comment]
Limit on PyPI bumped to 125 MB. :)

**Comment by tylerjereddy** [comment]
thanks!!

**Comment by rgommers** [comment]
Thanks @pradyunsg for the quick response. FYI this size increase is unexpected (and not desired), we should be able to get it back down to <75 MB for the `universal2` wheels I believe - need to investigate what happened here.
