### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jeblad** [pypa/pypi-support#1528]
### PyPI Username

jeblad

### Reason for request

Email address is not verified due to password problems, thus can not be used for reset of password. Could be user error during copy-paste from a password manager, or a password error due to some other problem. Checked what could be used as password, but none worked.

Note: This is on Test PYPI!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Are you still experiencing an issue? I see that the email address associated with the account on test.pypi.org is now marked as verified. Please reopen if assistance is needed.
