### ISSUE TITLE
Email soft bounces due to IP spam classification from gmx.net

### ISSUE THREAD

**Issue by poke1024** [pypa/pypi-support#153]
Hello there, I've been trying to reset my password through https://pypi.org/account/request-password-reset/ for like 30 minutes, but I don't seem to receive any email with reset link.

**Comment by yeraydiazdiaz** [comment]
Hi @poke1024, you seem to be in a similar situation that was [reported yesterday](https://github.com/pypa/pypi-support/issues/154#issuecomment-573606690). The error message is the same so it may be a temporary issue.

cc @ewdurbin

**Comment by poke1024** [comment]
@yeraydiazdiaz Ok, that makes sense, probably an issue with gmx.net.

**Comment by ewdurbin** [comment]
Using all of the available data from our SES integration, it seems that many of the IP addresses that our account is associated with have been listed on the "SORBS" and "UCEPROTECT" 

[From SES docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/blacklists.html#bl-q4):

> We don't monitor blacklists that are unlikely to impact delivery across the entire Amazon SES service, or that don't have a measurable impact on delivery to major email providers. The blacklists offered by SORBS and UCEPROTECT fall into this category. Because of the specific listing and delisting practices of the vendors who operate these lists, we are unable to have our IP addresses removed from these lists.

Based on the domains of all Soft Bounces in the the current record, it seems that the following providers may be using these block lists:

- `web.de`
- `gmx.de`
- `gmx.com`
- `gmx.net`
- `gmx.at`
- `gmxpro.de`

At this time, it seems there is little we can do aside from requesting a dedicated IP on SES... which we are very unlikely to qualify for based on our comparatively low volume.

**Comment by poke1024** [comment]
Hm. Interesting. These domains all belong to United Internet (https://en.wikipedia.org/wiki/United_Internet).

**Comment by poke1024** [comment]
Since it's still blocking, is this a good place to ask for change of email on my PyPI account?

**Comment by ewdurbin** [comment]
@poke1024 sorry for missing that request, can you open a new issue here with the Account Recovery template?

**Comment by armando170A** [comment]
> Hola, he estado tratando de restablecer mi contraseña a través [de https://pypi.org/account/request-password-reset/](https://pypi.org/account/request-password-reset/) durante unos 30 minutos, pero no parece que reciba ningún correo electrónico con el enlace de restablecimiento.

**Comment by armando170A** [comment]
?S

**Comment by armando170A** [comment]
https://help.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-mobile-app

**Comment by di** [comment]
@armando170A Please open a new issue if you're still experiencing this.

**Comment by di** [comment]
Looks like this is now affecting `@outlook.com` and `@hotmail.com` addresses as well.

**Comment by ewdurbin** [comment]
the gmx domains seem to be accepting our emails again!

**Comment by ewdurbin** [comment]
also not seeing @outlook.com, @hotmail.com, or @live.com addresses in our bounces at the moment either.

**Comment by cjw85** [comment]
I had  issues receiving verification emails to `@outlook.com` yesterday evening. Verification emails to alternative were received immediately.

**Comment by poke1024** [comment]
For me, this has been resolved in the meanwhile. I'm closing this.

**Comment by di** [comment]
@cjw85 Could you open a new issue w/ and include your PyPI username?
