### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ksaur** [pypa/pypi-support#1533]
### PyPI Username

ksaur

### Reason for request

Hi, 
I have access to my email. I have my password, and I have my "one time app" setup that is giving me a code. However, it says that I can only login with a USB, my device, or a recovery code.  My "one time password" that I can access via my phone app is not accepted by the website anymore.  Can I use any of these (email, my password, my one time app) to recover my account?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello @ksaur.

Our internal security logs indicate that the following activities occurred on this account on 2020-12-06:

- A security key was added
- Recovery codes were generated
- TOTP was disabled

The security key was then used successfully for login over the following months, most recently 2021-04-13.

Please use your security key or one of the generated recovery codes to access your account.

**Comment by ksaur** [comment]
The security key was coming from my updated authenticator app only.  I have never had a physical security key other than my phone app TOTP which I used throughout this year, so I'm not sure what changed or what to do.

I do not have access to recovery codes.  I do have my email, password, and TOTP.  Is there something else I can do?

**Comment by ksaur** [comment]
I think my "computer" (MacOS) used to somehow be the "device" I used, and after the last OS update maybe that is why it is broken.  Is there a way to re-enable TOTP?

**Comment by ksaur** [comment]
<img width="429" alt="Screen Shot 2021-12-18 at 9 20 08 AM" src="https://user-images.githubusercontent.com/1703543/146650059-f65f2568-8fca-4efb-8683-ac030b279329.png">
Then i would pick "This Device" which stopped working for me recently apparently.

**Comment by ewdurbin** [comment]
The only information we have about the WebAuthn credential (aka Security Key, key is more to do with the cryptographic sense than physical) is the label `px5`.

If that's not sufficient, we're a little stuck with recovery options since your account has valid two-factor auth enabled *and* recovery keys.

**Comment by ksaur** [comment]
Ok, I guess I am permanently locked out then?  There is no way to re-enable TOTP or use my email?

Do I make a new account and have my co-maintainers add my new account?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ksaur** [comment]
Hello, I had followed the instructions, is there any other action i need to do?

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
