### ISSUE TITLE
PEP 541 Request: mozilla-schema-generator

### ISSUE THREAD

**Issue by whd** [pypa/pypi-support#1534]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mozilla-schema-generator/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/mozdataops/

### Reasons for the request

This is a Mozilla-owned project, and the currently listed maintainers are past and present Mozillians, but we have lost admin access because some maintainers had corporate emails that were deactivated.

See https://github.com/pypa/pypi-support/issues/1448 for our original attempt to regain ownership. We'd like to add our ops team's PyPi account as owner of the project so this doesn't happen again.

We might be able to re-enable the email address associated with current maintainers and forward messages to the new maintainers (mozdataops) if that is helpful in establishing the legitimacy of this ownership transfer.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/mozilla/mozilla-schema-generator

### Contact and additional research

See https://github.com/pypa/pypi-support/issues/1448. @fbertsch is aware of this request and per that issue was trying to get @wlach added as owner of the project, but did not have access to the email associated with his pypi account. We're requesting `mozdataops` be made owner here instead of (or in addition to) wlach. wlach is currently able to push packages but not change ownership of the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @whd, I have set @wlach as the owner of the project.
