### ISSUE TITLE
PEP 541 Request: Cantera

### ISSUE THREAD

**Issue by bryanwweber** [pypa/pypi-support#1536]
### Project to be claimed

Cantera

### Your PyPI username

`bryanwweber`: https://pypi.org/user/bryanwweber/

### Reasons for the request

I am trying to upload our first release of Cantera to PyPI. However, `twine` is giving me a 400 error:

> HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
> The name 'Cantera' isn't allowed. See https://pypi.org/help/#project-name for more information.

I [searched](https://pypi.org/search/?q=cantera) for 'cantera' on PyPI, but did not turn up any projects named only 'cantera'. All the projects listed in the search results are related to the Cantera project, but none are an actual release of Cantera.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Our GitHub organization is https://github.com/Cantera and our website is https://cantera.org. I am a member of the [Cantera steering committee](https://cantera.org/governance.html#current-steering-committee) and I am the primary developer handling packaging for Cantera. We have a Conda package in [our own channel](https://anaconda.org/cantera/cantera) as well as in the [conda-forge channel](https://anaconda.org/conda-forge/cantera).

### Contact and additional research

I do not see any owners of a 'cantera' package on PyPI, so I have not contacted anyone. I'm a little perplexed as to why this name cannot be used. Following the [link](https://pypi.org/help/#project-name) for additional help, I do not see how any of these reasons apply to this project:

* The project name conflicts with a Python Standard Library module from any major version from 2.5 to present.
  * There are no standard library modules named Cantera as far as I know
* The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.
  * I don't see why this would be a name-squatting problem
* The project name has been registered by another user, but no releases have been created.
  * If the name has been registered but no releases have been created, and therefore the project does not appear in a search, I'm not quite sure how to proceed.

Thank you for your help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bryanwweber, `cantera` was placed in the prohibited project names list by an admin after a name confusion report. I believe it would be safe to release the project name to you, but only @pypa/warehouse-admins have permissions to do so.

**Comment by bryanwweber** [comment]
@yeraydiazdiaz Thank you! I'm curious what the other package was?

**Comment by yeraydiazdiaz** [comment]
I personally don't know, the admin that processed the request may remember.

**Comment by ewdurbin** [comment]
It was placed on the prohibited project name list after being included in a report of projects which did not exist on the index, but were included as a dependency of projects which _did_ exist on the index. Which could have allowed attackers to register the name and deliver malicious code to dependent projects.

After review, the projects depending on the non-existent `cantera` dependency on PyPI document retrieving it from Conda, thus I'm confident having released the project to PyPI User `bryanwweber`.

**Comment by bryanwweber** [comment]
Thanks for the quick help @ewdurbin and @yeraydiazdiaz!
