### ISSUE TITLE
Project Limit Request: apache-flink - 30 GB

### ISSUE THREAD

**Issue by HuangXingBo** [pypa/pypi-support#1537]
### Project URL

https://pypi.org/project/apache-flink/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We provide python support in Apache Flink since 1.9 version. And we have released 22 versions since Feb 11, 2020. 

### How large is each release?

In release-1.9 and release-1.10,  the size of each small release will be about 250MB, which include only one source package.
In release-1.11, the size of each small release will be about 1.5GB, which include 6 wheel packages and one source package.
In release-1.12, the size of each small release will be about 2GB, which include 8 wheel packages and one source package.
After release-1.13, we optimize the package size and the size of each small release will be only about 20MB.

### How frequently do you make a release?

Roughly once every 4 months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Is this related to #1359, #1360, #1361 and #952?

**Comment by HuangXingBo** [comment]
https://github.com/pypa/pypi-support/issues/952 The apache-flink-librareis mentioned in the description is another package introduced when we optimized the package size in Flink 1.13. As for pyalink, it is another project in the apache-flink ecosystem. It depends on apache-flink, just like the relationship between pandas and numpy.

**Comment by HuangXingBo** [comment]
Hi @pradyunsg Could you help resolve this request? Thanks.

**Comment by HuangXingBo** [comment]
@pradyunsg Sorry to bother you again, but Flink is about to release 1.15 in next month, and the previously released-1.12.6 package has not been uploaded to PyPi because of insufficient space.

**Comment by pradyunsg** [comment]
Hiya! There's no need to @-mention me here -- it isn't going to speed things up -- I triage these tickets in bulk, when I have the free time to do so.

I've bumped the limit to 30 GB. I'll might defer to the PyPI admins for larger requests in the future. :)
