### ISSUE TITLE
Verification e-mail not arriving

### ISSUE THREAD

**Issue by stefandtw** [pypa/pypi-support#154]
Hello,

I am not receiving any e-mails. My account name is stefandtw.

I resent the verification e-mail.

I checked my spam folder and whitelisted noreply@pypi.org on my e-mail account.

Last week I received e-mails from TestPyPI without any issues.

**Comment by yeraydiazdiaz** [comment]
@alffdtu I assume your issue has been resolved, if not feel free to comment.

I'm closing this issue in favor of the more specific #153.

**Comment by AnySomebody1** [comment]
Hello, it could be that I'm havin the same issue currently. At least I don't receive any verification mail and I use gmx as mail service.
