### ISSUE TITLE
File Limit Request: rife-ncnn-vulkan-python - 400 MB

### ISSUE THREAD

**Issue by ArchieMeng** [pypa/pypi-support#1540]
### Project URL

https://pypi.org/project/rife-ncnn-vulkan-python/

### Does this project already exist?

- [X] Yes

### New Limit

400

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[rife-ncnn-vulkan](https://github.com/nihui/rife-ncnn-vulkan) is nihui's ncnn implementation of Real-World Super-Resolution via Kernel Estimation and Noise Injection super resolution.

[rife-ncnn-vulkan-python](https://github.com/media2x/rife-ncnn-vulkan-python) wraps [rife-ncnn-vulkan project](https://github.com/nihui/rife-ncnn-vulkan) by SWIG to make it easier to integrate rife-ncnn-vulkan with existing python projects.

It was created on 29 Mar 2021.

Since it includes machine learning models from upstream, which reach totally 368M, it is impossible to drop and compress the whole packge down to the 100M limit.

### Reasons for the request

Since it includes machine learning models from upstream, which reach totally 368M, it is impossible to drop and compress the whole packge down to the 100M limit.
And since upstream may adopt new models (the RIFE models is still updating), the package size may go higher in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
From the guidelines in the README:

> Upload limits are generally denied for the following reasons:
>  project contains large pre-trained machine learning models

Consider providing these models via a separate mechanism compared to bundling them in PyPI wheels (like https://www.nltk.org/data.html).

**Comment by ArchieMeng** [comment]
> From the guidelines in the README:
> 
> > Upload limits are generally denied for the following reasons:
> > project contains large pre-trained machine learning models
> 
> Consider providing these models via a separate mechanism compared to bundling them in PyPI wheels (like https://www.nltk.org/data.html).

Ok, I will try to do that.
