### ISSUE TITLE
PEP 541 Request: eris

### ISSUE THREAD

**Issue by pukkamustard** [pypa/pypi-support#1541]
### Project to be claimed

`eris`: https://pypi.org/project/eris/

### Your PyPI username

`pukkamustard`: https://pypi.org/user/pukkamustard

### Reasons for the request

- Links to Documentation, Source Code are broken and return a 404.
- Links to Bug tracker lead to a mostly inactive project with the same name but seemingly unrelated to the PyPI package 'eris' (https://launchpad.net/eris).
- There is a single "pre-release" version released in 2017. I have not found any continued development of the project.
- I am unable to contact the two listed maintainers as I can not find an email address.
- The author-email in the setup.cfg points to a mailing list that does not seem to exist anymore (openstack-dev@lists.openstack.org)

I would like to claim the name for a library that implements the ERIS encoding (http://purl.org/eris). The library currently lives here: http://inqlab.net/git/python-eris.git

### Maintenance or replacement?

Replacement

### Source code repositories URLs

- repository of replacement: http://inqlab.net/git/python-eris.git/about/

### Contact and additional research

I have unsuccessfully attempted to find an email address to contact authors or maintainers.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @pukkamustard, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owners and allow one week for replies before proceeding with the request.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
