### ISSUE TITLE
PEP 541 Request: pyreleaseplugin

### ISSUE THREAD

**Issue by rlvoyer** [pypa/pypi-support#1543]
### Project to be claimed

`pyreleaseplugin`: https://pypi.org/project/pyreleaseplugin

### Your PyPI username

`robotron`: https://pypi.org/user/robotron

### Reasons for the request

The current pyreleaseplugin project seems to be abandoned. As one of the primary authors of [an open source Python Github project by the same name](https://github.com/socrata/python-release-plugin), I am requesting that ownership of the pypi project be transferred to me. If ownership is transferred, I will take steps to make sure that the project functions as expected (which is not the case presently).

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/socrata/python-release-plugin

### Contact and additional research

The email currently associated with the pypi project appears to be fake (author@example.com).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @rlvoyer, the project was placed under control of @pypa/warehouse-admins, I have transferred it to you.
