### ISSUE TITLE
File Limit Request: pybacktrack - 120 MB

### ISSUE THREAD

**Issue by jcannon-gplates** [pypa/pypi-support#1545]
### Project URL

https://pypi.org/project/pybacktrack

### Does this project already exist?

- [X] Yes

### New Limit

120 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a tool for reconstructing paleobathymetry on oceanic and continental crust.

This will be the 5th release. The first release was mid-2018.

To reduce the package size we have:
- Used NetCDF 4 (instead of 3) which compresses our binary grid image files.
- Downsampled the *resolution* of our binary grid image files to reduce file sizes (while still retaining enough resolution for functionality).

### Reasons for the request

We request a size limit increase because:
- We have added two new dynamic topography models (each model is a sequence of embedded grid image files).
- Also added a deformation model (embedded binary files) to support new functionality in this release.

We also expect the next release to increase in size as new dynamic topography models will likely be added.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Granted! Your new limit is 200 MB per release file.
