### ISSUE TITLE
PEP 541 Request: sam

### ISSUE THREAD

**Issue by abontsema** [pypa/pypi-support#1547]
### Project to be claimed

`sam`: https://pypi.org/project/sam

### Your PyPI username

`abontsema`: https://pypi.org/user/abontsema

### Reasons for the request

This package is no longer in use. Last update in 2011, and no existing repo/documentation.

I like to use this tag for a project that I am working on.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

non existent

### Contact and additional research

I had email contact with the owner and he accepted a transfer. He's not in the position to add me as a owner, so therefore I try it via this request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abontsema** [comment]
![image](https://user-images.githubusercontent.com/32163843/146594324-d2a77b36-10f9-449f-8c29-e256296dc436.png)

**Comment by yeraydiazdiaz** [comment]
Hello @abontsema, I have started the reachability process for your request, hopefully we will hear back soon from the owner and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
