### ISSUE TITLE
PEP 541 Request: feast-trino

### ISSUE THREAD

**Issue by MattDelac** [pypa/pypi-support#1549]
### Project to be claimed

`Feast trino`: https://pypi.org/project/feast-trino

### Your PyPI username

`shopify`: https://pypi.org/user/shopify

### Reasons for the request

Shopify wants to publish an open source project (https://github.com/Shopify/feast-trino/) under the name `feast-trino`. 

Feast is an open source feature store (refer to https://docs.feast.dev/) and it would make sense to keep a similar convention (refer to other plugins available in pypi https://pypi.org/search/?q=feast-&o=)

### Source code repositories URLs

https://github.com/Shopify/feast-trino/

### Contact and additional research

When I want to register the package `feast-trino` with twine I get the following error
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'feast-trino' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

I can confirm that this package does not exist on pypi (refer to https://pypi.org/project/feast-trino/ or [the search](https://pypi.org/search/?q=feast-trino&o=)).

It's not possible to contact the previous owner of this package

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @MattDelac, the name `feast-trino` was placed in the prohibited project names list, @pypa/warehouse-admins could you release the name, please?

**Comment by MattDelac** [comment]
> Hello @MattDelac, the name `feast-trino` was placed in the prohibited project names list, @pypa/warehouse-admins could you release the name, please?

What do you mean by `could you release the name` ?
