### ISSUE TITLE
PEP 541: transfer ownership of unmaintained 'zflow' package

### ISSUE THREAD

**Issue by elgalu** [pypa/pypi-support#155]
**Project to be claimed**
`zflow`: https://pypi.org/project/zflow

**Your PyPI username**
`elgalu`: https://pypi.org/user/elgalu

**Reasons for the request**
I believe this project has been abandoned:
- last release was in 2010.
- the author of the project @jlowery hasn't replied to my contact attempts for a long time.

**Maintenance or replacement?**
We (Zalando SE) intended to publish a different package under the `zflow` name.
Our project `zflow` is described at:
https://www.linkedin.com/pulse/building-ml-workflows-zalando-zflow-s%C3%A1nchez-fern%C3%A1ndez/

We haven't published the source code yet but we can see examples of Zalando code at:
https://github.com/zalando/

**Contact and additional research**
I've tried to contact the author via email as published at pypi with no success.

**Comment by fcojersanchez** [comment]
👍

**Comment by elvinx** [comment]
👍

**Comment by HCharlie** [comment]
👍

**Comment by yeraydiazdiaz** [comment]
Thanks @elgalu for the report. Could I please ask other users to not comment with 👍 , it only adds to the noise, there's a button for that in GitHub.

**Comment by HCharlie** [comment]
👍

**Comment by yeraydiazdiaz** [comment]
Hello @elgalu, I have emailed the owner regarding your request. I also realized he owns another project [`stypes`](https://pypi.org/project/stypes/) which has a GitHub repo owned by user @jeremylowery.

Hopefully we'll hear back soon and move forward with the request.

**Comment by jeremylowery** [comment]
Yes, that is me, as well as the owner of the zflow package. You are correct in that I currently no long maintain the package (as various other people asked for my blessing to fork the project and roll it into their own which I approved). I would be perfectly fine relinquishing the package name.

**Comment by jamadden** [comment]
Hi @jeremylowery, and thanks for responding! It requires superuser privileges for a PyPI admin to transfer a project (and there are very few of those and they're all overworked), plus it results in an unclear audit trail when they do so. To solve both issues, the preferred way to move forward would be for you to log in to PyPI and add `elgalu` as a new owner on the project. Once this is done, `elgalu` could remove your account as an owner, if desired.

**Comment by elgalu** [comment]
Thank you so much guys, it all worked out!
https://pypi.org/project/zflow/
