### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gkoller** [pypa/pypi-support#1552]
### PyPI Username

`gkoller`

### Reason for request

Did a password recovery (still got access to my email), and now it asks me to enter an authentication code. Can't remember ever having set one. However as I switched phones recently, I simply might have forgotten to transer all my 2FA data specifically the PyPI one.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by gkoller** [comment]
Thank you for your help. Smooth process!
