### ISSUE TITLE
PEP 541 Request: sqlalchemy-admin

### ISSUE THREAD

**Issue by aminalaee** [pypa/pypi-support#1554]
### Project to be claimed

`sqlalchemy_admin`: https://pypi.org/project/sqlalchemy_admin

### Your PyPI username

`aminalaee`: https://pypi.org/user/aminalaee

### Reasons for the request

I'm working on a SQLAlchemy admin project, it's still a work-in-progress, the PyPI package is taken.
The `sqlalchemy_admin` package was last updated in 2013 on PyPI and I couldn't find the project home.

I've contacted the owner and asked him if he doesn't plan to use the name, so I can take it. I haven't received any response yet, and I'm not sure if they ever see my message.

He has a few other projects on PyPI which were updated recently but they weren't done by him.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/sqlalchemy-admin/sqlalchemy-admin

### Contact and additional research

I've contacted the owner recently, I haven't received any response yet. He hasn't been active on GitHub in 2021 that's why I don't think he might even see my message.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @aminalaee, are you still interested the project name? I see you've published your project as https://pypi.org/project/sqladmin/

**Comment by aminalaee** [comment]
Hi @yeraydiazdiaz 

Yes, that is correct. I used another name anyway.

Thank you,
