### ISSUE TITLE
PEP 541 Request: django-global-permissions

### ISSUE THREAD

**Issue by gdalmau** [pypa/pypi-support#1556]
### Project to be claimed

`django-global-permissions`: https://pypi.org/project/django-global-permissions

### Your PyPI username

`gdalmau`: https://pypi.org/user/gdalmau

### Reasons for the request

The project seems abandoned and it is unmaintained. I want to make it compatible with Django 4.0 and for that at least the pull request https://github.com/eduardo-matos/django-global-permissions/pull/14 is needed.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/eduardo-matos/django-global-permissions

### Contact and additional research

I created an issue mentioning the owner (@eduardo-matos) and I sent him an email without receiving any reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @gdalmau, I will now start the reachability process for your request, hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by gdalmau** [comment]
Thanks @yeraydiazdiaz. Just for information purposes I didn't receive a reply during the time this issue was open.

**Comment by eduardo-matos** [comment]
I've just added [Fernando Celmer](https://github.com/FernandoCelmer) to this project an he will be able to release new versions of this package.

**Comment by yeraydiazdiaz** [comment]
Thanks @eduardo-matos, closing as contact has been made.
