### ISSUE TITLE
PEP 541 Request: page

### ISSUE THREAD

**Issue by fubuloubu** [pypa/pypi-support#156]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/page/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/fubuloubu

**Reasons for the request**

1. This project was never in use, project is merely name squatting using a template project
2. The current maintainer has several projects using the same exact template:
https://pypi.org/user/doublenorth/

**Maintenance or replacement?**

I propose to replace this package with a new package [`page`](https://github.com/zatoichi-labs/page), which adds Python bindings for the new [`age`](https://github.com/FiloSottile/age) encryption tool.

**Contact and additional research**

I contacted the author of `page` via their github-listed email on Janurary 2nd, and have not received a response.

**Comment by yeraydiazdiaz** [comment]
Hello @fubuloubu, I can confirm that user `doublenorth` is name squatting this and other project names.

I will now contact an admin to perform the transfer.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by fubuloubu** [comment]
Thank you!
