### ISSUE TITLE
PEP 541 Request: pyrblx

### ISSUE THREAD

**Issue by Maginfyx** [pypa/pypi-support#1560]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pyrblx

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Execed

### Reasons for the request

The project has been abandoned, as written by the authors on GitHub (https://github.com/credital/pyrblx). They have moved to a new library (roblox.py) which means that the old library is no longer able to be used.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/credital/pyrblx

### Contact and additional research

No contact information can be found on either PyPi, or on the users GitHub profile.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Maginfyx, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
