### ISSUE TITLE
PEP 541 Request: mldev

### ISSUE THREAD

**Issue by prog-autom** [pypa/pypi-support#1561]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ml-dev

### Your PyPI username

`USER_NAME`: https://pypi.org/user/se_ml

### Reasons for the request

The project https://pypi.org/project/ml-dev has a single empty release which does not contain any functionality besides providing the version and basic package info. It has not been updated since 2019, the project repository is no longer available

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://gitlab.com/mlrep/mldev

### Contact and additional research

I contacted the author Lunluen via email <mas581301 [at] gmail.com>.
The project repository is no longer available (404) https://github.com/lunluen/ml-dev

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by prog-autom** [comment]
Just an update that I still did not receive a reply from Lunluen @lunluen regarding the replacement. Hope he reacts here if I mention him :)

**Comment by yeraydiazdiaz** [comment]
Hello @prog-autom, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
