### ISSUE TITLE
PEP 541 Request: minestrone

### ISSUE THREAD

**Issue by adamghill** [pypa/pypi-support#1563]
### Project to be claimed

`minestrone`: https://pypi.org/project/minestrone

### Your PyPI username

`adamghill`: https://pypi.org/user/adamghill

### Reasons for the request

After searching on PyPI and not seeing any projects with the name `minestrone`, I uploaded my package to test.pypi.org just fine: https://test.pypi.org/project/minestrone/. But, then when I uploaded to pypi.org I got this error:

```
UploadError

HTTP Error 403: The user 'adamghill' isn't allowed to upload to project 'minestrone'. See https://pypi.org/help/#project-name for more information.
```

I assume that someone has the project name, but has never created a release for it? If possible, I would like the ability to use this project name. Thank you!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/adamghill/minestrone

### Contact and additional research

No attempts to contact because I can't find any information about this project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @adamghill, the `minestrone` project exists in PyPI but has no releases and is therefore considered invalid. I believe its owner is @jezdez so hopefully he'll be able to clarify his position in regards to the project.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
