### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ShyPixie** [pypa/pypi-support#1564]
### PyPI Username

shypixie

### Reason for request

I've been away for a while and now I need to reset my password because it was leaked but the registered email don't exist anymore

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via the email address on file, if that bounces or no response is received after 7 days, we will proceed via another mechanism.

**Comment by ewdurbin** [comment]
Thanks, responded from support@ with instructions to proceed.

**Comment by ewdurbin** [comment]
Confirmation complete. Account email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
