### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Ahmaf1100** [pypa/pypi-support#1565]
### PyPI Username

4M1RR32A

### Reason for request

I have lost my test.pypi.org recovery code
Please email it to me

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Ahmaf1100** [comment]
??

**Comment by ewdurbin** [comment]
test.pypi.org 2FA reset for 4M1RR32A User.
