### ISSUE TITLE
Need owner access to Cookiecutter on test.pypi.org

### ISSUE THREAD

**Issue by audreyfeldroy** [pypa/pypi-support#1566]
### PyPI Username

`audreyr`

### Reason for request

We are rebuilding the Cookiecutter release process and need to be able to have multiple people testing the process. Unfortunately, I do not have rights on test.pypi.org to do any maintenance. Please grant me maintainer/ownership rights on test.pypi.org

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by pradyunsg** [comment]
Can you please file a PEP 541 (name retention ticket) for this?

**Comment by ewdurbin** [comment]
Hi @audreyfeldroy, I see that the `audreyr` user on test.pypi.org was granted `Owner` permission on 2021-12-28 by another project owner. Please reopen this issue if you still need assistance.
