### ISSUE TITLE
PEP 541 Request: purgatory

### ISSUE THREAD

**Issue by mardiros** [pypa/pypi-support#1567]
### Project to be claimed

`purgatory`: https://pypi.org/project/purgatory

### Your PyPI username

`mardiros`: https://pypi.org/user/mardiros

### Reasons for the request

Hello,
I've recently created a new library but the names is not available on PyPI and it is confusing to me. The project does not exists on PyPI currently, so I don't see the reason of the error. Is the name offensing ?

I've uploaded to "https://pypi.org/project/purgatory-circuitbreaker/" so I hope it is not the case, but please, let me know.

### Contact and additional research

```
Publishing purgatory (0.1.0) to PyPI
 - Uploading purgatory-0.1.0-py3-none-any.whl 100%

  UploadError

  HTTP Error 403: The user 'mardiros' isn't allowed to upload to project 'purgatory'. See https://pypi.org/help/#project-name for more information.
```

https://pypi.org/project/purgatory/  raise a HTTP 404  error

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @mardiros, the `purgatory` project exists in PyPI but does not have any releases and is therefore considered invalid. The owner appears to be GitHub user @jpulec, since he's active in GitHub I will consider this an attempt of contact and allow one week for replies before proceeding with the transfer.

**Comment by jpulec** [comment]
@yeraydiazdiaz This was a project I started but never managed to get off the ground. Please transfer the name. Thanks for reaching out first.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
