### ISSUE TITLE
PEP 541 Request: lgtv

### ISSUE THREAD

**Issue by klattimer** [pypa/pypi-support#1568]
### Project to be claimed

Can't find an existing one

### Your PyPI username

klattimer

### Reasons for the request

I've been asked to publish my project from here on pypi - https://github.com/klattimer/LGWebOSRemote

The project structure is built around the module name LGTV but it isn't allowed.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/klattimer/LGWebOSRemote

### Contact and additional research

I can't find an existing project

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by klattimer** [comment]
The name I'm trying to claim is lgtv or LGTV whichever.

**Comment by yeraydiazdiaz** [comment]
Hello @klattimer, there is no project in PyPI name `lgtv` so no transfer is possible.

Looks like you've already packaged your project so you should be able upload the package to PyPI following the [official instructions](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives). If you're still having problems have a look at the [troubleshooting section in PyPI](https://pypi.org/help/#troubleshooting).
