### ISSUE TITLE
PEP 541 Request: shape

### ISSUE THREAD

**Issue by smidm** [pypa/pypi-support#1569]
### Project to be claimed

`shape`: https://pypi.org/project/shape

### Your PyPI username

`smidm`: https://pypi.org/user/smidm

### Reasons for the request

The existing package is basically empty. There is no functionality. It looks like a pypi test.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/smidm/shapes

### Contact and additional research

There is no email address, the website www.hizsr.xyz from `setup.py` doesn't exist.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid, I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
