### ISSUE TITLE
Reset of 2FA on my PyPi account

### ISSUE THREAD

**Issue by gizmo84** [pypa/pypi-support#157]
username: stephane.ludwig
email: gitlab@stephane-ludwig.net
Request: Reset of 2FA on my PyPi.org account.
Reason: Reset phone

Thank you.

**Comment by ewdurbin** [comment]
Hello @gizmo84, please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
