### ISSUE TITLE
Project ownership changes for deceased coworker

### ISSUE THREAD

**Issue by epeisach** [pypa/pypi-support#1573]
### PyPI Username

`Westbrook`

### Reason for request

John Westbrook died recently.  While the GitHub projects he was working on are in organizational GitHub repositories and are taking steps to secure ownership or other oraganziational repositories. 

There are 33 pypi projects owned by John.  In some cases, I  (epeisach) was added as a co-owner, and in some - he is the sole owner. These are wwpdb.* and rcsb.* projects. How do we arrange a transfer of ownership. 

As an organization, we moving to ensure double redundancy to prevent this in the future.

We can provide any documentation you may need.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This is a sad one :(, condolences to your team as well as the friends and family of the deceased. I was able to verify the bad news via online obituary listings.

I see that the User account has been active as recently as Jan 24, 2022, so the password may still be stored in some continuous integration or deployment pipeline.

Otherwise, the Author email on most project uploads is an rcsb domain address. Is that email address still active? If so we can use that for verification.

**Comment by epeisach** [comment]
Yes, some of John's email addresses are still valid.  rcsb.rutgers.edu and rcsb.org domains are being monitored by our assistant director. I suspect that he used is rcsb.org account. (iqb.rutgers.edu or Rutgers.edu were managed by the university IT and the accounts were deleted)

The activity you are observing is likely due to John's use of Azure pipelines to push out releases.  As we control to rcsb and wwpdb GitHub project repositories, we were able to change ownership of those repositories.  We also had several "owners" associated with the Azure account pushing out those releases. I suspect that someone on our data out team made a change to the repository, which automatically created a new release.

Once the pypi ownerships have been expanded,  we will reconfigure Azure.

Due to this experience, we are putting three owners on every pypi package.

Thank you in advance,

Ezra Peisach

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account as well as the common Author address on the rcsb domain, please read the instructions and reply to proceed with recovery.

**Comment by epeisach** [comment]
?I think a more accurate statement is that it is not actively being monitored.  Knowing that you sent a message - I notified our assistant director to look.


We have followed through with your message today.  The timing was such that I told our AD before you sent this message - but it was still being acted upon.


Thank you,


Ezra


________________________________
