### ISSUE TITLE
PEP 541 Request: sunlight

### ISSUE THREAD

**Issue by adriangb** [pypa/pypi-support#1574]
### Project to be claimed

`sunlight `: https://pypi.org/project/sunlight

### Your PyPI username

`adriangb `: https://pypi.org/user/adriangb

### Reasons for the request

Here are the reasons I believe this project is dead:

- There have been no releases since 2015 ([PyPi releases](https://pypi.org/project/sunlight/#history))
- There have been no commits since 2015 ([GitHub commits](https://github.com/sunlightlabs/python-sunlight/commits/master))
- There have been no issues opened since 2016 ([GitHub issues](https://github.com/sunlightlabs/python-sunlight/issues))
- The package sees about 0 downloads without mirrors ([PyPi stats](https://pypistats.org/packages/sunlight))
- Their webpage states that the company (Sunlight Labs) closed: https://sunlightfoundation.com/api/

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/sunlightlabs/python-sunlight

### Contact and additional research

I conducted the above research. The only contact info I found for maintainers was Twitter handles. I sent a tweet and will update if I hear back, but I believe the info above should be conclusive.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Please update the title of this request.

**Comment by adriangb** [comment]
Apologies! Missed that

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub users @jamesturk, @paultag, and @rshorey, that seem to be of the owners of the project.

**Comment by adriangb** [comment]
I forgot about this issue in the last couple months. To be honest I no longer am interested in  transferring the name, but if it's not being used it might still be nice to open it back up to the community.

**Comment by yeraydiazdiaz** [comment]
Thank you @rshorey, I'll close the transfer as @adriangb is no longer interested, but let me know if you need anything else from me.

**Comment by adriangb** [comment]
Thank you all for the effort you put in, apologies for the lack of communication
