### ISSUE TITLE
PEP 541 Request: Breve

### ISSUE THREAD

**Issue by adriangb** [pypa/pypi-support#1575]
### Project to be claimed

`Breve `: https://pypi.org/project/Breve

### Your PyPI username

`adriangb `: https://pypi.org/user/adriangb

### Reasons for the request

Here are the reasons I believe this project is dead:

- No releases since 2009: https://pypi.org/project/Breve/#history
- Homepage and author email point to a domain that is for sale
- Not even listed on PyPi stats, so presumably has had 0 downloads per month for years

### Maintenance or replacement?

Replacement

### Source code repositories URLs

On PyPi http://breve.twisty-industries.com is listed, but it's a dead link for me at least

### Contact and additional research

I could not find any valid contact info for the project owner

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Please update the title of this request, to include the project name.

**Comment by adriangb** [comment]
Apologies! Missed that

**Comment by adriangb** [comment]
I was able to track down the repo: https://github.com/cwells/breve/. From there I was able to get the author's GitHub profile and send an email. I will update if / when I hear back.

**Comment by adriangb** [comment]
The owner answered and agreed to release the name! I'll close this ticket. Sorry for the bother folks, it wasn't until the second time digging into the history that I was able to find live contact information.

**Comment by adriangb** [comment]
@cwells

**Comment by adriangb** [comment]
@pradyunsg , Cliff is the original author of the Breve package. They have agreed to transfer ownership, but unfortunately no longer have access to their PyPi account. Are you able to transfer ownership with Cliff's approval as a comment on this issue?

**Comment by cwells** [comment]
Hello,

I'm the owner of the PyPI project, but I no longer have access to the email address I used when creating the account.

I no longer maintain Breve, and am fine with this being transferred.

**Comment by cwells** [comment]
I just archived the Breve GH repository to help avoid confusion:

https://github.com/cwells/breve

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @cwells, transfer complete.
