### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lilohuang** [pypa/pypi-support#1577]
### PyPI Username

lilohuang

### Reason for request

Hi there, 

I lost my 2FA authentication app and not able to login to my account. Could you help me to recover this?

Thank you so much,
Lilo

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
