### ISSUE TITLE
PEP 541 Request: `quick`

### ISSUE THREAD

**Issue by PierreGuilmin** [pypa/pypi-support#1578]
### Project to be claimed

`quick`: https://pypi.org/project/quick/

### Your PyPI username

`PierreGuilmin`: https://pypi.org/user/PierreGuilmin/

### Reasons for the request

This project is not maintained and sources are unavailable (last released June 25th 2011).

### Maintenance or replacement?

Replacement

### Contact and additional research

We discussed by email with the package maintainer Javier Mansilla on June 29th 2021, who agreed to release the package name because the project is not used anymore. However, I didn't get any response afterward (I sent 3 other emails, on July 12th, October 5th and December 6th). I don't think he is receiving my emails anymore 🤷🏼‍♂️.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid, I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by PierreGuilmin** [comment]
Thank you!
