### ISSUE TITLE
Issue: Limit Request: Alyvix - 92MB

### ISSUE THREAD

**Issue by alyvix** [pypa/pypi-support#158]
**Alyvix**

https://pypi.org/project/alyvix/

**92MB**

**PyPI**

**Alyvix can use and test any desktop application using Computer Vision, we now use RNN and we have training data inside our new package**

**Comment by jamadden** [comment]
The limit for https://pypi.org/project/alyvix/ has been set to 100MB.

**Comment by alyvix** [comment]
Thank you very much!
