### ISSUE TITLE
Project Limit Request: openvisusnogui - 50 GB

### ISSUE THREAD

**Issue by scrgiorgio** [pypa/pypi-support#1582]
### Project URL

https://pypi.org/manage/project/openvisusnogui

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Please refer to:

https://github.com/sci-visus/OpenVisus
http://nationalsciencedatafabric.org/

### How large is each release?

300-400 MB
probably 5-8 artifacts for each commit

### How frequently do you make a release?

5/months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there! Appreciate your patience here -- this issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.

The project is currently at ~4-5 GB. That leads me to a few questions:

- Is this request still relevant?
- If you bundle other packages in your project.
- If you bundle example data in your project.

If there's no response in the next 4 weeks, I'll close this when I come back around. Feel free to open a new ticket then! :)

**Comment by pradyunsg** [comment]
Closing this due to lack of a response.
