### ISSUE TITLE
PEP 541 Request: django-rq-scheduler

### ISSUE THREAD

**Issue by cunla** [pypa/pypi-support#1585]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/django-rq-scheduler/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/cunla/

### Reasons for the request

The project is not actively maintained.  
See source [here](https://github.com/isl-x/django-rq-scheduler) with multiple simple pull requests that are not merged.
The last commit was 2 years ago and the latest version does not support Django 4.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/isl-x/django-rq-scheduler

### Contact and additional research

I have attempted to reach out to the original owner (chad@isl.co), as well as create issues and pull requests in the original repositories. No response and it looks like the domain points to an empty heroku page (https://isl.co/).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cunla** [comment]
Meanwhile, I already published a replacement here: https://pypi.org/project/django-rqscheduler4/
The [source code](https://github.com/cunla/django-rqscheduler) was updated with github actions, pyproject.toml and django4 support.

**Comment by yeraydiazdiaz** [comment]
Hello @cunla, I will now start the reachability process which will last up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by cunla** [comment]
Hi @yeraydiazdiaz, any update on this?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
