### ISSUE TITLE
File Limit Request: torch-habana - 1024 MB

### ISSUE THREAD

**Issue by HabDevops** [pypa/pypi-support#1586]
### Project URL

https://test.pypi.org/project/torch-habana

### Does this project already exist?

- [X] Yes

### New Limit

1024

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Forked https://pypi.org/project/torch/ package supporting Habana accelerators

### Reasons for the request

torch-habana is a forked [https://pypi.org/project/torch/](https://pypi.org/project/torch/) package supporting Habana accelerators, the wheel size would be similar to wheels hosted in https://pypi.org/project/torch/, which is close to 1 GB (Link to torch files: https://pypi.org/project/torch/#files)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've increased the upload limit for `torch-habana` to 1GB on TestPyPI.
