### ISSUE TITLE
PEP 541 Request: harmony

### ISSUE THREAD

**Issue by anthonyyangdev** [pypa/pypi-support#1587]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/harmony

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ayang4114

### Reasons for the request

The existing package has not been maintained/updated for at least 5 years on GitHub or GitLab. The email found in the `setup.py` file cannot be contacted.

We've implemented programming language also named [Harmony](http://harmony.cs.cornell.edu/). We would like to distribute the compiler via PyPi using the name `harmony` for students and other users.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/4degrees/harmony
https://gitlab.com/4degrees/harmony

### Contact and additional research

The email found in the user profile, Authors field, and `setup.py` file (`martin@4degrees.ltd.uk`) cannot be reached.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by kevinsun-dev** [comment]
To give more context to this request, [Harmony](https://harmony.cs.cornell.edu/) is a project initially started by [Prof. Robbert Van Renesse](https://www.cs.cornell.edu/home/rvr/) in 2019 as a python-like language to perform detailed model checking of distributed algorithms. It's currently used as part of Cornell University's CS4410 Operating Systems course, taken by hundreds of students each semester as a core class in the curriculum, with planned talks to expand to other courses and universities. We're launching the language as a pypi package to improve installation and ease of adoption.

Repository:
https://github.com/harmonylang/harmony

Documentation:
https://harmony.cs.cornell.edu/book.pdf
https://harmony.cs.cornell.edu/docs/reference/textbook/ (WIP)

**Comment by yeraydiazdiaz** [comment]
Hello @anthonyyangdev, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner and proceed with the transfer.

**Comment by martinpengellyphillips** [comment]
Hi, I'm the owner of the current Harmony package. I'm happy to transfer it. Let me know the next steps :)

**Comment by yeraydiazdiaz** [comment]
Thank you for your reply @martinpengellyphillips, I've transfered the project.

**Comment by anthonyyangdev** [comment]
Hi @martinpengellyphillips! Thank you so much for transferring it to us, we really appreciate it!

@yeraydiazdiaz Thank you for transferring the package in the main PyPi registry! For testing purposes, can you also transfer the package namespace in the test PyPi registry?

**Comment by yeraydiazdiaz** [comment]
Sure, I've set you as the owner of `harmony` in test.pypi.org as well.
