### ISSUE TITLE
PEP 541 Request: imc

### ISSUE THREAD

**Issue by afrendeiro** [pypa/pypi-support#1588]
### Project to be claimed

`imc`: https://pypi.org/project/imc

### Your PyPI username

`afrendeiro`: https://pypi.org/user/afrendeiro

### Reasons for the request

The `imc` package on PyPI (https://pypi.org/project/imc/) calculates the body mass index (BMI; index de massa corporal [imc] in Portuguese) using a single function with fairly straight forward combination of two numerical inputs: `BMI = weight / (height ** 2)`.
The package isn't maintained, the email of the author does not exist anymore (I tried contacting them) and has very few downloads (https://pypistats.org/packages/imc).

Since I'm developing a package for the analysis of a particular kind of biological data called imaging mass cytometry (imc; https://github.com/ElementoLab/imc) I'd like to claim the name for my project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ElementoLab/imc

### Contact and additional research

The response from the remote server was:554 5.7.1 <ojuara@araujo.com>: Recipient address rejected: user ojuara@araujo.com does not exist

---------- Forwarded message ----------
From: "André Rendeiro" <afrendeiro@gmail.com>
To: ojuara@araujo.com
Cc: 
Bcc: 
Date: Tue, 4 Jan 2022 19:18:37 -0500
Subject: imc package on PyPI
Hello,

I'm developing a package for the analysis of a particular kind of biological data called imaging mass cytometry (imc).
I see that you have deployed a 'imc' package on PyPI (https://pypi.org/project/imc/) which calculates a BMI in a single function, doesn't seem like it's maintained, and has very few downloads (https://pypistats.org/packages/imc).

I wonder if you would consider removing the package if it's indeed not being maintained and used?

Best wishes,
Andre

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @afrendeiro, I will consider the project _almost_ invalid as it has very little functionality, attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by afrendeiro** [comment]
@yeraydiazdiaz Thanks you!
