### ISSUE TITLE
Issue: PEP 541 Request: wagtail-draftail-snippet

### ISSUE THREAD

**Issue by adamghill** [pypa/pypi-support#159]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/wagtail-draftail-snippet

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/adamghill

**Reasons for the request**
I accidentally uploaded `wagtail-draftail-snippet` under my user account rather than my employer's account (`themotleyfool`). After I deleted the project from my account, it's still locked so I was hoping to release the project name, so I could re-upload it under the `themotleyfool` account. I will definitely use the test PyPI from now on to make sure I know which account gets used for the upload.

**Maintenance or replacement?**
Maintenance: https://github.com/themotleyfool/wagtail-draftail-snippet/

**Contact and additional research**
I was the previous user, so I was hoping this was possible to release the project name, but I understand if it isn't possible. Thank you in any case for all the work on PyPI!

**Comment by jamadden** [comment]
The PyPI admin console shows that project name as being available. It was removed from PyPI, and hence made available for anyone to claim, by `adamghill` at 2020-01-17 20:40:06.553164, about three minutes after it was created. All it should be necessary to do is upload *a new version* of the project from the desired account.

**Comment by adamghill** [comment]
Thank you so much for the information -- I didn't realize that all I needed to do was create a new version, but that worked (https://pypi.org/user/themotleyfool/)! Thanks again for all of your help.
