### ISSUE TITLE
PEP 541 Request: Storage

### ISSUE THREAD

**Issue by J0** [pypa/pypi-support#1591]
### Project to be claimed

`storage`: https://pypi.org/project/storage/

### Your PyPI username

`joellee`: https://pypi.org/user/joellee/

### Reasons for the request

We are the maintainers of the [python client libraries](https://github.com/supabase-community/supabase-py) for [Supabase](https://github.com/supabase/supabase) which is an open source firebase. As part of the client library, we implemented a `storage` client library. We would like to distribute the package via PyPi using the name `storage` to align with our conventions for `gotrue`,`realtime`, and `postgrest` this would make it easier for our users to install the library.

The existing package has not been maintained/updated for at least 5 years on GitHub or GitLab. We've reached out to the team via email and have yet to receive a response after four days.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current Owner:

https://github.com/OpenSRM/storage/

Repository which we are requesting the namespace for:

https://github.com/J0/storage-py

The repository is currently listed under my namespace but will be moved to the [Supabase Community](https://github.com/supabase-community/) once we've found a suitable PyPI namespace.

### Contact and additional research

We have opened an issue here:

https://github.com/OpenSRM/storage/

and also followed up with an email to the address listed on PyPI a few days back(w.r.t time this was posted):

![image](https://user-images.githubusercontent.com/8011761/148573100-85cf9643-2ce9-4bb1-891c-6a01fbe6c099.png)

Feel free to let us know if any further documentation is needed.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @J0, I have started the reachability process for your request which can last up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by J0** [comment]
Hey @yeraydiazdiaz 

No worries, totally understand. 

Thanks for looking into this!
