### ISSUE TITLE
File Limit Request: aymara - 300 MB

### ISSUE THREAD

**Issue by kleag** [pypa/pypi-support#1592]
### Project URL

https://pypi.org/project/aymara/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The LIMA linguistic analyzer was started in 2002 and is free software since 2014. It was rule-based and now includes deep learning-based modules. It is developed in C++. Its python binding, this project, was initialy just a wrapper executing the c++ native executable and was then changed to use a docker container. 
This new version is a real python binding based on manylinux_2_24. But as LIMA depends on several external libraries (Qt, boost, icu, tensorflow and soon libtorch), it must bring with it binary versions of all these libraries. This represent a large part of current 255 MB wheel (383 MB unziped).
The remaining unziped content (285MB) are mainly compiled linguistic resources and configuration files that can hardly be distributed separately. The main deep learning models are downloaded using an integrated script.

### Reasons for the request

I see no other reasonable way to distribute a working tool than to include all the necessary libraries. It ensures that it will run smoothly.
In the future, it should not increase too much in size as only the libtorch library should be added soon. In fact, some of the old rule-based libraries and resources will become obsolete and it should go down in size in the future.

All the dockerfiles allowing to build this project and thus other Qt and/or boost and/or icu, etc -based projects are made available here: https://github.com/aymara/lima/tree/master/continuous_integration (last changes are not pushed).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by kleag** [comment]
Since I submitted this request, I realized that shared libraries where duplicated in the wheel and that some of them could be striped. I corrected this problem and the wheel went down from 307 to 255 MB. So, I changed the request from 350 to 300 MB.

**Comment by pradyunsg** [comment]
Hiya! Appreciate your patience here -- this issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.

I have bumped the file size limit to 300 MB. Please be mindful of how often you cut releases and how many large release artifacts you have in each release. There's also a total project size limit of 10 GB. You're at ~100 KiB right now.

PS: I like what you've done with the logo, project name and the domain-specific words. :)

**Comment by kleag** [comment]
> Hiya! Appreciate your patience here -- this issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.
Hi, no problem with the delay. I was impatient but I know well the Free Software world, so I was not surprised.
> 
> I have bumped the file size limit to 300 MB. Please be mindful of how often you cut releases and how many large release artifacts you have in each release. There's also a total project size limit of 10 GB. You're at ~100 KiB right now.
Yes, we have the habit to give publish new packages with each commit to offer bug corrections and new features ASAP. We will have to do otherwise for the python binding.

> 
> PS: I like what you've done with the logo, project name and the domain-specific words. :)
Thank you :-)
