### ISSUE TITLE
File Limit Request: cpgames - 200 MB

### ISSUE THREAD

**Issue by CharlesPikachu** [pypa/pypi-support#1593]
### Project URL

https://pypi.org/project/cpgames/0.1.0/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is used to create interesting games by pure python, here is the repo of this project: https://github.com/CharlesPikachu/Games

I have made efforts to reduce the size of my PyPI releases. Since there are 27 games in this project, the game resources (e.g., music and images) is too many to reduce. 

### Reasons for the request

If I package the data (e.g., music and images), people can more easily run my project by simply using pip.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by CharlesPikachu** [comment]
any update?

**Comment by pradyunsg** [comment]
Hi there! Appreciate your patience here -- this issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.

I've bumped the limit to 200 MB. :)
