### ISSUE TITLE
File Limit Request: mindspore-gpu, mindspore-cuda11-dev - 500 MB

### ISSUE THREAD

**Issue by nicholasyanghaoran** [pypa/pypi-support#1594]
### Project URL

https://pypi.org/project/mindspore-gpu/ https://pypi.org/project/mindspore-cuda11-dev/

### Does this project already exist?

- [X] Yes

### New Limit

500MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.

### Reasons for the request

As mentioned in the previous issue https://github.com/pypa/pypi-support/issues/1474 , MindSpore was subject to further increase in package size, and now `mindspore-cuda11-dev` and `mindspore-gpu` have exceded the previous limit of 200MB due to recent addtion of features. 

I apologize for troubling you once again, but would like to apply for a further increase of size limit to 500MB per package. Our team will make sure to keep the package size limit under 500MB in the forseeable future. 

Thank you very much!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nicholasyanghaoran** [comment]
@pradyunsg sorry for interrupting again, could you please help take a look into this and the other issue #1595 ? Our GPU packages and CPU for Mac packages are exceeding our previously planned sizes as features are being added continuously. Thanks for considering my requests.

**Comment by pradyunsg** [comment]
Hi there! There's no need to @-mention me here -- it isn't going to speed things up -- I triage these tickets in bulk, when I have the free time to do so. This issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly. :)

> MindSpore was subject to further increase in package size

Could you provide more detail on what exactly changed for the MacOS wheels, that your wheels have doubled in size? If it's for uploading universal2 wheels, you might want to instead publish two separate wheels for arm vs not-arm.

**Comment by nicholasyanghaoran** [comment]
Hi, thanks for the reply, sorry for troubling you once again... Our CPU for Mac packages were a recent addition and changes are frequently being made, as we can see in the latest dev packages https://pypi.org/project/mindspore-dev/1.6.0.dev20220216/#files (thanks for approving the issue for dev packages!) we have noticed the abnormal size of Mac x86 packages and shrinked them down to ~110 MB, as compared to  ~90 MB for Mac arm and ~110 MB for other OS. The double-sized Mac x86 wheel you have seen was due to a mistake in the compile script, and is already fixed.

**Comment by pradyunsg** [comment]
I've bumped the limits for both projects to 500 MB.

Please be mindful of how often you make releases. FYI: Both projects are at ~3-4 GiB of the 10 GiB total project size limit.

**Comment by nicholasyanghaoran** [comment]
Thank you so much! We are trimming the outdated packages frequently, and considering to lower the frequency of publishing nightly packages, or publish nightly packages through our own servers, definitely not exceeding the size limit.
