### ISSUE TITLE
File Limit Request: mindspore-dev - 200 MB

### ISSUE THREAD

**Issue by nicholasyanghaoran** [pypa/pypi-support#1595]
### Project URL

https://pypi.org/project/mindspore-dev/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.

### Reasons for the request

As mentioned in the previous issue #1474 , MindSpore was subject to further increase in package size, and our preview  version `mindspore-dev` has recently exceeded the default package size limite of 100MB, due to addtion of MacOS versions, which is lightly larger than Linux and Windows packages (90MB-ish, has already been dangerously close to the size limit).

I apologize for troubling you once again, but would like to apply for a further increase of size limit to 200MB per package. This issue is filed separately from #1594 because MindSpore for CPU delivers fewer features as compared to GPU version, and we will make sure to keep the size limit for a long time.

Thank you very much!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limit increased to 200 MiB. Please be mindful of your release cadence, since the project is currently at ~6.2 GiB of the total project size limit (which is at 10 GiB currently).
