### ISSUE TITLE
PEP 541 Request: JaroWinkler

### ISSUE THREAD

**Issue by maxbachmann** [pypa/pypi-support#1596]
### Project to be claimed

`JaroWinkler`: https://pypi.org/project/JaroWinkler

### Your PyPI username

`maxbachmann`: https://pypi.org/user/maxbachmann

### Reasons for the request

The project was created in 2005 and has not seen any upload (even the initial release is empty).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/maxbachmann/JaroWinkler

### Contact and additional research

I could not find any contact for this user. This unmaintained project is the only project of this user, so it is likely that this account is not active anymore either.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @maxbachmann, the owner's email address is not longer active so I have transfered the project to you.
