### ISSUE TITLE
PEP 541 Request: postgrest

### ISSUE THREAD

**Issue by J0** [pypa/pypi-support#1598]
### Project to be claimed

`postgrest`: https://pypi.org/project/postgrest

### Your PyPI username

`joellee`: https://pypi.org/user/joellee

### Reasons for the request

Hey!

We are the maintainers of supabase-py which is the python client library for Supabase which is an open source Firebase. As Supabase also uses postgrest under the hood we also wrote a [python client library](https://github.com/supabase-community/postgrest-py/tree/master/postgrest_py) which has a substantial number of users. 

It seems like the [existing py-postgrest library](https://github.com/Kong/py-postgrest) might not be actively maintained given that the last commit was made with 2.5 years. 

To attempt to confirm this,  we took the following steps:

1. Email listed in setup.py -> It seems like the request was routed to a disposal email with the message:
> This account doesn't exist. Re: Enquiry About Status of Postgrest Python library

Perhaps the author might have left the org.

2. Filing an issue on the repository -> It seems like there was no response after about four days(as of time of posting)

We were hoping to take over the postgrest namespace to complement the convention of other libraries `realtime` , `supabase` , and `gotrue`. The library we are proposing as a replacement would have similar functions as the old library and functions as a client library for `postgrest`.

Let us know!

Joel

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/supabase-community/postgrest-py
https://github.com/Kong/py-postgrest

### Contact and additional research

![image](https://user-images.githubusercontent.com/8011761/148675966-72164683-3ef7-43cc-8f8d-a90e280135cd.png)
![image](https://user-images.githubusercontent.com/8011761/148675972-118f45e3-06dd-446e-939b-0c6ad152c13a.png)

https://github.com/Kong/py-postgrest/issues/8

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @J0, I have started the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by james-callahan** [comment]
Hi, I'm not longer at Kong.

I'm not sure who may still be using the library.

**Comment by yeraydiazdiaz** [comment]
Thank you for your reply @james-callahan, judging by the [low number of downloads](https://pypistats.org/packages/postgrest) I think it's safe to transfer the project, @J0 is now the owner.

**Comment by J0** [comment]
Thanks @yeraydiazdiaz !
