### ISSUE TITLE
PEP 541 Request: joy

### ISSUE THREAD

**Issue by Tinche** [pypa/pypi-support#1599]
### Project to be claimed

`joy`: https://pypi.org/project/joy

### Your PyPI username

`tinchester`: https://pypi.org/user/tinchester

### Reasons for the request

The PyPI project has no files whatsoever (`pip install joy` fails) or activity since 2016, so to me it looks like a simple squatting.

I would like to use the name for my next open source project, since I find it simple, easy to remember and evocative.

### Maintenance or replacement?

Replacement

### Contact and additional research

I have attempted contacting the owner using the email address from another one of their projects (https://pypi.org/project/rotest/) only to have it bounce (`5.1.0 - Unknown address error 553-'Inactive user gregoil'`).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @Tinche, the owner no longer has an active email address and since the project has no releases and thus is considered invalid I have transfered the project to you.

**Comment by Tinche** [comment]
Thank you!
