### ISSUE TITLE
PEP 541: Transfer ownership of unmaintained `dissect`

### ISSUE THREAD

**Issue by Schamper** [pypa/pypi-support#16]
I'd like to request ownership of the `dissect` package name to be transferred to the PyPI user [fox-it](https://pypi.org/user/fox-it/). I can provide proof of ownership of this user if necessary.

The last release on PyPI for `dissect` was on Jul 5, 2015, with the last activity on the GitHub repository on Mar 6, 2017. I've tried contacting the owner multiple times on various e-mail addresses and publicly on Twitter, but without success. Maybe a reach-out from PyPA is successful.

The reason for wanting this package name is that we (Fox-IT) have been building a lot of internal libraries under the `dissect` "namespace". When we started, this package didn't exist yet and we had no intentions of open-sourcing at the time. However, we're now in the process of preparing to open-source various projects under this namespace (for example, [dissect.cstruct](https://pypi.org/project/dissect.cstruct/)). 

I'm aware it's a single package right now, but we have multiple projects in the pipeline to be open-sourced. However, not controlling the `dissect` package on PyPI is somewhat of a show stopper for us publishing more libraries under this name. Since the current `dissect` package on PyPI hasn't been updated in a long time, we're first attempting it this way before we have to go and think of a different name.

I can provide more information on request, if necessary.

**Comment by Schamper** [comment]
Hi, just pinging again.

**Comment by yeraydiazdiaz** [comment]
Hi @Schamper as you can see in https://github.com/vivisect/dissect/issues/7 we've attempted contact with @invisig0th but got no answer, I will try contacting via email, if unsucessful we can assume the project is abandoned and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Hi @Schamper, I have had no response from the current owner of the project so it is now considered abandoned. I will now ask an admin to transfer the project to you.

**Comment by ewdurbin** [comment]
Transfer complete.
