### ISSUE TITLE
PEP 541 Request: beem

### ISSUE THREAD

**Issue by sicarius97** [pypa/pypi-support#1606]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/beem/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/sicarius

### Reasons for the request

The reason for this request is that beem has for quite some time been a vital library for many applications that interact with the hive blockchain. Unfortunately, there are problems with beem in its current state that are causing problems in apps spanning a whole ecosystem, and many app developers who depended on this library are now struggling to make or find alternatives to this library. There is a whole community of devs ready to step in and make fixes to this project, but it has seemingly been abandoned. For some time, the maintainer of the library has seemingly been absent from the project and after multiple attempts to contact the maintainer, Holgern, through various communication channels, I have received no response. Some fellow hive blockchain developers have also had the same issue.

Rather than fork and make an entirely new project, this community of developers would much rather maintain the project that is already being used across this ecosystem, which is why I decided to make this request. Ultimately, if we can't continue to improve and maintain this package, we will instead end up having to make a new one. We seemingly fit most of the requirements for a project being eligible for maintenance transfer and I personally have made a good amount of the most recent commits. I and a few other devs can supply improvements that have been pending having the owner review and merge branches to make said improvements that would hopefully fix this package's broken state.

Thank you in advance for taking a look into this issue and we hope to hear from pypi soon!

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

This is the original repository and the one the package is linked to: https://github.com/holgern/beem

This is a fork maintained by myself on openhive-network (an open source org that helps maintain various libraries in the hive community) that has a few hot fixes and is the go to for now since the pypi package is broken: https://github.com/openhive-network/beem

### Contact and additional research

For reference, various communication attempts, as far back as july of this last year:
![image](https://user-images.githubusercontent.com/73046273/149615150-174ae667-44c4-4c76-87d6-5c68a33975b9.png)

![image](https://user-images.githubusercontent.com/73046273/149615183-c78d704b-7beb-4600-97f5-6d82597932c0.png)

Proof of community interest and other devs noting the same issue:
![image](https://user-images.githubusercontent.com/73046273/149615220-52c6c00f-4ae9-41c4-9238-555f93394c7d.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sicarius97** [comment]
@yeraydiazdiaz If you have a moment to review this request, that would be absolutely fantastic. There are quite a few apps depending on this package currently experiencing issues from bugs that could be resolved fairly quickly, but not without being able to update this project and cut a new release

**Comment by yeraydiazdiaz** [comment]
Hello @sicarius97, I have started the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied to my email and said they would add you as a maintainer soon. I'll keep the request open in the meantime as a reminder.

**Comment by yeraydiazdiaz** [comment]
The owner has not yet added more maintainers to this project but since he did reply to my email the project is not abandoned and cannot be transferred. Hopefully the owner will have some time to add more maintainers soon.
