### ISSUE TITLE
PEP 541 Request: dcm2niix

### ISSUE THREAD

**Issue by casperdcl** [pypa/pypi-support#1609]
### Project to be claimed

`dcm2niix`: https://pypi.org/project/dcm2niix

### Your PyPI username

`Casper.dcl`: https://pypi.org/user/Casper.dcl

### Reasons for the request

- The package is not claimed on PyPI
- [There is an error when attempting to claim the package on PyPI](https://github.com/rordenlab/dcm2niix/pull/573#discussion_r785302639) - presumably as an automated precaution because it's [claimed on conda-forge](https://github.com/conda-forge/dcm2niix-feedstock)?
- The maintainer @neurolabusc (of both source package & conda-forge feedstock) has [requested me to claim/maintain the PyPI name](https://github.com/rordenlab/dcm2niix/pull/573#issuecomment-1014629292)

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/rordenlab/dcm2niix

### Contact and additional research

See https://github.com/rordenlab/dcm2niix/pull/573 for discussion with the maintainers of `dcm2niix`. There does not appear to be a current owner of the PyPI name to contact.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by neurolabusc** [comment]
@ casperdcl thanks for taking the lead on this. As lead developer of this community driven project, I fully endorse this request.

**Comment by yeraydiazdiaz** [comment]
Hello @casperdcl, the project name `dcm2niix` was placed in the prohibited project names list. @pypa/warehouse-admins could you release the project name, please?

**Comment by ewdurbin** [comment]
Released to `Casper.dcl` User on PyPI.
