### ISSUE TITLE
PEP 541 Request: magpy

### ISSUE THREAD

**Issue by EddyCMWF** [pypa/pypi-support#1612]
### Project to be claimed

`magpy`: https://pypi.org/project/magpy

### Your PyPI username

`EddyCMWF`: https://pypi.org/user/EddyCMWF

### Reasons for the request

The magpy project has been abandoned: It does not point to any github source code, and it never has done. Additionally, there is no author information available to contact the author to request a transfer.
I have searched the issue board and did not find any issues related to the magpy project, therefore I think I must be the first user to request the project namespace.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ecmwf/ecmwf-geomaps
This repository will be renamed to magpy if this change of ownership request is successful

### Contact and additional research

There was no contact information either on the project or the maintainer's profile page.
The project dos not point to any source code.

Our proposed project is for a python implementation of the widely used Magics plotting software, supported by ECMWF.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @EddyCMWF, I can confirm the project has a single release with no files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
