### ISSUE TITLE
PEP 541 Request: speck

### ISSUE THREAD

**Issue by tgamblin** [pypa/pypi-support#1615]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/speck

### Your PyPI username

`USER_NAME`: https://pypi.org/user/tgamblin

### Reasons for the request

I'm looking into options for renaming another project that has a name some consider offensive.  `speck` is pretty close to that project's name and would be easy for users to migrate to.

`speck` on PyPI hasn't had a release since 2012, and the code doesn't look to have progressed since then.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/vaz/speck

### Contact and additional research

I have tried reaching out to @vaz on codementor.io (https://www.codementor.io/@vazallen) but he did not respond to several attempts to schedule a short session to chat.  His twitter appears to be inactive.  Not sure how best to reach him, so pinging him here.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by vaz** [comment]
Hi @tgamblin. Sorry I wasn't so easy to get ahold of. I'm totally fine with this, that project was really just an experimental thing from way back when. I deleted in PyPI so the name is yours if you want it.

**Comment by tgamblin** [comment]
That was easy!  Thanks @vaz!
