### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Kenny2github** [pypa/pypi-support#1617]
### PyPI Username

`kenny2pip`

### Reason for request

Lost 2FA authentication app when the phone that had the app bricked. I had not had the foresight to generate recovery codes. Will do so upon regaining access.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Kenny2github** [comment]
Replied to email, thank you!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
