### ISSUE TITLE
PEP 541 Request: spack

### ISSUE THREAD

**Issue by tgamblin** [pypa/pypi-support#1619]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/spack

### Your PyPI username

`USER_NAME`: https://pypi.org/user/tgamblin

### Reasons for the request

Spack (https://github.com/spack/spack) is a large community project with thousands of users, and is currently the number 3 HPC project on GitHub (per https://github.com/topics/hpc). We'd like to be able to use the `spack` name on PyPI.  We have traditionally not had a PyPI package, because you can just close Spack and it works out of the repo. However, we'd like to make it available in more ways, and getting the name makes sense at this point.

Spack on PyPI (https://pypi.org/project/spack/) is a cool sphere packing project. However, the last release was in 2016, and development looks like it stopped at the same time.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

* Spack the package manager: https://github.com/spack/spack
* Spack the sphere packer: https://github.com/wackywendell/spack

### Contact and additional research

@wackywendell was nice enough to give us https://spack.readthedocs.io years ago, but I wasn't able to get in touch with him about the PyPI name after that (no response).  I'd like to pick that discussion up again, as a lot of time has passed and Spack (the package manager) has grown a lot.  I am not sure of his current contact info save for pinging him on here, so sorry in advance for the noise.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @tgamblin, I will now start the reachability process for your request which can last up to 6 weeks, hopefully we will hear back from the owner and proceed with the transfer soon.

**Comment by tgamblin** [comment]
Thanks!

**Comment by wackywendell** [comment]
Hello! Thanks for reaching out. After some thought, it seems reasonable to transfer over; as noted, I haven't worked on my spack project for some time, and if there are other users of it out there, they are probably few and far enough between to survive a pypi name change.

@yeraydiazdiaz - how do we proceed from here?

**Comment by pradyunsg** [comment]
@wackywendell You should be able to log into PyPI, go to [the relevant project's page](https://pypi.org/project/spack), click manage project, and add @tgamblin as a owner on the project in the management section. I think there's an extra click somewhere in this process, that I might be missing.

**Comment by yeraydiazdiaz** [comment]
Hi @wackywendell, thanks for your reply, I've transferred the project to @tgamblin as requested.

**Comment by tgamblin** [comment]
Thanks @yeraydiazdiaz!

@wackywendell I will probably delete the old releases but let me know if you want me to help with moving them to some new name.  I'm happy to do that.

**Comment by wackywendell** [comment]
Hi! Thanks for taking care of this, all. @tgamblin you can leave them be - no need to worry here.
