### ISSUE TITLE
PEP 541 Request: urllib3 (test.pypi.org)

### ISSUE THREAD

**Issue by sethmlarson** [pypa/pypi-support#1620]
### Project to be claimed

urllib3

### Your PyPI usernames

shazow
SethMichaelLarson

### Reasons for the request

urllib3 name is owned on `pypi.org` and we would like to use `test.pypi.org` to test our package builds.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/urllib3/urllib3

### Contact and additional research

Haven't contacted the author, the name was uploaded to once and hasn't been uploaded in 4 years.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hey @sethmlarson, I've set you as the owner of the project in PyPI but `shazow` is not registered in test.pypi.org with that name. You'll have to add him yourself once he confirms his username.

**Comment by sethmlarson** [comment]
Thanks @yeraydiazdiaz!
