### ISSUE TITLE
File Limit Request: ACAT - 200 MB

### ISSUE THREAD

**Issue by shuanghan6848** [pypa/pypi-support#1626]
### Project URL

https://pypi.org/project/acat/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

ACAT is a Python package for atomistic modelling of metal or alloy catalysts used in heterogeneous catalysis, and it has been active for 9 months. The package is based on automatic identifications of adsorption sites and adsorbate coverages on surface slabs and nanoparticles. ACAT provides useful tools for building atomistic models of alloy catalysts with and without adsorbates. The goal is to automate workflows so that the structure generations can be readily adapted in a high-throughput screening. 

I have tried to reduce the size of the package, but the size keep growing since the code is still under active development. The project is not bundled with other packages.

### Reasons for the request

Since I am still actively adding features to the package, the package is bound to exceed the 100 MB limits. The size of the file is now 102 MB, which I already cannot upload to PyPI. I want to request 200 MB limit, so that I can add more features in the developing. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hiya! Your distributions have the generated HTML for the documentation, as well as the __pycache__ directories.

Please create a .gitignore file in the repository root (i.e. beside the setup.py file) with the cotnents from https://github.com/github/gitignore/blob/main/Python.gitignore and then run:

```
git rm -r --cached . 
git add .
git commit -am "Remove ignored files and resubmitting files"
```

After that, please create a MANIFEST.in file (again, beside the setup.py file) and add the following content to it:

```
prune docs/_build/
```

For more on MANIFEST.in files, please read https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/#non-code-files.

With all this, you should have smaller distribution sizes and shouldn't need this size increase. :)
