### ISSUE TITLE
PEP 541 Request: versioncontrol

### ISSUE THREAD

**Issue by bittner** [pypa/pypi-support#1627]
### Project to be claimed

`versioncontrol`: https://pypi.org/project/versioncontrol

### Your PyPI username

`bittner`: https://pypi.org/user/bittner

### Reasons for the request

The PyPI package name `versioncontrol` is one of the numerous names grabbed by the namesquatter `Collie`. This has been reported in #791 over a year ago and is still unresolved as a PyPI abuse case. According to the comments in that issue, the user seems to continue using the account for grabbing more package names on PyPI for no specific reason, just like other people do for domain parking.

I'd like to use the package name for an abstraction layer package to operate the public APIs of various source code version control services (GitHub, GitLab, Bitbucket) that I wrote a few years ago and open sourced the code 3 years ago. I now have a need to use that code in a bigger project and would like to keep it cleanly separate (maintainable) and installable from PyPI.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/painless-software/python-versioncontrol

### Contact and additional research

The PyPI user's (Collie) projects seem to all have an empty email address specified, intentionally. The likewise named GitHub, Twitter and LinkedIn users don't seem to correlate with that user or don't exist.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by bittner** [comment]
Thank you! :1st_place_medal:
