### ISSUE TITLE
PEP 541 Request: kotko

### ISSUE THREAD

**Issue by kotko** [pypa/pypi-support#1629]
### Project to be claimed

https://pypi.org/project/fake-requirement-for-unit-tests

### Your PyPI username

https://pypi.org/user/kotko

### Reasons for the request

As far as I understand, the project has no releases
I would like to have this name

### Contact and additional research

I don't know how to contact him

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @kotko, the project name was placed in the prohibited project names list, could you provide a repository of the code you intend to release under that name?

**Comment by yeraydiazdiaz** [comment]
@kotko are you still interested in this transfer? If so, could you provide the repository for the project you intend publish?

**Comment by yeraydiazdiaz** [comment]
Closing for housekeeping, feel free to reopen if you're still interested.
