### ISSUE TITLE
name transfer request for 'decred'

### ISSUE THREAD

**Issue by buck54321** [pypa/pypi-support#163]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/Decred

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/tinydecred

**Reasons for the request**

The repo has no functionality. It will be 12 months since the last activity, but it likely doesn't need to meet reachability and abandonment requirements because 1) it has no author information in either PyPI or the placeholder files and 2) it appears to meet the [**invalid project**](https://www.python.org/dev/peps/pep-0541/#invalid-projects) name-squatting case

> project is name squatting (package has no functionality or is empty)

**Maintenance or replacement?**

This will be the package for the Decred Python toolkit, from https://github.com/decred/tinydecred. 

**Contact and additional research**

Project author has deleted their PyPI account. The placeholder package files have no additional information.

**Comment by yeraydiazdiaz** [comment]
Hello @buck54321, the current owner is `deleted-user` which is a fake user admin assign project to when consiered invalid.

I will now ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
Transfer complete.
