### ISSUE TITLE
Project Limit Request: torch - 160 GB

### ISSUE THREAD

**Issue by seemethere** [pypa/pypi-support#1630]
### Project URL

https://pypi.org/project/torch

### Does this project already exist?

- [X] Yes

### New limit

160

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[PyTorch](https://pypi.org/project/torch) is a Python package that provides two high-level features:

Tensor computation (like NumPy) with strong GPU acceleration
Deep neural networks built on a tape-based autograd system

### How large is each release?

~ 6GB in total

4 linux wheels
4 windows wheels
8 macos wheels (intel + m1)

### How frequently do you make a release?

Every quarter, sometimes multiple times per quarter depending on patch releases

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by seemethere** [comment]
cc @rgommers

**Comment by seemethere** [comment]
We've landed on removing all pre-1.0 pytorch binaries from pypi which should give us enough headroom for 1.10.2 for now but yeah it'd be nice to have more headroom for future releases

**Comment by ewdurbin** [comment]
This limit request has been approved.
