### ISSUE TITLE
Project Limit Request: glaxnimate - 200 MB

### ISSUE THREAD

**Issue by mbasaglia** [pypa/pypi-support#1632]
### Project URL

https://pypi.org/project/glaxnimate/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Gives access to utilities to edit / create vector animation files.

### Reasons for the request

I want to include binary modules for Python 3.8, 3.9, 3.10 in the manylinux wheel. it's fine for only 2 versions but with all 3 it goes over the limit

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
> it's fine for only 2 versions but with all 3 it goes over the limit

That shouldn't be the case. The limit is per-file, at a 100 MB/file. Can you confirm whether any of your project's individual distribution files are more that 100 MB in size?

**Comment by mbasaglia** [comment]
I have gotten that error from my CI system: https://gitlab.com/mattbas/glaxnimate/-/jobs/2031169432#L5230

**Comment by pradyunsg** [comment]
I've gone ahead and increased the limit to 200 MB.
