### ISSUE TITLE
PEP 541 Request: numpy-aarch64

### ISSUE THREAD

**Issue by rgommers** [pypa/pypi-support#1635]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/numpy-aarch64

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rgommers

### Reasons for the request

1. The `numpy-aarch64` package claims to provide _official_ numpy binaries and lists the NumPy developers as authors. This package is not created by the NumPy developers, it's uploaded by a random person we don't know. This is clearly also a security issue.
2. I managed to find the repository associated with this package, filed an issue there to ask for removal of `numpy-aarch64`, and documented that in [this numpy mailing list message](https://mail.python.org/archives/list/numpy-discussion@python.org/message/5XCG2BKBPN2THALOVRMQ63Y2B5FKTH7D/). In response the author seems to have deleted his repository without replying, which is not a good faith response.

### Maintenance or replacement?

Once I get access to the package on PyPI, I intend to delete the one existing wheel and replace its README with a notice to use `numpy` instead (it provides `aarch64` wheels) and if someone used `numpy-aarch64` before they should realize it may have contained malicious code and should act accordingly.

### Source code repositories URLs

The repo was at https://github.com/tomasriv/DNA_Sequence, now deleted

The official NumPy repo is at https://github.com/numpy/numpy/

### Contact and additional research

I managed to find the repository associated with this package, filed an issue there to ask for removal of `numpy-aarch64`, and documented that in [this numpy mailing list message](https://mail.python.org/archives/list/numpy-discussion@python.org/message/5XCG2BKBPN2THALOVRMQ63Y2B5FKTH7D/). In response the author seems to have deleted his repository without replying, which is not a good faith response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @rgommers, I've transferred the project to you. There seems to be [very few downloads](https://pypistats.org/packages/numpy-aarch64) of this package so if you prefer we could place it in the prohibited project names list.

**Comment by rgommers** [comment]
Thanks @yeraydiazdiaz!

> so if you prefer we could place it in the prohibited project names list.

This is not necessary. I have deleted the one release of the project, and I'll remain the sole owner of this project now, so it's no longer a risk for anyone.
