### ISSUE TITLE
PEP 541 Request: mmcif and other related projects

### ISSUE THREAD

**Issue by epeisach** [pypa/pypi-support#1638]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mmif

### Your PyPI username

`USER_NAME`: https://pypi.org/user/epeisach

### Reasons for the request

The owner of this project on pypi, John Westbrook, died in October 2021.

See notice at https://www.rcsb.org/news/feature/61787050ef055f03d1f22329

John was a member of both RCSB and wwPDB and developed a number of packages that are on pypi in which he is the sole owner.  

This is a request to add owners to the 30+ packages that he the sole owner.  As the development Is in an organization space on GitHub, we can change the ownership there, but not on PyPi.

I placed a request under the recover account in at the end of December but have not heard back in four weeks. 

How can we change the ownership of these packages to add current members of the organization.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/rcsb/py-mmcif
https://github.com/wwPDB/py-wwpdb_utils_align
and about 30 more...

### Contact and additional research

As a co-worker at RCSB, I attended his memorial service and spoke to his wife.  He is not able to respond to email.

That said, at the organization, we are still monitoring he email - and a message sent there (@rcsb.org or @rcsb.rutgers.edu email address) could get a response.

If you require other documentation, I am sure we could arrange.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Closing since #1573 covered this, I believe.
