### ISSUE TITLE
PEP 541 Request: pybuild

### ISSUE THREAD

**Issue by bryantbiggs** [pypa/pypi-support#1639]
### Project to be claimed

`pybuild`: https://pypi.org/project/pybuild

### Your PyPI username

`clowdhaus`: https://pypi.org/user/clowdhaus

### Reasons for the request

Hello - I reached out to the (previous) owner of the `pybuild` namespace on PyPI asking if they intended to use it. The project did not appear to have any source code related to it or deployments; it was last updated in 2016. The author obliged by deleting the package from their account and it now shows up on the index as not found - however I am unable to claim it and I am receiving the error `400 The name 'pybuild' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.`

I would like to request ownership of the package name `pybuild` please. I also have the email correspondence between myself and the previous package holder as well - see screenshot provided below.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The project is slated for release in late February and the source code on GitHub is not publicly accessible yet. However, here is the link https://github.com/serverless-delivery/pybuild

And screenshot:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/10913471/151871319-268ae98d-63c6-43c6-a80f-fc593d6e5bcd.png">

### Contact and additional research

Previous package owner https://github.com/szabolcsdombi

Screenshot of email correspondence:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/10913471/151871482-e778d77b-6ec9-417f-a796-b794d5a91eea.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by bryantbiggs** [comment]
🙏🏽 😬

**Comment by bryantbiggs** [comment]
is there anything else I can help provide for this @pradyunsg / @yeraydiazdiaz / @ewdurbin ? thank you

**Comment by ewdurbin** [comment]
Hi @bryantbiggs this project name is easily confused with the existing project https://pypi.org/project/py-build/, our policy is not to allow new project registration where the name may be easily confused due to the prevalence of typosquatting/dependency confusion on PyPI lately.

**Comment by yeraydiazdiaz** [comment]
Hi @bryantbiggs, unfortunately the previous owner _deleted_ the project, rather than transferring it to you. Which means you'd need to create new package with that name which PyPI now refuses, if he had transferred it both projects would be able to coexist as before.

I'm sorry for the inconvenience but I don't think there's anything we can do at this point, maybe @pypa/warehouse-admins know of a potential solution that I don't.

**Comment by ewdurbin** [comment]
Thanks for investigating the details @yeraydiazdiaz. The project has been released to the `clowdhaus` User on pypi.org

**Comment by bryantbiggs** [comment]
thank you both - I was able to claim the project today 🎉 - have a great weekend!
