### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Ayehavgunne** [pypa/pypi-support#164]
Request for account recovery.

## PyPI Username

`ayehavgunne`

---

##  Reason for request

Reason:
Got new phone, forgot to set up authenticator.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete.

2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
