### ISSUE TITLE
PEP 541 Request: rsocket

### ISSUE THREAD

**Issue by OlegDokuka** [pypa/pypi-support#1641]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/rsocket

### Your PyPI username

`USER_NAME`: https://pypi.org/user/rsocketbot

### Reasons for the request

The last maintainer of [rsocket-py](https://github.com/rsocket/rsocket-py) (a.k.a @vjn) project is completely unavailable and the project was in an unmaintained state since 2017. We restarted the maintenance of the codebase and we hope we can have ownership on the PyPi package transferred as well so we don't have to create a new separate similar (e.g. rsocket-py) package name to start publishing new packages.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/rsocket/rsocket-py

### Contact and additional research

We don't have the email of the previous maintainer so the only way to ping him was via LinkedIn (see image below) but with no success.
![image](https://user-images.githubusercontent.com/5380167/151978327-4aad68ba-c2a2-4eba-a186-4d3dd10dbeee.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by gabis-precog** [comment]
Related request #1658 (same developer, different package)

**Comment by yeraydiazdiaz** [comment]
Hi @OlegDokuka, I have now started the reachability process for your request which can take up to 6 weeks. Hopefully the owner will reply soon and we can proceed with the transfer.

**Comment by OlegDokuka** [comment]
> Hi @OlegDokuka, I have now started the reachability process for your request which can take up to 6 weeks. Hopefully the owner will reply soon and we can proceed with the transfer.

We will appreciate a fast line taking ito account that we are already waiting there for 2 months

**Comment by yeraydiazdiaz** [comment]
@OlegDokuka I apologise for the delay but this is a community effort driven by volunteers such as myself. I tackle each request in turn when I have time to do so. Moderators are obliged to follow the PEP which [explictly states we must attempt contact for 6 weeks](https://peps.python.org/pep-0541/#reachability), there is no 'fast line'.

**Comment by OlegDokuka** [comment]
> @OlegDokuka I apologise for the delay but this is a community effort driven by volunteers such as myself. I tackle each request in turn when I have time to do so. Moderators are obliged to follow the PEP which [explictly states we must attempt contact for 6 weeks](https://peps.python.org/pep-0541/#reachability), there is no 'fast line'.

We all are doing so called 'community effort'. I'm just emphasizing the time spans, as well as the others facts like 'no response' from the original.

Best,
Oleh

**Comment by vjn** [comment]
Sorry for the delay in responding to this. I am completely in agreement with the transfer, so users can use the rsocket name itself, rather than the rsocket-py alternative. Please do effect the transfer. Thank you!

**Comment by yeraydiazdiaz** [comment]
Thank you for your reply @vjn, transfer complete.
