### ISSUE TITLE
Project Limit Request: aws-cdk-lib - 20 GB

### ISSUE THREAD

**Issue by madeline-k** [pypa/pypi-support#1642]
### Project URL

https://pypi.org/project/aws-cdk-lib/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

aws-cdk-lib is the second major version of the aws-cdk. It bundles all aws-cdk modules into a single library, which makes the package size much larger than in the first major version. Project on github: https://github.com/aws/aws-cdk 

We started releasing aws-cdk-lib weekly since 01/21/2021, and the total size of all published artifacts is 5.6 GB. The current package size is 60 MB, and we expect that to remain the same, or decrease. With the current size and release cadence, we will hit the 10 GB limit within the year, so requesting an increase. 

### How large is each release?

~60 MB

Python source files
~55 MB - A package that bundles all of the JavaScript code that the python source calls through a technology called JSII. This package is essentially the aws-cdk-lib npm package, which contains some bundled dependencies including the AWS CLI, and Kubectl. We are currently working on a project to stop bundling some of these dependencies, but the package will always require the JavaScript bundle, because of how the library is designed. 

### How frequently do you make a release?

once per week

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by madeline-k** [comment]
Hello @pradyunsg, I saw that you approved my other request that was similar to this one - https://github.com/pypa/pypi-support/issues/1643 - Any chance you can take a look at this one as well? Thank you!

**Comment by pradyunsg** [comment]
Hi there! There's no need to @-mention me here -- it isn't going to speed things up -- I triage these tickets in bulk, when I have the free time to do so. This issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.

Approving this, although (a) the project is at 5.6 GB right now and (b) you may want to consider reducing your release frequency. I'll likely defer larger requests to the PyPI admins. :)

From the README:

> Upload limits are generally denied for the following reasons:
>
>    project makes nightly releases and/or is published frequently
