### ISSUE TITLE
Project Limit Request: monocdk - 20 GB

### ISSUE THREAD

**Issue by madeline-k** [pypa/pypi-support#1643]
### Project URL

https://pypi.org/project/monocdk/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

monocdk is an experimental module in CDK v1 that bundles all aws-cdk modules into a single library. monocdk was first published on 10/7/2020, and has been released weekly since then. 

The total size of all published artifacts is ~8.6 GB. With the current size and release cadence, we will hit the 10 GB limit, so requesting an increase. 

### How large is each release?

~67 MB

Python source files
~55 MB - A package that bundles all of the JavaScript code that the python source calls through a technology called JSII. This package is essentially the aws-cdk-lib npm package, which contains some bundled dependencies including the AWS CLI, and Kubectl. We are currently working on a project to stop bundling some of these dependencies, but the package will always require the JavaScript bundle, because of how the library is designed. 

### How frequently do you make a release?

Once a week.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Approved!
