### ISSUE TITLE
Project Limit Request: construct-hub - 20 GB

### ISSUE THREAD

**Issue by RomainMuller** [pypa/pypi-support#1644]
### Project URL

https://pypi.org/project/construct-hub/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is the CDK Construct Library used to manage the https://constructs.dev website. Users can leverage that same library to host a private instance of ConstuctHub (for example, to index & aggregate company-internal construct libraries for their internal developer community).

We release ConstructHub almost on every commit to GitHub in a fully automated manner. We consequently expect our project size to continue growing at a similar pace in the future.

### How large is each release?

At present, releases are a little under 30MB each.

The library is a `jsii`-generated package, which includes an NPM package tarball (containing the JS version of that same library), and python bindings around those. The JS version of the library also includes the source code for the react front-end of the website.

### How frequently do you make a release?

We release ConstructHub almost on every commit to GitHub in a fully automated manner. There is no set cadence per se. Our release frequency so far should be a decent indication of future release frequency.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I'm approving this, somewhat tentatively. Please be mindful of your release frequency and consider reducing the frequency of releases. I'll likely defer any larger requests to the admins.

From the README:

> Upload limits are generally denied for the following reasons:
>
>    project makes nightly releases and/or is published frequently
