### ISSUE TITLE
PEP 541 Request: pycea

### ISSUE THREAD

**Issue by kovar** [pypa/pypi-support#1645]
### Project to be claimed

`pycea`: https://pypi.org/project/pycea

### Your PyPI username

`kovar`: https://pypi.org/user/kovar

### Reasons for the request

Hello 👋 I would like to start a new open source project called `pycea`. However, the name is taken by a mass name squatter (reported here https://github.com/pypa/pypi-support/issues/1610). The current project contains some random code and its homepage is linked to a non-existent GitHub repository.

I am hoping this single name request can be resolved faster as I understand that the mass name squat issue https://github.com/pypa/pypi-support/issues/1610 is probably more difficult to deal with. Thank you for your consideration.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/kovar/pycea

### Contact and additional research

I did not manage to find any contacts for the owner, but I believe his GitHub account is https://github.com/thorwhalen/.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
