### ISSUE TITLE
Project Limit Request: playwright - 100 GB

### ISSUE THREAD

**Issue by mxschmitt** [pypa/pypi-support#1646]
### Project URL

https://pypi.org/project/playwright/

### Does this project already exist?

- [X] Yes

### New limit

100GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Playwright is a library to automate Chromium, Firefox, and WebKit with a single API. It provides it in a sync and in an async API manner. Usually it gets used with [`pytest-playwright`](https://github.com/microsoft/playwright-pytest) to perform end-to-end tests of web-applications.

### How large is each release?

It contains a driver per wheel which ends up in that large size. The driver is currently a Node.js binary + upstream Playwright Node.js library / driver code. We thought about hosting the driver externally and downloading it on demand, but thought this is a bad practise in the Python/PIP ecosystem. (if you think different on how we should distribute let us know!)

We'll work on reducing the driver size in the future (by compiling Node.js manually without some modules we could reduce it probably by 50%). Also we're working on reducing the amount of files, but thats not a limitation in this case.

```
playwright-1.18.1-py3-none-win_amd64.whl (27.6 MB view hashes)
playwright-1.18.1-py3-none-win32.whl (27.6 MB view hashes)
playwright-1.18.1-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (33.3 MB view hashes)
playwright-1.18.1-py3-none-manylinux1_x86_64.whl (33.4 MB view hashes)
playwright-1.18.1-py3-none-macosx_11_0_universal2.whl (31.1 MB view hashes)
playwright-1.18.1-py3-none-macosx_11_0_arm64.whl (29.6 MB view hashes)
playwright-1.18.1-py3-none-macosx_10_13_x86_64.whl (31.1 MB view hashes)

-> usual release size: ~ 214 MB
```

### How frequently do you make a release?

We usually make a minor release every month which includes 1-2 additional patch releases.

-> 3 releases per month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hiya!

How big are the bundled binaries of playwright?

At 100 GB, this would be the 12th highest limit on PyPI: https://pypi.org/stats/

> We thought about hosting the driver externally and downloading it on demand, but thought this is a bad practise in the Python/PIP ecosystem. (if you think different on how we should distribute let us know!)

I don't think it's a bad practice! See https://www.nltk.org/data.html for example, although their data needs are likely in a slightly different class from yours. :)

**Comment by mxschmitt** [comment]
Hi! Thank you for your fast response.

> How big are the bundled binaries of playwright?

```
 90M    driver/linux-amd64
 89M    driver/linux-arm64
 95M    driver/mac-amd64
 86M    driver/mac-arm64
```

and compressed / zipped usually a third of that size.

100 GB was definitely a very provokative request. I think 20 or 30 GB would help already a lot. I mitigated it for now by deleting old unsupported versions (before we initially released this project to the public). But I can't continue doing this of course.

**Comment by pradyunsg** [comment]
Bumped the limit to 25 GB. :)

**Comment by mxschmitt** [comment]
@pradyunsg thank you so much!
