### ISSUE TITLE
PEP 541 Request: connexion TestPyPI

### ISSUE THREAD

**Issue by RobbeSneyders** [pypa/pypi-support#1647]
### Project to be claimed

connexion: https://test.pypi.org/project/connexion/

### Your PyPI username

RobbeSneyders: https://test.pypi.org/user/RobbeSneyders/

### Reasons for the request

I am an owner of the connexion project on PyPI. We would like to use TestPyPI in our release automation, but the connexion project on TestPyPI has been claimed by a different user.

### Source code repositories URLs

https://github.com/zalando/connexion

### Contact and additional research

I could not find any contact details or related github profile for the owner of the TestPyPI project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
