### ISSUE TITLE
Project Limit Request: Home Assistant Frontend - 50 GB

### ISSUE THREAD

**Issue by balloob** [pypa/pypi-support#1648]
### Project URL

https://pypi.org/manage/project/home-assistant-frontend

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Home Assistant is an open source home automation platform: https://pypi.org/project/homeassistant/. In 2020 it was the 2nd most active Python project on GitHub (according to GitHub State of the Octoverse).

Home Assistant exists of a server and a frontend. The server is in Python and the frontend is JavaScript. The frontend is needed to control Home Assistant.

To make our maintenance easier we have split the frontend out of the backend code and publish it as separate Python project and include it as a requirement to Home Assistant.

### How large is each release?

~33MB except for the last one.

Note: The last release was twice the size because it included a wheel after we updated our build system. It will be back to 33MB as we will drop the source distribution and just upload the wheel.

### How frequently do you make a release?

~8 per month

- Home Assistant does a major release a month.
- Some new builds during betas with fixes
- Some new builds during hotfixes

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
50,000 / (40 * 8) / 12 ~= 13 -- looks like this limit will serve HA for about 13 years, assuming things don't drastically change sizes. Seems reasonable to me, so I've bumped this limit as requested. :)

**Comment by balloob** [comment]
Thank you!

**Comment by balloob** [comment]
Sorry to disturb this old issue, but we hit the same issue on our other package. Tracking it #1819. Would really appreciate if you find the time to take a look 🙏
