### ISSUE TITLE
PEP 541 Request: keylime (Fedora reservation)

### ISSUE THREAD

**Issue by THS-on** [pypa/pypi-support#1649]
### Project to be claimed

`keylime`: https://pypi.org/project/keylime

### Your PyPI username

`THS`: https://pypi.org/user/THS

### Reasons for the request

We (the Keylime team) want to upload Keylime to PyPI, so that it can also be installed that way and easily be used as a library.

The name was reserved by Fedora (see https://github.com/pypa/pypi-support/issues/355). [Keylime](https://keylime.dev) is the upstream project to the package in Fedora. @encukou can you unblock `keylime`, so that we can use it?

I'm a maintainer of Keylime: https://github.com/keylime/keylime/blob/master/MAINTAINERS.md

### Source code repositories URLs

https://github.com/keylime/keylime

### Contact and additional research

The name was reserved by Fedora, so there was no owner to contact.

The Fedora package (https://src.fedoraproject.org/rpms/keylime) is the package of upstream Keylime.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment]
Looks legit! Thank you for releasing on PyPI!

@di, can you unblock `keylime`, please?

**Comment by THS-on** [comment]
Thank you.

Is it possible to add #355 to https://pypi.org/help/#project-name, so that the list of reserved names can be more easily found?
