### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Parakoopa** [pypa/pypi-support#165]
Request for account recovery.

## PyPI Username

`Parakoopa`

---

##  Reason for request

Reason:
My Yubikey (security device) broke. It's no longer working, so I can't login.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete.

2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
