### ISSUE TITLE
PEP 541 Request: sapiens

### ISSUE THREAD

**Issue by prihoda** [pypa/pypi-support#1651]
### Project to be claimed

`sapiens`: https://pypi.org/project/sapiens

### Your PyPI username

`prihoda`: https://pypi.org/user/prihoda

### Reasons for the request

The "sapiens" project does not exist, but I cannot create it. 

I'm guessing this is because of the existing package "sapien": https://pypi.org/project/sapien/. If that's the case, I believe "sapiens" is distinct enough from "sapien", both packages will be used by a small niche group of users who know the name of the tool.

### Source code repositories URLs

Sapiens code repository https://github.com/Merck/Sapiens

### Contact and additional research

-

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by prihoda** [comment]
@di @yeraydiazdiaz can you give this a look? Thanks!

**Comment by prihoda** [comment]
Bump, could anyone have a look at this issue please? @di

**Comment by yeraydiazdiaz** [comment]
Hi @prihoda, I can confirm the project exist but has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
