### ISSUE TITLE
Project Limit Request: PyArrow - 20 GB

### ISSUE THREAD

**Issue by kszucs** [pypa/pypi-support#1653]
### Project URL

https://pypi.org/project/pyarrow/

### Does this project already exist?

- [X] Yes

### New limit

20 (if that's not possible please increase by just one so I can upload the current 7.0 release)

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

A cross-language development platform for in-memory analytics

See https://github.com/apache/arrow and https://arrow.apache.org for more details.

### How large is each release?

Roughly 750MB per release. 

### How frequently do you make a release?

Every 3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by kszucs** [comment]
It would be better to increase the limit over 20GB, but I don't know how much can we request.

**Comment by kszucs** [comment]
@jamadden perhaps you could take a look?

**Comment by kszucs** [comment]
cc @pitrou

**Comment by pradyunsg** [comment]
Limit increased to 20 GB on PyPI. :)

**Comment by kszucs** [comment]
Thank you @pradyunsg!
