### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jogrundy** [pypa/pypi-support#1654]
### PyPI Username

drjojo

### Reason for request

I evidently set up 2FA but have no memory of how. I got a new phone a couple of weeks ago and if I used Microsoft authenticator, it doesn't seem to back anything up, and I didn't think to. Arg. Sorry. If you could possibly recover my account I'd be very grateful, the python package I uploaded is part of my research project, and I need it for subsequent publications, and have referenced it in a previous publication. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by jogrundy** [comment]
I should also add I can still upload new versions of the package using twine, I have a token that seems to work fine. it is just logging in to the website that is the issue.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
