### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pythoninthegrass** [pypa/pypi-support#1656]
### PyPI Username

pythoninthegrass

### Reason for request

Lost access to email address. Only affects https://test.pypi.org; I've got access to https://pypi.org.

Thanks in advance!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Primary email address for the pythoninthegrass User on test.pypi.org has been updated to match the primary email address for the pythoninthegrass User on pypi.org.

You can complete a password reset to regain access to your account.

**Comment by pythoninthegrass** [comment]
All set! Thanks for your help @ewdurbin !
