### ISSUE TITLE
PEP 541 Request: reactive

### ISSUE THREAD

**Issue by rmorshea** [pypa/pypi-support#1658]
### Project to be claimed

`reactive`: https://pypi.org/project/reactive

### Your PyPI username

`rmorshea`: https://pypi.org/user/rmorshea

### Reasons for the request

This project could be considered abandoned and/or invalid.

- The author has no listed contact email on PyPI or on GitHub.
- The "Homepage" links to a [missing repo](https://github.com/vjn/reactive-py)
- The project has a single release from 2017
- The sole contents of the package is a solitary `reactive/__init__.py` file with the following function:

  ```python
  def reactive():
    return 'reactive-0.1'
  ```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The broken Homepage link: https://github.com/vjn/reactive-py

To see the lack of functionality for yourself you can run do following:

- `pip install reactive`
- ```python
  >>> import reactive
  >>> {k: v for k, v in reactive.__dict__.items() if not k.startswith("_")}
  {'reactive': <function reactive at 0x1052434c0>}
  >>> reactive.reactive()
  'reactive-0.1'
  ```

### Contact and additional research

The author has no listed contact email on [PyPI](https://pypi.org/user/vjn/) or on [GitHub](https://github.com/vjn). The GitHub user appears to be relatively inactive (at least from public info) - they only made one contribution last year according to their activity graph - they've been pinged below.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rmorshea** [comment]
I plan to rename and move this project under the `reactive` name: https://github.com/idom-team/idom

**Comment by rmorshea** [comment]
cc: @vjn

**Comment by rmorshea** [comment]
@yeraydiazdiaz, this seems like a fairly straightforward case - the author has failed to respond after a week via the only obvious method of contact (GitHub).

**Comment by gabis-precog** [comment]
@rmorshea another projects which **appears to be** under the same maintainer and has a ticket #1641 here.
apparently his linked-in account (according to the ticket) is at https://www.linkedin.com/in/vijayan/
you can attempt contacting him there and attach the attempt here.

**Comment by rmorshea** [comment]
@yeraydiazdiaz, the last communication avenue has been explored. The owner of this repository remains unresponsive.

**Comment by yeraydiazdiaz** [comment]
Hi @rmorshea, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by vjn** [comment]
@rmorshea is correct that there is no functionality yet under this project. I am in agreement with the transfer. Thanks!

**Comment by yeraydiazdiaz** [comment]
Thank you @vjn, transfer complete.

**Comment by rmorshea** [comment]
Thanks all!
