### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by romankoblov** [pypa/pypi-support#166]
Request for account recovery.

## PyPI Username

`penpen`

---

##  Reason for request
  - Lost access to email address
  - Password breached

Reason:
So, I’ve tried to login to my account (penpen) to update my very old package and looks like password was breached, so I cannot login to account. 
Even more, I’ve removed my google account a long ago, so I cannot restore password for PyPI account. Problem is, that when I’m tried to register it again, it
was taken already. 

Problem is, if somebody really taken this email address (and its not locked by google), then somebody can possible update this library without my knowledge and access to github.
So it would be cool if its possible to restore access to this account, but if its not possible, can you please lock it down?

**Comment by ewdurbin** [comment]
@romankoblov I've removed that address from the account to prevent unauthorized access you note.

I'll review the status of the account and projects associated with it to determine how to proceed with account recovery.

**Comment by ewdurbin** [comment]
@romankoblov I also note that the password reset attempts did bounce, so unauthorized access via that address should not be a concern.

**Comment by romankoblov** [comment]
Great, thanks for fast response!

> password reset attempts did bounce
Didn't know, tried to re-signup email and it was taken. Better to be safe than sorry.

As for review: there is two packages (only first one is usable):
- https://github.com/romankoblov/leaf (https://pypi.org/project/leaf/)
- https://github.com/romankoblov/srq-python (https://pypi.org/project/srq/)
My github username was 'penpen' too, but I've changed it. You can see it by redirect from 'https://github.com/penpen/leaf' to 'https://github.com/romankoblov/leaf'

**Comment by ewdurbin** [comment]
@romankoblov yeah, I confirmed that the existing releases for both projects had their homepages set to GitHub projects under the penpen username and both now redirect to the given repositories.

Given that the history of both projects match up to the releases, I think this is sufficient.

Is the public email address associated with your GitHub account and displayed on your user profile OK to use for the new email address on the pypi account?

**Comment by romankoblov** [comment]
Yep, would be great. Thanks for help!

**Comment by ewdurbin** [comment]
Done. You can now proceed with a password reset to recover your account.
