### ISSUE TITLE
Project Limit Request: RAiSEHD - 200 GB

### ISSUE THREAD

**Issue by rossjturner** [pypa/pypi-support#1660]
### Project URL

https://pypi.org/project/RAiSEHD

### Does this project already exist?

- [X] Yes

### New limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is an astrophysical fluid dynamics package that uses particles from hydrodynamical simulations to model the radio-frequency emission from the region surrounding black holes. The particle file is 79MB in size after compression and removal of as much data as possible. Future version may require more than one such particle file. This package has only recently been added on PyPI, but code distributed through other means for several years. 

### How large is each release?

The current release is 79MB; this size is primarily due to the .hdf5 files of fluid particles taken from a hydrodynamical simulation. This was initially over 1GB in size, but has had unnecessary particles removed, data normalised close to 1 and stored as float16, and stored as a compressed file format. However, it is still not possible to provide new releases of the code without deleted the current version. We request 200MB of storage for the project so the new and previous version can both be kept on PyPI.

### How frequently do you make a release?

New releases will be made every few months, though at present, much more regular updates will be made based on user feedback during the beta release.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
> ### Project URL
> 
> RAiSEHD

Please include the pypi.org/project/{name} URL, as the template requested and as the title suggested.

---

Thanks for including a complete description of the details here! ^.^

I've bumped the limit to 200 MB on PyPI.
