### ISSUE TITLE
File Limit Request: fbgemm-gpu-nightly - 200 MB

### ISSUE THREAD

**Issue by jianyuh** [pypa/pypi-support#1661]
### Project URL

https://pypi.org/project/fbgemm-gpu-nightly/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

FBGEMM_GPU (FBGEMM GPU kernel library) is a collection of high-performance CUDA GPU operator library for GPU training and inference. It will be active at least for 1 ~ 2 years from now.

We have made the efforts to reduce the binary size of our PyPI releases by limiting the supported CUDA arch to be V100 GPU (CUDA 7.0) and A100 GPU (CUDA 8.0). However, we want to support more CUDA architectures so the final compiled binary size can exceed 100 MB.

### Reasons for the request

In order to support more CUDA architecture (CUDA6.0 for p100; CUDA7.0 for v100; CUDA8.0 for a100), we need to compile a relatively big wheel file for the user to download. The currently 100 MB limits us from building a binary supporting multiple CUDA architectures.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Limit increased, since it's a small request. Please be mindful of your total project size, since there's a 10 GB limit on that. From the README:

> Upload limits are generally denied for the following reasons:
>
>    project makes nightly releases and/or is published frequently
