### ISSUE TITLE
PEP 541 Request: maglev

### ISSUE THREAD

**Issue by EmersonDove** [pypa/pypi-support#1663]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/maglev

### Your PyPI username

`USER_NAME`: https://pypi.org/user/EmersonDove

### Reasons for the request

The current page located at https://pypi.org/project/maglev is a 404 with no existing project. We are interested in using this package name because it is internally what we use for our component of our software and we believe this subcomponent of this package https://pypi.org/project/blankly will be useful to users

### Maintenance or replacement?

Replacement

### Source code repositories URLs

This would hold a component of the package https://github.com/blankly-finance/blankly

### Contact and additional research

I have not attempted to contact the owner of the claim. The 404 page does not provide any info about releases, accounts or reasons I cannot push to this.

Thank you for reviewing this!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @EmersonDove, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact witht he owners and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Hi @EmersonDove, the owner replied stating that the project will have releases soon and is planned to be part of infrastructure at Nvidia, so we will not be transferring it at this time.
