### ISSUE TITLE
File Limit Request: compiler_gym - 1000 MB

### ISSUE THREAD

**Issue by ChrisCummins** [pypa/pypi-support#1665]
### Project URL

https://pypi.org/project/compiler-gym/

### Does this project already exist?

- [X] Yes

### New Limit

1000 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

CompilerGym is a set of reinforcement learning environments for compiler optimization tasks, developed by Meta. It was [first released](https://github.com/facebookresearch/CompilerGym) in December 2020 and has 13 releases, 17 contributors, and >500 github stargazers.

### Reasons for the request

The reason for requesting a size limit increase is that our project requires native compiler binaries and data files that, if included in the python package, would take it over the size limit.

The workaround we have been using so far is to host these data files in S3 buckets and use [ad-hoc code to download and unpack them on first run](https://github.com/facebookresearch/CompilerGym/blob/00ae8c0d080da4d429f95398be1df01b5d6e7b71/compiler_gym/third_party/llvm/__init__.py#L22-L89). This has worked fine for our needs so far, but will no longer be sufficient for the next release as some new features we are working on require the data files to be bundled in the compiler_gym wheel.

I am requesting a generous size limit increase of 1000 MB to allow some room for future growth. I anticipate the size of the next release to be on the order of 500MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi there!

Do you anticipate a larger number of compilers being supported, or more data to be shipped with the distribution? If so, it might be reasonable to host data like that externally as you're doing currently -- that's somewhat similar to how NLTK handles their datasets (see [nltk.org/data.html](https://www.nltk.org/data.html) for example).

> will no longer be sufficient for the next release as some new features we are working on require the data files to be bundled in the compiler_gym wheel.

Could you elaborate a bit more on this? What changes with the new features, that it is no longer possible to ship data externally?

**Comment by ChrisCummins** [comment]
Hi Pradyun,

Thanks for following up and sorry for the slow reply. 

> Could you elaborate a bit more on this? What changes with the new features, that it is no longer possible to ship data externally?

Certainly. One of the compilers that CompilerGym supports is [LLVM](https://llvm.org/), which is widely used both in industry as a production-grade toolchain and in academia as a platform for compiler research. To support LLVM, CompilerGym relies on ~130 MB of compiled binaries. The way we support this in the current implementation is that we host those binaries in S3, and implemented a mechanism to lazily download and cache the binaries on the user's first run of CompilerGym.

This works fine if we only want to support a single version of LLVM. However, it is common for companies and researchers to fork LLVM and apply their own set of downstream modifications. We would like to support these use cases by enabling users to build and run CompilerGym against their own local copies of LLVM. This means we can no longer use the method of shipping compiler binaries separately, and we would instead need to embed those ~130 MB of binaries as static data files. For more context see https://github.com/facebookresearch/CompilerGym/issues/568.

Once this is implemented in CompilerGym, we will switch to shipping two versions of LLVM (the current version as a reference, and whatever the most recent version at the time of release is), requiring ~ 2x 130 = 260MB of data, and we are also working with some third party contributors who are working on a new compiler environment, based on LLVM, which will add a further ~ 250 MB of data, for an estimated package size at the next release of ~ 520 MB.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Hi @pradyunsg, gentle nudge 🙂 Any update on this?

Chris

**Comment by pradyunsg** [comment]
Hi there! There's no need to @-mention me here -- it isn't going to speed things up -- I triage these tickets in bulk, when I have the free time to do so. This issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.

**Comment by di** [comment]
I've set the upload limit for `compiler-gym` to 1 GB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by ChrisCummins** [comment]
Hi @di, thank you so much, and will do!

Cheers,
Chris
