### ISSUE TITLE
PEP 541 Request: specfile

### ISSUE THREAD

**Issue by nforro** [pypa/pypi-support#1667]
### Project to be claimed

`specfile`: https://pypi.org/project/specfile

### Your PyPI username

`nforro`: https://pypi.org/user/nforro

### Reasons for the request

As far as I can tell, there is no existing project with the name `specfile`. However, an attempt to create one ends with:
`The name 'specfile' isn't allowed.`
I wonder why it isn't allowed and if it would be possible to allow it.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/packit/specfile

### Contact and additional research

I wasn't able to contact current owner because I don't think there is any.

https://pypi.org/help/#project-name lists reasons why a new project can't be created with the desired name:

> The project name conflicts with a [Python Standard Library](https://docs.python.org/3/library/index.html) module from any major version from 2.5 to present.

There is no module with a name similar to `specfile`.

> The project name is too similar to an existing project and may be confusable.

There are projects with similar names, namely [suitcase-specfile](https://pypi.org/project/suitcase-specfile/) and a couple of projects with *spec* in their name. However, none of them is confusable in my opinion.

> The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.

If this is the case, can I know the reason?

> The project name has been registered by another user, but no releases have been created.

How can I check that? How can I contact such user?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nforro** [comment]
Bump, could anyone have a look at this issue?

**Comment by di** [comment]
Hi, this project name was prohibited on PyPI because it had been previously squatted in a [dependency confusion attack](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610). If https://github.com/packit/specfile is the canonical repo for the `specfile` project, we can release this project name to you.

**Comment by di** [comment]
Done!

**Comment by nforro** [comment]
Thank you!
