### ISSUE TITLE
PEP 541 Request: exiv2

### ISSUE THREAD

**Issue by jim-easterbrook** [pypa/pypi-support#1669]
### Project to be claimed

`exiv2`: https://pypi.org/project/exiv2/

### Your PyPI username

`jim_easterbrook`: https://pypi.org/user/jim_easterbrook/

### Reasons for the request

I believe this project to be abandoned. The last release was in May 2020, but the project description promises imminent further developments.

I have developed a package that has a very similar API, but is far more complete. It is currently on PyPI as `python-exiv2` (https://pypi.org/project/python-exiv2/) but I would prefer the name `exiv2`.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Abandoned project repo: https://bitbucket.org/zmic/exiv2-python/src/master/

Replacement project repo: https://github.com/jim-easterbrook/python-exiv2

### Contact and additional research

I have been unable to find an email address for the project owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @jim-easterbrook, I have started the reachability process for your request which can last up to 6 weeks. Hopefully we will hear back from the owner soon.

**Comment by zmic** [comment]
> Hello @jim-easterbrook, I have started the reachability process for your request which can last up to 6 weeks. Hopefully we will hear back from the owner soon.

@jim-easterbrook @yeraydiazdiaz 

Hello Mr. Easterbrook, it looks like you wrote a fine & complete wrapper. I have no time to work on this project (I just needed something that worked on Windows) so feel free to take over exiv2.

**Comment by jim-easterbrook** [comment]
Thank you @zmic 

@yeraydiazdiaz is there a "standard" procedure for migrating a project on PyPI? For example, will requests for `python-exiv2` be redirected to `exiv2` once I've assumed control of it?

**Comment by jim-easterbrook** [comment]
Thanks, I've found some instructions on how to do that.
