### ISSUE TITLE
Unable to upload to non-existent project `oryx`

### ISSUE THREAD

**Issue by sharadmv** [pypa/pypi-support#167]
I'm interested in uploading a `pypi.org` package called `oryx`, and checked that it doesn't exist (the [url](https://pypi.org/project/oryx/) 404s), but I'm still getting an HTTP 403 error when trying to upload it

```
HTTPError: 403 Client Error: The user 'sharadmv' isn't allowed to upload to project 'oryx'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```
Is there some way of gaining access to this or is it a reserved name?

**Comment by sharadmv** [comment]
Thanks!

**Comment by yeraydiazdiaz** [comment]
Hello @sharadmv, could you please confirm your PyPI username to move forward with your request?

**Comment by sharadmv** [comment]
Yes, my username is `sharadmv`.

**Comment by yeraydiazdiaz** [comment]
Thanks for confirming, I will now ask an admin to perform the transfer.

**Comment by sharadmv** [comment]
Thank you!

**Comment by ewdurbin** [comment]
transfer complete.
