### ISSUE TITLE
File Limit Request: abcmrt16 - 400 MB

### ISSUE THREAD

**Issue by jaden-pieper** [pypa/pypi-support#1670]
### Project URL

https://pypi.org/project/abcmrt16/

### Does this project already exist?

- [X] Yes

### New Limit

400

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This software implements the ABC-MRT16 algorithm for objective estimation of speech intelligibility. The algorithm is discussed in detail in [1] and [2]. ABC-MRT is short for “Articulation Band Correlation Modified Rhyme Test.” The software was originally written by NTIA/ITS in MATLAB (https://github.com/NTIA/ABC-MRT16), but has now been ported to Python.

The software relies on a large template file; this is a .mat file containing representations of source audio that are integral for the intelligibility estimation algorithm and cannot be removed.

It is unlikely that the total file size will change in the future.

### Reasons for the request

The software relies on a large template file; this is a .mat file containing representations of source audio that are integral for the intelligibility estimation algorithm and cannot be removed. This file is 348 MB, the total whl file is also 348 MB, so the templates is almost all of the size issue (there is a ~100 kb difference between the template and the whl file). 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
> It is unlikely that the total file size will change in the future.

Granting this on this basis.

If this increases substantially, you might want to consider hosting this data file externally and mirroring how https://www.nltk.org/data.html handles externally hosted data.
