### ISSUE TITLE
File Limit Request: mcvqoe-psud - 200 MB

### ISSUE THREAD

**Issue by jaden-pieper** [pypa/pypi-support#1671]
### Project URL

https://pypi.org/project/mcvqoe-psud/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The purpose of this software is to measure the Probability of Successful Delivery (PSuD) of a push-to-talk network. PSuD generally describes the likelihood that a message of a given length. It has been in development for a year.

It contains predefined audio specifically created for measuring the PSuD on push-to-talk networks.

### Reasons for the request

It is important that users of the measurement have the default audio to run measurements. It is specifically created and tailored to the measurement system and makes it easy for our users to start running measurements right away. The wheel and tar files come out to be 177 MB each.

We do not expect release sizes to increase in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Bumped the limit to 200 MB. :)
