### ISSUE TITLE
PEP 541 Request: pyrate

### ISSUE THREAD

**Issue by sheecegardezi** [pypa/pypi-support#1673]
### Project to be claimed

`pyrate`: https://pypi.org/project/pyrate

### Your PyPI username

`chive`: https://pypi.org/user/sheecegardezi/

### Reasons for the request

Project has been abandoned defiantly been abandon, it not been updated in 9 years now. Code base dose not even work now.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs
This is the project I worked on:
https://github.com/GeoscienceAustralia/PyRate

It will be really good if this project can get `pyrate` name. At the moment we use py-rate. Its a bit confusing.  

### Contact and additional research

I send multiple emails to the author in 2019. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @sheecegardezi, I've started the reachability process for your request which can last up to 6 weeks. Hopefully we will hear back from the owner soon.

**Comment by Chive** [comment]
Hi @yeraydiazdiaz , Hi @sheecegardezi 

Thanks for reaching out and congrats on the success of PyRate! First and foremost: I'm not against giving up the package name on PyPI, but I'm quite worried about breaking old projects.

I've had a look at https://pypistats.org/packages/pyrate and the package sees a surprising amount of weekly downloads. According to the [about](https://pypistats.org/about) page this even seems to exclude known mirrors so I'm really worried this might break a significant amount of projects.

I have originally developed this package at a previous employer to be used on multiple projects; to which I do no longer have access to. Therefore I'm a bit worried about breaking projects where this potentially might still be used. Please take into consideration that some of these projects we built might still run under the same Python versions on which they were originally built upon.

What are your thoughts on this?

Best,
Kim

**Comment by yeraydiazdiaz** [comment]
Hello @Chive, thanks for your reply. I did notice the downloads but part of the process is determining if the project is in fact abandoned first. The PEP is clear in regards of the transferring project for replacement if the project is still in use, so I conclude the transfer is not possible at this time.
