### ISSUE TITLE
PEP 541 Request: nose2

### ISSUE THREAD

**Issue by sirosen** [pypa/pypi-support#1676]
### Project to be claimed

`nose2`: https://pypi.org/project/nose2

### Your PyPI username

`sirosen`: https://pypi.org/user/sirosen

### Reasons for the request

For the past few years, I've been the only remaining maintainer of `nose2`.

I've gotten access on GitHub and ReadTheDocs from other maintainers back when the project was more active. However, ownership on pypi has always been missing. (I _do_ have maintainer credentials to publish.)

I want to remove all of the past maintainers from the project, as they are no longer active. This is a minor security issue, as they may have credentials which could be used to publish.

---

I understand that per PEP 541, the project is not "Abandoned". Nor does this situation perfectly meet any of the other criteria set out in the PEP. I'm hoping that this case is an acceptable enough exception that we can act on it and give me Owner privileges.

I would be willing to participate in an amendment process to the PEP if necessary, to allow for "reasonable exceptions after consideration by the Packaging Workgroup", but I would need a great deal of guidance on how to do submit an amendment.

EDIT: I realized after posting that a better amendment would be to allow for this exact scenario. Someone with Maintainer who needs to be made Owner.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/nose-devs/nose2

### Contact and additional research

I last exchanged some emails with the original author of `nose2`, Jason Pellerin, over a year ago, and the intent was to get me owner/maintainer permissions. That is to say: the original author was onboard but hasn't gotten around to it. I can only speculate that there may be a lost pypi.org password or other issues at play that made this more of a chore, and easily forgotten.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @sirosen, I think I'll attempt contact with the owner and if I do not get a reply simply transfer the ownership to you given your history with the project. I'll start the reachability process now, hopefully we will hear back soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied and accepted, transfer complete.

**Comment by sirosen** [comment]
Thanks! 🎉
