### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jroose** [pypa/pypi-support#1677]
### PyPI Username

jroose

### Reason for request

2FA token appears to have "lost sync".  I still have the authenticator app configured and my password still works, but when I try to log in using my authenticator I get an "invalid TOTP code" error.  

Judging by this issue, I might not be the only one to experience this type of problem?
https://github.com/pypa/pypi-support/issues/1618

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
TOTP codes are sensitive to the date and time on your device. Are you sure that the device generating codes is in sync?

If you are unable to resolve this on your own please reopen this issue to proceed with an account recovery.
