### ISSUE TITLE
Project Limit Request: Taichi - 30 GB

### ISSUE THREAD

**Issue by qiao-bo** [pypa/pypi-support#1679]
### Project URL

https://pypi.org/project/taichi

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[Taichi](https://github.com/taichi-dev/taichi) is an open source, high-performance programming language for computer graphics applications. We aim for productive and portable high-performance programming in Python. The project has been active since 2017.     

### How large is each release?

~440 MB total

4 Linux wheels at ~27 MB.
4 Windows wheels at ~22 MB.
10 MacOS wheels at ~24 MB.

We have tried to reduce our wheel size by removing examples and tests, etc. There is a relatively large release matrix to address a broad range of users. 

### How frequently do you make a release?

Roughly once every two weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Approved, and limit increased to 30 GB. Please be mindful of how often you release to PyPI.
