### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by matthew-brett** [pypa/pypi-support#168]
Request for account recovery.

## PyPI Username

`matthew.brett`

---

##  Reason for request

Reason:

I forgot the password to decrypt passwords in my 2FA app.  I know, I know ...

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete.

2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
