### ISSUE TITLE
PEP 541 Request: tuttle

### ISSUE THREAD

**Issue by clstaudt** [pypa/pypi-support#1680]
### Project to be claimed

`tuttle`: https://pypi.org/project/tuttle

### Your PyPI username

`clstaudt`: https://pypi.org/user/clstaudt

### Reasons for the request

We develop a business planning application for freelancers (https://github.com/tuttle-dev/tuttle) under the GPL. Upload of the core package under the name "tuttle" failed since the name seems to be claimed / reserved. 

Checking with the https://pypi.org/project/pypi-name/ tool, the name is not free:

```python
In [1]: from pypi_name import pypiName
   ...: 

In [2]: pypiName('tuttle')
Out[2]: False
```

However, no installable package or PyPI entry is found for the name "tuttle". The name seems to be claimed but never used. 

We believe the name should be transferred to our active project - please see the criteria checklist below.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/tuttle-dev/tuttle

### Contact and additional research

Checklist of the criteria for transfer:

> An abandoned project can be transferred to a new owner for purposes of reusing the name when ALL of the following are met:

> the project has been determined abandoned by the rules described above;

We believe the package name is not in use and should be treated as abandoned according to https://www.python.org/dev/peps/pep-0541.

> the candidate is able to demonstrate their own failed attempts to contact the existing owner;

We were unable to obtain contact details for whoever is reserving the package name.

> the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;

Our project has been in development since September 2021 and is funded by the Prototype Fund (https://prototypefund.de/en/).

> the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;

Since the package name seems to be claimed but never used, we believe an active project has the better claim to the name.

> download statistics on the Package Index for the existing package indicate project is not being used; 

PyPI does not show a project page for "tuttle". "pip install tuttle" does not find a package. 

![Screenshot 2022-02-14 at 12 49 10](https://user-images.githubusercontent.com/875194/153860675-251da1aa-2ea2-4b2e-91af-7007600514d2.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @clstaudt, a `tuttle` project exists but has no releases in PyPI and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
