### ISSUE TITLE
PEP 541 Request: CICADA

### ISSUE THREAD

**Issue by louis-pie** [pypa/pypi-support#1682]
### Project to be claimed

`CICADA`: https://pypi.org/project/cicada/

### Your PyPI username

`LOUIS-PIE`: https://pypi.org/user/louis-pie/

### Reasons for the request

- Emailed maintainer on `justin+cicada@justiniso.com` and `contact@justiniso.com` -> no reply
- Found maintainer GitHub account at [https://github.com/justiniso](https://github.com/justiniso)
  - no additional public contact info
  - no CICADA repository on account
- Current CICADA project appears stale since 2015

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/transferwise/cicada

### Current project/maintainer
- Emailed maintainer on `justin+cicada@justiniso.com` and `contact@justiniso.com` -> no reply
- Found maintainer GitHub account at [https://github.com/justiniso](https://github.com/justiniso)
  - no additional public contact info
  - no CICADA repository on account
- Current CICADA project appears stale since 2015

### New project/maintainer
- Maintainer GitHub [https://github.com/louis-pie](https://github.com/louis-pie)
- Codebase at [https://github.com/transferwise/cicada](https://github.com/transferwise/cicada)
- Cicada has been recently open-sourced after some extensive changes
- Cicada is used as the scheduler for PipelineWise
  - PipelineWise documentation [https://transferwise.github.io/pipelinewise/](https://transferwise.github.io/pipelinewise/)
  - PipelineWise codebase [https://github.com/transferwise/pipelinewise](https://github.com/transferwise/pipelinewise)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @louis-pie, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
