### ISSUE TITLE
Project Limit Request: mkl, mkl-static, daal, daal-static, ipp- 15 or 20 GB

### ISSUE THREAD

**Issue by nikkidreamt** [pypa/pypi-support#1686]
### Project URL

https://pypi.org/project/mkl/, https://pypi.org/project/mkl-static/, etc

### Does this project already exist?

- [X] Yes

### New limit

at least 15 Gb, 20 Gb will be great

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

https://pypi.org/project/mkl/
https://pypi.org/project/mkl-static/
https://pypi.org/project/daal
https://pypi.org/project/daal-static
https://pypi.org/project/ipp
 
the projects are active since 2017

### How large is each release?

for https://pypi.org/project/ipp :
2 Windows wheels (100 Mb , 60 Mb)
2 Linux wheels  (550 Mb, 300Mb)
1 Mac wheel (100Mb)
at total: 1,1 Gb

for mkl
https://pypi.org/project/mkl/
2 Windows wheels (230Mb , 130 Mb)
2 Linux wheels  (250Mb, 150Mb)
1 mac (160 Mb)
at total : ~900 Mb

### How frequently do you make a release?

quarterly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Could you please file separate issues for each of the projects?

That makes it easier for the volunteers who help triage this issue tracker, to reference past issues and check the history of the requests made. It also serves to provide a clearer record of what changed for each of these projects individually.

**Comment by pradyunsg** [comment]
This led to https://github.com/pypa/pypi-support/issues/1688, https://github.com/pypa/pypi-support/issues/1689, https://github.com/pypa/pypi-support/issues/1690, https://github.com/pypa/pypi-support/issues/1691 and https://github.com/pypa/pypi-support/issues/1692.
