### ISSUE TITLE
Project Limit Request: mkl - 15 or 20 GB

### ISSUE THREAD

**Issue by nikkidreamt** [pypa/pypi-support#1688]
### Project URL

https://pypi.org/project/mkl/

### Does this project already exist?

- [X] Yes

### New limit

15 or 20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

the projects are active since 2017

### How large is each release?

2 Windows wheels (230Mb , 130 Mb)
2 Linux wheels (250Mb, 150Mb)
1 mac (160 Mb)
at total : ~900 Mb

### How frequently do you make a release?

quaterly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `mkl` to 20 GB on PyPI.
