### ISSUE TITLE
Project Limit Request: mkl-static - 15 or 20 GB

### ISSUE THREAD

**Issue by nikkidreamt** [pypa/pypi-support#1689]
### Project URL

https://pypi.org/project/mkl-static/

### Does this project already exist?

- [X] Yes

### New limit

at least 15 Gb, 20 Gb will be great

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

the projects are active since 2017

### How large is each release?

2 Windows wheels (300Mb , 150 Mb)
2 Linux wheels (300Mb, 170Mb)
1 mac (200Mb)
at total : ~1,12 Gb

### How frequently do you make a release?

quarterly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `mkl-static` to 20 GB on PyPI.
