### ISSUE TITLE
Limit request

### ISSUE THREAD

**Issue by scrgiorgio** [pypa/pypi-support#169]
When we try to upload https://github.com/sci-visus/OpenVisus artifacts to PyPi we get the following:

Found artifact 'build\Release\OpenVisus\dist\OpenVisus-1.3.69-cp37-none-win_amd64.zip' matching 'build\Release\OpenVisus\dist*.zip' path
Uploading artifacts...
The maximum allowed artifact storage size of 50000 Mb will be exceeded.

Is it possible to increase the max file size to 100MB?
Thanks.

**Comment by jamadden** [comment]
Hi @scrgiorgio ! The admin tools indicate the limit is already set to 100MB so I think we're seeing something else. 

In https://github.com/pypa/warehouse/issues/7263 it was indicated the error was seen on AppVeyor, and doesn't correspond to an error produced by PyPI. Perhaps this error is coming from Appveyor storing the artifact? (I would try to check the Appveyor logs, but the link in the repository's `README.md` to appveyor is incorrect, it just links to the badge.)

**Comment by scrgiorgio** [comment]
Thanks a lot for your help.
The problem magically solved itself.
