### ISSUE TITLE
Project Limit Request: daal-static - 15 or 20 GB

### ISSUE THREAD

**Issue by nikkidreamt** [pypa/pypi-support#1691]
### Project URL

https://pypi.org/project/daal-static

### Does this project already exist?

- [X] Yes

### New limit

at least 15 Gb, 20 Gb will be great

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

the projects are active since 2017

### How large is each release?

1 Windows wheel (250Mb)
1 Linux wheel (530Mb)
1 Mac wheel (405 Mb)
at total: ~ 1,2 Gb

### How frequently do you make a release?

quarterly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `daal-static` to 20 GB on PyPI.
