### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mphillipson** [pypa/pypi-support#1694]
### PyPI Username

mphillipson

### Reason for request

Lost 2FA authentication app or security token for TestPyPI

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mphillipson** [comment]
Thank you, Ee. The branch has been pushed to the github.com/homedepot/apialchemy repo.

As a reminder, this 2FA reset request is for my TestPyPI account only - not my regular PyPI account.

Thanks again for your assistance!

Mike Phillipson

**Comment by mphillipson** [comment]
Hello again. I created the repo branch as requested, but I did not receive any followup re. my 2FA reset. Can you please assist? Thank you!

**Comment by ewdurbin** [comment]
Please respond to the email, as instructed.

**Comment by mphillipson** [comment]
Respectfully, I did reply to the email. Branch has been created. Please advise.

**Comment by ewdurbin** [comment]
The reply needs to go to the out of band email, not this issue.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
