### ISSUE TITLE
PEP 541 Request: pylcs

### ISSUE THREAD

**Issue by kuangkzh** [pypa/pypi-support#1696]
### Project to be claimed

`pylcs`: https://pypi.org/project/pylcs

### Your PyPI username

`kuangzh`: https://pypi.org/user/kuangzh

### Reasons for the request

The author seemed not working for this project from 2020. But the package has bugs return wrong result in some cases. I started a pull request to fix the bugs and add new functions but have not got any response.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Old package: https://github.com/Meteorix/pylcs
New package: https://github.com/kuangkzh/pylcs

### Contact and additional research

I started the pull request from 29 Oct.2021 but got no response.
Then I found the email address lxhustauto@gmail.com from author's homepage and sent an email on 13 Jan.2022 and got no response so far.
And I also found the author decalred not working for the project in  Mar.2020 https://github.com/Meteorix/pylcs/issues/4#issuecomment-602979031
So I expect to get the maintenance permission.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @kuangkzh, I've started the reachability process for your request which can last up to 6 weeks. Hopefully we will hear back from the owner soon.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
