### ISSUE TITLE
PEP 541 Request: cytools

### ISSUE THREAD

**Issue by ariostas** [pypa/pypi-support#1698]
### Project to be claimed

`cytools`: https://pypi.org/project/cytools

### Your PyPI username

`ariostas`: https://pypi.org/user/ariostas

### Reasons for the request

I believe that this project is a clear case of name squatting. The current cytools project in PyPI contains no code and it has not been updated in almost a year. I would like to host my Python package CYTools (link to the source code below), which has been in development for over a year and is starting to be used by the scientific community. Thus, I believe that my package would be a better use for the cytools project in PyPI than the current empty and abandoned project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/LiamMcAllisterGroup/cytools

### Contact and additional research

I have emailed the maintainer, but I have received no response. I have also tried to find more information about them online, but I have not found anything useful.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @ariostas, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
