### ISSUE TITLE
PEP 541 Request: latex2svg

### ISSUE THREAD

**Issue by Moonbase59** [pypa/pypi-support#1699]
### Project to be claimed

`latex2svg`: https://pypi.org/project/latex2svg

### Your PyPI username

`Moonbase59`: https://pypi.org/user/Moonbase59

### Reasons for the request

I’m trying to develop my first package, https://github.com/Moonbase59/latex2svg, because we need it in another project, namely https://github.com/BoboTiG/ebook-reader-dict.

I checked before if there was a project `latex2svg` on PyPI, and there seems none. Following the [tutorial](https://python-packaging.readthedocs.io/en/latest/index.html), I tried to register the project first, which told me "no need for registering, just upload".

Now when trying to upload my code using `python3 setup.py sdist upload`, I get an error

```text
Upload failed (400): The name 'latex2svg' isn't allowed. See https://pypi.org/help/#project-name for more information.
```
and seem unable to resolve it.

Note: My project is a much enhanced version of Tino Wagner’s [latex2svg](https://github.com/tuxu/latex2svg), and he never made it a Python module, or uploaded such on PyPI.

Any help much appreciated.

### Source code repositories URLs

https://github.com/Moonbase59/latex2svg

### Contact and additional research

None, since there is no such package on PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Moonbase59, `latex2svg` was placed in the prohibited project names list for squatting, @pypa/warehouse-admins could you release the project to @Moonbase59, please?

**Comment by ewdurbin** [comment]
'latex2svg' released to 'Moonbase59'
