### ISSUE TITLE
PEP 541 Request: hererocks

### ISSUE THREAD

**Issue by hishamhm** [pypa/pypi-support#170]
**Project to be claimed**

`hererocks`: https://pypi.org/project/hererocks

**Your PyPI username**

`luarocks`: https://pypi.org/user/luarocks

**Reasons for the request**

The original author of the project, Peter Melnichenko, passed away over a year ago. His Github account was  https://github.com/mpeterv/. The original upstream repository is https://github.com/mpeterv/hererocks. Peter was a member of the LuaRocks organization at https://github.com/luarocks and now the organization wishes to continue maintenance of hererocks at https://github.com/luarocks/hererocks.

**Maintenance or replacement?**

We intend to continue maintenance of the package, as explained above.

**Contact and additional research**

We have been contacted by people who knew him personally, this is how we learned about what happened. We have waited one year before submitting this request to comply with the criteria of "no releases in twelve months" stated by PEP 541. We are available to provide any other information, to the extent that we have them.

We created a PyPI account called `luarocks` which is validated with a `@luarocks.org` email, to confirm that this request comes from the upstream LuaRocks project (for which hererocks is a helper utility).

Thanks in advance for the consideration.

**Comment by yeraydiazdiaz** [comment]
Hi @hishamhm, I've asked an admin to perform the transfer for you.

**Comment by hishamhm** [comment]
Thank you <3

**Comment by ewdurbin** [comment]
transfer complete
