### ISSUE TITLE
File Limit Request: Open3D - 600 MB

### ISSUE THREAD

**Issue by yxlao** [pypa/pypi-support#1701]
### Project URL

https://pypi.org/project/open3d/

### Does this project already exist?

- [X] Yes

### New Limit

600

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[Open3D](https://github.com/isl-org/Open3D) is an open-source library that supports rapid development of software that deals with 3D data. The Open3D frontend exposes a set of carefully selected data structures and algorithms in both C++ and Python. 

Open3D is widely used by the computer vision community and it was downloaded 2.5M+ times from PyPI in 2021.

### Reasons for the request

Hello PyPI maintainers,

We are hitting the file size limit (400MB) for Open3D v0.15. You have graciously increased our quota to 400MB file size limit for our 0.13 release in Jun 2021 (https://github.com/pypa/pypi-support/issues/1131), but we have unfortunately crossed it. Can you increase the quota to 600MB for us?

The main reason for the increase is increasing functionality in Open3D, especially with respect to both CUDA GPU and CPU implementations that are implemented as compiled modules. The file size issue mainly happens for our Linux wheels, since it contains pre-compiled CUDA code. The macOS and Windows wheels are considerably smaller. 

We have already identified a way to reduce the binary size in the next release. We will be implementing that soon.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `open3D` to 600 MB on PyPI. Please be mindful of the frequency of releases at that size.
