### ISSUE TITLE
File Limit Request: Xlassify - 350 MB

### ISSUE THREAD

**Issue by maokangkun** [pypa/pypi-support#1707]
### Project URL

https://pypi.org/project/Xlassify/

### Does this project already exist?

- [X] Yes

### New Limit

350 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Xlassify is an alignment-free deep-learning model that is specifically trained to classify human gut bacteria.
We tried our best to compress the file size, but the binary files take up some storage space。

### Reasons for the request

For compatibility reasons our releases contains lot of binary files for different models, resulting in a size of ~280MB which exceeds the limit of 100MB.

It would be great if our limit could be increased to 300MB per wheel file. 300MB should be enough for now but an extra 50MB can not hurt in case the releases sizes increases a little bit in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `Xlassify` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.
