### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by josephmancuso** [pypa/pypi-support#1709]
### PyPI Username

josephmancuso

### Reason for request

Lost 2FA authentication.

Actually i don't fully remember setting this up. I think i did. It says insert USB and click a button but i don't think i have a USB with a button for this ...

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
The label on the WebAuthn key associated with the account is `Macbook 2019`. This may be TouchID.

If you're unable to access your account using this device, please respond to proceed with account recovery.

**Comment by josephmancuso** [comment]
Thats what I thought but when I try "with this device" I get this error. Is it just broken?


<img width="473" alt="Screen Shot 2022-02-23 at 8 55 45 AM" src="https://user-images.githubusercontent.com/20172538/155333456-d587ca24-2cfe-4646-9bc9-f2f276ad4401.png">

<img width="499" alt="Screen Shot 2022-02-23 at 8 55 55 AM" src="https://user-images.githubusercontent.com/20172538/155333473-5174b2fe-c042-45fd-b0e2-c63039c3be10.png">

**Comment by ewdurbin** [comment]
I'm able to reproduce this using a known good Touch ID credential in Safari, but attempting to sign in with Chrome. Please try using Safari.

**Comment by ewdurbin** [comment]
It seems that MacOS requires registering the credential separately for each browser, so this isn't necessarily a bug, just a quirk of the OS: https://stackoverflow.com/questions/70217770/webauthn-authentication-and-registration-using-touchid-on-two-different-browsers

**Comment by josephmancuso** [comment]
Tried that too. I get this and don't have a way to proceed
<img width="510" alt="Screen Shot 2022-02-23 at 9 06 50 AM" src="https://user-images.githubusercontent.com/20172538/155335295-9b3b0733-779c-4d8f-8f23-f5eabc2c6155.png">

**Comment by josephmancuso** [comment]
I thought maybe I just need to click my Touch ID to activate it but that puts my computer to sleep

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by josephmancuso** [comment]
Replied

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
