### ISSUE TITLE
Claim project sonlib

### ISSUE THREAD

**Issue by diekhans** [pypa/pypi-support#171]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/sonLib

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/diekhans

**Reasons for the request**

This  pypi package was created by a former student (arand) without consulting with the authors of the code and is now abandoned.  The pypi package It is out of data, ss no longer maintained.  

The pypi package does point to the Github repository of the actual author without his knowledge:
   https://github.com/benedictpaten/sonLib

**Maintenance or replacement?**

Maintenance
the current public repo is:
  https://github.com/ComparativeGenomicsToolkit/sonLib

which is a fork of the author's development repository
  https://github.com/benedictpaten/sonLib:

I am a staff member of Bendict Paten's research group

**Contact and additional research**

arand does not list an email address in his pypi profile.  We were able to locate him in linkedin, however he didn't respond to a message in that forum.  We have not been able to find another e-mail address for him.

**Comment by yeraydiazdiaz** [comment]
Hello @diekhans, `arand` does have an email registered in PyPI but it has been disabled.

I've done some quick research and it seems GitHub user @ArtRand might be the owner of the PyPI project.

Hopefully I'm correct and he can clarify his position regarding this project. Apologies if that is not the case.

**Comment by yeraydiazdiaz** [comment]
Tagging @ArtRand a second time as outlined [PEP 541 reachability section](https://www.python.org/dev/peps/pep-0541/#reachability).

**Comment by diekhans** [comment]
Art can be reached at art.rand@gmail.com, he no longer has access
to the email that created the account.

**Comment by yeraydiazdiaz** [comment]
Thanks, I have emailed Art to that address.

The best course of action is for him to reply to this issue or to my email accepting the transfer so we can move forward with the request.

If he's interested in regaining access to his account he can open an [account recovery issue](https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.md&title=Account+recovery+request).

**Comment by yeraydiazdiaz** [comment]
Hello @diekhans, I have not received reply from Art so this `sonlib` is now considered abandoned.

I will now ask an admin to perform the transfer for you.

**Comment by ewdurbin** [comment]
transfer complete.
