### ISSUE TITLE
PEP 541 Request: point-cloud-utils

### ISSUE THREAD

**Issue by fwilliams** [pypa/pypi-support#1710]
### Project to be claimed

`point-cloud-utils`: https://pypi.org/project/point-cloud-utils

### Your PyPI username

`francis.williams`: https://pypi.org/user/francis.williams

### Reasons for the request

Hi, 

I realize this may not be exactly the right form for this type of request, but it's the closest forum I could find for my request. 

I am the maintainer of [point-cloud-utils](https://github.com/fwilliams/point-cloud-utils), an open source library for processing 3D data. This package is reasonably widely used within my community. Unfortunately, when I try to publish a `point-cloud-utils` package on PyPI, I am met with an error that the name is too close to another package ([ping-cloud-utils](https://pypi.org/project/ping-cloud-utils/)). These packages are quite different in nature and I feel the names are reasonably far apart not to be confused. Thus, I am wondering if I could get an exception allowing me publish a package named `point-cloud-utils`. 

### Source code repositories URLs

[https://github.com/fwilliams/point-cloud-utils](https://github.com/fwilliams/point-cloud-utils)

### Contact and additional research

See above.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by fwilliams** [comment]
Hi, 

I just wanted to follow up on this issue. Is there anything needed on my end?

**Comment by yeraydiazdiaz** [comment]
Hello @fwilliams, it might be possible for a @pypa/warehouse-admins to do this but I'm not sure.

**Comment by fwilliams** [comment]
Thanks for the reply! The warehouse-admins link seems to 404. Where exactly should I post this issue?

**Comment by yeraydiazdiaz** [comment]
Hi @fwilliams, there's nothing for you to do at this point, the request just needs to be looked at by one of the admins to assess whether there is something they can do.

**Comment by ewdurbin** [comment]
Conflict is with `pointcloud-utils` Project name, which seems a bit less mature. Only concern with releasing the name is that now there is an obvious confusion point between the two names.

Curious what @pypa/warehouse-team thinks about how to handle these situations. IMHO if the difference between ultranormalized names is just the placement of a hyphen it should be treated as a standard 541 request (in other words releasing the requested name would claim the existing name).

**Comment by fwilliams** [comment]
Thanks for the follow up. I somehow missed `pointcloud-utils`, sorry about that! 

This project does seem quite a bit less mature. It has [20 commits with the span of ~3 weeks last year](https://github.com/zhangtingyu11/pointcloud_utils/commits/main) and does not have any documentation. 

In contrast, `point-cloud-utils` has been around 3 years longer (since 2018), has hundreds of commits, documentation, and a reasonable sized userbase (e.g. [conda package has 243k downloads](https://anaconda.org/conda-forge/point_cloud_utils), [GitHub repo has 489 stars](https://github.com/fwilliams/point-cloud-utils)). 

I've sent an email to the maintainer of `pointcloud-utils` asking if they would give up the name on PyPA. Are there any other steps to take after this?

**Comment by di** [comment]
Given the notability of `point-cloud-utils`, I'm in favor of granting this request directly, and have transferred the `point-cloud-utils` name to `francis.williams`.
