### ISSUE TITLE
PEP 541 Request: ertk

### ISSUE THREAD

**Issue by agkphysics** [pypa/pypi-support#1711]
### Project to be claimed

`ertk`: https://pypi.org/project/ertk

### Your PyPI username

`agkphysics`: https://pypi.org/user/agkphysics

### Reasons for the request

Based on discussion over at https://github.com/pypa/warehouse/issues/10810 the name `ertk` was previously prohibited as it was used maliciously. I wish to use this name for my Python library.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The source for the new package is at https://github.com/Strong-AI-Lab/emotion

### Contact and additional research

See https://github.com/pypa/warehouse/issues/10810 for discussion.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @agkphysics, as mentioned in the discussion the project was placed in the prohibited project names list, @pypa/warehouse-admins could you release the project to @agkphysics, please?

**Comment by ewdurbin** [comment]
'ertk' released to 'agkphysics'.
