### ISSUE TITLE
File Limit Request: uitestrunner-syberos - 200 MB

### ISSUE THREAD

**Issue by jinzhe0094** [pypa/pypi-support#1712]
### Project URL

https://pypi.org/project/uitestrunner-syberos/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is a GUI automatic test tool suitable for syberos. The first version was released on pypi on August 4, 2021.
Considering the reason of simple deployment and the fact that it is suitable for offline production environment, the project includes some supporting files that cannot be directly obtained in pypi, such as model files for OCR image recognition and phantomjs headless browser

### Reasons for the request

The project contains some supporting files that cannot be directly obtained in pypi, such as model files for OCR image recognition and phantomjs headless browser.
The current package size is about 170m. Considering the future code and resource updates, we are applying for the upper limit of 200m.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, have you considered other means of providing the models and headless browser?
