### ISSUE TITLE
PEP 541 Request: solaris

### ISSUE THREAD

**Issue by nrweir** [pypa/pypi-support#1714]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/solaris

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nrweir

### Reasons for the request

I am the author of the Solaris project and  created the project using an account associated with a previous employer. My account, nrweir, is listed as a maintainer on the project. I no longer work there and would like the ownership to be transferred to another maintainer, avanetten. The email address for the author of the project (nweir@iqt.org) no longer resolves.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/cosmiq/solaris

### Contact and additional research

I am the current owner, but no longer have access to the Author account. No owners are listed on the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nrweir** [comment]
@avanetten

**Comment by yeraydiazdiaz** [comment]
Hi @nrweir.

> I no longer work there and would like the ownership to be transferred to another maintainer, avanetten.

 PyPI user [`avanetten`](https://pypi.org/user/avanetten/) is already an owner of the project, along with [`dphogan`](https://pypi.org/user/dphogan/), and  [`jshermeyer`](https://pypi.org/user/jshermeyer/).

**Comment by yeraydiazdiaz** [comment]
Closing as there is nothing to do. Let me know if I misunderstood something.
