### ISSUE TITLE
File Limit Request: PypeIt - 200 MB

### ISSUE THREAD

**Issue by kbwestfall** [pypa/pypi-support#1715]
### Project URL

https://pypi.org/project/pypeit/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

PypeIt is a data-reduction package for astronomical spectrographs used by 100s of astronomers to process data from more than 30 spectrographs.  We have been distributing our software on PyPi via regular releases since ~Jan 2020.  Three components of the package are the primary contributors to the size of the package: (1) We require template spectra for accurate wavelength calibration for many spectrographs; (2) We require spectra of spectrophotometric standards and sensitivity functions for accurate flux calibration; and (3) We include a modest amount of test data used by our continuous integration tests.  Up until our upcoming version 1.8.1 release, we were able to keep the size of the repository below 100MB (actually version 1.8.0 seemed to go slightly above this). 

### Reasons for the request

In our most recent 1.8.1 release, we ran into the upload limit with our `pypeit-1.8.1.tar.gz` file; it is 117 MB.  We expect the package to continue to grow as we add more supported spectrographs and expand the capabilities of the code.  We are requesting a 200 MB limit to allow for these additional developments.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `pypeit` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by kbwestfall** [comment]
Thank you!
