### ISSUE TITLE
Can upload new package to test.pypi.org, but not to PyPI

### ISSUE THREAD

**Issue by robmoss** [pypa/pypi-support#1718]
**Describe the bug**

I created a new package ([jobq](https://bitbucket.org/robmoss/job-queue/)) and successfully uploaded it to [test.pypi.org](https://test.pypi.org/project/jobq/). When I try to upload it to PyPI, I receive the following error message:

    The user 'robmoss' isn't allowed to upload to project 'jobq'. See https://pypi.org/help/#project-name for more information.

As far as I can tell, the package name doesn't conflict with a Python Standard Library, and isn't too similar to an existing project. So I don't understand why this fails. Has this name been explicitly prohibited by the PyPI administrators?

**Expected behavior**

I would have expected identical results when uploading the package to test.pypi.org and to PyPI.

**To Reproduce**

    git clone https://bitbucket.org/robmoss/job-queue/
    python3 -m build
    python3 -m twine -r testpypi upload dist/jobq-0.1.0-py3-none-any.whl
    python3 -m twine upload dist/jobq-0.1.0-py3-none-any.whl

**My Platform**

I'm running Python 3.9.10, with build 0.7.0 and twine 3.7.0, on Debian Testing.

**Additional context**

My apologies if I'm missing something obvious here ...

**Comment by di** [comment]
This project was recently created on PyPI (on 2022-02-20). Is it possible this was by a colleague of yours?

If not, it appears that they are squatting the name, you can request the project name via a [name retention request](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME).

**Comment by robmoss** [comment]
No, none of my colleagues would have created the project. How are you able to see the project? I get a 404 error when I visit https://pypi.org/project/jobq/

**Comment by robmoss** [comment]
Thank you @di for your advice. I've submitted a name retention request, so I'll close this issue.

**Comment by di** [comment]
> How are you able to see the project? I get a 404 error when I visit https://pypi.org/project/jobq/

I'm a PyPI administrator. The project exists, but has no releases, hence the 404.

**Comment by robmoss** [comment]
Oh, I didn't realise that you could create a project without uploading a release. Thanks!
