### ISSUE TITLE
PEP 541 Request: jobq

### ISSUE THREAD

**Issue by robmoss** [pypa/pypi-support#1719]
### Project to be claimed

`jobq`: https://pypi.org/project/jobq

### Your PyPI username

`robmoss`: https://pypi.org/user/robmoss

### Reasons for the request

No package for this project has been uploaded to PyPI. But when I tried to upload a package with this name, it failed because the project has been created. I [raised an issue](https://github.com/pypa/pypi-support/issues/1718) and @di [suggested](https://github.com/pypa/pypi-support/issues/1718#issuecomment-1050418128) that I could request the project name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://bitbucket.org/robmoss/job-queue/

### Contact and additional research

I cannot identify the current owner of the project. Attempting to visit the [project page](https://pypi.org/project/jobq/) results in a 404 error. I was not aware that a project with this name had already been created, until it was mentioned in [my original issue](https://github.com/pypa/pypi-support/issues/1718).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @robmoss, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by robmoss** [comment]
Thank you very much.

**Comment by yeraydiazdiaz** [comment]
The owner, @drkennetz, replied and said they intend to make a release soon.

**Comment by robmoss** [comment]
Okay, I'll try another name. Is there a simpler way to test if a name is accepted than uploading a package? I tried renaming my package to "jobqueue" but apparently this is too similar to an existing project (I search PyPI and found `job_queue`, which I guess is the cause).
