### ISSUE TITLE
PEP 541 request: maelstrom

### ISSUE THREAD

**Issue by danhey** [pypa/pypi-support#172]
**Project to be claimed**

`maelstrom`: https://pypi.org/project/maelstrom

**Your PyPI username**

`danhey`: https://pypi.org/user/danhey

**Reasons for the request**

The project has not been updated since 2013, and there is no documentation or available source code on github under the users profile (@mlavin). 

**Maintenance or replacement?**

replacement: I will publish a [different package](https://github.com/danhey/maelstrom). As above, there is no repo for the current pypi maelstrom.

**Contact and additional research**

I've found the author's github and [website](http://mlavin.org/). No email has been provided, but I sent a message through keybase several months ago with no response.

**Comment by mlavin** [comment]
Sorry I don't regularly check Keybase for messages. I've added you as an owner to the project on PyPI. You're welcome to the name and best of luck with your project.

**Comment by danhey** [comment]
Cool, thanks Mark! I really appreciate this
