### ISSUE TITLE
PEP 541 Request: compy

### ISSUE THREAD

**Issue by eaklein** [pypa/pypi-support#1720]
### Project to be claimed

`compy`: https://pypi.org/project/compy

### Your PyPI username

`eaklein`: https://pypi.org/user/eaklein

### Reasons for the request

I believe the project has been abandoned. I tried downloading the code and receive a 404 error. There is no project description.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I would like to replace the package with my own "compy" package for processing CoMPASS data directories: https://github.com/eaklein/compy

### Contact and additional research

I attempted downloading the package from PyPI and received a 404 error.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @eaklein, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by eaklein** [comment]
Thank you very much, Yeray.
________________________________

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
