### ISSUE TITLE
PEP 541 Request: noo

### ISSUE THREAD

**Issue by vcokltfre** [pypa/pypi-support#1722]
### Project to be claimed

`noo`: https://pypi.org/project/noo

### Your PyPI username

`vcokltfre_dev`: https://pypi.org/user/vcokltfre_dev

### Reasons for the request

The project has no page on PyPI, but I am unable to upload my project (https://github.com/py-noo/noo) to it. My assumption is that as a 3 letter name the name is reserved/allowlisted/similar to prevent it being 'namesquatted' by an empty or malicious package.

### Source code repositories URLs

https://github.com/py-noo/noo

### Contact and additional research

As far as I can see there is no owner, the package is simply not allowing me to upload, as such no attempts have been made to context the owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @vcokltfre , I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.
