### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Haagimus** [pypa/pypi-support#1725]
### PyPI Username

haagimus

### Reason for request

lost 2FA authentication device and recovery codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Haagimus** [comment]
Are there any updates as to how long this process might take? There are some tickets in the pending verification from 2020! Hopefully, this doesn't take that log-in actuality. Is there anything I can do to speed the process along?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Haagimus** [comment]
I have completed the sent instructions and pushed a commit to the specified branch successfully.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by Haagimus** [comment]
Alright my friend I am good to go! Thank you so much for the help, I am in my account again and have successfully reset my password and 2FA device. I hope you have a wonderful weekend sir!
