### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ibdafna** [pypa/pypi-support#1726]
### PyPI Username

`itayd`

### Reason for request

I did not lose my 2FA app and can still generate codes with it, but the codes are not accepted by PyPI for some reason.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ibdafna** [comment]
Hey folks, is there anyone looking at this? I soon won't be able to cut releases for packages if my access is not reset.

**Comment by SylvainCorlay** [comment]
It would be great if this was resolved!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
