### ISSUE TITLE
File Limit Request: cpg-hail - 150 MB

### ISSUE THREAD

**Issue by vladsaveliev** [pypa/pypi-support#1729]
### Project URL

https://pypi.org/project/cpg-hail

### Does this project already exist?

- [X] Yes

### New limit

0.15

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`cpg-hail` is a fork of hail (https://hail.is) supported by the Centre for Population Genomics in Australia. Hail is a tool for genomic variation data analysis.

We recently switched from conda, and hit the PyPI size limits.

The package will be used only within our centre, so we don't expect it to be downloaded often.

We also don't expect it to grow in size in the future.

### How large is each release?

~130 MB total: 1 wheel at 130MB, due to a bundled Java artefact.

### How frequently do you make a release?

Once or twice a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by vladsaveliev** [comment]
Hi, my bad - exactly, I wanted to increase a per-file limit. Should I open a new issue?

**Comment by pradyunsg** [comment]
Nah, it’s fine. :)

I’ll come back around to this when I end up triaging the open limit requests here in bulk. :)

**Comment by vladsaveliev** [comment]
Thanks @pradyunsg for your response! Is there any chance it can be addressed earlier? Unfortunately not being able to upload a release is blocking us :(

We'd be happy to explore other ways, or switch conda, if it's not possible.

**Comment by di** [comment]
I've set the upload limit for `cpg-hail` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
