### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by carpediemmlf** [pypa/pypi-support#173]
Request for account recovery.

## PyPI Username

carpediemmlf

---

##  Reason for request

Reason:

- Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by carpediemmlf** [comment]
Thank you for tha fast response.

Responded via primary email.

**Comment by ewdurbin** [comment]
Confirmed, 2FA has been disabled for this account. You should be able to recover access by completing a password reset.

**Comment by carpediemmlf** [comment]
Thank you very much indeed.
