### ISSUE TITLE
PEP 541 Request: svgcheck (only at test.pypi.org)

### ISSUE THREAD

**Issue by rjsparks** [pypa/pypi-support#1731]
### Project to be claimed

`svgcheck`: https://test.pypi.org/project/svgcheck/

### Your PyPI username

`rjsparks`: https://pypi.org/user/rjsparks

### Reasons for the request

**PLEASE NOTE: this is only a request for test.pypi.org - the projects as pypi.org itself are fine**

The test.pypi.org version of this project has not been touched for several years. At the time it was touched Jim Schaad was the sole maintainer. He has since passed away. Before his passing, he added me (Robert Sparks) and Henrik Levkowetz as maintainers at the actual pypi project: https://pypi.org/project/svgcheck/. 

We are now modernizing the project to use test.pypi.org as part of CI/CD, and need administrative access to the project at the test version of the index.

This also affects three other projects: rfctools-common, rfc-xmldiff, and rfclint. Please let me know if I should create separate tickets for those.
https://test.pypi.org/project/rfctools-common/
https://test.pypi.org/project/rfc-xmldiff/
https://test.pypi.org/project/rfclint/

Again, the https://pypi.org versions of all of these are fine - the issue is only with the versions at https://test.pypi.org.

If it helps, all of the projects are homed now at https://github.com/ietf-tools/

Apologies in advance if this is not the best mechanism for making this request.

Robert Sparks
rjsparks@nostrum.com

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/ietf-tools/svgcheck
https://github.com/ietf-tools/rfctools-common
https://github.com/ietf-tools/rfc-xmldiff
https://github.com/ietf-tools/rfclint

### Contact and additional research

Jim passed away in late 2020. See https://mailarchive.ietf.org/arch/msg/ietf/uhn5CQBATbLvP4OZ6IkLF-4OW24/. As noted above, we had established additional maintainers for these projects at pypi.org, but did not manage to do so at test.pypi.org.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dkg** [comment]
I can confirm that @rjsparks is now one of the responsible upstream maintainers for svgcheck.  helping him improve the testing infrastructure on test.pypi.org would be a big help for those of us who write internet drafts.  thanks!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by rjsparks** [comment]
@yeraydiazdiaz Thank you. There were 3 other test-pypi repos mentioned in the ticket - do I need to enter separate tickets for those, or can they be handled as part of this one?
