### ISSUE TITLE
PEP 541 Request: emma

### ISSUE THREAD

**Issue by grantjenks** [pypa/pypi-support#1732]
### Project to be claimed

`emma`: https://pypi.org/project/emma

### Your PyPI username

`Grant.Jenks`: https://pypi.org/user/Grant.Jenks

### Reasons for the request

I created a new Python projects called "Emma" at https://github.com/grantjenks/emma . When I try to upload using twine, I get:

```
$ twine upload dist/emma-0.0.1.tar.gz 
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: Grant.Jenks
Enter your password: 
Uploading emma-0.0.1.tar.gz
100%|███████████████████████████████████████████████| 11.4k/11.4k [00:00<00:00, 13.3kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'Grant.Jenks' isn't allowed to upload to project 'emma'. See https://pypi.org/help/#project-name for more information.
```

The docs say that names may be reserved for any of:

> The project name conflicts with a [Python Standard Library](https://docs.python.org/3/library/index.html) module from any major version from 2.5 to present.

I did a Google search for "python standard library emma" but no results.

> The project name is too similar to an existing project and may be confusable.

There is a "PyEMMA" project but it doesn't seem that popular: http://github.com/markovmodel/PyEMMA/

> The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.

I can't think why this would be, but maybe?

> The project name has been registered by another user, but no releases have been created.

Doesn't seem so as there's nothing at https://pypi.org/project/emma/

Could you explain why the project name "emma" is not working for me?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/grantjenks/emma

### Contact and additional research

I did not attempt to contact any other owners. No ownership information is available. Additional research is detailed in "Reasons for the request".

Thank you for your time.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @grantjenks, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer.

**Comment by grantjenks** [comment]
Thank you!
