### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kavigupta** [pypa/pypi-support#1733]
### PyPI Username

`kavigupta`

### Reason for request

I seem to have lost my 2FA authentication app, it says "Account disabled". It is possible I forgot to update it when I moved to a new phone a while back, and I haven't logged into my account in a while. I still have access to my email address.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by kavigupta** [comment]
Any follow-up on this? It has been nearly half a year

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
