### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vianneyveremme** [pypa/pypi-support#1737]
### PyPI Username

`Vianpyro`

### Reason for request

Lost 2FA authentication app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by vianneyveremme** [comment]
If possible I would like to get my account back as soon as possible because I have some important updates to do to a bookstore I'm trying to create, if that's not too much to ask.
If there is anything I can do to speed up the process, please let me know, I'll do it as soon as possible.
Sorry if I sound rude, english isn't my biggest strengh...

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
