### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by disa-mhembere** [pypa/pypi-support#1738]
### PyPI Username

disa-mhembere

### Reason for request

Hello,

I have lost access to my school email address (disa@jhu.edu) as I completed my PhD in 2019. I'm now trying to access the pypi registry to update maintainers and packages, but have completely lost access. Would you be able to assist please?

Sincere thanks,
Disa

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by remram44** [comment]
I made a copy at https://pypi.org/project/d3m-jhu-primitives/

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account and CC'd the primary address on your new account, please read the instructions and reply to proceed with recovery.

**Comment by disa-mhembere** [comment]
Thanks -- done!

**Comment by ewdurbin** [comment]
Confirmation complete. Your User on PyPI has been updated to use the personal email address you used during confirmation and a password reset has been issued. Please complete that password reset to regain access to your account.
