### ISSUE TITLE
Limit Request: essentia-tensorflow - 381MB

### ISSUE THREAD

**Issue by dbogdanov** [pypa/pypi-support#174]
**Project**
essentia-tensorflow
https://pypi.org/project/essentia-tensorflow

**Size of release**
381MB each wheel. Currently, only Linux ```manylinux2014``` wheels are supplied (`cp35-cp35m-manylinux2014_x86_64`, `cp36-cp36m-manylinux2014_x86_64`, `cp37-cp37m-manylinux2014_x86_64`).

**Which indexes**
PyPI and Test PyPI

**Reasons for the request**
This is a request to expand the upload limits for the new ```essentia-tensorflow``` package. 

We have been successfully hosting  ```essentia``` package (https://pypi.org/project/essentia),  a [library for audio and music analysis, description, and synthesis](https://essentia.upf.edu/), widely used by research communities focused on music information retrieval, sound and music computing and audio signal processing. 

While the original ```essentia``` package falls below the 60MB limit, we have recently expanded the functionality of Essentia with [a TensorFlow wrapper](https://mtg.github.io/essentia-labs//news/2019/10/19/tensorflow-models-in-essentia/), allowing to integrate inference with deep learning models into our audio analysis pipeline. As the TensorFlow dependency is very heavy and not all of our user base will need it, the builds of Essentia with this wrapper will be distributed as a separate package ```essentia-tensorflow```.

Unfortunately we do not have any version of the new package submitted yet, because our shared library dependency, TensorFlow, already surpasses the limit. 

Is it possible to work this out? 

Our development wheels are currently hosted at https://essentia.upf.edu/python-wheels/

**Comment by pabloEntropia** [comment]
Any updates on this request?

**Comment by dbogdanov** [comment]
A gentle ping for this request as we are planning to present this software package soon on a conference.

**Comment by ewdurbin** [comment]
Projects must be created on test.pypi.org and pypi.org before limits can be created, I'm unable to find projects with the name essentia-tensorflow on either index.

**Comment by dbogdanov** [comment]
@ewdurbin I've uploaded a dummy version of the package to fit below the size limit: 
- https://pypi.org/project/essentia-tensorflow/
- https://test.pypi.org/project/essentia-tensorflow/

**Comment by ewdurbin** [comment]
Upload limits set to 400MB on both indexes.

Please limit the number of releases created using this limit. Nightly or automated releases are discouraged.
