### ISSUE TITLE
Project Limit Request: Cicadad- 1 GB

### ISSUE THREAD

**Issue by herzo175** [pypa/pypi-support#1740]
### Project URL

https://pypi.org/project/cicadad/

### Does this project already exist?

- [X] Yes

### New limit

1 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Cicadad is a load testing package that has been in development for about a year. It gets new releases every 1-3 months (ideally). This limit increase is needed to accommodate for binaries included with the package that allow an agent to be run locally. 

### How large is each release?

Approximately 140 MB compressed. Includes agent binaries for MacOS, Windows, and Linux on x86, x64, arm, and arm64 which take up the bulk of the code

Binary sizes:

```bash
53M     ./backend-amd64.exe
52M     ./backend-darwin-amd64
53M     ./backend-darwin-arm64
47M     ./backend-linux-32
52M     ./backend-linux-amd64
46M     ./backend-linux-arm
51M     ./backend-linux-arm64
```

### How frequently do you make a release?

1-3 months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, the default project limit is 10GB. Did you mean to request to increase the file size limit? If so, would a 200MB file size limit suffice?

**Comment by herzo175** [comment]
Oh okay. If that solves the problem of the 140mb packaged tar, that would be great! Thanks!

**Comment by di** [comment]
I've set the upload limit for `cicadad` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by herzo175** [comment]
Thanks!
