### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by foozzi** [pypa/pypi-support#1742]
### PyPI Username

foozzi

### Reason for request

The fact is that when evacuating from my city in Ukraine, I lost access to my phone and, accordingly, to google authenticator, I know my password, I can provide any evidence that the pypi.org/user/foozzi account is really mine, I have access to github all my projects, as you can see, mail is also available to me, help me restore my account, I'm ready to pass any checks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
