### ISSUE TITLE
PEP 541 Request: yamlconfig

### ISSUE THREAD

**Issue by julie777** [pypa/pypi-support#1749]
### Project to be claimed

`yamlconfig`: https://pypi.org/project/yamlconfig

### Your PyPI username

`julie777`: https://pypi.org/user/julie777

### Reasons for the request

Currently this is a placeholder while I wait to see if the current owner will reply to email.

yamlconfig looks abandoned
- it has no home page
- it has not changed in more than 10 years
- the owner has no repo for it on GitHub where his other repos live
- there is no license in the package being distributed, although it mentions one on pypi
- very few uses on the library.io page and the most significant one no longer lists it as a dependency.
- it has no project description, and based on that I am planning to use the name for a new project

Note: for the purposes of PEP541 it would be nice if I could see the last time it was downloaded. I hope that pypi maintainers have that information.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

None

### Contact and additional research

I sent email to the owner and I am waiting for a reply.

The package page on PyPI
- has no description,
- the homepage is a broken link
- the last change was more than 10 years ago
- there is no link to the source repo
- the library.io page shows very little use

I also tracked down the owner's account on github and there is no repo for yamlconfig there.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by julie777** [comment]
I received a response from Kelsey Hightower, the current owner, and he is willing to transfer ownership to me.

There is no current repo.

**Comment by pradyunsg** [comment]
I believe that's @kelseyhightower.

He can go to log in to PyPI, https://pypi.org/project/yamlconfig/, go to manage project and then perform the transfer from there by adding you as an owner (`julie777`).
