### ISSUE TITLE
Project Limit Request: alphad3m - 1.0 GB

### ISSUE THREAD

**Issue by roquelopez** [pypa/pypi-support#1750]
### Project URL

https://pypi.org/project/alphad3m/

### Does this project already exist?

- [X] Yes

### New limit

1.0

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

AlphaD3M is an AutoML system that automatically searches for models and derives end-to-end pipelines that read,
pre-process the data, and train the model. AlphaD3M supports many ML tasks: classification (semi-supervised, binary, multiclass), regression (univariate, and multivariate), time series (forecasting, and classification),  image-based problems (object detection, and image classification), graph-based problems (collaborative filtering, community detection, graph matching, link prediction, and vertex classification),  and clustering. AlphaD3M has been in development for about four years.

Some of these ML tasks need models like ResNet 50, BERT,  etc. These models need static pretrained files. Each pretrained file has a significant size, and all in all, encompasses about 1.0G. We would like to add these files in our next release.

### How large is each release?

Current release:
~ 220.0 kB
Source tar files: 220.0 kB

Future release with static files:
~ 1.0G
Source files: 220.0 kB
Pretrained Files: 1.0G

### How frequently do you make a release?

Roughly once every one month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, have you explored alternative ways to distribute these models?

**Comment by roquelopez** [comment]
Hi, we found another strategy to use these models. We don't need anymore this request. Thanks!
