### ISSUE TITLE
PEP 541 Request: panther

### ISSUE THREAD

**Issue by AliRn76** [pypa/pypi-support#1757]
### Project to be claimed

`panther`: https://pypi.org/project/panther

### Your PyPI username

`alirn`: https://pypi.org/user/alirn

### Reasons for the request

I tried to use this name for my package, but someone reserve it in 2014 and it does not even have github or ... .

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/AliRn76/panther

### Contact and additional research

I couldn't find his github, email, or anything.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by AliRn76** [comment]
I found his email and messaged him
he is ok with transferring the ownership, now what should we do?

**Comment by yeraydiazdiaz** [comment]
Hello @AliRn76, the owner can add you as a collaborator with owner permissions in the project's management page https://pypi.org/manage/project/panther/collaboration/

**Comment by yeraydiazdiaz** [comment]
Closing as the owner seems to have transferred the project as requested.

**Comment by AliRn76** [comment]
Yea, thank you , its transfered.✌️
