### ISSUE TITLE
PEP 541 Request: openai

### ISSUE THREAD

**Issue by gdb** [pypa/pypi-support#176]
**Project to be claimed**
`openai`: https://pypi.org/project/openai

**Your PyPI username**
`gdb`: https://pypi.org/user/gdb

**Reasons for the request**
I'm the CTO of OpenAI (openai.com). I would like to create an official `openai` PyPI package, and want to avoid user confusion!

**Maintenance or replacement?**
Replacement.

**Contact and additional research**
The current `openai` PyPI project appears to be a stock template created by Peter Downs (@peterldowns). I contacted Peter Downs, who said he has no affiliation with this project. I wasn't able to immediately find contact information for the `openai` project maintainer, souljaboy.

**Comment by jamadden** [comment]
The project appears to be empty and offer no functionality. (Moreover, the same owner uploaded many additional projects on the same day that are generated from the same template.) Thus, it appears to fall under the 'name squatting' provisions of PEP 541. I will raise this to the admins to initiate a transfer.

**Comment by peterldowns** [comment]
Great, thank you. Just writing here to confirm everything Greg wrote in the initial email. Let me know if there's anything else you need.

Peter

**Comment by gdb** [comment]
Just checking in — anything I can do to help finalize the transfer? Thank you!

**Comment by jamadden** [comment]
Thanks for your patience. It's in the queue to be processed by the admins (commonly @ewdurbin) Please understand their time is extremely limited and they'll get to it as soon as they can.

**Comment by gdb** [comment]
Sounds good, thank you!

**Comment by ewdurbin** [comment]
transfer complete.
