### ISSUE TITLE
PEP 541 Request: module

### ISSUE THREAD

**Issue by tombulled** [pypa/pypi-support#1760]
### Project to be claimed

`module`: https://pypi.org/project/module

### Your PyPI username

`tbulled`: https://pypi.org/user/tbulled

### Reasons for the request

I believe the current package constitutes an invalid project for the following reason:
* project is name squatting (package has no functionality or is empty)

The current code consists of the following:
```python
name = "module"

print("Hey! Looks like you accidentally pulled in an incorrect dependency. This can bork your software supply chain in all sorts of ways, so it's very important to be careful with what you're pulling in. Read more about software supply chain security here: https://www.usenix.org/conference/usenixsecurity19/presentation/torres-arias")
```

Commit messages such as [`My second python package - just squattin`](https://github.com/adityasaky/module/commit/0cbcc5e1f419af084534052bcc5e6cc52469e342) indicate that the user is aware that they are squatting the package name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing Repo:
* https://github.com/adityasaky/module

To be replaced with:
* https://github.com/tombulled/module

### Contact and additional research

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @tombulled, frankly I agree with the owner in that `module` is a dangerous name for a project. I think it should be placed in the prohibited project names list, @pypa/warehouse-admins any thoughts on this?

**Comment by ssbarnea** [comment]
I totally agree that this should be added to prohibited list.

**Comment by ewdurbin** [comment]
project name `module` added to the prohibited project name list. existing project removed as non-op
