### ISSUE TITLE
TestPyPI: Account recovery request

### ISSUE THREAD

**Issue by kazunarikudo** [pypa/pypi-support#1762]
### PyPI Username

`harvesters`

### Reason for request

Dear Sir or Madam,

This is Kazunari. Thank you for your support. I appreciate that.

This request is for my account in TestPyPI.

I can't remember when but I seem to have set up TFA before. However, I do not have any way to get the authentication account back, unfortunately. Since I do not have any way to provide an authentication code.

Best regards,
Kazunari

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by kazunarikudo** [comment]
@ewdurbin Hello Mr. Durbin, please let me know if there is another procedure I need to complete before asking you to recover the account. Thank you, Kazunari.

**Comment by kazunarikudo** [comment]
Excuse me, is there any maintainer who can take care of the account recovery request?

**Comment by ewdurbin** [comment]
TestPyPI 2FA disabled and password reset issued.
