### ISSUE TITLE
File Limit Request: antspyx - 350 MB

### ISSUE THREAD

**Issue by stnava** [pypa/pypi-support#1765]
### Project URL

https://pypi.org/project/antspyx/

### Does this project already exist?

- [X] Yes

### New Limit

350MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Revisiting https://github.com/pypa/pypi-support/issues/52

This project has been active since 2018 and we use it heavily in large-scale image analysis for both industry and academia.

https://github.com/ANTsX/ANTsPy this project templated C++ to generate 2, 3 and 4-dimensional processing routines for medical imaging and related types of data. it wraps the (large) C++ project https://github.com/ANTsX/ANTs using pybind11. As such, the project installation files are rather large:

* My current manylinux builds are 310MB

the majority of the space is *.so files.

I would love to continue to distribute this project  via pypi.   we use it in large-scale distributed computing on AWS and related cloud compute platforms (via docker).   

thank you for considering this request and thank you for this generous project.

best,

BA

### Reasons for the request

it looks like with changes in compilers, number of libraries, etc in our stack, we may expect a slow growth of the package size.  I've tried `strip` and `doctor-wheel` without luck in reducing whl size.   

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by stnava** [comment]
Brief update:  I tried several strategies to more portable and smaller wheels but none have worked out.  Best I could do was get it down to 305MB.     I am dealing with an irritated user community and would appreciate if  this relatively modest increase in our file size limit were approved.    Many thanks for your efforts on this critical project and thx for supporting our imaging community's use of pypi.

**Comment by stnava** [comment]
this should be fixed now.   please close if you confirm.

**Comment by pradyunsg** [comment]
I've bumped the limit to 400 MB. :)

FYI: You're at 4.7 GiB / 10GiB of the total project size limit.

**Comment by stnava** [comment]
hi @pradyunsg - thanks so much - we should be good for some time with this ....
