### ISSUE TITLE
File Limit Request: ikomia - 150 MB

### ISSUE THREAD

**Issue by LudoBar** [pypa/pypi-support#1767]
### Project URL

https://pypi.org/project/ikomia/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Ikomia is a french company specialized in Computer Vision. We aim to provide Open Source software to ease the use of state of the art algorithms in this field. We develop a prototyping software (Ikomia Studio), a marketplace of algorithms and this Python API to build workflows with few line of codes. The API integrates built-in algorithms from different sources and thus needs quiet a lot of dependencies. As a example, we bundle a complete and specific build of OpenCV. (https://ikomia.com/en/)

### Reasons for the request

Computer Vision algorithms are now often based on Deep Learning methods. Thus, we provide several versions of our API, including some GPU-enabled wheels. Those wheels are too heavy to be uploaded to PyPI due to CUDA dependencies. But we want to provide at least CPU version on PyPI for our users.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `ikomia ` to 200 MB on PyPI. It does not exist on TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by LudoBar** [comment]
Thank you very much!
