### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by masa-su** [pypa/pypi-support#177]
Request for account recovery.

## PyPI Username

`masa-su`

---

##  Reason for request

- Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via the primary email address on the PyPI account. Please read the instructions in the email and respond.

**Comment by ewdurbin** [comment]
Confirmation complete.

2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
