### ISSUE TITLE
PEP 541 Request: quark

### ISSUE THREAD

**Issue by DrIcetar** [pypa/pypi-support#1770]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/quark

### Your PyPI username

`USER_NAME`: https://pypi.org/user/dricetar

### Reasons for the request

The project seems abandoned I guess
- this project hasn't been updated since 2016
- the package is marked as "beta"

if possible, I'd like to claim this project

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://opendev.org/x/quark

### Contact and additional research

n/a

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @DrIcetar, the project's homepage points to https://github.com/openstack-archive/quark which states it's been moved to https://opendev.org/x/quark, am I right to assume you intend to maintain the project?

If you are in contact with the current owners they could simply add you as an owner in https://pypi.org/manage/project/quark/collaboration/

**Comment by DrIcetar** [comment]
Thanks @yeraydiazdiaz , but I didn't mean to maintain that project. I've realized that the current owners have moved their project to a new place. I've also sent a message to the owners and got no response for now.  Once they give me their decision, I'll close this issue. Thanks again~

**Comment by yeraydiazdiaz** [comment]
Sorry, I'm not following. You claim you do not want to maintain the project so you intend to replace it? If so you need to provide a repository for the new project you intend to publish under that name.

**Comment by yeraydiazdiaz** [comment]
Thanks @DrIcetar, I will start the reachability process for this request which can take up to 6 weeks.

**Comment by roaet** [comment]
From my understanding this is just an attempt to claim the name of the project. It may still be used by Rackspace though. I am not in a position to understand the impacts of this. I have updated the maintainer list so that someone from Rackspace can make a decision.

**Comment by quadewarren** [comment]
@yeraydiazdiaz It was decided that we're going to keep the project. We are not going to release the name.

**Comment by DrIcetar** [comment]
Understood and thanks very much@yeraydiazdiaz @quadewarren @roaet. I'll close this issue immediately
