### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by travisclagrone** [pypa/pypi-support#1773]
### PyPI Username

`travis-c-lagrone`

### Reason for request

Lost prior 2FA authentication because it was tied to a 2FA app on my old phone which died.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by travis-c-lagrone** [comment]
**What is the ETA on response to this support request?** I acknowledge that "it may take a significant amount of time to process" this support request, but it has been over a month without any sort of activity whatsoever. Thank you for your time and effort in responding to this.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
