### ISSUE TITLE
Project Limit Request: aim - 40 GB

### ISSUE THREAD

**Issue by gorarakelyan** [pypa/pypi-support#1775]
### Project URL

https://pypi.org/project/aim

### Does this project already exist?

- [X] Yes

### New limit

40 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Aim is an open-source machine learning experiment tracking tool - https://github.com/aimhubio/aim

Aim consists from the following main components:
- Storage: at its core Aim uses a custom-built storage, based on rocksdb (python+cython)
- SDK: on top of the storage SDK provides functionality to track/select/query data (python)
- Web: app allowing to browse tracked data (python+typescript)

The first version was released on Sep 20, 2019 under `aim-cli` name. Then we moved the package to `aim` project on Oct 26, 2020. Since then we have released ~60-65 versions. 
We also release preview versions(based on community request), but keep only the last 14 ones and regularly clean up the project. We will reconsider and move previews to another repo if it violates guidelines in any way.

To make the maintenance easier we are going to split the web front-end out of the project code and publish it as separate python project and include it as a requirement. Which will optimize the package size reducing it by ~90%.

40 GB space should be enough for 10 years:
- **30 GB**: 22 MB(release size after optimization) * 10(monthly releases) * 12(yearly releases) * 10(for 10 years) 
- **\+ ~9 GB**: already occupied space

### How large is each release?

~220 MB in total:
- 5 linux wheels ~ 100 MB
- 5 macos wheels ~ 100 MB
- the source tarball ~ 20MB

However, as already mentioned, we are going to optimize the build in a very near future and move js bundles.
The package size will be optimized accordingly:

~ 22 MB in total:
- 5 linux wheels ~ 10 MB
- 5 macos wheels ~ 10 MB 
- the source tarball ~ 2MB

### How frequently do you make a release?

Roughly 10 releases each month:
- one minor release each 2 weeks 
- in average 4 patch releases in-between minors 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `aim` to 20 GB on PyPI for now. Happy to revisit this as you approach this limit, please file a new issue if/when this is necessary.

**Comment by gorarakelyan** [comment]
thanks a lot @di ! 🙏
