### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kammoh** [pypa/pypi-support#1777]
### PyPI Username

`kammoh`

### Reason for request

- Lost 2FA authentication app.

The app was on a phone which I lost a while ago. I can't seem to find any recovery codes, so I might have forgotten to download them at all :(
I _do_ have access to my email and GitHub accounts, as well as my phone number (not sure it was asked by PyPI at all, but anyways).
I _greatly_ appreciate your help with recovery of my account.

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by kammoh** [comment]
Thank you very much Ee!
I responded to your email.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
