### ISSUE TITLE
Name 'fiddle' isn't allowed

### ISSUE THREAD

**Issue by dhr** [pypa/pypi-support#1783]
### Project to be claimed

`fiddle`: https://pypi.org/project/fiddle

### Your PyPI username

`dhr`: https://pypi.org/user/dhr

### Reasons for the request

We have a new project named "Fiddle" (source at https://github.com/google/fiddle), and we'd like to use the corresponding PyPI package name of "fiddle". However, attempting to create a package with this name results in an error stating "The name 'fiddle' isn't allowed.":

```
$ python3 -m twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: dhr
Enter your password: 
Uploading fiddle-0.0.0-py3-none-any.whl
100%|███████████████| 7.97k/7.97k [00:00<00:00, 23.1kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'fiddle' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

I wanted to reach out to understand why this name isn't currently allowed, and whether it would be possible to allow it. (Note that this isn't strictly a PEP 541 request, since there doesn't appear to be an existing package with this name and no ownership to transfer, but this seemed to be the closest issue template I was able to use.)

### Source code repositories URLs

https://github.com/google/fiddle

### Contact and additional research

There is no existing package with the desired name, and so no owner to contact.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @dhr, `fiddle` has been placed in the prohibited project names list for dependency confusion reasons. @pypa/warehouse-admins could you release the project to @dhr, please?

**Comment by dhr** [comment]
Thanks for the response! So if I understand correctly, it will be possible to release this name for our project's use going forward?

**Comment by dhr** [comment]
Friendly ping! Wanted to know if there's any update on the status of this... Is there anything else I can do to help facilitate the  name release?

**Comment by pradyunsg** [comment]
This issue tracker is mostly handled by volunteers so things are worked through somewhat slowly. The volunteers tend to triage tickets in bulk, when they have the free time to do so.

This specific ticket needs one of the volunteers who serve as PyPI administators to do such a triage round, of tickets that need admin review and action. This will likely get handled as part of one of these triage rounds, which is when you'll see an update. :)

Until then, I think the only thing that you can do is wait patiently until that happens.

**Comment by ewdurbin** [comment]
'fiddle' released to 'dhr'.

**Comment by dhr** [comment]
Awesome! Thanks so much for the help with this.
