### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by garydavenport73** [pypa/pypi-support#1785]
### PyPI Username

`garydavenport73`

### Reason for request

Hi, I lost access to my email address.  I used to use dovedweller@gmail.com and garydavenport73@gmail.com.  Unfortunately when I closed these accounts I forgot to update the PyPI information.  I did update my github email and passwords but forgot to change these in PyPI.

My new email address is software@garydavenport.com.  

As evidence, If it helps, you could take a look at one of my 5 my PyPI projects, https://pypi.org/project/preferredsoundplayer/ and notice that the homepage is listed as https://github.com/garydavenport73/PreferredSoundPlayer.

When you go to the github page you will see my new email address software@garydavenport.com listed as the contact information.  Hopefully, there is a way I can make this correction.

I apologize to you and appreciate your time,

Gary Davenport
software@garydavenport.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account and the new email address you're requesting., please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. Primary email address for the user has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
