### ISSUE TITLE
Project Limit Request: azureml-dataprep-rslex - 25 GB

### ISSUE THREAD

**Issue by yikei** [pypa/pypi-support#1790]
### Project URL

https://pypi.org/project/azureml-dataprep-rslex/

### Does this project already exist?

- [X] Yes

### New limit

25

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This package contains data runtime code for Azure Machine Learning and has been active on PyPI since 2020 (although dev started in 2019).

### How large is each release?

Each release is approximately 190MB. We release one wheel to support each of the 3 platforms (Windows, Linux, Mac), for Python 3.5, 3.6, 3.7, 3.8, and 3.9. Hence there are 15 wheels approximately 12MB each.

### How frequently do you make a release?

Roughly once every month (sometimes twice, if we need a hotfix).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've increased the limit to 25 GB.
