### ISSUE TITLE
PEP 541 Request: Warp

### ISSUE THREAD

**Issue by mmacklin** [pypa/pypi-support#1791]
### Project to be claimed

`warp`: https://pypi.org/project/warp

### Your PyPI username

`mmacklin`: https://pypi.org/user/mmacklin

### Reasons for the request

We believe the current project is squatting the "Warp" name. The project was empty since last year (provided zero functionality) until we contacted the author this week to request a transfer of the name. 

At this point they have put up a minimally functional project that we believe is a direct attempt to squat on the name with what is essentially a skeleton / placeholder library of no real utility.

This is the project we are asking to use as a replacement: https://github.com/nvidia/warp

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/woop/warp

Please see repo. history prior to March 25th showing that the repository was empty / non-functional. After my contact on this date the author has attempted to obfuscate the status of the project with what is essentially a dummy project.

### Contact and additional research

On the 25th of March I contacted the author via. a Twitter DM:

Hi William,

My name is Miles, I’m an engineer at NVIDIA - we have recently released an open source software library called Warp for Python:

[https://github.com/nvidia/warp](https://t.co/esxNIrOvmB)

and we would like distribute this from PyPi using the `warp` label which is currently in use by your project:

[https://pypi.org/project/warp/](https://t.co/1SHYNok03u)

I wasn’t sure if the project was active or not – and wanted to ask if you would consider relinquishing the name for us to use?

Thanks for your consideration.

Cheers,
Miles

----

I received no response, and then tried to contact the author via. LinkedIn:

Miles Macklin 1:59 AM

Hi from NVIDIA Willem,

We would like distribute a new PyPi package using the `warp` label which is currently in use by your project:

[pypi.org/project/warp](http://pypi.org/project/warp)

I wasn’t sure if the project was active – would you consider letting us use the name for our project ([github.com/nvidia/warp](http://github.com/nvidia/warp))?

Best,
Miles
Willem Pienaar sent the following message at 2:01 AM
View Willem’s profile Willem Pienaar
Willem Pienaar 2:01 AM

Hi Miles,

We are actively working on a project that we intend to release under the same name. So unfortunately we do want to use the PyPi package name.

Regards,
Willem
Miles Macklin sent the following message at 10:44 AM
View Miles’ profile Miles Macklin
Miles Macklin 10:44 AM

Thanks for the reply Willem, 
 
My understanding is that name squatting is not permitted by PyPi (https://peps.python.org/pep-0541/#invalid-projects), so in this case we may ask for a review from the PyPi moderators.
 
Cheers,
Miles

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by woop** [comment]
I am the author of the Warp library. Not only is this project in active use, but it has been in active use prior to any attempts to claim the name.

> what is essentially a skeleton / placeholder library of no real utility

Clearly the library IS of utility since it's in active use. This project is fully compliant with ALL the validity requirements defined in [PEP-541](https://peps.python.org/pep-0541).

**Comment by yeraydiazdiaz** [comment]
Hello @mmacklin, while it is true that name squatting is not permitted the PEP is clear in that the active projects cannot be transferred against the wishes of the owner, which is the case at the moment.
