### ISSUE TITLE
File Limit Request: tensorflow-recommenders-addons-gpu - 160 MB

### ISSUE THREAD

**Issue by rhdong** [pypa/pypi-support#1793]
### Project URL

https://pypi.org/project/tensorflow-recommenders-addons-gpu

### Does this project already exist?

- [X] Yes

### New Limit

160MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

We have limited the hashtable dim for 1-100, as mentioned in [decrease range of dim to 200](https://github.com/tensorflow/recommenders-addons#to-use-gpu-by-tfradynamic_embeddingvariable), but it's difficult to keep balance the whl size and user experience.

### Reasons for the request

The whl size increased from 100MB to 118MB for adding lots of new features, and we have tried some method to decrease the size of whl, but fail. So please help us increase the limit to 160MB, thanks a lot!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rhdong** [comment]
Hi @pradyunsg , please help increase our project limit per file, thank you ~

**Comment by pradyunsg** [comment]
I've increased the limit to 200 MB.

There's no need to @-mention me here -- it isn't going to speed things up -- I triage these tickets in bulk, when I have the free time to do so. This issue tracker is mostly handled by volunteers, so the backlog is worked through somewhat slowly.
