### ISSUE TITLE
PEP 541 Request: ethers

### ISSUE THREAD

**Issue by elyase** [pypa/pypi-support#1794]
### Project to be claimed

`ethers`: https://pypi.org/project/ethers

### Your PyPI username

`elyase`: https://pypi.org/user/elyase

### Reasons for the request

[Invalid projects](https://peps.python.org/pep-0541/#invalid-projects)

A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:

    project is name squatting (package has no **functionality** or is **empty**);

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/elyase/ethers-py

### Contact and additional research

I have sent two emails to the project owner and received no reply. The author seems to have incurred in name squatting by registering 17 empty packages on the same date in the pypi index (and similar behaviour on the [crates.io index](https://crates.io/users/EazyReal)) 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by elyase** [comment]
@yeraydiazdiaz muchas gracias!! :-)
