### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by GiardEmilien** [pypa/pypi-support#1795]
### PyPI Username

`emilien@arcane.run`

### Reason for request

- I have access to my email (so I can reset my password) but I cannot find my username and I cannot log with my mail. Could you please fetch me my username?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Username: `arcane`
