### ISSUE TITLE
File Limit Request: PySide6_Addons - 250 MB

### ISSUE THREAD

**Issue by cmaureir** [pypa/pypi-support#1797]
### Project URL

https://pypi.org/project/PySide6-Addons/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The PySide project has been active for many years starting from the initial release in Qt4 (2008), we had the initial release for Qt5 in 2018 with the 5.12 version of the PySide2 project. You can find more information of the project in https://pyside.org

As a first version, we released everything bundled on the same wheel, but with the time we have been noticing the large size is not optimal, so we started to think about plans to split the package into sub-packages.
On the PySide6 wheel package we noticed we included extra files, like a couple of modules we were not using, and debug information for a Qt-related language: QML. We removed those but the wheel was still quite large, and we couldn't keep up uploading more releases to the https://pypi.org/project/PySide6 project. We currently have been investigating compiling flags optimizations that might reduce a couple of MB from our binaries.

We bundle Qt binaries, examples, and documentation.

### Reasons for the request

Including a C++ library like Qt does add many MB to the project, and also considering that since a couple of versions ago we have universal binary wheels for our macOS users, which also increased that platform wheels size.

We wanted to start a wheel split process to make PySide6 more modular, and the initial attempt was to create `PySide6_Essentials` and `PySide6_Addons` from the `PySide6` wheel, leaving that to be a meta-wheel with a direct dependency on these two new wheels.

You can see all the information of the new wheels size here: https://download.qt.io/snapshots/ci/pyside/dev/wheelsplit2/pyside6/
The current sizes of our wheels are: 210M (macOS), 115M (Linux), and 89M (Windows), so to be safe in case the Qt-macOS binaries increase size, we are requesting 250M.

Still with this approach, the wheels are a bit large, but we are considering split those wheels further on in future releases to have a similar meta-wheel like PySide6 will be from the 6.3 release, having something like PySide6_Addons depending on many other PySide6_ModuleX packages.

In case you require more information, please let me know.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey there :wave: 
we haven't heard anything, so in case something else is missing or we can somehow help,
please let us know :)

**Comment by stonebig** [comment]
Would it be possible to publish for non-macos in waiting for pypa team answer ?

**Comment by pradyunsg** [comment]
I've increased the limit to 300 MB. Thanks for filling the issue form properly, making it easy to review this ticket! :)

**Comment by cmaureir** [comment]
Thank you! :tada:
