### ISSUE TITLE
PEP 541 Request: forge

### ISSUE THREAD

**Issue by davegaeddert** [pypa/pypi-support#1799]
### Project to be claimed

`forge`: https://pypi.org/project/forge

### Your PyPI username

`dropseed`: https://pypi.org/user/dropseed

### Reasons for the request

Looks like this package name has been claimed since 2010, and never used! I have a real use case ready to go.

### Maintenance or replacement?

Replacement

### Contact and additional research

I've reached out to https://pypi.org/user/seandstewart/ via a contact form on his website (https://seandstewart.io/contact/), but haven't been able to get a hold of him.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @davegaeddert, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by davegaeddert** [comment]
Thanks @yeraydiazdiaz!
