### ISSUE TITLE
PEP541: Transfer ownership of `gnpy` to a new maintainer

### ISSUE THREAD

**Issue by jktjkt** [pypa/pypi-support#18]
Hi, I work for the @TelecomInfraProject organization as a maintainer of the [oopt-gnpy](https://github.com/Telecominfraproject/oopt-gnpy) software. Previously, this stuff was done by James Powell (@dutc) who also created the [`gnpy` package at pypi](https://pypi.org/project/gnpy/). James is no longer with @TelecomInfraProject, unfortunately, meaning that the maintainer address listed in PyPI's Meta -> Author no longer works.

Can you please pass the ownership of [`gnpy`](https://pypi.org/project/gnpy/) to my account [`jktjkt`](https://pypi.org/user/jktjkt/)?

I was not able to secure a proper handover before James' mail account was closed. I'm sorry that our internal process flaw causes extra work for you. I'll make sure that this event does not repeat by ensuring that there are more accounts distributed among several companies which are all listed as co-maintainers.

refs Telecominfraproject/oopt-gnpy#254

**Comment by yeraydiazdiaz** [comment]
Hello @jktjkt, we would need confirmation from @dutc to proceed with the transfer. Replying to this issue is enough.

**Comment by jktjkt** [comment]
Hi @yeraydiazdiaz , it seems that we are not able to reach @dutc. We've been trying to get his explicit approval for 6+ months already, but our efforts were unsuccessful. Can we proceed without James' approval, then?

Look at, e.g., the [commit history of repo's `README.md`](https://github.com/Telecominfraproject/oopt-gnpy/commits/master/README.rst), in particular [this commit](https://github.com/Telecominfraproject/oopt-gnpy/commit/1a10495645c98333617df932614e4e6db29e80be#diff-88b99bb28683bd5b7e3a204826ead112) shows that I've resumed James' duties.

I'm sorry that @TelecomInfraProject's internal process flaw causes this extra work. Once I get access, I'll make sure that it's spread among multiple people so that this won't happen again.

**Comment by yeraydiazdiaz** [comment]
Hi @jktjkt, the owner does have a email address registered in PyPI so I've attempted contact that way. Hopefully we will hear back soon and move forward with your request.

**Comment by yeraydiazdiaz** [comment]
Hello @jktjkt, I have not received response from the owner so this project is now considered abandoned.

I will now ask an admin to perform the transfer for you.

**Comment by ewdurbin** [comment]
transfer complete.
