### ISSUE TITLE
PEP 541 Request: mathematics

### ISSUE THREAD

**Issue by arihant2math** [pypa/pypi-support#1801]
### Project to be claimed

`mathematics`: https://pypi.org/project/mathematics/

### Your PyPI username

`ashwin06`: https://pypi.org/user/ashwin06

### Reasons for the request

The last and only release was October 2013, and also the source code contains three files, two are for packaging purposes and the third one contains one function, `multiply_elements()`.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There was no linked code repository, with the source code being in the zip file in the release.

### Contact and additional research

The owner did not have an email associated with his account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @arihant2math, could you provide a repository for the project you intend to publish under that name, please?

**Comment by arihant2math** [comment]
Sure, [https://github.com/arihant2math/mathematics](https://github.com/arihant2math/mathematics)

**Comment by yeraydiazdiaz** [comment]
Thanks @arihant2math, due to the limit functionality of the project I will treat it as invalid and attempt contact with the owner allowing one week for replies.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
