### ISSUE TITLE
PEP 541 Request: astromer

### ISSUE THREAD

**Issue by cridonoso** [pypa/pypi-support#1803]
### Project to be claimed

`astromer`: https://pypi.org/project/astromer

### Your PyPI username

`astromember`: https://pypi.org/user/astromember

### Reasons for the request

I accidentally created and removed the "astromer" package when configuring the code for the first time. I deleted my account and create this new one in an attempt to fix it, but didn't work.

Is there any way to use the same name again?

Thanks

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/astromer-science/python-library

### Contact and additional research

the current owner is me

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @cridonoso, the `astronomer` package already had `astromember` as its owner so there's nothing to transfer. I assume you managed to solve your issue?

**Comment by yeraydiazdiaz** [comment]
Hi @cridonoso, that error is due you trying to upload the same version of the package `0.0.1`, try bumping the version.

**Comment by yeraydiazdiaz** [comment]
Closing as no transfer is possible.
