### ISSUE TITLE
Account email request

### ISSUE THREAD

**Issue by andydevlinsmith** [pypa/pypi-support#1804]
### PyPI Username

grndworkrenewables

### Reason for request

Not exactly an account recovery request, but related.

We are having issues adding an alias (pypi@grndwork.com) to our pypi account- the alias is not getting verification emails. (verification to my address works just fine) 

Google workspaces is requesting the message headers for the email sent from noreply@pypi.org to pypi@grndwork.com to troubleshoot. Is it possible to provide this in some way?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Is this still ongoing? If so please reopen and initiate a new email and we'll see what we can get you.
