### ISSUE TITLE
File Limit Request: cnmaps - 500 MB

### ISSUE THREAD

**Issue by Clarmy** [pypa/pypi-support#1807]
### Project URL

https://github.com/Clarmy/cnmaps
https://pypi.org/project/cnmaps/

### Does this project already exist?

- [X] Yes

### New limit

500 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This project is a package to fetch and draw chinese map easily. This package includes chinese administrative boundary files(geojson) at province level now. And I'am going to enlarge the dataset to district/county level in next release. The new dataset is about 250Mb for now. And maybe it will increase in future.

### How large is each release?

~250M

### How frequently do you make a release?

Roughly once 1 month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Have you explored making it possible to get the map data separately from the source code?

For example, NLTK hosts their data separately from the source code published on PyPI (https://www.nltk.org/data.html). That would also make it possible for the data to be managed separately from the source code (eg: being able to update the data without updating the source code or vice versa). That would also allow users to download the data once, and use it regardless of what version of the source code they're using.

**Comment by Clarmy** [comment]
@pradyunsg  Thank you for your suggestion. Maybe this request is unnecessary. I found the data is not as large as I guess because it will be compressed before uploading. I have published the new release with new dataset that only about 50Mb. If it grows beyond 100Mb in future, I will consider separate the extra-data from pypi. But I still wish it could be all data included in pypi for ease of use.

**Comment by pradyunsg** [comment]
Sounds good. If you do need to add additional data and need an increase while you migrate to an external host, please feel free to ask for it. :)
