### ISSUE TITLE
PEP 541 Request: bluesky-simulator

### ISSUE THREAD

**Issue by jooste** [pypa/pypi-support#1808]
### Project to be claimed

`bluesky-simulator`: https://pypi.org/project/bluesky-simulator

### Your PyPI username

`jellerbroek`: https://pypi.org/user/jellerbroek

### Reasons for the request

BlueSky is an air traffic simulator developed by myself and colleagues at the Technical University Delft, NL. Up until now the master version has only been available by downloading the source from Github: [https://github.com/TUDelft-CNS-ATM/bluesky](https://github.com/TUDelft-CNS-ATM/bluesky). One of the forks of the project was made available as pip package some years ago by Liam Deacon. The last update of the pip package is from 2019.

We (TU Delft) would like to start making the master version of bluesky available on pip, and to avoid the confusion of having several packages of the same project, we want to claim the `bluesky-simulator` project. I tried contacting its maintainer, Liam Deacon, but he is not replying to my email.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/TUDelft-CNS-ATM/bluesky

### Contact and additional research

I found Liam Deacon's contact information on this site: http://lightbytestechnology.co.uk. I tried contacting him through the email address provided here, but he hasn't responded to this.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @jooste, I will start the reachability process for this project which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by Liam-Deacon** [comment]
Hi @jooste - @yeraydiazdiaz has gotten in contact to explain the situation. You should now have received an invite to be an owner of the `bluesky-simulator` pypi project, which should allow you to publish new versions when needed. Hope this helps. Kind regards, Liam

**Comment by jooste** [comment]
Hi @yeraydiazdiaz, thanks for your help!
Hi @Liam-Deacon, that's a great solution, thanks! I tried reaching out to you via the email address you list on your lightbytes page, could it be that it is an outdated address? I'm also curious to hear if your group is still using bluesky!
