### ISSUE TITLE
PEP 541 Request: brainpy

### ISSUE THREAD

**Issue by chaoming0625** [pypa/pypi-support#1809]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/brainpy/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/brainpy_team/

### Reasons for the request

This package ``brainpy`` has long been deprecated. We cannot download it, cannot install it, and even cannot find the release files. The author Claudio Carvalhaes cannot be contacted. I tried to contact the author in 2021-07. But I have not got any response from him (see below). 

The github homepage of the author has also been stopped updating since 2019 (https://github.com/cgcarvalhaes?tab=repositories).  

We cannot find any download statistics of ``brainpy`` from pypistats.org (https://pypistats.org/search/brainpy) or PePy.tech (https://pepy.tech/project/brainpy). 

However, our package BranPy (https://github.com/PKU-NIP-Lab/BrainPy) is actively maintained. Thus, I believe that our package would be a better use for the ``brainpy`` project in PyPI than the currently empty and abandoned project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/PKU-NIP-Lab/BrainPy

### Contact and additional research

I have emailed the author, but I have received no response (see the following figure). I found the author also stopped updates his github since 2019. 

![Wang Chaoming - Outlook](https://user-images.githubusercontent.com/14275596/161513003-59b960bf-a224-4cdb-9ae4-32aef3d8a1e0.jpg)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @chaoming0625, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by chaoming0625** [comment]
Dear @yeraydiazdiaz , thanks for your effort on this request very much.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
