### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by C3NZ** [pypa/pypi-support#181]
Request for account recovery.

## PyPI Username

`C3NZ`

---

##  Reason for request

Reason:
My previous phone is broken beyond repair and I didn't have a backup that contained the account data in my authentication app.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete, 2FA has been disabled and a password reset initiated. After completing the password reset you should regain access to your account.
