### ISSUE TITLE
PEP 541 Request: mono

### ISSUE THREAD

**Issue by frostming** [pypa/pypi-support#1810]
### Project to be claimed

`mono`: https://pypi.org/project/mono

### Your PyPI username

`frostming`: https://pypi.org/user/frostming

### Reasons for the request

The project doesn't actually exist on the PyPI. From the https://pypi.org/help/#project-name it is possibly the case that the project name has been registered by another user, but no releases have been created. What's more, I believe it isn't a reserved name for the standard library.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/frostming/mono

### Contact and additional research

Since I cannot find the original owner and there are no other requests for it, the only thing I can do is file an issue here.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @frostming, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
