### ISSUE TITLE
PEP 541 Request: vapi-client-bindings, vmc-client-bindings, nsx-python-sdk, vsphere-automation-sdk

### ISSUE THREAD

**Issue by vmehtavmware** [pypa/pypi-support#1811]
### Project to be claimed

`PROJECT_NAME`:
* https://pypi.org/project/vapi-client-bindings
* https://pypi.org/project/vmc-client-bindings
* https://pypi.org/project/nsx-python-sdk
* https://pypi.org/project/vsphere-automation-sdk

### Your PyPI username

`USER_NAME`: `vandit.mehta`

### Reasons for the request

vapi-client-bindings, vmc-client-bindings, nsx-python-sdk, vsphere-automation-sdk are packages owned by VMware, but currently we aren't able to claim these packages, as while trying to publish the packages to pypi, we are getting error
`The name <package name> isn't allowed. See https://pypi.org/help/#project-name for more information. `

Out of these packages, we raised claim request for `vapi-client-bindings` in Issue #946 and the request was closed as well, but it seems like instead of giving ownership to the requestor (Anusha), it was released to be claimed by anyone.

Can you please transfer the ownership of these packages at the earliest to us (PyPi user: vandit.mehta).

### Source code repositories URLs

https://github.com/vmware/vsphere-automation-sdk-python

### Contact and additional research

We aren't able to contact the owner(s) of any of these packages.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've transferred `vapi-client-bindings`, `vmc-client-bindings`, `nsx-python-sdk` and `vsphere-automation-sdk` to `vandit.mehta`.
