### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by shasagaredel** [pypa/pypi-support#1813]
### PyPI Username

Jagmohan.Reen@edelweissfin.com

### Reason for request

Lost access to email. The developer has left the organisation. We need to re install account details.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I cannot find a PyPI user associated with that email address
