### ISSUE TITLE
PEP 541 Request: `subman`

### ISSUE THREAD

**Issue by septatrix** [pypa/pypi-support#1816]
### Project to be claimed

`subman`: https://pypi.org/project/subman

### Your PyPI username

`cde-ev`: https://pypi.org/user/cde-ev/

### Reasons for the request

Trying to publish a package under said name results in the following error:

> The name 'subman' isn't allowed. See https://pypi.org/help/#project-name for more information.

We choose the name as the purpose of this package is **sub**scription **man**agement for mailman3 and feel like it is a reasonable name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current development takes place at https://github.com/cde-ev/subman. It is this organizations pypi user which I entered above and who we would like to transfer the project to. If desired it would also be possible to transfer this project to my personal account first.

### Contact and additional research

As the name is not taken it seems to be prohibited/reserved for some other reasons.
I did not find any issue in this repo about this being reserved for typos or similar so my best guess is that it may be blocked due to it being an insult? However I am not native english speakers so I do not know if the word is used in this regard.

If the reason is blocking due to it being an insult we believe that our package has a legitimate claim to this name without being insulting to anyone.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @septatrix, `subman` was placed in the prohibited project names list to prevent dependency confusion attacks. @pypa/warehouse-admins, could you release the name to @septatrix, please?

**Comment by ewdurbin** [comment]
'subman' released to 'cde-ev'.

**Comment by septatrix** [comment]
Thank you. May I ask with which dependency this packet was at risk of being confused with as we know of no similar or similarly named package and pip etc. to my knowledge do not have a similarly spelled command?
