### ISSUE TITLE
PEP 541 Request: bayesian-changepoint-detection

### ISSUE THREAD

**Issue by hildensia** [pypa/pypi-support#1817]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/bayesian-changepoint-detection

### Your PyPI username

`USER_NAME`: https://pypi.org/user/hildensia

### Reasons for the request

The project was uploaded by user wanbin, who is not the author of the package and whom I cannot reach. I am the original author of the package under http://github.com/hildensia/bayesian-changepoint-detection and want to claim the project myself to update the pypi package.

### Source code repositories URLs

http://github.com/hildensia/bayesian-changepoint-detection

### Contact and additional research

No contact data for maintainer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
