### ISSUE TITLE
Project Limit Request: Home Assistant - 50 GB

### ISSUE THREAD

**Issue by balloob** [pypa/pypi-support#1819]
### Project URL

https://pypi.org/project/homeassistant/

### Does this project already exist?

- [X] Yes

### New limit

50GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Open source home automation that puts local control and privacy first.

https://www.home-assistant.io/

### How large is each release?

~30MB:

- 10MB source
- 17.2MB wheel

https://pypi.org/project/homeassistant/#files

### How frequently do you make a release?

Once every 2-3 days on average. Monthly release + ~6 betas and ~5 patch releases

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
50,000 / (30 * 8) / 12 ~= 17 -- looks like this limit will serve HA for about 17 years, assuming things don't drastically change sizes. Seems reasonable to me, so I've bumped this limit as requested. :)
