### ISSUE TITLE
Issue: PEP 541 Request: conductor

### ISSUE THREAD

**Issue by lawschlosser** [pypa/pypi-support#182]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/conductor

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/conductor

**Reasons for the request**

- **Project is invalid** - The current `conductor` pypi project is one of 114 projects authored by [_deleted user_](https://pypi.org/user/deleted-user/), all of which are blatant namesquatting infractions. 
The sole `conductor` release - `conductor-1.0.0-py3-none-any.whl` contains no actual python code:  
    ```
    top_level.txt  
    WHEEL  
    METADATA  
    RECORD  
    ```

- **Project is abandoned**
  1.  Owner unreachable - no valid contact information exists (the author's projects have the same fraudulent information posted, e.g fake email address, links to unaffiliated repositories, etc
  2. no releases within the past twelve months - the last (and only) release was on Jul 27, 2018.
  3.  no home page listed

**Maintenance or replacement?**

The following repository (or a fork of it) will act as the **replacement** https://github.com/AtomicConductor/conductor_client

**Contact and additional research**

None

**Comment by yeraydiazdiaz** [comment]
Hello @lawschlosser, the `deleted-user` account is used by admins to assign namesquatting projects when they're detected, as such there is no problem transferring the project to you.

I'll contact an admin to perform the transfer now.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by lawschlosser** [comment]
@ewdurbin @yeraydiazdiaz Thanks so much! :heart:
