### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JavaScriptDude** [pypa/pypi-support#1820]
### PyPI Username

TimothyCQuinn

### Reason for request

Lost 2FA Auth App. No token stored :(

I search through all my TOTP apps, and there is nothing. I set up my 2FA right around the time I set up my account and was a bit sloppy. Sorry.

I'll definitely be more careful next time. I don't know why I did not store the recovery key; I am very anal with using password managers.

To verify, I have my passwords and API Tokens for both Test and Prod. 

FYI - I just posted v0.1 of a new package early this morning (tiotrap) and tried to post an update but got an error (may be unrelated). My code base is updated in [Github though](https://github.com/JavaScriptDude/tiotrap).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by JavaScriptDude** [comment]
FYI - I was able to upload my project to use `pyproject.toml` and just published v0.2 now. 

This ticket is still needed but its not urgent.

**Comment by JavaScriptDude** [comment]
!PING! - I'm still maintaining several projects under this username. Please verify and help with reset.

My Projects:

1. https://pypi.org/project/zfslib/
2. https://pypi.org/project/multisort/
3. https://pypi.org/project/comstrip/
4. https://pypi.org/project/whereval/
5. https://pypi.org/project/tiotrap/

I'm posting a new version of `zfslib` in about an hour.

Thanks!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by JavaScriptDude** [comment]
Email task completed and replied. Thanks!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by JavaScriptDude** [comment]
Acknowledged. Recovery codes generated and stored and new 2FA configured.

Thanks for your assistance!
