### ISSUE TITLE
PEP 541 Request: pyeq3

### ISSUE THREAD

**Issue by bobmyhill** [pypa/pypi-support#1821]
### Project to be claimed

`pyeq3`: https://pypi.org/project/pyeq3

### Your PyPI username

`bob.myhill`: https://pypi.org/user/bob.myhill

### Reasons for the request

I believe that this repository has been abandoned, likely due to the owner being unable to continue work on the project (see additional detail below).

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Old repository: https://bitbucket.org/zunzuncode/pyeq3/src/master/
New repository: https://github.com/bobmyhill/pyeq3

### Contact and additional research

This project was maintained by James Phillips, and was associated with a website, zunzun.com, and a google group:
https://groups.google.com/g/zunzun_dot_com

As documented in that group, the website went down in March 2020. James' last contribution to the code had taken place just beforehand (see https://github.com/bobmyhill/pyeq3/graphs/contributors). 

Since March 2020, several people have tried to contact the author via email, phone and snail mail, with no success (https://groups.google.com/g/findcurves/c/K8qixlWGIu8). A new website (findcurves.com) and Google group (https://groups.google.com/g/findcurves) has been started by Ross Moffet, but the code itself is no longer being maintained.

I have posted on the new Google Group to ask whether other users would like to join me in maintaining the code, but for now, I would like to work on maintenance and bug-fixes, and release new, documented versions.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bobmyhill, I will start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
My attempts to contact the current owner were unsuccessful and I could not find any other means of contact so I've transfered the project to @bobmyhill

**Comment by bobmyhill** [comment]
@yeraydiazdiaz many thanks. If I hear back from James Phillips, I'll be happy to share or transfer ownership back to him.
