### ISSUE TITLE
PEP 541 Request: l10n

### ISSUE THREAD

**Issue by orsinium** [pypa/pypi-support#1822]
### Project to be claimed

`l10n`: https://pypi.org/project/l10n

### Your PyPI username

`orsinium`: https://pypi.org/user/orsinium

### Reasons for the request

The project was blocked by "ultranormaliztion" introduced in https://github.com/pypa/warehouse/pull/10498. The only name I found that seems to be similar after the ultranormalization is [lion](https://pypi.org/project/lion/). To my taste, these are 2 completely different words. [Lion](https://en.wikipedia.org/wiki/Lion) is an animal, [l10n](https://en.wikipedia.org/wiki/Internationalization_and_localization) is a common abbreviation for "localization". Also, if it matters, the project "lion" isn't very active nor popular, so I'm not mimicking it.

### Contact and additional research

Most likely, inapplicable. There is no described procedure for claiming "similar" names yet (see https://github.com/pypa/warehouse/issues/11139). I'm not going to replace the project with colliding name and so don't find explicit consent from the author necessary. Still, if PyPA disagrees on that matter, we can try to involve the lion's author in the process.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @orsinium, @pypa/warehouse-admins could you allow the publishing of the project, please?

**Comment by ewdurbin** [comment]
Project `l10n` released to User `[orsinium](https://pypi.org/admin/users/be26c975-692d-41b4-9e25-8bd4e549d4b8/)`
