### ISSUE TITLE
PEP 541 Request: WRF-Python

### ISSUE THREAD

**Issue by michaelavs** [pypa/pypi-support#1823]
### Project to be claimed

`WRF-Python`: https://pypi.org/project/wrf-python/

### Your PyPI username

`michaelavs`: https://pypi.org/user/michaelavs

### Reasons for the request

I work on the team that maintains WRF-Python. The previous maintainers (Bill Ladwig, Kevin Hallock, and Rick Brownrigg) have all left our organization but we unfortunately did not migrate maintainers before their departure to avoid this issue. The new maintainers are myself and @[erogluorhan](https://github.com/erogluorhan). We have been maintaining and releasing new versions of WRF-Python for about 1.5 years, but have not been able to update the PyPI version in this time, leaving our PyPI user base on a version from 2019. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/NCAR/wrf-python

### Contact and additional research

The contact link for the primary maintainer on WRF-Python PyPI (Bill Ladwig) does not work, so there has not been a way to contact the maintainers. Additionally, we are technically the current owners of the software which can be validated via the GitHub repo and the associated conda-forge channel.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @michaelavs, I have started the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from one of the owners soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
@michaelavs, one of the owners replied and has added you as an owner of `WRF-Python`.
