### ISSUE TITLE
PEP 541 Request: rfc-xmldiff (only at testpypi.org)

### ISSUE THREAD

**Issue by rjsparks** [pypa/pypi-support#1826]
### Project to be claimed

rfc-xmldiff: https://test.pypi.org/project/rfc-xmldiff/

### Your PyPI username

rjsparks: https://pypi.org/user/rjsparks

### Reasons for the request

PLEASE NOTE: this is only a request for test.pypi.org - the projects as pypi.org itself are fine

The test.pypi.org version of this project has not been touched for several years. At the time it was touched Jim Schaad was the sole maintainer. He has since passed away. Before his passing, he added me (Robert Sparks) and Henrik Levkowetz as maintainers at the actual pypi project: https://pypi.org/project/rfc-xmldiff/.

We are now modernizing the project to use test.pypi.org as part of CI/CD, and need administrative access to the project at the test version of the index.

See also the similar, and already processed request for a different repository at https://github.com/pypa/pypi-support/issues/1731

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/ietf-tools/rfc-xmldiff

### Contact and additional research

Jim passed away in late 2020. See https://mailarchive.ietf.org/arch/msg/ietf/uhn5CQBATbLvP4OZ6IkLF-4OW24/. As noted above, we had established additional maintainers for these projects at pypi.org, but did not manage to do so at test.pypi.org.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
