### ISSUE TITLE
Project Limit Request: honeybee-energy - 10 GB?

### ISSUE THREAD

**Issue by chriswmackey** [pypa/pypi-support#1829]
### Project URL

https://pypi.org/project/honeybee-energy/

### Does this project already exist?

- [X] Yes

### New limit

10 GB? I cannot understand how we hit the limit

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We are an open source project that connects Computer Aided Design interfaces to simulation engines that estimate building energy use and model occupant comfort. More information can be found on [our website](https://www.ladybug.tools/).

Our Python libraries are relatively small but we have subdivided them into different packages [as can be seen in our SDK docs here](https://discourse.ladybug.tools/pub/ladybug-tools-core-sdk-documentation). Given restrictions of how pip resolves dependencies, this has necessitated that we perform a lot of releases to keep the versions of these packages synced and compatible with one another.

Hopefully it goes without saying that PyPI provides a mission-critical service for us and our development would grid to a halt without it. The business we have founded around our open source software is not yet profitable but, if there was any way to purchase additional space for our packages from PyPI, we would undoubtedly do so.

### How large is each release?

The project is currently 428.7 kB total (or roughly 0.5 MB):
![image](https://user-images.githubusercontent.com/5567574/162574074-0ac3757c-6d15-4861-8a60-d11de3da780d.png)

We have performed ~500 releases of the project:
![image](https://user-images.githubusercontent.com/5567574/162573992-085f9ed9-a7d3-48be-9ab1-9a345f2fc626.png)

Taking this together, the amount of space consumed by the project should be `0.5 MB * 500 releases = 250 MB`. So I was expecting that we were not even at 1 GB yet and I don't know how we have hit the 10 GB limit.

### How frequently do you make a release?

Roughly once every few days in order to keep all of our core packages synced with one another.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I can confirm that the project has hit the total size limit of 10.0 GiB already.

There are 504 releases currently. Each release that I looked at has a roughly 500KB wheel file and a 26 MB source distirbution file.

**Comment by pradyunsg** [comment]
It's unclear to me what should be done here, since this project's size limit is already at 10 GB (which is has now hit). I'll mark this as awaiting response, once OP is able to provide context on why the source distribution is so big and whether they need an increased limit (if so, please edit the first post and title) or they will delete certain files or change their workflows.

**Comment by chriswmackey** [comment]
Thank you for the response and for the explanation, @pradyunsg . 

I did not realize that the source code of the release was ~25MB since only the `.whl` file was showing up under the [Download Files section of the latest releases](https://pypi.org/project/honeybee-energy/1.89.2/#files). Moreover, I can see that our test suite and our online docs are somehow being included in the `.tar.gz` source of the releases, which is definitely not our intention. The actual source code itself is only ~1.5 MB when it is fully decompressed and the compressed `.tar.gz` file is less than half of a MB. I will change our CI to make sure that we only release the source code without the tests going forward.

Can you confirm that the latest releases of honeybee-energy still have this 25 MB source code even though it does not show up under the Download Files section next to the .whl files?

Also, I would ideally like to go back through our previous releases and replace them with versions that exclude our test suite. If you could point me to any documentation that might help me do a mass update of the source code in our previous releases, this would be greatly appreciated.

Thank you, again.

**Comment by chriswmackey** [comment]
Hi @pradyunsg ,

I just wanted to confirm that [I have edited our automated deployment to exclude all tests and docs](https://github.com/ladybug-tools/honeybee-energy/pull/860). This has dropped the size of our sdist from ~25 MB down to 0.33 MB. Furthermore, I have gone through the honeybee-energy release history and deleted ~50 of the oldest releases in order to free up some space. I am performing similar exclusions of tests and docs on our other PyPI packages. So you should not have any issues with us pushing large distributions in future releases.

My only concern now is that we have a lot of large recent releases of honeybee-energy, which could mean that we eventually run out of space again in the future. From what I can tell, it does not seem possible to edit the sdist of previous releases. However, it looks like I can delete the sdist while still leaving the `.whl` file. Given that the latest releases of honeybee-energy seem to work with only the `.whl` file and not the sdist, it seems like deleting the sdist of the latest releases could be a nice solution.

Can you confirm that deleting the sdist of the latest honeybee-energy releases will still allow our end-users to `pip install honeybee-energy` (as long as the `.whl` file remains)?

If so, I'll do that. If not, would it be possible to get a limit extension to 11 GB just for this package? By my calculations, that limit increase should now last us another 5-10 years.

**Comment by pradyunsg** [comment]
I've bumped it to 15 GB. That should last for a while. :)

**Comment by chriswmackey** [comment]
Thank you, @pradyunsg ! That will work very well.
