### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Danielhiversen** [pypa/pypi-support#183]
Request for account recovery.

## PyPI Username

`dahoiv`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

Lost my phone

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete, 2FA has been disabled and a password reset initiated. After completing the password reset you should regain access to your account.
