### ISSUE TITLE
PEP 541 Request: united-states-congress

### ISSUE THREAD

**Issue by stevesdawg** [pypa/pypi-support#1830]
### Project to be claimed

`united-states-congress`: https://pypi.org/project/united-states-congress

### Your PyPI username

`sseshan7`: https://pypi.org/user/sseshan7

### Reasons for the request

The `united-states-congress` project has not been updated since Dec 2016, but the code base has had multiple improvements made since then, and is still actively being worked on.

To allow users to more easily install and run the scripts in this project, I would like to transfer the project to my username, so that it can be updated with the latest source code.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/unitedstates/congress/

### Contact and additional research

It was initially uploaded to PyPI by @illegalnumbers in 2016. If @illegalnumbers has any objection to transferring this project, I am open to hear your thoughts, and discuss.

Initial packaging proposal documented here: https://github.com/unitedstates/congress/issues/188

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @stevesdawg, I have started the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied stating they would like to keep control of the project, as per PEP 541 no transfer is possible.

**Comment by stevesdawg** [comment]
Thanks for the response @yeraydiazdiaz, could you attach the correspondence for transparency?

I had also reached out to the owner via email on Monday April 11th. This is the message I sent:

> Hello Ben!
This is Shriv Seshan (https://github.com/stevesdawg), reaching out to you about the united-states-congress package on PyPI. I wanted to reach out to you to ask about transferring ownership to myself (https://pypi.org/user/sseshan7/), in order to continue maintaining the package, and releasing new versions to PyPI.
It's been a while since it was last updated (Dec 2016)! I've been actively using and contributing to the congress repo for the last year, and would love to see it more easily accessed by other users via PyPI.
Some relevant issues you can take a look at that I opened regarding this:
https://github.com/unitedstates/congress/pull/283
https://github.com/unitedstates/congress/issues/282
https://github.com/pypa/pypi-support/issues/1830
The last issue is in the PyPI support repository. If you want to continue the discussion or grant permission, commenting on that issue would be the best way to proceed! Thanks in advance Ben.
--
Shrivathsav Seshan

**Comment by michaelblyons** [comment]
Is there an appeal process? We're 6 years into new versions without updates from the current owner.
