### ISSUE TITLE
File Limit Request: oasislmf - 150 MB

### ISSUE THREAD

**Issue by sambles** [pypa/pypi-support#1832]
### Project URL

https://pypi.org/project/oasislmf/

### Does this project already exist?

- [X] Yes

### New Limit

150MB 

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Hello, our project its an open source loss modelling framework (catastrophe risk analysis)  and we've been on PyPI since 2018. 

The package wheel we upload contains statically built C++ binaries (for consistency across Linux distributions) for a running risk analysis kernel. 

### Reasons for the request

Up until this release it was within the limit (49mb~)  however we've added parquet support which has pushed the total wheel size to 107mb  `107M Apr 11 09:02 oasislmf-1.26.0rc1-py3-none-manylinux1_x86_64.whl`

Is it possible to increase the single file limit to 150mb, the bundled static binaries might increases slightly but shouldn't exceed `150mb` per release (monthly upload).  

Over the long term we hope to reduce the dependence on our C++ kernel by switching to `numba`, so the total package size should hopefully decrease again   

All the best, 
-The OasisLMF Team 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've increased the limit to 200 MB. Thanks for properly filling out the issue template, and making this ticket easy to review. :)
