### ISSUE TITLE
Project Limit Request: SimpleITK - 25 GB

### ISSUE THREAD

**Issue by blowekamp** [pypa/pypi-support#1833]
### Project URL

https://pypi.org/project/SimpleITK/

### Does this project already exist?

- [X] Yes

### New limit

25GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

SimpleITK ([www.simpleitk.org](http://www.simpleitk.org/)) is a free, open source, image analysis toolkit which is in widespread use in the bio-medical research community (about 90,000 downloads per month from PyPI). The project has been active been active for over 10 years.

The project takes a long time to compile at around 2 hours. For most users if the binary wheel is not available then the package is considered broken and unusable for them. We expect the total project size to increate as more releases are made.

A key requirement of the scientific process is reproducibility. Recently, the lack of reproducibility of scientific publications garnered attention from the US National Academies, "Reproducibility and Replicability in Science", US National Academies report 2019. According to the report highlight ([pdf](https://nap.nationalacademies.org/resource/25303/R&R.pdf)) "To help ensure the reproducibility of computational results, researchers should convey clear, specific, and complete information about any computational methods and data products that support their published results in order to enable other researchers to repeat the analysis. "
To enable reproducibility of image analysis algorithms relying on the SimpleITK toolkit we need to make all toolkit versions readily available, so that both old and new research results can be validated using the specific software version that was used in the original publication. We are therefore asking for a size limit exemption.

### How large is each release?

Each binary wheel is about 50MB (windows more efficient at 30MB). Make each release about 1-1.5GB.

For the next 2.2.0 release we are planning on having the following binary wheels, for each currently supported Python version (3.7-3.10):
  - cp3X-cp3X-macosx_10_9_x86_64
  - cp3X-cp3X-macosx_11_0_arm64
  - cpX-cpX-manylinux_2_17_x86_64.manylinux2014_x86_64
  - cp3X-cp3X-win_amd64
  - cp3X-cp3X-manylinux_2_17_aarch64.manylinux2014_aarch64
  
A source distribution is also uploaded.

For patch releases, the same type of binary wheels are produced plus additional wheels for new python versions (or architectures if needed).

The entire SimpleITK library was architected to make a comparable "small" API interface to  the Insight Toolkit (itk.org) which has a very large C++ template API library. The size of the package is extremely efficient for the amout of the instantiated C++ code compiles (hence long compile time).

The underlying ITK C++ toolkit does use some "vendorized" C++ libraries.

No, example data is include in the project.

### How frequently do you make a release?

Once every 3-6 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
At ~1.5 GB/release, this should be sufficient for 10 releases. At 3-6 months per release, assuming the size of the releases don't change drastically, that should be good for 2.5-5 years. :)

I've increased the limit to 25 GB, as requested. Thanks for properly filling out the issue template, and making this easy to review.
