### ISSUE TITLE
PEP 541 Request: arx

### ISSUE THREAD

**Issue by jrollins** [pypa/pypi-support#1834]
### Project to be claimed

`arx`: https://pypi.org/project/arx

### Your PyPI username

`jrollins`: https://pypi.org/user/jrollins

### Reasons for the request

I believe the existing project was either abandoned or was maybe just a skeleton for a project that never really got off the ground.  I have contacted the upstream author and they have agreed to release the name (see below).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://git.ligo.org/jameson.rollins/arx

### Contact and additional research

I have contacted the upstream maintainer of the project currently holding the name (@greysonhead https://github.com/graysonhead), and they have very graciously agreed to transfer it to me:

https://github.com/graysonhead/arx/issues/2

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by jrollins** [comment]
great!  thank you!
