### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cx1111** [pypa/pypi-support#1835]
### TestPyPI Username

Not pypi, but test.pipi. Username is:

cx1111

### Reason for request

Lost access to the email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
TestPyPI 2FA disabled and password reset issued.
