### ISSUE TITLE
PEP 541 Request: automatize

### ISSUE THREAD

**Issue by ttportela** [pypa/pypi-support#1836]
### Project to be claimed

`automatize`: https://pypi.org/project/automatize

### Your PyPI username

`tarlis`: https://pypi.org/user/tarlis

### Reasons for the request

I looked for this project name and haven't found. Now, i see that it is empty for more than a year. I build a data science package that is under publishing by IEEE International Conference on Mobile Data Management, an important event in the area. Then I just want to use the same name as it is the one I am publishing in the conference.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ttportela/automatize

### Contact and additional research

I have not received answer from the previous owner to the date.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @ttportela, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
