### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cjng96** [pypa/pypi-support#184]
Request for account recovery.

## PyPI Username

`cjng96`

---

##  Reason for request

Reason:
Lost 2FA authentication app. :(

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete, 2FA has been disabled and a password reset initiated. After completing the password reset you should regain access to your account.
