### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by that1guy15** [pypa/pypi-support#1840]
### PyPI Username

apstra

### Reason for request

Lost access to login password and email address for this account. https://pypi.org/user/apstra/

We do not know the email addressed used on the account and cannot initiate a password reset. We only have the username 'apstra' and password hash used in old repos.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by that1guy15** [comment]
thanks @ewdurbin, is there any way to send this email to another address in our domain? I know the maintainers emails but Im not sure which email was used as primary for this account and they are all very old accounts.

**Comment by that1guy15** [comment]
Also if I could get the email address this email is coming from it will help me track it down in our mail system. Thanks

**Comment by ewdurbin** [comment]
Please email support@pypi.org from an address on the same domain, including a reference to this issue, and we can provide the address.

**Comment by ewdurbin** [comment]
Address provided to a user emailing from the same domain. A password reset flow using that address will be sufficient for account recovery.
