### ISSUE TITLE
File Limit Request: ocp-vtk - 180 MB

### ISSUE THREAD

**Issue by roipoussiere** [pypa/pypi-support#1841]
### Project URL

https://pypi.org/project/ocp-vtk

### Does this project already exist?

- [X] Yes

### New Limit

180

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project provides Python wrappers for OCCT (Open Cascade Technology).

It is an open-source development platform for 3D modeling, that is developed and supported by [Open Cascade SAS](https://www.opencascade.com/).

OCCT is at the core of the [CadQuery](https://cadquery.readthedocs.io/en/latest/) project, which started in 2013.

All necessary dependencies are included in the wheel and we made an effort to reduce the size of the wheels as much as possible.

### Reasons for the request

For now, CadQuery must be installed using Conda, which seem to be tedious for an important part of the project community ([see issue #153 for instance](https://github.com/CadQuery/cadquery/issues/153)).

We recently found a way to bundle OCP as a Python wheel, that will be a huge improvement for the community.

Publishing it on Pypi will facilitate even more the project installation, and therefore its adoption.

Each ocp-vtk release is used to support Windows, MacOS and Linux, and python 3.8, 3.9, and 3.10, so we produce 9 files in total:

- ocp-vtk_macos-cp3.10: **150 MB**
- ocp-vtk_macos-cp3.8: **142 MB**
- ocp-vtk_macos-cp3.9: **142 MB**
- ocp-vtk_ubuntu-cp3.10: **159 MB**
- ocp-vtk_ubuntu-cp3.8: **150 MB**
- ocp-vtk_ubuntu-cp3.9: **150 MB**
- ocp-vtk_windows-cp3.10: 59.4 MB
- ocp-vtk_windows-cp3.8: 60.1 MB
- ocp-vtk_windows-cp3.9: 59.9 MB

You can see an example of our CI build [here](https://github.com/roipoussiere/OCP/actions/runs/2156108607).

We need to extend the file size limit for the macos and linux wheels. Their size can vary a little bit, since ocp-vtk is based on OCCT releases, but not drastically. That's why we ask for 180MB for all these 6 wheels, in order to anticipate an eventual file increase in the next OCCT releases.

Note that a new OCCT release is published [approximately each year](https://github.com/Open-Cascade-SAS/OCCT/releases).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've increased the limit to 200 MB.
