### ISSUE TITLE
PEP 541 Request: crypto-tools

### ISSUE THREAD

**Issue by roccobarbi** [pypa/pypi-support#1843]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/crypto-tools

### Your PyPI username

`USER_NAME`: https://pypi.org/user/roccobarbi

### Reasons for the request

No package by this name seems to exist, and I'd like to use it to publish a series of libraries that help with writing code to solve traditional "pen and paper" cryptographic messages (a.k.a. cryptograms).

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/roccobarbi/crypto_tools

### Contact and additional research

I tried to verify if such a project exists, but could not find any trace of it, therefore I can't contact a previous owner.
I can't find this name as that of an existing package, either in the standard library or on pypi.
Still, I get the error message: The name 'crypto-tools' isn't allowed.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @roccobarbi, `crypto-tools` was placed in the prohibited project names list to prevent dependency confusion attacks. One of the @pypa/warehouse-admins should be able to release the project name to you soon.

**Comment by ewdurbin** [comment]
'crypto-tools' released to 'roccobarbi'.
