### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by nikwl** [pypa/pypi-support#1849]
### PyPI Username

`nikwl`

### Reason for request

Lost 2FA authentication app. I was setting up 2FA in a rush last october and didn't get a chance to setup the recovery tokens. Since then I've changed phones and didn't realize that the old phone had my pypi account linked to it. I can provide any identifying information, within reason, to verify that I am the real account holder. Thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
