### ISSUE TITLE
Lost 2FA Access

### ISSUE THREAD

**Issue by urielmann** [pypa/pypi-support#185]
Hello,

My name is Uri Mann and I'm the account holder of srcsrv package. My user name is urimann and the email address associated with it is [email redacted].
Last month traded my phone back to t-mobile for an updated device. I made a mistake and didn't realized that I had to disable 2FA before switching. My recovery codes were also on the phone I reset and traded back and I'm locked out of the account. I re-enabled Google Authenticator on my new phone but the codes are no longer valid.

Is there a way to restore access? I'd very much like to keep the package name since it is very significant. I also have access to an account by the same name on test.pypi.org.

Please, please help.
-Uri Mann
[phone number redacted]

**Comment by ewdurbin** [comment]
PyPI Username: `urimann`

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete, 2FA has been disabled and a password reset initiated. After completing the password reset you should regain access to your account.

**Comment by urielmann** [comment]
Thanks for your help
-Uri
