### ISSUE TITLE
File Limit Request: openturns - 125 MB

### ISSUE THREAD

**Issue by jschueller** [pypa/pypi-support#1851]
### Project URL

https://pypi.org/project/openturns/

### Does this project already exist?

- [X] Yes

### New Limit

125

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

OpenTURNS is a large C++ library with Python bindings using swig.
There is no data nor things we can strip, mainly some libraries and their dependencies (libxml, tbb, cminpack, nlopt, hdf5, ceres, pagmo, ...)

### Reasons for the request

We were already around the 100mb limit for the osx binaries, but now with pagmo and its dependency to boost it is around 120mb.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've increased the limit to 200 MB. Please be mindful of how this package size grows in the future. :)

**Comment by jschueller** [comment]
thank you
