### ISSUE TITLE
PEP 541 Request: tensorrt

### ISSUE THREAD

**Issue by pranavm-nvidia** [pypa/pypi-support#1856]
### Project to be claimed

`tensorrt`: https://pypi.org/project/tensorrt/

### Your PyPI username

`nvidia`: https://pypi.org/user/nvidia/

### Reasons for the request

The existing package is essentially empty, including only a README and basic metadata files, and seems to exist only to name squat. 
Note that this project was posted by the same user who was previously found to be squatting `openvino`. See https://github.com/pypa/pypi-support/issues/636 for details.

### Maintenance or replacement?

Replacement

### Contact and additional research

Like in https://github.com/pypa/pypi-support/issues/636, the maintainer email provided, others@WTF.com, is a fake address and unreachable. There is no other contact information provided.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by pranavm-nvidia** [comment]
Thanks!
