### ISSUE TITLE
PEP 541 Request: fakeredis

### ISSUE THREAD

**Issue by bmerry** [pypa/pypi-support#1857]
### Project to be claimed

`fakeredis`: https://pypi.org/project/fakeredis

### Your PyPI username

`bmerry`: https://pypi.org/user/bmerry

### Reasons for the request

I am currently the primary maintainer on the project, and have been making releases for some time. However, on PyPI I am only a maintainer, not an owner, so I am unable to fully manage the project or to add new maintainers. I have been unable to reach the original owner for over a year. I am requesting that my project membership be upgraded from maintainer to owner.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/jamesls/fakeredis. I have commit rights so it will not be immediately necessary to fork it, but I will do so (to a newly-created organisation) if I am unable to add collaborators. You should be able to verify that all merges for the last while have been done by me.

### Contact and additional research

I emailed `@jamesls` on 22 Nov 2021 requesting ownership and have had no reply. He is still using the same address on recent Github commits (e.g. [this one](https://github.com/jmespath/jmespath.py/commit/9eb120d75cab800117c2e6649f27e3a37a9b7748)) so I presume he's still alive and on the internet.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @bmerry, I will start the reachability process for your request which can take up to 6 weeks. I'll attempt contact with @jamesls as the owner of the project, hopefully we will hear back soon and proceed with the transfer.

**Comment by jamesls** [comment]
Hi, sorry for the delay, I rarely check that email.  I'll take care of this today.  Sorry for the delay.

**Comment by jamesls** [comment]
Just want to double check the pypi username, right now I see [bmerry-ska](https://pypi.org/user/bmerry-ska/) as a maintainer, but on this ticket you're requesting [bmerry](https://pypi.org/user/bmerry/) to be added.  Just wanted to confirm the pypi username of bmerry as the correct name.

**Comment by jamesls** [comment]
I've added you as an owner.  Let me know if you need anything else.

**Comment by bmerry** [comment]
> I've added you as an owner. Let me know if you need anything else.

Thanks @jamesls. I've created a new Github organisation called fakeredis-py and invited you. Can you transfer the jamesls/fakeredis repository there? (instructions [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository))

**Comment by bmerry** [comment]
Closing since the PyPI permissions have been sorted out. @yeraydiazdiaz if you have an alternative email for @jamesls could you forward [this comment](https://github.com/pypa/pypi-support/issues/1857#issuecomment-1116960283) to him? I still only have the address that he rarely checks so am unable to reach him.

**Comment by jamesls** [comment]
> > I've added you as an owner. Let me know if you need anything else.
> 
> Thanks @jamesls. I've created a new Github organisation called fakeredis-py and invited you. Can you transfer the jamesls/fakeredis repository there? (instructions [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository))

Sure thing, I'll take care of this today.
