### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by digitalsleuth** [pypa/pypi-support#1859]
### PyPI Username

`digitalsleuth`

### Reason for request

PyPi tells me I have 2FA set up, but it's not showing up anymore in my 2FA apps (either Google or Microsoft). 

I have my user/pass (confirmed working through recent publishing to PyPi), and my API tokens, but I cannot log into the PyPi site to confirm my 2FA application and re-add.

My account is not lost, but I cannot log in to register / re-register my 2FA application.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by digitalsleuth** [comment]
Bump - any progress on this?

**Comment by digitalsleuth** [comment]
Good day, I pushed the new branch and replied as of Thursday morning. Cheers!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
