### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alifzl** [pypa/pypi-support#1860]
### PyPI Username

alifzl

### Reason for request

Dear PyPI community,

recently I upgraded my iPhone, not considering my G-Authenticator will not migrate the 2FA submissions of mine.
Plus, unfortunately I hesitated to take recovery codes from PyPI. I'd truly be happy if you could help me out with reseting the 2FA function or at least send me a recovery code.
thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
