### ISSUE TITLE
Project Limit Request: Intel-TensorFlow - 30 GB

### ISSUE THREAD

**Issue by wei-v-wang** [pypa/pypi-support#1863]
### Project URL

https://pypi.org/project/intel-tensorflow/

### Does this project already exist?

- [X] Yes

### New limit

30 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project hosts Intel's released binary for TensorFlow. In future it will feature more Windows TensorFlow binaries. 

### How large is each release?

1 GB per night and  a rolling 20 days of wheels to keep. 

### How frequently do you make a release?

nightly 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by wei-v-wang** [comment]
Hi, any updates on this request? Who should I contact offline for such request?

**Comment by di** [comment]
I've set the total project size limit for `intel-tensorflow` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.
