### ISSUE TITLE
File Limit Request: tfjsa - 200 MB

### ISSUE THREAD

**Issue by zhangys11** [pypa/pypi-support#1865]
### Project URL

https://pypi.org/project/tfjsa

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This repo can be a good starting point for building your own tfjs (tensorflow-js)-based web applicaitons.
The original project is developed for ASP.Net MVC (http://zhangys.org.cn/DeepLearning). Now I rewrite it as a Flask web app.

We provide 5 apps:
    General image classification based on a pre-trained mobilenet model on imagenet.
    Object detection trained on COCO
    Style transfer. Provided by Reiichiro Nakano (https://github.com/reiinakano/arbitrary-image-stylization-tfjs)
    A binary classifier for judging fundus image quality.
    A plant disease classifier trained on PlantVillage dataset (doi: 10.17632/tywbtsjrjv)

### Reasons for the request

This package contains some trained ANN models for inference. Although I've removed some unused models, for the next release, I will add new models and it will soon exceed the 100MB.  Request for 200MB for both the whl and gz.

Thanks, best regards~

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `tfjsa` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by zhangys11** [comment]
Thank you, Dustin



***@***.***
 
From: Dustin Ingram
Date: 2022-04-28 11:24
To: pypa/pypi-support
CC: zhangys11; Author
Subject: Re: [pypa/pypi-support] File Limit Request: tfjsa - 200 MB (Issue #1865)
I've set the upload limit for tfjsa to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
