### ISSUE TITLE
PEP 541 Request: vnlp

### ISSUE THREAD

**Issue by meliksahturker** [pypa/pypi-support#1867]
### Project to be claimed

https://pypi.org/project/vnlp/

### Your PyPI username

https://pypi.org/user/meliksahturker

### Reasons for the request

I am the developer of an open source NLP tool, named **vnlp**. I would like to register it under the name "vnlp" on pypi. This namespace is currently being used, however the project is inactive for 4 years with source code resulting in 404 error.

I tried to reach the owner of the project using the e-mail provided in the [vnlp pypi page](https://pypi.org/project/vnlp/) by sending 3 e-mails in the last 6 weeks with no success.
You can find the e-mails [here](https://drive.google.com/file/d/1OK0RueqG1dRhdzei5jpzwR38E8qwkWRx/view?usp=sharing).

Hence I would like to take over this namespace and publish my project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: https://gitlab.com/vzhong/vnlp/ . It results in a "404 Page Not Found" error.
My project: https://github.com/vngrs-ai/vnlp

### Contact and additional research

I tried to reach the owner of the project using the e-mail provided in the [vnlp pypi page](https://pypi.org/project/vnlp/) by sending 3 e-mails in the last 6 weeks with no success.
You can find the e-mails [here](https://drive.google.com/file/d/1OK0RueqG1dRhdzei5jpzwR38E8qwkWRx/view?usp=sharing).
Moreover I tried to reach him via DM on Twitter with no success again.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @meliksahturker, I can confirm the project is not installable and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Hi @vzhong, thanks for your reply. PEP 541 states that moderators should not transfer the project against the will of its current owner.

However, given that you registered the project 4 years ago and made no changes to it until the request was raised and I attempted contact with you, I think you should consider allowing the transfer in the spirit of sharing the limited names available in PyPI. If you would like to transfer the project you can add `meliksahturker` as an owner in the project's collaboration page https://pypi.org/manage/project/vnlp/collaboration/

That being said I will close this issue as contact has been made and it is now up the current owner to make a decision.
