### ISSUE TITLE
PEP 541 Request: dtypes

### ISSUE THREAD

**Issue by DrInfiniteExplorer** [pypa/pypi-support#1868]
### Project to be claimed

`dtypes`: https://pypi.org/project/dtypes

### Your PyPI username

`DrInfiniteExplorer`: https://pypi.org/user/DrInfiniteExplorer

### Reasons for the request

Attempting an upload with plain `py -m twine upload dist/*` fails, while and upload with `py -m twine upload dist/* --verbose` yields

```
Response from https://upload.pypi.org/legacy/:
         400 The name 'dtypes' isn't allowed. See https://pypi.org/help/#project-name for more information.
INFO     <html>
          <head>
           <title>400 The name 'dtypes' isn't allowed. See https://pypi.org/help/#project-name for more
         information.</title>
          </head>
          <body>
           <h1>400 The name 'dtypes' isn't allowed. See https://pypi.org/help/#project-name for more information.</h1>
           The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
         The name &#x27;dtypes&#x27; isn&#x27;t allowed. See https://pypi.org/help/#project-name for more information.


          </body>
         </html>
```

I noticed that there are other requests for unallowed names that have been granted by using this form (like #1816 ), so here I am.

I have put together a small library that makes life using `ctypes` easier, like enabling forward-declaration of types for pointers by lazily resolving them behind properties as needed, and making declarations nicer.
I choose the name `dtypes` because it is supposed to extend the functionality of `ctypes` with new, better features, much like the D language was started as a _better c[++]_.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing: None
Intended `dtypes`: https://github.com/DrInfiniteExplorer/dtypes

### Contact and additional research

There is no existing `dtypes` library on pypi, and `ctypes` isn't pip'able either AFAIK.
The best search result for `dtypes` is [db-dtypes](https://pypi.org/project/db-dtypes/) which is (imo) quite far from plain `dtypes`.
`dtype` gives some results with the prefix `dtype-`, but given that it's singular and namespaced/prefixed I don't think there should be any conflict there either.
I hope that this has just been deemed 'to similar' by some name distance algorithm and that human intervention might unlock the name 🙏

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @DrInfiniteExplorer, `dtypes` was placed in the prohibited project names list for dependency confusion reasons. A @pypa/warehouse-admins should be able to release the project to you soon.

**Comment by DrInfiniteExplorer** [comment]
Yo cool dudes how's it going?

**Comment by ewdurbin** [comment]
not all dudes here.

name released to `DrInfiniteExplorer` User on PyPI.
