### ISSUE TITLE
No recovery email - cmancone

### ISSUE THREAD

**Issue by cmancone** [pypa/pypi-support#187]
I can't get into my account and the password recovery is not working - I'm not receiving my email.  The account name is cmancone.  My current email address is cmancone@gmail.com, but I'm guessing I registered with either cmancone@ufl.edu or cmancone@astro.ufl.edu (neither of which I have access to anymore).  Any chance you can help me recover access?

If it helps, the package I'm trying to update ([mygrations](https://pypi.org/project/mygrations/)) has my gmail address listed under authorship.

Thank you,
Conor

**Comment by ewdurbin** [comment]
Looks like there is another address aside from those listed above associated with the account, I've emailed you at that address and the address you supplied above.

If you've lost access to that address we'll go through another verification process to help you regain access to your account.

**Comment by cmancone** [comment]
I still have access to that email, have recovered my password, and changed my email address.  Thank you!
