### ISSUE TITLE
Project Limit Request: tensorflow-cpu - 150 GB

### ISSUE THREAD

**Issue by mihaimaruseac** [pypa/pypi-support#1870]
### Project URL

https://pypi.org/project/tensorflow-cpu/

### Does this project already exist?

- [X] Yes

### New limit

150GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TF has 3 main projects for each release:
* `tensorflow`
* `tensorflow-gpu`
* `tensorflow-cpu`

The first one contains the most implementations for both GPU and CPU kernels but there are users that use the other 2 to install localized wheels. In particular, `tensorflow-cpu` is used by people who don't want to download a 500MB wheel with GPU kernels if they only want to run TensorFlow on CPU (the CPU-only wheel is 200MB)

### How large is each release?

Total ~8GB/release

Each Linux wheel has ~210MB
Each Windows wheel has ~250MB
Each MacOS wheel has ~230MB

For each python version, we need ~690MB (rounded to 700MB). We support 4 Python versions in parallel, so this leads to ~2.7GB per release/RC.

We usually do 2 RCs and one final release, so that would be a total of ~8GB/release

### How frequently do you make a release?

Quarterly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `tensorflow-cpu` to 150 GB on PyPI. Please be mindful of the frequency of releases at that size.
