### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by romanin-rf** [pypa/pypi-support#1873]
### PyPI Username

programmer-from-parlament

## Reason
- Authentication application removed

## If you read more
An _**authentication app**_ has been _**installed on the phone**_. I decided to sell the phone because I bought a new one and _**reset it to factory settings**_ and only now realised after about a month that I now have no access to my pypi account.

## The account had modules such as
- [playsoundsimple.py](https://github.com/romanin-rf/playsoundsimple.py)
- [tpng.py](https://github.com/romanin-rf/tpng.py)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by romanin-rf** [comment]
Already!

ср, 12 окт. 2022 г. в 15:40, Ee Durbin ***@***.***>:

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
