### ISSUE TITLE
File Limit Request: acuitylite - 300 MB

### ISSUE THREAD

**Issue by lileiigithub** [pypa/pypi-support#1874]
### Project URL

https://pypi.org/project/acuitylite/

### Does this project already exist?

- [X] Yes

### New Limit

300MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Acuitylite is an end-to-end neural-network deployment tool for embedded systems. Acuitylite support converting caffe/tflite model to a TIM-VX case. In addition, Acuitylite support asymmetric uint8 quantization.
Acuitylite is a project owned by VeriSilicon, INC. (A leading Silicon Platform as a Service company, https://github.com/VeriSilicon)

We want to release a new version of Acuitylite, but hitting the file size limit of 100MB problem.  We have reduced the size of the release package, but it still hitting the file size limit. So could you please help to change the size limit?

Thanks.

### Reasons for the request

We expect the new file size limit for our new features need more storage. We hope the release size of 300MB is good. Thanks very much.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `acuitylite` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by lileiigithub** [comment]
Great, we'll be careful, thanks very much.
