### ISSUE TITLE
PEP 541 Request: NNCF

### ISSUE THREAD

**Issue by MarkByun** [pypa/pypi-support#1875]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/nncf/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/markbyun

### Reasons for the request

Current project's listed owner and maintainers are unavailable and Intel requests new contact to be mark.byun@intel.com.

### Source code repositories URLs

Current project repo is "https://github.com/openvinotoolkit/nncf" and I will not make new repo.

### Contact and additional research

![NNCF_owner_contact_mail](https://user-images.githubusercontent.com/100335829/165003802-ca516c5f-835b-445a-8bda-0c4b12be8952.PNG)
As you can see from the email, we contacted the owner two weeks ago and got all authority for maintaining github repo already, but we cannot contact the owner anymore now.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @MarkByun :wave:
Just to clarify a couple of things, the pypi contact is alexander kozlov (intel), the pypi maintainer is https://pypi.org/user/vshampor/ but I don't know how Vinnam Kim enters the picture. Is that the 'project owner' you mentioned?

Also regarding the topic "Maintenance or replacement?" you intend to maintain, right?

**Comment by MarkByun** [comment]
Hi Cristian,

The picture was attached to show that we tried to get NNCF project ownership for github from Alexander and Vinnam Kim is my team member and he got the right from Alexander now, but we cannot request the same thing for Pypi account because we cannot contact with Alexander anymore.
Yes, we want to maintain the NNCF project instead of Alexander and this is our company’s decision.

Thanks,
Mark

From: Cristián Maureira-Fredes ***@***.***>
Date: Thursday, May 5, 2022 2:22 PM
To: pypa/pypi-support ***@***.***>
Cc: Byun, Mark ***@***.***>, Mention ***@***.***>
Subject: Re: [pypa/pypi-support] PEP 541 Request: NNCF (Issue #1875)

Hey @MarkByun<https://github.com/MarkByun> 👋
Just to clarify a couple of things, the pypi contact is alexander kozlov (intel), the pypi maintainer is https://pypi.org/user/vshampor/ but I don't know how Vinnam Kim enters the picture. Is that the 'project owner' you mentioned?

Also regarding the topic "Maintenance or replacement?" you intend to maintain, right?

**Comment by yeraydiazdiaz** [comment]
Hello @MarkByun, as moderators we are obliged to contact the current owner directly ourselves, and this must be the PyPI project owner, not the GitHub repository owner.

I do have one question, you mention your intention to maintain the project but you also state you will not create a new repo, does that mean you already have ownership of the existing repo?

Regardless I will start the reachability process for your request, which can take up to 6 weeks.

**Comment by MarkByun** [comment]
Hi Vasily,

Thank you for your support.

Best regards,
Mark

From: Vasily Shamporov ***@***.***>
Date: Tuesday, May 10, 2022 2:42 AM
To: pypa/pypi-support ***@***.***>
Cc: Byun, Mark ***@***.***>, Mention ***@***.***>
Subject: Re: [pypa/pypi-support] PEP 541 Request: NNCF (Issue #1875)

Owner of the NNCF package here. I have added https://pypi.org/user/markbyun as a maintainer for the project. I will be keeping ownership of the package to myself for the time being.

**Comment by yeraydiazdiaz** [comment]
Thank you for your quick reply @vshampor.

**Comment by MarkByun** [comment]
Hi,

Yes, I will maintain the project and my team member has ownership for existing github repo.

Thanks,
Mark

From: Yeray Díaz ***@***.***>
Date: Sunday, May 8, 2022 7:01 PM
To: pypa/pypi-support ***@***.***>
Cc: Byun, Mark ***@***.***>, Mention ***@***.***>
Subject: Re: [pypa/pypi-support] PEP 541 Request: NNCF (Issue #1875)

Hello @MarkByun<https://github.com/MarkByun>, as moderators we are obliged to contact the current owner directly ourselves, and this must be the PyPI project owner, not the GitHub repository owner.

I do have one question, you mention your intention to maintain the project but you also state you will not create a new repo, does that mean you already have ownership of the existing repo?

Regardless I will start the reachability process for your request, which can take up to 6 weeks.
