### ISSUE TITLE
PEP 541 Request: PySh

### ISSUE THREAD

**Issue by Ovsyanka83** [pypa/pypi-support#1876]
### Project to be claimed

`PySh`: https://pypi.org/project/PySh

### Your PyPI username

`Ovsyanka`: https://pypi.org/user/Ovsyanka

### Reasons for the request

* The latest version of this package has been released in 2009
* This package only has two versions, none of which contain any source code or readme. It is not even installable through `pip install`
* I have contacted the author and he refused to delete the package, claiming that this is the part of his work history

Due to the reasons above, I believe that this project is and always was completely unmaintained. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

* Current project has no source repository listed
* My project's source repository is: https://github.com/Ovsyanka83/pysh

### Contact and additional research

I have contacted the author once and he refused to delete the package, claiming that this is the part of his work history.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Ovsyanka83 it does sounds like the pypi project has been not only [abandoned](https://peps.python.org/pep-0541/#abandoned-projects) but never active. I think your request is valid to replace and hopefully @pypa/warehouse-admins will address this soon.

**Comment by yeraydiazdiaz** [comment]
Hi @Ovsyanka83 I can confirm the project has two releases with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
