### ISSUE TITLE
PEP 541 Request: inferex

### ISSUE THREAD

**Issue by paulfsheridan** [pypa/pypi-support#1877]
### Project to be claimed

`inferex`: https://pypi.org/project/inferex

### Your PyPI username

`USER_NAME`: https://pypi.org/user/paulfsheridan

### Reasons for the request

It looks like this project has been abandoned (the last update was on 18 Oct 2017). We'd like to use it for our company's open-source project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Source code for our public Python package will be available at: https://github.com/Inferex

### Contact and additional research

Written correspondence between the package owner, and our CEO:

![Screenshot 2022-04-25 at 21 14 37](https://user-images.githubusercontent.com/32114499/165167535-328d6bb8-3c59-4a25-842b-f99fe0bc8510.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @paulfsheridan, you seem to already be the owner of this project, I'll assume the project was transferred already.
