### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gbastien** [pypa/pypi-support#1879]
### PyPI Username

gauthierbastien

### Reason for request

My e-mail is still correct, I updated password, I can connect with username/pwd but then I can not authenticate with Two-factor authentication because my GSM is new and the Google authenticator I use does not work...
Thank you!
Gauthier Bastien

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by gbastien** [comment]
Hi,

I come back to you regarding this, could you please help me?

Thanks !

Gauthier

**Comment by gbastien** [comment]
Hi @ewdurbin

sorry to disturb you, can you help?  I can login with my pypi account but do not get to work with the 2FA, I used Google Authenticator and lost my previous phone...

Could you please just disable 2FA on my account and I will setup a new and follow pypi help guidelines (generating recovery codes...)

Thank you!

Gauthier

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by gbastien** [comment]
Hi @ewdurbin 

I responded to your email, sorry for delay, I am attending the https://2022.ploneconf.org/ ;-)

Many thanks,

Gauthier

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
