### ISSUE TITLE
Spam packages on PyPI

### ISSUE THREAD

**Issue by z3ntu** [pypa/pypi-support#188]
Most packages from this user https://pypi.org/user/007gzs/ look like name-squatting known/short names; where the packages don't contain anything except the setup.py file which doesn't do anything nefarious either.

The following packages don't seem to contain any code:
* django-cool
* gdb
* sf
* 007
* nfc
* svg
* bi
* en
* sn
* unionpay

The rest of the packages from that user (basically the ones with a Project description on PyPI) seems to contain legitimate code.

Sorry if this is the wrong place to report something like this but I couldn't find a better place.

**Comment by jakirkham** [comment]
Any thoughts on these?

**Comment by di** [comment]
Thanks for the report, most of these have been removed as namesquatting. In the future, please contact admin@pypi.org instead.
