### ISSUE TITLE
PEP 541 Request: trex

### ISSUE THREAD

**Issue by berrysauce** [pypa/pypi-support#1881]
### Project to be claimed

`trex`: https://pypi.org/project/trex

### Your PyPI username

`berrysauce`: https://pypi.org/user/berrysauce

### Reasons for the request

I think that the project is abandoned because:
1. The description just says "This is a test description"
2. The project hasn't been updated since 2014 and is still on version 0.0.0
3. The project author's email doesn't work anymore (tried to reach out before making this request)
4. The project's repository doesn't exist anymore

I would like to use it for a CLI project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project's repository according to PyPi: https://github.com/anthonyalmarza/trex-py (doesn't exist)
The new project's repository: https://github.com/berrysauce/trex

Since I know this request can take some time to be completed, I'm still working on the project I want to replace the current one with.

### Contact and additional research

I tried contacting the owner via the listed contact email on PyPi (anthony@reeliolabs.com) but I got a Mail Delivery System error (message couldn't be delivered). I also didn't find any additional contact info on the GitHub or Twitter profile of the author.

Also, it looks like the domain reeliolabs.com (from the email) doesn't even belong to the author anymore.

[This site](https://hunter.io/verify/anthony@reeliolabs.com) shows the following details about the email's status:
<a href="https://hunter.io/verify/anthony@reeliolabs.com"><img src="https://i.ibb.co/qjxgwC3/Screenshot-2022-04-26-at-21-42-29-Email-Verifier-Verify-email-address-with-free-email-checker-Hunter.png" alt="Screenshot-2022-04-26-at-21-42-29-Email-Verifier-Verify-email-address-with-free-email-checker-Hunter" border="0"></a>

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @berrysauce, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by berrysauce** [comment]
Awesome! Thank you!

**Comment by berrysauce** [comment]
Hey, any updates already @yeraydiazdiaz? Thanks again!

**Comment by berrysauce** [comment]
Hey @yeraydiazdiaz, any updates? Thanks!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
