### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by srobertson** [pypa/pypi-support#1882]
### PyPI Username

scott@triv.io

### Reason for request

I no longer have access to the scott@trivi.io email address.  But I do have access to git repository.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by srobertson** [comment]
any word on this?

**Comment by ewdurbin** [comment]
Please email support@pypi.org with the email address you'd like associated with the account. Please include a reference to this GitHub issue.
