### ISSUE TITLE
Name squatting package removal

### ISSUE THREAD

**Issue by ylathouris** [pypa/pypi-support#1883]
### PyPI Username

ylathouris

### Reason for request

Some of my packages have been removed from PyPI. I hadn't published much code to them so I think it might be due to name squatting concerns. However, they haven't been published for long (much less than a year) and I just tried to push changes to one of them. Can someone please explain what my options are?  

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
This is not an account recovery request. Can you pleas provide names of projects you're attempting to publish to?

**Comment by di** [comment]
Closing due to lack of response.
