### ISSUE TITLE
PEP 541 Request: github

### ISSUE THREAD

**Issue by VarMonke** [pypa/pypi-support#1885]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/github

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Var

### Reasons for the request

The project, namely `github` has been released on the 30th of January, 2013. There has been no updates regarding this package, and has been stale. I'd like to take over this project name, and put my own Python Wrapper over the Github API.
I have tried to contact the owner of the project on the 13th of April, 2022, but have not received a reply.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/VarMonke/Github-API-Wrapper

### Contact and additional research

![image](https://user-images.githubusercontent.com/94229714/165460599-5c1c543e-f7f3-41da-b098-273ad2863a70.png)
![image](https://user-images.githubusercontent.com/94229714/165460623-839d80bf-fadb-4dcf-9118-b2e1a6295517.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Ovsyanka83** [comment]
The author of this package has another name-squatted package: dititalocean. No readme, no code. Should we do anything about this as well?

**Comment by domdfcoding** [comment]
@Ovsyanka83 do you mean [digitalocean](https://pypi.org/project/digitalocean/) rather than dititalocean?

**Comment by Ovsyanka83** [comment]
> @Ovsyanka83 do you mean [digitalocean](https://pypi.org/project/digitalocean/) rather than dititalocean?

Yes, I did. But I deleted my comment since it will be more logical for the author of python-digitalocean to reclaim that package instead. I've already contacted him.

**Comment by VarMonke** [comment]
Ah I see. No worries - and hopefully so. 
Have a good one!

**Comment by yeraydiazdiaz** [comment]
Hello @VarMonke, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owners and allow one week for replies before proceeding with the transfer.

**Comment by VarMonke** [comment]
Hey! Sorry to bother you. Is there something else I'm supposed to do, to proceed? Do let me know. Thank you

**Comment by Ovsyanka83** [comment]
Give him time, please. Hi allows only one week but you never know when he comes back to check. It's almost never more than 15 days and your request will most likely be among the first for him to work on so just be patient.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
