### ISSUE TITLE
PEP 541 Request: httpie-edgegrid

### ISSUE THREAD

**Issue by robertolopezlopez** [pypa/pypi-support#1886]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/httpie-edgegrid/
`PROJECT_NAME`: https://test.pypi.org/project/httpie-edgegrid/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Roberto.Lpez.Lpez
`USER_NAME`: https://test.pypi.org/user/Roberto.Lpez.Lpez

### Reasons for the request

Hi,

I am creating this PEP-541 request on behalf of my company, Akamai Technologies. The project httpie-edgegrid was developed by Akamai. When the current owner of the project left the company we lost control over it.

In the last months we have been fixing bugs and adding some new feature. We would like to get once again ownership over this, abandoned project.

The last release done for this project was in 2017, as you can see in the release history
![image](https://user-images.githubusercontent.com/1519467/165493412-1f0e1a19-b61b-4b4a-bd53-2347fdf78ec6.png)
In test.pypi.org, there were just two releases done, in January 2021. That's more than 12 months ago.
![image](https://user-images.githubusercontent.com/1519467/165493597-d106ff05-40ab-48e1-81a4-aa686045b0f9.png)

On the other hand, the project owner does not seem reachable on the email address I have found on the PyPI project. Normal, because she does not work in Akamai any more. This person is just unreachable.
<img width="801" alt="image" src="https://user-images.githubusercontent.com/1519467/165494401-7bec0609-6388-46f7-bc0f-c9d2df7b3037.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/1519467/165494493-3316c3a8-cc44-4da3-916d-83c5f21adf77.png">

Regarding the current owner, she has not done any contribution to this project since 2019. This is clearly visible in the commits page https://github.com/akamai/httpie-edgegrid/commits/master 

Here you will be able to see the improvements which we have done in the last weeks on this project. https://github.com/akamai/httpie-edgegrid/commits/master

Because of all those reasons listed above, I consider that a project ownership transfer is reasonable, under the conditions listed in PEP-541. If you have any further question, please do not hesitate on contacting me.

Kind regards,

Roberto

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/akamai/httpie-edgegrid/

### Contact and additional research

![image](https://user-images.githubusercontent.com/1519467/165500244-cfb85e5d-3b8d-4ab3-abde-d0ed7c3d4cab.png)

<img width="801" alt="image" src="https://user-images.githubusercontent.com/1519467/165500015-d8447f0d-3f63-4eac-ac5e-f34da93e534d.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/1519467/165499933-3b4c3539-7aec-4326-87a9-1901ef5feb4b.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by robertolopezlopez** [comment]
If possible, I would like to claim ownership for the test.pypi.org corresponding project as well

https://test.pypi.org/project/httpie-edgegrid/

Please let me know if any further proof is needed. Thanks in advance.

**Comment by robertolopezlopez** [comment]
Also, as extra proof of continued work on the official httpie-edgegrid repository: we have just published v2.0.0, with breaking changes and enhancements

https://github.com/akamai/httpie-edgegrid/releases/tag/v2.0.0

**Comment by robertolopezlopez** [comment]
Hi,

Sorry to insist. Any update on this issue? Thanks

**Comment by robertolopezlopez** [comment]
Hi @yeraydiazdiaz or any other moderator in this queue

Do you mind to share your thoughts, please?

Regards

**Comment by yeraydiazdiaz** [comment]
Hello @robertolopezlopez, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by robertolopezlopez** [comment]
awesome, thanks @yeraydiazdiaz

**Comment by yeraydiazdiaz** [comment]
I have transferred the project in PyPI and Test PyPI to you.
