### ISSUE TITLE
File Limit Request: itk-elastix - 150 MB

### ISSUE THREAD

**Issue by dzenanz** [pypa/pypi-support#1888]
### Project URL

https://pypi.org/project/itk-elastix/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`itk-elastix` is part of [ITK](https://pypi.org/project/itk/). It has been around since August 2019.

We already split ITK into several core modules, and many "remote" modules, one of which is `itk-elastix`. It is big because it contains [elastix](https://github.com/SuperElastix/elastix). Example data is not bundled.

### Reasons for the request

The most recent tag of `itk-elastix` breached the package size limit (two wheels just shy of 100MB, third 119MB). The [CI run log](https://github.com/InsightSoftwareConsortium/ITKElastix/runs/6196956638?check_suite_focus=true).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `itk-elastix` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by dzenanz** [comment]
Thank you.
