### ISSUE TITLE
PEP 541 Request: smol

### ISSUE THREAD

**Issue by lbluque** [pypa/pypi-support#1889]
### Project to be claimed

`smol`: https://pypi.org/project/smol

### Your PyPI username

`lbluque`: https://pypi.org/user/lbluque

### Reasons for the request

This project has been registered by another user, but has no releases.
pypa/warehouse#11270

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Nothing has been published for the current project,

Repo to replace with [here](https://github.com/CederGroupHub/smol)

### Contact and additional research

I can not find the project on PyPI, so do not have the contact information of the current owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Ovsyanka83** [comment]
Please, fix your issue's title to the proper project name.

**Comment by lbluque** [comment]
If I can get the contact information for the user squatting the name `smol` I can attempt to contact them. (however I can not find it myself since nothing under that name is on PyPI)

**Comment by yeraydiazdiaz** [comment]
Hello @lbluque, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by AstraLuma** [comment]
Hello! I am the owner (todo: change name on pypi).

This was for the Smol MOdpack Launcher https://github.com/astraluma/smol but I am unlikely to actually release this project. Certainly not in an appreciable time frame.

I hereby release the package name `smol` to the Statistical Model On Lattices.

**Comment by yeraydiazdiaz** [comment]
Thank you for your quick reply @AstraLuma, I have transferred the project to @lbluque.
