### ISSUE TITLE
File Limit Request: k-Wave-python - 300 MB

### ISSUE THREAD

**Issue by waltsims** [pypa/pypi-support#1890]
### Project URL

https://test.pypi.org/project/k-Wave-python/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This project is a python interface to accelerated GPU binaries of a pseudo-spectral solver of the Westervelt equation for non-linear acoustics. Currently we are shipping compiled GPU accelerated binaries from the [k-Wave](http://www.k-wave.org/) with the package. In the future we will try to compile from source locally, but this is currently not possible.

### Reasons for the request

We expect/hope the release size to decrease in the future.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `k-Wave-python` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by waltsims** [comment]
When trying to publish on test, I'm getting ``` Received "503: first byte timeout"      ``` error. Is this related to this limit or something else? Thank you
