### ISSUE TITLE
File Limit Request: comet-pkg - 105 MB

### ISSUE THREAD

**Issue by akshay9594** [pypa/pypi-support#1891]
### Project URL

https://test.pypi.org/manage/project/comet-pkg/

### Does this project already exist?

- [X] Yes

### New Limit

105 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

The project is a compiler using MLIR. It depends on certain pre-built binaries to perform optimizations.

### Reasons for the request

I am requesting the increase to accommodate the pre-built binaries mentioned above.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `comet-pkg` to 200 MB on TestPyPI. Please be mindful of the frequency of releases at that size.
