### ISSUE TITLE
File Limit Request: hail - 150 MB

### ISSUE THREAD

**Issue by daniel-goldstein** [pypa/pypi-support#1892]
### Project URL

https://pypi.org/project/hail/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

hail is a scalable scientific analysis toolkit that we have hosted on PyPI since 2018. The python package works both on a user's laptop and on Spark clusters often run on cloud providers. As such we have to bundle in a JAR that is used in conjunction with pyspark (our largest dependency) to operate in a Spark cluster setting. We have worked hard to keep our jar size under the 100MB limit by minimizing the number of Java dependencies that we bundle into our JAR, but have sometimes needed to do so to maintain version compatibility with Spark versions on cloud providers, which can often be slow to update. We do not bundle in large example data.

### Reasons for the request

As we've added support for additional clouds, we've added their sdk's as dependencies of our project. We've tried to minimize this bloat by including only the necessary authentication and blob-storage libraries, but ultimately this tipped us over the edge. We assert in our CI system that our wheel size does not exceed 100MB and we are now at 101MB. We do not expect it to increase considerably in the future as adding a cloud provider is a rare event. We hope to eventually *decrease* our wheel size by creating separate builds for different platforms, but that would require a large refactoring effort on our end and would stall us considerably in the near term.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `hail` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
