### ISSUE TITLE
TestPyPI Account recovery request

### ISSUE THREAD

**Issue by ShyPixie** [pypa/pypi-support#1893]
### PyPI Username

ShyPixie

### Reason for request

I asked for this to be done in https://github.com/pypa/pypi-support/issues/1564, but only my account for PyPI, and not TestPyPI, was recovered.

Thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ShyPixie** [comment]
Bump

**Comment by ShyPixie** [comment]
@ewdurbin

**Comment by ewdurbin** [comment]
TestPyPI account does not have 2FA enabled. You can recover access with a password reset.

**Comment by ShyPixie** [comment]
> TestPyPI account does not have 2FA enabled. You can recover access with a password reset.

@ewdurbin as exposed on the first issue #1564, the registered email don't exist anymore so I can't reset the password.

**Comment by ShyPixie** [comment]
> Another user account (ShyPixieTest) on test.pypi.org has the email address matching the pypi.org user.
> 
> Please delete this user on test.pypi.org or change it's primary email. Once that is complete I'll assign ShyPixie TestPyPI User the primary email address associated with ShyPixie on PyPI.

Done.

**Comment by ewdurbin** [comment]
All set, the ShyPixie user on TestPyPI now has same primary email address as ShyPixie user on PyPI. You can proceed with a standard password reset to regain access to your account on test.pypi.org.
