### ISSUE TITLE
PEP 541 Request: graphtheory

### ISSUE THREAD

**Issue by ufkapano** [pypa/pypi-support#1894]
### Project to be claimed

`graphtheory`: https://pypi.org/project/graphtheory

### Your PyPI username

`ufkapano`: https://pypi.org/user/ufkapano

### Reasons for the request

Good morning,
I contacted the owner of the 'graphtheory' project (David Amos) and he removed his project in order to release the project name for me. However, I still can not upload my project under the name 'graphtheory'. I suppose that the name 'graphtheory' is still reserved in order to keep the history of PyPI.
Please, help me in publishing my project on PyPI.
Regards,
Andrzej Kapanowski

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The original project is removed by the owner (David Amos).
Here is the Homepage of my project:
https://github.com/ufkapano/graphtheory

### Contact and additional research

[Gmail_graphtheory_on_ PyPI.pdf](https://github.com/pypa/pypi-support/files/8588538/Gmail_graphtheory_on_.PyPI.pdf)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @ufkapano, the project still exists in PyPI but it currently has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer, which is now complete.

**Comment by ufkapano** [comment]
Hello,
Thank you very much for your help.
Regards,
Andrzej Kapanowski
