### ISSUE TITLE
PEP 541 Request: boi

### ISSUE THREAD

**Issue by dradux** [pypa/pypi-support#1898]
### Project to be claimed

`boi`: https://pypi.org/project/boi

### Your PyPI username

`dradux`: https://pypi.org/user/dradux

### Reasons for the request

As far as I can see there is no existing project with the name `boi`; however, an attempt to create one returns the following: 

`HTTP Error 400: The name 'boi' is too similar to an existing project.`

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://gitlab.com/drad/boi

### Contact and additional research

I was not able to contact a current owner because I do not think there are any.

In searching pypi I do see a few similar package names (`boi-balance` and `mortgage-boi`); however I do not see this as confusing; both look to be related to banking and are much more descriptive (not easily confused) names.

I appreciate the time and help!

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, this project name is considered to be in conflict with https://pypi.org/project/bol/, which could be easily confused for `boi` and vice versa. Is there another project name you'd be able to use instead?

**Comment by dradux** [comment]
Thanks for checking @di could you check ibuild or ibuilder? I have tried ibuild and get the too similar error as well.

**Comment by di** [comment]
Looks like `ibuild` would conflict with https://pypi.org/project/lbuild/ and https://pypi.org/project/1build/, but `ibuilder` is available!

**Comment by dradux** [comment]
Great! I was able to upload as ibuilder. Thanks for your help in this @di!
