### ISSUE TITLE
File Limit Request: wenet - 500 MB

### ISSUE THREAD

**Issue by robin1001** [pypa/pypi-support#1899]
### Project URL

https://pypi.org/project/wenet/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

it's a popular speech recognition framework, and we want python binding for it.

### Reasons for the request

The project depends on a lot of big third-party shard libraries, such as openfst, libtorch.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `wenet` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
