### ISSUE TITLE
PEP 541: Transfer of abandoned project Mosek to Mosek ApS

### ISSUE THREAD

**Issue by ulfworsoe** [pypa/pypi-support#19]
I would like to request a transfer of the Mosek project to `https://pypi.org/user/mosek/`.

I have not found a way to contact the listed maintainer, and the project have only a single release from 2014 (which is a repackaging of the official MOSEK release from back then).

I am currently the official maintainer if the Python interface for Mosek at https://mosek.com (and at github: https://github.com/Mosek), so I would like to be able to start updating the packages regularly.

References pypa/warehouse#1506

@aszekMosek

**Comment by yeraydiazdiaz** [comment]
Hi @ulfworsoe, we haven't received a reply to our emails so we consider this project abandoned. Could you confirm you PyPI username so we can proceed with the transfer?

**Comment by ulfworsoe** [comment]
I would like to use the "mosekadmin" account (with email info@mosek.com).

And thank you  for helping out.

**Comment by yeraydiazdiaz** [comment]
Thanks @ulfworsoe I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
transfer complete.
