### ISSUE TITLE
Issue: Limit Request: deeplc - 300MB

### ISSUE THREAD

**Issue by RalfG** [pypa/pypi-support#190]
**Project**

deeplc - https://pypi.org/project/deeplc/

**Size of release**

300MB

**Which indexes**

PyPI

**Reasons for the request**

DeepLC is a deep learning application that predicts peptide LC retention times. The models, which are required for predictions, exceed the default size limit of 60MB. We might add more models in the future, which will further increase the size of the package.

**Comment by di** [comment]
Hi @RalfG, it looks like you're still making releases, do you still need this limit raised? Or can we raise it to a smaller amount for now?

We generally do not provide such large limits to packages that contain pre-trained models. Is it possible for you to externally host these models?

**Comment by RalfG** [comment]
Hi @di, thanks for the reply! As you mention this is not standard procedure, we will opt to host the models on our GitHub repository, so the limit does not need to be raised. Thanks!
