### ISSUE TITLE
PEP 541 Request: PyScript

### ISSUE THREAD

**Issue by jezdez** [pypa/pypi-support#1903]
### Project to be claimed

`PyScript `: https://pypi.org/project/PyScript

### Your PyPI username

`jezdez`: https://pypi.org/user/jezdez

### Reasons for the request

Anaconda and a number of people have released the PyScript project during the PyCon US 2022 keynote: https://www.anaconda.com/blog/pyscript-python-in-the-browser

Anaconda's CEO @pzwang gave one of the keynotes: https://us.pycon.org/2022/about/keynote-speakers/#peter

The project in question hasn't received releases for a while (since 2006) and would go a long way to make sure [PyScript](https://github.com/pyscript/pyscript) can be released on PyPI.

Full disclosure: I work at Anaconda

Announcement: https://engineering.anaconda.com/2022/04/welcome-pyscript.html

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/pyscript/pyscript

### Contact and additional research

https://github.com/pyscript/pyscript
https://www.anaconda.com/blog/pyscript-python-in-the-browser
https://us.pycon.org/2022/about/keynote-speakers/#peter
https://engineering.anaconda.com/2022/04/welcome-pyscript.html

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @jezdez, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by jezdez** [comment]
Thank you @yeraydiazdiaz!
