### ISSUE TITLE
PEP 541 Request: bain-wizard-interpreter

### ISSUE THREAD

**Issue by Holt59** [pypa/pypi-support#1905]
### Project to be claimed

bain-wizard-interpreter

### Your PyPI username

Holt59

### Reasons for the request

The name is not allowed by pypi and have no clue why. Name looks unrelated to other projects, does not seem to be an existing project?

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/Holt59/bain-wizard-interpreter

### Contact and additional research

I don't think there is a current owner since the project does not exist on PyPi.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Holt59, `bain-wizard-interpreter` was placed in the prohibited projects names list for reasons of dependency confusion. A @pypa/warehouse-admins should be able to release the project name to you.

**Comment by di** [comment]
I've transferred `bain-wizard-interpreter` to `Holt59`. This project name was originally prohibited due to a dependency confusion attack -- note that you will be unable to publish a `bain_wizard_interpreter-0.0.2.tar.gz` distribution, but all other versions and distributions should be fine.
