### ISSUE TITLE
File Limit Request: Thermobar - 500 MB

### ISSUE THREAD

**Issue by PennyWieser** [pypa/pypi-support#1907]
### Project URL

https://pypi.org/project/Thermobar/

### Does this project already exist?

- [X] Yes

### New limit

500 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I have written a tool for performing calculations of pressure and temperature from the composition of minerals (about to be submitted for publication) to help predict volcanic hazards. https://thermobar.readthedocs.io/en/latest/. This work is currently performed mostly in Excel by my field, which is very inefficient. This tool is already being widely used. 

I have recently added a number of pretrained machine learning models using both onnx and pkl formats, these scrips are currently only available in R from the original authors of the models, and its advantageous for the community to have everything in a single package in python (I have coded up >150 models). 

The reason for the model duplication is because onnx keeps the value the same as scipy versions change, but cant currently be used to implement the extra trees voting the authors built into R, hence pkls for this. 

I am getting the error 

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         File too large. Limit for project 'Thermobar' is 100 MB. See           
         https://pypi.org/help/#file-size-limit for more information.  

(P.S. I'm really sorry I'm a python beginner, I dont think its an indvidual file limit as none of my files are 100 Mb. It makes more sense its a project limit). 

### How large is each release?

I have already compressed the pkl files as much as is feasible. 

My release pre PyPI compression is 354 MB. 

### How frequently do you make a release?

On average once a month, but I have now finished the package, so I anticipate less than once every 3 months moving forwards

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @PennyWieser :wave: have you consider to place your models in other server, so when people use the model can have a method to fetch that data? Lately I found a project which provide that option through a command argument https://github.com/mne-tools/mne-python/blob/main/mne/tests/test_transforms.py#L34  but I guess you could expose it as a custom method.

**Comment by pradyunsg** [comment]
I believe you're hitting the per-file size limit of 100 MB, not the per-project limit of 10 GB.

**Comment by PennyWieser** [comment]
To clarify, is the per file "one push", because none of my physical files (.py, .ipynb, .pkl) exceed 100MB?

**Comment by PennyWieser** [comment]
Do I need to post in the file inrease, or could you possibly grant me a file (e.g. 1 push) increase to 500 MB

**Comment by pradyunsg** [comment]
The file size limit is for the distribution files, like `Thermobar-0.0.22.tar.gz`. Typically, with setuptools, those are generated in the dist/ directory.

**Comment by PennyWieser** [comment]
Okay thanks, that's currently 287 so 500 MB will give me some wiggle room. Thanks!

**Comment by cmaureir** [comment]
I've set the upload limit for `Thermobar` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day!
