### ISSUE TITLE
PEP 541 Request: emmer

### ISSUE THREAD

**Issue by cryoTUD** [pypa/pypi-support#1910]
### Project to be claimed

`emmer`: https://pypi.org/project/emmer/

### Your PyPI username

`ajakobi`: https://pypi.org/user/ajakobi

### Reasons for the request

It seems this project has been abandoned:

1. The empty version 0.0.0 was created in 2015 and has since not been updated
2. The package does not contain any code or link to code repository
3. The package does not contain any project description.

I would like to use the package name for an academic research software package.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no code repository linked to the current project.

I would like to replace it with the following project I intend to publish in its place:

https://gitlab.tudelft.nl/aj-lab/emmer

### Contact and additional research

I have not been able to contact the current owner. Since no code repository is attached to the project there is no possibility to leave an issue request.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @cryoTUD, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by cryoTUD** [comment]
Many thanks @yeraydiazdiaz. Any update on this?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
