### ISSUE TITLE
File Limit Request: TorchRec_Nightly - 200 MB

### ISSUE THREAD

**Issue by RenfeiChen-FB** [pypa/pypi-support#1913]
### Project URL

https://pypi.org/project/torchrec-nightly/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TorchRec is a PyTorch domain library built to provide common sparsity & parallelism primitives needed for large-scale recommender systems (RecSys). It allows authors to train models with large embedding tables sharded across many GPUs.

We have made the efforts to reduce the binary size of our PyPI releases by limiting the supported CUDA arch to be V100 GPU (CUDA 7.0) and A100 GPU (CUDA 8.0). However, we want to support more CUDA architectures so the final compiled binary size can exceed 100 MB.

### Reasons for the request

project contains large compiled binaries to maintain platform/architecture/GPU support. In order to support more CUDA architecture (CUDA6.0 for p100; CUDA7.0 for v100; CUDA8.0 for a100), we need to compile a relatively big wheel file for the user to download. The currently 100 MB limits us from building a binary supporting multiple CUDA architectures.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by colin2328** [comment]
cc https://github.com/orgs/pypa/teams/warehouse-admins - similar request https://github.com/pypa/pypi-support/issues/1912

**Comment by cmaureir** [comment]
I've set the upload limit for `TorchRec_Nightly` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
