### ISSUE TITLE
File Limit Request: Jaxlib-alpa - 350 MB

### ISSUE THREAD

**Issue by zhisbug** [pypa/pypi-support#1914]
### Project URL

https://pypi.org/project/jaxlib-alpa/

### Does this project already exist?

- [X] Yes

### New Limit

350 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project
Alpa is a Python library (https://github.com/alpa-projects) developed by UC Berkeley RISE Lab to support automated large-scale training and inference of deep neural networks on distributed GPUs and TPUs.

Jaxlib-alpa is the C++ backend of Alpa. It compiles many CUDA kernel codes.

we have made our best effort to reduce static linking but this is the best we can do now.

### Reasons for the request

Currently, our compiled project is around 280Mb. We foresee it will increase slightly a bit to exceed 300MB after we add more features. So we ask for 350Mb to host this project, thanks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @zhisbug :wave: I think everything with your request is in order. I'm certain @pypa/warehouse-admins will react soon and enable the 350M for your project.

**Comment by cmaureir** [comment]
I've set the upload limit for `Jaxlib-alpa` to 350 MB on PyPI. Please be mindful of the frequency of releases at that size.
