### ISSUE TITLE
(possibly) PEP 541 Request: typeshed

### ISSUE THREAD

**Issue by brainwane** [pypa/pypi-support#192]
Moving this over from [this tweet](https://twitter.com/okapies/status/1225604759752601600).

**Project to be claimed**

`typeshed`: https://pypi.org/project/typeshed/

**Your PyPI username**

Not sure! Yuta Okamoto requested this via Twitter.

**Reasons for the request**

> Hi. I found typeshed on https://pypi.org/project/typeshed/ but it refers to the non-official codebase, no longer maintained, and, especially, typeshed isn't intended to publish on pypi. I think it should be removed and blocked to avoid confusion. Any idea?

**Maintenance or replacement?**

I think Yuta Okamoto thinks it should just be taken down.

**Contact and additional research**

**Comment by di** [comment]
See also: https://github.com/python/typeshed/issues/3001

**Comment by okapies** [comment]
I'm sorry to cause you an inconvenience. I haven't noticed this repository. Yes, it seems typeshed is unofficial and not maintained. I think typeshed team should take over the privilledges to prevent confusion. Thanks.

**Comment by di** [comment]
I've removed the project and blocked the name from being registered per https://github.com/python/typeshed/issues/3001.

**Comment by okapies** [comment]
Thanks!
