### ISSUE TITLE
PEP 541 Request: breakfast

### ISSUE THREAD

**Issue by matthuska** [pypa/pypi-support#1920]
### Project to be claimed

`breakfast`: https://test.pypi.org/project/breakfast

### Your PyPI username

`matthuska`: https://pypi.org/user/matthuska

### Reasons for the request

The project "breakfast" did not exist in PyPI, and I have recently uploaded my first release of my tool to pypi.org. However, there is was a project called breakfast at test.pypi.org. It was inactive for the last ~3 years and never published to pypi itself, and I contacted the owner to ask him if he is planning to continue with that project, and if not then could I use the name. He agreed, and deleted his project from test.pypi.org, but it is still not possible to push my project there.

In short: I already have the "breakfast" project at pypi.org, and am requesting to also have the same project at "test.pypi.org", which was agreed upon by its previous owner.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Previous: https://github.com/curtis-turner/breakfast

My project: https://github.com/rki-mf1/breakfast

### Contact and additional research

---- email request to the current owner:

Hi Chris,

I'm a computational biologist, and over the last few months I developed a tool that we use at my work for identifying potential Covid outbreaks: "breakfast" (roughly stands for Fast outBreak detection...). I checked pypi and conda for name conflicts and didn't see any, but I didn't think to check [test.pypi.org](http://test.pypi.org/). I see now that you uploaded a test package with that name a few years ago, but didn't end up publishing a package to pypi itself. If you're not going to continue with that project could you do me a favor and delete the test pypi breakfast package so that I can upload my tool there? Here's a link to my repo if you're curious:

https://github.com/rki-mf1/breakfast/

Best regards,
Matt

--- reply:

Hey Matt, 

Sure thing I have no need for this package and I will delete it from test pypi as soon as I get the chance. Good luck with your project.

Curtis Turner

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @matthuska, we have a policy by which the owners of the projects in PyPI get automatic ownership of the equivalent projects in TestPyPI so I have transferred the project to you.
