### ISSUE TITLE
File Limit Request: cadquery-ocp - 200 MB

### ISSUE THREAD

**Issue by jmwright** [pypa/pypi-support#1922]
### Project URL

https://pypi.org/project/cadquery-ocp/

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is a sub-package of the [CadQuery project](https://pypi.org/project/cadquery/). We have been off of PyPi for a long time because of the complexity of building wheels for OCP, which is our set of bindings to the OpenCASCADE CAD kernel. I have created a release with only the Windows wheels uploaded, because they are smaller than 100MB. The Linux and MacOS wheels are all between 140MB and 160MB in size, so I can't upload them. We have wheels for Python 3.8, 3.9 and 3.10 on each OS.

A community member recently requested a size increase for the [ocp-vtk](https://pypi.org/project/ocp-vtk/) package which allowed them to get everything working. The cadquery-ocp package will be the final home.

### Reasons for the request

We have Python 3.8, 3.9 and 3.10 versions of the cadquery-ocp wheels for Linux and MacOS that are over 100MB. We would like to get back to where users can simply use `pip install cadquery` again, and the cadquery-ocp package takes care of the most difficult dependency to make that happen.

I don't anticipate a large increase in wheel size, but we may include other Python versions (i.e. 3.7) in the future. I requested an increase to 200MB per file, but we could get by with an increase to 170MB.

Thank you for your consideration.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @jmwright it seems like a reasonable size request. I think soon the @pypa/warehouse-admins will check this issue and accept the request. I hope you understand  if the waiting is too long, but we will try to do our best to solve this soon.

**Comment by jmwright** [comment]
@cmaureir Thank you.

**Comment by cmaureir** [comment]
Hey @jmwright quick question, I was checking and it seems the project doesn't exist on https://test.pypi.org/ If you still need the new limit there as well you need to create the project first. If you only need it on PyPi, you can update your issue.

**Comment by jmwright** [comment]
@cmaureir That was an oversight on my part. The project is [here](https://test.pypi.org/project/cadquery-ocp/) on test.pypi.org now. Please let me know if you need anything else.

**Comment by cmaureir** [comment]
I've set the upload limit for `cadquery-ocp` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by jmwright** [comment]
Thank you.

**Comment by jmwright** [comment]
I would like to request an increase in the total size of the cadquery-ocp project from the 10 GB limit. If my math is correct, the current release will come in at about 3.8 GB. I am currently about 1.7 GB short of being able to upload this release. So if I could have an increase to 12 GB, that should get me through this release (I think). More information below.

The proper way to do this may be to open a new issue, but I thought it might be helpful to have the previous history as context. I am trying to upload more wheels to the cadquery-ocp project on PyPI, and I am getting the following error.
```
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                                                                    
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                                                           
         Project size too large. Limit for project 'cadquery-ocp' total size is 10 GB. See https://pypi.org/help/#project-size-limit
```
The uploads are working on test.pypi.org (I assume) because I do not have all the releases on there. I am guessing that means the total size of all our production releases has now exceeded 10 GB. For the current release, I still have 5 MacOS ARM64 wheels to upload for a total of 790 MB (158 MB each), as well as 5 wheels for aarch64 Linux for a total of 905 MB (181 MB each). Looking back at our release history, it looks like our release cadence varies between 3 and 6 months. The Mac ARM64 and Linux aarch64 wheels are new. We have not made them available before, so that will increase the size of each new release.
