### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by upbit** [pypa/pypi-support#1924]
### PyPI Username

rmusique

https://pypi.org/user/rmusique/

### Reason for request

Lost 2FA authentication app and security token. Because I lost the app on my phone, and I couldn't find the security code.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by eggplants** [comment]
Mr. @ewdurbin last responded on March 2.
https://github.com/pypa/pypi-support/issues/1713#issuecomment-1055895971

seems to be busy now?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by upbit** [comment]
Reply from primary email address, verifying branch: https://github.com/upbit/pixivpy/tree/VXowsZOFE60ma48c

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by upbit** [comment]
Thank you SO much!
