### ISSUE TITLE
PEP 541 Request: tf-nightly-intel

### ISSUE THREAD

**Issue by justkw** [pypa/pypi-support#1926]
### Project to be claimed

`tf-nightly-intel `: https://pypi.org/project/tf-nightly-intel 

### Your PyPI username

`IntelAI`: https://pypi.org/user/IntelAI

### Reasons for the request

request to create new project name 'tf-nightly-intel'

### Source code repositories URLs

https://github.com/tensorflow/tensorflow/
We'll be publishing the nightly wheel for Windows platform for this project

### Contact and additional research

This is a request to create a new project, and I'll be the owner for this project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by bani-intelaipg** [comment]
@di may we request your help with this? This namespace was agreed with Rostam. Thanks!

**Comment by angerson** [comment]
@bani-intelaipg I'm a little confused here -- PEP 541 requests are about [name transfers](https://peps.python.org/pep-0541/#abstract); creating a new package on PyPI doesn't require an issue like this unless you tried to upload your first package and it failed. PyPI doesn't have true namespaces, just package names, although we've sometimes called them "project" names.

So you might not need this issue at all right now -- is there context I'm missing?

**Comment by di** [comment]
@angerson is right, this project doesn't exist and the name isn't prohibited, so you didn't need to make a PEP 541 request here for it.

That said, in the interest of preventing others from squatting this name, I've gone ahead and created the project and transferred it to you, but in the future you can just upload the package to create the project.

**Comment by justkw** [comment]
Thank you for your clarification.  Do we need to file an issue to request for increase file-size-limit?  I just tried to upload, but got the following error:

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/

         File too large. Limit for project 'tf-nightly-intel' is 100 MB. See https://pypi.org/help/#file-size-limit for more

         information.



I was trying to upload one of our nightly wheel which is about 171M.

Thanks,

Karen



From: Austin Anderson ***@***.***>
Date: Monday, May 23, 2022 at 3:14 PM
To: pypa/pypi-support ***@***.***>
Cc: Wu, Karen ***@***.***>, Author ***@***.***>
Subject: Re: [pypa/pypi-support] PEP 541 Request: tf-nightly-intel (Issue #1926)

@bani-intelaipg<https://github.com/bani-intelaipg> I'm a little confused here -- PEP 541 requests are about name transfers<https://peps.python.org/pep-0541/#abstract>; creating a new package on PyPI doesn't require an issue like this unless you tried to upload your first package and it failed. PyPI doesn't have true namespaces, just package names, although we've sometimes called them "project" names.

So you might not need this issue at all right now -- is there context I'm missing?

**Comment by bani-intelaipg** [comment]
Hi @angerson and @di can you please advice? We are still not able to push wheel for this project.
