### ISSUE TITLE
PEP 541 Request: utopya

### ISSUE THREAD

**Issue by blsqr** [pypa/pypi-support#1927]
### Project to be claimed

`utopya`: https://pypi.org/project/utopya

### Your PyPI username

`blsqr`: https://pypi.org/user/blsqr

### Reasons for the request

In the process of outsourcing a Python package from a [larger open source library](https://ts-gitlab.iup.uni-heidelberg.de/utopia/utopia/-/merge_requests/277), we would like to distribute [the `utopya` package](https://gitlab.com/utopia-project/utopya) via PyPI.

As reported in #1610, this project name is currently blocked by a mass name squatter. The current project contains some random code, only a single version is published, the homepage link is broken, and it has seen no changes since late 2020.
A similar procedure was carried out for another squatted name in #1645. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no longer any source code available at the linked address: https://github.com/thorwhalen/ut/tree/master/utopya

The project I intend to publish under `utopya`: https://gitlab.com/utopia-project/utopya

### Contact and additional research

I have not reached the current owner. I believe the corresponding GitHub account is: https://github.com/thorwhalen/

As described in #1610, the owner appears to have [a larger repository](https://github.com/thorwhalen/ut) from which all the squatted repositories have been created. A project called `utopya` is [no longer among them](https://github.com/thorwhalen/ut/search?q=utopya).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by blsqr** [comment]
@yeraydiazdiaz Could you perhaps give this a look? Or is there anyone else I should tag instead?

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by blsqr** [comment]
Thank you, @yeraydiazdiaz!
