### ISSUE TITLE
File Limit Request: rtb-data - 150 MB

### ISSUE THREAD

**Issue by jhavl** [pypa/pypi-support#1929]
### Project URL

https://pypi.org/project/rtb-data/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This package (`rtb-data`) holds important data (mainly robot models, the size comes largely from the robot meshes contained) for the [roboticstoolbox-python](https://pypi.org/project/roboticstoolbox-python/1.0.1/) package*.  In `rtb-data`, we contain the models of many popular mobile robots and arm-type robots. The meshes of these robots are provided the the manufacturers and are already in minimal forms defined by collada or stl files.

*We have separated the data from `roboticstoolbox-python` into this package for several reasons:
- We only need to release a single .whl of this package but for `roboticstoolbox-python` we need to release several pre-built wheels for each release. This keeps the size of `roboticstoolbox-python` way down on PyPI.
- We publish releases of the `rtb-data` package far less often, once again keeping total size low on PyPI.

### Reasons for the request

We are requesting an increase in the limit as we have recently added new robot models to our package which has pushed us over the limit. This could increase in the future as new robots are released and become popular in the robotics community.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
I'm glad to see that your project handles that type of data on a separate package instead of the main wheel, I think it's the way to go for these kinds of projects. Also the size you are requesting it's not too much, so I think @pypa/warehouse-admins will drop by soon to address your request.

**Comment by cmaureir** [comment]
I've set the upload limit for `rtb-data` to 150 MB on PyPI. Please be mindful of the frequency of releases at that size.
