### ISSUE TITLE
PEP 541 Request: Clippy

### ISSUE THREAD

**Issue by steverichey** [pypa/pypi-support#193]
**Project to be claimed**
`Clippy`: https://pypi.org/project/Clippy

**Your PyPI username**
`steverichey`: https://pypi.org/user/steverichey

**Reasons for the request**
This project has clearly been abandoned. The package has no description, the GitHub repo has not been updated in four years, and efforts to contact the maintainer via email have not succeeded.

**Maintenance or replacement?**
I intend to replace this package with https://github.com/gowithfloat/clippy, which I only settled on when I realized that `pip install clippy` did not return an existing package.

**Contact and additional research**
I have attempted to contact the maintainer of this package via the email they provided, with no success.

**Comment by yeraydiazdiaz** [comment]
Hello @steverichey, I can confirm the project is invalid as it has a single release with no files.

I will now contact an admin to perform the transfer for you.

**Comment by ewdurbin** [comment]
transfer complete.
