### ISSUE TITLE
PEP 541 Request: heimdall

### ISSUE THREAD

**Issue by Jon-Becker** [pypa/pypi-support#1930]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/heimdall

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Jon-Becker

### Reasons for the request

Inactive since 2015, I have a project that I'd like to publish to this name.

https://github.com/Jon-Becker/heimdall

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: https://github.com/Brainlabs-Digital/heimdall

Mine: https://github.com/Jon-Becker/heimdall

### Contact and additional research

N/A

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Jon-Becker, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
I believe GitHub user @TomAnthony is the current owner, he replied he's looking into this request.

**Comment by Jon-Becker** [comment]
no longer needed
