### ISSUE TITLE
PEP 541 Request: datagen

### ISSUE THREAD

**Issue by EgorLu** [pypa/pypi-support#1934]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/datagen

### Your PyPI username

`USER_NAME`: https://pypi.org/user/egorlu

### Reasons for the request

Hi team,
I work at [Datagen](https://datagen.tech/), and we've uploaded a [public package](https://pypi.org/project/datagen-tech/) to PyPI. We'd like to use the "Datagen" name but it's taken.

This package is unmaintained for over 5 years now and seems to be abandoned.
We've been trying to contact the owner - Todd Wilson via all known ways but there's no success as for now.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

**Old:** https://github.com/toddwilson/datagen
**New:** https://pypi.org/project/datagen-tech/ (sorry, no GitHub repo yet)

### Contact and additional research

We've contacted Todd Wilson via:

- Email (todd@toddwilson.net)
- [LinkedIn](https://www.linkedin.com/in/toddbw/) (toddbw)
- [GitHub](https://github.com/toddwilson) (toddwilson) [Raised an Issue](https://github.com/toddwilson/datagen/issues/3)
- [Vakaros Website](https://www.vakaros.com/contact)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Ovsyanka83** [comment]
Please, set a proper title for your issue.

**Comment by yeraydiazdiaz** [comment]
Hello @EgorLu, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by toddwilson** [comment]
Hello, my name is Todd Wilson and I'm the current maintainer. I'm happy to release the package name 'datagen' as requested.

**Comment by EgorLu** [comment]
Apologies for the delayed reply,
@toddwilson, thanks for your cooperation. Greatly appreciated! <3
@yeraydiazdiaz how should we proceed?

**Comment by yeraydiazdiaz** [comment]
Apologies, I missed @toddwilson's reply. Transfer complete.

**Comment by EgorLu** [comment]
Thanks a lot for the cooperation and super quick reply! :)
