### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aexvir** [pypa/pypi-support#1935]
### PyPI Username

aexvir

### Reason for request

I don't know what device I used as 2fa and none of my devices/yubikeys seems to work; it was probably set up on a device I no longer own and I forgot to save any recovery code

I have access to the correct credentials and main email account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by aexvir** [comment]
I've seen many newer requests than mine being handled 😕 
is there something I can do to bring this higher up on the processing queue?

**Comment by ewdurbin** [comment]
Account recovery requests have not been processed out of order, other requests handled by volunteers have been addressed.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
