### ISSUE TITLE
PEP 541 Request: squishy

### ISSUE THREAD

**Issue by lethalbit** [pypa/pypi-support#1937]
### Project to be claimed

`squishy`: https://pypi.org/project/squishy/

### Your PyPI username

`lethalbit`: https://pypi.org/user/lethalbit

### Reasons for the request

The last update to this package was 2016-09-24, a full 6 years ago, while the last update to the source repository is at most 4 years ago. 

Despite my attempts to contact the maintainer by email (which was found via the git logs of the project) over the past 2-ish weeks (first email sent 2022-04-28, second email sent 2022-05-10) , there has been nothing but radio silence.

As such, I believe this falls within the classification of abandonment as per PEP 541.

Uploading the intended replacement package under an altered name would cause branding issues, as well as invalidate a large amount of work already done under the given name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: [https://github.com/tmehlinger/squishy](https://github.com/tmehlinger/squishy)

Intended replacement: [https://github.com/lethalbit/squishy](https://github.com/lethalbit/squishy)

### Contact and additional research

The contents of the email sent on the two separate occasions that has had no response so far:

```
Hi!

Sorry if this seems out of nowhere, but I was looking to submit a project of mine ( https://github.com/lethalbit/squishy ), also called squishy by chance to PyPi, and noticed you have a project
of the same name ( https://pypi.org/project/squishy/ ).


I was wondering, as your package has not been updated in little over 6-years, if you would be willing to relinquish the name on PyPi?

Thanks, and I hope you're doing well,

- Aki 
```

This was sent to their `tmehlinger` email address that was found via the git commit logs and matches the email listed on PyPi.

As to date no other means of contact for them has been found.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @lethalbit, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by tmehlinger** [comment]
Hi! I've been another planet and don't check that email very often. It's all yours, have at it. 😄

**Comment by lethalbit** [comment]
@tmehlinger that sounds great, thanks~

@yeraydiazdiaz is there anything specific that either @tmehlinger or myself need to do to facilitate the transfer?

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @tmehlinger, transfer complete.
