### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by seperman** [pypa/pypi-support#1938]
### PyPI Username

seperman

### Reason for request

At the time that I had signed up for 2FA, I did not see a way to generate recovery codes. Since then I have switched my phone and I don't have the original Google auth 2FA items on the new phone anymore. I thought I had generated the recovery codes for all of them. This is the first one that I see I didn't.
The reason it took me a while to realize is that https://upload.pypi.org/legacy/ has been working without 2FA.
Could you please disable the 2FA? I will re-enable it and find a way to download the recovery codes this time.
Thank you,
Sep

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by seperman** [comment]
Hi @ewdurbin
Sorry, I know you are super busy so no worries if you don't have time.
I have some bug fix for the deepdiff package (it has 6 million downloads a month via pypi) that I can't publish currently since I crashed my phone and lost my 2FA. Apologies that I did not save the recovery codes.
Thank you.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
