### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by santiagxf** [pypa/pypi-support#1939]
### PyPI Username

santiagxf

### Reason for request

For some reason (still not sure) the TOTP account for PyPi is missing in the Microsoft Authenticator app I generally use. I think it got lost when I changed my phone and probably the backup didn't work as expected. Since it's the only 2FA method I have setup, I can't get access to the account. I do have a personal token generated so I can interact with the APIs, but in case I have to regenerate it I won't be able to. I'm the maintainer of the library `jobtools` so I would like to keep the same username.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by santiagxf** [comment]
Email answered.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
