### ISSUE TITLE
PEP 541 Request: turf

### ISSUE THREAD

**Issue by docyx** [pypa/pypi-support#194]
**Project to be claimed**

`turf`: https://pypi.org/project/turf

**Your PyPI username**

`docyx`: https://pypi.org/user/docyx

**Reasons for the request**

The project has been abandoned for about 3 years now, and the [Homepage](https://github.com/HurricaneLabs/turf) link returns a 404.

**Maintenance or replacement?**

I plan to replace it with a different package that is still in development, and the code isn't published yet so I don't have a GitHub link for it.

**Contact and additional research**

I have sent an email to the [owner](https://github.com/mcm) as well as the [organization](https://www.hurricanelabs.com/) and haven't gotten a reply in almost 5 days.

**Comment by docyx** [comment]
Paging @HurricaneLabs and @mcm

**Comment by mcm** [comment]
This is fine by us. If there’s a way I can facilitate this to make it easier let me know.

**Comment by docyx** [comment]
@mcm Thank you so much for the reply. I will email you again.

**Comment by docyx** [comment]
@mcm If you could just simply set me as the maintainer I think it would work, as specified in the [PEP 541](https://www.python.org/dev/peps/pep-0541/)

**Comment by mcm** [comment]
Done. Let me know if that's all you need.

**Comment by docyx** [comment]
That's it! Thank you again.
