### ISSUE TITLE
Project Limit Request: maturin - 20 GB

### ISSUE THREAD

**Issue by messense** [pypa/pypi-support#1940]
### Project URL

https://pypi.org/project/maturin/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Maturin builds and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages. It's a important package to support packaging Rust-based Python extension modules.

### How large is each release?

~135 MB totol.

11 Linux wheels at ~100 MB.
3 Windows wheels at ~16 MB.
2 macOS wheels at ~19 MB.
The source tarball at 153KB.

We have deleted some old prereleases to reduce storage.

### How frequently do you make a release?

Usually every month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
I've set the project limit for `maturin` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
