### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rltvty** [pypa/pypi-support#1942]
### PyPI Username

`kaskada`

### Reason for request

Lost 2FA authentication app or security token

Our developer who setup the pypi account is no longer with the company, and must have saved the 2FA & password to a non-shared 1password vault instead of one of our shared vaults.  We do have access to the credentials for `test.pypi`.

I was able to reset the account password, since I have access to the email address on the account, but not the 2FA.

To further prove ownership you can see I belong to https://github.com/orgs/kaskada-eng/people and https://gitlab.com/groups/kaskada/-/group_members

I also can provide a valid auth_token to the pypi account if that is helpful.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
