### ISSUE TITLE
File Limit Request: tf_gpu - 525 MB

### ISSUE THREAD

**Issue by ssbuild** [pypa/pypi-support#1944]
### Project URL

https://pypi.org/project/tf-gpu/

### Does this project already exist?

- [X] Yes

### New Limit

525

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

rebuilding the tensorflow 1.15 and tensorflow 2 with lastest cuda cudnn  and nccl

### Reasons for the request

We're releasing for main tensorflow gpu package and we're hitting the project size limit at only some whl package ,hope you can increased mytensorflow project size to 525 MB , and total size with 30G, I will do rarely upload.
We build tensorflow using the environment as follow cuda 11.6 cudnn 8.4 nccl 2.12
tensorrt: 8.4 nvidia Compute Capability 6.1 7.0 7.5 8.0 8.6.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ssbuild :wave:
I recommend you to create another issue asking for the project size limit, and let's keep this one on the file (wheel) limit.
Because the project is empty (which is fine!) can you share the repo of the project? or any other website? on that PyPi link the 'homepage' link goes to https://github.com/passion765 which doesn't exist.

**Comment by ssbuild** [comment]
> Hey @ssbuild 👋 I recommend you to create another issue asking for the project size limit, and let's keep this one on the file (wheel) limit. Because the project is empty (which is fine!) can you share the repo of the project? or any other website? on that PyPi link the 'homepage' link goes to https://github.com/passion765 which doesn't exist.

File for more than 100 million limited transmission, so made a fake wheel sorry did not modify the home page, I quote tensorflow https://github.com/tensorflow/tensorflow
https://github.com/nvidia/tensorflow

**Comment by cmaureir** [comment]
I've set the upload limit for `tf-gpu` to 600 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day!
