### ISSUE TITLE
File Limit Request: aws-tensorflow-cpu - 500 MB

### ISSUE THREAD

**Issue by mseth10** [pypa/pypi-support#1951]
### Project URL

https://pypi.org/project/aws-tensorflow-cpu/
https://test.pypi.org/project/aws-tensorflow-cpu/

### Does this project already exist?

- [X] Yes

### New Limit

500 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

`aws-tensorflow-cpu` is the ARM64 counterpart of the package [tensorflow-cpu](https://pypi.org/project/aws-tensorflow-cpu). Currently [tensorflow-cpu](https://pypi.org/project/aws-tensorflow-cpu) does not support ARM64 architecture. `aws-tensorflow-cpu` is built on AWS Graviton powered EC2 instances and uploaded directly from the CD pipeline of TensorFlow GitHub repository [here](https://github.com/tensorflow/tensorflow/blob/6aeba27f29cdef2837a8e4fbbd8a9da9249d585f/.github/workflows/arm-cd.yml#L55). This project has been active for about 2 months now.

### Reasons for the request

Just like x86 architecture wheels are around 500MB (project [tensorflow-cpu](https://pypi.org/project/aws-tensorflow-cpu)), ARM64 wheels are also expected to be around the same size once all features are enabled.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @mseth10 :wave:
I was checking https://pypi.org/project/tensorflow-cpu/#files and most of the wheels are around 2XX MB
Which wheels are the ones you mention ere around 500 MB?

**Comment by mseth10** [comment]
Hi @cmaureir , sorry I was also referring to https://pypi.org/project/tensorflow/#files
