### ISSUE TITLE
PEP 541 Request: helixswarm

### ISSUE THREAD

**Issue by pbelskiy** [pypa/pypi-support#1952]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/helixswarm

### Your PyPI username

`USER_NAME`: https://pypi.org/user/pbelskiy

### Reasons for the request

I am owner of https://github.com/pbelskiy/helix-swarm project (https://pypi.org/project/helix-swarm) and I want to create upload also it with name `helixswarm` as alias and because it easy typed and more obvious because users use `import helixswarm`, so I need it as alias and for future migration.

But I cannot do so because of error - The name 'helixswarm' is too similar to an existing project.

So I suggest ignore such error if existing project belong to the same author, because you have many issues here with same errors.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/pbelskiy/helix-swarm

### Contact and additional research

I am the owner of helix-swarm and would like to own helixswarm.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @pbelskiy, a @pypa/warehouse-admins should be able to release the project name to you.

**Comment by pbelskiy** [comment]
Any updates?

**Comment by pbelskiy** [comment]
Hi guys! Sorry, but any updates here?
