### ISSUE TITLE
PEP 541 Request: hab

### ISSUE THREAD

**Issue by MHendricks** [pypa/pypi-support#1953]
### Project to be claimed

`hab`: https://pypi.org/project/hab

### Your PyPI username

`blurstudio`: https://pypi.org/user/blurstudio

### Reasons for the request

There doesn't seem to be an existing project with this name, but I get `403 The user 'blurstudio' isn't allowed to upload to project 'hab'.` when trying to claim it.

I'm not sure if this project was abandoned or is reserved for some reason, Apparently there is a different error message a package name is too close to another project name so I don't think that why its being rejected.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My repo https://github.com/blurstudio/habitat. I will be renaming the github project to hab if I'm able to claim the project name.
There doesn't appear to be an existing project to check the source urls or contact info.

### Contact and additional research

I don't see any standard library modules similar to hab, and I can't see an existing project to find any contact info to contact the old project managers so I can't contact the old project manager.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by MHendricks** [comment]
@yeraydiazdiaz, I'm not sure who to ask about this, but you seem to be pretty active for pep 541 requests. Is there any chance this can be looked at soon? We would like to start using the package name or switch to an alternative if its deemed that we can't use hab.

**Comment by yeraydiazdiaz** [comment]
Hi @MHendricks, I can confirm a `hab` project exists in PyPI but has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before transferring it.

**Comment by MHendricks** [comment]
@yeraydiazdiaz any word on this? It was moved into the one week invalid courtesy period over 2 weeks ago.

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay. Transfer complete.
