### ISSUE TITLE
PEP 541 Request: mbs

### ISSUE THREAD

**Issue by mueslo** [pypa/pypi-support#1958]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/mbs

### Your PyPI username

`USER_NAME`: https://pypi.org/user/mueslo

### Reasons for the request

Created in 2016 and never used in 6 years (i.e. name squatting), no known project that it is intended for.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current: none
(Seemed to belong to https://github.com/rescrv/minion, which turned into a Go project)

New: https://github.com/mueslo/mbs

### Contact and additional research

I have contacted the project owner @rescrv by e-mail (24.04.2022), I realize this is not a sufficient time to wait, but I am opening this issue already.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @mueslo, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.

**Comment by mueslo** [comment]
Thanks @yeraydiazdiaz and @rescrv!
