### ISSUE TITLE
PEP 541 Request: oracledb

### ISSUE THREAD

**Issue by anthony-tuininga** [pypa/pypi-support#1960]
### Project to be claimed

`oracledb`: https://pypi.org/project/oracledb

### Your PyPI username

`atuining`: https://pypi.org/user/atuining

### Reasons for the request

I am unable to upload this project as noted in this issue: https://github.com/pypa/warehouse/issues/11453

I am the primary author as can be seen in this GitHub repository: https://github.com/oracle/python-oracledb

### Source code repositories URLs

https://github.com/oracle/python-oracledb

### Contact and additional research

I am not aware of any current owners. The issue indicated that this name was forbidden due to a dependency confusion attack. Let me know if you require any additional information.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by anthony-tuininga** [comment]
@di, would it be possible to get this addressed today? We would like to continue forward with our release if at all possible! Thanks.

**Comment by ewdurbin** [comment]
@anthony-tuininga I would be happy to process this today if you are able to add and verify an @oracle.com email address to the [atuining](https://pypi.org/user/atuining) User account on PyPI.

**Comment by anthony-tuininga** [comment]
Thanks! I have added my @oracle.com email address as requested.

**Comment by ewdurbin** [comment]
`oracledb` Project name released to `atuining` User on PyPI.

**Comment by anthony-tuininga** [comment]
Thank you, @ewdurbin !
