### ISSUE TITLE
File Limit Request: BIG-bench test - 400 MB

### ISSUE THREAD

**Issue by ethansdyer** [pypa/pypi-support#1964]
### Project URL

https://test.pypi.org/project/BIG-bench/

### Does this project already exist?

- [X] Yes

### New Limit

400 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

The Beyond the Imitation Game Benchmark ([BIG-bench](https://github.com/google/BIG-bench)) is a collaborative machine learning benchmark intended to probe large language models and extrapolate their future capabilities. It contains over 200 tasks. The project has been active since January 2021. We do not expect the project to grow significantly in size moving forward.

### Reasons for the request

Hi,

   I submitted and was helped with a size limit request for our PyPI project (https://github.com/pypa/pypi-support/issues/1782) -- Thank you! However, I believe this was not mirrored on the test project (possibly due to the confusing BIG-bench v bigbench). I am hoping to increase the quota for the test project as well.

Thank you for the help!

Ethan

Informational questions:

  - The project has no individual files over 100MB, but the full project tarball is over 300MB is it this tarball size that is hitting the per-file limit?
  - It is unfortunate that the test project and main project have slightly different names, when I try to create a bigbench project in TestPyPI, however, I get a name too close conflict. Is there anyway to migrate the name in TestPyPI?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @ethansdyer :wave:
That's right, PyPi and TestPyPi are different, that's why there is an option "Which Indexes" where you can select both.
I've set the upload limit for `BIG-bench` to 400 MB on TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
