### ISSUE TITLE
PEP 541 Request: txi2p

### ISSUE THREAD

**Issue by exarkun** [pypa/pypi-support#1965]
### Project to be claimed

`txi2p`: https://pypi.org/project/txi2p

### Your PyPI username

`exarkun`: https://pypi.org/user/exarkun

### Reasons for the request

The current owner and sole maintainer of the project, st4d, has been out of communication for quite a long time now.  Another project I maintain, Tahoe-LAFS, depends on txi2p for interactions with the I2P network.  We have made essential fixes to txi2p and tried to get them merged upstream and released but with no response.

Contact attempts on GitHub (https://github.com/str4d/txi2p/issues/10), via email, and via IRC over almost two years have failed.

Meanwhile Tahoe-LAFS has released txi2p-tahoe with the necessary changes.  Since our fixes are not specific to Tahoe-LAFS and would benefit any txi2p user, we believe it would be better for the community if we could publish them as "txi2p" - the most obvious package for potential users to investigate.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The current repo is https://github.com/str4d/txi2p
The replacement is https://github.com/tahoe-lafs/txi2p

### Contact and additional research

The primary publicly visible contact attempt is in the txi2p GitHub issue tracker - https://github.com/str4d/txi2p/issues/10

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by May-Lee** [comment]
I contacted @str4d on March 1, 2021. When I heard no response, I sent another email out on March 13, stating we would release a fork of the project by July 1, 2021, if we didn't hear an objection before then. This fork was needed to maintain functionality and could not be delayed further.

**Comment by str4d** [comment]
Oh hi, this just popped up in my notifications.

I had to drop all I2P-related development several years ago for personal reasons, and was not monitoring any of those avenues. Apologies for missing this amongst that.

I'm happy for the tahoe-lafs GitHub org to take over maintainership of the txi2p PyPI package.

**Comment by exarkun** [comment]
Hi @str4d, glad to hear from you :)  Thanks for your blessing on this transfer of maintainership.

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @str4d, transfer complete.
