### ISSUE TITLE
Deleted project by mistake!

### ISSUE THREAD

**Issue by sabrygad** [pypa/pypi-support#197]
Hi;

We have a new package, pyhma, that is part of our mapped-averaging project:
https://github.com/etomica/mapped-averaging
The Docs are here:
https://pyhmadocs.readthedocs.io/en/latest/index.html

I deleted the whole whole pyhma project on PyPI as I made many changes ... etc (which is BAD!). I did not know that:
"PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated."
https://pypi.org/help/#file-name-reuse

I changed the version, however still getting the same error:

[sabrygad@dhcp-10-84-95-142 pyhma]$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: sabrygad
Enter your password: 
Uploading pyhma-1.0.1-py3-none-any.whl
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 13.9k/13.9k [00:01<00:00, 9.84kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/

I appreciate it if you can help me get the same name.

Best;
Sabry

Request for account recovery.

## PyPI Username

`username`

---

##  Reason for request

Reason:

**Comment by di** [comment]
It seems like this was resolved on Distutils-SIG, but if not, please feel free to comment.
