### ISSUE TITLE
PEP 541 Request: fins

### ISSUE THREAD

**Issue by aphyt** [pypa/pypi-support#1970]
### Project to be claimed

`fins`: https://pypi.org/project/fins/

### Your PyPI username

`josephryan`: https://pypi.org/user/josephryan

### Reasons for the request

The current fins PyPi package is using a subset of my code at https://bitbucket.org/jryan/finsgit/commits/ which was released by a third party who seems to have abandoned it. The fins library is a module for communicating with Programmable Logic Controllers (PLCs) with the Omron protocol Factory Intelligent Network Service (FINS). The current maintainer has not implemented any updates in over two years and has only removed functionality from the library I wrote (removed all memory areas but one, removed all protocol methods but one). I reached out to the current maintainer because I want this to implement the full functionality of the library so that Python users trying to use the FINS protocol are able to use the more complete functionality, but have not heard back. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current: https://github.com/per000/fins/tree/master/fins
My Replacement: https://bitbucket.org/jryan/finsgit

### Contact and additional research

I reached out to the email address listed on the PyPi page on May 18th 2022 and received no reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @aphyt, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by aphyt** [comment]
The current maintainer reached out to me and added me as an owner, so I am closing this issue.
