### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by maedoc** [pypa/pypi-support#1974]
### PyPI Username

marmaduke

### Reason for request

Lost access to the email address (mw@eml.cc  I think; Fastmail account expired).  In particular, I pushed a package named `tvb`,

https://pypi.org/project/tvb/

which in the description mentions an article 

https://www.frontiersin.org/articles/10.3389/fninf.2013.00010/full

where I'm co-author (Woodman) as is @liadomide, and you can see out contributions to the main project (thevirtualbrain.org, github.com/the-virtual-brain) later release updated packages e.g.

https://pypi.org/project/tvb-library

but we would like to recover the `tvb` package name, and if possible move the package to the same account as the tvb-library package (user `tvb`, https://pypi.org/user/tvb/), that would be ideal.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account as well as the primary email on the requesting account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Verification complete. tvb User has been granted Owner role on the tvb project.
