### ISSUE TITLE
File Limit Request: glycowork - 300 MB

### ISSUE THREAD

**Issue by Bribak** [pypa/pypi-support#1975]
### Project URL

https://pypi.org/project/glycowork/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Our package is the leading data science and machine learning package for the academic field of glycobiology, the science of complex sugars and their role in biology, developed with and for the scientific community. Next to substantial functionality and algorithms, we also store curated datasets and trained machine learning models within the package. This is crucial, as the average user of glycowork is not extensively familiar with state-of-the-art methods in computational biology. We therefore emphasize usability and accessibility, democratizing the usage of advanced computational biology in our field.

### Reasons for the request

The trained models and stored curated datasets we provide within glycowork require a certain amount of storage space. Our new, current release is at the moment at 177 MB. Since we expect this to increase over the next releases, we request a storage limit of 300 MB, in order to be long-term sustainable and flexible. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the detailed explanation @Bribak !
I do encourage you to look in the future for other options to get the models for the users (in case you are going around 1GB) like a special `download()` method that can fetch those files from a project URL.

I've set the upload limit for `glycowork` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.

Have a nice weekend!
