### ISSUE TITLE
PEP 541 Request: sierraecg

### ISSUE THREAD

**Issue by sixlettervariables** [pypa/pypi-support#1976]
### Project to be claimed

`sierraecg`: https://pypi.org/project/sierraecg

### Your PyPI username

`christopherwatford`: https://pypi.org/user/christopherwatford

### Reasons for the request

I had not yet published a new package to PyPi, but in the two weeks between putting up the PR (https://github.com/sixlettervariables/sierra-ecg-tools/pull/38) and merging it I found the package had already been published from my repo by [hyerim1606](https://pypi.org/user/hyerim1606/). I do not know this user and have no way of contacting them. It appears they may be package squatting because I made my intended package name public prior to publishing.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/sixlettervariables/sierra-ecg-tools

### Contact and additional research

I'm the sole owner of my personal GitHub repos. I'm not quite sure who `[hyerim1606](https://pypi.org/user/hyerim1606/)` is or how they came to publish my package. I have no means of contacting them as they do not have any public emails listed and have not contributed to my library.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @sixlettervariables, it seems the `sierraecg` project does not exist in PyPI anymore so you should be able to upload it now.
