### ISSUE TITLE
Namesquatting user: acue

### ISSUE THREAD

**Issue by lordmauve** [pypa/pypi-support#198]
This user has registered over 400 packages based on some kind of name generator: 

https://pypi.org/user/acue/

Examples:

* [yamllathe](https://pypi.org/project/yamllathe/)
* [raspberrypibricks](https://pypi.org/project/raspberrypibricks/)
* [inidata](https://pypi.org/project/inidata/)

Most of these contain a template-generated tarball that doesn't contain any code. I don't think the packages are intended to be malicious but they do contain code in their `setup.py` that appears to invoke a remote debugger if installed.

I believe this contravenes PEP-541:

> project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:
>
> * project is name squatting (package has no functionality or is empty);

A very small number of the user's packages seem to be genuine.

**Comment by jorgecarleitao** [comment]
related: #536

**Comment by yeraydiazdiaz** [comment]
Closing as dupicate of #536
