### ISSUE TITLE
File Limit Request: datarobot-mlops - 135 MB

### ISSUE THREAD

**Issue by elatt** [pypa/pypi-support#1981]
### Project URL

https://pypi.org/project/datarobot-mlops

### Does this project already exist?

- [X] Yes

### New Limit

135

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This library is an interface to the DataRobot MLOps platform. Users can import it into their Python ML models and use it as an interface to report statistics back to the DataRobot platform for analysis. The main contributor to the large size is that we include the Java package (https://mvnrepository.com/artifact/com.datarobot/datarobot-mlops) into this file and uses `py4j` to communicate with it.

### Reasons for the request

The size of the Java package that we embed has increased in size due to us upgrading some dependencies and those packages having considerable increases in their size. The package size is currently 104 MB so we are requesting 135 MB to provide a little headroom.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by elatt** [comment]
cc @DrewParallel @lemonez

**Comment by cmaureir** [comment]
Thanks for the information @elatt 
Be careful with the Homepage url on the pypi project, it redirects to https://github.com/datarobot/tracking-agent which doesn't exist. But I'm certain you will take care of it with the new upload.

I've set the upload limit for `datarobot-mlops` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size ;)

Have a nice weekend!
