### ISSUE TITLE
File Limit Request: PROJECT_NAME - 800 MB

### ISSUE THREAD

**Issue by waspa** [pypa/pypi-support#1982]
### Project URL

https://pypi.org/project/en_hotel_sm-0.0.0

### Does this project already exist?

- [X] Yes

### New Limit

800

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

Custom Spacy NER

### Reasons for the request

Increase in size to 800MB

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @waspa :wave:
Your issue needs a little bit more details, could you please:
* Update the issue title with the name of the project on PyPi
* Share the URL of the project. The one you provided doesn't work and returns a 404 error.
* Explain the project, maybe share where it's being developed (a github link?)
* Tell us more on reason you are asking 800MB, does the packages has a dependency? it does contain data files? etc.
Thanks!

**Comment by waspa** [comment]
Thank you for the response. Fortunately i got this sorted.
