### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by LulzLoL231** [pypa/pypi-support#1983]
### PyPI Username

LulzLoL231

### Reason for request

Hello, i lost access to my old email address `lznet@pm.me`, can you help me?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by LulzLoL231** [comment]
You can connect with me by this email: [max@mosin.pw](mailto:max@mosin.pw)

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account as well as the requested email address, please read the instructions and reply to proceed with recovery.
