### ISSUE TITLE
I can not create a account

### ISSUE THREAD

**Issue by Vic217** [pypa/pypi-support#1987]
I want to create an account but my username does not accept it, I tried to change it several times and I still cannot register.

**Comment by di** [comment]
Hi sorry you're having issues. You're going to need to provide us with a bit more detail here: where were you trying to create an account (pypi.org or test.pypi.org)? What username were you trying to use? What error message did you get?

**Comment by Vic217** [comment]
The problem is already solved.
Thank you!!!
