### ISSUE TITLE
PEP 541 Request: big

### ISSUE THREAD

**Issue by larryhastings** [pypa/pypi-support#1988]
### Project to be claimed

`big`: https://pypi.org/project/big

### Your PyPI username

`larry`: https://pypi.org/user/larry

### Reasons for the request

There is no `big` project currently registered.  But PyPI won't let me upload a package named `big`.  Instead I get this error:

`requests.exceptions.HTTPError: 400 Client Error: The name 'big' isn't allowed. See https://pypi.org/help/#project-name for more information.`

I asked Dustin Ingram what was going on; he said the name was on an internal "prohibited names" list:

> [that name] was explicitly prohibited due to being part of a dependency confusion attack.

That's all I know.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no current `big` project on PyPI.

My `big` project is here:

https://github.com/larryhastings/big

### Contact and additional research

There is no current owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @larryhastings, as Dustin mentioned `big` was placed in the prohibited project names list. A @pypa/warehouse-admins should be able to release the project name to you.

**Comment by larryhastings** [comment]
Is there something I need to do to bring it to the attention of the warehouse admins?  Or did you already do that?

**Comment by yeraydiazdiaz** [comment]
I've done that by tagging them and triaging the issue.

**Comment by larryhastings** [comment]
Ok, thanks!

**Comment by dstufft** [comment]
I've gone ahead and released the project ``big`` to user ``larry``.
