### ISSUE TITLE
Limit Request: sdss-mangadap - 120 MB

### ISSUE THREAD

**Issue by kbwestfall** [pypa/pypi-support#199]
**Project**

The package name is: **sdss-mangadap**
Github page: https://github.com/sdss/mangadap
TestPyPI page: https://pypi.org/project/sdss-mangadap/2.5.1/
PyPI page: https://test.pypi.org/project/sdss-mangadap/2.5.1/

**Size of release**

The current size of the release would be **97 MB**, but I'd like to push that to **120MB** for future development purposes.

**Which indexes**

I would like to increase **both** PyPI and Test PyPI.

**Reasons for the request**

The sdss-mangadap project is the data-analysis pipeline (DAP) for the SDSS-IV/MaNGA survey.  See here: https://www.sdss.org/surveys/manga/ .  The survey is of galaxy in the nearby universe to provide spatially resolved properties and internal kinematics.  The MaNGA DAP is the survey-led software packages that provides pipeline processed physical properties derived from the observed spectra for direct use by the SDSS collaboration and, after an ~1 year proprietary period, the general public.  The code base itself is rather small (2MB), which is currently what I've uploaded to the PyPI and Test PyPI pages.  The bulk of the size requirements come from a set of template spectra used to construct models of the galaxy spectra.  These are a critical component of the functionality of the software package.  It's effectively useless without it.  The current size of the distribution that includes the template spectra would be 97 MB.  I've requested a 120 MB limit for future development; however, additional space may be needed beyond this.

**Comment by jamadden** [comment]
The limit has been set to 150MB on pypi.org and test.pypi.org

**Comment by kbwestfall** [comment]
Thanks!
