### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by NihalAgarwal** [pypa/pypi-support#1992]
### PyPI Username

NihalAgarwal

### Reason for request

Lost 2FA authentication app and security token : 
I uninstalled 2FA authentication app (Microsoft authenticator app) and reinstall it but forget to back up the accounts (PyPI), and also not having access to recovery code. Please help.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by NihalAgarwal** [comment]
Hi, I had done all the steps as mentioned by you. Please verify it and unlock it.
