### ISSUE TITLE
File Limit Request: swh.graph - 500 MB

### ISSUE THREAD

**Issue by seirl** [pypa/pypi-support#1998]
### Project URL

https://pypi.org/project/swh.graph/

### Does this project already exist?

- [X] Yes

### New Limit

500 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

We already asked for an exemption here: https://github.com/pypa/pypi-support/issues/71

Our project includes a front-end for the [WebGraph framework](http://webgraph.di.unimi.it/), which is developed in Java and accessed via Py4J (also available via PyPI). A so-called "fat JAR" with all Java dependencies is included to make deployment possible with a simple "pip install" and weighs around 200 MB.

### Reasons for the request

Even with a conscious effort to reduce our dependencies, we had to import a bunch of new Java libraries which made the file a bit less than 200 MB. We ask for an exemption of 500 MB so that we get unstuck for the short/medium term. If the dependencies grow uncontrollably, we'll find another deployment method (dual setup PyPI + Maven, or something like that).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey as described in the issue you referenced, the project doesn't exist on TestPyPi, so I was unable to do any change there.

I've set the upload limit for `swh.graph` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size :)
Have a nice Sunday!
