### ISSUE TITLE
File Limit Request: wolfhece - 250 MB

### ISSUE THREAD

**Issue by PierreArchambeau** [pypa/pypi-support#1999]
### Project URL

https://pypi.org/search/?q=wolfhece

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is a hydrologic/hydrodynamic model (pre and post processors) from ULiège - Belgium.

### Reasons for the request

I would like to upload dependent dll (Fortran compiled) > 100 Mo

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
I've set the upload limit for `wolfhece` to 250 MB on PyPI. Please be mindful of the frequency of releases at that size.
