### ISSUE TITLE
PEP 541: Invalid package: texteditor

### ISSUE THREAD

**Issue by jpscaletti** [pypa/pypi-support#2]
I believe the https://pypi.org/project/texteditor/ is an invalid project:

- The content is a copy-pasted Python exercise with an absolute minimal setup.py, no README and a misspelled license.
- It was uploaded a year and a half ago (September 2017) and hasn't been touch since.
- The linked homepage returns a 404.
- The repo is a mix of other copy-pasted Python exercises.
- Nobody answer at the listed email.

In fact, I suspect that the user is a fake account, but that's beyond this issue.

Disclaimer: I own the project text-editor (with a dash) so I'm worried about name confusion.

**Comment by yeraydiazdiaz** [comment]
I have not received a response to any of my emails hence this project can be considered abandoned. I will now ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
transfer complete.
