### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `dokuwikixmlrpc`

### ISSUE THREAD

**Issue by kynan** [pypa/pypi-support#20]
I would like to request transfer of ownership of the project `dokuwikixmlrpc` to myself as per pypa/warehouse#1506.

I took over maintenance of this project in 2014 and the original author / previous maintainer @chimeric transferred the GitHub repository chimeric/dokuwikixmlrpc over to me in 2016. When you follow the "Homepage" link at https://pypi.org/project/dokuwikixmlrpc/ you will be redirected to the repository I maintain.

He does not have access to his PyPI account nor the email address associated with it any more and is therefore unable to do the transfer himself.

Just to be clear: this will be a continuation of the same project under a new maintainer and any existing releases can be kept as they are.

Below is an excerpt from an email exchange, which didn't go anywhere at the time since PyPI did not have a process for transfer of ownership:

```
From: Michael Klier <REDACTED>
Date: Mon, Sep 26, 2016 at 7:40 AM
Subject: Re: Maintenance of dokuvimki, dokuwikixmlrpc
To: Florian Rathgeber <REDACTED>

Hey Florian,

wow, cool to hear this stuff is still being used :)!

[...]

Re the PyPi - I would love to do that but unfortunately I don't remember the password
anymore and the mailserver I used to register has been down for years now. Not sure
if there's a way to recover that account. If you want to talk to the PyPi admins and explain
the situtation I'll be happy to help out as best as I can with providing relevant info etc..

Cheers,
Michael

On 25 September 2016 at 23:37, Florian Rathgeber <REDACTED> wrote:
>
> Hi Michael,
>
> Apologies for reviving a 2 year old email conversation: I'm in fact
> *still* using dokuvimki!
>
> Recently I've looked into making it Python 3 compatible, which
> requires changes to both dokuwikixmlrpc and dokuvimki.
>
> Could you give me access (with this email address) to the
> dokuwikixmlrpc package on PyPI so I can push a new release?
>
> [...]
>
> Cheers,
> Florian
```

**Comment by yeraydiazdiaz** [comment]
Hi @kynan, we'd need confirmation from Michael that this is the case.

If he's interested in recovering his PyPI account we could certainly help so he can perform the transfer. Alternatively you can email me his email address at yeraydiazdiaz@gmail.com and I can try contacting him directly for confirmation.

**Comment by yeraydiazdiaz** [comment]
CC'ing @chimeric in case he still recieves GH emails.

**Comment by kynan** [comment]
Thanks for following up. I've emailed @chimeric, hope he'll read it and comment here to confirm.

**Comment by MichaelKlier** [comment]
Hi everyone,

I can confirm that I'm okay with transferring ownership of dokuvimki to Florian (@kynan). Not sure if commenting from this account is enough for everyone to validate my identity. If you need a 3rd person to confirm, I guess you can ask the author of DokuWiki, @splitbrain here on gibthub :).

Cheers and have a great week,
Michael

**Comment by splitbrain** [comment]
for what it's worth, I can confirm @MichaelKlier is @chimeric :+1:

**Comment by yeraydiazdiaz** [comment]
Thanks @MichaelKlier and @splitbrain for confirming.

@kynan could you confirm your PyPI username so we can proceed with the transfer, please?

**Comment by kynan** [comment]
@yeraydiazdiaz my PyPI user name is kynan

**Comment by yeraydiazdiaz** [comment]
Thank you @kynan, I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
