### ISSUE TITLE
PEP 541 Request: tensorflow-intel

### ISSUE THREAD

**Issue by justkw** [pypa/pypi-support#2000]
### Project to be claimed

`tensorflow-intel`: https://pypi.org/project/tensorflow-intel

### Your PyPI username

`IntelAI`: https://pypi.org/user/IntelAI: https://pypi.org/user/IntelAI

### Reasons for the request

request to create new project name 'tensorflow-intel'  which will be used for 2.10 release of Windows

### Source code repositories URLs

https://github.com/tensorflow/tensorflow/

### Contact and additional research

This is a request to create a new project and reserve the project name 'teensorflow-intel', and I'll be the owner for this project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @justkw, there is no project named `tensorflow-intel` in PyPI and we do not reserve project names, you simply need to upload your project as detailed in https://packaging.python.org/en/latest/tutorials/packaging-projects/

I will close this request as no transfer is possible.
