### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ringods** [pypa/pypi-support#2003]
### PyPI Username

pulumiverse

### Reason for request

* Person who registered this account no longer works at the company
* He couldn't provide us with any credentials.
* We need access to this account again to publish Python packages linked to Pulumi providers hosted on https://github.com/pulumiverse

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by rawkode** [comment]
- I do still work at Pulumi
- I do have the credentials
- I can give you access

Let's close this out, I believe it's a misunderstanding

**Comment by ringods** [comment]
Indeed. Sorry for the misunderstanding.
