### ISSUE TITLE
PEP 541 Request: covalent

### ISSUE THREAD

**Issue by wjcunningham7** [pypa/pypi-support#2006]
### Project to be claimed

`covalent`: https://pypi.org/project/covalent

### Your PyPI username

`wjcunningham7`: https://pypi.org/user/wjcunningham7

### Reasons for the request

I am an owner of [Covalent](https://github.com/AgnostiqHQ/covalent), which is a Pythonic workflow tool currently listed in PyPI under the project name `cova`.  I would like to use the project name `covalent` instead.  I see that there is currently another project named `covalent` in PyPI although it appears abandoned and contacting the owner has not garnered any response.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The existing project has no URL listed.  The maintainer's [GitHub page](https://github.com/orgs/locp/repositories?type=all) shows no public repositories with this name.  The intended replacement is listed at https://github.com/AgnostiqHQ/covalent

### Contact and additional research

Another member of my team has previously attempted to contact the owner via e-mail and on GitHub, but has not received any response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

CC: @scottwn

**Comment by yeraydiazdiaz** [comment]
Hello @wjcunningham7, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by dallinb** [comment]
Hi @yeraydiazdiaz,

Please go ahead and transfer the project.  It was an idea that never saw fruition and if somebody has a claim to the name (and @wjcunningham7 definitely seems to) then it is more appropriate that they should have the name in PyPi.

Best wishes,

Ben

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @dallinb, transfer complete.
