### ISSUE TITLE
File Limit Request: deephaven-server - 200 MB

### ISSUE THREAD

**Issue by devinrsmith** [pypa/pypi-support#2007]
### Project URL

https://pypi.org/project/deephaven-server

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

deephaven-server is a python application that https://github.com/deephaven/deephaven-core will be producing.  This project has had on-going development for more than a year. At its core, it's a JVM-based application; we are bundling the necessary jars to make it easy for python developers to start the application (and interact with it) from python.

### Reasons for the request

Our first release is blocked on the file size limit. Right now, our application needs ~137MB of already-compressed jars. We don't expect this size to increase significantly in the future, but I'm requested a limit of 200MB as a "reasonable" buffer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
I've set the upload limit for `deephaven-server` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice Sunday!
