### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by we684123** [pypa/pypi-support#2008]
### PyPI Username

we684123

### Reason for request

Lost https://test.pypi.org/ 2FA authentication app (not https://pypi.org/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
TestPyPI 2FA disabled and password reset issued.

**Comment by we684123** [comment]
Thank you very much！
