### ISSUE TITLE
PEP 541 Request: iotics-identity

### ISSUE THREAD

**Issue by KarimIotic** [pypa/pypi-support#2009]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/iotics-identity/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Iotics_Maintainer

### Reasons for the request

Dear team,

Miroslav Sommer (Miro) has left the company. We need to recover the Iotics-identity project to provide the latest update and maintain the project. Can you please transfer the ownership to Iotics_Maintainer (admin@iotics.com).

If needed and for any security confirmation, you can reach out to me head of security and compliance, by calling directly the UK phone number highlighted on this page and ask to speak with Dr. Karim Tobich 
https://iotics.com/contact-us/

Kind regards,
Karim

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

We are not intending to modify the source code for now. We want to transfer of ownership to a generic address for now so we don't face any issue with the offboarding of our employees.

### Contact and additional research

We did try to find other owner or maintainer of this project, but the only one was Miro.
We tried to reset his password but the username was not recorded into our system.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @KarimIotic, we would need to get approval from the current owner which seems to be GitHub user @mirogta. If you are still in contact with him you could direct him to this issue and confirm the transfer.

**Comment by mirogta** [comment]
Approved

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @mirogta, transfer complete.
