### ISSUE TITLE
PEP 541 Request: `shed`

### ISSUE THREAD

**Issue by Zac-HD** [pypa/pypi-support#201]
**Project to be claimed**  
`shed`: https://pypi.org/project/shed/

**Your PyPI username**

`Zac-HD`: https://pypi.org/user/Zac-HD/

**Reasons for the request**

This project doesn't seem to exist, but attempting a `twine upload` gives me `The user 'Zac-HD' isn't allowed to upload to project 'shed'`, so I suspect it once did and has since been deleted.

I intend to use this for my new auto-formatter `shed` - https://github.com/Zac-HD/shed - which is considerably more opinionated (and willing to risk breaking code) than Black.  It combines `black`, `isort`, `autoflake`, `pyupgrade`, and (WIP) some custom rewrites inspired by `flake8-bugbear` and `flake8-comprehensions`.  

The major advantage over existing libraries is that, especially for students and other new Pythonistas, `shed` requires far less configuration precisely because it's not configurable; and because it accepts the possibility of breaking valid code it can be far more aggressive about transforming and canonicalising code so there really is only one way to do something!

**Maintenance or replacement?**

Replacement, to the degree that there is something to replace!

**Contact and additional research**

The PyPI page 404s, so I was unable to determine who (if anyone) to contact.  I searched GitHub, GitLab, and Bitbucket for Python projects named `shed`.  The closest match was [`shed_sh`, which provides a CLI under the name `shed`](https://pypi.org/project/shed_sh/) which has not had a release in over five years.  I did not find anyone who seemed to own the name `shed` on PyPI.

**Comment by yeraydiazdiaz** [comment]
Hello @Zac-HD, I can confirm the project has no releases and is thus invalid.

I will now ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by Zac-HD** [comment]
Thanks @yeraydiazdiaz and @ewdurbin!  I'm delighted to say that it's published and working well :smile:
