### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by miklevin** [pypa/pypi-support#2013]
### PyPI Username

`miklevin`

### Reason for request

I don't even remember turning on 2FA. I use Google Authenticator religiously for other apps. I don't see PyPi in my list. I wish to use 2FA and will turn it on again immediately after account recovery and generate recovery codes. Please turn off 2FA on my account.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by miklevin** [comment]
Can I get 2FA deactivated? I'm cut off from my PyPI login. I will do whatever confirmation process is necessary.

**Comment by miklevin** [comment]
Squeak

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
