### ISSUE TITLE
PEP 541 Request: pyrage

### ISSUE THREAD

**Issue by woodruffw** [pypa/pypi-support#2014]
### Project to be claimed

`pyrage`: https://pypi.org/project/pyrage

### Your PyPI username

`woodruffw`: https://pypi.org/user/woodruffw/

### Reasons for the request

This name is currently being squatted: the project on PyPI has one uploaded wheel, which in turn contains an empty Python package.

As far as I can tell, that makes it an "invalid project" for the purposes of [PEP 541](https://peps.python.org/pep-0541/#invalid-projects), which in turn makes it eligible for transfer.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The current project has no public repository, as far as I can tell.

I intend to replace it with this repository: https://github.com/woodruffw/pyrage

### Contact and additional research

I attempted to follow the ["How to request a name transfer"](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer) steps and contact the current owner directly, but they have no public email associated with their PyPI account.

The empty wheel currently published on the project also has no email metadata:

```
Metadata-Version: 2.1
Name: pyrage
Version: 0.0.1
Summary: UNKNOWN
Home-page: UNKNOWN
Author: chaokunyang
License: Apache 2.0
Platform: UNKNOWN
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10

UNKNOWN
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by woodruffw** [comment]
As an additional datum: `pyrage` was uploaded on 2020-01-15, which means that it's been squatted with no visible activity for close to half a year.

**Comment by woodruffw** [comment]
I did a little bit more sleuthing, and found a GitHub account and email address that I believe are the package owner's. I'm going to close this for the time being, and reopen only if they don't respond or indicate that they're only interested in squatting (i.e., in continuing violation).

**Comment by woodruffw** [comment]
I haven't heard back, so reopening.

**Comment by yeraydiazdiaz** [comment]
Hi @woodruffw, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by woodruffw** [comment]
Gentle ping!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by woodruffw** [comment]
Thanks a ton!
