### ISSUE TITLE
Project Limit Request: pulsar-client-sn - 100 GB

### ISSUE THREAD

**Issue by yaalsn** [pypa/pypi-support#2016]
### Project URL

https://pypi.org/project/pulsar-client-sn

### Does this project already exist?

- [X] Yes

### New limit

100 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project is https://github.com/streamnative/pulsar pulsar client python package and It has been active for almost one year. 

### How large is each release?

~400 MB total

14 Linux wheels at ~300 MB
8 macOS wheels at ~100 MB

We use `_pulsar.so` in the python package and It is compiled in different target OS, so we need to provide many targets' packages.

### How frequently do you make a release?

Roughly once every two weeks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @yaalsn :wave:
If I may suggest you something, it seems to me that you could totally use limited API in your project to avoid the large amount of wheels you have. In a nutshell, it's mainly to reduce the amount of C-API functions you can use, so you are compatible with the ABI starting from Python 3.6 onward, being possible to install that wheel with any Python 3.6+ on a specific OS. At the end of the day that will allow you to have 1 Linux wheel, and 1 macOS wheel. You can read more here: https://docs.python.org/3/c-api/stable.html

Regarding the size, you are at the moment at 10G after all the releases, asking for 10 times that size sounds like being super safe for the many releases in future releases. Would you be OK for you to get a smaller increase like 30-40G and if at some point to reach the limit, you can open a new issue? I'm certain that if you consider the limited api approach, that will happen after maaany releases.
Let me know!

**Comment by yaalsn** [comment]
@cmaureir Thanks for your suggestions! It would be better to get a smaller increase cause we need to fix the pypi releasee as soon as possible. I'll consider the limited api approach and create pr to pulsar community to reduce the release size.

The new issue is https://github.com/pypa/pypi-support/issues/2035.
