### ISSUE TITLE
My user isn't allowed to upload to project

### ISSUE THREAD

**Issue by andreasnuesslein** [pypa/pypi-support#202]
I'm assuming it's the same situation as pypa/warehouse#4057 - I'm trying to upload a package called `django-elasticsearch` but I'm getting:
```
[UploadError]
HTTP Error 403: The user 'nutz' isn't allowed to upload to project 'django-elasticsearch'. See https://pypi.org/help/#project-name for more information.
```

And https://pypi.org/project/django-elasticsearch/ yields a 404.
(I guess that qualifies as an "Invalid project" / namesquatting according to PEP 541 as well?)

Cheers

**Comment by andreasnuesslein** [comment]
I know you probably get a ton of these, but could somebody maybe look into this? Much obliged

**Comment by hugovk** [comment]
It sounds like someone has registered the project name, but not uploaded anything.

In that case, you could request a PEP 541 transfer.

**Comment by andreasnuesslein** [comment]
Hey @hugovk 
yes thank you for that quick response. Who do I talk to about the PEP 541 transfer?

**Comment by hugovk** [comment]
You can create an issue in this repo using this template (it's also an option when clicking "New issue"): 

https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME

**Comment by andreasnuesslein** [comment]
perfect thanks for your help! - https://github.com/pypa/pypi-support/issues/251
