### ISSUE TITLE
File Limit Request: h2o-pysparkling-3.3 - 200 MB

### ISSUE THREAD

**Issue by mn-mikke** [pypa/pypi-support#2021]
### Project URL

https://pypi.org/project/h2o-pysparkling-3.3

### Does this project already exist?

- [X] Yes

### New Limit

200MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`h2o-pysparkling-3.3` is a new project representing a pysparkling build for Apache Spark 3.3. Pysparkling integrates a distributed machine learning framework H2O-3 with Apache Spark.

### Reasons for the request

The size of Pysparkling artifacts are over the limit 100MB. I'm kindly ask you to change the limit to 200MB as it's already done for other pysparkling projects (builds) h2o-pysparkling-x.y (where x.y could be 3.0, 3.1, 3.2).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @mn-mikke :wave:
I've set the upload limit for `h2o-pysparkling-3.3` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice weekend!

**Comment by mn-mikke** [comment]
@cmaureir Thanks a lot!
