### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by valentinbasel** [pypa/pypi-support#2025]
### PyPI Username

valentinbasel

### Reason for request

The cell phone where I had the freeotp+ app installed with the 2FA system broke and I couldn't recover the app and I don't have a backup.
(I still have the same phone number and the same email account, but since I didn't support the freeotp+ account, I couldn't re-generate the authentication token and I can't access my pypi account).

Thank you very much for the help, I never thought that I would be left without a cell phone at once, and do not take precautions regarding freeotp +

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.
