### ISSUE TITLE
PEP 541 Request: cml

### ISSUE THREAD

**Issue by casperdcl** [pypa/pypi-support#2026]
### Project to be claimed

`cml`: https://pypi.org/project/cml

### Your PyPI username

`casper.dcl`: https://pypi.org/user/casper.dcl

### Reasons for the request

- no owner contact details provided
- no releases since initial upload in 2017-09-05
- no home page listed
- no other owner activity on PyPI at all (no other packages)

Package simply has:

```python
name = 'cml'
version = '0.0.1'
description = 'just a simple test'
install_requires = ['cloud-ml-sdk>=0.2.12']
author = 'yjw'
```

and nothing else.

Meanwhile https://github.com/iterative/cml (~3.4k stars) would like to release a proper, maintained `pip install`-able `cml` package.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

- current: none, untraceable
- replacement: https://github.com/iterative/cml

### Contact and additional research

- Downloaded & extracted source metadata, couldn't find anything
- Could not find any other projects under https://pypi.org/user/yjw

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @casperdcl, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by casperdcl** [comment]
Hey @yeraydiazdiaz it's been a couple of weeks now :)

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
