### ISSUE TITLE
Add redirect to itsdangerous pythonhosted docs

### ISSUE THREAD

**Issue by davidism** [pypa/pypi-support#203]
ItsDangerous has had docs on Read the Docs for some time now. Unfortunately, the very old pythonhosted ones still show up first in searches. I'd like to remove the old docs, but I want to replace them with a redirect to the current docs.

If I remember correctly, @di said @ewdurbin would be the one who could do this.

Please redirect https://pythonhosted.org/itsdangerous/ to https://itsdangerous.palletsprojects.com/. Let me know if I should delete the old docs first.

**Comment by ewdurbin** [comment]
redirect is all set. caches and such may cause it to be spotty for the next few hours.

**Comment by davidism** [comment]
Thanks! I deleted the docs now, everything seems to be working.
