### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by argosopentech** [pypa/pypi-support#2031]
### PyPI Username

`argosopentech`

### Reason for request

I can no longer access 2FA or my account.

I lost access to 2FA and attempted to disable it several months ago. I was able to access my account until a few weeks ago but 2FA appears to have been made mandatory and I can no longer login. I still have access to my email (admin@argosopentech.com) and the password for my account.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by argosopentech** [comment]
Thank you!
