### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pauleveritt** [pypa/pypi-support#2033]
### PyPI Username

pauleveritt

### Reason for request

My previous attempt at restoration in #1721 was successful but my 2FA approach has since failed.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hi @pauleveritt, I don't see that you have 2FA enabled on your account. You should be able to regain access by performing a password reset.
