### ISSUE TITLE
Project Limit Request: llvmlite - 20 GB

### ISSUE THREAD

**Issue by esc** [pypa/pypi-support#2039]
### Project URL

https://pypi.org/project/llvmlite/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The llvmlite project provides bindings to LLVM. It has been active for many years with the first release in 2014 and enjoys significant popularity. It is actively maintained and has regular releases. It is the backbone for the Numba library.

### How large is each release?

Each llvmlite release ships a source distribution. The last one for 0.38.0 was 130kb.

What makes llvmlite need more space is that each wheel for each python version must ship a statically linked LLVM binary which is comparatively large tp other projects on PyPi. We support a wide range of wheels, including Apple m1.

The last release had 27 binary wheels across Pythons and architectures, with a size range of 19.1 to 37.3 MB and a total size of 761 MB for all wheels.

with new Python versions and new architectures, we expect the size of each release to continue to grow over the coming years. 

### How frequently do you make a release?

Two to four times a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @esc :wave:
Thanks for the detailed explanation. 
I've set the project limit for `llvmlite` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!

**Comment by esc** [comment]
> Hey @esc 👋 Thanks for the detailed explanation. I've set the project limit for `llvmlite` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size. Have a nice week!

Thank you so much @cmaureir -- we are in the middle of a release right now so really appreciate the swift response.
