### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Byron** [pypa/pypi-support#204]
Request for account recovery.

## PyPI Username

`Sebastian.Thiel`

---

##  Reason for request

The account was backed by a google login, which at some point was turned off, making it unusable. Since then I have republished under a new name (e.g. `gitdb` became `gitdb2`), which has created its [faire share](https://github.com/gitpython-developers/gitdb/issues/45) of [confusion](https://github.com/gitpython-developers/gitdb/issues/47).

It was [suggested to me](https://gitter.im/Harmon758#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications) to try again here, after my first attempts remained unanswered to the point where I have given up.

Thanks for you help.

**Comment by ewdurbin** [comment]
Hi @Byron! I've emailed an @googlemail.com email address associated with your PyPI user account. If you're able to receive it, then you should also be able to request a password reset to recover access to your account.

**Comment by Byron** [comment]
Thank you! It worked! 

Probably I failed last time due to the intricacies between '.gmail.com' and '.googlemail.com', and possibly the capitalization of the user name.
It was also confusing that I cannot login with my email address, but must use the user name, whereas the password reset screen supports both.
