### ISSUE TITLE
PEP 541 name claim: `wraps`

### ISSUE THREAD

**Issue by nekitdev** [pypa/pypi-support#2042]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/wraps

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nekitdev

### Reasons for the request

I believe this name perfectly suits the [`wraps`][wraps] library I'm developing, though `wraps` name is currently explicitly prohibited to use.

[wraps]: https://github.com/nekitdev/wraps

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/nekitdev/wraps

### Contact and additional research

As previously mentioned, this name is not claimed by anyone, rather prohibited to use.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @nekitdev, I can confirm the project `wraps` was placed in the prohibited project names list for reasons of dependency confusion. @pypa/warehouse-admins should be able to release the name to you.

**Comment by nekitdev** [comment]
I see, thanks a lot :)

**Comment by nekitdev** [comment]
Hey there! Any updates?

**Comment by ewdurbin** [comment]
Project name released to [nekitdev](https://pypi.org/user/nekitdev)
