### ISSUE TITLE
PEP 541 Name claim: STPyV8

### ISSUE THREAD

**Issue by buffer** [pypa/pypi-support#2044]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/stpyv8

### Your PyPI username

`USER_NAME`: https://pypi.org/user/buffer

### Reasons for the request

I am the lead maintainer of STPyV8 (https://github.com/cloudflare/stpyv8). A few days ago a fake PyPi package was created for this project. The fake package was already removed but I would like the package name could be released to me. Thanks

### Source code repositories URLs

https://github.com/cloudflare/stpyv8

### Contact and additional research

angelo.dellaera@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @buffer, there is no project in PyPI with the name `STPyV8`. You should be able to upload your project normally.

**Comment by buffer** [comment]
Experiencing some issue while uploading the project...

```
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading stpyv8-10.4.132.16.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 81.3k/81.3k [00:05<00:00, 14.0kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'stpyv8' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

**Comment by seidnerj** [comment]
Is there any plan to resolve this? I'd love to be able to use this directly from PyPi.
