### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Alphare** [pypa/pypi-support#2046]
### PyPI Username

`Alphare`

### Reason for request

I reset my phone (which removed FreeOTP+) and apparently didn't keep the recovery codes for 2FA for this service, oops...

Thanks in advance and sorry for the trouble,
Raphaël

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Alphare** [comment]
I have answered the email. The notion of branch is different in Mercurial than in Git, so I've pushed a topic to the main development repository, which hopefully should serve the same purpose. :)

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
