### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pschwllr** [pypa/pypi-support#2047]
### PyPI Username

phisch

### Reason for request

The account is registered with my former work email and I lost access. I would need it to update the packages `rxnfp` and `rxnmapper`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I'm showing this account being associated with an @gmail.com address that appears to be personal. Please attempt a normal password reset to regain access to your account.
