### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jhamrick** [pypa/pypi-support#2049]
### PyPI Username

jhamrick

### Reason for request

The codes generated by my 2FA authentication app no longer seem to work, and I unfortunately do not have back up codes. I'm not sure why the 2FA codes are no longer working but as a result I can no longer log into my account!

If it helps for verifying my identity, you can see that I am a maintainer of the nbgrader package on pypi (https://pypi.org/project/nbgrader/) as well as on GitHub (https://github.com/jupyter/nbgrader/graphs/contributors).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
