### ISSUE TITLE
PEP 541 Request: ujson

### ISSUE THREAD

**Issue by rstms** [pypa/pypi-support#205]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/ujson

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/rstms

**Reasons for the request**

I believe the project has been abandoned according to the 541 criteria and that the original authors are not likely to object to transfer.   

The owner is not reachable by email. - email to the owner on 2020-02-14 bounced:
```
<jonas.tarnstrom@esn.me>:
209.222.82.10 failed after I sent the message.
Remote host said: 550 permanent failure for one or more recipients (jonas.tarnstrom@esn.me:550 5.1.1 The email account that you tried to reach does not exist. Please try 5.1.1 double-ch...)
```
The website listed on PyPI seems to be unresponsive.
The last release was 1.35 on 2016-01-20
A github issue [Is this project still maintained?](https://github.com/esnme/ultrajson/issues/343) has been open without resolution since 2019-11-22
Multiple github issues have called for the project's maintainers to get in contact with no results.

**Maintenance or replacement?**

My intent is to continue maintenance of the project, solving the immediate breakage on recent ubuntu and alpine distros with a new release of my fork of the project.  I'd then work towards testing and release of the backlog of 14 PRs and address 59 outstanding issues.

My fork of the project at: https://github.com/rstms/ultrajson  solves [https://github.com/esnme/ultrajson/issues/346](https://github.com/esnme/ultrajson/issues/346)

The original author's github is: https://github.com/esnme/ultrajson

There are a number of forks and alternatives, but the ujson project is still downloaded at a fairly high rate, and I think it's worthwhile for the python community to keep the original name active.

**Contact and additional research**

I've emailed the author, which bounced, and posted to issues on the github page, along with others,  using github's @ mechanism to contact all the users that have ever committed to the repo.  To date nobody has responded except one person who said they only ever submitted a single PR and were no longer interested in the project.   Other web searching hasn't been successful in locating Mr. Tarnstrom.

**Comment by hugovk** [comment]
Thanks for opening this issue @rstms.

 I emailed Jonas at his current email address, and he said he no longer works at EA/ESN and isn't able to work on the project for the foreseeable future, but he did make effort to make contact to see if sharing access to the project is possible. Thank you Jonas!

And that appears to have been successful, someone has made contact about finding new maintainers over at https://github.com/esnme/ultrajson/issues/343#issuecomment-587651978! 

Let's continue this over there.

**Comment by yeraydiazdiaz** [comment]
Closing this issue as contact has been made, thanks @hugovk picking this up.
