### ISSUE TITLE
PEP 541 Request: hhnk-threedi-tools

### ISSUE THREAD

**Issue by Ckerklaan** [pypa/pypi-support#2050]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/hhnk-threedi-tools

### Your PyPI username

`USER_NAME`: https://pypi.org/user/chris.kerklaan

### Reasons for the request

Hello,

We are trying to create a package called hhnk-threedi-tool. This is related to a waterboard in the Netherlands. This is however not possible. Are you able to check why we cannot upload to hhnk-threedi-tools. Thanks! We are not sure if the name is already in use, but we cannot find it.

  

### Maintenance or replacement?

Replacement

### Source code repositories URLs

We are intending to use https://github.com/threedi/hhnk-threedi-tools in its place. 

### Contact and additional research

We don't know who the owner is.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @Ckerklaan, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by Ckerklaan** [comment]
Thank you! Let me know 🙂


Met vriendelijke groet,



Chris Kerklaan

Consultant Integraal Waterbeheer

Nelen & Schuurmans



Werkdagen: ma di do vr | Working Days: Mon Tue Thu Fri

+31 (0)30 233 0200   |  +31 (0)6 4387 0711

www.nelen-schuurmans.nl<https://www.nelen-schuurmans.nl/>

Zakkendragershof 34-44, 3511AE, Utrecht

[Logo N&S]

[twitter]<https://twitter.com/nelenschuurmans>

[linkedin]<https://www.linkedin.com/company/245070/>



________________________________

**Comment by yeraydiazdiaz** [comment]
Closing as I believe the owner transferred the project to you already.
