### ISSUE TITLE
PEP 541 Request: minium

### ISSUE THREAD

**Issue by yopofeng** [pypa/pypi-support#2051]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/minium

### Your PyPI username

`USER_NAME`: https://pypi.org/user/minitest

### Reasons for the request

Hello,

We are trying to create a package named `minium`. This is a test framework for WeChat Miniprogram. Are you able to check why we cannot use `minium`. Thanks! We are not sure if the name is already in use, but we cannot find it. we have a [website](https://minitest.weixin.qq.com/#/minium/Python/readme) and use this name for years. This is the first time I upload this package, but remind me`The name 'minium' isn't allowed`

### Source code repositories URLs

no github source code

### Contact and additional research

no current owner can contact

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @yopofeng, `minium` was placed in the prohibited project names list, a @pypa/warehouse-admins should be able to release it to you.

**Comment by yopofeng** [comment]
what anything else can i do for it?

**Comment by ewdurbin** [comment]
Project released to [minitest](https://pypi.org/user/minitest)
