### ISSUE TITLE
PEP 541 Request: nodejs

### ISSUE THREAD

**Issue by samwillis** [pypa/pypi-support#2058]
### Project to be claimed

`nodejs`: https://pypi.org/project/nodejs

### Your PyPI username

`samwillis`: https://pypi.org/user/samwillis

### Reasons for the request

I have recently started a project to repackage Node.js as Python Wheels so that installing Node in a Python virtual environment is as simple as:

```
pip install nodejs
```

As the `nodejs` project name was unavailable I have up until now published it as `nodejs-bin`. However, as the `nodejs` project has been abandoned with no updates after a single release in 2015, I believe it would make much more sense for my project to use that name.

My nodejs-bin project is still in alpha and so there are not yet any stable packages depending on it.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The old `nodejs` project is here: https://github.com/markfinger/python-nodejs

My new project is here: https://github.com/samwillis/nodejs-pypi

### Contact and additional research

I have made contact with the original project owner and he has agreed to relinquish the name and pass it to me for purpose of my project. I will drop him a note and ask if he could confirm that here.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
@samwillis, it seems you are already an owner of `nodejs` so I'm closing this request.
