### ISSUE TITLE
PEP 541 Request: kite

### ISSUE THREAD

**Issue by miili** [pypa/pypi-support#2059]
### Project to be claimed

`kite`: https://pypi.org/project/kite

### Your PyPI username

`pyrocko`: https://pypi.org/user/pyrocko

### Reasons for the request

We want to claim this concise project name. To increase the project's visibility and foster the community for sustainable maintenance.

Looking at the index (https://pypi.org/search/?q=kite) we don't see conflicting project names.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/pyrocko/kite

### Contact and additional research

The project name is not claimed at the moment.

Contact info:
info@pyrocko.org, mi@gfz-potsdam.de
or here in this issue.

Thanks a bunch for your work!!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by miili** [comment]
@yeraydiazdiaz, ping

**Comment by miili** [comment]
@yeraydiazdiaz, ping

**Comment by yeraydiazdiaz** [comment]
Hello @miili, there is no project named `kite` and it is not in the prohibited project names list, you should be able to upload your project normally, are you not able to do so?

**Comment by miili** [comment]
The pipeline throws a 403
```
 ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         The user 'pyrocko' isn't allowed to upload to project 'kite'. See      
         https://pypi.org/help/#project-name for more information.       
```
see https://github.com/pyrocko/kite/runs/7510388057?check_suite_focus=true#step:4:49

**Comment by yeraydiazdiaz** [comment]
Apologies, I made a mistake, there is indeed a project called `kite` but it has no releases and is therefore considered invalid.

The owner is @jezdez so hopefully he will be able to clarify his position towards it soon.

**Comment by jezdez** [comment]
I don't use `kite` anymore, have fun!

**Comment by yeraydiazdiaz** [comment]
Thanks for the quick reply @jezdez, transfer complete.

**Comment by miili** [comment]
yay, package is online now. Thanks @yeraydiazdiaz, thanks @jezdez for the quick help and your work!
