### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by abahdanovich** [pypa/pypi-support#206]
Request for account recovery.

## PyPI Username

`abahdanovich`

---

##  Reason for request

Reason:

  - Lost 2FA authentication app or security token

Thanks for your help!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please reply there to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete.

2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
