### ISSUE TITLE
PEP 541 Request: cryptobot

### ISSUE THREAD

**Issue by ragnarok22** [pypa/pypi-support#2061]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/cryptobot

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ragnarok22

### Reasons for the request

I got this error `The name 'cryptobot' is too similar to an existing project.`. I'm create a sdk for a Telegram bot to processing payments. I think [this abandoned](https://pypi.org/project/2d6io-cryptobot/) package is the similar proyect

### Maintenance or replacement?

Replacement

### Source code repositories URLs

This is my repo: https://github.com/ragnarok22/cryptobot_python/

The other package is 404

### Contact and additional research

The current proyect has no repo

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @ragnarok22, I believe the project that's conflicting is https://pypi.org/project/crypto-bot/ which I think is too similar in name to your project to be released without causing confusion.

Would you consider a new name for your project?

**Comment by ragnarok22** [comment]
Hi @yeraydiazdiaz, thanks for replying. That project seems abandoned. I changed the package name to [cryptobot-python](https://pypi.org/project/cryptobot-python/). I don't like it but it is what it is

**Comment by yeraydiazdiaz** [comment]
It does seem abandoned, if you'd like to claim the name we can start the reachability process.

**Comment by ragnarok22** [comment]
nevermind. It's ok

**Comment by yeraydiazdiaz** [comment]
Ok, closing as requested.
