### ISSUE TITLE
PEP 541 Request: Packer

### ISSUE THREAD

**Issue by RamiAwar** [pypa/pypi-support#2062]
### Project to be claimed

`Packer`: https://pypi.org/project/packer

### Your PyPI username

`ramiawar`: https://pypi.org/user/ramiawar

### Reasons for the request

2013 last release, github repository is deleted, author email bounces. Name is too close to 'packr' which I want to claim. Or if possible, maybe un-prohibit the name 'packr'?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Old project: Not available anymore.

New project: https://github.com/RamiAwar/packr

### Contact and additional research

Email is bouncing, couldn't find any way to contact them. Github repo deleted, can't create an issue there either.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by RamiAwar** [comment]
Yes I'm suggesting we can delete packer as it is not in use anymore, and maintainer not reachable

**Comment by ewdurbin** [comment]
Project packr released to [ramiawar](https://pypi.org/user/ramiawar). Removal of abandoned projects is only acceptable if the name is intended to be used, per PEP 541.

**Comment by ewdurbin** [comment]
Maybe I misread this issue? I saw the new project had the name `packr`

**Comment by RamiAwar** [comment]
@ewdurbin Yes but I can't release my package as 'packr' because there is another project called 'packer' with an e. But that other project is not in use.

**Comment by RamiAwar** [comment]
Oh never mind someone created it 6 minutes ago, seems to have worked. Thanks!
