### ISSUE TITLE
PEP 541 Request: Element

### ISSUE THREAD

**Issue by VincentRPS** [pypa/pypi-support#2063]
### Project to be claimed

`element`: https://pypi.org/project/element

### Your PyPI username

`VincentRPS`: https://pypi.org/user/VincentRPS

### Reasons for the request

This project has seemingly been abandoned, It's repository links don't work and the last version uploaded was in 2018.

It also seems like this project could've been uploaded in a mass amount as the user made more projects that same day with the same description and metadata.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Apparently, the project url given is https://github.com/peterldowns/mypackage

The replacement project is https://github.com/tryelement/element

### Contact and additional research

Since I couldn't find the email of the user on their projects page, I looked to the GitHub page and contacted the email associated to the github account on the project.

Although, as with the projects description and what the response verified is that this project was most likely a test project.

excerpt from the response:

> Hi Vincent, I'm sorry but unfortunately I do not own this package and cannot transfer it to you. I used to have a blog with instructions on how to publish pypi packages, and the many people have published packages with my name in the metadata.

It also seems like the [owner](https://pypi.org/user/souljaboy/) has also uploaded a mass abundance of other projects, with the same description and metadata.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @VincentRPS, I can confirm the project was spam, I've transfered the project to you.
