### ISSUE TITLE
PEP 541 Request: termcolor

### ISSUE THREAD

**Issue by hugovk** [pypa/pypi-support#2064]
### Project to be claimed

`termcolor`: https://pypi.org/project/termcolor

### Your PyPI username

`hugovk`: https://pypi.org/user/hugovk

### Reasons for the request

I believe the project has been abandoned:

* Last PyPI release Jan 13, 2011 https://pypi.org/project/termcolor/#history
* No homepage or source repo
* I emailed the single listed maintainer on 20 June, but no reply (email didn't bounce)
* Cannot find maintainer on GitHub or online elsewhere

I wish to make some improvements:

* Release a wheel: termcolor is one of only 6 on this list without a wheel: https://pythonwheels.com/
* Add support for [`NO_COLOR`](https://no-color.org/) and `FORCE_COLOR` env vars
* Add type annotations
* I don't intend large changes. For more complex colour control, existing libraries such as [Rich](https://github.com/Textualize/rich), [Blessed](https://github.com/jquast/blessed) and [Colorama](https://github.com/tartley/colorama) are a better fit

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

* Current project: no code repo

* Fork: https://github.com/termcolor/termcolor

### Contact and additional research

I emailed the current owner at the Gmail address listed at https://pypi.org/project/termcolor/ on 20th June, but received no reply. The email didn't bounce. I've searched for other online presence/email addresses on GitHub, Bitbucket and via Google but didn't find any.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by groodt** [comment]
I’ve got no authority here, but Im part of the python user community and I endorse this proposal. I was just thinking of stepping up to do similar myself and pleased to see somebody else had similar ideas.

**Comment by yeraydiazdiaz** [comment]
Hi @hugovk, I will start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by hugovk** [comment]
Hi @yeraydiazdiaz, it's been six weeks, have you heard anything back? Thanks!

**Comment by hugovk** [comment]
Thank you!
