### ISSUE TITLE
PEP 541 Request: piexif

### ISSUE THREAD

**Issue by davetapley** [pypa/pypi-support#2065]
### Project to be claimed

`piexif `: https://pypi.org/project/piexif

### Your PyPI username

`davetapley`: https://pypi.org/user/davetapley

### Reasons for the request

* Sole owner of existing GitHub repo (@hMatoba) has been inactive on GitHub since Dec 2019
* Blog and email linked on their profile are gone
* Issue since Sept 2021 asking about project status unanswered: https://github.com/hMatoba/Piexif/issues/122
* Healthy interest in keeping development up: https://github.com/hMatoba/Piexif/issues/122#issuecomment-1175590297

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/hMatoba/Piexif ➡️ https://github.com/JEFuller/Piexif

### Contact and additional research

From profile at https://github.com/hMatoba:

* Sent email to address hiroaki.mtb@outlook.com
* Link to https://blog.hmatoba.net/ is offline, last post May 2020: https://web.archive.org/web/20210730171236/https://blog.hmatoba.net/

Assuming is also https://stackoverflow.com/users/4511232/hmatoba:
* "Last seen more than 1 year ago"

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @davetapley,  I will start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by davetapley** [comment]
Hi @yeraydiazdiaz any update? 🙏🏻

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
