### ISSUE TITLE
PEP 541 Request: catch22

### ISSUE THREAD

**Issue by chlubba** [pypa/pypi-support#2068]
### Project to be claimed

`catch22`: https://pypi.org/project/catch22

### Your PyPI username

`caaarl`: https://pypi.org/user/caaarl

### Reasons for the request

Dear PyPI team,

I recently made an unexperienced user of PyPI an owner of my project `catch22` on PyPI. They accidentally deleted it entirely from PyPI. The name was registered as a new project by a freshly opened account that put a placeholder in their project. I would like to recover my old name. The `catch22` project is a popular time series analysis software package that is widely used, see the [GitHub respository](https://github.com/DynamicsAndNeuralSystems/catch22) with over 200 stars and 45 forks. As you can see, I am the main contributer in this repo and have developed the package. 

I would be grateful if you could reassign the project to me. Thank you very much in advance.

Best,
Carl 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/DynamicsAndNeuralSystems/catch22

### Contact and additional research

As the account of the current owner has freshly been openend and no further contact information is available, no contact attempts were made.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @chlubba, since you transferred the project to the new owner yourself the quickest way forward would be for you to contact them and have them transfer it back?

I'm assuming that's not possible and since the project has no functionality and is therefore considered invalid I can try to contact the owner myself. If I get no response I will transfer the project to you.

**Comment by chlubba** [comment]
Hi @yeraydiazdiaz,

thank you very much for your reply. 

I originally transferred the project to somebody different from the current owner. This person then deleted the repo. After that, somebody else whom I do not know has registered a new project under the name of my old project (catch22). This unkown person is the new owner. So I cannot contact them.

Thank you very much for trying to get in touch with them. And even more so for transferring my old project back to me. :-)

Best,
Carl

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
