### ISSUE TITLE
PEP 541 Request: oida

### ISSUE THREAD

**Issue by ljodal** [pypa/pypi-support#2069]
### Project to be claimed

`oida`: https://pypi.org/project/oida

### Your PyPI username

`oda`: https://pypi.org/user/oda

### Reasons for the request

We have a project under the name Oida that we'd like to publish on PyPI. The current Oida project only has a single release, from 2019, that does not contain any code. The homepage link also leads to a 404 on GitHub, so the repo has either been deleted or is private. As such the project seems to fall clearly under the "Invalid project" definition.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I cannot find any source code for the existing project, but here is the one I want to replace it with: https://github.com/kolonialno/oida

### Contact and additional research

I have tried to reach out to the previous owner both using the email listed on PyPI and through a work email I found on Gitlab. I  have not heard anything back yet.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I seem the owner is GitHub user @riga, I will consider this the contact attempt for invalid projects and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
