### ISSUE TITLE
PEP 541 Request: nexttest

### ISSUE THREAD

**Issue by Skelmis** [pypa/pypi-support#2076]
### Project to be claimed

`nexttest`: https://pypi.org/project/nexttest

### Your PyPI username

`skelmis`: https://pypi.org/user/skelmis

### Reasons for the request

The project has no page on PyPi however I am unable to upload my project <https://github.com/Skelmis/nexttest> to it. I believe this is due to the package being 'namesquatted' and used to simply squat the name with no intention to utilize it.

### Source code repositories URLs

https://github.com/Skelmis/nexttest

### Contact and additional research

The page appears to simply not exist and has no discernible owner so no further attempts have been made to contact the owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
