### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by marsggbo** [pypa/pypi-support#208]
Request for account recovery.

## PyPI Username

`marsggbo`

The username of both TestPyPi and PyPi are `marsggbo`.

---

##  Reason for request

Reason:Lost 2FA authentication app

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please reply there to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been disabled and a password reset initiated for your user on pypi.org and test.pypi.org. You should be able to regain access by completing that password reset.
