### ISSUE TITLE
PEP 541 Request: libpyfoscam

### ISSUE THREAD

**Issue by krmarien** [pypa/pypi-support#2080]
### Project to be claimed

`libpyfoscam `: https://pypi.org/project/libpyfoscam/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/krmarien/

### Reasons for the request

The project is not updated anymore in 2+ years. On GitHub there are no responses anymore on issues and pull requests.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current: https://github.com/viswa-swami/python-foscam
New: https://github.com/krmarien/python-foscam

### Contact and additional research

Created a GitHub issue, but no response received. Also pull requests of others are not answered.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @krmarien, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by krmarien** [comment]
Is it also possible to transfer the project on test.pypi.org (https://test.pypi.org/project/libpyfoscam/)
