### ISSUE TITLE
PEP 541 Request: swordfish

### ISSUE THREAD

**Issue by Adoni5** [pypa/pypi-support#2085]
### Project to be claimed

`swordfish`: https://pypi.org/project/swordfish

### Your PyPI username

`adoni5`: https://pypi.org/user/adoni5

### Reasons for the request

There doesn't seem to be an existing project with this name, but I get 403 The user 'adoni5' isn't allowed to upload to project 'swordfish'. when trying to claim it for the first time.

As I understand it from looking at #1953 there is a high likelihood that this a package that is being squatted on and is invalid, unless it is reserved by admins for some reason. 

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My repo is https://github.com/LooseLab/swordfish
I'm not sure if I can find the correct repo for whomever holds the swordfish package name, so I won't include one.

### Contact and additional research

I haven't made any attempts to contact the current owners as I cannot be sure of who they are.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Adoni5, I can confirm the project exists but has no releases and is therefore considered invalid. The owner is @dstufft an active member of the PyPA so hopefully this issue will be resolved soon.

**Comment by dstufft** [comment]
I've invited [adoni5](https://pypi.org/user/adoni5) as an owner on the swordfish project on PyPI, feel free to use the name and to remove my access to the project once you confirm the invite.

**Comment by Adoni5** [comment]
Hi @dstufft,

Thanks very much for your swift response here, but I've been on holiday for the past two weeks and have only just seen the invite email, which is obviously expired now! When you get a moment would you be kind enough to resend it? 

Many Thanks,
Rory

Also thanks @yeraydiazdiaz for handling the issue.
