### ISSUE TITLE
PEP 541 Request: pyasn1 and pyasn1-modules

### ISSUE THREAD

**Issue by tiran** [pypa/pypi-support#2090]
### Project to be claimed

`pyasn1`: https://pypi.org/project/pyasn1
`pyasn1-modules`: https://pypi.org/project/pyasn1-modules

### Your PyPI username

`tiran`: https://pypi.org/user/tiran
`droideck`: https://pypi.org/user/droideck

### Reasons for the request

Simon Pichugin (@droideck) and I are co-workers of Ilya Etingof (@etingof) at Red Hat. Ilya has not been able to maintain pyasn1 and pyasn1-modules for the past two years. He won't be able to take of the packages in the foreseeable future, too. We like to take care of the packages until Ilya is back.

The packages are dependencies for open source software that we develop or maintain:
* https://github.com/python-ldap/python-ldap
* https://github.com/389ds/389-ds-base/
* https://github.com/freeipa/freeipa/

I have also contacted @russhousley (pyasn1 contributor, owner of https://github.com/russhousley/pyasn1-alt-modules) and @yeraydiazdiaz. Russ is interested to join us as maintainer. Yeray has previously requested project ownership in ticket #1104.

Please add me and Simon (https://pypi.org/user/droideck/) as admins to the projects on PyPI and [Test PyPI](https://test.pypi.org/).

* `pyasn1`: https://pypi.org/project/pyasn1
* `pyasn1-modules`: https://pypi.org/project/pyasn1-modules

### Maintenance or replacement?

Maintenance

## Ilya's repos

* https://github.com/etingof/pyasn1
* https://github.com/etingof/pyasn1-modules

## new pyasn1 organization repos

I have created a new organization for pyasn1. The repositories are 

* https://github.com/pyasn1/pyasn1
* https://github.com/pyasn1/pyasn1-modules

### Contact and additional research

Ticket https://github.com/pypa/pypi-support/issues/1104 lists several failed attempts to contact Ilya. If necessary I can ask Ilya's manager to comment on the ticket, too.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Thanks for your help clarifying the situation and taking over these project @tiran. I have transfered both project to you and Simon.

**Comment by tiran** [comment]
Thank you! Could you please transfer ownership of Test PyPI projects as well? I would like to test new release workflow before I push releases to main PyPI.

**Comment by yeraydiazdiaz** [comment]
I've transferred `pyasn1` in Test PyPI to you, seems Simon does not have an account with the same name in PyPI and there doesn't seem to be a `pysan1-modules` in Test PyPI.

**Comment by tiran** [comment]
Thanks! I have created `pyasn1-modules` on Test PyPI. I have now access to both projects on both PyPI instances.
