### ISSUE TITLE
File Limit Request: dplus-api - 150 MB

### ISSUE THREAD

**Issue by zmbq** [pypa/pypi-support#2091]
### Project URL

https://pypi.org/project/dplus-api/

### Does this project already exist?

- [X] Yes

### New Limit

150MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This project is the Python API For D+ - an xray defraction simulator. Older versions (pre 4.6) required D+ to be installed separately to work. This new version contains the relevant parts of the D+ backend, and is self-contained.

Alas, D+ uses the GPU for faster calculations. The Linux wheels contain various CUDA static libraries, and is quite large. I've noticed other GPU packages suffer from the same problem on Linux.

### Reasons for the request

We can't fit the GPU code in 100MB. We do not expect the 150MB limit to increase in the foreseeable future, unless CUDA libraries become even larger.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @zmbq :wave:
Thanks for the explanation!
I've set the upload limit for `dplus-api` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice weekend!
