### ISSUE TITLE
PEP 541 Request: pycanon

### ISSUE THREAD

**Issue by alvarolopez** [pypa/pypi-support#2092]
### Project to be claimed

`pycanon`: https://pypi.org/project/pycanon

### Your PyPI username

`aloga`: https://pypi.org/user/aloga

### Reasons for the request

The project seems to be abandoned in SourceForge, with no code activity since 2008. Its repository only contains a single tar.gz file. I have tried to contact the maintainer, to no avail.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project repository: https://sourceforge.net/projects/pycanon/files/
New project repository: https://gitlab.ifca.es/privacy-security/pycanon/ (Mirror in https://github.com/IFCA/pycanon)

### Contact and additional research

I have tried to contact the owner via email, to no avail. The SourceForge support page does not provide any alternative way to contact the owner (https://sourceforge.net/projects/pycanon/support)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by alvarolopez** [comment]
After checking a bit more, it seems that the owner is @kpoman, so hopefully he will be able to clarify the pycanon status!

**Comment by kpoman** [comment]
Hi @alvarolopez ! I am not longer maintaining it, as it depends on an abandoned SDK and specific canon cameras, so nobody should have them as of 2022. Feel free to close it. Thank you for prompting me !

**Comment by alvarolopez** [comment]
Many thanks, @kpoman (and ping @yeraydiazdiaz)!!

**Comment by yeraydiazdiaz** [comment]
Thank you for your quick reply @kpoman, transfer complete.
