### ISSUE TITLE
File Limit Request: Replidec - 400 MB

### ISSUE THREAD

**Issue by pengSherryYel** [pypa/pypi-support#2095]
### Project URL

https://pypi.org/project/Replidec/

### Does this project already exist?

- [X] Yes

### New Limit

400M

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This package is a bioinformatic software, and is used to predict the replication cycle of phages. Because the biological data used in this software is big, Although data were used by other software to compact to reduce the size. The Software will keep active at least for three years.

### Reasons for the request

Because this is the first version of this project, the software will keep active at least for three years. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @pengSherryYel :wave:
Thanks for the shared information. Have you consider a  different way to distribute the data you require in your package? for example there are projects like `nltk` that provide a specific way of  getting datasets https://www.nltk.org/install.html#installing-nltk-data
From your description, it does sounds that it's the only problem at  the moment of why you get large wheels.
Let me know what do you think about this approach.

**Comment by pradyunsg** [comment]
Closing this out given the lack of a response on this. Please feel welcome to come back and respond to this, or to file a new issue with the answer. :)
