### ISSUE TITLE
File Limit Request: MHCnuggets - 150 MB

### ISSUE THREAD

**Issue by XiaoshanShao** [pypa/pypi-support#2097]
### Project URL

https://pypi.org/project/mhcnuggets/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is a package for neoantigen predictions. It has been active since 2018. The new release contains data that needs an increase of file size limit. We have already down-sampled these data files, and compressed the distribution to a tar.gz file.

### Reasons for the request

This is a package for neoantigen predictions. It has been active since 2018. The new release contains data that needs an increase of file size limit. We have already down-sampled these data files, and compressed the distribution to a tar.gz file.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @XiaoshanShao :wave: Thanks for the description.
I've set the upload limit for `mhcnuggets` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
