### ISSUE TITLE
PEP 541: transfer ownership of Flask-CRUD

### ISSUE THREAD

**Issue by revmischa** [pypa/pypi-support#21]
Module: https://pypi.org/project/Flask-Crud
Last release: 2014
Project description: UNKNOWN

I have opened a ticket on GitHub asking if I can take it over and sent an email to the author at plummer574@gmail.com

Thanks!

**Comment by revmischa** [comment]
What condition needs to be met to continue the process here?

**Comment by jamadden** [comment]
I've attempted another contact using the verified PyPI email address for the owner; that account has recently been active. There's also very recent GitHub activity for that account and I've attempted contact that way. I don't have any records of previous contact attempts by PyPI moderators so in a strict interpretation of PEP 541 I'm afraid this would start the reachability countdown.

**Comment by jamadden** [comment]
The owner has responded in plumdog/flask_crud#2. That means this project meets the PEP 541 definition of an *active* project (nor is it an *invalid* project). The owner indicated unwillingness to transfer the name, and the PEP [specifically removes PyPI from conflict arbitration for active projects](https://www.python.org/dev/peps/pep-0541/#name-conflict-resolution-for-active-projects), so I don't think there's anything more PyPI can do here. 

Thank you for contributing to the Python ecosystem and I wish you good luck with your project.
