### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sgibson91** [pypa/pypi-support#2100]
### PyPI Username

`sgibson91`

### Reason for request

Lost 2FA authentication app or security token: for both Test PyPI and PyPI (same username on both).

(Really sorry - I'm now switching to an authenticator app that allows multiple devices and has cloud backup.)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by sgibson91** [comment]
I had recovery codes on my main PyPI account so I have recovered that - but I did not do the same for Test PyPI so still doesn't have access to that. But that is less critical.

**Comment by ewdurbin** [comment]
TestPyPI 2FA disabled and password reset issued.

**Comment by sgibson91** [comment]
Thank you :pray:
