### ISSUE TITLE
PEP 541 Request: ZTPServer PyPi Test Maintainer Transfer

### ISSUE THREAD

**Issue by mharista** [pypa/pypi-support#2102]
### Project to be claimed

`PROJECT_NAME`: https://test.pypi.org/project/ztpserver

### Your PyPI username

`USER_NAME`: https://test.pypi.org/user/mhartzel

### Reasons for the request

The project is owned by Arista Networks. I have successfully added myself as a maintainer for the standard PyPi project but only Jere Julian is a maintainer on PyPi test. I have contacted Jere but he does not know his credentials to log in and his password reset likely has gone to his Arista email account that he no longer has access to since he has left the company awhile ago. I would like to have my account added as the maintainer for the ZTPServer project on PyPi test because Jere no longer works at Arista.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/arista-eosplus/ztpserver

### Contact and additional research

I contacted Jere today. Here is the email thread:

Hi Jere,

Hope all is well.

I've recently been tasked with fixing an issue on the old ZTPServer project. I've been able to get maintainer access to the project in PyPi but I wanted to also get maintainer access to the project in PyPiTest. Unfortunately you are the only maintainer in PyPiTest. Do you by chance still have access to PyPiTest and if so could you add me to the ZTPServer project as a maintainer?

https://test.pypi.org/project/ztpserver/

Thank you,
Matt

Response from Jere:

Eek. The credentials I have saved for PyPI don't work there. So I tried a password reset and I can only guess that it went to my old arista email.    So, unless they still have that forwarding to John, then it is likely gone.    I wonder if there's some way to get the admins to reassign ownership if they can look and see that you're also with Arista and you can explain that I'm no longer there.   They should also be able to see you as the owner on the live PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mharista** [comment]
Any update here? I can provide additional info or contact info for Jere if necessary.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by mharista** [comment]
Thanks!
