### ISSUE TITLE
PEP 541 Request: pytorch-ema

### ISSUE THREAD

**Issue by faroit** [pypa/pypi-support#2105]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pytorch-ema

### Your PyPI username

`USER_NAME`: https://pypi.org/user/lucidrains

### Reasons for the request

violates PEP 541 as this is an intellectual property infringement. 

The violation is clear even without looking at the source code, by just comparing the readme files: https://github.com/lucidrains/ema-pytorch/blob/main/README.md with https://pypi.org/project/pytorch-ema/#description.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Original package: https://github.com/lucidrains/ema-pytorch
Clone (already deleted): https://github.com/naetherm/torch_ema

### Contact and additional research

Please note: I am not the maintainer of either `pytorch-ema` or `ema-pytorch`. Thus I cannot and I don't want to claim anything in the name of @lucidrains. Instead, I discovered the copyright infringement accidentally from a users perspective.

Thus, the preferred solution here __does not require any ownership transfer__ but instead to __delete `pytorch-ema`__. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @faroit, as PEP 541 describes:

> Possibly-infringing packages should be reported to [legal@python.org](mailto:legal%40python.org) and counsel to the Python Software Foundation will determine an appropriate response. A package can be removed or transferred to a new owner at the sole discretion of the Python Software Foundation to address a claim of infringement.

I will keep this issue open for tracking purposes.

**Comment by di** [comment]
This seems like a fairly obvious typosquat on https://pypi.org/project/ema-pytorch/. I've prohibited the project name.
