### ISSUE TITLE
PEP 541 Request: LIA

### ISSUE THREAD

**Issue by Professor-G** [pypa/pypi-support#2106]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/LIA

### Your PyPI username

`USER_NAME`: https://pypi.org/user/godines

### Reasons for the request

Hello team I reached out to the owner of the project LIA and he agreed to give me the name for my PhD project! My project was previously called MicroLIA. 

The owner of LIA deleted the project so that I could re-upload using the name, I have since deleted my MicroLIA project but cannot upload it as LIA because it is similar to another name. Can we please make an exception in this case?

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Professor-G/LIA

### Contact and additional research

I have contacted the owner via e-mail, he deleted his package so that I could re-upload my own using the name.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @Professor-G, the project does not exist so you should be able to simply upload your package normally.

**Comment by Professor-G** [comment]
@yeraydiazdiaz -- I just tried again but same error:

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         The name 'LIA' is too similar to an existing project. See              
         https://pypi.org/help/#project-name for more information.

**Comment by yeraydiazdiaz** [comment]
I see, so as the error is says the problem is that because the owner deleted the project instead of transferring it to you PyPI is now preventing you from uploading because the project name is too close to another one, most likely https://pypi.org/project/lla/ (LLA). They coexisted before because this feature of PyPI is fairly new.

Given how close it is to LLA I would suggest using a different name to avoid confusion.

**Comment by Professor-G** [comment]
Can we please make an exception? LIA has been advertised since 2019 in the gravitational microlensing community, which is why the owner of the package agreed to delete it so that I could upload my own. I see now we should have transferred ownership instead, so can an exception be made for this case?
