### ISSUE TITLE
PEP 541 Request: optik

### ISSUE THREAD

**Issue by Boyan-MILANOV** [pypa/pypi-support#2110]
### Project to be claimed

`optik`: https://pypi.org/project/optik/

### Your PyPI username

`trailofbits`: https://pypi.org/user/trailofbits

### Reasons for the request

- the current `optik` package available on PyPI hasn't been updated since 2005
- the download statistics indicate that there is no current usage of it
- `optik` doesn't even show up when searching for `optik` in the PyPI search console: https://pypi.org/search/?q=optik

### Maintenance or replacement?

Replacement

### Source code repositories URLs

- The project we would like to replace doesn't have its source code directly available online on Github or gitlab. The main page from the project is http://optik.sourceforge.net/. It seems that the source archives can be downloaded from https://sourceforge.net/projects/optik/files/

- The project we would like to package and upload to PyPI is hosted on Github at: https://github.com/trailofbits/optik 

### Contact and additional research

I tried contacting the current owner on two different e-mail addresses taken from his personal page (gward@python.net, greg@gerg.ca), without success. The `python.net` one is not valid anymore and I didn't get any response from the other one: 

<img width="1219" alt="Screenshot 2022-07-21 at 08 39 55" src="https://user-images.githubusercontent.com/16084180/180146563-eff395ed-a302-48ca-8c0e-8490c938a7e3.png">

 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Boyan-MILANOV, I will now start the reachability process for your request which can take up to 6 weeks. I believe the owner is GitHub user @gward, hopefully he will be able to provide some information regarding his project.

**Comment by gward** [comment]
Hello,

I do not want to abandon the name optik in pypi. That project is part of the history of the Python community, and we should not simply discard our history. IMHO. 

Thanks!

Greg

**Comment by yeraydiazdiaz** [comment]
Thank you for your quick reply @gward, as stated in PEP 541 we cannot transfer the project against the wishes of the current owner.
