### ISSUE TITLE
File Limit Request: reconstructor - 2000 MB

### ISSUE THREAD

**Issue by emmamglass** [pypa/pypi-support#2112]
### Project URL

https://pypi.org/project/reconstructor/

### Does this project already exist?

- [X] Yes

### New Limit

2000

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project takes an amino acid fasta sequence and creates a genome scale metabolic network reconstruction. We are currently putting together a package before publication of this tool in an academic journal. This code has been used (unpackaged) in several academic research projects already, and has aided in important scientific discovery. The main file uses three databases that are over the 100MB limit and must be included in the package for functionality. The databases are 115 MB, 104 MB, and 1.64 GB. 

I have tried to use other ways of including this dataset in the package such as a git dependency, but these files are too large to upload to a GitHub repository as well.

### Reasons for the request

The project size will not increase in the future, once it is packaged that will be it. If the individual file limit is increased, the total package will be 4.02 GB large including the files that were unable to be uploaded previously (the aforementioned database files). 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @emmamglass :wave:
Thanks for the shared information. Have you consider a  different way to distribute the data you require in your package? for example there are projects like `nltk` that provide a specific way of  getting datasets https://www.nltk.org/install.html#installing-nltk-data
From your description, it does sounds that it's the only problem at  the moment of why you get large wheels.
Let me know what do you think about this approach.

**Comment by pradyunsg** [comment]
Closing this out given the lack of a response on this. Please feel welcome to come back and respond to this, or to file a new issue with the answer. :)
