### ISSUE TITLE
PEP 541 Request: miko

### ISSUE THREAD

**Issue by Animenosekai** [pypa/pypi-support#2113]
### Project to be claimed

`miko`: https://pypi.org/project/miko

### Your PyPI username

`Animenosekai`: https://pypi.org/user/Animenosekai

### Reasons for the request

Hello

I'm currently making a new Python documentation style, with its parser and CLI.

I was looking for a new name for my project. Thought about `zero` at first, but it seems to be taken and maintained. Then I thought about `miko`

`miko` seems to be already taken, but no update has been done for a while (Sep 2, 2018) and hasn't changed since its "0.1.dev9021825" version.

Moreover, the actual code doesn't seem to have a lot of things : from what I have downloaded, it seems to only print "Hello Miko...".

Also, the home page link seems to be broken, and the email associated with the project doesn't work either (I got a `Relay access denied` error when trying to send an email).

I find the name perfect for my project and would like to claim this name since the current project holding it seems to be abandoned.

Sincerely,
Animenosekai

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current Project Repository : https://repo.spanda.io/ysicing/miko-cli

New Project Repository : https://github.com/Animenosekai/zero

### Contact and additional research

I tried to send an email to the email address on the project page without any success :

<img width="789" alt="Capture d’écran 0004-07-22 à 03 51 10" src="https://user-images.githubusercontent.com/40539549/180344774-3523d102-7ebe-4661-ab6b-845cb5deb549.png">

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Animenosekai, I can confirm the project has very limited functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.

**Comment by Animenosekai** [comment]
> The owner replied accepting the transfer which is now complete.

Thank you ! ✨
