### ISSUE TITLE
PEP 541 Request: django-avatar

### ISSUE THREAD

**Issue by johanneswilm** [pypa/pypi-support#2114]
### Project to be claimed

`django-avatar`: https://pypi.org/project/django-avatar

### Your PyPI username

`johanneswilm`: https://pypi.org/user/johanneswilm

### Reasons for the request

No releases have been made that are compatible with current versions of Django. We are several contributors who pushed patches to make ti Django 3.2 and Django 4.0 compatible [1][2][3]. The maintainer has stopped working on the package and has stated on Twitter that he has stopped working on unpaid open source software projects [4]. He has also stopped corresponding since early May 2022.

[1] https://github.com/grantmcconnaughey/django-avatar/issues/210
[2] https://github.com/grantmcconnaughey/django-avatar/pull/201
[3] https://github.com/grantmcconnaughey/django-avatar/pull/209
[4] https://twitter.com/gmcconnaughey/status/1546263970201337857

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The original:
https://github.com/grantmcconnaughey/django-avatar

My updated version:
https://github.com/johanneswilm/django-avatar

### Contact and additional research

We tried tagging the owner in the issues mentioned above. In early May this resulted in our changes being merged in and a release was promised. The release never substantiated and we have not heard back since then.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @johanneswilm, I see you've suggested moving the project to JazzBand and that @jezdez is already an owner of the project. I'm not familiar with the process of adding project to JazzBand but hopefully one of the current owners can add you as a maintainer if you are interested.

I'll keep this issue open to track the process and will start the reachability process if no progress is made.

**Comment by johanneswilm** [comment]
Hey @yeraydiazdiaz , yes that would be the preferred solution. @jezdez didn't respond to me previously tagging him, so I'm wondering if it just gets drowned in too much mail from github. If you know of another way of contacting him, maybe that should be tried.

**Comment by jezdez** [comment]
@johanneswilm Yep, that's the case, just a long TODO list myself 😬 Thanks for pinging me about it again though, django-avatar is a lifetime ago but it would certainly fit into Jazzband.

Could you please open a proposal here: https://github.com/jazzband/help/issues/new/choose and tag @grantmcconnaughey so we can take it from there?

@yeraydiazdiaz I think it would be best to close this request since we have another way to move this forward.

**Comment by yeraydiazdiaz** [comment]
Thanks for the quick reply @jezdez, closing as requested.

**Comment by johanneswilm** [comment]
@jezdez Ok, an issue has now been filed at https://github.com/jazzband/help/issues/305 . I see some proposals for packages have been waiting since 2016. If it can take a few years to get approval to move it into JazzBand, given that you have access to makign releases, do you think you could make a release with the current code first so that all those of us using Django 3.2/4.0/etc. can use it again?

**Comment by jezdez** [comment]
@johanneswilm Some requests are pretty old, you're right, and lack the public information for why they didn't go ahead. I've replied in https://github.com/jazzband/help/issues/305 to move ahead since I think it's a good match. Let's see what grantmcconnaughey says about it.
