### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by xliiv** [pypa/pypi-support#2115]
### PyPI Username

xliiv

### Reason for request

Lost access to email address

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Primary email address bounced. Please email support@pypi.org referencing this issue and stating the email address you'd like associated with the account.

**Comment by xliiv** [comment]
The account is recovered.
I'm closing this issue.

Thank you!
