### ISSUE TITLE
PEP 541 Request: coltrane

### ISSUE THREAD

**Issue by adamghill** [pypa/pypi-support#2118]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/coltrane

### Your PyPI username

`USER_NAME`: https://pypi.org/user/adamghill

### Reasons for the request

After searching on PyPI and not seeing any projects with the name `coltrane`, I uploaded my package to test.pypi.org just fine: https://test.pypi.org/project/coltrane/. But, then when I uploaded to pypi.org I got this error:

```
UploadError

HTTP Error 403: The user 'adamghill' isn't allowed to upload to project 'coltrane'. See https://pypi.org/help/#project-name for more information.
```

I assume that someone has the project name, but has never created a release for it? If possible, I would like the ability to use this project name. Thank you!

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/adamghill/coltrane

### Contact and additional research

Not able to

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @adamghill, I cannot see a project with that name in PyPI or any reason why it would prevent you from uploading your project. Maybe something's changed since you posted the issue, could you try uploading it again?

**Comment by adamghill** [comment]
Hello! I was able to upload with the `coltrane` project name now when I just tried! Sorry for the false alarm, I will close this issue. Thank you for checking for me!
