### ISSUE TITLE
PEP 541 Request: deli

### ISSUE THREAD

**Issue by maxme1** [pypa/pypi-support#2119]
### Project to be claimed

`deli`: https://pypi.org/project/deli/

### Your PyPI username

`memax`: https://pypi.org/user/memax/

### Reasons for the request

The project was created in 2014 and still doesn't have a single release published, so `pip install deli` simply fails with `Could not find a version that satisfies the requirement deli (from versions: none)`

Currently the project is clearly abandoned - the latest commit in its repository is also 8 years old.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project from pypi: https://github.com/tonysyu/deli
My project: https://github.com/maxme1/deli

### Contact and additional research

I contacted the author (@tonysyu) ~3 months ago via the email provided in the project description, but didn't receive a response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @maxme1, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by maxme1** [comment]
Thank you!
