### ISSUE TITLE
PEP 541 Request: cliche

### ISSUE THREAD

**Issue by kootenpv** [pypa/pypi-support#212]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/cliche

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/PascalVKooten

**Reasons for the request**

There is no sign of a package having been uploaded so far. 

There are already a lot of CLI tools out there, which is why I think cliche is the perfect name for a CLI tool.

**Maintenance or replacement?**

Publish a different one as there is nothing to be replaced.

For now it is called `mincli` but I think it is a bad name: https://github.com/kootenpv/mincli

**Contact and additional research**

There is no contact information available.

I can be reached here or my known email address.

**Comment by jamadden** [comment]
There was a project with that name that had a single release (0.1) in 2013. It was removed on 2018-08-06. I will add it to the queue for the admins to release it.

**Comment by kootenpv** [comment]
@jamadden Thanks a lot! I'll design a logo for cliche then :)

**Comment by kootenpv** [comment]
@jamadden Is there something I can still do about this?

**Comment by jamadden** [comment]
It's on the list for the admins to transfer. Admin resources are extremely limited though, so we appreciate your patience.

**Comment by ewdurbin** [comment]
transfer complete.
