### ISSUE TITLE
File Limit Request: aisfx - 300 MB

### ISSUE THREAD

**Issue by alisonbma** [pypa/pypi-support#2120]
### Project URL

https://pypi.org/project/aisfx/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is code and deep learning model checkpoints to accompany an accepted paper at the International Society for Music Information Retrieval Conference (ISMIR); submitted and accepted this year in 2022.

Every file is small except for the model checkpoints .pickle files, which range from 95-250MB. To be safe, I have requested a 300MB limit. I only plan to upload 1-3 model checkpoints. The testPyPI version of this project has more information and examples of the data that may go over this size limit.

### Reasons for the request

N/A

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @alisonbma :wave:
I've set the upload limit for `aisfx` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
