### ISSUE TITLE
Account recovery request - Lost recovery codes

### ISSUE THREAD

**Issue by Perzan** [pypa/pypi-support#2122]
### PyPI Username

`Perzan`

### Reason for request

I have recently reset my PyPI password using my email address.
I am unable to log in with my new password, for I have lost both my 2FA app **_and my recovery codes_**.
I am aware that I have generated recovery codes in the past, but I have since lost those codes.
Please remove 2FA from my account.
Thank you.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
