### ISSUE TITLE
PEP 541 Request: beat

### ISSUE THREAD

**Issue by hvasbath** [pypa/pypi-support#2123]
### Project to be claimed

`beat`: https://pypi.org/project/beat

### Your PyPI username

`hvasbath`: https://pypi.org/user/hvasbath

### Reasons for the request

The project has not been updated since 2019.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

current project: https://github.com/tonyskapunk/beat
new project: https://github.com/hvasbath/beat

### Contact and additional research

The author of the current project has been contacted and a response is still pending.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hvasbath** [comment]
@tonyskapunk I wrote you an email asking if you would agree to free the package-name. It would help me a lot as the software is published in scientific literature- where I cannot change the name anymore. Whats your take on that? Thanks a lot in advance!

**Comment by tonyskapunk** [comment]
Hello @hvasbath, to share what I replied over email.

I agree to transfer the name from my project https://pypi.org/project/beat to you.

I would only request to have a mention in your project to mine in case anyone looks for the internet time project.

I think this is the best place to make the arrangement and set the timelines for the change. Do you have any idea or plan for that? Is there a standard procedure or best practice for the change of ownership, etc?

**Comment by hvasbath** [comment]
Hello @tonyskapunk! Thanks a lot for agreeing to free the name! I will for sure mention your project in the README.md.

It would be best to do the transfer as soon as maintainers look into it. It seems they are very busy- and issues regarding PEP541 are tackled only now and then, which is of course totally understandable.
I am waiting with my new release just for this being resolved.

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @tonyskapunk, transfer complete.

**Comment by hvasbath** [comment]
Awesome that was fast! Thanks a lot!
