### ISSUE TITLE
PEP 541 Request: mapillary-tools

### ISSUE THREAD

**Issue by cbeddow** [pypa/pypi-support#2124]
### Project to be claimed

`mapillary-tools`: https://pypi.org/project/mapillary-tools

### Your PyPI username

`mapillary`: https://pypi.org/user/mapillary

### Reasons for the request

The current project is not actively maintained, and represents a fork of a very actively maintained project that we (Mapillary team) wish to keep updated on PyPI.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

current: https://github.com/MarcelloPerathoner/mapillary-tools/
new: https://github.com/mapillary/mapillary_tools

### Contact and additional research

Contact and agreement we made here: https://github.com/MarcelloPerathoner/mapillary-tools/issues/1

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @cbeddow since @MarcelloPerathoner approved the transfer in his repo I have now transferred the project to you.
