### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sethrj** [pypa/pypi-support#2125]
### PyPI Username

`sethrj`

### Reason for request

I lost access to my 2FA authentication app (Google Authenticator) when switching phones 9 months ago, and my account recovery codes were lost due to an unrelated issue a year before that. I haven't tried to log into pypi in the last two years, I guess. Thanks for your help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by sethrj** [comment]
Branch pushed, email responded to. I'm so happy for your assistance!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
