### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jm-rivera** [pypa/pypi-support#2127]
### PyPI Username

jm-rivera

### Reason for request

I changed my phone and therefore lost access to my authentication token which was linked to my google authenticator. I had generated recovery codes for test PyPI but not PyPI. I therefore do not have access to my account at pypi.org

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by jm-rivera** [comment]
Thank you @ewdurbin, just did as indicated and responded to the email. Thanks again!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
