### ISSUE TITLE
PEP 541 Request: ril (Name isn't allowed)

### ISSUE THREAD

**Issue by Cryptex-github** [pypa/pypi-support#2128]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ril

### Your PyPI username

`USER_NAME`: https://pypi.org/user/cryptex-pypi/

### Reasons for the request

I have a project named `ril` and I'd like to upload it to pypi with the corresponding name. However when attempting such, it says `The name 'ril' isn't allowed`.

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'ril' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

I'd like to understand why this name isn't allowed and whether is possible to lift such limitation.

### Source code repositories URLs

https://github.com/Cryptex-github/ril-py

### Contact and additional research

There is no existing package named with `ril` so no one to contact.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Cryptex-github, the name `ril` was placed in the prohibited project names list by a @pypa/warehouse-admins to avoid dependency confusion attacks. I see no reason for it to be released to you, I've placed your request in the admin queue.

**Comment by Cryptex-github** [comment]
> Hello @Cryptex-github, the name `ril` was placed in the prohibited project names list by a @pypa/warehouse-admins to avoid dependency confusion attacks. I see no reason for it to be released to you, I've placed your request in the admin queue.

Hello, thank you for your reply. May I ask which package in particular does the name conflicts/might leads confusion with?

**Comment by yeraydiazdiaz** [comment]
I can't be 100% sure but a quick search yields `rll`, `rii` and `rli` as candidates.

**Comment by ewdurbin** [comment]
Project released to [cryptex-pypi](https://pypi.org/user/cryptex-pypi/)

**Comment by yeraydiazdiaz** [comment]
Thanks @ewdurbin
