### ISSUE TITLE
PEP 541 Request: sci-oer

### ISSUE THREAD

**Issue by MarshallAsch** [pypa/pypi-support#2129]
### Project to be claimed

`sci-oer`: https://pypi.org/project/sci-oer

### Your PyPI username

`marshallasch`: https://pypi.org/user/marshallasch

### Reasons for the request

I accidentally created the project with a `-` in the name (I built an old version of the package initially that had the dash). This project is not yet in use so it will not cause any breaking changes. 

There is currently one partner package `scioer-builder` that we are also maintaining, and the name change will help keep consistency with that. 

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/sci-oer/student-cli

### Contact and additional research

I am the owner of the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @MarshallAsch, if I understood correctly you're trying to change the name of your project to `scioer` (without a dash), PyPI does not have that feature but you should be able to make necessary changes to your package to have the name `scioer` and upload it normally. Once you're happy with it you can delete `sci-oer`.

**Comment by MarshallAsch** [comment]
Hey @yeraydiazdiaz I tried originally to change name to remove the - and republish it, that was rejected as a duplicate because of the name normalization. If I go to delete the existing package I am given a warning saying that once its deleted the name cannot be reused. 

Is there any other way around the mistake or am I stuck with the - ?

**Comment by ewdurbin** [comment]
Project scioer released to [marshallasch](https://pypi.org/user/marshallasch), You can publish to that then delete sci-oer if you choose.
