### ISSUE TITLE
Request reconnection of account

### ISSUE THREAD

**Issue by pennythewho** [pypa/pypi-support#213]
Request for account recovery.

## PyPI Username

pennythewho

---

##  Reason for request

Reason:
Mine is currently the sole account associated with the SeaFreeze project on PyPI, although I am just one of several contributors to the project.  I use DUO for authentication but only had it installed on one device.  When I replaced that device, I thought that the data transfer process would ensure that the keys were transferred.  I wiped the old device before giving it to a family member.  However, the keys did not properly transfer and now DUO shows the PYPI account is disabled, and the option to reconnect it requires me to be able to log into PyPI, which I cannot do.   I need to reconnect to my account so that I can add other owners to the project.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
