### ISSUE TITLE
PEP 541 Request: sketch

### ISSUE THREAD

**Issue by bluecoconut** [pypa/pypi-support#2132]
### Project to be claimed

`sketch`: https://pypi.org/project/sketch

### Your PyPI username

`bluecoconut`: https://pypi.org/user/bluecoconut/

### Reasons for the request

We have a project under the name Sketch we'd like to publish on PyPI. The current sketch project only has a single release, from 2011. The homepage link leads to a github repo: https://github.com/nikcub/Sketch with no updates since 2011, and also includes language about it no longer being supported / developed (specifically the `About` section has: `About: [DEPRECATED]`. As such, the project seems to clearly fall into the "Abandoned project" definitions. Also, this possibly may fall into "Invalid project" category: of note, a search on pypi for sketch https://pypi.org/search/?q=sketch does not return the package, so we had thought the name was available. I have also reached out to the email of the user, and have received no response (and am still waiting/hoping to hear from @nikcub)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Here is the current project:
https://github.com/nikcub/Sketch

Here is the one I intend to publish in its place: https://github.com/approximatelabs/sketch

### Contact and additional research

I have sent two emails to the address referenced on @nikcub github profile (and as found on their personal website), and received no response. Additionally, this post (here) I am pinging the current owner and hoping for a response on github. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @bluecoconut, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
