### ISSUE TITLE
File Limit Request: Milvus - 300 MB

### ISSUE THREAD

**Issue by soothing-rain** [pypa/pypi-support#2133]
### Project URL

https://pypi.org/project/milvus/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Milvus is an open-source vector database built to power embedding similarity search and AI applications. Milvus makes unstructured data search more accessible, and provides a consistent user experience regardless of the deployment environment.

Milvus currently has 11.5k stars (https://github.com/milvus-io/milvus)

### Reasons for the request

Some Milvus wheels exceeded 100MB on some platforms, because of the ways we compile on different platforms.

Thanks! :)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @soothing-rain :wave:
Thanks for the information, I've set the upload limit for `milvus` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week
