### ISSUE TITLE
PEP 541 Request: trails

### ISSUE THREAD

**Issue by sphh** [pypa/pypi-support#2136]
### Project to be claimed

`trails`: https://pypi.org/project/trails

### Your PyPI username

`sph`: https://pypi.org/user/sph

### Reasons for the request

There  is not project named `trails`, but on June, 28th I asked admin@pypi.org, if it is possible to reserve that name.

When I now tried to upload the packages to PyPi, I get the following error:
```python3
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'sph' isn't allowed to upload to project 'trails'. See https://pypi.org/help/#project-name for more information.
```

### Source code repositories URLs

The project is based on https://codeberg.org/Trails/Trails

### Contact and additional research

There is no Python library with that name nor could I find a Linux command `trails`.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by sphh** [comment]
I was told by @di, that the name `trails` is already taken, but nothing has been uploaded and the project is probably abandoned.

Please consider transferring the name `trails` to the actively maintained project https://codeberg.org/Trails/Trails.

### Some background information

- The project `Trails` started as [`PyFlow`](https://github.com/wonderworks-software/PyFlow), but the maintainer [lost interest](https://github.com/wonderworks-software/PyFlow/issues/106).
- A [request](https://github.com/wonderworks-software/PyFlow/issues/112) to transfer maintainership (and name) was not replied to, hence the [`Trails` fork](https://codeberg.org/Trails/Trails) and the change of name.
- There already exists a project [`pyflow`](https://pypi.org/project/pyflow/) on PyPi, which is more recent but registered on PyPi, which `PyFlow` has never done (which is another reason to change name).

**Comment by yeraydiazdiaz** [comment]
Hi @sphh, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by sphh** [comment]
Hi @yeraydiazdiaz! Thanks for looking into this. Has the owner replied? What was his/her plans about his/her project?

**Comment by yeraydiazdiaz** [comment]
They did not, I have now transferred the project to you.

**Comment by sphh** [comment]
Many thanks for your help!
