### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MatthewJA** [pypa/pypi-support#2137]
### PyPI Username

dea-alger

### Reason for request

I've lost access to my account dea-alger, associated with matthew.alger@ga.gov.au. This email address no longer exists, so I can't do a password reset.

I'd like to either a) regain access or b) make any other maintainer of the dea-tools PyPI project an owner/admin, rather than just my inactive account.

Please let me know if I need to provide any extra info. Thanks in advance!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by BexDunn** [comment]
PyPI username: BexD
Maintainer on this repo. Commenting to support @MatthewJA [dea-alger](https://pypi.org/user/dea-alger/) 's request. 
Very happy to support @MatthewJA remaining as an admin with the project with another email account, and any or all other maintainers of the dea-tools pypi project : [dea-tools](https://pypi.org/project/dea-tools/ ) being added as admins/owners. 
Maintainers are currently [damien.ayers](https://github.com/omad) and myself

**Comment by ewdurbin** [comment]
Attempted to contact primary email address on the account to determine bounce status. In the mean time you can contact support@pypi.org referencing this issue to state the new email address you'd like associated with the account in order to proceed with recovery.

**Comment by BexDunn** [comment]
@ewdurbin thanks. I've emailed support@pypi.org stating the new email address in line with your advice above. Any problems please let us know! Thanks again :)

**Comment by ewdurbin** [comment]
Contacted via requested email address, please read the instructions and reply there to proceed with recovery.

**Comment by ewdurbin** [comment]
OK, the email address requested is already taken by another user. So while confirmed I cannot complete the action requested.

Options are to transfer the Owner role to one (or both) of the other existing maintainers or to transfer ownership to the user with that email address. Please let me know what works best.

**Comment by MatthewJA** [comment]
Can we do both? Transfer owner to other maintainers and add MatthewJA (the account associated with the requested email address).

**Comment by ewdurbin** [comment]
I've transferred ownership of the project to the MathewJA account. You may add the other maintainers as Owners at your discretion.

**Comment by BexDunn** [comment]
Thanks @ewdurbin
