### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mrbuche** [pypa/pypi-support#2141]
### PyPI Username

`mrbuche`

### Reason for request

Lost 2FA authentication app

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by mrbuche** [comment]
For more info: I got a new phone and was not able to transfer the 2FA app :(

**Comment by mrbuche** [comment]
@ewdurbin halp plz i beg of you

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mrbuche** [comment]
Responded to email

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by mrbuche** [comment]
THANK YOU
