### ISSUE TITLE
PEP 541 Request: bayesian-optimization

### ISSUE THREAD

**Issue by bwheelz36** [pypa/pypi-support#2144]
### Project to be claimed

`bayesian-optimization`: https://pypi.org/project/bayesian-optimization/

### Your PyPI username

`bwheelz36`: https://pypi.org/user/bwheelz36/

### Reasons for the request

The current package is quite out of date, to the point that it will not work with the latest version of scipy. The original author no longer has time to maintain this package.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/fmfn/BayesianOptimization

### Contact and additional research

I have sent several emails requesting access to the PyPi page. I have received some responses, for instance I am not a maintainer of the source code, but I have not received any responses to my last three emails requesting access to the PyPi project.
I have also logged an [issue on the code repository](https://github.com/fmfn/BayesianOptimization/issues/339) discussing how to handle new releases and maintenance. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @bwheelz36, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer. It seems the owner may be GitHub user @fmfn who seems to me active.

**Comment by bwheelz36** [comment]
Yep sounds good. I think fmfn is indeed active, but very busy - I did let him know via email that I would be making this request :-)

**Comment by bwheelz36** [comment]
Actually, another outcome I would be ok with is setting up a github action on the repository alongside a pypi publishing token - basically, my goal is just to keep the releases of the code up to date, I don't actually care how it happens

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
