### ISSUE TITLE
File Limit Request: XGBoost - 300 MB

### ISSUE THREAD

**Issue by RAMitchell** [pypa/pypi-support#2146]
### Project URL

https://github.com/dmlc/xgboost

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

XGBoost is a popular machine learning library active since 2015. 

### Reasons for the request

Shared libraries size is increased due to an expansion of GPU algorithms in xgboost, as well as compiling and supporting more recent cuda architectures. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @RAMitchell :wave:
I've set the upload limit for `XGBoost` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week!

**Comment by trivialfis** [comment]
Thank you!
