### ISSUE TITLE
File Limit Request: tensorflow-aarch64 - 250 MB

### ISSUE THREAD

**Issue by elfringham** [pypa/pypi-support#2149]
### Project URL

https://pypi.org/project/tensorflow-aarch64/

### Does this project already exist?

- [X] Yes

### New Limit

250MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The tensorflow-aarch64 project will be used to upload AARCH64 builds of TensorFlow.

### Reasons for the request

Previous releases have been the default build using Eigen. From 2.10 the AARCH64 build will be including support for the oneDNN backend with support from Arm Compute Library. This is resulting in the wheel files now exceeding the old 200MB file limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @elfringham :wave:
I've set the upload limit for `tensorflow-aarch64` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week.
