### ISSUE TITLE
Issue: Limit Request: intel-tensorflow - 250MB

### ISSUE THREAD

**Issue by chuanqi129** [pypa/pypi-support#215]
**Project**: intel-tensorflow

**Size of release**: 205M

**Which indexes**: both

**Reasons for the request**: intel-tensorflow is intel optimized tensorflow, which has better performance on intel platform. We'd like increase the limit to 250MB

**Comment by jamadden** [comment]
Hi! The limit is currently set at 150MB and the current uploaded wheels are about 130MB. Can you please let us know what causes the wheels to get 75MB larger?

**Comment by chuanqi129** [comment]
Hi @jamadden, thanks for your quickly reply. From date, the intel-TF last release is 1.15.0, not the 2.0.0. The size of 1.15.0 is 155MB, so the intel-tf 2.1 has increased 50MB. This change comes from new components added and manylinux support updated.

**Comment by jamadden** [comment]
The limit has been set to 250MB on both indexes. Please be mindful of the frequency of releases at that size.

**Comment by chuanqi129** [comment]
@jamadden Thank you very much! I can upload now.
