### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by henrikmelin** [pypa/pypi-support#2150]
### PyPI Username

hmelin

### Reason for request

Hi PyPi,

I got a new phone and the 2FA for PyPi seems to have disappeared, which means I cannot log in. I only have one project on here (h3ppy), which I need to update. I didn't generate the recovery codes, which now seems very foolish of me. 

Please advice on how to proceed!

Thanks,
Henrik Melin

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
