### ISSUE TITLE
Project Limit Request: tensorflow-aarch64 - 20 GB

### ISSUE THREAD

**Issue by elfringham** [pypa/pypi-support#2151]
### Project URL

https://pypi.org/project/tensorflow-aarch64/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The tensorflow-aarch64 project will be used to upload AARCH64 builds of TensorFlow.

### How large is each release?

820MB total. 4 wheels of ~205MB each. Would like to keep available v2.7.x, v2.8.x, v2.9.x and v2.10.x as that is what the project supports.

### How frequently do you make a release?

A new major release every 3 months, but previous major versions may also have point releases at that time as well.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @elfringham :wave: Thanks for the report.
I've set the project limit for `tensorflow-aarch64` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day.
