### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tr4cefl0w** [pypa/pypi-support#216]
Request for account recovery.

## PyPI Username
`tr4cefl0w`

##  Reason for request
  - Lost 2FA authentication app or security token

Reason:
Need to update my virustotal3 package but my phone died a couple months ago so I lost my 2FA.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
