### ISSUE TITLE
PEP 541 Request: pysolid

### ISSUE THREAD

**Issue by yunjunz** [pypa/pypi-support#2166]
### Project to be claimed

`pysolid`: https://pypi.org/project/pysolid

### Your PyPI username

`yunjunz`: https://pypi.org/user/yunjunz

### Reasons for the request

Hi PyPI support team,

The current PyPI project seems to be abandoned as:

+ There is no public email address associated with the owner or in the project documentation. Thus, I could not make contact with the owner.

+ The current project has not been updated since Aug 17, 2016.

+ No homepage is listed within the project. The linked URL from the project documentation to GitHub seems to be broken.

The project that I am developing under the same name is already available on the `conda-forge` channel (https://anaconda.org/conda-forge/pysolid) and Debian GNU/Linux OS (https://tracker.debian.org/pkg/pysolid), and has been actively downloaded and used by various users and developers (https://github.com/insarlab/PySolid/network/dependents).

I tried to use a different name such as `pytides` or `pytide`, but they are already been taken and used. I also find the name `pysolid` is a perfect name for my project: a python wrapper for solid Earth tides, not for ocean tides or pole tides!

While the current existing project is a fork of another project with a different name of `solidpython`, which is actively maintained both on GitHub and PyPI. Therefore, I would like to claim this name.

Sincerely,
Yunjun

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project code repository: https://github.com/plumps/pysolid
My intended project code repository: https://github.com/insarlab/pysolid

### Contact and additional research

The current project maintainer has a PyPI profile here (https://pypi.org/user/mb/) and a GitHub profile here (https://github.com/plumps/), but no public email address is found in these profiles or their owned public projects/repositories.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @yunjunz, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yunjunz** [comment]
> Hi @yunjunz, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

Great, thank you @yeraydiazdiaz .

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by yunjunz** [comment]
Thank you @yeraydiazdiaz!
