### ISSUE TITLE
Account recovery request (test.pypi.org)

### ISSUE THREAD

**Issue by tpalko** [pypa/pypi-support#2167]
### PyPI Username

`tpalko`

### Reason for request

Transferring authenticator to a new phone I managed to lose some accounts - test.pypi.org was one. I scoured my hard drive, email accounts, password manager, cannot find recovery codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
TestPyPI 2FA disabled and password reset issued.
