### ISSUE TITLE
File Limit Request: andisdk - 150 MB

### ISSUE THREAD

**Issue by sensokame** [pypa/pypi-support#2169]
### Project URL

https://pypi.org/project/andisdk/

### Does this project already exist?

- [X] Yes

### New Limit

150 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is originally a dotnet application with a pythonnet wrapper, this means that the project has multiple dll and executables being run from dotnet environment (both windows and linux)

Efforts made to reduce size
- remove xml and pdb files
- compressing executables with upx

### Reasons for the request

The package size has just hit the limit (current package size is 106MB) so it would be nice to extend the possible size. I requested 150MB in case in the future the size increases a little bit more, but it shouldn't exceed 150MB since the project is entering maintenance mode

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sensokame :wave: thanks for the report information.
I've set the upload limit for `andisdk` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day!
