### ISSUE TITLE
Limit increase: PYTROPD (100 MB, both PyPI and TestPyPI)

### ISSUE THREAD

**Issue by admg26** [pypa/pypi-support#217]
Hello,

I would like to include the validation data as part of the wheel and the total size (wheel and source tar ball) comes to 96MB. Could I possibly have 100MB please?

Cheers!

**Project**
Pytropd

https://test.pypi.org/project/pytropd/
https://pypi.org/project/pytropd/

**Size of release**
96MB

**Which indexes**
PyPI and Test PyPI

**Reasons for the request**
The project include some validation data and example scripts that plot the data provided. I do not expect the project to increase in size beyond 100MB

**Comment by pradyunsg** [comment]
Hi @admg26! Sorry for the delay -- PyPI is managed and maintained by volunteers so our availability to handle these requests is variable.

I've gone ahead and raised the limits for 'pytropd' to 100MB on PyPI and TestPyPI.
