### ISSUE TITLE
PEP 541 Request: pytest-env

### ISSUE THREAD

**Issue by gaborbernat** [pypa/pypi-support#2172]
### Project to be claimed

`pytest-env`: https://pypi.org/project/pytest-env

### Your PyPI username

`gaborbernat`: https://pypi.org/user/gaborbernat

### Reasons for the request

The original maintainer no longer maintains the project, so I would like to take over by forking the project and continue maintaining it under the pytest-dev org.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/MobileDynasty/pytest-env

### Contact and additional research

I've created an issue here https://github.com/MobileDynasty/pytest-env/issues/16 (in February). Contacted the person in e-mail without any response. Contacted them over linkedin where I managed to reach them and they were open to this, but then the communication dropped off:

![image](https://user-images.githubusercontent.com/690238/185759365-8c97e60b-118d-4357-8f14-10f2e7c7b7d8.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @gaborbernat, I will now start the reachability process for your request, hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
I understand but it's the process laid out in PEP 541, sometimes owners respond better to emails from moderators 🤞🏻

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.
