### ISSUE TITLE
Mass name squat by user: Collie

### ISSUE THREAD

**Issue by Shaloc** [pypa/pypi-support#2176]
### PyPI user performing the mass project name squatting

https://pypi.org/user/Collie

### Additional information

This user keeps submitting blank packages to PyPI, even includes name like `apps`, which makes import sorting tools like isort treat `apps` as a non-project package.
I think this user is abusing the service and packages like `apps` may better be removed from PyPI.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by marcelm** [comment]
See #791, #724

**Comment by di** [comment]
Invalid namesquatting packages have been removed.
