### ISSUE TITLE
PEP 541 Request: django-store

### ISSUE THREAD

**Issue by zeromage** [pypa/pypi-support#2179]
### Project to be claimed

`django-store`: https://pypi.org/project/django-store

### Your PyPI username

`USER_NAME`: https://pypi.org/user/zeromage

### Reasons for the request

project is name squatting (package has no functionality or is empty);

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The one i intend to publish:
https://git.docka.io/zeromage/django-store

### Contact and additional research

There was no contact information available.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @zeromage, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Seems the owner deleted the project and failed to notify me. In any case you should be able to upload your project now.
