### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Uninen** [pypa/pypi-support#218]
Request for account recovery.

## PyPI Username

`Uninen`

---

##  Reason for request

Reason:

  - Lost access to email address

Edit: the public email on my GH profile would be ok to use with the account. Thanks for your help and sorry for the trouble!

**Comment by ewdurbin** [comment]
Hello. As there are no projects associated with that User account on PyPI, I've updated the email address as directed and you can now complete a password reset to regain access to the username.
