### ISSUE TITLE
File Limit Request: sagemaker-pyspark - 200 MB

### ISSUE THREAD

**Issue by navinsoni** [pypa/pypi-support#2180]
### Project URL

https://pypi.org/project/sagemaker-pyspark/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This project supports pyspark on AWS SageMaker.

### Reasons for the request

This project uses hadoop-aws version 3.3.4 as dependency.
hadoop-aws has added compile time dependency on [aws-java-sdk-bundle](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bundle) version 1.11.901. Size of this dependency is 184 Mb. Hence the ask.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by navinsoni** [comment]
@alex @jezdez @pjenvey @berkerpeksag 
Can you please look into this. It’s a blocking issue for our release.

**Comment by alex** [comment]
I don't think any of the four of us have the ability to solve your problem, please don't ping random users.

**Comment by navinsoni** [comment]
@alex sorry about that. I thought you are owners of the repo.

**Comment by navinsoni** [comment]
@cmaureir
Can you please look into this. It’s a blocking issue for our release.

**Comment by cmaureir** [comment]
Hello @navinsoni :wave:
Thanks for the report. In the future, please avoid tagging people. Moderators visit the issues quite often, so usually you will get replies within a couple of days.
I've set the upload limit for `sagemaker-pyspark` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day

**Comment by navinsoni** [comment]
@cmaureir i am sorry for tagging for the issue. Will make sure this do not happen again. 

Thanks a lot for the approval
