### ISSUE TITLE
File Limit Request: wenetruntime - 500 MB

### ISSUE THREAD

**Issue by robin1001** [pypa/pypi-support#2181]
### Project URL

https://pypi.org/project/wenetruntime/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`wenet` is a popular end-to-end speech recognition project, please see https://github.com/wenet-e2e/wenet and `wenetruntime` is the corresponding python bingding wrapper for wenet c++ runtime. The runtime depends on LibTorch(c++ library of pytorch), which is much bigger than 100MB.

### Reasons for the request

`wenetruntime` depends on LibTorch(c++ library of pytorch), which is much bigger than 100MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @robin1001 :wave:
Thanks for the report. Can you share why asking for 500M? I see your comment that you mention libtorch is more than 100M, but then why 500M and not 200M for example? if you could explain more about that size it would be great.

**Comment by robin1001** [comment]
Libtorch varies from 100M+ to 300M+ according to the OS, with/without CUDA. And there is also other third party libraries in our project, I think 500M should be enough to cover all the cases.

**Comment by robin1001** [comment]
Hello, any update about the issue? It would be grateful if you give a quick feedback.

**Comment by cmaureir** [comment]
I've set the upload limit for `wenetruntime` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by robin1001** [comment]
Thanks!
