### ISSUE TITLE
File Limit Request: mxnet-cu113 - 600 MB

### ISSUE THREAD

**Issue by josephevans** [pypa/pypi-support#2182]
### Project URL

https://pypi.org/project/mxnet-cu113/

### Does this project already exist?

- [X] Yes

### New Limit

600 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Apache MXNet (incubating) is a deep learning framework that contains a lot of dependency libraries, which is why the wheels are so big.

We are requesting increases for new projects that use newer NVidia Cuda versions (we currently only publish up to 11.2, and want to start publishing releases for Cuda 11.3 through 11.7.)

### Reasons for the request

We do not anticipate the size increasing too much in the future.

If possible, can you also increase the limit for all the following projects below? If you would prefer separate tickets, please let me know and I can file them. The limit should be the same for all (600MB.) Thanks.

- mxnet-cu113 - https://pypi.org/project/mxnet-cu113/
- mxnet-cu114 - https://pypi.org/project/mxnet-cu114/
- mxnet-cu115 - https://pypi.org/project/mxnet-cu115/
- mxnet-cu116 - https://pypi.org/project/mxnet-cu116/
- mxnet-cu117 - https://pypi.org/project/mxnet-cu117/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @josephevans :wave: thanks for the report.
I'm wondering which efforts you have tried to reduce the wheel size. Could you maybe have a wheel with the C++ libraries dependencies? say `mxnet-cuXXX-depa, `mxnet-cuXXX-depb`, ... or maybe `mxnet-cuXXX-deps` ? not sure how much of the Python API you change on each release, but having separate projects per CUDA version seems to be a complicated approach.
Have you consider for people to download/install the dependencies instead of bundling them on the wheels?

**Comment by josephevans** [comment]
Hi @cmaureir, thanks for the suggestions. I should have been more clear on why our packages are so big. Although we do statically link some dependencies for portability (protobuf, opencv, etc) the bulk of the space consumed by the package is due to linking all the compiled GPU operators into our shared library. These operators must be compiled by the specific Cuda version for all GPU architectures that are supported.

We have considered creating packages specific for each GPU architecture which would reduce the size of each specific GPU architecture package, but that would require us maintaining many more packages (around 4-6 architectures per Cuda version).

**Comment by cmaureir** [comment]
Hey @josephevans :wave:
I've set the upload limit for `mxnet-cu113`, `mxnet-cu114`, `mxnet-cu115`, `mxnet-cu116`, `mxnet-cu117` to 600 MB on PyPI. Please be mindful of the frequency of releases at that size.
