### ISSUE TITLE
Project Limit Request: tiledb - 20 GB

### ISSUE THREAD

**Issue by nguyenv** [pypa/pypi-support#2183]
### Project URL

https://pypi.org/project/tiledb/

### Does this project already exist?

- [X] Yes

### New limit

20GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

https://github.com/TileDB-Inc/TileDB-Py

This project is the Python API for the [TileDB Storage Engine](https://github.com/TileDB-Inc/TileDB). It has been active for nearly 5 years.

We may have a small increase to the release sizes in the future when we begin to support PyPI wheels for arm64. 

To reduce the size of our project, we are also in progress working on disabling wheel builds for Python 3.6 for future releases and deleting wheels prior to 0.7.

### How large is each release?

~150M total.

These are the sizes of each wheel for our latest release. We have binary dependencies packaged into the wheels. All our releases contain these wheels and do not deviate much from the sizes listed below. 
```
total 153M
-rw-r--r-- 1 vivian vivian 9.3M Aug 25  2022 tiledb-0.17.2-cp310-cp310-macosx_10_15_x86_64.whl
-rw-r--r-- 1 vivian vivian  19M Aug 25  2022 tiledb-0.17.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-r--r-- 1 vivian vivian 4.3M Aug 25  2022 tiledb-0.17.2-cp310-cp310-win_amd64.whl
-rw-r--r-- 1 vivian vivian 9.1M Aug 25  2022 tiledb-0.17.2-cp36-cp36m-macosx_10_15_x86_64.whl
-rw-r--r-- 1 vivian vivian  18M Aug 25  2022 tiledb-0.17.2-cp36-cp36m-manylinux2010_x86_64.whl
-rw-r--r-- 1 vivian vivian 9.1M Aug 25  2022 tiledb-0.17.2-cp37-cp37m-macosx_10_15_x86_64.whl
-rw-r--r-- 1 vivian vivian  18M Aug 25  2022 tiledb-0.17.2-cp37-cp37m-manylinux2010_x86_64.whl
-rw-r--r-- 1 vivian vivian 4.3M Aug 25  2022 tiledb-0.17.2-cp37-cp37m-win_amd64.whl
-rw-r--r-- 1 vivian vivian 9.1M Aug 25  2022 tiledb-0.17.2-cp38-cp38-macosx_10_15_x86_64.whl
-rw-r--r-- 1 vivian vivian  19M Aug 25  2022 tiledb-0.17.2-cp38-cp38-manylinux2010_x86_64.whl
-rw-r--r-- 1 vivian vivian 4.3M Aug 25  2022 tiledb-0.17.2-cp38-cp38-win_amd64.whl
-rw-r--r-- 1 vivian vivian 9.1M Aug 25  2022 tiledb-0.17.2-cp39-cp39-macosx_10_15_x86_64.whl
-rw-r--r-- 1 vivian vivian  18M Aug 25  2022 tiledb-0.17.2-cp39-cp39-manylinux2010_x86_64.whl
-rw-r--r-- 1 vivian vivian 4.3M Aug 25  2022 tiledb-0.17.2-cp39-cp39-win_amd64.whl
-rw-r--r-- 1 vivian vivian 287K Aug 25  2022 tiledb-0.17.2.tar.gz
```

### How frequently do you make a release?

Roughly once a week or every other week.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @nguyenv :wave:
Thanks for the report. It seems that using Limited API in your project will certainly help you reduce considerably the amount of wheels and the size of each release. Check this out https://docs.python.org/3/c-api/stable.html
I've set the project limit for `tiledb` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice day

**Comment by nguyenv** [comment]
Thank you very much for the quick response and limit increase, @cmaureir

> It seems that using Limited API in your project will certainly help you reduce considerably the amount of wheels and the size of each release.

We use PyBind11 which [doesn't support the limited API](https://github.com/pybind/pybind11/issues/1755). However, we are looking forward to if/when HPy (or something like it) is usable and supported. In the meantime we are brainstorming other approaches to reduce the rate of growth and will implement ASAP. Thanks again!

**Comment by cmaureir** [comment]
**Disclaimer**: _The following is my opinion only, and a comment on a project I'm currently a maintainer, which is not associated with PyPa or any other moderator._


I understand, that's one of the reasons that even if pybind11 is quite easy to get started, I still prefer [Shiboken](https://www.youtube.com/watch?v=wOMlDutOWXI) to follow that approach, which is the binding generator used in the [Qt for Python](https://doc.qt.io/qtforpython/) project, which I'm one of the maintainers. Of course, migrating the binding generator is not optimal, and not even worth it, but just wanted to mention that there are other options that does support it for C++ bindings.
