### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tjensen** [pypa/pypi-support#2185]
### PyPI Username

`tjensen`

### Reason for request

I lost access to the 2FA application I was using when my phone stopped working. I do not seem to have any recovery codes stored anywhere.

I still have access to my email address and I can verify my identity via GitHub, if necessary.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
