### ISSUE TITLE
PEP 541 Request: pystack

### ISSUE THREAD

**Issue by mariocj89** [pypa/pypi-support#2187]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pystack

### Your PyPI username

`USER_NAME`: https://pypi.org/user/mariocj89

### Reasons for the request

I've spoken with the current owner and he agreed to pass us the name. He has already deleted the existing package but I am unable to publish a new version:

```
INFO     Response from https://upload.pypi.org/legacy/:
         400 The name 'pystack' is too similar to an existing project. See https://pypi.org/help/#project-name for more
         information.
INFO     <html>
          <head>
           <title>400 The name 'pystack' is too similar to an existing project. See https://pypi.org/help/#project-name
         for more information.</title>
          </head>
          <body>
           <h1>400 The name 'pystack' is too similar to an existing project. See https://pypi.org/help/#project-name for
         more information.</h1>
           The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
         The name &#x27;pystack&#x27; is too similar to an existing project. See https://pypi.org/help/#project-name for
         more information.


          </body>
         </html>
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'pystack' is too similar to an existing project. See https://pypi.org/help/#project-name for more
         information.
```

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Old repo: https://github.com/RobinDavid/pystack

The new repo is still to be published, we wanted to block the name ASAP.

### Contact and additional research

I've spoken with the existing owner already, (Robin ) who agreed to delete the repository and pass the name to us.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Transfer complete. The original project was deleted by the old maintainer, but was being blocked from re-reg due to ultranormalization.
