### ISSUE TITLE
PEP 541 Request: pyquest (Name isn't allowed)

### ISSUE THREAD

**Issue by rrmeister** [pypa/pypi-support#2188]
### Project to be claimed

`pyquest`: https://pypi.org/project/pyquest

### Your PyPI username

`rmeister`: https://pypi.org/user/rmeister/

### Reasons for the request

Our research group has a quantum computing simulation project named QuEST, for which I am writing a Python interface, which we named `pyquest`. Attempting to upload our project to PyPI results in `The name 'pyquest' isn't allowed.`

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'pyquest' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

I would like to understand why this name is reserved/prohibited, and wheter it would be possible to release this name as it would closely represent our project.

### Source code repositories URLs

https://github.com/rrmeister/pyQuEST

All work so far in the develop branch.

### Contact and additional research

I could not find any project named `pyquest`. There is `pyquest-cffi` which we specifically requested not to be named `pyquest` as at the time we were still debating implementing a wrapper ourselves, which has now happened.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @rrmeister, the reason it is not allowed is because it was placed in the prohibited project names list. An @pypa/warehouse-admins should be able to release the name to you.

**Comment by ewdurbin** [comment]
Project released to [rmeister](https://pypi.org/user/rmeister/)
