### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jbrobertson** [pypa/pypi-support#219]
Request for account recovery.

## PyPI Username

`jbrobertson`

---

##  Reason for request

Reason:

I lost access to my e-mail address when berlios.de closed their open source hosting activities.
Note that the setup.py files in the project at https://pypi.org/project/Swish-E/ points to a web page with my contact details (http://jibe.freeshell.org/bits/SwishE), which should help validate this request.

Thanks a lot for your time.
Kind regards
Jean

**Comment by ewdurbin** [comment]
Hello @jbrobertson, I do not see an @berlios.de email address associated with that user account. I've emailed the address currently associated with the account.

**Comment by jbrobertson** [comment]
Hello,

thank you for your response.  

jbrobertson@users.berlios.de is shown on https://pypi.org/project/Swish-E/ under meta / author -- that is a project I submitted with this account.  If that's not the e-mail associated with the account, then I do not know what address I used at the time.

Would it be possible to reset that e-mail to jibe (at) freeshell.org?

Thanks!

**Comment by ewdurbin** [comment]
The email address associated with your account has been updated and a password reset initiated.

Please complete that password reset to regain access to your account.
