### ISSUE TITLE
Project Limit Request: AWS CRT - 30 GB

### ISSUE THREAD

**Issue by DmitriyMusatkin** [pypa/pypi-support#2190]
### Project URL

https://pypi.org/project/awscrt

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

AWS CRT is a set of foundational components for communicating with AWS services. AWS Python SDK and CLI depend on it, and anyone could use to build custom sdks. 

### How large is each release?

~200mb

we provide wheels for the following configurations for several latest cpython versions (cp310, cp39, cp38, cp37, cp35 on latest release):
- manylinux aarch64, x86_64, i686
- macos universal and x86_64
- win 32 and amd64

### How frequently do you make a release?

about once a month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @DmitriyMusatkin :wave:
I've set the project limit for `awscrt` to 30 GB on PyPI and TestPyPI. Please be mindful of the frequency of releases, maybe another idea could be for you to use the [Limited API](https://docs.python.org/3/c-api/stable.html) so you get one wheel per architecture, helping reducing the amount of wheels and the overall project size.
Have a nice week!

**Comment by TingDaoK** [comment]
Hi @cmaureir 

We actually considered about using the limited API, but we worried about the performance impact it might have to our lib (We haven't dig into it yet). Do you know how it will affect the performance?
