### ISSUE TITLE
PEP 541 Request: discord4py

### ISSUE THREAD

**Issue by mccoderpy** [pypa/pypi-support#2192]
### Project to be claimed

`discord4py`: https://pypi.org/project/discord4py

### Your PyPI username

`mccoder.py`: https://pypi.org/user/mccoder.py

### Reasons for the request

As the latest release and the only releases of the project (wich is a outdated fork of the project `discord.py` with no changes from the original and just pointing to the actual  `discord.py` project) where on  `Aug 28, 2021` and the owner stated a few hours after uploading the project that he will move to use an other API-wrapper for discord bots instead _**the project seems to bee abandoned**_.

[![image](https://user-images.githubusercontent.com/80390413/187251589-5d82cd73-f496-4d40-9b59-0cc01f3a1bc6.png)](https://github.com/palmtrww69/palmtrww69/blob/main/README.md#quick-announcement)

Since I started my project `discord.py-message-components` before all this happens as a standalone API-Wrapper and work on it now for a long time, I decided it needs a rename within the next stable release as the current one sounds like an extension. So I made a poll for a new name in my community and the result was `discord4py`.

Now I just realised that this project name is already taken on PyPi by a dead fork of a project and _**want to ask for the rights to publish my package under this name.**_

### Maintenance or replacement?

Replacement

### Source code repositories URLs

- The current project seems to rely on this fork: https://github.com/palmtrww69/discord.py

- The project I want to publish in its place is: https://github.com/mccoderpy/discord.py-message-components (the developer-branch is planed to move to a stable release within a rename)

### Contact and additional research

1. As there is no email listed in the project or the owners profile I tried to find a way to contact him via. his GitHub profile (The link to it was in a hyperlink of the project description)

2. Sadly there wasn't any contact information too.

3. So I tried to find him on [Discord](https://discord.com) but all users I found with a name mostly similar to his one are offline and have never send a message in any mutual server.

4. I send them a privat message to ask if they own the GitHub account, but no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mccoderpy** [comment]
Any updates to this?
I'm waiting for a response nearly a month now and looking in [projects](https://github.com/pypa/pypi-support/projects/1) I see even other requests has been reviewed in the time 🥲

**Comment by yeraydiazdiaz** [comment]
Hi @mccoderpy, I will now start the reachability process for you request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by mccoderpy** [comment]
> Transfer complete.

Thank you very much ❤️
