### ISSUE TITLE
PEP 541 Request: pydhan

### ISSUE THREAD

**Issue by dhan-oss** [pypa/pypi-support#2194]
### Project to be claimed

`pydhan`: https://pypi.org/project/pydhan

### Your PyPI username

`dhan-oss`: https://pypi.org/user/dhan-oss

### Reasons for the request

I can't name my package pydhan as I believe it was abandoned and deleted from Pypi server.
Also any project with same name is not there on Pypi server.
I can't find the package or project with same name on Pypi website but when I try to upload my package with name pydhan it says:
"HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/ The user 'dhan-oss' isn't allowed to upload to project 'pydhan'. See https://pypi.org/help/#project-name for more information."

### Maintenance or replacement?

Replacement

### Source code repositories URLs

NA

### Contact and additional research

NA

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @dhan-oss, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
