### ISSUE TITLE
PEP 541 Request: pie

### ISSUE THREAD

**Issue by alexanderdavidj** [pypa/pypi-support#2195]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pie

### Your PyPI username

`USER_NAME`: https://pypi.org/user/alexanderdavid

### Reasons for the request

The project has not been active since March 25. 2020

Looking through the issues, on May 13. 2021 a user called [prashanth-up](https://github.com/prashanth-up) opened an [issue](https://github.com/pypa/pypi-support/issues/381) requested the name transfer and the transfer was confirmed on April 14, 2021.
While the transfer was confirmed, the user does not have any repository called pie on their GitHub profile nor did the pie-0.6 project on PyPi update at all since then.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The code for my repository can be found [here](https://github.com/alexzerozeroone/pie)
The code for the [current](https://pypi.org/project/pie/0.6/) project can be found [here](https://github.com/Siegallab/PIE)

### Contact and additional research

I understood that the owner could not be contacted in the original issue for the name transfer as the 6 weeks passed at that time.
I've done some research and one of the current maintainer's username [(Siegallab)](https://pypi.org/user/SiegalLab/) matches up with a [GitHub profile](https://github.com/Siegallab) called Siegallab which has the project [PIE](https://github.com/Siegallab/PIE) with the last commit on June 23, 2021.

The install command for that project is 
```bash
python -m pip install git+https://github.com/Siegallab/PIE@v1.0.1
```
which by looking at the ``git+https://github.com/Siegallab/PIE@v1.0.1`` part means that the maintainer did not use the PyPi project page, even 7 years (2014 latest on PyPi, 2021 latest on GitHub) after the last release on PyPi. I believe this to mean the PyPi project page (the GitHub too, while at it) has been abandoned.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by alexanderdavidj** [comment]
> Hi @alexanderdavidj, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

Thank you, I'm looking forward to it.

**Comment by yeraydiazdiaz** [comment]
The owner replied stating they had a project ready for release and is now published. Closing as no transfer is possible since the project is in active development.
