### ISSUE TITLE
Account recovery request on pypi.test

### ISSUE THREAD

**Issue by bsrdjan** [pypa/pypi-support#2198]
### PyPI Username

bsrdjan

### Reason for request

Lost 2FA authentication app or security token, no recovery codes, please help recover pypi.test account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by bsrdjan** [comment]
Hello, any update on when this request might be processed?

**Comment by ewdurbin** [comment]
2FA disabled and password reset issued on TestPyPI
