### ISSUE TITLE
File Limit Request: lightseq - 300 MB

### ISSUE THREAD

**Issue by Taka152** [pypa/pypi-support#2203]
### Project URL

https://pypi.org/project/lightseq/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

[Our project](https://github.com/bytedance/lightseq) is for deep learning GPU acceleration which depends on Nvidia cuda toolkit.  This project is active on GitHub for about 3 years and has 2.3k stars.

we provide a .so file in this project which is the core of our projects.  when built with CUDA 10, the wheels are just 40+MB， but our new feature in the next release requires CUDA 11 which makes the wheels grow to 200+MB. 

We try our best to reduce the size of the releases but we want to provide an easy installation for users without caring about which cuda version should they install, so the CUDA depend can't be just removed or dynamically linked to reduce the size of the binary.

### Reasons for the request

Our new releases are about 280+MB, which exceeds the current limit of 100MB. it would be appreciated if the limit could be increased to 300MB.

Anyway, thanks for providing such a great platform, it helps a lot for python and the community.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Taka152** [comment]
@cmaureir Hi, it would be appreciated if you could help me with this file limit issue.

**Comment by Taka152** [comment]
I modified the limit to the least size we need.

**Comment by cmaureir** [comment]
Hey @Taka152 :wave:
Sorry I was away for some time, but I have just set the upload limit for `lightseq` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
have a nice week :)
