### ISSUE TITLE
PEP 541 Request: retrying

### ISSUE THREAD

**Issue by groodt** [pypa/pypi-support#2205]
### Project to be claimed

`retrying`: https://pypi.org/project/retrying/

### Your PyPI username

`groodt`: https://pypi.org/user/groodt/

### Reasons for the request

I believe the project has been abandoned:

* Last PyPI release Dec 15, 2004 https://pypi.org/project/retrying/#history
* Activity on the GitHub repo indicates the package is unmaintained https://github.com/rholder/retrying/issues/65
* I emailed the single listed maintainer on 20 June, but no reply (email didn't bounce)

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Existing: https://github.com/rholder/retrying
New: https://github.com/groodt/retrying

### Contact and additional research

* I've tried to connect on LinkedIn
* I've tried to comment on the existing repository and have not had a reply

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @groodt, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
