### ISSUE TITLE
PEP 541 Request: trill

### ISSUE THREAD

**Issue by gregersn** [pypa/pypi-support#2206]
### Project to be claimed

`trill`: https://pypi.org/project/trill

### Your PyPI username

`gregersn`: https://pypi.org/user/gregersn

### Reasons for the request

I can not find any project from before named "trill", also, it worked when I tried it with the test site first, so I figured it would not be a blocked or reserved name. ( https://test.pypi.org/project/trill/ )

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Source code for my project: https://github.com/gregersn/Trill/

### Contact and additional research

I have not find a project earlier, that is named "trill"

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @gregersn, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before moving forward with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
