### ISSUE TITLE
PEP 541 Request: Cobbler

### ISSUE THREAD

**Issue by SchoolGuy** [pypa/pypi-support#221]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/Cobbler/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/SchoolGuy/

**Reasons for the request**

The project is currently maintained on Github by myself. The old Pypi Account of @mpdehaan is not reachable anymore because the E-Mail address used for this account is not accessible anymore.

**Maintenance or replacement?**

Maintenance --> https://github.com/cobbler/cobbler

**Contact and additional research**

@mpdehaan is in E-Mail contact with me and has welcomed the transfer to my account.

**Comment by yeraydiazdiaz** [comment]
Hi @SchoolGuy, we'd need confirmation from @mpdehaan to proceed with the transfer, replying to this issue would be enough.

Alternatively he could open an [account recovery issue](https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.md&title=Account+recovery+request) to regain access and perform the transfer himself.

**Comment by mpdehaan** [comment]
Hi @yeraydiazdiaz, I've spoken with @SchoolGuy on video chat and am good with this transfer.

Thanks for helping with pypi.

**Comment by yeraydiazdiaz** [comment]
Hi @mpdehaan, thanks for replying. Are you able to complete the transfer yourself? We'd appreciate it to reduce the pressure on the admins.

To do so:

1. Log into PyPI
2. Navigate to https://pypi.org/manage/project/Cobbler/collaboration/
3. Add `SchoolGuy` as an Owner

**Comment by SchoolGuy** [comment]
@yeraydiazdiaz Like I wrote in my initial request he is not able to do that as this account was setup with an email he is not able to access anymore.

**Comment by yeraydiazdiaz** [comment]
Right, I'll ask an admin to perform the transfer then.

@mpdehaan if you're interested in regaining access to your PyPI account please open an [account revcovery issue](https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.md&title=Account+recovery+request).

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by SchoolGuy** [comment]
Thanks @ewdurbin & @yeraydiazdiaz
