### ISSUE TITLE
PEP 541 Request: Datumaro

### ISSUE THREAD

**Issue by chuneuny-emily** [pypa/pypi-support#2213]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/datumaro

### Your PyPI username

`USER_NAME`: https://pypi.org/user/chuneuny

### Reasons for the request

Datumaro project is one of open source projects in openvinotoolkit, which is developed and managed by Intel.
The previous owner of Datumaro project was [zhiltsov-max](https://github.com/openvinotoolkit/datumaro/issues?q=is%3Apr+is%3Aopen+author%3Azhiltsov-max). And he is not in the Intel company anymore.
Now I’m in charge of Datumaro project, and trying to release hotfix release r0.3.1. But I cannot upload it due to access denied issue. Can you remove mzhiltso ([zhiltsov-max](https://github.com/openvinotoolkit/datumaro/issues?q=is%3Apr+is%3Aopen+author%3Azhiltsov-max)) and add me in maintainer of Datumaro project ASAP?

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/openvinotoolkit/datumaro

### Contact and additional research

I don't have the previous owner(Maxim) contact. I just left the request at https://github.com/openvinotoolkit/datumaro/issues/729.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @chuneuny-emily, it seems you are already and owner of `datumaro`, you should be able to remove `mzhiltso` from the project yourself in https://pypi.org/manage/project/datumaro/collaboration/.
