### ISSUE TITLE
PEP 541 Request: async-sendgrid

### ISSUE THREAD

**Issue by Actticus** [pypa/pypi-support#2216]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/async-sendgrid

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nullinside

### Reasons for the request

I deleted a project to fix one problem and not to change the version, but it was a mistake because I cannot create a new project with the same name (name of the deleted project).

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/sensodevices/async-sendgrid

### Contact and additional research

I am the owner

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi, please see here: https://pypi.org/help/#file-name-reuse. You can reclaim the project name by publishing a release with a version that you hadn't previously used.
