### ISSUE TITLE
Unable change PyPI Username

### ISSUE THREAD

**Issue by jnsougata** [pypa/pypi-support#2219]
### PyPI Username

Gyrooo

### Reason for request

I am unable to change my username. There's no option I can find.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Please see: https://pypi.org/help/#username-change
