### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by michaelosthege** [pypa/pypi-support#222]
Request for account recovery.

## PyPI Username

`id.mosthege.net`

---

##  Reason for request

When I created my PyPI account, I used OpenID that I had set up on my server. Now, years later, I want to log in and it looks like the OpenID login was discontinued. Unfortunately I must have missed warnings for some reason, so now I can not log in.

Can you help me to recover the account?

**Comment by ewdurbin** [comment]
Hello @michaelosthege, it appears that there is a hotmail.com address associated with the account that recent password reset requests have been successfully delivered to.

If you're unable to access that account, we can take further steps to help you recover your account.

**Comment by michaelosthege** [comment]
Hi @ewdurbin, thank your for the quick response.
I double-checked the account and found the reset request emails.
I have now restored access. Thanks.
