### ISSUE TITLE
PEP 541 Request: icw

### ISSUE THREAD

**Issue by n8henrie** [pypa/pypi-support#2220]
### Project to be claimed

icw

### Your PyPI username

`n8henrie`: https://pypi.org/user/n8henrie

### Reasons for the request

I've been developing a project called `icw` (for `ics converter webapp`) for several years, during which it's been available on GitHub. I finally decided to publish it to PyPI but got a "name too similar" error. It doesn't seem to be an existing project.

The only obvious name conflict I see is https://pypi.org/project/icw-lib/ which hasn't seen activity in years and links to a non-existing repo at https://github.com/Haneawa/icw-lib

I have a dozen other projects, I have 2FA enabled, this is not an attempt at name squatting.

I didn't see an issue template for this exact problem, I hope it's okay that I picked the next closest one.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

[github.com/n8henrie/icw](https://github.com/n8henrie/icw)

### Contact and additional research

I searched for existing projects with `icw` in their name.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @n8henrie, I believe the clash is with https://pypi.org/project/lcw/

3 letter project names usually collide with existing projects in one way or another, I suggest finding a new name for your project.

**Comment by n8henrie** [comment]
Ah, thanks for pointing that out.

I can see how L vs i could be confused, though a little frustrating that this project with no releases in 7 years, no source code available that I can tell, and a 404 homepage <https://dada.pink/lcw/> ... is blocking me for what I presume are concerns regarding typo squatting.

I'll just keep the project off PyPI. Thanks for your time and attention anyway.
