### ISSUE TITLE
PEP 541 Request: python-Levenshtein

### ISSUE THREAD

**Issue by maxbachmann** [pypa/pypi-support#2222]
### Project to be claimed

`python-Levenshtein`: https://pypi.org/project/python-Levenshtein

### Your PyPI username

`maxbachmann`: https://pypi.org/user/maxbachmann

### Reasons for the request

The project did not see a release in the last 1.5 years and the author asks for a new maintainer for the project. I am already maintaining a fork of the project [here](https://github.com/maxbachmann/Levenshtein). The fork fixes most issues of the project, with the most important one being the large use of legacy string APIs which will be removed in Python 3.12. There is already a discussion on handing over maintenance of the project on the projects issue tracker: https://github.com/ztane/python-Levenshtein/issues/61 where the current maintainer stated that he would be willing to hand over the maintainer role on Pypi to me: https://github.com/ztane/python-Levenshtein/issues/61#issuecomment-899264097. However I failed to reach @ztane afterwards both on the issue tracker and via e-mail.

I hope this issue brings this back to @ztane's attention, so he can decide how to move forward with the project.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/ztane/python-Levenshtein

### Contact and additional research

I talked to @ztane in the following issue: https://github.com/ztane/python-Levenshtein/issues/61. I wrote an e-mail both to @ztane and the old maintainer @miohtama. Mikko was able to reach Antti Haapala, but he never got back to me.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @maxbachmann, I will now start the reachability process which can take up to 6 weeks. Ideally @ztane or one of the other owners can confirm in this issue if they agree with the transfer, regardless I will try to contact them myself.

**Comment by dorianj** [comment]
I looked at the fork and the changes appear positive. I've added Max as a maintainer on the project. Please reach out to me if you need any other help.

**Comment by maxbachmann** [comment]
Thank you for the quick help @dorianj
