### ISSUE TITLE
Project Limit Request: rapidfuzz - 20 GB

### ISSUE THREAD

**Issue by maxbachmann** [pypa/pypi-support#2223]
### Project URL

https://pypi.org/project/rapidfuzz/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project implements optimized versions of common metrics used to compare strings. It has been active for 2.5 years.

### How large is each release?

The current size is around 200mb per release. The wheels have a size between 1 and 4mb depending on the platform, but at this point it builds around 100 wheels per release, which is still quite large.

Things I considered to reduce binary size:
- use only stable ABI -> I use non stable unicode API's like PyUnicode_DATA. Creating a copy of the string would hurt performance quite a bit.
- combining multiple modules, since they include some duplicated sections. This should save some space and will likely be done starting one of the next releases

### How frequently do you make a release?

around once per week

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by maxbachmann** [comment]
> combining multiple modules, since they include some duplicated sections. This should save some space and will likely be done starting one of the next releases

I implemented this for part of the modules which reduces the release size to 155 mb.

**Comment by cmaureir** [comment]
Hey there :wave:
I've set the project limit for `rapidfuzz` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week :)
