### ISSUE TITLE
PEP 541 Request: bbq

### ISSUE THREAD

**Issue by agaier** [pypa/pypi-support#2227]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/bbq

### Your PyPI username

`USER_NAME`: https://pypi.org/user/agaier

### Reasons for the request

Project has been abandoned

- Project with no code except setup.py, last commit more than 10 years ago
- Contacted owners via email and github issue 9 months ago, no response.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/agaier/bbq

### Contact and additional research

- Contacted owners via email and github issue 9 months ago, no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @agaier, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the request.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
