### ISSUE TITLE
PEP 541 Request: bpy

### ISSUE THREAD

**Issue by TylerGubala** [pypa/pypi-support#2231]
### Project to be claimed

`bpy`: https://pypi.org/project/bpy

### Your PyPI username

`TylerGubala`: https://pypi.org/user/TylerGubala

### Reasons for the request

I received a request from Blender Foundation to transfer ownership of `bpy` in email format.

I assume a user is going to follow up here. Not sure on if there will be maintenance. I think it will be a direct replacement.

### Source code repositories URLs

My current repo:

https://github.com/TylerGubala/blenderpy

Replacement repo by Blender Foundation:

https://git.blender.org/gitweb/gitweb.cgi/blender.git

### Contact and additional research

I am the current owner and was contacted by the Blender Foundation team. Attached is my corroboration with BF member(s).

[Gmail - Blender as a Python Module (official support).pdf](https://github.com/pypa/pypi-support/files/9569721/Gmail.-.Blender.as.a.Python.Module.official.support.pdf)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I'm closing this issue for housekeeping until the intended new owner is defined.

**Comment by ideasman42** [comment]
@TylerGubala can you confirm passing ownership to my work email: `campbell[at]blender.org` is acceptable?

**Comment by ideasman42** [comment]
@yeraydiazdiaz Hi, I wasn't involved in writing the message but we have created a user account

`BlenderFoundation` on https://pypi.org (using a `blender.org` email), I'm not sure if there is anything else we can do, besides double checking @TylerGubala is fine to assign ownership to an account managed by blender.org developers.

**Comment by TylerGubala** [comment]
Please transfer ownership to `BlenderFoundation` @yeraydiazdiaz 

Thanks in advance!

**Comment by yeraydiazdiaz** [comment]
I've added `BlenderFoundation` as an owner of project `bpy`.
