### ISSUE TITLE
PEP 541 Request: pycryptosat

### ISSUE THREAD

**Issue by msoos** [pypa/pypi-support#2233]
### Project to be claimed

`pycryptosat`: https://test.pypi.org/project/pycryptosat

### Your PyPI username

`msoos-test`: https://test.pypi.org/user/msoos-test

### Reasons for the request

Hi,

[ NOTE: I already got access to the non-test `pycryptosat` package here: #1318 This is a similar request, **but this time the user is `msoos-test` in test.pypi.org** instead of `msoos` in production test.pyp.org, since `msoos` was already taken in test.pypi.org ]

I am Mate Soos, the author of [CryptoMiniSat](https://github.com/msoos/cryptominisat), as per my GitHub profile, and as per how the original PyPi maintainer put together the [pycryptosat PyPi project](https://pypi.org/project/pycryptosat/). Check out the homepage (www.msoos.org), the Maintainer (clearly set to me), etc. The "pycryptosat" is the python module that packages CryptoMiniSat for python.

The issue is, the version on PyPi very outdated. I tried reaching out the maintainer, but I couldn't get any response. There is no official email address listed for her/him, so I tried searching around. I sent a few emails to what I would guess to be her/his email, but no response. I'd like to get control over the **test** PyPi project -- I already got access to the non-test PyPi project. I believe I would be in a good position to maintain this project (I am trying to update it right now, but I can't test). Furthermore, I'd like to release some research projects in the long term (I work in academia sometimes), and having control over pycryptosat would be invaluable for this.

Would it be possible to give me the project? Thanks so much in advance,

Mate

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

github.com/msoos/cryptominisat

### Contact and additional research

I have sent 3 emails to what I believe to be Pierre Vignet, working at IRISA (pierre.vignet@irisa.fr), the current maintainer (see INRISA webpage: https://www-dyliss.irisa.fr/team-members/, a bioinformatics team), back in 2019.. Two in February with a 10 day delay, and one in May of the same year. I did not get a response. I strongly believe pierrev to be Pierre Vignet, I even put him on the authors of [pycryptosat.cpp.in](https://github.com/msoos/cryptominisat/blob/master/python/src/pycryptosat.cpp.in): `(2017, Pierre Vignet)`. He also maintains the https://pypi.org/project/cadbiom-cmd/ and other `cadbiom`-related packages, with is for `Computer Aided Design of Biological Models`. So that matches up with the bioinformatics team above.

![image](https://user-images.githubusercontent.com/1334841/190510786-82aa09b2-288b-48c5-b9e4-2f4b2bd866ab.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @msoos, I've transferred the project to you as owners of the PyPI project have automatic ownership of the Test PyPI project if requested.

**Comment by msoos** [comment]
Many thanks! :heart: 

Mate
