### ISSUE TITLE
File Limit Request: fbgemm-gpu - 300 MB

### ISSUE THREAD

**Issue by mjanderson09** [pypa/pypi-support#2237]
### Project URL

https://pypi.org/project/fbgemm-gpu/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

FBGEMM_GPU (FBGEMM GPU kernel library) is a collection of high-performance CUDA GPU operator library for GPU training and inference. It has been active since December 2020 (almost 2 years).

### Reasons for the request

We've limited the binary size in the past by compiling for only two CUDA architectures (7.0 and 8.0). As we've gradually added more features and optimizations the binary has continued to grow past the 200 MB limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello :wave:
thanks for the report, I've set the upload limit for `fbgemm-gpu` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
