### ISSUE TITLE
Project Limit Request: MOSEK - 25 GB

### ISSUE THREAD

**Issue by aszekMosek** [pypa/pypi-support#2240]
### Project URL

https://pypi.org/project/Mosek/

### Does this project already exist?

- [X] Yes

### New limit

25

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

MOSEK is a package for large-scale convex optimization, including linear programming, second-order cone optimization, SDP and mixed-integer variants.

The project on pypi is active since February 2020. MOSEK as a product has 20+ years history.

### How large is each release?

The package consists of Python code and native binaries. An average size of a package is 10MB.

We now release for 5 platforms (Win64, Linux64, LinuxARM, Osx64, OsxARM), each with 3-4 python versions (starting from Python 3.7 or 3.8 towards 3.10), which gives almost 20 packages per release.

Altogether around 200MB of space per release.

### How frequently do you make a release?

On average twice a month. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @aszekMosek :wave:
Thanks for the detailed issue. Have you consider the usage of the [Limited API](https://docs.python.org/3/c-api/stable.html)? it really looks like a nice approach to solve your issue of having 3-4 different wheels (per python version) and having only 1 per platform, reducing your 20 packages to only 5.
Would that work for you?

**Comment by ulfworsoe** [comment]
Hi,
Unfortunately we may have to build per-Python-version wheels for a while yet. We rely on the `Py_buffer` API, which is not included in the Limited API until 3.11.

**Comment by di** [comment]
I've increased the limit for `Mosek` to 25GB.
