### ISSUE TITLE
PEP 541 Request: rai

### ISSUE THREAD

**Issue by SimonBiggs** [pypa/pypi-support#2244]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/rai

### Your PyPI username

`USER_NAME`: https://pypi.org/user/SimonBiggs

### Reasons for the request

The project has been abandoned. The source repository has been archived on GitHub:

https://github.com/kennell/rai

The name of the project `rai` refers to the now deprecated name of the nano cryptocurrency:

https://en.wikipedia.org/wiki/Nano_(cryptocurrency)#Rebrand_to_Nano

The name rebranding occurred in 2018.

The most recent release of rai was in 2018:

https://pypi.org/project/rai/

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current abandoned project: https://github.com/kennell/rai

Project which I intend to publish in its place: https://github.com/RadiotherapyAI/rai/tree/bbe871d

### Contact and additional research

I initially reached out to Kevin, the listed maintainer, on the 12th September with the following email:

> Hi Kevin,
> 
> I am making an open source medical device to help cancer treatments. I was hoping to be able to utilise the `rai` package name (short for Radiotherapy AI) on PyPI. Would you be open to having your package name be repurposed for that?
> 
> Kind regards,
> Simon

But I received no response.

I followed up with an attempt to reach one of the other contributors on the GitHub repo, Colin, with the following email on the 21st September:

> Hi Colin,
> 
> I noticed that you have contributed in the past to the [rai package](https://github.com/kennell/rai). Given it looks like the project is now archived, I was hoping to be able to utilise the `rai` PyPI name for a library I am building to help researchers in cancer treatment:
> 
> https://github.com/RadiotherapyAI/rai
> 
> I tried reaching out to Kevin (see email below) but couldn't get through. Do you know how to contact Kevin? Or, do you happen to have the required permissions to be able to transfer the rai package on PyPI?
> 
> Thank you, so very much.
> 
> Cheers,
> Simon

No response yet, but it was only recently sent.

I also attempted to reach out to Kevin via LinkedIn. No success as of yet.

---

Thank you for your time, and for considering this name change application.

Cheers,
Simon

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by SimonBiggs** [comment]
Some follow up, after submitting this issue both Colin and Kevin did get back to me. Colin wasn't able to help and Kevin asked for me to detail why it is that I wanted the transfer. I sent the following in response. (Not copying in his email as I haven't received his permission to do so).

Here was my response (I edited the email slightly using square brackets, to make it make a little more sense):

> Hi Kevin,
> 
> Thank you for getting back to me. It's the package name length which is mostly the issue. `radiotherapyai` is quite a bit too large for a top level package name, for pip installing, remembering the name, and for writing many times at the top of python files when importing.
> 
> [One of the] associated application [names] is `RAIContours`. Essentially the branding around the package is to have RAI be the 'prepend' acronym [for each of the applications created].
> 
> I had also thought of RTAI, but that clashes with the Real Time Application Interface for Linux (https://www.google.com/search?q=rtai).
> 
> Also, radiation therapy cancer treatment uses radiation "rays" and "rai" can be pronounced "ray", so it is quite a neat overlap there that would be useful to be able to take advantage of.
> 
> It would be absolutely amazing if you were willing and able to facilitate a transfer. Thank you, so very much.
> 
> Kind regards,
> Simon

That was on the 21st of September. I'll update this issue when I have further information.

**Comment by yeraydiazdiaz** [comment]
Hi @SimonBiggs, it seems you're already the owner of the project so I assume the previous owners transferred it to you.

**Comment by SimonBiggs** [comment]
Hi, yes! Sorry I should have closed this.

Thank you!
