### ISSUE TITLE
PEP 541 Request: claim TestPyPI project teradataml

### ISSUE THREAD

**Issue by tomcnolan** [pypa/pypi-support#2245]
### Project to be claimed

TestPyPI project teradataml: https://test.pypi.org/project/teradataml/

### Your PyPI username

TestPyPI user teradata: https://test.pypi.org/user/teradata/

### Reasons for the request

TestPyPI project teradataml is currently owned by TestPyPI user sv250058 (Sanath Vobilisetty) who is a former employee of Teradata Corporation.

Teradata Corporation needs to claim the TestPyPI project teradataml and transfer the project to the official Teradata Corporation TestPyPI user teradata.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Source code repository is internal to Teradata Corporation and is not published on the Internet.

### Contact and additional research

Sanath Vobilisetty is a former employee of Teradata Corporation and we have no current contact information.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
It seems the project is already owned by user `teradata` in both Test PyPI and PyPI
