### ISSUE TITLE
Regain access to my PyPI account

### ISSUE THREAD

**Issue by KhaimovMR** [pypa/pypi-support#225]
Hello.

I've got no recovery codes for the 2 factor authentications (I don't even remember to activate it on any of my devices), but I have a full access to the email of my account and I have a password to the pypi account.
Could you help me, please, to regain the access to the account again?

Kind regards,
Michael Khaimov.

**Comment by ewdurbin** [comment]
@KhaimovMR please provide the information requested in the Account Recovery template:

```
---

Request for account recovery.

## PyPI Username

<!-- Replace the following with your PyPI username -->
`username`

---

##  Reason for request

<!-- State the reason for your request
  - Lost access to email address
  - Lost 2FA authentication app or security token
-->

Reason:
```

**Comment by KhaimovMR** [comment]
---

Request for account recovery.

## PyPI Username

KhaimovMR
---

##  Reason for request

Lost 2FA authentication app and have no backup codes.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
