### ISSUE TITLE
PEP 541 Request: identity

### ISSUE THREAD

**Issue by rayluo** [pypa/pypi-support#2251]
### Project to be claimed

`identity`: https://pypi.org/project/NONEXIST

### Your PyPI username

`Ray Luo`: https://pypi.org/user/rayluo

### Reasons for the request

Unlike other PEP 541 requests, this time the [project `identity` does not even exist on PyPI](https://pypi.org/search/?q=identity). So I proceeded with that project name, and successfully uploaded [my new package `identity` onto TestPyPI](https://test.pypi.org/project/identity/), but the attempt on PyPI failed with this error message:

    ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'identity' isn't allowed. See
         https://pypi.org/help/#project-name for more information.

After reading the 4 reasons of "[why isn't my desired project name available](https://pypi.org/help/#project-name)", I figure it is "The project name has been explicitly prohibited by the PyPI administrators". But why? This is not the `requirements.txt` case.

P.S.: I do work in the Identity/Authentication area for years, and I am currently the main maintainer of [another authentication library MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-python). This new library is a genuine effort on creating a new library for the ecosystem.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Current project repo: N/A. It does not exist.

New project repo: https://github.com/rayluo/identity

### Contact and additional research

N/A. No old project exists.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @rayluo, the name `identity` was placed in the prohibited project names list. A @pypa/warehouse-admins should be able to release it to you.

**Comment by di** [comment]
I've released `identity` to `rayluo`.
