### ISSUE TITLE
PEP 541 Request: PyDO

### ISSUE THREAD

**Issue by mikeberezowski** [pypa/pypi-support#2252]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/PyDO

### Your PyPI username

`USER_NAME`: https://pypi.org/user/do-api-engineering

### Reasons for the request

DigitalOcean is developing an officially supported API client library in Python. The project name PyDo conforms to our naming convention so we want to use this project name for our new library.

I have written confirmation from the current project owners that we can transfer ownership of this project and replace the codebase. The current project hasn't been developed or released since 2007.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no longer a link to the code repository for the existing project.

Our new project hasn't been made public yet, we are waiting to set up the pypi project, so that we can correctly name our package in our repository.

### Contact and additional research

I contacted the owner Jacob Smullyan on July 20, 2022. On July 22, 2022 Jacob confirmed they are willing to transfer the project name. See quoted text below:

`Hi Mike - I spoke with project's other owner and we agreed it would be fine for you to use the name.

I'll look at what's involved in turning it over this weekend.

j

-
Jacob Smullyan`

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mikeberezowski** [comment]
We would like confirmation about this project ownership transfer so that we can update our package in our repository before opening it publicly. Once complete I can link the github project repo.

**Comment by yeraydiazdiaz** [comment]
Hi @mikeberezowski, it looks like `do-api-engineering` is already an owner of the PyDO package so no transfer is possible.

**Comment by mikeberezowski** [comment]
Yes, I was misinterpreting the instructions for the ownership transfer. Thank you for following up. This is resolved.
