### ISSUE TITLE
PEP 541 Request: weasel

### ISSUE THREAD

**Issue by svlandeg** [pypa/pypi-support#2255]
### Project to be claimed

`weasel`: https://pypi.org/project/weasel

### Your PyPI username

explosion

### Reasons for the request

I don't see this package being in use, but nevertheless I'm getting a 
>  The user 'explosion' isn't allowed to upload to project 'weasel'. See https://pypi.org/help/#project-name for more information.

when trying to upload.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

We want to start using https://github.com/explosion/weasel to host the code we currently have in https://github.com/explosion/spaCy/tree/master/spacy/cli/project as a separate package. Before continuining, we'd like to know whether this name will be available on pypi or not though...

### Contact and additional research

There is no current owner of a "weasel" project as far as I can see - so I'm unsure why the upload command is failing. Is there another reason why `weasel` is locked orso?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @svlandeg, `weasel` exist but has no releases which is why PyPI responds with a 404. However, the project is invalid and subject to transfer. I will attempt contact with the owner and allow one week for replies before moving forward with your request.

**Comment by yeraydiazdiaz** [comment]
Hi @svlandeg, the owner just deleted the project so hopefully you should be able to upload yours now.

**Comment by svlandeg** [comment]
Hi @yeraydiazdiaz, thanks a lot! We've uploaded a placeholder for now and will be moving the proper code into the proper repo soon. We're really excited to have this name for our new workflow system. Thanks again!
