### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vinayak-mehta** [pypa/pypi-support#226]
Request for account recovery.

## PyPI Username

`vinayakmehta`

---

##  Reason for request

Reason: Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by vinayak-mehta** [comment]
Thanks for looking into this! I've replied to the email.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by vinayak-mehta** [comment]
Thanks!
