### ISSUE TITLE
PEP 541 Request: pymeter

### ISSUE THREAD

**Issue by eldaduzman** [pypa/pypi-support#2260]
### Project to be claimed

`pymeter`: https://pypi.org/project/pymeter

### Your PyPI username

`eldad.uzman`: https://pypi.org/user/eldad.uzman

### Reasons for the request

This project has been inactive since 2007, it has no website attached, no source code repository, the sole owner has a corporate email address that might be inactive.

I would like to replace it with a better project that will serve a vast community of python performance engineers as well as backend developers and devops professionals.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

As mentioned above, the project has no source code repository.
The replacing source code is [at ](https://github.com/eldaduzman/pymeter/), currently it's private but I'll make it public soon enough.

### Contact and additional research

I contacted the owner as you can see in the image attached, no reply.
I think this corporate email address is inactive.

![image](https://user-images.githubusercontent.com/55621402/192617085-7380a319-1c99-463a-b01f-d1e75d2080e5.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @eldaduzman, I will now start the reachability process for your request. I believe the owner is GitHub user @kov who seems somewhat active. Hopefully we will hear back from him soon and proceed with the transfer.

**Comment by kov** [comment]
Oh hai, yes I am happy for you to replace pymeter in pypi with your project. The email address listed in the page is working, though I am not paying as much attention to it as I used to. But if the process requires verification that I control kov@debian.org we can do that (I could not see anything on a first glance).

**Comment by eldaduzman** [comment]
Thanks @kov , @yeraydiazdiaz how do we continue with this case?

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @kov, I've transfered the project now.
