### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by crazyzhou** [pypa/pypi-support#2262]
### PyPI Username

pravega

### Reason for request

Lost access to email address.

This account should be maintainer-shared account for this project: https://pypi.org/project/pravega/ , but our previous maintainer @shrids who creates this account is not reachable now, thus lost access to the email address. We need to validate this account to make our next release. Looking forward to response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by crazyzhou** [comment]
cc @tkaitchuck

**Comment by tkaitchuck** [comment]
To prevent this from happening again. We could use cncf-pravaga-dev@lists.cncf.io

**Comment by crazyzhou** [comment]
> To prevent this from happening again. We could use [cncf-pravaga-dev@lists.cncf.io](mailto:cncf-pravaga-dev@lists.cncf.io)

I'm not sure if it is appropriate. This mailing list is public to all developers, any developer can see all the mails and even change password. It's would be better if we have a specific email account under `@pravega.io` that only maintainers can have access.

**Comment by ewdurbin** [comment]
Contacted via primary email address as well as all additional addresses on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. Primary email address has been updated to the user who completed confirmation and a password reset issued, you should be able to regain access to your account after completing the password reset.
