### ISSUE TITLE
PEP 541 Request: dag

### ISSUE THREAD

**Issue by nanx64** [pypa/pypi-support#2267]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/dag

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nanx64

### Reasons for the request

I would like to publish a Python 3 library for DAG composing / dataflow programming, which will allow users to write data-processing tasks in a streaming fashion.
I am currently using it on multiple data-processing-heavy projects of mine.
It can be easily integrated into existing codebases, since it is very lightweight and simple  to use.
I also submitted #2265, which is also an appropriate package name for this project, but since the outcome of that issue is questionable, I want to claim this highly-related package name as well, just in case.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

New project repo (my project): https://github.com/nanx64/dataflow
Old project repo (abandoned project): N/A
(the homepage link is also broken: http://entitycrisis.blogspot.com/)

### Contact and additional research

I tried contacting the user over the email listed on PyPI: simonwittber@gmail.com
The PyPI project is also as dead as it can be - no description, no documentation, no releases, nothing... Not to mention it doesn't even support Python 3.
The last release was more than 15 years ago.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @nanx64, I will now start the reachability process for your request. Hopefully we will hear back from the owner soon and proceed with the transfer. I believe the owner is GitHub user @simonwittber.

**Comment by nanx64** [comment]
@yeraydiazdiaz hello, just a quick reminder - 6 weeks after nov 12 is due on dec 24 (5 days ago); looking forward for your status update! thanks!!

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.
