### ISSUE TITLE
PEP 541 Request: pydantic-settings

### ISSUE THREAD

**Issue by samuelcolvin** [pypa/pypi-support#2272]
### Project to be claimed

`pydantic-settings`: https://pypi.org/project/pydantic-settings

### Your PyPI username

`samuelcolvin`: https://pypi.org/user/samuelcolvin

### Reasons for the request

Daniel Daniels (Данилкин Даниил) has agreed to transfer the `pydantic-settings` package to the pydantic organisation (e.g. my pypi account).

However he's lost his security key and therefore can't log in to PyPI. I'm sure he'll be happy to confirm that via email, and also via his github account @danields761.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/danields761/pydantic-settings

### Contact and additional research

I have an email exchange, I'm sure @danields761 will confirm.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by danields761** [comment]
Hello!

I'm `danields` on pypi, original owner of package `pydantic-settings`.

I'm confirming the package name transfer to @samuelcolvin 

Please, tag me, if there's any other action required from me

**Comment by yeraydiazdiaz** [comment]
@samuelcolvin I've added you as an owner of `pydantic-settings`.

**Comment by samuelcolvin** [comment]
Thank you so much. I'm AFK, I'll check everything if okay on Tuesday.
