### ISSUE TITLE
PEP 541 Request: wallet

### ISSUE THREAD

**Issue by johnturnham** [pypa/pypi-support#2275]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/wallet

### Your PyPI username

`USER_NAME`: https://pypi.org/user/walletinc

### Reasons for the request

Wallet Inc is a C-Corporation, organized in the state of Delaware in May of 2015, with its headquarters located in California. The company provides a B2B2C SaaS platform for merchants to optimize the customer lifecycle through a combination of CRM, marketing, digital payments, and messaging features, provided through a digital wallet interface for consumers. The platform is entirely proprietary, built from scratch, and the company has been publishing reusable modules to NPM (https://www.npmjs.com/package/wallet) and through its developer hub (https://wallet.dev) for years.

As the company introduces its Python SDK to the development community, it appears that another user (motives unknown, but presumably a name squatter) has reserved the package name, and has not published any code since the name was reserved in 2017. At the time of this request, the wallet package in Pypi is still at version 0.0.0.0 and contains no code.

To prevent confusion in the development community, and to ensure uniformity across all package management systems, we politely respectfully request a reassignment of this name to Wallet Inc.

![NPM - Wallet Inc](https://user-images.githubusercontent.com/8730862/193477382-def60a6c-1f20-45fe-b5f1-9bf276835070.png)
![Pypi - Name Squatter](https://user-images.githubusercontent.com/8730862/193477422-26245e4c-5992-45ad-97fb-46d223385ec4.PNG)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing repository: https://github.com/muraty/wallet (404, does not exist)

Replacement repository: https://github.com/WalletInc/api-clients/tree/master/python

### Contact and additional research

We have been unable to locate any method to contact existing owner "muraty". No contact details have been listed on Pypi.

We believe some assistance from a moderator is necessary to facilitate the outreach and name transfer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @johnturnham, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
