### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mt0rm0** [pypa/pypi-support#2276]
### PyPI Username

mt0rm0

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello, I am showing that this account has successfully logged in as of 10-12-2022. Please re-open if you still need support.

**Comment by ewdurbin** [comment]
Ah, duplicate of #1778
