### ISSUE TITLE
PEP 541 Request: kwik

### ISSUE THREAD

**Issue by dmezzogori** [pypa/pypi-support#2277]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/kwik

### Your PyPI username

`USER_NAME`: https://pypi.org/user/dmezzogori

### Reasons for the request

I would like to take ownership of the project, since it seems the project is stale and not updated anymore. The aim of the takeover is for replacement with a library of mine (already on Github, as private repo, soon to be open-sourced).

Formally, I will be following the procedure described at [PEP541](https://peps.python.org/pep-0541/)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

[Current project](https://github.com/sroedger/kwik)

[Project to be published](https://github.com/dmezzogori/kwik)

### Contact and additional research

Tried to contact the library author via mail [sroedger@gmail.com](mailto:sroedger@gmail.com) in date 2022-09-30 (no reply yet).
Posted an [issue](https://github.com/sroedger/kwik/issues/1) on github, with request to take over.

![image](https://user-images.githubusercontent.com/1754525/193617230-8b5c8781-2f6e-40d1-9e2f-e0105777ca98.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Ovsyanka83** [comment]
I don't think you can make a PEP 541 with a closed source repository. If you want to speed up the process, I suggest you make the repository public :)

**Comment by yeraydiazdiaz** [comment]
Hello @dmezzogori, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by dmezzogori** [comment]
Hello @yeraydiazdiaz, thank you very much for your feedback. May I ask if what @Ovsyanka83 suggests is correct? A Github public repository is something needed for the process, or just to speed up, or not at all? Thanks again.

**Comment by yeraydiazdiaz** [comment]
The transfer is now complete. It is not a requirement for projects in PyPI to be open source, that being said for PEP 541 requests it does help since moderators are able to gauge the maturity of the projects easily. In this case it's irrelevant since the project is invalid.

**Comment by dmezzogori** [comment]
Thanks a lot! Will be open sourcing the project ASAP, as this is the goal anyway!
