### ISSUE TITLE
PEP 541 Request: `rod`

### ISSUE THREAD

**Issue by diegoferigo** [pypa/pypi-support#2278]
### Project to be claimed

`rod`: https://pypi.org/project/rod/

### Your PyPI username

`dgferigo`: https://pypi.org/user/dgferigo

### Reasons for the request

The original [git repo](https://github.com/jmcs/redis-object-database) has been archived and the last commit is 8 years old.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: https://github.com/jmcs/redis-object-database
Replacement project: https://github.com/ami-iit/rod

### Contact and additional research

I wrote the owner the following email, cc-ing him also here @jmcs

![Screenshot_20221109_094307](https://user-images.githubusercontent.com/469199/200782037-825ba143-a265-4f0d-b1d5-cb85944d73df.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jmcs** [comment]
I missed the original e-mail. I deleted the project as I also don't use it anymore.

**Comment by diegoferigo** [comment]
> I missed the original e-mail. I deleted the project as I also don't use it anymore.

No problem, thanks so much @jmcs for taking care! I appreciate it :rocket: 

I just tried to manually upload the [latest dev sdist](https://pypi.org/project/rod/0.1.dev51/) and it succeeded, I'm closing this issue.
