### ISSUE TITLE
File Limit Request: mvtb-data - 150 MB

### ISSUE THREAD

**Issue by petercorke** [pypa/pypi-support#2279]
### Project URL

https://pypi.org/project/mvtb-data/

### Does this project already exist?

- [X] Yes

### New Limit

150MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a set of data to support a new Python computer vision package that in turn supports a textbook.

I have split the project data (images) off from the [code](https://pypi.org/project/machinevision-toolbox-python) since the image data changes infrequently so it makes code updates smaller and more efficient.

Some very big image files live on another server and I provide a script to download those as needed.

### Reasons for the request

I have deleted some images that I would like to include in order to make it fit under the 100MB limit.

150MB will be enough.  

There are two massive files 300MB that I provide on another server since they support just one example in the book and are likely to be used by a small hardcore set of readers.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @petercorke :wave:
Seems like the 'Home' url on your PyPi project is broken and is missing a `-`:
Currently is: https://github.com/petercorke/machinevisiontoolbox-python and checking your profile it should be https://github.com/petercorke/machinevision-toolbox-python right?

I've set the upload limit for `mvtb-data` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Cheers
