### ISSUE TITLE
PEP 541 Request: balance

### ISSUE THREAD

**Issue by stevemandala** [pypa/pypi-support#2280]
### Project to be claimed

`balance`: https://pypi.org/project/balance

### Your PyPI username

`scubasteve`: https://pypi.org/user/scubasteve

### Reasons for the request

Our group has a statistical modeling project named balance, for which I am introducing a new Python package as part of our open source initiative. Attempting to load our initial pkg to PyPI results in:

```
Uploading balance-0.0.0-py3-none-any.whl
. . .
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         The name 'balance' isn't allowed. See https://pypi.org/help/#project-name for more information.
```
I am not aware of any collisions with the Py standard library and PyPi doesn't appear to have this packaged reserved for another project. I would like to understand why this name is reserved/prohibited, and whether it would be possible to release this name as it would match our public name & source code repo for the project.

### Source code repositories URLs

Github: https://github.com/facebookresearch/balance

(At the time of this writing, our repository is currently private, pending setup of our external deployments & documentation at which point it will be made public)

### Contact and additional research

I could not find any project named balance. There are other projects with different names (e.g. boi-balance), but none matching this exact name 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've released `balance` to `scubasteve`.

**Comment by talgalili** [comment]
Thanks!
