### ISSUE TITLE
PEP 541 Request: ambrosia

### ISSUE THREAD

**Issue by xandaau** [pypa/pypi-support#2281]
### Project to be claimed

`ambrosia`: has no active page in PyPI(https://pypi.org/project/ambrosia/)

### Your PyPI username

`xandaau`: https://pypi.org/user/xandaau

### Reasons for the request

Our team has developed and published an open-source library for conducting A/B tests which will benefit data scientists/analytics community and enthusiasts.

We would like to claim `ambrosia` project name in PyPI, since the existing project with such name has no releases, no PyPI homepage, does not have any activity and owner contact information; so I believe it clearly falls under the definition of "abandoned project".

This name of the project was agreed with the lawyers of our company in the process of publishing the library as an open source project and is really important for us. 
We are going to continue to actively develop our `Ambrosia` project for the benefit of the open community.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

There is no evidence of existing project repository(it has no PyPI page)
[Project to be published](https://github.com/MobileTeleSystems/Ambrosia)

### Contact and additional research

I have found no evidence of such project in PyPI, its functionality, and any author contact information.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nschloe** [comment]
https://pypi.org/project/ambrosia/ no longer exists so I believe this can be closed.

**Comment by xandaau** [comment]
No it could not. I guess there is stiil a project with no releases, because we have this error:

`HTTP Error 403: The user 'xandaau' isn't allowed to upload to project 'ambrosia'. `

**Comment by yeraydiazdiaz** [comment]
Hello @xandaau, I can confirm the project exists but has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by xandaau** [comment]
Thank you, sir
