### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fuhuifang** [pypa/pypi-support#2282]
### PyPI Username

azureml-ds

### Reason for request

Lost 2FA authentication and recovery code showed expired

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by fuhuifang** [comment]
Was able to recover the account with @ewdurbin's help.
