### ISSUE TITLE
PEP 541 Request: elk-py

### ISSUE THREAD

**Issue by stez-mind** [pypa/pypi-support#2284]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/elk-py

### Your PyPI username

`USER_NAME`: https://pypi.org/user/max_ElkAudio

### Reasons for the request

We were about to publish our `elkpy` package:
https://github.com/elk-audio/elkpy

The current `elk-py` registered on PyPi is a completely empty project and not maintained since 2018.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Original:
https://github.com/tenzinngodup/elk-py

Replacement:
https://github.com/elk-audio/elkpy

### Contact and additional research

We contacted the author of the original package at:
tenngo@yahoo.com

without receiving a response yet.

You can contact me at:
stefano@elk.audio

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
I must have missed commenting on this issue, but the project is indeed invalid. I contacted the owner last week and got no response so I proceeded with the transfer.
