### ISSUE TITLE
PEP 541 Request: tripper

### ISSUE THREAD

**Issue by CasperWA** [pypa/pypi-support#2286]
### Project to be claimed

`tripper`: https://pypi.org/project/tripper

### Your PyPI username

`CasperWA`: https://pypi.org/user/CasperWA

### Reasons for the request

The project does not exist, but was part of the mass name squat by RemindSupplyChainRisks. See pypa/pypi-support#935 and https://discuss.python.org/t/projects-automatically-deleted-from-pypi/8710 for more information.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project does not actually exist.
Intended project: https://github.com/EMMC-ASBL/tripper

### Contact and additional research

While the package could not be found via pypi.org, it was found on libraries.io: https://libraries.io/pypi/tripper
Here is was clear it was related to the mass name squat issue mentioned and fixed in pypa/pypi-support#935 and discussed also here: https://discuss.python.org/t/projects-automatically-deleted-from-pypi/8710

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've released `tripper` to `CasperWA`.
