### ISSUE TITLE
PEP 541 Request: matplotlib-arm64

### ISSUE THREAD

**Issue by tacaswell** [pypa/pypi-support#2291]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/matplotlib-arm64

### Your PyPI username

`USER_NAME`: https://pypi.org/user/thomas.caswell

### Reasons for the request

This project appears to be a wheel-only build of an old version (3.3.4 from Jan 2021) of Matplotlib for py36 on aarch64.manylinux2014.  All the front matter for the project is identical to the upstream project.

The original release is https://pypi.org/project/matplotlib/3.3.4/ which does not have published aarch64 wheels.

I believe that this project has a high chance of confusing users to think that this wheel is uploaded by the Matplotlib project.  

In the best case this is an earnest attempt to provide wheels for a niche need (I skimmed a couple of the .py files from the wheel and they look right, but did not do a systematic search) and in the worst case malicious.

In general I think `matplotlib-XYZ` packages are OK so long as they are extensions not republishing binary builds of upstream.

### Source code repositories URLs

https://github.com/matplotlib/matplotlib in both cases.

### Contact and additional research

There is no public contact information for the user (https://pypi.org/user/aditya_j/) and all of the contact information on the package is for Matplotlib (which I am the project lead of).

The user has also done the same for skimage (https://pypi.org/project/scikit-image-arm64/).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @tacaswell, I'm not sure what would be the best outcome for the issue is, but it is certainly not a PEP 541 request. I'll defer to @pypa/warehouse-admins for judgement and action on this but remove the PEP 541 issue to avoid confusion.

**Comment by tacaswell** [comment]
@yeraydiazdiaz Fair enough.  I was not sure what the right path for "impersonation" was.  We have had this issue with `pyplot` in the past, but in thoses cases we were able to get a hold of the person involved and work something out.

**Comment by ewdurbin** [comment]
In cases like these, I think such projects are valid when:

1) The upstream has no interest or plans for releasing builds for the usecase
1) The publisher makes clear they are releasing unofficial builds for a specific usecase
1) The publisher makes an effort to keep their project and builds up to date with upstream

In this case, none of those seem applicable. I'll contact the user to notify them, and plan to transfer the projects to the corresponding owners/maintainers of upstream projects unless they are up for adhering to the above.

**Comment by ewdurbin** [comment]
Given no response from the user, I have transferred matplotlib-arm64 to the Owners of the matplotlib project to do with as they choose. I will notify the scikit-image maintainers to see how they want to proceed with that project.
