### ISSUE TITLE
File Limit Request: RNAlysis- 350 MB

### ISSUE THREAD

**Issue by GuyTeichman** [pypa/pypi-support#2292]
### Project URL

https://pypi.org/project/RNAlysis/

### Does this project already exist?

- [X] Yes

### New Limit

350

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

RNAlysis is an open-source software for analysis of RNA sequencing data. It has been available on PyPI for over 3 years. 

Multiple scientific publications have already been made which used this software, including:
https://pubmed.ncbi.nlm.nih.gov/35134343/
https://pubmed.ncbi.nlm.nih.gov/33729152/

Up until recently the project did not approach the file size limit, and therefore no efforts to reduce the size of the release have been necessary. 

Previous versions of this project have included a small number of data files; the current development version (V3.0.0) includes a larger quantity of data files, as elaborated below. 

### Reasons for the request

Over the years that RNAlysis has existed, it has been available to users as a programmatic tools, and users had to be familiar with Python coding in order to use it. 

These past few months I have been developing a graphical user interface for this software, to make is more approachable and usable by researchers who are not well acquainted with computer programming in general and the Python language in particular. 

To this end, I had to add data files to the release that increased the release file size - graphical assets, example data, tutorial content, etc. 
Unfortunately, even after compressing these files and minimizing the number of files added to the release, I have not been able to go under the release file size limit of 100MB. 

Since the graphical user interface is meant to appeal to users with no programming experience and low technological literacy, I fear that any complication of the installation or usage process (such as downloading data separately from the software, or calling a separate function upon execution that would fetch the data) could drive away the users who would benefit the most from such a tool. 

Increasing the file size limit of RNAlysis to ~350MB will allow me to release the new version without complications; but even a smaller increase would help me release this version, albeit with a smaller library of user guidance and examples. 

Thanks in advance,

Guy Teichman
developer of RNAlysis

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `RNAlysis` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.
