### ISSUE TITLE
Project Limit Request: TensorFlow-ROCM - 200 GB

### ISSUE THREAD

**Issue by jayfurmanek** [pypa/pypi-support#2296]
### Project URL

https://pypi.org/manage/project/tensorflow-rocm

### Does this project already exist?

- [X] Yes

### New limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

TensorFlow-ROCM is TensorFlow built for AMD GPUs.
We have been active for more than 4 years.

We do expect sizes to increase in the future as TensorFlow itself is large.

### How large is each release?

~1600 MB Total

4 whl files at ~400 MB
TensorFlow is large. It typically includes an embedded LLVM build and full GPU support.

### How frequently do you make a release?

Once a quarter for TensorFlow releases but we refresh n-2 releases with updated ROCM builds.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `tensorflow-rocm` to 200 GB on PyPI. Please be mindful of the frequency of releases at that size.
