### ISSUE TITLE
PEP 541 Request: bibclean

### ISSUE THREAD

**Issue by mscheltienne** [pypa/pypi-support#2297]
### Project to be claimed

`bibclean`: non-existant

### Your PyPI username

`mscheltienne`: https://pypi.org/user/mscheltienne/

### Reasons for the request

My publication workflow was greeted with:

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         The name 'bibclean' isn't allowed. See                                 
         https://pypi.org/help/#project-name for more information.       
```

Yet, this name is not used, see: https://pypi.org/search/?q=bibclean
I fail to understand why it's locked, could you please let me know?

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Source: https://github.com/mscheltienne/bibclean

### Contact and additional research

There is no current owner..

Thanks for the help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've transferred `bibclean` to `mscheltienne`.
