### ISSUE TITLE
PEP 541 Request: jibe

### ISSUE THREAD

**Issue by jpcaram** [pypa/pypi-support#230]
**Project to be claimed**
`jibe`: https://pypi.org/project/jibe

**Your PyPI username**
`jpcaram`: https://pypi.org/user/jpcaram

**Reasons for the request**
No releases and abandoned.

**Maintenance or replacement?**
There is no package. Does not apply.

**Contact and additional research**
There is no page for the project in pypi, so I cannot possibly know the owner's name or contact information. I also searched for "jibe python" and nothing related shows up.

**Comment by yeraydiazdiaz** [comment]
Hello @jpcaram, I can confirm the project has no releases and is thus invalid.

I will ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
transfer complete.
