### ISSUE TITLE
File Limit Request: intel-extension-for-tensorflow-lib - 250 MB

### ISSUE THREAD

**Issue by ashahba** [pypa/pypi-support#2300]
### Project URL

https://pypi.org/project/intel-extension-for-tensorflow-lib/
https://test.pypi.org/project/intel-extension-for-tensorflow-lib/

### Does this project already exist?

- [X] Yes

### New Limit

250MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is an `Intel` owned project that we are planning to release in the next few weeks as part of our TensorFlow Optimizations and it'll be owned and maintained by this user: https://pypi.org/user/IntelAI/

### Reasons for the request

As of now the wheels are a little under 250MB in size and being rejected during upload due to larger than default size limit:

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ashahba** [comment]
We decided to hold off on some large wheels for this release to hopefully speedup this approval.

@di please let me know if you have any questions.

Thanks.

**Comment by cmaureir** [comment]
Hello @ashahba :wave:
I've set the upload limit for `intel-extension-for-tensorflow-lib` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice day!

**Comment by ashahba** [comment]
Thank you so much @cmaureir 
I really appreciate your support.
