### ISSUE TITLE
Please delete all my packages

### ISSUE THREAD

**Issue by benshayden** [pypa/pypi-support#2303]
### Problem description

I deleted faulkner891 at gmail.com too long ago to recover it, so I cannot manage the packages under https://pypi.org/user/faulkner/
I keep receiving emails from new project owners who want to use some of the package names.
Please delete all packages under that username so the package names can be recycled and I stop getting emails about them.
Thanks in advance!

**Comment by ewdurbin** [comment]
@benshayden please open as an account recovery request, regain access to your account, then you can transfer names as desired. also note, the account is not associated with a gmail.com address.
