### ISSUE TITLE
File Limit Request: torch-mlir - 500 MB

### ISSUE THREAD

**Issue by dellis23** [pypa/pypi-support#2307]
### Project URL

https://pypi.org/manage/project/torch-mlir/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`torch-mlir` is an llvm project that enables users to compile PyTorch models to MLIR.  We've tried to lower the file size by not running audit wheel, but we're then unable to publish.  `torch-mlir` depends on C++ libraries that are included as part of its wheel to be able to provide maximum compatibility flexibility for the end users.

### Reasons for the request

`torch-mlir` depends on C++ libraries that are included as part of its wheel to be able to provide maximum compatibility flexibility for the end users.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by dellis23** [comment]
Note that the project exists but I've not pushed a 0.0.0 release.  It's unclear to me from the wording whether creating a project is sufficient.  We have a number of users using the project, and I'm worried about creating a broken empty release if not necessary that they might inadvertently install from.

**Comment by cmaureir** [comment]
Hey @dellis23 thanks for the issue details.
You need to push the initial version, so we can manage it, so you could do an alpha release (empty) or a 0.0.0 because I guess you plan to push another version as the new one? anything will do :)

**Comment by dellis23** [comment]
Thanks @cmaureir.  I've created a dummy release here: https://pypi.org/manage/project/torch-mlir/release/0.0.0/

**Comment by dellis23** [comment]
Also, I'm guessing we will hit the project limit pretty quickly if we upload nightly.  Is that true?  If so, are our only options 1) request a higher limit for that too and/or 2) figure out an automated way of deleting old releases?

**Comment by dellis23** [comment]
@cmaureir Friendly ping :-)  Let me know if there's anything else I need to do.

**Comment by cmaureir** [comment]
Thanks for the ping! 
I've set the upload limit for `torch-mlir` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week :rocket:
