### ISSUE TITLE
Project Limit Request: Fiona - 30 GB

### ISSUE THREAD

**Issue by sgillies** [pypa/pypi-support#2308]
### Project URL

https://pypi.org/project/Fiona/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Fiona is a foundational package for the geographic data science community. It's used by GeoPandas and many other projects. We've been publishing wheels to PyPI for 6 years. Fiona vendors over a dozen C libraries (gdal, geos, proj, tiff, curl, etc, along with supporting data) using the strategy pioneered by the numpy and scipy projects. After various optimizations, including library symbol stripping, wheels are 16-26 MB in size, depending on the platform. I expect that wheel sizes won't get significantly larger in future releases, 10-15% at most.

### How large is each release?

3 platforms x 5 versions of Python x 20 MB wheel size  = ~300 MB per release. Most of this is C libraries and supporting data like cartographic projection databases and world geodetic data.

We'd like to offer arm64 wheels in the future, roughly doubling the size of each release.

### How frequently do you make a release?

Once every 2-3 months. A new 30 GB limit would allow ~30 releases (at the future 600 MB size) over the next 5-6 years.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @sgillies :wave: thanks for filling this issue.
I've set the project limit for `fiona` to 30 GB on PyPI. Please be mindful of the frequency of releases at that size.

To avoid having too many Python versions wheels for the same release, you could look into https://docs.python.org/3/c-api/stable.html so you can provide only 1 wheel per platform.
have a nice week!
