### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by arnoldblinn** [pypa/pypi-support#231]
Request for account recovery.

## PyPI Username

`domainconnect`

---

##  Reason for request

Reason:
I'm not receiving the email for a password reset; although I created the account.  I'm the primary owner and contributor to all things Domain Connect; one of which is a Python package to implement the protocol at https://github.com/Domain-Connect/DomainConnectApplyZone

Even knowing the email behind the domainconnect user might help be diagnose what is going on.   Ultimately need to update the package domainconnectzone.....

**Comment by di** [comment]
Hi @arnoldblinn, the primary email address you have on that account is bouncing due to "Recipient address rejected". I've initiated a reset for the secondary email address on that account, and it seems to have been delivered, please update here accordingly.

**Comment by arnoldblinn** [comment]
So I haven't gotten any mails.  Regular or junk folder.

I don't know what the primary and secondary mail are on this account; I'm 95% sure I'm the one who created this account last summer.  But I could be mistaken.  So either someone else owns this account (and they probably shouldn't), or something is going wrong with mail delivery.

You can see that I'm the github owner for this project.  My emails might be a******@godaddy.com, a***********@hotmail.com or a*****@a*********n.com....

**Comment by di** [comment]
Hi @arnoldblinn, it's none of those, please send me an email and we'll take it from there: `di@python.org`

**Comment by ewdurbin** [comment]
@di @arnoldblinn have y'all been able to connect on this?

**Comment by arnoldblinn** [comment]
This was resolved.  I was able to get added to the alternative alias and get access to the account.

Appreciate the help.
