### ISSUE TITLE
PEP 541 Request: excel

### ISSUE THREAD

**Issue by zooba** [pypa/pypi-support#2310]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/excel

### Your PyPI username

`USER_NAME`: https://pypi.org/user/microsoft

### Reasons for the request

The project appears to be abandoned after the first release in 2015, the user's GitHub history is silent, listed website appears to have been taken over by spam, and listed email address is unresponsive.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Current project: https://github.com/twz915/excel

Our new project is not yet released (we want to confirm the package name first). Initially we'd probably put up a placeholder to ensure the old code isn't being installed with our name attached, but are planning to publish an actual library within the next 6-8 months.

### Contact and additional research

The listed email host for the owner appears to be dead, and their website is no longer alive.

We haven't made any other attempts to contact them yet, since if the email is gone they probably can't log into PyPI themselves anymore. If they registered with a different email, the moderators will have to try it because we can't see it.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by zooba** [comment]
Ping team - any updates for us on this?

**Comment by yeraydiazdiaz** [comment]
Hello @zooba, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back soon and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer which is now complete.

**Comment by zooba** [comment]
Thank you
