### ISSUE TITLE
Project Limit Request: Open3D - 25 GB

### ISSUE THREAD

**Issue by ssheorey** [pypa/pypi-support#2311]
### Project URL

https://pypi.org/project/open3d/

### Does this project already exist?

- [X] Yes

### New limit

25 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[Open3D](https://github.com/isl-org/Open3D) is an open-source library that supports rapid development of software that deals with 3D data. The Open3D frontend exposes a set of carefully selected data structures and algorithms in both C++ and Python. It is active since 2018.

Open3D is widely used by the computer vision community and it was downloaded 2.5M+ times from PyPI in 2021. It was  designated as critical (top 1% downloads) in 2022.

We expect the total project size to increase in the future with continued releases. The main contributor to the size of the wheels are compiled binary libraries, especially CUDA binaries. The size of each release has also increased recently, since we are adding support for more hardware platforms (such as SYCL devices and macOS on Apple Silicon).

### How large is each release?

Each release is about 2.5GB in size and provides support for all current Python versions on different platforms:

4x 400MB for 4 Linux x86_64 wheels (with CUDA support).
4x 56MB for 4 Linux ARM64 wheels.
4x 71MB for 4 macOS x86_64 wheels.
3x 36MB for 3 macOS ARM64 (M1) wheels.
4x 60MB for 4 Windows x86_64 wheels.

We have made efforts to reduce the size of wheels by reducing the number of precompiled CUDA platforms.

We do not bundle test data with the wheels - we instead provide easy functionality for downloading it as required. Dependent packages are not bundled into the wheel but installed by pip as separate dependencies.

### How frequently do you make a release?

Roughly every 4-6 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @ssheorey :wave: thanks for the details you shared. 
I've set the project limit for `open3d` to 25 GB on PyPI. Please be mindful of the frequency of releases at that size.

To avoid having too many wheel per python version, you might want to check https://docs.python.org/3/c-api/stable.html to provide only one wheel per platform.
have a nice week!
