### ISSUE TITLE
PEP 541 Request: arrow

### ISSUE THREAD

**Issue by krisfremen** [pypa/pypi-support#2315]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/arrow

### Your PyPI username

`USER_NAME`: https://pypi.org/user/krisfremen

### Reasons for the request

I would like to request to be added as an owner to be able to publish new versions of the releases from GitHub.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/arrow-py/arrow

### Contact and additional research

I tried to contact the original author of the package on August 25th, but haven't heard back since.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @krisfremen, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back soon and proceed with the transfer.

**Comment by crsmithdev** [comment]
Sorry for the difficulty in reaching me, it's totally fine if Kris is an admin, let me see if I can just do this myself?

**Comment by crsmithdev** [comment]
I have re-sent the invite for Kris

**Comment by yeraydiazdiaz** [comment]
Thank you @crsmithdev, I will close this issue since contact has been made.
