### ISSUE TITLE
PEP 541 Request: selfcord

### ISSUE THREAD

**Issue by Shell1010** [pypa/pypi-support#2316]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/selfcord/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Shell101

### Reasons for the request

The reason I request to claim this project name is because the original owner of the previous project is no longer on github, and it seems that he has completely deleted his github account, hence I was unable to contact him. He has not made any sort of contribution in over a year. His pypi account is also inactive. Before attempting to do this I tried using the name self-cord, however it was deemed "too similar" to an existing project which I assume is this.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

My project: https://github.com/Shell1010/Selfcord

The owner of the current project occupying the name selfcord has since deleted his github account.

### Contact and additional research

I attempted to contact him via github, to which I found that his github was deleted. After further searching, I found this project:
https://pypi.org/project/pyhakoot/

This project is under the same owner account and the homepage button linked to https://github.com/theusaf/KahootPY. After contacting the owner of this repository via discord, apparently they have no association with the selfcord project. They've stated that the PyPI account is not theirs and they assume that the original owner must have forked the project.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Shell1010** [comment]
I have now acquired the project name `selfcord.py` due to the long wait. However, I will still be happy if this project current project name could be given to me. The original owner after all is no longer on github and hasn't had any sort of activity in months.

**Comment by yeraydiazdiaz** [comment]
Hello @Shell1010, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by bentettmar** [comment]
Hi, my old GitHub account is ilyBenny or whatever it was called which you said is not active/deleted now. I would like to keep access to this package on pypi as I have recently created a rewrite but not yet published it to pypi. Yarely i will respond to the email you sent me if needed to verify this account being linked to bennyontop on pypi.

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @bentettmar. As per PEP 541 no transfer is possible against the wishes of the current owner.
