### ISSUE TITLE
PEP 541 Request: pyproximabe

### ISSUE THREAD

**Issue by proxima-se** [pypa/pypi-support#2318]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pyproximabe

### Your PyPI username

`USER_NAME`: https://pypi.org/user/proxima

### Reasons for the request

pyproximabe should be official python sdk name for our opensource project proximabilin on https://github.com/alibaba/proxima

somehow, when I tried to upload the package, I got error like this. 
The project name in pyproject.toml is "pyproximabe". I don't know the reason of problem.

#twine upload -r pypi dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: proxima
/opt/anaconda3/lib/python3.8/site-packages/twine/auth.py:75: UserWarning: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
  warnings.warn(str(exc))
Enter your password:
Uploading pyproximabe-0.2-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40.1k/40.1k [00:01<00:00, 22.2kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'pyproximabe' isn't allowed. See https://pypi.org/help/#project-name for more information.

### Source code repositories URLs

https://github.com/alibaba/proxima/tree/master/sdk/python

### Contact and additional research

I don't know if the name "pyproximabe" is owned by others.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @proxima-se, `pyproximabe` was placed in the prohibited project names list by a @pypa/warehouse-admins, they should be able to release the project to you.

**Comment by proxima-se** [comment]
Thanks for your help. It's uploaded successfully.
