### ISSUE TITLE
Test-PyPi Website and Upload Failures

### ISSUE THREAD

**Issue by cw00dw0rd** [pypa/pypi-support#2319]
### My Platform

When attempting to upload to Test PyPi via GitHub Actions I receive the following error:
```
Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 503 Service Unavailable from https://test.pypi.org/legacy/  
         Backend is unhealthy
```
Additionally, multiple pages on test-pypi report service are unavailable, but I see no indicator of this on the status page.
![image](https://user-images.githubusercontent.com/7775349/197195293-1dce1967-6a90-4ce4-a87e-bb7a8ee7c1e0.png)
Some Affected pages:
https://test.pypi.org/legacy/
https://test.pypi.org/help/
https://test.pypi.org/sponsors/
https://test.pypi.org/help/#feedback
https://test.pypi.org/security/
https://test.pypi.org/policy/terms-of-use/

Additionally, there is no longer a sign-in button on the website, though this was available at least Wednesday (10/19) evening.
![image](https://user-images.githubusercontent.com/7775349/197195540-93978b23-7bb0-4686-806a-38fea9e28231.png)

I can update the rest of the template if that will help with this and I saw mention of installing a GitHub action to test that end in this issue: https://github.com/pypa/pypi-support/issues/2317

### Fastly Debug

``` (paste your output on the next line)

```

### DNS Resolution

```console (paste your output after the line with the dig command)
$ dig pypi.org A

```

```console (paste your output after the line with the dig command)
$ dig pypi.org AAAA

```

```console (paste your output after the line with the dig command)
$ dig files.pythonhosted.org A

```

```console (paste your output after the line with the dig command)
$ dig files.pythonhosted.org AAAA

```

### Traceroutes / IPv4

```console (paste your output after the line with the traceroute command)
$ traceroute pypi.org

```

```console (paste your output after the line with the traceroute command)
$ traceroute files.pythonhosted.org

```

### Traceroutes / IPv6 (If available)

```console (paste your output after the line with the traceroute command)
$ traceroute6 pypi.org

```

```console (paste your output after the line with the traceroute command)
$ traceroute6 files.pythonhosted.org

```

### HTTPS Requests / IPv4

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json

```

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz

```

### HTTPS Requests / IPv6 (If available)

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv6 https://pypi.org/pypi/pip/json

```

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv6 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz

```

### TLS Debug / IPv4

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -4 -connect pypi.org:443

```

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -4 -connect files.pythonhosted.org:443

```

### TLS Debug / IPv6 (If available)

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -6 -connect pypi.org:443

```

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -6 -connect files.pythonhosted.org:443

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
test.pypi.org service restored.
