### ISSUE TITLE
PEP 541 Request: somata

### ISSUE THREAD

**Issue by mh105** [pypa/pypi-support#2322]
### Project to be claimed

`somata`: https://pypi.org/project/somata

### Your PyPI username

`mh105`: https://pypi.org/user/mh105

### Reasons for the request

Hi, we have a new project developed under the name `somata` (source at https://github.com/mh105/somata), and we would like to use the same name for PyPI packaging as "somata". We've already tried uploading under `somata` to Test PyPI server successfully (https://test.pypi.org/project/somata/0.1.1). However, when trying to create a package with this name to PyPI encounters the error saying "The name 'somata' isn't allowed.": 

```
% python3 -m twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: __token__
Enter your password: 
Uploading somata-0.1.1-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB • 00:00 • 79.5 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                                                                                                
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                                                                                       
         The name 'somata' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

I would like to get help and understand why this name isn't allowed, and whether it could be possible to be released. I don't believe this is strictly a PEP 541 request, since there isn't an existing package with this name therefore no ownership to transfer. But I have exhausted other criteria as described on https://pypi.org/help/#project-name and this seems the closest issue template to use. Thank you.

### Source code repositories URLs

https://github.com/mh105/somata

### Contact and additional research

There is no existing package with the name `somata`, so no owner could be contacted. There is also no other closed or open issue tickets requesting the same name. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @mh105, `somata` was placed in the prohibited project names list by a @pypa/warehouse-admins, they should be able to release the project to you.

**Comment by mh105** [comment]
@yeraydiazdiaz Thank you for the reply comment. Is there a way for us to reach out to the admins? Please let me know if there's anything I should do to make the release happen. Thank you!

**Comment by yeraydiazdiaz** [comment]
I've tagged them above and place your request in the appropriate project list. Admins are quite busy but they will get to your request.

**Comment by ewdurbin** [comment]
Project name `somata` has been released to the `mh105` User on PyPI.

**Comment by cracker911181** [comment]
@ewdurbin please check my issue. And fix it as soon as possible please🥺🥺

https://github.com/pypi/support/issues/2570
