### ISSUE TITLE
File Limit Request: mindspore, mindspore-dev  - 1200 MB

### ISSUE THREAD

**Issue by nicholasyanghaoran** [pypa/pypi-support#2324]
### Project URL

https://pypi.org/project/mindspore/ https://pypi.org/project/mindspore-dev/

### Does this project already exist?

- [X] Yes

### New Limit

1200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.

### Reasons for the request

MindSpore is merging its backend-specifc packages to one unified package for linux (still using smaller, CPU-only packages for Windows and MacOS), this will reduce the total space taken, but increase the size of a single package. Projects including mindspore-ascend and mindspore-ascend-dev will then be removed to save storage space.
Could you please hlep increase the file size limit to 1200MB per package? Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nicholasyanghaoran** [comment]
Cloud someone please review this requeset? It has been a month and we are unable to publish our latest releases on pypi :(

**Comment by nicholasyanghaoran** [comment]
@ewdurbin @cmaureir I'm very sorry for the interruption, could you please have a look into this request and let me know if it is ok to raise the limit? And for #2325 as well. Our team would like to know whether or not we are still able to publish our packages here

**Comment by cmaureir** [comment]
Hey @nicholasyanghaoran sorry for missing this issue,
and thanks for the ping.
It's certainly a large size for a wheel, I do recommend you explore ways to get some of the models that you are shipping with different alternatives, like other modules that offer an option to download extra data, datasets, models, etc.
Additionally, you can always explore a way of splitting  a bit your project into pieces that don't change much, so you can have dependencies, and not offering one 1.2G package.

I've set the upload limit for `mindspore` and `mindspore-dev` to 1200 MB on PyPI. Please be mindful of the frequency of releases at that size.

have a nice day!

**Comment by nicholasyanghaoran** [comment]
Thank you very much! There are no datasets or models within this package, we had to include different sets of compiled binaries in order to support CUDA10 and CUDA11 and some other hardware platforms using one single package, and the current size is rather a conjuction of previously sepearated packages, which actually saves a bit of space than uploading 3~4 different packages. We are still trying to reduce the size by optimizing our build script and hopefully fix this problem. 
After all, thank you so much for your response and have a nice day :)

**Comment by ewdurbin** [comment]
There is a 1.0 GiB overall upload limit for PyPI, a lack of constraints in our admin interface allows setting a higher value but uploads larger than that will not succeed. I've adjusted mindspore and mindspore-dev to match this limit.
