### ISSUE TITLE
Project Limit Request: mindspore, mindspore-dev - 50 GB

### ISSUE THREAD

**Issue by nicholasyanghaoran** [pypa/pypi-support#2325]
### Project URL

https://pypi.org/project/mindspore/ https://pypi.org/project/mindspore-dev/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.
As mentioned in #2324, we are merging our linux packages into one single package for all backends, this leads to an increase in requirements for storage space and thus I would like to ask if you could please increase the size limit of project mindspore and mindspore-dev, the official release and preview release projects for MindSpore.

### How large is each release?

~6 GB total

8 Linux wheels at ~500MB, being x86/arm packages for python 3.7 - 3.10
4 Windows wheels at ~130MB for python 3.7 - 3.10
8 MacOS wheels at ~130MB for x86/arm packages for python 3.7 - 3.10

### How frequently do you make a release?

Roughly once every 3 months

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @nicholasyanghaoran, same comments as the other issue, it really looks like you could improve the scenario by offering downloading the data with an alternative method. But I understand those changes are not done easily, so 
I've set the project limit for `mindspore` and `mindspore-dev` to 50 GB on PyPI. Please be mindful with the releases.
