### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vsalvino** [pypa/pypi-support#2327]
### PyPI Username

`faulkner`

### Reason for request

* Lost access to email address.

FYI - I am submitting this on behalf of @benshayden (https://github.com/benshayden) who is the owner of the `faulkner` account per issue #2303. I have been pestering him about the abandoned `cr` package (#2259) and want to help as much as possible in facilitating a quick resolution.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Confirmation complete. The email address associated with the `faulkner` User on PyPI has been updated. A standard password reset should be sufficient for @benshayden to regain access to their account and do with their projects as they choose.
