### ISSUE TITLE
Issue: Limit Request: pyalink-flink-1.9 - 180MB

### ISSUE THREAD

**Issue by Fanoid** [pypa/pypi-support#233]
Hi, 
I'd like to increate the file size limit to 180MB, as our package includes several large jar files to provide access to Java SDK.

**Project**
pyalink-flink-1.9

**Size of release**
180MB

**Which indexes**
both

**Reasons for the request**
Our package provides Python API for its corresponding Java SDK, which must includes several jar for usage.
This makes our package too large.
So we expect a release size of about 180MB.

**Comment by Fanoid** [comment]
How long does it usually take to increate the limit? Actually this is our first release. Because a release needs to be

**Comment by Fanoid** [comment]
Any updates on this request?

**Comment by pradyunsg** [comment]
Hi @Fanoid! Sorry for the delay -- PyPI is managed and maintained by volunteers so our availability to handle these requests is variable.

I've gone ahead and bumped the upload limit for `pyalink-flink-1.9` to 200 MB on PyPI and TestPyPI. :)

**Comment by Fanoid** [comment]
Thanks for your kindly support!
