### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by victormusembi11** [pypa/pypi-support#2330]
### PyPI Username

vwm11

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
I'm unable to find an account on pypi.org with the username `vwm11`
