### ISSUE TITLE
Project Limit Request: cdktf-cdktf-provider-azurerm - 30 GB

### ISSUE THREAD

**Issue by xiehan** [pypa/pypi-support#2334]
### Project URL

https://pypi.org/project/cdktf-cdktf-provider-azurerm/

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

[CDK for Terraform](https://cdk.tf) is an open source library that allows you to provision infrastructure through Terraform using native programming languages (TypeScript, Python, Java, C# and Go) as an alternative to HCL. CDKTF users can make use of any/all Terraform providers in their projects. As a convenience and performance optimization, we make certain providers available as [pre-built providers](https://developer.hashicorp.com/terraform/cdktf/concepts/providers#install-pre-built-providers), where we generate the bindings for each language ahead of time and publish them as installable packages for users. `cdktf-cdktf-provider-azurerm` is one such package, which essentially wraps the existing [Azure Provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest) with Python bindings to allow it to be used in a CDKTF project.

CDKTF itself has been available in alpha since summer 2020 and went GA on August 1, 2022. We started publishing pre-built providers like `cdktf-cdktf-provider-azurerm` in late 2020. We don't expect individual release sizes to increase significantly in the future, but we do need to be able to continue to publish a weekly release for the foreseeable future, and are currently butting up against the 10GB project size limit.

### How large is each release?

The `.tar.gz` file is about 25MB and the `.whl` is about 26MB in size. The project size is as minimal as can be; we're not aware of any way to significantly reduce the bundle size.

What we have done in the past when we've run into the project size limits is delete older versions; at this point we've already deleted all unpublished versions from before December 2021. We're afraid to delete any more than that because deleting the older packages does potentially block workflows for users using older versions of CDKTF.

### How frequently do you make a release?

We do a release when one of the following is true:
- The underlying Terraform provider is updated, which typically happens once a week
- The CDKTF library is updated, which happens on average once a month

There was previously a bug where a new release would be published anytime _any_ underlying dependency was updated, but [we've fixed that](https://github.com/cdktf/cdktf-provider-project/commit/7efd53d7448b0a6b1d08d9c3d4b44ba47c97b656) within the last couple of weeks so now the above logic will hold true for future releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Note

#2332 and #2333 are nearly identical to this request because we're running into this issue across the board with all of our major pre-built providers. If there is some way to raise the project limit not just for these individual packages but for all projects owned by [cdktf-team](https://pypi.org/user/cdktf-team/), that would be ideal.

**Comment by cmaureir** [comment]
Hello @xiehan :wave: and thanks for the report
I've set the project limit for `cdktf-cdktf-provider-azurerm` to 30 GB on PyPI. 
Have a nice week!
