### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Corvince** [pypa/pypi-support#2336]
### PyPI Username

`corvince`

### Reason for request

I have lost access to my password and email account **for test.pypi.org**. My normal pypi account still works, but I want to reset my test account/ link it to a new email adress. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Email address for `corvince` user on test.pypi.org is now updated to match the email address for the `corvince` user on pypi.org, you can complete a standard password reset ton test.pypi.org to regain access to the account.
