### ISSUE TITLE
PEP 541 Request: topologika

### ISSUE THREAD

**Issue by klacansky** [pypa/pypi-support#2338]
### Project to be claimed

`topologika`: https://pypi.org/project/topologika

### Your PyPI username

`klacansky`: https://pypi.org/user/klacansky

### Reasons for the request

I worked on this library in past; however, I am not sure where it is, and I do not see the project anywhere. I decided to continue the development and upload new version.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

It is the same repository.

https://github.com/sci-visus/topologika

### Contact and additional research

I am the current owner.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by klacansky** [comment]
I moved the repository under our SCI team https://github.com/sci-visus/topologika/tree/persistence.

**Comment by yeraydiazdiaz** [comment]
Hello @klacansky, the project's only release was deleted by the owner PyPI user [n8vm](https://pypi.org/user/n8vm/) which explains why PyPI shows a 404 page.

The owner may be GitHub user @natevm, I'll consider this tag a first reachability attempt of contact.

**Comment by klacansky** [comment]
Thank you, @natevm is part of our research group.

**Comment by klacansky** [comment]
@natevm added me to the project, and I can upload packages. Thanks!
