### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dylancrockett** [pypa/pypi-support#234]
Request for account recovery.

## PyPI Username
`dylancrockett`

---

##  Reason for request
  - Lost 2FA authentication app

Reason:
I have lost access to my device containing my 2FA codes for my pypi due to device damage, and was ignorant to the requirement of recovery codes before this incident. It is unlikely I will be able to recover the device meaning I will have no means of logging into my pypi account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
