### ISSUE TITLE
File Limit Request: kivy-deps.gstreamer - 200 MB

### ISSUE THREAD

**Issue by misl6** [pypa/pypi-support#2342]
### Project URL

https://pypi.org/project/kivy-deps.gstreamer

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The package provides `gstreamer` support for `kivy` (we provide this package only for Windows).
A `gstreamer` build is included in the package we upload on PyPi.

### Reasons for the request

Unfortunately, the newer `gstreamer` release produces an artifact with an additional +40 MB, so we now exceed the 150 MB size limit.

The package size may change ( lower down or increase ) in the future, as the `gstreamer` build may change in size.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @misl6 :wave:
thanks for your report,  I've set the upload limit for `kivy-deps.gstreamer` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!

**Comment by misl6** [comment]
Thank you!
Have a nice week you too!
