### ISSUE TITLE
File Limit Request: Pytonium - 130 MB

### ISSUE THREAD

**Issue by Maximilian-Winter** [pypa/pypi-support#2349]
### Project URL

https://pypi.org/project/Pytonium/

### Does this project already exist?

- [X] Yes

### New Limit

130

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a python framework called Pytonium for building python apps with a GUI, based on the web technologies HTML, CSS and Javascript.

It uses the Chromium Embedded Framework for rendering and execution of javascript.

I bundle the libcef.dll from the Chromium Embedded Framework with the package together with some other necessary files to launch CEF, which is the reason the release is so big. 

At the moment the framework has basic functionality for loading an url and add Javascript bindings, so a python function can be called from Javascript. And also Javascript can be executed, on the website, from python.

It is still at an early stage.

And active since this month.

### Reasons for the request

I bundle the libcef.dll from the Chromium Embedded Framework with the package together with some other necessary files to launch CEF, which is the reason the release is so big.  The dll is 178 mb alone.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Maximilian-Winter :wave:, thanks for the detailed report.
I've set the upload limit for `Pytonium` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by Maximilian-Winter** [comment]
@cmaureir Thank you very much. Just one question because of the frequency. Is it ok to upload a release every 2 weeks, at the beginning and release less frequently later? Or what would be mindful?

**Comment by cmaureir** [comment]
> @cmaureir Thank you very much. Just one question because of the frequency. Is it ok to upload a release every 2 weeks, at the beginning and release less frequently later? Or what would be mindful?

Hey, so it's mainly due to the Project Size limit, which is set initially to 10GB. I guess a release every two weeks can give you a couple of years :)
