### ISSUE TITLE
File Limit Request: bpy - 500 MB

### ISSUE THREAD

**Issue by brechtvl** [pypa/pypi-support#2353]
### Project URL

https://pypi.org/project/bpy

### Does this project already exist?

- [X] Yes

### New Limit

500MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Blender is 3D software with many features. It has not had an official package on pypi yet, but the intent is to have a full featured version available as a Python module, maintained by the Blender Foundation, for use cases such as scientific research, machine learning or web services.

In general we try to keep Blender releases as small as possible, but need to bundle many libraries and binaries for many different GPUs. The size could be reduced by disabling features and reducing GPU hardware support, but for this package to be most useful it should match the functionality of full Blender releases exactly.

There is no example data bundled that takes up significant space.

### Reasons for the request

The current largest package size is 270MB exceeding the current 200MB limit. Requesting 500MB to have some headroom since it will likely increase in the future, though it's hard to predict how much.

There are packages for 4 platforms, currently totaling a bit less than 1GB per release. Releases happen 4 times per year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by engineering9023J** [comment]
@brechtvl Brecht, 
stop making lies about real  Engineering. Stop being a wannabe. You'll never be an engineer, period.
You are not an engineer, never were, and never will be close. Engineering has nothing to do with sitting behind keyboard and writing code. There is no such thing as "software" "engineer". That is the stupidest, most pathetic & disrespectful lie ever. 
Stop being disrespectful to real engineering (mechanical engineering is the ONLY engineering).

Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. 
Software dev is easy and has absolutely nothing to do with engineering, you are just being stupid liars. 
You daft software kiddos will never be engineers, not even close. 

Mechanical Engineering is the ONLY engineering. Period.

**Comment by engineering9023J** [comment]
Brecht van lommel,

Software dev is easy and has absolutely nothing to do with engineering, you are just being stupid liars. 
You daft software kiddos will never be engineers, not even close. 
Mechanical Engineering is the ONLY engineering. Period.

**Comment by cmaureir** [comment]
Thanks for the report @brechtvl :+1: 
I've set the upload limit for `bpy` to 500 MB on PyPI . Please be mindful of the frequency of releases at that size.
Have a nice week!
