### ISSUE TITLE
PEP 541 Request: uwsgi

### ISSUE THREAD

**Issue by xrmx** [pypa/pypi-support#2354]
### Project to be claimed

`PROJECT_NAME`: https://test.pypi.org/project/uwsgi

### Your PyPI username

`USER_NAME`: https://pypi.org/user/xrmx

### Reasons for the request

I'm a maintainer of uwsgi, we have the `uwsgi` on `pypy.org` and would like to push automatically stuff to `test.pypi.org` but here name is not available.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/unbit/uwsgi

### Contact and additional research

Haven't been able to find a contact for the current owner. I think the name has been used as a one-off experiment.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by xrmx** [comment]
Thanks!
