### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by d1manson** [pypa/pypi-support#2356]
### PyPI Username

`d1manson`

### Reason for request

Lost access to email (d****@btinternet.com) and no other users on account for testpypi.python.org.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello. Please contact support@pypi.org referencing this issue to receive information on how to proceed with account recovery.

**Comment by ewdurbin** [comment]
Noted as resolved by submitter.
