### ISSUE TITLE
File Limit Request: HloEnv - 250 MB

### ISSUE THREAD

**Issue by iamohcy** [pypa/pypi-support#2357]
### Project URL

https://pypi.org/project/hloenv/

### Does this project already exist?

- [X] Yes

### New Limit

250

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is HloEnv: A Graph Rewrite Environment for Deep Learning Compiler Optimization Research. It has been under development since Jan 2022, and is slated to be released as open source today concurrently as part of a paper accepted in the ML for Systems workshop in NeurIPS 2022.

The release includes a modified TensorFlow build. 

### Reasons for the request

The size of the file is relatively large as it contains a modified TensorFlow build, as the project makes several modifications to XLA. File sizes should decrease in the future when XLA is decoupled as part of the OpenXLA migration, and we will not have to include an entire tensorflow build.

The current file size is 184 MB, but I have indicated 250 MB to provide a bit more of a buffer as we add more functionality to the library. However if the memory limits are very strict, 200 MB will suffice. 

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the detailed report @iamohcy :rocket: 
I've set the upload limit for `hloenv` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
