### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by poke1024** [pypa/pypi-support#236]
Request for account recovery.

## PyPI Username

`poke1024`

##  Reason for request

see https://github.com/pypa/pypi-support/issues/153

I cannot receive any emails, including passwort reset emails.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@poke1024 checking in, have you received the email sent to your gme account? it was not sent via the same mail service as pypi and I haven't received a bounce.

**Comment by poke1024** [comment]
@ewdurbin I received the mail, but failed to see it at the time, and now the token is expired. Sigh.

**Comment by ewdurbin** [comment]
@poke1024 what token?

**Comment by poke1024** [comment]
I received a mail von March 14th, that obviously is now expired:

<img width="1017" alt="Bildschirmfoto 2020-03-31 um 12 40 54" src="https://user-images.githubusercontent.com/11859538/78017684-ef6f9f00-734c-11ea-9f42-074893ed889d.png">

**Comment by ewdurbin** [comment]
Oh, that was not the account recovery attempt I emailed you about. That is a valid password reset delivered by PyPI then.

Might be worth attempting another password reset to see if the mail is able to deliver now.

**Comment by poke1024** [comment]
Just triggered another reset, no email so far.

**Comment by poke1024** [comment]
Oh, wow I received, yes finally. :smiley:
