### ISSUE TITLE
File Limit Request: CocCocTokenizer - 200 MB

### ISSUE THREAD

**Issue by trituenhantaoio** [pypa/pypi-support#2361]
### Project URL

https://pypi.org/project/CocCocTokenizer/

### Does this project already exist?

- [X] Yes

### New Limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a Cython project for a Vietnamese tokenizer.

### Reasons for the request

Since the data must come with the tokenizer, we exceed the size limit.

We appreciate your help in advance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @trituenhantaoio :wave:
thanks for the report.  I've set the upload limit for `CocCocTokenizer` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by trituenhantaoio** [comment]
Many thanks for the prompt support. It worked perfectly now!
