### ISSUE TITLE
Project Limit Request: vtk - 50 GB

### ISSUE THREAD

**Issue by banesullivan** [pypa/pypi-support#2367]
### Project URL

https://pypi.org/project/vtk/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The Visualization Toolkit (VTK) is open source C++ software for manipulating and displaying scientific data with Python bindings published as wheels on PyPI. VTK is a popular library for 3D visualization and has been releasing on PyPI for several years now (since ~2018) though the project has seen over 25 years of continuous development. The project is one of the most widely used libraries for 3D visualization in Python with countless downstream dependencies and wrappings (see [PyVista](https://pypi.org/project/pyvista/), [vedo](https://pypi.org/project/vedo/), [Mayavi](https://pypi.org/project/mayavi/), [MNE](https://pypi.org/project/mne/), and many more.

VTK is exceeding the current limit and having to make sacrifices on which platforms we upload wheels for as well as having to remove older releases and release candidates to make room for new ones.

cc'ing some of the maintainers of the wheel and downstream projects that would benefit from this size increase: @mathstuf, @jcfr, @larsoner, @akaszynski

Please note that I am not listed as a maintainer of the wheel but that I am an employee of Kitware and representing Kitware in this request. For confirmation from a listed maintainer of the PyPI project, please ping @mathstuf

### How large is each release?

Each wheel is between ~50-70 Mb and we support the following matrix:

Python: 3.7, 3.8, 3.9, 3.10, (and soon 3.11 if we can get more space)
Architectures: `manylinux2014_x86_64`, `macosx_11_0_arm64`, `macosx_10_10_x86_64`, `win_amd64`

The latest release (9.2.2) was ~1GB for that matrix,

### How frequently do you make a release?

VTK has a target release cycle of every 6 months with 3-4 release candidates and 2-3 patches.  It took ~4 years of releases to reach the current limit. We are currently around 1GB per release (50-80 MB / wheel), so could easily grow by 3-5 GB / year going forward.

I have requested an increase in total space to at least 50 GB which should be sufficient for the next few years. After which, we could more comfortably remove older wheels to make space if needed. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Thanks for filing this issue and for properly filling in the information requested in the template! :)

I've gone ahead and bumped the limit to 50 GB. Please be mindful of the frequency of releases at your current release sizes.
