### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by symonk** [pypa/pypi-support#2368]
### PyPI Username

`simonk`

### Reason for request

Quite a while back I damaged my phone to the point of no repair accidentally, however I had a google authenticator app on the phone that had auth codes for my pypi.org account.  Would you be able to assist me with removing that so I can add the authenticator I have on my new device?  I need to deploy new releases of existing libraries and publish some new ones.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
