### ISSUE TITLE
PEP 541 Request of package transfer 'SLOTH'

### ISSUE THREAD

**Issue by Legorooj** [pypa/pypi-support#237]
# Project
* `SLOTH`: https://pypi.org/project/SLOTH

## PyPI username
* `Legorooj`: https://pypi.org/user/Legorooj/

## Purpose
 
I'd like to publish a speedtesting library called `sloth`. (Feedback on the name is welcome 😄)

I decided to check PyPI for the name of course, and found the above library. I'd like the project name transferred to my account so I can delete the project and recreate it (Does uppercase/lowercase make a diff?)

The project has been inactive since July 2012, and the user hasn't had any activity since then. I've not tried to contact the user because I can't find an email address. 

Could this be transferred?

(PS I'd like it transferred so I can delete it when I have time to reclaim the name straight away - do you guys know how long it will take for a deleted package name to be free for use again?)

**Comment by hugovk** [comment]
> Does uppercase/lowercase make a diff?

No. 

> I've not tried to contact the user because I can't find an email address.

There's an email at https://pypi.org/project/SLOTH/, linked from "Author: M.Kauer".

> do you guys know how long it will take for a deleted package name to be free for use again?

The PEP requires PyPI maintainers to attempt at least 3 times over 6 weeks, see https://www.python.org/dev/peps/pep-0541/

**Comment by Legorooj** [comment]
@hugovk I didn't see that email. I'll send one to him now. Hmm maybe I'll just edit/manage the project and do it that way.

**Comment by Legorooj** [comment]
@hugovk K message sent. I'll let you know if he responds by Tuesday.

**Comment by Legorooj** [comment]
@hugovk I'm going to close this issue. If I can't get it under the name `sloth` from the current holder of said name, I'll put it on under `sloth-speedtest`.

**Comment by Legorooj** [comment]
@hugovk I've changed my mind due to the following:

```
This is the mail system at host zimbra-srv1.mpi-cbg.de.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<kauer@mpi-cbg.de>: mpi-cbg.de
----------------------------------------------
message/delivery-status
----------------------------------------------
Reporting-MTA: dns; zimbra-srv1.mpi-cbg.de
X-Postfix-Queue-ID: 8B478940142
X-Postfix-Sender: rfc822; legorooj@protonmail.com
Arrival-Date: Sun, 1 Mar 2020 00:31:51 +0100 (CET)

Final-Recipient: rfc822; kauer@mpi-cbg.de
Original-Recipient: rfc822;kauer@mpi-cbg.de
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; mpi-cbg.de
```

You'll see on the second last line, `Status: 5.0.0`. thats SMTP for address doesn't exist, meaning that this person probably doesn't work there anymore (they are a Uni in Germany).

Could we get this project transferred to my account?

PS that is a trimmed version of the message. If you'd like the full one, post your email.

**Comment by Legorooj** [comment]
Unless you have other contact details on the system @di

**Comment by hugovk** [comment]
I believe this is the same person and there's an email on this page:

https://biophysics.uchicago.edu/the-students/monika_kauer/

**Comment by Legorooj** [comment]
Almost definitely (I suspected her name was Monika because I searched the old email site for "Kauer" and one paper came up, with an author Monika Kauer). I'll send her an email through that adress and get back to you.

**Comment by Legorooj** [comment]
@hugovk thanks for your help. I got a reply this time, and this was the right person. They'd like to keep the library as it is, because they have a paper that references it. Thanks though!

**Comment by hugovk** [comment]
You're welcome! That sounds very reasonable, glad you got it sorted :)
