### ISSUE TITLE
PEP 541 Request: django-uwsgi-admin

### ISSUE THREAD

**Issue by ionelmc** [pypa/pypi-support#2373]
### Project to be claimed

`django-uwsgi-admin`: https://pypi.org/project/django-uwsgi-admin

### Your PyPI username

`ionel`: https://pypi.org/user/ionel

### Reasons for the request

I would like to take over this name since it's 100% dead and forgotten - 12 years is enough. My goal is to start maintaining a fork of https://github.com/unbit/django-uwsgi (another dead-ish project, but only dead for 2 years) under the django-uwsgi-admin name.

I think this is a reasonable request.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The project will be maintained at https://github.com/ionelmc/django-uwsgi-admin 

### Contact and additional research

django-uwsgi-admin was long dead, that's why unbit made releases under the django-uwsgi name 

django-uwsgi-admin's release doesn't have any contact info (they just copied unbit's email), thus I don't have any way to contact whoever made that release 12 years ago.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @ionelmc, I will now start the reachability process for your request which can take up to 6 weeks. Hopefully we will hear back from the owner soon and proceed with the transfer.

**Comment by phretor** [comment]
@yeraydiazdiaz: LGTM - please hand it over to @ionelmc

**Comment by yeraydiazdiaz** [comment]
Thanks for your quick reply @phretor, transfer complete.
