### ISSUE TITLE
Project Limit Request: torch-mlir - 200 GB

### ISSUE THREAD

**Issue by dellis23** [pypa/pypi-support#2374]
### Project URL

https://pypi.org/manage/project/torch-mlir/

### Does this project already exist?

- [X] Yes

### New limit

200

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

`torch-mlir` is an llvm project that enables users to compile PyTorch models to MLIR. `torch-mlir` depends on C++ libraries that are included as part of its wheel to be able to provide maximum compatibility flexibility for the end users.  

The project has been active for years.

We expect sizes to increase in the future as LLVM and IREE itself are large.  We publish nightlies that are large in size and will eat up our project limit quickly.

### How large is each release?

Each release is >200MB right now.  We've tried to lower the file size by not running audit wheel, but we're then unable to publish.  `torch-mlir` depends on C++ libraries that are included as part of its wheel to be able to provide maximum compatibility flexibility for the end users.  

### How frequently do you make a release?

Nightly.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the report @dellis23 :+1: 
I've set the project limit for `torch-mlir` to 200 GB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
