### ISSUE TITLE
PEP 541 Request: opensearch-py-ml

### ISSUE THREAD

**Issue by dhrubo-os** [pypa/pypi-support#2379]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/opensearch-py-ml

### Your PyPI username

`USER_NAME`: https://pypi.org/user/OpenSearch

### Reasons for the request

We are from OpenSearch team. We recently made our [Opensearch-py-ml](https://github.com/opensearch-project/opensearch-py-ml/) github repo public and we are in the process of releasing our package to Pypi. 

But today we found that somebody intentionally uploaded a package with the same name `opensearch-py-ml` in [pypi](https://pypi.org/project/opensearch-py-ml/). But unfortunately this package doesn't have anything related to opensearch. In addition provided contact information is also not valid. So we don't have any way to reach out.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/opensearch-project/opensearch-py-ml/

### Contact and additional research

```
    author="Aloneee walker",
    author_email="aloneewalker@facebook.com",
```

This is the contact is given but all these information is fake. The email is not a valid email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @dhrubo-os, it seems `OpenSearch` is already the owner so no transfer is possible.
