### ISSUE TITLE
Issue: PEP 541 Request: bus

### ISSUE THREAD

**Issue by CoburnJoe** [pypa/pypi-support#238]
**Project to be claimed**
`bus`: https://pypi.org/project/bus/

**Your PyPI username**
`CoburnJoe`: https://pypi.org/user/CoburnJoe

**Reasons for the request**
This project returns a 404 - there are no published packages for it, so it's either been deleted or someone is squatting on it.

**Maintenance or replacement?**
I'd like to publish a brand new (different) project - a JSON HTTP aggregator. https://github.com/CoburnJoe/bus

**Contact and additional research**
I cannot find the original owner - either through PyPi or GitHub. I don't think this is a project and can't find any projects that seem remotely close to that name.

**Comment by jamadden** [comment]
That project was originally created, and them immediately removed, by @prologic back in 2013. Hopefully @prologic can respond to this issue and ideally transfer the name so we don't have to go through the admin transfer process for an invalid project.

**Comment by prologic** [comment]
> That project was originally created, and them immediately removed, by @prologic back in 2013. Hopefully @prologic can respond to this issue and ideally transfer the name so we don't have to go through the admin transfer process for an invalid project.

Sorry I did what now? :) I'd love to help but I'm a bit out of context! How can I help?

**Comment by prologic** [comment]
Oh you want https://pypi.org/project/bus/ ?

Sure I can give that tup :) How do I do this?

**Comment by hugovk** [comment]
Like [this](https://github.com/pypa/warehouse/issues/1745#issuecomment-280370719):

["Your Projects"](https://pypi.org/manage/projects/) > (project name) > "Manage" > "Collaborators" > Add

**Comment by prologic** [comment]
Can I just delete the project and let you re-create it?

<img width="806" alt="Screen Shot 2020-03-07 at 12 08 49" src="https://user-images.githubusercontent.com/1290234/76134748-72fae080-606c-11ea-8bc9-cdddaab92d22.png">

**Comment by CoburnJoe** [comment]
@jamadden please can you advise?

**Comment by yeraydiazdiaz** [comment]
@prologic, we prefer you adding @CoburnJoe as an owner to ensure that there is no window of opportunity for other users to claim the project.

**Comment by prologic** [comment]
Okay I'll do this now Thanks!

**Comment by prologic** [comment]
Done. Feel free to remove me as Owner.

<img width="1312" alt="Screen Shot 2020-03-20 at 08 30 14" src="https://user-images.githubusercontent.com/1290234/77120630-0f69ad80-6a85-11ea-9fd4-59ec267bca5a.png">

**Comment by yeraydiazdiaz** [comment]
Thank you @prologic.

**Comment by CoburnJoe** [comment]
@prologic thank you so much

**Comment by prologic** [comment]
Your welcome!
