### ISSUE TITLE
File Limit Request: `cutensor-cu11` - 200 MB

### ISSUE THREAD

**Issue by leofang** [pypa/pypi-support#2385]
### Project URL

https://pypi.org/project/cutensor-cu11/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

cuTENSOR is an NVIDIA GPU library. In an effort to reduce wheel size and align with other NVIDIA products, we plan to migrate from the existing [`cutensor`](https://pypi.org/project/cutensor) wheel to `cutensor-cu11` wheel, as the former would go beyond 350 MB per wheel for future releases (since it needs to support all CUDA 10.2, 11.0, 11.x, and future CUDA users), while the latter would only support 11.x users. 

However, despite our best effort to reduce the wheel size, we still need to go beyond a bit the default limit, hence this request. We are currently blocked from uploading new releases, and we would appreciate if this request can be addressed promptly.

Thank you!

### Reasons for the request

It could be possible that the `cutensor-cu11` wheel would go beyond 200 MB per wheel in the future, when we need to support more GPU architectures and/or provide more GPU functionalities. However, the growth is currently not predictable, as we are also investigating internally more aggressive approaches for binary size reduction. We are hoping to make best effort to stay within the new limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @leofang :wave:
Thanks for your report, I've set the upload limit for `cutensor-cu11` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!

**Comment by leofang** [comment]
Thank you very much Cristián, I confirm the limit is bumped 🙂
