### ISSUE TITLE
File Limit Request: pytorch-san - 400 MB

### ISSUE THREAD

**Issue by Kristoff-starling** [pypa/pypi-support#2386]
### Project URL

https://test.pypi.org/project/pytorch-san/

### Does this project already exist?

- [X] Yes

### New Limit

400

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

The project will contain a PyTorch package that is built with sanitizers. (Currently the 0.0.2 version is just a dummy release, which is used to create the project.)

### Reasons for the request

The PyTorch package with sanitizers is useful for bug reproduction and debugging when communicating with PyTorch developers. However, the `.whl` file generated is about 360MB in size, that's why I want to request a 400MB per file size for this project.
The package is only used for bug reproduction, that's why I upload it on testpypi. 
Thanks a lot!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Kristoff-starling :wave:
Thanks for the detailed report, I've set the upload limit for `pytorch-san` to 400 MB on TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
