### ISSUE TITLE
Project Limit Request: apache-beam - 20 GB

### ISSUE THREAD

**Issue by chamikaramj** [pypa/pypi-support#2389]
### Project URL

https://pypi.org/project/apache-beam/

### Does this project already exist?

- [X] Yes

### New limit

20

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Apache Beam is released approximately every 6 weeks and current release's PyPI artifacts are about 223 MB.

Appreciate if project size limit can be increased to 20 GB.

We are trying to release a new version of Apache Beam and running into the following error.

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                         
         Project size too large. Limit for project 'apache-beam' total size is 10 GB. See https://pypi.org/help/#project-size-limit

### How large is each release?

~ 223 MB total

12 linux wheels ~ 165 MB
12 Windows/MacOS wheels ~ 55 MB
The source tarball at ~ 3 MB

### How frequently do you make a release?

Roughly every 6 weeks.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @chamikaramj :wave:
Thanks for the detailed explanation on the wheel sizes.
I've set the project limit for `aoache-beam` to 20 GB on PyPI.
Cheers

**Comment by chamikaramj** [comment]
Thanks you for the quick turnaround.
