### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bryanwweber** [pypa/pypi-support#239]
Request for account recovery.

## PyPI Username

`bryanwweber`

---

##  Reason for request

Reason: Lost access to 2FA authentication app. My phone suddenly died and I neglected to create recovery codes. Thank you for your help!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by bryanwweber** [comment]
Thank you!
