### ISSUE TITLE
File Limit Request: intel-extension-for-tensorflow-lib - 400 MB

### ISSUE THREAD

**Issue by ashahba** [pypa/pypi-support#2392]
### Project URL

https://pypi.org/project/intel-extension-for-tensorflow-lib/
https://test.pypi.org/project/intel-extension-for-tensorflow-lib/

### Does this project already exist?

- [X] Yes

### New Limit

400MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

This is an `Intel` owned project that we are planning to release in the next few weeks as part of our TensorFlow Optimizations and it'll be owned and maintained by this user: https://pypi.org/user/IntelAI/

### Reasons for the request

As of now the wheels are around 350MB in size and being rejected during upload due to larger than the current size limit which is at 250MB

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks @ashahba for the report :+1: 
I've set the upload limit for `intel-extension-for-tensorflow-lib` to 400 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
Have a nice week!
