### ISSUE TITLE
File Limit Request: fastdeploy-python - 300 MB

### ISSUE THREAD

**Issue by Zeref996** [pypa/pypi-support#2393]
### Project URL

~https://github.com/PaddlePaddle/FastDeploy~
https://pypi.org/project/fastdeploy-python/

### Does this project already exist?

- [X] Yes

### New Limit

300 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

fastdeploy-python 0.1.0   Released: Jun 27, 2022
FastDeploy is an Easy-to-use and High Performance AI model deployment toolkit for Cloud, Mobile and Edge with 📦out-of-the-box and unified experience, 🔚end-to-end optimization for over 🔥150+ Text, Vision, Speech and Cross-modal AI models. Including image classification, object detection, image segmentation, face detection, face recognition, keypoint detection, matting, OCR, NLP, TTS and other tasks to meet developers' industrial deployment needs for multi-scenario, multi-hardware and multi-platform

### Reasons for the request

We will release a new version for fastdeploy-python recently. Our current size limit is less than 200 M, and the dev version is almost 300M. Because some new features are enabled in this version, so the size increase. Can you please help to increase this to around 300MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @Zeref996 thanks for the report.
The project doesn't exist on test.pypi.org so I've just set the upload limit for `fastdeploy-python` to 300 MB on PyPI.
In case you create the test.pypi.org project, feel free to open a new issue referencing this one. Please be mindful of the frequency of releases at that size.
Have a nice week
