### ISSUE TITLE
File Limit Request: imojify- 142MB

### ISSUE THREAD

**Issue by abdulrahmankhayal** [pypa/pypi-support#2414]
### Project URL

https://pypi.org/project/imojify/

### Does this project already exist?

- [X] Yes

### New Limit

150

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

its a small python library that maps almost every emoji-unicode to its color image
it's my first release

### Reasons for the request

the project need thousands of images in order to perform its job 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks @abdulrahmankhayal for the report :+1: 
I've set the upload limit for `imojify` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
