### ISSUE TITLE
Project Limit Request: polars - 50 GB

### ISSUE THREAD

**Issue by ritchie46** [pypa/pypi-support#2419]
### Project URL

https://pypi.org/project/polars/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Polars is a dataframe library that is a more performant alternative to pandas.

### How large is each release?

We have removed older releases and are (almost) hitting the 10GB limit.

These are the current binary sizes per release:

```
polars-0.14.29.tar.gz (1.2 MB [view hashes](https://pypi.org/project/polars/#copy-hash-modal-d3d62afe-2d2c-4c70-a27f-8230883b8fdf))

Uploaded Nov 18, 2022 source
Built Distributions
polars-0.14.29-cp37-abi3-win_amd64.whl (14.9 MB [view hashes](https://pypi.org/project/polars/#copy-hash-modal-2a732730-0555-4e2f-b4da-2260b801cfb2))

Uploaded Nov 18, 2022 cp37
polars-0.14.29-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB [view hashes](https://pypi.org/project/polars/#copy-hash-modal-f7b30be6-b3e4-4076-9ca0-23a9ee44da5c))

Uploaded Nov 18, 2022 cp37
polars-0.14.29-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (12.3 MB [view hashes](https://pypi.org/project/polars/#copy-hash-modal-aad6bbce-afc0-48e4-a096-07bd035400df))

Uploaded Nov 18, 2022 cp37
polars-0.14.29-cp37-abi3-macosx_11_0_arm64.whl (11.9 MB [view hashes](https://pypi.org/project/polars/#copy-hash-modal-a1c3dcda-ddcf-4dd6-bf80-3ded67cc586a))

Uploaded Nov 18, 2022 cp37
polars-0.14.29-cp37-abi3-macosx_10_7_x86_64.whl (13.3 MB [view hashes](https://pypi.org/project/polars/#copy-hash-modal-edb0887f-b4b3-4fd6-ac4d-9740341def4e))
```

### How frequently do you make a release?

We develop rapidly and ship every week.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the report @ritchie46 :+1: 
I've set the project limit for `polars` to 50 GB on PyPI.
have a nice week!

**Comment by ritchie46** [comment]
Thanks! :)
