### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vreis** [pypa/pypi-support#242]
Request for account recovery.

## PyPI Username

vreis

---

##  Reason for request

Reason:
I had 2fac setup through Google Authenticator on my phone. My phone's screen stopped working (hardware failure), so I had to switch to a new phone without the chance of a proper backup/migration. I lost all my Google Authenticator codes. Most other websites allow me to use 2fac via SMS, so that hasn't been an issue. But looks like that's not available for PyPI, and I never generated recovery codes. I manage an OSS project (https://github.com/facebookresearch/ClassyVision) and we need my account to upload our 0.3 release. Let me know if there's any other information you need. Thanks!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
