### ISSUE TITLE
File Limit Request: xFormers - 300 MB

### ISSUE THREAD

**Issue by danthe3rd** [pypa/pypi-support#2421]
### Project URL

https://pypi.org/project/xformers/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

xFormers contains efficient components for PyTorch users - https://github.com/facebookresearch/xformers
The size comes from the multiple CUDA kernels (binaries) that are shipped with the project, built for multiple GPU architectures.
(The wheels available on pypi at the moment are outdated due to size limits reached)

cc @fmassa @bottler

### Reasons for the request

We are currently using conda for our releases, and the binary size is right above 100MB, which prevents us from uploading wheels to pypi:
https://anaconda.org/xformers/xformers/files

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
thanks for the  report @danthe3rd :+1: 
I've set the upload limit for `xFormers` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice day!
