### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tdousset** [pypa/pypi-support#2433]
### PyPI Username

tdousset

### Reason for request

I'm not certain which email address this was under. It doesn't seem to be any of my usual ones. Hopefully not an ex-employer.

tim@dousset.id.au current email.

I'd like the username back so I can upload a package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, the email has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
