### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Adonai-ai** [pypa/pypi-support#244]
Request for account recovery.

## PyPI Username

`Adonai`

---

##  Reason for request

Reason:
 - Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Adonai-ai** [comment]
> Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

ewdurbin@gmail.com

**Comment by ewdurbin** [comment]
@Adonai-ai no, an email was sent to the primary email address associated with the account with the subject “PyPI Account Recovery Request: Adonai” please respond there.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
