### ISSUE TITLE
Project Limit Request: Scikit-learn - 20 GB

### ISSUE THREAD

**Issue by jeremiedbb** [pypa/pypi-support#2441]
### Project URL

https://pypi.org/project/scikit-learn/

### Does this project already exist?

- [X] Yes

### New limit

20 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Scikit-learn is a 12 years old reference package for machine learning in Python.

### How large is each release?

~ 350 MB total for approx 20 wheels for many platforms (linux, macos, windows, arm)

### How frequently do you make a release?

A major release every 6 month, with 2 or 3 minors in between so around 5 per year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jeremiedbb** [comment]
I edited to a 20 GB request because it should give us ~5 years before we reach this limit.

**Comment by cmaureir** [comment]
Hey @jeremiedbb :wave:
thanks for the report. 
I've set the project limit for `scikit-learn` to 20 GB on PyPI.
have a nice week!

**Comment by jeremiedbb** [comment]
Thanks a lot !
Have a nice week as well
