### ISSUE TITLE
File Limit Request: deeprtalign - 200 MB

### ISSUE THREAD

**Issue by FineLiu** [pypa/pypi-support#2442]
### Project URL

https://pypi.org/project/deeprtalign/

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

DeepRTAlign is a retention time alignment tool for large cohort LC-MS data analysis, first released in Dec 30, 2021. 
We use a larger neural network in the new version with a much larger parameter file (191M) than before.  After compression, the installation file is 174MB.

### Reasons for the request

We use a larger neural network in the new version with a much larger parameter file (191M) than before. After compression, the installation file is 174MB. The current neural network is large enough, and the possibility of further increase in the future is very small. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @FineLiu :wave:
I've set the upload limit for `deeprtalign` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice week!
