### ISSUE TITLE
Mass name squat by user: david-aws

### ISSUE THREAD

**Issue by wistuba** [pypa/pypi-support#2444]
### PyPI user performing the mass project name squatting

https://pypi.org/user/david-aws

### Additional information

User keeps claiming AWS related projects. Apparently the user monitors AWS repositories and as soon as a repo goes public, this user tries to claim the project name for himself. None of his projects contain code.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Closing as duplicate of https://github.com/pypa/pypi-support/issues/2171
