### ISSUE TITLE
File Limit Request: vdtk - 700 MB

### ISSUE THREAD

**Issue by DavidMChan** [pypa/pypi-support#2446]
### Project URL

https://pypi.org/project/vdtk/

### Does this project already exist?

- [X] Yes

### New Limit

700

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a project that packages several tools in a common (python) interface for the automated evaluation of visual description models. Most of these tools are originally java or perl code, which means that we have to bundle some depndencies in other languages, which are then exposed to python.  To maintain parity with some other individual tools, we need to include several java libraries, particularly among them, stanford's corenlp models library, which ships at ~379 MB. This is the largest file in the release, and accounts for the vast majority of the total release size ~521MB.  We also must ship several other large jar files, and three core model data files which represent a fair amount of the remainder of the package size. We could package these files separately, and allow users to download the checkpoints (such as the vendored 3p repositories), but this can decrease the user experience, particularly for a tool which is designed to make evaluation easier for scientists.

### Reasons for the request

From above, to maintain parity with some other individual tools, we need to include a java lilbrary, stanford's corenlp models library, which ships at ~379 MB. This is the largest file in the release, and accounts for the vast majority of the total release size ~578MB.  

We don't expect that the size of the whl will increase dramatically at any point in the future (as this dependency is fixed), and we don't currently intend to bundle any additional java packages/checkpoint files.

---

Full file list:
Archive:  vdtk-0.3.0-py3-none-any.whl
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
       5  Defl:N        7 -40% 2022-11-29 20:40 31d019d8  vdtk-0.3.0.dist-info/top_level.txt
       7  Defl:N        9 -29% 2022-11-09 22:17 9c10b948  vdtk/metrics/cider/.gitignore
      12  Defl:N       14 -17% 2022-11-10 18:48 0b6bb99e  vdtk/metrics/spice/.gitignore
      20  Defl:N       22 -10% 2022-11-29 18:07 b4c7525e  vdtk/third_party/clip/clip/__init__.py
      21  Defl:N       23 -10% 2022-11-11 20:07 9b968ffe  vdtk/metrics/tokenizer/__init__.py
      21  Defl:N       23 -10% 2022-11-11 20:07 a3fe0e8d  vdtk/metrics/bleu/__init__.py
      21  Defl:N       23 -10% 2022-11-11 20:07 a3fe0e8d  vdtk/metrics/cider/__init__.py
      21  Defl:N       23 -10% 2022-11-11 20:07 a3fe0e8d  vdtk/metrics/meteor/__init__.py
      22  Defl:N       21   5% 2022-11-10 18:53 ac9c540c  vdtk/metrics/corenlp/.gitignore
      23  Defl:N       25  -9% 2022-11-11 20:07 cb878f06  vdtk/metrics/rouge/__init__.py
      38  Defl:N       36   5% 2022-11-29 20:40 cdd26b6a  vdtk-0.3.0.dist-info/entry_points.txt
      41  Defl:N       36  12% 2022-11-10 19:12 30ff1861  vdtk/metrics/corenlp/lib/.gitattributes
      76  Defl:N       68  11% 2022-11-10 17:44 3027b168  vdtk/metrics/corenlp/__init__.py
      92  Defl:N       92   0% 2022-11-29 20:40 ee31a5a1  vdtk-0.3.0.dist-info/WHEEL
     138  Defl:N      106  23% 2022-11-29 19:42 c2b5b094  vdtk/third_party/bleurt/bleurt/test_checkpoint/bleurt_config.json
     220  Defl:N      106  52% 2022-11-11 20:08 9c55d7c6  vdtk/metrics/distribution/kbm/__init__.py
     246  Defl:N      110  55% 2022-11-11 22:59 fdea6395  vdtk/metrics/distribution/__init__.py
     286  Defl:N      163  43% 2022-11-29 19:42 b611b1fe  vdtk/third_party/bleurt/bleurt/test_checkpoint/bert_config.json
     349  Defl:N      194  44% 2022-11-29 19:51 812d4d61  vdtk/third_party/__init__.py
     391  Defl:N      204  48% 2022-11-11 20:08 2a47ad10  vdtk/metrics/distribution/distance/__init__.py
     438  Defl:N      228  48% 2022-11-11 23:51 e7a1a227  vdtk/metrics/distribution/distance/rouge.py
     458  Defl:N      243  47% 2022-11-11 23:51 5fe70fe1  vdtk/metrics/distribution/distance/meteor.py
     491  Defl:N      273  44% 2022-11-29 18:07 e56671b3  vdtk/third_party/clip/setup.py
     615  Defl:N      391  36% 2022-11-29 19:42 168d85af  vdtk/third_party/bleurt/bleurt/__init__.py
     616  Defl:N      392  36% 2022-11-29 19:42 74a8356f  vdtk/third_party/bleurt/bleurt/lib/__init__.py
     616  Defl:N      392  36% 2022-11-29 19:42 74a8356f  vdtk/third_party/bleurt/bleurt/wmt/__init__.py
     621  Defl:N      365  41% 2022-08-01 16:05 9442b34f  vdtk/assets/coco_labels.txt
     683  Defl:N      378  45% 2022-11-29 19:44 a05fbd9d  vdtk/metrics/distribution/distance/bleurt.py
     727  Defl:N      313  57% 2022-11-11 20:52 09dfdba1  vdtk/utils/rich.py
     776  Defl:N      465  40% 2022-11-10 17:45 85b003f3  vdtk/__init__.py
     812  Defl:N      380  53% 2022-11-29 18:18 5cf58ae2  vdtk/third_party/clip/tests/test_consistency.py
     837  Defl:N      294  65% 2022-11-11 23:47 c007a2ab  vdtk/metrics/distribution/distance/cider.py
     915  Defl:N      347  62% 2022-11-11 20:35 70db4624  vdtk/stats_utils.py
     998  Defl:N      902  10% 2022-11-29 19:42 3ffe5e08  vdtk/third_party/bleurt/bleurt/test_checkpoint/variables/variables.index
    1081  Defl:N      620  43% 2022-11-29 20:40 45b07bc2  vdtk-0.3.0.dist-info/LICENSE
    1105  Defl:N      657  41% 2022-08-01 16:05 0af021ee  vdtk/metrics/bleu/LICENSE
    1173  Defl:N      421  64% 2022-11-29 17:55 f79b7fcd  vdtk/utils/nlp.py
    1274  Defl:N      480  62% 2022-11-11 20:28 fb7af37f  vdtk/cli.py
    1382  Defl:N      644  53% 2022-11-29 18:07 7ff1baf8  vdtk/third_party/clip/hubconf.py
    1611  Defl:N      693  57% 2022-11-11 21:59 8f84b7bd  vdtk/metrics/bleu/bleu.py
    1653  Defl:N      659  60% 2022-11-09 21:21 79460f7e  vdtk/metrics/distribution/distance/normalize.py
    1700  Defl:N      655  62% 2022-11-12 00:00 51d3d763  vdtk/lm.py
    1709  Defl:N      602  65% 2022-11-11 23:52 a174e5ef  vdtk/metrics/distribution/distance/bert.py
    1731  Defl:N      680  61% 2022-11-09 21:28 3c741ebe  vdtk/metrics/distribution/kbm/emd.py
    1820  Defl:N      731  60% 2022-11-12 00:07 29733b69  vdtk/metrics/distribution/kbm/fid.py
    1987  Defl:N      941  53% 2022-11-29 19:42 a860f67c  vdtk/third_party/bleurt/setup.py
    2193  Defl:N     1008  54% 2022-11-29 19:42 ae08f5ff  vdtk/third_party/bleurt/bleurt/score_not_eager_test.py
    2770  Defl:N     1061  62% 2022-11-29 19:42 e2a435df  vdtk/third_party/bleurt/bleurt/lib/tokenizers.py
    3106  Defl:N     1171  62% 2022-11-29 19:42 3aa90cec  vdtk/third_party/bleurt/bleurt/lib/experiment_utils.py
    3183  Defl:N     1065  67% 2022-11-29 19:42 4df23905  vdtk/third_party/bleurt/bleurt/score_test.py
    3580  Defl:N     1386  61% 2022-11-29 19:42 d321983d  vdtk/third_party/bleurt/bleurt/wmt/benchmark.py
    3715  Defl:N      975  74% 2022-11-11 20:34 482acbc2  vdtk/caption_metrics.py
    3816  Defl:N     1724  55% 2022-08-01 16:05 27de03e9  vdtk/assets/places_labels.txt
    3818  Defl:N     1324  65% 2022-11-12 01:00 b530f84d  vdtk/metrics/spice/spice.py
    3821  Defl:N      997  74% 2022-11-12 00:08 3d2acdd8  vdtk/metrics/distribution/trm.py
    3833  Defl:N     1261  67% 2022-11-12 00:35 dfe14de0  vdtk/ngram_metrics.py
    3991  Defl:N     1427  64% 2022-11-29 19:42 d3f146c9  vdtk/third_party/bleurt/bleurt/length_batching_test.py
    4006  Defl:N     1091  73% 2022-11-11 23:47 e219b0ab  vdtk/metrics/cider/cider.py
    4014  Defl:N     1445  64% 2022-11-29 19:42 069597fc  vdtk/third_party/bleurt/bleurt/finetune.py
    4142  Defl:N     1212  71% 2022-11-12 00:11 bb09beb3  vdtk/semantic_variance.py
    4211  Defl:N      968  77% 2022-11-29 17:48 733d171d  vdtk/data_utils.py
    4358  Defl:N     1210  72% 2022-11-11 20:47 bebc3b69  vdtk/metrics/tokenizer/ptbtokenizer.py
    4393  Defl:N     1500  66% 2022-11-12 00:00 f777eabd  vdtk/metrics/distribution/utils/progress.py
    4632  Defl:N     1724  63% 2022-11-29 18:07 23e24e36  vdtk/third_party/clip/clip/simple_tokenizer.py
    4788  Defl:N     1708  64% 2022-11-12 00:41 6e755bd5  vdtk/core_set.py
    4920  Defl:N     1271  74% 2022-11-29 19:42 fe1d830f  vdtk/third_party/bleurt/bleurt/finetune_test.py
    5115  Defl:N     1826  64% 2022-11-11 20:08 81e773b9  vdtk/metrics/distribution/distance/bleu.py
    5318  Defl:N     1520  71% 2022-11-12 00:29 dbadc2ec  vdtk/qualitative_sample.py
    5350  Defl:N     1711  68% 2022-11-12 00:29 2ac3c854  vdtk/leave_one_out.py
    5791  Defl:N     1421  76% 2022-11-11 22:08 9e7790fc  vdtk/metrics/meteor/meteor.py
    5956  Defl:N     2437  59% 2022-08-01 16:05 ed29475a  vdtk/assets/kinetics_400_labels.txt
    6125  Defl:N     2066  66% 2022-11-29 19:42 d09588f6  vdtk/third_party/bleurt/bleurt/score_files.py
    6287  Defl:N     2273  64% 2022-11-29 19:42 bdcc02f5  vdtk/third_party/bleurt/bleurt/lib/optimization.py
    6543  Defl:N     1474  78% 2022-11-11 22:24 c8d9c64a  vdtk/metrics/rouge/rouge.py
    6712  Defl:N     1510  78% 2022-11-29 17:48 62f3d8af  vdtk/content_recall.py
    6817  Defl:N     2072  70% 2022-11-29 19:42 fe71de81  vdtk/third_party/bleurt/bleurt/checkpoint.py
    6892  Defl:N     1657  76% 2022-11-12 00:34 00096a7f  vdtk/vocab_metrics.py
    7181  Defl:N     1933  73% 2022-11-29 18:10 a820dae3  vdtk/metrics/distribution/kbm/mmd.py
    7269  Defl:N     2773  62% 2022-11-29 20:40 98ca79bc  vdtk-0.3.0.dist-info/METADATA
    7948  Defl:N     2548  68% 2022-11-29 19:42 0bc8b720  vdtk/third_party/bleurt/bleurt/encoding.py
    8054  Defl:N     1926  76% 2022-11-29 18:10 f1fa1efb  vdtk/clip_recall.py
    8206  Defl:N     2437  70% 2022-11-11 23:50 f4af256b  vdtk/metrics/cider/cider_scorer.py
    9043  Defl:N     1779  80% 2022-11-29 19:42 4686cdfa  vdtk/third_party/bleurt/bleurt/score_files_test.py
    9209  Defl:N     3682  60% 2022-08-01 16:05 b1d806cf  vdtk/assets/kinetics_600_labels.txt
    9396  Defl:N     3404  64% 2022-11-29 18:07 0f8fd5db  vdtk/third_party/clip/clip/clip.py
   10357  Defl:N     2522  76% 2022-11-12 00:05 4efc4ef7  vdtk/metrics/distribution/scorer.py
   10436  Defl:N     3394  68% 2022-11-29 19:42 d6710bb3  vdtk/third_party/bleurt/bleurt/wmt/db_builder.py
   10704  Defl:N     9214  14% 2022-11-10 18:36 18d58479  vdtk/metrics/corenlp/lib/slf4j-simple-1.7.9.jar
   10714  Defl:N     3048  72% 2022-11-11 21:53 6a67f5e1  vdtk/metrics/bleu/bleu_scorer.py
   11184  Defl:N     2783  75% 2022-11-12 02:01 7f961e5f  vdtk/concept_metrics.py
   11358  Defl:N     3949  65% 2022-11-29 19:42 86e2b4b4  vdtk/third_party/bleurt/LICENSE
   11381  Defl:N     3596  68% 2022-11-29 19:42 4fc23dbb  vdtk/third_party/bleurt/bleurt/lib/bert_tokenization.py
   12558  Defl:N     6122  51% 2022-11-29 20:40 f00e0d91  vdtk-0.3.0.dist-info/RECORD
   15098  Defl:N     4582  70% 2022-11-29 19:42 01882def  vdtk/third_party/bleurt/bleurt/wmt/evaluator.py
   16789  Defl:N     4025  76% 2022-11-29 19:42 5f119abc  vdtk/third_party/bleurt/bleurt/score.py
   17374  Defl:N     4266  75% 2022-11-29 18:07 e3da2cf4  vdtk/third_party/clip/clip/model.py
   18092  Defl:N     6811  62% 2022-11-29 19:09 4e46f4a1  vdtk/metrics/corenlp/lib/CORENLP_LICENSE
   19841  Defl:N     5803  71% 2022-11-29 19:42 a86e473c  vdtk/third_party/bleurt/bleurt/model.py
   20814  Defl:N     9147  56% 2022-08-01 16:05 92a41cea  vdtk/assets/imagenet_labels.txt
   23931  Defl:N    21027  12% 2022-11-10 18:36 b9b17532  vdtk/metrics/corenlp/lib/json-simple-1.1.1.jar
   26497  Defl:N     4417  83% 2022-11-29 19:44 02c5aa62  vdtk/score.py
   26521  Defl:N     9342  65% 2022-11-29 19:24 f8a3ca58  vdtk/metrics/corenlp/lib/METEOR_LICENSE
   30408  Defl:N     6481  79% 2022-11-29 19:42 0876f6cf  vdtk/third_party/bleurt/bleurt/wmt/downloaders.py
   32121  Defl:N    28056  13% 2022-11-10 18:36 21ab956e  vdtk/metrics/corenlp/lib/slf4j-api-1.7.9.jar
   34520  Defl:N    11759  66% 2022-11-29 19:10 6769ec3f  vdtk/metrics/corenlp/lib/SPICE_LICENSE
   39062  Defl:N     9722  75% 2022-11-29 19:42 75ddbd9a  vdtk/third_party/bleurt/bleurt/lib/modeling.py
   45024  Defl:N    39918  11% 2022-11-10 18:36 ac772733  vdtk/metrics/corenlp/lib/hamcrest-core-1.3.jar
   54391  Defl:N    46598  14% 2022-11-10 18:36 61971370  vdtk/metrics/corenlp/lib/objenesis-2.5.1.jar
   72671  Defl:N    64983  11% 2022-11-10 18:36 705c0b19  vdtk/metrics/corenlp/lib/lmdbjni-win64-0.4.6.jar
   85980  Defl:N    76584  11% 2022-11-10 18:36 47d9dbbb  vdtk/metrics/corenlp/lib/lmdbjni-0.4.6.jar
  106300  Defl:N    92265  13% 2022-11-10 18:36 44662432  vdtk/metrics/corenlp/lib/lmdbjni-osx64-0.4.6.jar
  164039  Defl:N   150946   8% 2022-11-10 18:36 aeb0c378  vdtk/metrics/corenlp/lib/SceneGraphParser-1.0.jar
  180197  Defl:N    17465  90% 2022-11-29 19:42 ee88769f  vdtk/third_party/bleurt/bleurt/test_checkpoint/saved_model.pb
  231508  Defl:N   110671  52% 2022-11-29 19:42 e3084609  vdtk/third_party/bleurt/bleurt/test_checkpoint/vocab.txt
  282438  Defl:N   267022   6% 2022-11-10 18:36 bffa4c4d  vdtk/metrics/corenlp/lib/jackson-core-2.8.8.jar
  301506  Defl:N   279087   7% 2022-11-10 18:36 27d5cc41  vdtk/metrics/corenlp/lib/ejml-0.23.jar
  314932  Defl:N   278248  12% 2022-11-10 18:36 50cb8f45  vdtk/metrics/corenlp/lib/junit-4.12.jar
  385952  Defl:N   310890  19% 2022-11-10 18:36 aea6debe  vdtk/metrics/corenlp/lib/lmdbjni-linux64-0.4.6.jar
  395170  Defl:N   360635   9% 2022-11-10 18:36 1147b868  vdtk/metrics/corenlp/lib/fst-2.56.jar
  734815  Defl:N   684202   7% 2022-11-10 18:36 7d06b1ff  vdtk/metrics/corenlp/lib/javassist-3.21.0-GA.jar
 1356917  Defl:N  1357332   0% 2022-11-29 18:07 c82a18c4  vdtk/third_party/clip/clip/bpe_simple_vocab_16e6.txt.gz
 2308517  Defl:N  2042271  12% 2022-11-10 18:36 7e260b27  vdtk/metrics/corenlp/lib/guava-19.0.jar
 6318693  Defl:N  6309947   0% 2022-11-10 18:59 e1dfee24  vdtk/metrics/corenlp/lib/Meteor-1.5.jar
 7270741  Defl:N  6796410   7% 2022-11-10 18:36 208c2bb0  vdtk/metrics/corenlp/lib/stanford-corenlp-3.6.0.jar
17544204  Defl:N 16253205   7% 2022-11-29 19:42 effc6ba1  vdtk/third_party/bleurt/bleurt/test_checkpoint/variables/variables.data-00000-of-00001
19750600  Defl:N 19731416   0% 2022-11-10 18:34 d7a4f28b  vdtk/metrics/corenlp/lib/spice-1.0.jar
61813011  Defl:N 61831861   0% 2022-11-10 18:53 afa9cdb6  vdtk/metrics/corenlp/lib/data/paraphrase-en.gz
80028729  Defl:N 26064819  67% 2022-11-09 22:16 0669bfbc  vdtk/metrics/cider/data/coco-val.pkl
378116526  Defl:N 378223243   0% 2022-11-10 18:36 74f949de  vdtk/metrics/corenlp/lib/stanford-corenlp-3.6.0-models.jar
578513002         521630520  10%                            133 files

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @DavidMChan :wave: and thanks for the report.
I've set the upload limit for `vdtk` to 700 MB on PyPI. Please be mindful of the frequency of releases at that size.
have a nice day!
