### ISSUE TITLE
Project Limit Request: itk-elastix - 50 GB

### ISSUE THREAD

**Issue by thewtex** [pypa/pypi-support#2449]
### Project URL

https://pypi.org/project/itk-elastix/

### Does this project already exist?

- [X] Yes

### New limit

50

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We expect 50 GB will be sufficient for the foreseeable future. We had to delete a few old releases already and would really like to avoid that going forward.

Thank you in advance!

### How large is each release?

~ 1GB total

Python 3.7 to Python 3.11, macOS, Windows, Linux, amd64, ARM.

We are making an effort to use the stable Python 3 ABI, but that, if it works, would only come sometime in the future (next year or two).

### How frequently do you make a release?

Roughly once every three months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @thewtex :wave: thanks for the report.
You could explore the limited api https://docs.python.org/3/c-api/stable.html to avoid having too many linux wheels, it's not straightforward but certainly helps the releasing process.
I've set the project limit for `itk-elastix` to 50 GB on PyPI. Please be mindful of the frequency of releases.
Have a nice day!

**Comment by thewtex** [comment]
Hey @cmaureir, thank you!!!

Yes, we are working towards the Python 3 stable API through updates in [scikit-build](https://scikit-build.org/). This will help in the meantime.

CC @jcfr @henryiii
