### ISSUE TITLE
Account recovery request, Lost access to email account

### ISSUE THREAD

**Issue by mikeatm** [pypa/pypi-support#246]
Request for account recovery.
lost access to m.atambo@nano.cnt.it, need to update it to same email in my public profile
## PyPI Username

`aiida-yambo`

---

##  Reason for request

Reason:
I not so recently (1> yr) changed employer, and wound up the address used to create the account, but did not update pypi.

**Comment by ewdurbin** [comment]
@mikeatm there is a `@max-centre.eu` email address associated with your user account, do you still have access to that?

**Comment by mikeatm** [comment]
No it seems that  the address at max-center  is not accessible either.

**Comment by ewdurbin** [comment]
@mikeatm primary email address on the `aiida-yambo` has been updated to the address you requested. you should now be able to complete a password reset to regain access to the account.
