### ISSUE TITLE
PEP 541 Request: seeq on Test PyPI

### ISSUE THREAD

**Issue by mpderbec** [pypa/pypi-support#2461]
### Project to be claimed

`seeq`: https://test.pypi.org/project/seeq/

### Your PyPI username

`mpderbec`: https://pypi.org/user/mpderbec

### Reasons for the request

Several years ago, I successfully lobbied the maintainer of the "seeq" project to transfer to me. However, we didn't think to transfer the Test PyPI project as well. The original maintainer is no longer responding to my emails.

Can you make the maintainers of https://test.pypi.org/project/seeq/ the same as https://pypi.org/project/seeq/?

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

Source code is proprietary.

### Contact and additional research

![image](https://user-images.githubusercontent.com/4581968/205466673-11bc4f58-6974-43b2-b2ee-12e7297a63ff.png)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete, owners of project in PyPI automatically get ownership of corresponding projects in Test PyPI.
