### ISSUE TITLE
File Limit Request: cutensor-cu12 - 200 MB

### ISSUE THREAD

**Issue by leofang** [pypa/pypi-support#2466]
### Project URL

https://pypi.org/project/cutensor-cu12

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a follow-up of #2385. Today NVIDIA releases CUDA 12, and this project is to support CUDA 12 users to use cuTENSOR. Like `cutensor-cu11` we're requesting the same size limit for `cutensor-cu12`. Separation of CUDA 11/12 wheels are necessary as CUDA only guarantees minor version compatibility, not major version.

### Reasons for the request

cuTENSOR is an NVIDIA GPU library. In an effort to reduce wheel size and align with other NVIDIA products, we have been migrating from the existing [`cutensor`](https://pypi.org/project/cutensor) wheel to `cutensor-cu11` (and now `cutensor-cu12`) wheel.

However, despite our best effort to reduce the wheel size, we still need to go beyond a bit the default limit, hence this request. We are currently blocked from uploading new releases, and we would appreciate if this request can be addressed promptly.

It could be possible that the `cutensor-cuXX` wheels would go beyond 200 MB per wheel in the future, when we need to support more GPU architectures and/or provide more GPU functionalities. However, the growth is currently not predictable, as we are also investigating internally more aggressive approaches for binary size reduction. We are hoping to make best effort to stay within the new limit.

Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Thanks for the details :wave:, I've set the upload limit for `cutensor-cu12` to 200 MB on PyPI. Have a nice weekend.

**Comment by leofang** [comment]
Thanks Cristián! I confirm it's bumped. Have a nice weekend too!
