### ISSUE TITLE
Transfer of test PVLIB to primary maintainers

### ISSUE THREAD

**Issue by CameronTStark** [pypa/pypi-support#247]
**Note:** This is only to transfer the _test_ PyPI project only. I am already a maintainer of the https://www.pypi.org/project/pvlib/

**Project to be claimed**

`PROJECT_NAME`: https://test.pypi.org/project/pvlib/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/CameronTStark/

**Reasons for the request**

The test PyPI.org profile for pvlib-python is owned solely by the previous maintainer who has been inactive on the project for at least a year. We would like access to test.PyPI.org pvlib for Continuous Deployment testing.

Calama-Consulting is listed in GitHub while Heliolytics is listed for test.PyPI.org however they are the same person (see link below). 

* [To confirm Calama-Consulting as a previous maintainer see their contributions here.](https://github.com/pvlib/pvlib-python/graphs/contributors)
* [To confirm that Calama-Consulting and Heliolytics are the same person see Rob's LinkedIn.](https://www.linkedin.com/in/robwandrews/)
* To confirm that I am currently a maintainer of pvlib-python see the main project on [PyPI](https://pypi.org/project/pvlib/) and [GitHub](https://github.com/pvlib). 

**Maintenance or replacement?**
The purpose is for continued maintenance.

**Contact and additional research**

I have reached out to the old maintainer in an pvlib issue here: https://github.com/pvlib/pvlib-python/issues/929#issuecomment-594709617

**Comment by yeraydiazdiaz** [comment]
Hi @CameronTStark, we have a policy where maintainers of projects of the main PyPI are automatically granted ownership of the project in test PyPI if they request it.

As such I will ask an admin to perform this transfer now.

**Comment by CameronTStark** [comment]
Great, thank you!

-------- Original Message --------

**Comment by ewdurbin** [comment]
Complete.
