### ISSUE TITLE
Test pypi recovery

### ISSUE THREAD

**Issue by Phornee** [pypa/pypi-support#2477]
### PyPI Username

'phornee'

### Reason for request

Hello. Lost my f2a access for testpypi ( not for pypi), and ive got no recovery code for it.
Maya i have it cleaned, so i can set It again?. Thank you!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
2FA for `phornee` user on TestPyPI reset.
