### ISSUE TITLE
Project Limit Request: SciPy - 50 GB

### ISSUE THREAD

**Issue by rgommers** [pypa/pypi-support#2479]
### Project URL

https://pypi.org/project/scipy/

### Does this project already exist?

- [X] Yes

### New limit

50 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

SciPy is one of the most widely used library for scientific computing with Python.

### How large is each release?

~640 MB total (19 wheels with average size of 32 MB, one sdist of 40 MB).

We were close to the current 40 GB limit earlier today. I did delete a number of pre-releases, so we now have about 5 GB left. That's still uncomfortably close (one minor release cycle of 6 months may see ~6 releases, so that will bring us back near the limit), and it's better not to delete even more recent pre-releases.

### How frequently do you make a release?

Including pre-releases and bug fix releases, about once a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've bumped the limit to 50 GB, as requested. :)

**Comment by rgommers** [comment]
Thanks Pradyun!
