### ISSUE TITLE
Project Limit Request: NumPy - 40 GB

### ISSUE THREAD

**Issue by rgommers** [pypa/pypi-support#2480]
### Project URL

https://pypi.org/project/numpy/

### Does this project already exist?

- [X] Yes

### New limit

40 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

NumPy is the fundamental library for numerical computing with Python.

### How large is each release?

~415 MB total (27 wheels with a 15 MB average size, 1 sdist of 11 MB)

### How frequently do you make a release?

About once a month

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
I've bumped the limit to 40 GB, as requested. :)
