### ISSUE TITLE
Project Limit Request: ddtrace - 60 GB 

### ISSUE THREAD

**Issue by mabdinur** [pypa/pypi-support#2483]
### Project URL

https://pypi.org/project/ddtrace/

### Does this project already exist?

- [X] Yes

### New limit

60

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The project is the official Python APM client for Datadog.

The project has been active on PyPI since 2017.

We currently support a broad range of operating systems, and Python versions. Since we have C-extensions we try to build and publish for as many systems as we can so our customers avoid needing to install our build dependencies.

I expect the size of the wheel/binaries we build to slowly grow over time as we support new python versions and platforms.

Last April, we opened https://github.com/pypa/pypi-support/issues/1884 to increase the size limit of our package from 10GB to 20GB. We expected this increase to give us 60 weeks of runway. However with the introduction of new features that required new dependencies we hit this limit earlier than expected.

### How large is each release?

For our 1.7.0 release:
Total combined: 210.6M

Source distribution: 1 file, 1.6M total
Python 2.7: 5 files, 14M total
Python 3.5: 5 files, 13M total
Python 3.6: 9 files, 27M total
Python 3.7: 9 files, 27M total
Python 3.8: 10 files, 32M total
Python 3.9: 10 files, 31M total
Python 3.10: 10 files, 30M total
Python 3.11: 10 files, 31M total

We vendor a few dependencies and have a few data files, but the bulk of our package is pre-built binaries specifically for our code.

<details>
<summary>du -sh *</summary>
<br>
<pre>
1.5M	ddtrace-1.7.0rc1-cp27-cp27m-macosx_10_9_x86_64.whl
2.9M	ddtrace-1.7.0rc1-cp27-cp27m-manylinux2010_i686.whl
3.0M	ddtrace-1.7.0rc1-cp27-cp27m-manylinux2010_x86_64.whl
2.9M	ddtrace-1.7.0rc1-cp27-cp27mu-manylinux2010_i686.whl
3.0M	ddtrace-1.7.0rc1-cp27-cp27mu-manylinux2010_x86_64.whl
2.1M	ddtrace-1.7.0rc1-cp310-cp310-macosx_10_9_universal2.whl
1.6M	ddtrace-1.7.0rc1-cp310-cp310-macosx_10_9_x86_64.whl
3.7M	ddtrace-1.7.0rc1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
3.6M	ddtrace-1.7.0rc1-cp310-cp310-manylinux_2_17_i686.manylinux2014_i686.whl
3.8M	ddtrace-1.7.0rc1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
4.2M	ddtrace-1.7.0rc1-cp310-cp310-musllinux_1_1_aarch64.whl
4.2M	ddtrace-1.7.0rc1-cp310-cp310-musllinux_1_1_i686.whl
4.3M	ddtrace-1.7.0rc1-cp310-cp310-musllinux_1_1_x86_64.whl
1.3M	ddtrace-1.7.0rc1-cp310-cp310-win32.whl
1.4M	ddtrace-1.7.0rc1-cp310-cp310-win_amd64.whl
2.0M	ddtrace-1.7.0rc1-cp311-cp311-macosx_10_9_universal2.whl
1.5M	ddtrace-1.7.0rc1-cp311-cp311-macosx_10_9_x86_64.whl
3.8M	ddtrace-1.7.0rc1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
3.7M	ddtrace-1.7.0rc1-cp311-cp311-manylinux_2_17_i686.manylinux2014_i686.whl
3.9M	ddtrace-1.7.0rc1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
4.3M	ddtrace-1.7.0rc1-cp311-cp311-musllinux_1_1_aarch64.whl
4.3M	ddtrace-1.7.0rc1-cp311-cp311-musllinux_1_1_i686.whl
4.4M	ddtrace-1.7.0rc1-cp311-cp311-musllinux_1_1_x86_64.whl
1.3M	ddtrace-1.7.0rc1-cp311-cp311-win32.whl
1.4M	ddtrace-1.7.0rc1-cp311-cp311-win_amd64.whl
3.3M	ddtrace-1.7.0rc1-cp35-cp35m-manylinux2010_i686.whl
3.4M	ddtrace-1.7.0rc1-cp35-cp35m-manylinux2010_x86_64.whl
3.5M	ddtrace-1.7.0rc1-cp35-cp35m-manylinux2014_aarch64.whl
1.3M	ddtrace-1.7.0rc1-cp35-cp35m-win32.whl
1.4M	ddtrace-1.7.0rc1-cp35-cp35m-win_amd64.whl
1.5M	ddtrace-1.7.0rc1-cp36-cp36m-macosx_10_9_x86_64.whl
3.5M	ddtrace-1.7.0rc1-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
3.5M	ddtrace-1.7.0rc1-cp36-cp36m-manylinux_2_17_i686.manylinux2014_i686.whl
3.6M	ddtrace-1.7.0rc1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
4.0M	ddtrace-1.7.0rc1-cp36-cp36m-musllinux_1_1_aarch64.whl
4.1M	ddtrace-1.7.0rc1-cp36-cp36m-musllinux_1_1_i686.whl
4.1M	ddtrace-1.7.0rc1-cp36-cp36m-musllinux_1_1_x86_64.whl
1.3M	ddtrace-1.7.0rc1-cp36-cp36m-win32.whl
1.4M	ddtrace-1.7.0rc1-cp36-cp36m-win_amd64.whl
1.5M	ddtrace-1.7.0rc1-cp37-cp37m-macosx_10_9_x86_64.whl
3.6M	ddtrace-1.7.0rc1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
3.5M	ddtrace-1.7.0rc1-cp37-cp37m-manylinux_2_17_i686.manylinux2014_i686.whl
3.6M	ddtrace-1.7.0rc1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
4.1M	ddtrace-1.7.0rc1-cp37-cp37m-musllinux_1_1_aarch64.whl
4.1M	ddtrace-1.7.0rc1-cp37-cp37m-musllinux_1_1_i686.whl
4.2M	ddtrace-1.7.0rc1-cp37-cp37m-musllinux_1_1_x86_64.whl
1.3M	ddtrace-1.7.0rc1-cp37-cp37m-win32.whl
1.4M	ddtrace-1.7.0rc1-cp37-cp37m-win_amd64.whl
2.1M	ddtrace-1.7.0rc1-cp38-cp38-macosx_10_9_universal2.whl
1.6M	ddtrace-1.7.0rc1-cp38-cp38-macosx_10_9_x86_64.whl
3.9M	ddtrace-1.7.0rc1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
3.8M	ddtrace-1.7.0rc1-cp38-cp38-manylinux_2_17_i686.manylinux2014_i686.whl
4.0M	ddtrace-1.7.0rc1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
4.6M	ddtrace-1.7.0rc1-cp38-cp38-musllinux_1_1_aarch64.whl
4.6M	ddtrace-1.7.0rc1-cp38-cp38-musllinux_1_1_i686.whl
4.7M	ddtrace-1.7.0rc1-cp38-cp38-musllinux_1_1_x86_64.whl
1.3M	ddtrace-1.7.0rc1-cp38-cp38-win32.whl
1.4M	ddtrace-1.7.0rc1-cp38-cp38-win_amd64.whl
2.1M	ddtrace-1.7.0rc1-cp39-cp39-macosx_10_9_universal2.whl
1.6M	ddtrace-1.7.0rc1-cp39-cp39-macosx_10_9_x86_64.whl
3.8M	ddtrace-1.7.0rc1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
3.8M	ddtrace-1.7.0rc1-cp39-cp39-manylinux_2_17_i686.manylinux2014_i686.whl
3.9M	ddtrace-1.7.0rc1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
4.3M	ddtrace-1.7.0rc1-cp39-cp39-musllinux_1_1_aarch64.whl
4.3M	ddtrace-1.7.0rc1-cp39-cp39-musllinux_1_1_i686.whl
4.4M	ddtrace-1.7.0rc1-cp39-cp39-musllinux_1_1_x86_64.whl
1.3M	ddtrace-1.7.0rc1-cp39-cp39-win32.whl
1.4M	ddtrace-1.7.0rc1-cp39-cp39-win_amd64.whl
</pre>
</details>

### How frequently do you make a release?

We release a new minor version, along with at least 1 pre-release about every 2-3 weeks.
 
We release patch releases on demand, but average ~1 per week.

At ~210MB per release an increase to 60GB would buy us about a year of space. We are currently looking into strategies to avoid frequently asking for package limit increases. Increasing our size limit to ~60GB will give us time to investigate this issue and define next steps in 2023.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Limit updated on PyPI.

**Comment by brettlangdon** [comment]
Thank you @ewdurbin !!!
