### ISSUE TITLE
Transfer of s3monkey to the primary maintainer

### ISSUE THREAD

**Issue by kobayashi** [pypa/pypi-support#249]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/s3monkey

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/kkobayashi

**Reasons for the request**
The project is transferred to the new owner in github. Because of this, I need transfer the maintainer in pypi  also.

**Maintenance or replacement?**
To maintain the project continuously

**Contact and additional research**
github repo: https://github.com/kobayashi/s3monkey

**Comment by yeraydiazdiaz** [comment]
Hello @kobayashi, we'd need confirmation from the current owners of the project in PyPI, @kennethreitz or @timofurrer.

**Comment by kobayashi** [comment]
Thank you reply. @yeraydiazdiaz
Because no response even though contacted, I open this issue.

**Comment by kobayashi** [comment]
@yeraydiazdiaz As I mentioned both current maintainers does not give me any response.

**Comment by yeraydiazdiaz** [comment]
The [reachability section of PEP 541](https://www.python.org/dev/peps/pep-0541/#reachability) describes the process, we moderators need to attempt contact with current owners at least three times for a six week period. If we receive no response we can classify the project as abandoned and proceed with the transfer.

I was hoping that tagging the owners here in GitHub might be enough but I will proceed to email them now.

**Comment by timofurrer** [comment]
I got push permissions some time ago from Kenneth. I can confirm that @kobayashi is the current maintainer of the project (Kenneth transferred the ownership).

It is okay for me to handover sole ownership of the project to @kobayashi - you can even remove myself as a maintainer on PyPI.

Cheers and good look with the project! :tada:

**Comment by yeraydiazdiaz** [comment]
Thanks for your reply @timofurrer.

I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
`kkobayashi` user has been granted owner role on the project
