### ISSUE TITLE
Account rename request (case sensitivity only)

### ISSUE THREAD

**Issue by tonyseek** [pypa/pypi-support#2501]
### PyPI Username

`TonySeek`

### Reason for request

Sorry for using the account recovery template to request an account renaming. My PyPI username is `TonySeek` and I want to change it to `tonyseek` (lowercase). Is this still possible? 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Looks like it *is* still possible, but cumbersome. This is complete.
