### ISSUE TITLE
PEP 541 Request: django-elasticsearch

### ISSUE THREAD

**Issue by andreasnuesslein** [pypa/pypi-support#251]
**Project to be claimed**

`django-elasticsearch`: https://pypi.org/project/django-elasticsearch

**Your PyPI username**

`andreas.nuesslein`: https://pypi.org/user/andreas.nuesslein

**Reasons for the request**
I'm not sure if there ever were any packages but as of the last ~20 days there was no package there and I don't know who the maintainer is.

**Maintenance or replacement?**
I would like to inherit the name for this project: https://github.com/django-elasticsearch/django-elasticsearch-dsl which at the moment is still called `django-elasticsearch-dsl` but I want to rename to `django-elasticsearch`. I forked the original `django-elasticsearch-dsl` because of its slow pace and disagreement with the course it's taking. I intentionally created a group on github as I don't plan on keeping the project to myself but hoping to have other maintainers flock to it :crossed_fingers: 

**Contact and additional research**
I have no lead as to who the original maintainer would be

**Comment by yeraydiazdiaz** [comment]
Hi @andreasnuesslein, I can confirm `django-elasticsearch` has no releases and is thus considered invalid. I will now ask an admin to perform this transfer to you.

**Comment by andreasnuesslein** [comment]
@yeraydiazdiaz thank you :)

**Comment by andreasnuesslein** [comment]
Just a little bump to inquire about the status here,

cheers

**Comment by ewdurbin** [comment]
This is complete.

**Comment by andreasnuesslein** [comment]
much obliged :)
