### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by playpauseandstop** [pypa/pypi-support#252]
Request for account recovery.

## PyPI Username

`playpauseandstop`

---

##  Reason for request

Reason:

- Lost 2FA authentication app or security token

---

I've set up 2FA for my PyPI account early after it has been activated and shortly after lost my phone with Google Authenticator app. I didn't have a chance to create recovery codes, so right now asking about turning off 2FA. Thanks

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by playpauseandstop** [comment]
Hi. Thanks for helping me with this. 

I’ve replied to email shortly after receiving it. Replying here to ensure my reply hasn’t missed.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by playpauseandstop** [comment]
Thanks a lot for your help!
