### ISSUE TITLE
PEP 541 Request: pspy

### ISSUE THREAD

**Issue by xgarrido** [pypa/pypi-support#256]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/pspy

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/xgarrido

**Reasons for the request**

The project appears to have been abandoned. The unique release dates from December, 2014 and the `github` project has not been updated since this date.

**Maintenance or replacement?**

We plan to replace this project by a totally different one related to cosmology analysis. The current project is located https://github.com/simonsobs/pspy and is actively developed now and, at least for the next 5-10 years.

**Contact and additional research**
We contact (in January, 2020) the original author by mail using the address in his github profile page hty0807@gmail.com. We received no answer since. We can provide the original mail.

**Comment by yeraydiazdiaz** [comment]
Hello @xgarrido, I agree it looks abandoned but as there seems to be some functionality I'm obliged by the PEP to attempt contact with the owner @tesseract2048. I will also attempt contact by email as sometimes we have better luck as moderators. Hopefully we'll hear back soon and move forwards with your claim.

**Comment by yeraydiazdiaz** [comment]
@xgarrido the owner came back to me and added you as an owner for the project.
