### ISSUE TITLE
PEP 541 Request: arbor

### ISSUE THREAD

**Issue by bcumming** [pypa/pypi-support#257]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/arbor

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/bcumming

**Reasons for the request**

This package appears to be *invalid* by virtue of *name squatting*. The package was created on June 26 2015, and is empty. The same user, `djbchepe` has 10 projects, all created in June and October 2015, each of them empty.

**Maintenance or replacement?**

We plan to publish a different package for Arbor, a neuroscience simulation tool: https://github.com/arbor-sim/arbor

**Contact and additional research**

I attempted to contact the owner via LinkedIn on Feb 26 2020, and I have received no response. I made the request as a contact request, because I don't have a pro user account on LinkedIn, which isn't ideal, but it was the best I could do. LinkedIn was the only contact method I could find, via a GitHub account with the same user name and profile picture: https://github.com/djbchepe

**Comment by hugovk** [comment]
I found his email via a whois of the webpage on his profile: http://www.davidcheperdak.com/

https://www.godaddy.com/whois

You could try emailing that.

**Comment by bcumming** [comment]
Thanks for the pointer. I sent the following to the hotmail address on godaddy.

```
Hello David,

I am the maintainer of a software library for scientific research called Arbor:

https://github.com/arbor-sim/arbor

We would like to use the package name "arbor" on PyPI:

https://pypi.org/project/arbor/

I think that this package is registered to your PyPI account. The arbor package
on PyPI is empty, four years after you created it, so I am reaching out to see if
you could transfer the arbor package to us?

Our work is publicly funded scientific research, and we would love to be able to
have a PyPI package name that perfectly matches our library!

Please reply to this email, or respond directly on the GitHub issue:

https://github.com/pypa/pypi-support/issues/257

Regards,

Ben Cumming.
```

**Comment by bcumming** [comment]
I got a reply from the current owner by email, saying that they are unable to transfer the package:

```
My life has taken many different paths, and unfortunately it has drifted a bit from my arbor project. However my arbor project is still on the road map at some point in the near future. So unfortunately I will be unable to transfer this package name.
```

What is the next step here? PEP 541 states:

```
A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:
...
* project is name squatting (package has no functionality or is empty);
```

This package was created over 4 years ago, and has remained empty since, so it meets these standards, along with the other 9 empty packages by the same author. Further, the owners reasons for keeping the name were very vague.

Is it standard practice to respect the wishes of the owner, or do we follow the letter of the law?

**Comment by di** [comment]
Considering [all the other project names](https://pypi.org/user/djbchepe/) that the user has similarly reserved, yet provided no additional releases, this looks a lot like squatting to me.

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by bcumming** [comment]
Thank you!
