### ISSUE TITLE
PEP 541 Request: PyRFC

### ISSUE THREAD

**Issue by bsrdjan** [pypa/pypi-support#258]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/PyRFC

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/bsrdjan

**Reasons for the request**

The project looks inactive and we would like to reuse the name for a different, mature and active project.

**Maintenance or replacement?**

The replacement.

[SAP/PyRFC](https://github.com/SAP/PyRFC) is a mature and active project, distributed so far via GutHib only. The project is now ready for PyPI and the name is unfortunately already taken https://pypi.org/project/pyrfc/

**Contact and additional research**

We contacted the original author by E-mail using the address in his github [profile page](https://github.com/meisanggou) zhou5315938@163.com and via project [issues](https://github.com/meisanggou/rfc/issues). No response received so far.

**Comment by yeraydiazdiaz** [comment]
Hello @bsrdjan, while apparently inactive `pyrfc` still has functionality and releases, so we're obliged by the PEP to attempt contact with the owner before declaring it abandoned.

I will email @meisanggou myself as sometimes as moderators we have more luck in getting a response.

**Comment by bsrdjan** [comment]
Hello @yeraydiazdiaz,

just curious if any updates here? PyRFC users relatively often install `pyrfc` by mistake, instead of `pynwrfc` and raise issues like: [PyRFC/#189](https://github.com/SAP/PyRFC/issues/189#issuecomment-667230809).
Thanks and regards, srdjan

**Comment by yeraydiazdiaz** [comment]
I have not received any replies from the current owner, as such this project is considered abandoned. I will now ask an admin to perform the transfer for you. Apologies for the delay.

**Comment by bsrdjan** [comment]
Hey @yeraydiazdiaz, just a quick check, when the transfer could eventually happen?

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by bsrdjan** [comment]
Many thanks 👍
