### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by selwin** [pypa/pypi-support#265]
Request for account recovery.

## PyPI Username

`selwin`

---

##  Reason for request

Reason: TOTP generated by Google Auth doesn't work, I kept getting `Invalid TOTP code.` error.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@selwin Still awaiting response. Please respond to the email sent with subject "PyPI Account Recovery Request: selwin"

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
