### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mindflayer** [pypa/pypi-support#268]
Request for account recovery.

## PyPI Username

`drizzt`

---

##  Reason for request

  - Cannot login
-->

Reason:
  - The mobile having Google Authenticator is dead

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mindflayer** [comment]
Replied to your email, thank you very much.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
