### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `phantomjs-binary` package

### ISSUE THREAD

**Issue by tallero** [pypa/pypi-support#27]
Hi, my understanding is that if we believe that a project is abandoned by the rules of PEP 541, the current process is to post an issue here, since there is no other process at pypi.org. If that's wrong, please let me know and I'll close this.

The package has a merge request to fix linux executable since april

https://github.com/jayjiahua/phantomjs-bin-pip/pull/2

**Comment by yeraydiazdiaz** [comment]
Hi @tallero, seems this project just a means of distributing PhantomJS and has no actual Python code which I believe makes it an invalid project in PyPI.

I will close this issue now as I don't think allowing further releases to be published is the right thing to do.

cc'ing @pypa/pypi-moderators in case I'm wrong in my interpretation or if there's any additional action to be taken.
