### ISSUE TITLE
PEP 541 Request: pe

### ISSUE THREAD

**Issue by goodmami** [pypa/pypi-support#270]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/pe/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/goodmami/

**Reasons for the request**

The project URL gives a 404 but I am unable to upload to the project. I do not see `pe` in the Python standard library's module index for any version from 2.5. It could be blacklisted for trademark or confusability reasons, but I cannot find such a list to confirm. My guess is someone is squatting the name.

**Maintenance or replacement?**

There is no existing package that I can see, so I intend to upload a new package: https://github.com/goodmami/pe

**Contact and additional research**

I do not see information about any current owner, so I have not contacted anyone beyond this request.

**Comment by yeraydiazdiaz** [comment]
Hello @goodmami, I can confirm project `pe` has no releases and is thus considered invalid.

I will now ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
Transfer complete.
