### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by teratorn** [pypa/pypi-support#274]
Request for account recovery.

## PyPI Username

`teratorn`

---

##  Reason for request

  - Lost access to email address (domain expired)

## Notes

 - This account has not been used in many years, and the domain that the email was on is no longer registered (NXDOMAIN) and I don't wish to re-register it just to recover this account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
If no response is received or the email is undeliverable, I'll follow up to proceed.

**Comment by ewdurbin** [comment]
@teratorn what email address would you like to be associated with the user?

**Comment by ewdurbin** [comment]
@teratorn checking in again. just need confirmation on what email address you'd like associated with the account to proceed.

**Comment by teratorn** [comment]
teratorn /AT/ zoho /DOT/ com

**Comment by ewdurbin** [comment]
Email address associated with the user has been updated, you can now perform a password reset to regain access to the account.
