### ISSUE TITLE
Project `pylogix` taken on pypi by a fork

### ISSUE THREAD

**Issue by dmroeder** [pypa/pypi-support#275]
**Project to be claimed**

`pylogix`: https://pypi.org/project/pylogix

**Your PyPI username**

`dmroeder`: https://pypi.org/user/dmroeder

**Reasons for the request**
I am the owner of the pylogix repo on github.  A user forked the repo, then took the project name on pypi.  I made an attempt to get the name back, however the user stopped responding.

I am getting users opening issues on the main project, as well as contacting me via email because they are installing it via pip thinking that they are installing the main project.  This is causing a lot of confusion for both myself and the users.  People are also referencing the main project as a dependency but are directing users to install via pip, which is getting them the outdated fork.

**Maintenance or replacement?**
I had planned on putting the project up on pypi, I just hadn't taken the time to do it before the name was taken.  I was experimenting with the pypi sandbox at some point in the past (https://test.pypi.org/project/pylogix-pip/).  I will be uploading the project if the name is returned to me and it will be up to date with the main project.

**Contact and additional research**
Main project: https://github.com/dmroeder/pylogix
Forked project: https://github.com/daniel-leicht/pylogix

**Comment by yeraydiazdiaz** [comment]
Hello @dmroeder, we've had situations like this in the past and while there room for interpretation in the PEP our course of action is to start a dialogue between the parties.

I'll attempt contact with @daniel-leicht to see if we can clarify the situation. Hopefully we will hear back and move forwards with the request soon. Otherwise we can classify the project as abandoned and proceed with the transfer.

**Comment by dmroeder** [comment]
Thanks @yeraydiazdiaz.  Daniel and I had a brief email exchange but I stopped getting replies.

**Comment by yeraydiazdiaz** [comment]
Daniel has replied and has accepted the transfer. I will now ask an admin to perform the transfer for you.

**Comment by dmroeder** [comment]
Thank you for your help @yeraydiazdiaz

**Comment by kodaman2** [comment]
Nice to see a happy ending :grinning:

**Comment by ewdurbin** [comment]
Transfer complete.
