### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by brentnash** [pypa/pypi-support#276]
Request for account recovery.

## PyPI Username

`brentnash`

---

##  Reason for request

Reason: Lost 2FA authentication app or security token

(I lost my 2FA code in Google Authenticator when I destroyed my previous cell phone so badly that it no longer turns on.  I published projects to PyPi as part of work at a previous employer.  My PyPi 2FA recovery codes lived on machines owned by former employer that I no longer have access to).

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
