### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by takluyver** [pypa/pypi-support#278]
Request for account recovery.

## PyPI Username

`takowl`

---

##  Reason for request

Reason:

Lost 2FA authentication app or security token

Unfortunately, my phone (with the authenticator app) locked itself up and had to be wiped just a few days before I got the email alerting me to the possibility of generating recovery codes, so I got locked out of my account.

I have upload rights to a number of widely used projects, and I don't have an urgent need to log in (uploading still works without 2FA for now), so please take your time to be sure it's really me requesting account recovery. I have 2FA set up on Github as well (I think a pypa org owner can check that at https://github.com/orgs/pypa/people ), and several personal projects such as [astsearch](https://pypi.org/project/astsearch/) connect my PyPI account to my Github account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
