### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thirtytwobits** [pypa/pypi-support#280]
Request for account recovery.

## PyPI Username

`thirtytwo`

---

##  Reason for request

Phone (with app) was destroyed

Reason:

Sorry but I didn't have time to get recovery codes. I'm locked out of my account now and need to setup a new MFA device.

**Comment by thirtytwobits** [comment]
I really need help here guys. I'm sorry I didn't get the recovery codes but they did just become available recently. I'm stuck working from home and I've got a contractor waiting for access to Pypi so he can do his work.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
2FA has been reset for your user and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
