### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aph3rson** [pypa/pypi-support#282]
Request for account recovery.

## PyPI Username

`netspi`

---

##  Reason for request

Reason: Malfunctioning TOTP storage lost the secret to the authenticator before recovery codes could be generated. Email access and API tokens still available.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by aph3rson** [comment]
@ewdurbin branch created, can this be resolved?

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
