### ISSUE TITLE
PEP 541 Request: hivemind

### ISSUE THREAD

**Issue by mryab** [pypa/pypi-support#286]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/hivemind/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/mryab

**Reasons for the request**

I believe that in terms of PEP 541, the current state of `hivemind` fits the definition of an [invalid project](https://www.python.org/dev/peps/pep-0541/#invalid-projects). It seems like a case of squatting, given author's [35 other projects](https://pypi.org/user/miriaford/), all with no releases past version 0.0.0 and no functionality.

**Maintenance or replacement?**

The organization [learning-at-home](https://github.com/learning-at-home), which I'm a member of, intends to upload the [package](https://github.com/learning-at-home/tesseract) for distributed volunteer training on PyPI. Its current name `tesseract` coincides with the name of an already existing project (not to mention `tesseract-ocr` and the like), so we'd like to use `hivemind`, which is (arguably) more suitable given the functionality. We will rename the repository and the project as soon as the ownership is transferred.

**Contact and additional research**

I didn't find any contact information both on the current owner's [PyPI page](https://pypi.org/user/miriaford/) or on the corresponding [GitHub profile](https://github.com/miriaford).

**Comment by jamadden** [comment]
I concur that the existing hivemind project meets the definition of an invalid project and is thus subject to removal or transfer. I will ask the admins to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
