### ISSUE TITLE
PEP 541: transfer, release, or claim project 'dirs'

### ISSUE THREAD

**Issue by slurps-mad-rips** [pypa/pypi-support#29]
Hi!

Seems I'm not the only one to run into this.  pypa/pypi-support#7 and pypa/warehouse#5503 had the same issue. I was able to successfully upload my project [`dirs`][1] to TestPyPI. I had selected the name based on it returning a 404 on PyPI proper. Turns out there must have been a project with that name in the past, as I can't upload my initial release. 

This also blocks me from uploading a few other projects that use `dirs` as a dependency, so anything I can do to help speed along this process would help, as I believe I can't just upload packages that depend on git repositories in the meantime. 😉 

I would rename this, but several other possible names are collisions and those projects are actually still being developed. If there's anything I can do to help speed this along please let me know.

[1]: https://github.com/slurps-mad-rips/dirs

**Comment by yeraydiazdiaz** [comment]
Hello @slurps-mad-rips, I can confirm the `dirs` project has no releases and can be considered name squatting. Could you confirm your PyPI username, please?

**Comment by slurps-mad-rips** [comment]
@yeraydiazdiaz Hi! Sorry for the delay. I've been taking some time off. My username on PyPI is the same as it is here. `slurps-mad-rips`

**Comment by slurps-mad-rips** [comment]
@yeraydiazdiaz Just wanted to ping you briefly to see if anything else is needed from me!

**Comment by ewdurbin** [comment]
transfer complete.
