### ISSUE TITLE
Limit Request: ovito - 80MB

### ISSUE THREAD

**Issue by stukowski** [pypa/pypi-support#290]
**Project**

https://pypi.org/project/ovito/

**Size of release**

Requesting a new limit of 80 MB.

**Which indexes**

PyPI

**Reasons for the request**

OVITO is a code for scientific data visualization and analysis. It is used by computational chemists, materials researchers and engineers to process results from numerical computer simulations. For more information see https://www.ovito.org.

PyPI packages of OVITO are now around 60-70 MB (depending on the platform). The size has increased considerably due to the integration of a large code library that adds a neural network based algorithm (Intel Open Image Denoise).

**Comment by di** [comment]
I've set the upload limit for `ovito` to 100 MB on PyPI.
