### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by abadger** [pypa/pypi-support#291]
Request for account recovery.

## PyPI Username

On test.pypi.org
`ansible`

---

##  Reason for request

Reason:

Hi, I'm one of the owners of the ansible project on pypi: https://pypi.org/project/ansible/  (badger on pypi.org, a.badger on test.pypi.org)  We are getting ready to make a new release that reorganizes our software into two dependent packages and we wanted to upload our new packages onto https://test.pypi,org both so we could test that we have the dependencies working right and so that other community members can give us feedback on the planned split.

When we looked into doing this, though, we found that one of our former teammates, alikins, had already created the ansible project and ansible account there.  We aren't currently able to get in touch with him so we need to take over the ansible account on test.pypi.org (we're assuming that the ansible account is an owner of the ansible project on the test.pypi.org server.  If it's just a maintainer we probably will need to take over ownership of the project as well).

It is possible that we still have control of the email address to which the ansible account is associated but none of the people on the engineering team have received an email from hitting the password reset link so we don't know.  We assume that since alikins set this up, the ansible account probably is set to use his email.

**Comment by ewdurbin** [comment]
Hi @abadger. I can reset the email address associated with the test.pypi.org user `ansible` to the same address associated with the pypi.org user `ansible` if that works for y'all.

Just confirm and we'll take care of it.

**Comment by abadger** [comment]
Thanks @ewdurbin !  Yes, I think that will work for us.

**Comment by ewdurbin** [comment]
Done. The test.pypi.org user `ansible` can now perform a password reset to regain access.

**Comment by abadger** [comment]
Thank you much!
