### ISSUE TITLE
Limit Request: dcrpm - 100MB

### ISSUE THREAD

**Issue by davide125** [pypa/pypi-support#292]
**Project**

dcrpm: https://pypi.org/project/dcrpm/

**Size of release**

I'm trying to upload [v0.6.0](https://github.com/facebookincubator/dcrpm/releases/tag/v0.6.0), which has a source tarball around 66.5M.

**Which indexes**

PyPI

**Reasons for the request**

dcrpm is a tool to detect and correct common issues around RPM database corruption. The codebase includes a number of [rpmdb artifacts](https://github.com/facebookincubator/dcrpm/tree/master/tests/rpmdbs) that are used for end-to-end regression testing. In the latest release, we added two more platforms (CentOS 7 and Fedora 31), and their respective databases, which pushed us over the limit. We expect to add more platforms in the future, likely one or two every year.

**Comment by di** [comment]
I've set the upload limit for `dcrpm` to 100 MB on PyPI.
