### ISSUE TITLE
Limit Request: pyspark-cloud - 300MB

### ISSUE THREAD

**Issue by tekumara** [pypa/pypi-support#293]
**Project**
https://test.pypi.org/project/pyspark-cloud/

**Size of release**
300MB

**Which indexes**
PyPI, Test PyPI

**Reasons for the request**
This is [pyspark](https://pypi.org/project/pyspark/) bundled with libraries to access cloud object stores.

**Comment by ewdurbin** [comment]
Hi @tekumara, please review the [limit-request](https://raw.githubusercontent.com/pypa/pypi-support/master/.github/ISSUE_TEMPLATE/limit-request.md) issue template and update this issue with all requested information.

**Comment by tekumara** [comment]
See also https://github.com/pypa/packaging-problems/issues/329

**Comment by tekumara** [comment]
Thanks @ewdurbin I've updated the issue as per the template.

**Comment by di** [comment]
> This is pyspark bundled with libraries to access cloud object stores.

Sorry, there isn't enough detail here. What makes this distribution so large? Are you vendoring pyspark entirely? If so, why? Is this project part of or involved with the Spark project in some way?

**Comment by tekumara** [comment]
This is a build of the pyspark that is exactly the same as [pyspark](https://pypi.org/project/pyspark/) except it contains additional cloud libraries to access S3 and other object stores that are not provided in the official distribution. This is not an official distribution.

**Comment by jamadden** [comment]
I don't understand why this project needs to include all of pyspark again. Why can't it just use pyspark as a dependency?

I also don't understand how the "additional cloud libraries" need another 100MB beyond what pyspark itself uses. What makes them so big? 

If there was a homepage/git repo or some other information about this fork provided I might be able to answer those questions for myself, but I wasn't able to find any such information. The description and metadata appear to be exact copies of those provided by pyspark.

I am not a lawyer, but the [trademark guidelines for Apache Spark](http://spark.apache.org/trademarks.html) have strong opinions about how the name can be used that are worth reviewing, as are the terms of the Apache license section on redistributing changed and unchanged software.

**Comment by tekumara** [comment]
Thanks @jamadden for taking a look at this! I'll try and address your concerns.

Spark is a java application, and this distribution extends its capability to allow Spark to read/write from cloud object stores. Some of the java dependencies required by this new cloud functionality, conflict with the versions provided in the stock distribution. The only way I've found to provide a correct set of all dependencies is to bundle them together in one distribution. This is also what other third-parties do to augment low-level capabilities within the Spark application itself, eg: Amazon EMR, Hortonworks, or [Palantir](https://github.com/palantir/spark). More details about this distribution can be found at [tekumara/spark](https://github.com/tekumara/spark) and I've updated the project description and metadata.

[aws-java-sdk-bundle-1.11.271.jar](https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.271/) is what makes this distribution of spark so big. It's ~85MB on its own and is a transitive dependency included to access AWS.  

Thank you for pointing me to the trademark guidelines! 🙏 I was not aware of these. I noticed there were already a large number of Apache spark related projects [with spark in their name](https://pypi.org/search/?q=spark) and assumed it would be OK. I've reached out to trademarks@apache.org to understand if there is an issue here.

**Comment by tekumara** [comment]
Hiya @di is any more information needed from me? (as the status is still in awaiting response)

**Comment by di** [comment]
I've set the upload limit for `pyspark-cloud` to 300 MB on TestPyPI. The project does not exist on PyPI, you'll need to create it there before I can set the limit.

**Comment by tekumara** [comment]
Fantastic, thanks so much @di! 🙇 

I've created the [PyPI pyspark-cloud project](https://pypi.org/project/pyspark-cloud/). Would you like me to raise a new issue to increase its limit?

**Comment by di** [comment]
I've set the upload limit for `pyspark-cloud` to 300 MB on PyPI as well.
