### ISSUE TITLE
rayvision_sync

### ISSUE THREAD

**Issue by tao625** [pypa/pypi-support#294]
**Project**

https://pypi.org/project/rayvision-sync/
**Size of release**

82M
**Which indexes**

both
**Reasons for the request**

Adding support for new upload and download methods will increase the size of the module, but these new features are essential

**Comment by di** [comment]
Can you provide some more detail here? What is it that's making this distribution so large?

**Comment by jamadden** [comment]
The requested limit is lower than the new default 100MB limit, and there has been a release since this issue was created, so I think this can be closed.
