### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by JerBouma** [pypa/pypi-support#295]
Request for account recovery.

## PyPI Username

JerBouma

---

##  Reason for request

- Lost 2FA authentication app or security token

Reason: I did not use my PyPi account for a long time (last time should be around May/June 2019) and because of that did not properly handle preparing recovery codes. As I want to update my package: "FundamentalAnalysis" I would like to gain access to my account again.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
