### ISSUE TITLE
PEP 541 Request: openstates

### ISSUE THREAD

**Issue by jamesturk** [pypa/pypi-support#296]
**Project to be claimed**
`openstates`: https://pypi.org/project/openstates

**Your PyPI username**
`jamesturk`: https://pypi.org/user/jamesturk

**Reasons for the request**
I'm the creator/maintainer of Open States, it seems like a user had published the package to PyPI (perhaps on accident).  You can see on https://github.com/openstates/openstates/graphs/contributors/ that I am the maintainer of the relevant package.

**Maintenance or replacement?**
I will continue to maintain the package, but would like to also own the PyPI entry :)

**Contact and additional research**
I was unable to contact the person that published the package to ask for a transfer.

**Comment by jamadden** [comment]
As there is no actual release published to PyPI, this project falls under the "name squatting" guidelines. I've verified that the links it has do redirect to the mentioned github repository. 

I will ask the admins to schedule a transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
