### ISSUE TITLE
Verification e-mail never sent

### ISSUE THREAD

**Issue by dvorapa** [pypa/pypi-support#297]
**Describe the bug**

For e-mail: tools.pywikibot@tools.wmflabs.org no verification e-mail arrives from pypi.org. Even not into a spam folder. I've tried to create new account on test.pypi.org, but still no verification e-mail. I've also tried resend button several times in the past year, never got an e-mail. Is this an issue of PyPI? Account name: pywikibot-admin

**Expected behavior**

Verification e-mails should always be sent.

**To Reproduce**

Not sure. Try similar e-mail address with dots in name and server maybe?

**My Platform**

**Additional context**

**Comment by zhuyifei1999** [comment]
Downstream ticket: https://phabricator.wikimedia.org/T249114

This is SPF-related.

**Comment by dvorapa** [comment]
OK, closing here
