### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by junpataleta** [pypa/pypi-support#298]
Request for account recovery.

## PyPI Username
`gwaps`

---

##  Reason for request
  - Lost 2FA authentication app or security token

Reason:
  - I had to reset my phone to its factory settings and have lost my authenticator app in doing so. Didn't realise that I have not yet (and should have) generated my recovery codes before resetting my phone.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
