### ISSUE TITLE
Package 'grpc' is squatting and is too broken to install.

### ISSUE THREAD

**Issue by anadon** [pypa/pypi-support#3]
Harking back to pypa/warehouse#5196, there is a package which appears to be squatting and it too broken to install named 'grpc' registered at https://pypi.org/project/grpc/ .  It hold the name the 'grpcio' package should hold.

**Comment by yeraydiazdiaz** [comment]
Hi @anadon, as @jamadden mentions the `grpc` is still being actively installed from pip, 7.5K installs in the last 31 days, and the package is in fact installable in Python 2.7 and there's a non trivial amount of code so it's perfectly possible these are legitimate users of the package.

That being said you are right in pointing out it's confusing for users trying to install GRPC but if the package is actively used we cannot simply transfer ownership.

I've reached out to the owner to try and clarify his position regardless in case it has been abandonded and someone else would like to take ownership.

**Comment by lidizheng** [comment]
@yeraydiazdiaz From the `grpcio` maintainer's view, we concerned about the misleading `grpc` package for a while. We would be appreciated, and less users would got confused, if we can take ownership of that name :)

**Comment by yeraydiazdiaz** [comment]
Since I have received no response from the author I searched for the email and found a likely GitHub account @seewind.

There's not a lot of activity though but I hope this last means of contact is successful before declaring the package abandoned and proceed with the transfer.

Apologies to @seewind if the GitHub account is not related to the project.

**Comment by yeraydiazdiaz** [comment]
@anadon @lidizheng I have not received response from the owner of `grpc` so we can mover forward with your claim.

Could you confirm the PyPI user that the ownership should be transferred to? Presumably it would be the same as `grpc` but I'd need confirmation.

**Comment by anadon** [comment]
I would assume the same owner as the grpcio package owner, so

https://pypi.org/user/google_opensource/
And
https://pypi.org/user/grpc-packages/

**Comment by lidizheng** [comment]
@yeraydiazdiaz Thanks for the update. Finally, we can get the `grpc` direct to the gRPC Python repo. As a maintainer, I confirm the gRPC packages are owned by the PyPI account `grpc-packages`.

**Comment by ewdurbin** [comment]
transfer complete.
