### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `pynq` package

### ISSUE THREAD

**Issue by schelleg** [pypa/pypi-support#30]
### Request

I'd like to transfer the ownership of the abandoned `pynq` package ([PyPI](https://pypi.org/project/pynq/)) to myself ([PyPI account](https://pypi.org/user/schelleg/) and [GitHub repository](https://github.com/Xilinx/PYNQ)).  The last release of the current PYPI project was 10 years ago in 2009.  The current PYPI pynq-package's [project homepage](http://www.pynq.org/) is now owned by a unrelated meetup group.

#### The package is abandoned

The last release of the project was 10 years ago in 2009.  The homepage points to unrelated content.

#### Our 'pynq' has a growing community

We are hosted on github now and have over 700 stars.  Many projects depend on us, but don't have a way to cleanly `pip install pynq` directly.  Our project is unrelated to the current PYPI `pynq` package.

I have contacted the previous owner twice over the past 3 weeks with no response. 

Referencing and one more ping to [@heynemann](https://pypi.org/user/heynemann/), the current owner of the PYPI `pynq` package.

**Comment by schelleg** [comment]
hi @di - thank you for the move.  I appreciate your help here and assume this is a volunteer effort.  

Do we have an ETA when I can get the repo?

**Comment by jamadden** [comment]
I have reached out to @heynemann as a PyPI moderator. I have [opened an issue](https://github.com/pypa/pypi-support/issues/30) in what appears to be the github repository, and I have also emailed the verified address that PyPI has on file for the owner.

I don't see any indication that a PyPI moderator has attempted this before, so unfortunately the next step is to wait until contact is established or 6 weeks have elapsed. I apologize for the delay.

**Comment by schelleg** [comment]
hi @jamadden - thank you for starting that process.  I'll set a reminder to ping here after the six weeks.  Hopefully we hear back sooner, otherwise thank you again.

**Comment by schelleg** [comment]
hi @jamadden - 6 weeks have elapsed.  Can I have the PyPI entry for pynq?

Thank you for helping.

**Comment by jamadden** [comment]
As 

- I've been unable to contact @heynemann; and 
- the existing pynq package has [extremely few downloads](https://pypistats.org/packages/pynq) (~1 per day); and
- the replacement project is established under the `pynq` name, including domain names and RTD domain

I will ask the admins to transfer `pynq` to `schelleg` for the purposes of a new project.

**Comment by heynemann** [comment]
It's ok to transfer the domain to them.

I've only seen this now. The project is dead. Go ahead with the transfer.

Bernardo Heynemann

**Comment by ewdurbin** [comment]
Transfer complete.
