### ISSUE TITLE
Limit Request: atoti - 160MB

### ISSUE THREAD

**Issue by fabiencelier** [pypa/pypi-support#300]
**Project**

Project name: atoti
TestPypi: https://test.pypi.org/project/atoti/0.3.0/

**Size of release**

we have .tar.gz and wheel, each file is ~150MB

**Which indexes**

We need PyPI, would be convenient to also have Test PyPI

**Reasons for the request**

The package contains a Java JAR which is most of the library.
It is essential to the library.
On TestPypi I have uploaded the package without the JAR, you can see the full pakage on github: https://github.com/atoti/atoti/releases
The architecture is explained in this medium article: https://medium.com/atoti/getting-started-with-the-activeviam-python-library-for-data-science-28990b90d71c where the library used to be called *activeviam*
We don't plan to have significant changes in the future releases

**Comment by fabiencelier** [comment]
I have created an empty package on Pypi in case it is required to increase the limit: https://pypi.org/project/atoti/

Let me know if you need more information.

**Comment by fabiencelier** [comment]
Hello, any update on this ?

@di sorry for tagging you like that, I have seen you answer this kind of requests.
Can you tell me if you need anything else or if I just have to wait ?

**Comment by di** [comment]
I've set the upload limit for `atoti` to 160 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by fabiencelier** [comment]
Thanks a lot!
