### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bvoleti-p** [pypa/pypi-support#301]
Request for account recovery.

## PyPI Username

`bvoleti-p`

---

##  Reason for request

Reason: Got a new phone but forgot to set up the authenticator on the new phone before resetting it.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
