### ISSUE TITLE
PEP 541 Request: nux

### ISSUE THREAD

**Issue by rzabounidis** [pypa/pypi-support#304]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/nux

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/rzabounidis

**Reasons for the request**

The project does not seem to exist / isn't public. When we go to the URL, we get "We looked everywhere but couldn't find this page". Nonetheless, when trying to create the project, we get "HTTPError: 403 Client Error: The user 'rzabounidis' isn't allowed to upload to project 'nux'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/"

**Maintenance or replacement?**

Yes we do. NuX (Normalizing Flows using JaX) would be actively maintained by the Information Fusion Lab at the University of Massachusetts Amherst. Our current repository can be found here: https://github.com/Information-Fusion-Lab-Umass/NoX

**Contact and additional research**

There does not seem to be a current owner. For non-github correspondence, please email either rzabounidis@cs.umass.edu or edmondcunnin@cs.umass.edu

**Comment by yeraydiazdiaz** [comment]
Hello @rzabounidis, the project doesn't seem to exist anymore in PyPI.

Could you try again the upload again?

**Comment by rzabounidis** [comment]
Hello @yeraydiazdiaz, I tried again, and it seems it's been solved. The error seems to have been trying to upload a version 0.0.1, when I changed it to 0.0.2, it worked.

**Comment by jamadden** [comment]
>  The error seems to have been trying to upload a version 0.0.1, when I changed it to 0.0.2, it worked.

That's because PyPI never allows re-using the same filename, even after a project has been deleted or transferred.
