### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by NelsonScott** [pypa/pypi-support#305]
Request for account recovery.

## PyPI Username

`scottnelson`

---

##  Reason for request

Reason: New phone no longer has pypi Authenticator app.  Could have sworn I put text message as a backup recovery, but it doesnt seem to give me the option.  I could also verify via email associated, etc, if that's an option.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@NelsonScott checking in to see if you were able to receive the email with instructions on how to proceed.

**Comment by ewdurbin** [comment]
Closing due to lack of response. @NelsonScott please reopen this issue or respond to the email sent April 6, 2020 with subject "PyPI Account Recovery Request: scottnelson"
