### ISSUE TITLE
Limit Request: tensorflow-rocm / tensorflow-rocm-enhanced - 500MB

### ISSUE THREAD

**Issue by parallelo** [pypa/pypi-support#307]
**Project**

* `tensorflow-rocm`: https://pypi.org/project/tensorflow-rocm/
* `tensorflow-rocm-enhanced`: https://pypi.org/project/tensorflow-rocm-enhanced/

**Size of release**

* `tensorflow-rocm` - 500MB
* `tensorflow-rocm-enhanced` - 500MB

**Which indexes**

Both PyPI and Test PyPI

**Reasons for the request**

Hello!

We continue to use PyPI for distribution of ROCm-enabled TensorFlow packages.  

As time goes on, the official TensorFlow packages have become larger and larger.  The same is true with our ROCm-enabled packages.  **We are currently unable to upload WHLs due to our current 200MB limit.**

At this time, we are requesting an increase in our upload limit for the following projects:
* `tensorflow-rocm`: aligned with the code from the official TensorFlow repo
* `tensorflow-rocm-enhanced`: based on the public ROCm fork of TensorFlow, which includes extra enhancements

Please increase the upload limits for each of these projects to 500MBs.  As always, we will be conscious of minimizing the number of uploads we do.  

Many thanks, 

The AMD ROCm team

CC: @sunway513

**Comment by ewdurbin** [comment]
Hi @parallelo!

What is the current size of the files you're attempting to upload? I note that the -enhanced project currently doesn't have any releases larger than a few kB.

**Comment by parallelo** [comment]
Hi @ewdurbin! 

Official Google TensorFlow WHLs are in the range of 400+ MB.  

ROCm TF WHLs are currently on the order of 250MB and they are trending upwards as we add more hardware targets.  We're currently unable to upload our WHLs to `tensorflow-rocm`.  If 500MB is too much, we're fine with a limit that is less; however, we'd also like to balance that with minimizing the number of future limit requests.  

Regarding `tensorflow-rocm-enhanced`, we are in the process of finalizing this and plan to release soon.

**Comment by sunway513** [comment]
Hi @ewdurbin , gentle ping.. Could you help let us know the ETA for approval if possible? 
Many thanks!

**Comment by parallelo** [comment]
Hello @ewdurbin.  We are currently blocked on this due to the file size limitations.  Please help us find a solution to distribute TensorFlow WHLs via PyPI.

**Comment by ewdurbin** [comment]
Upload limits set to 500MB for both projects on both indexes.

Please limit the number of releases created using this limit. Nightly or automated releases are discouraged.
