### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jcrist** [pypa/pypi-support#310]
Request for account recovery.

## PyPI Username

`jcrist`

---

##  Reason for request

- Lost access to email address

Reason:

My PyPI account was foolishly associated with my work email at Anaconda (I think, the *reset password* link didn't send anything to my current personal email), and I've since changed jobs. Only discovered this when I tried to release a project I maintain to PyPI :/. Any help would be most appreciated.

**Comment by ewdurbin** [comment]
Hi @jcrist! I took some time to review your account as well as the metadata associated with past releases. I see that there is a gmail account consistently used for Maintainer-Email and Author-Email on past releases.

I've sent an email to the corporate email associated with the account as well as this gmail address. It contains instructions on how to proceed. Assuming the corporate email address bounces just follow the instructions in the email and we can proceed to update your account.

**Comment by ewdurbin** [comment]
Confirmation complete. I've updated the email address on your account to the gmail address associated with past release metadata.

You should be able to perform a password reset to regain access to your account.
