### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Baltoli** [pypa/pypi-support#311]
Request for account recovery.

## PyPI Username

`baltoli`

---

##  Reason for request

Reason:

* Lost access to email address

The email address on the account is an old one that I used through my parent's ISP when I was young; they cancelled that account and I lost access to it.

**Comment by ewdurbin** [comment]
The email address on this account has been updated to the public email address associated with your GitHub user. You can proceed with a password reset to regain access to your account.

**Comment by Baltoli** [comment]
Thank you! Much appreciated
