### ISSUE TITLE
Request to transfer Mikado and/or restore account on TestPyPI

### ISSUE THREAD

**Issue by lucventurini** [pypa/pypi-support#312]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/Mikado
`PROJECT_NAME (TestPyPI)`: https://test.pypi.org/project/Mikado

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/LucVen
`TestPyPI USER_NAME`: https://pypi.org/user/LucVen  (I do not have access to the email linked to this account, luca.venturini@earlham.ac.uk, any longer)
`TestPyPI USER_NAME`: https://pypi.org/user/lucventurini (back-up account opened in 2019 after losing access to the original mail).

**Reasons for the request**

**Maintenance or replacement?**

I intend to continue maintenance, indeed, I need to recover the account on TestPyPI (**not** PyPI) as I am in the process of releasing a new version.

**Contact and additional research**

As stated above, I am the owner of the project himself.

**Comment by yeraydiazdiaz** [comment]
Hi @lucventurini, I think the best course of action is to create an [account recovery request](https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.md&title=Account+recovery+request) stating clearly that it's only for Test PyPI.

**Comment by lucventurini** [comment]
Hi @yeraydiazdiaz 

I followed your suggestion and opened #313. Many thanks

**Comment by yeraydiazdiaz** [comment]
No worries, closing this issue.
