### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lucventurini** [pypa/pypi-support#313]
Request for account recovery.

## PyPI Username

`LucVen`, **only for Test.PyPI** (I still have access to the corresponding username on PyPI).

---

##  Reason for request

Reason: lost access to email address (luca.venturini@earlham.ac.uk). I still have access to the email address associated to the PyPI account (lucventurini@gmail.com) and I have created a second account (`lucventurini`) on Test.PyPI.org associated with the GMAIL account.

**Comment by ewdurbin** [comment]
@lucventurini what is the final result you'd like here? We cannot associate your gmail address with the LucVen user because it is associated with the newly created lucventurini account.

**Comment by lucventurini** [comment]
> @lucventurini what is the final result you'd like here? We cannot associate your gmail address with the LucVen user because it is associated with the newly created lucventurini account.

Dear @ewdurbin , I have just deleted the `lucventurini` account.
If you could now link the LucVen account to my `lucventurini@gmail.com` email address, that would solve the issue for me.
Many thanks for your support!

**Comment by ewdurbin** [comment]
This is complete. You can now perform a reset on the test.pypi.org user LucVen to recover access to your account.

**Comment by lucventurini** [comment]
Dear @ewdurbin , I have now successfully recovered access to the account.
Many thanks for your help!
