### ISSUE TITLE
Issue abandoned due to lack of admin actions

### ISSUE THREAD

**Issue by matijaaa** [pypa/pypi-support#315]
Issue abandoned due to lack of admin actions

**Comment by matijaaa** [comment]
Dear @jamadden & @ewdurbin ,
I am tagging you here since You were most recently active admins / moderators who were resolving PEP 541 issues. Can I kindly ask You to give me an update regarding this issue since it has now been 10 days since it was open? I do understand the current global circumstances, a somewhat large volume of unresolved **pypi-support** issues / requests and limited resources allocated to resolving those, but the sooner my package name request gets processed / resolved, the sooner I can do a public promotion of this open source project.
Cheers!

**Comment by jamadden** [comment]
I have attempted to contact the project owner. We are in the 6-week waiting period (set to expire first of June).

**Comment by matijaaa** [comment]
@jamadden hello! any updates on this? cheers

**Comment by jamadden** [comment]
I have updated the status to reflect that I wasn't able to make contact.

**Comment by matijaaa** [comment]
@ewdurbin Can I kindly ask you to perform the standard transfer routine? Cheers

**Comment by matijaaa** [comment]
@ewdurbin @jamadden  Any updates?

**Comment by pooryorick** [comment]
Hi, I'm the maintainer of the pipeline project.  I do have plans for it, and prefer that it remains the name of the project I initiated.  Granted, I haven't touched it in years.

**Comment by matijaaa** [comment]
@ewdurbin @jamadden Since the author's reply falls outside the 6-week waiting period and author hasn't published any new project releases and you already approved the transfer and marked the issue as "Awaiting admin transfer", is the project still eligible for transfer according to PEP 541 proposals?

**Comment by jamadden** [comment]
I believe we now have to consider the owner *reachable,* according to the PEP's definition, making it an *active* project. 

The PEP says that PyPI moderators "are not arbiters in disputes around active projects," and also says that "Under no circumstances will a name be reassigned against the wishes of a reachable owner."

That said, the only version of pipeline currently published, 0.1, *cannot be installed* using standard installation tools (e.g., pip). It was using external hosting for release files, something that was deprecated and removed from PyPI around 6 years ago in [PEP 470](https://www.python.org/dev/peps/pep-0470/). It's possible that qualifies it as an *invalid* project under the clause "package has no functionality or is empty." 

```console
$ pip install -v pipeline
…
https://pypi.org:443 "GET /simple/pipeline/ HTTP/1.1" 200 122
Given no hashes to check 0 links for project 'pipeline': discarding no candidates
…
ERROR: Could not find a version that satisfies the requirement pipeline (from versions: none)
ERROR: No matching distribution found for pipeline
```

Invalid projects are subject to removal from PyPI at any time.

I would encourage @pooryorick to upload a valid distribution to PyPI soon to ensure that this doesn't happen.

**Comment by matijaaa** [comment]
@jamadden Since there are still no updates regarding the project validity / functionality, therefore meaning the project is still empty, can I get any estimates or updates regarding the transfer status?

**Comment by jamadden** [comment]
Sorry, no estimates are possible. Transfers occur as and when the admins can find some time.

**Comment by matijaaa** [comment]
@jamadden But the current circumstances imply that the project is still eligible for transfer?

**Comment by matijaaa** [comment]
@jamadden But the current circumstances imply that the project is still eligible for transfer?
Do you mind updating the issue label from _Invalid courtesy period_  to  _Awaiting admin transfer_  if so?

**Comment by matijaaa** [comment]
@jamadden But the current circumstances imply that the project is still eligible for transfer?
Do you mind updating the issue label from _Invalid courtesy period_  to  _Awaiting admin transfer_  if so?

**Comment by matijaaa** [comment]
@jamadden But the current circumstances imply that the project is still eligible for transfer?
Do you mind updating the issue label from _Invalid courtesy period_  to  _Awaiting admin transfer_  if so?

**Comment by matijaaa** [comment]
@jamadden But the current circumstances imply that the project is still eligible for transfer?
Do you mind updating the issue label from _Invalid courtesy period_  to  _Awaiting admin transfer_  if so?

**Comment by jamadden** [comment]
@matijaa Please stop repeating the same comment over and over. It is not helpful to ping me repeatedly.

As I said before, this is a bit of a gray area as far as I can see. The owner is reachable and has stated that they will continue using the name. But the current distribution cannot actually be installed. I am interpreting the PEP as giving lots of leeway to the existing owner, which is why I have not changed the project status. Other moderators or admins may interpret the PEP differently, and if they do they'll say so here.
