### ISSUE TITLE
Limit Request: BootTorrent - 65MB

### ISSUE THREAD

**Issue by shreyanshk** [pypa/pypi-support#316]
**Project**
https://pypi.org/project/boottorrent/

**Size of release**
+5MB ; Total size is 65MB

**Which indexes**
PyPi

**Reasons for the request**
BootTorrent is a Python package to do P2P bittorrent based network boot.
As such, it contains some asset files (Linux kernel image + root file system) which are large.
There files are no longer expected to increase in size or change.

**Comment by di** [comment]
I've set the upload limit for `boottorrent` to 100 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
