### ISSUE TITLE
PEP 541 Request: cronicle

### ISSUE THREAD

**Issue by Kraymer** [pypa/pypi-support#317]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/cronicle

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/kraymer

**Reasons for the request**

The project name has been registered by another user, but no releases have been ever created. No pypi page neither.
The project meet the conditions of an abandoned project. 

**Maintenance or replacement?**

I have no information whatsoever about the existing indexed cronicle package.
If successful, a different package will be published : `https://github.com/Kraymer/cronicle`

**Contact and additional research**

I cannot contact the current owner as there is no public pypi information.
A google search gave no result.

**Comment by yeraydiazdiaz** [comment]
Hello @Kraymer, I can confirm the project as no releases and is therefore invalid.

As a courtesy I will attempt contact with the owner, if I receive no reply or objection we will proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
I have received no reply from the current owner so I will now ask an admin to perform the transfer.

**Comment by Kraymer** [comment]
Any news ? @yeraydiazdiaz 
regards

**Comment by ewdurbin** [comment]
transfer complete.
