### ISSUE TITLE
Issue: PEP 541 Request: helios

### ISSUE THREAD

**Issue by filipinascimento** [pypa/pypi-support#319]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/helios

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/filsilva

**Reasons for the request**

The project associated to the requested name does not have any public releases.

**Maintenance or replacement?**

Replacement, I'm a researcher scientist at the Indiana University Network Science Institute and we start developing a network visualization and layouting tool for python called Helios. This is one of my main projects and should be maintained in collaboration with other institutions from Indiana University. The repository for the current project is: https://github.com/heliosnet/helios-core

**Contact and additional research**

There is no link or any information leading to any kind of contact information from the previous owner since there is no public releases.

**Comment by yeraydiazdiaz** [comment]
Hello @filipinascimento, I can confirm the project has no releases and is therefore considered invalid.

I will attempt contact with @voidpp, the current owner, and wait for any objections for a period of one week. If we receive no reply or objection we will move forward with your request.

**Comment by yeraydiazdiaz** [comment]
I have received no response from the project's owner so I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
transfer complete.
