### ISSUE TITLE
Issue: Limit Request: openturns - 80MB

### ISSUE THREAD

**Issue by jschueller** [pypa/pypi-support#320]
**Project**

https://pypi.org/project/openturns

uncertainty treatment library

**Size of release**

OSX wheels for the new release are 63.2mb (osx & win32 ~ 40mb are fine)

**Which indexes**

both

**Reasons for the request**

osx binaries were quite big already (53mb on the previous 1.14 release), now we added some more dependencies (ipopt, bonmin) and we reached the limit.

**Comment by di** [comment]
I've set the upload limit for `openturns` to 100 MB on PyPI. Please be mindful of the frequency of releases at that size.

This project does not exist on TestPyPI and so I cannot raise the limit there. If you need that limit raised, please create the project first and let us know.

**Comment by jschueller** [comment]
@di, thank you
we release every 6 months, so that should not be too much trouble
