### ISSUE TITLE
Issue: PEP 541 Request: reagent

### ISSUE THREAD

**Issue by kittipatv** [pypa/pypi-support#322]
**Project to be claimed**
`reagent`: https://pypi.org/project/reagent

**Your PyPI username**
`kittipat`: https://pypi.org/user/kittipat

**Reasons for the request**
- The project is abandoned by the owner
  - owner not reachable (no contact info)
  - no releases within the past twelve months
  - no home page listed
- Invalid project 
  - project is name squatting (package has no functionality or is empty)

**Replacement**
We have been publishing our project under the name [ReAgent](https://github.com/facebookresearch/ReAgent) since October 2019, see references:

[Announcement](https://ai.facebook.com/blog/open-sourcing-reagent-a-platform-for-reasoning-systems/)
[External ref 1](https://venturebeat.com/2019/10/16/facebooks-reagent-is-a-toolkit-for-reinforcement-learning-and-reasoning-ai/)
[External ref 2](https://towardsdatascience.com/facebook-adds-this-new-framework-to-its-reinforcement-learning-arsenal-919f76dedb09)

We will publish a different package, from the source at https://github.com/facebookresearch/ReAgent

**Contact and additional research**
Current owner doesn't publish contact info. There is no project homepage.

**Comment by hugovk** [comment]
The owner is @notdsk and there is an email address on his profile.

**Comment by kittipatv** [comment]
Ok, I was looking at https://pypi.org/user/notdsk/. The project still looks like name squatting to me.

**Comment by jamadden** [comment]
I concur that this project meets the definition of an invalid/name-squatting project. Current PyPI practice is to give a one-week courtesy notification period for such projects. I've emailed @notdsk using the email address on file with PyPI informing them that the project will be transferred on or after April 22 if it is still invalid.

**Comment by hugovk** [comment]
Yeah, these are all created on 28 Jan 2020 and are pretty much empty boilerplate packages:

https://pypi.org/project/reagent/
https://pypi.org/project/animalia/
https://pypi.org/project/reptilia/
https://pypi.org/project/chordata/
https://pypi.org/project/ravel/
https://pypi.org/project/iter/

**Comment by notdsk** [comment]
For which of my projects are you referring to?  I assure you there is
no name-squatting taking place.  I've received no email from anyone
about this concern.

**Comment by jamadden** [comment]
This issue is about https://pypi.org/project/reagent, though as @hugovk notes there are a number of other projects owned by https://pypi.org/user/notdsk/ that also qualify as invalid/name-squatting.

At Wed, 15 Apr 2020 10:01:50 -0500 with subject "PyPI project reagent: PEP 541 Name Transfer" and Message-ID <E4CE1F01-BF8D-401E-976D-7B4FA4AA5AB4@nextthought.com> I emailed the address associated with that PyPI user; it is the same address associated with the github profile @notdsk.

**Comment by kittipatv** [comment]
@jamadden It's been 7 days and the project is still in the same state as it was. Could we claim the project name?

**Comment by jamadden** [comment]
I have asked the admins to perform the transfer.

**Comment by notdsk** [comment]
Thanks

**Comment by notdsk** [comment]
Thanks for the witch hunt

**Comment by ewdurbin** [comment]
transfer complete.
