### ISSUE TITLE
PEP 541 Request: snooze

### ISSUE THREAD

**Issue by yonromai** [pypa/pypi-support#323]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/snooze

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/yonromai

**Reasons for the request**

[pypi.org/project/snooze](https://pypi.org/project/snooze) returns 404, yet when trying to publish I'm getting a `403 Client Error: The user 'XX' isn't allowed to upload to project 'snooze'.`

Please correct me if I'm wrong but it seems that `snooze` has no releases and therefore can be considered as "under name squatting"?

**Maintenance or replacement?**

Indeed, I'd like to publish & maintain the following tool: https://github.com/yonromai/snooze

**Contact and additional research**

I am unfortunately unable to find the contact details of the owner.

**Comment by jamadden** [comment]
A version of that project was published in 2016 and then removed in 2018. It still exists, but has no releases. I think it may be owned by @vuolter, who I have tagged. I have also emailed the address we have on file. It is PyPI policy to provide owners of invalid/empty projects with 7 days notice before performing a transfer.

**Comment by vuolter** [comment]
Hey guys, no problems here with the transfer. Go ahead. :)

I remember I started a project a long time ago, but then I didn't have time to finish it or something. After that I forgot all about it until today.

Peace.

**Comment by ewdurbin** [comment]
transer complete.
