### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by de-cix** [pypa/pypi-support#324]
Request for account recovery.

## PyPI Username

`de-cix`

---

##  Reason for request

Reason: Lost access to email address

**Comment by de-cix** [comment]
Unfortunately we can't find the password reset mails. Maybe they go to an individual mailbox or to an old role account that has been disabled. Please kindly set it to "pypi@de-cix.io" (yes, we own that domain as well). If this looks to strange to you (which I can understand) please set it to my personal address: alexander.claude@de-cix.net and I will change it afterwards to the role account.

Thanks and best regards,
/Alex

**Comment by ewdurbin** [comment]
Hello @de-cix I see that the user is associated with an @de-cix.net user email address as is the sole project the user has ownership on [pbgpp](https://pypi.org/project/pbgpp/).

Given that, if you can provide an @de-cix.net email address you would like to update the account with we can proceed with that.

**Comment by de-cix** [comment]
Hey @ewdurbin and thanks for following up.  
Please set it to "syseng@de-cix.net".

**Comment by ewdurbin** [comment]
@de-cix email address for the user has been updated. You should now be able to issue a password reset requests and proceed with account recovery.
