### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jon-betts** [pypa/pypi-support#325]
Request for account recovery.

## PyPI Username

`jon.betts.hypothes.is`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

I was logging in to change permissions on a package I've just uploaded: https://pypi.org/project/h-api/ to allow our team account to access it (eng.hypothes.is).

I don't remember setting up 2FA on this account, but I suppose I must have. The page suggests I use recovery tokens, but these weren't available when I setup the account.

## Alternative fixes

I'd be equally happy if:

 * We could recover my account
 * The "eng.hypothes.is" account could be granted ownership of the project
 * The "h_api" project could be deleted fully so it doesn't squat the namespace and I could re-upload it as the "eng.hypothes.is" account

Sorry, this is a real pain I'm sure.

I have access to both email accounts and passwords for both the `jon.betts.hypothes.is` accounts and the `eng.hypothes.is` accounts, and 2FA access for the `eng` one. You should be able to see I've shared ownership for all the previous "h-*" packages too between the accounts.

_edit_: Oh I forgot to say, I still have access to a token to update the project, so if you need me to put something in the package to show I own it, I can do that too.

Thanks,
Jon

**Comment by jon-betts** [comment]
Oh I forgot to say, I still have access to a token to update the project, so if you need me to put something in the package to show I own it, I can do that too.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
