### ISSUE TITLE
Limit Request: fluxengine - 148MB

### ISSUE THREAD

**Issue by THolding** [pypa/pypi-support#326]
**Project**
fluxengine
PyPI page: https://pypi.org/manage/project/fluxengine/release/4.0.dev2/

**Size of release**
Total size: 148MB
Size above limit: 88MB

**Which indexes**
PyPi

**Reasons for the request**
FluxEngine is an open source toolbox designed to help climate researchers calculate atmosphere-to-ocean transfer of green house gases. It is aimed to be accessible for non-expert Python users, so comes with Jupyter notebook tutorials and verification tools. The verification tools require some data files to run (masks and geographic data) to allow users to verify their calculations against a set of known reference values. This data is approximately 120MB in size.

The size required is unlikely to grow significantly in the future. 160-200MB would certainly meet our needs.

**Comment by jamadden** [comment]
The limit has been set to 200MB on pypi.org.
