### ISSUE TITLE
PEP 541 Request: splunk-appinspect

### ISSUE THREAD

**Issue by rfaircloth-splunk** [pypa/pypi-support#327]
`PROJECT_NAME`: https://pypi.org/project/splunk-appinspect
`USER_NAME`: https://pypi.org/user/rfaircloth-splunk

I believe the present project was created as a place holder to publish at a later time and was never completed. I am the product owner for this tool and would like to publish active versions at this time. No releases have been published so I am unable to confirm the project will publish is indeed the same

I have queried internal contacts and can not identify who may have reserved this project name.

**Comment by yeraydiazdiaz** [comment]
Hello @rfaircloth-splunk, looks like you're already an owner of this project so I will now close this issue.
