### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by greyli** [pypa/pypi-support#330]
Request for account recovery.

## PyPI Username

`greyli`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

Hi, I think I set up the 2FA before, but the PyPI account not list on my 2FA application currently, it may be lost when I migrate my phone. Please reset my PyPI account's 2FA setting, thanks!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
