### ISSUE TITLE
Request for edit - NOT TAKEDOWN - of pythonhosted.com documentation

### ISSUE THREAD

**Issue by Legorooj** [pypa/pypi-support#332]
I'm one of the primary maintainers of [PyInstaller](https://github.com/pyinstaller/pyinstaller). I've noticed that `https://pythonhosted.org/PyInstaller` is registering on google - and many many SO questions - first. The documentation is 4 years old, and, for a project like PyInstaller, which is *very* actively developed, this is a bit of a problem for us. (Our up to date docs are at https://pyinstaller.rtfd.io)

This issue is related to #59 and https://github.com/pypa/warehouse/issues/5641#issuecomment-478095714. However, in this case, becuase this documentation URL is so well known, would it be possible to have a page saying "The pyinstaller docs have moved to https://pyinstaller.readthedocs.io"? We'd prefer not to have it removed if possible, just forwarded; the https://pythonhosted.org/pyinstaller url is too well known.

**Comment by ewdurbin** [comment]
@Legorooj a redirect has been configured. requests to https://pythonhosted.org/PyInstaller/ will be redirected to https://pyinstaller.readthedocs.io/

**Comment by Legorooj** [comment]
@ewdurbin thanks for your help!
