### ISSUE TITLE
Request for extra memory

### ISSUE THREAD

**Issue by nlpai-lab** [pypa/pypi-support#333]
kukolex 0.1.18

**Project**
 kukolex

**Size of release**
 60.8M

**Which indexes**
 both!

**Reasons for the request**
 We added C source code.

**Comment by jamadden** [comment]
The project needs to exist before the limits can be changed. It does not seem to exist on pypi.org.

**Comment by di** [comment]
We also need some additional details: what is this project? Why is it so large?

**Comment by nlpai-lab** [comment]
We uploaded kukolex=0.0.0 file.
Project

kukolex=0.0.0
Size of release

We need at least 62MB due to lots of dictionary files for morpheme analyzing.
Which indexes

PyPI
Reasons for the request

We expect size limit of 0.0.1 version of our file to be increased to 62MB, so that we can upload our whole file. Thank you!

**Comment by jamadden** [comment]
The default limit is 100MB. There have been several releases of kukolex since this issue was opened with files larger than the old 60MB default limit. So I think this can be closed as fixed.
