### ISSUE TITLE
Request trove classifier: cocotb

### ISSUE THREAD

**Issue by eric-wieser** [pypa/pypi-support#334]
### The name of the classifier you would like to add
* `Framework :: cocotb`

### Why do you want to add this classifier?

cocotb has an ecosystem of domain specific libraries built on top of it, some of which are listed on our [further resources page](https://github.com/cocotb/cocotb/wiki/Further-Resources#extension-modules-cocotbext) (and the section below that link). We believe a classifier would help with discoverability of these packages. `Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)` does not fulfill this need as there are many non-cocotb EDA packages.

**Comment by jamadden** [comment]
Thanks for the request! Classifiers are now managed at [pypa/trove-classifiers](https://github.com/pypa/trove-classifiers/issues). Could you please [open this issue there](https://github.com/pypa/trove-classifiers/compare)? (I can't transfer it automatically for some reason.)

**Comment by eric-wieser** [comment]
Whoops, was wondering why the template I was looking for seemed to no longer be there.

Opened https://github.com/pypa/trove-classifiers/pull/24
