### ISSUE TITLE
Increasing size limit for paddlepaddle_gpu: 450MB

### ISSUE THREAD

**Issue by kolinwei** [pypa/pypi-support#335]
Hi. We will release a new version for paddlepaddle_gpu recently. Our current size limit is 350M, and the last version is 330M. Because a few new features are enabled in this version, the package size will go to 380MB. Can you please help to increase this to around 450MB.

Project:
https://github.com/PaddlePaddle/Paddle
https://pypi.org/project/paddlepaddle-gpu/

**Comment by kolinwei** [comment]
Any update for this issue? Your help is most appreciated。
We will release a new version on May 2，and really need your help

**Comment by di** [comment]
I've set the upload limit for `paddlepaddle_gpu ` to 450 MB on PyPI. Please be mindful of how frequently you make releases with such a high limit -- each release will have a significant impact on how much traffic PyPI has to serve.

This project does not exist on TestPyPI and so I cannot raise the limit there. If you need that limit raised, please create the project first and let us know.
