### ISSUE TITLE
PEP 541 Request: pip-compile

### ISSUE THREAD

**Issue by jezdez** [pypa/pypi-support#336]
**Project to be claimed**

`pip-compile`: https://pypi.org/project/pip-compile

**Your PyPI username**

`jezdez`: https://pypi.org/user/jezdez

**Reasons for the request**

Following https://github.com/graingert/pip-compile/issues/1 and feedback from @ewdurbin there, I'm requesting (as https://github.com/jazzband admin) the transfer of the pip-compile project to my PyPI user account so that we can add it to the list of blocked project names on PyPI.

`pip-compile` is one of two entrypoint scripts (next to the already blocked `pip-sync`) included in the [pip-tools package](https://github.com/jazzband/pip-tools) maintained by [Jazzband](https://jazzband.co).

**Maintenance or replacement?**

The intention is to stop releasing the project and replace it with an entry in the blocked names database.

**Contact and additional research**

https://github.com/graingert/pip-compile/issues/1
https://github.com/jazzband/pip-tools/issues/1000

**Comment by graingert** [comment]
@yeraydiazdiaz how do I add the package to the blacklisted packages?

**Comment by ewdurbin** [comment]
That's an admin action, not available to end users. You'd just need to confirm that's what you want either here or on the original issue.

**Comment by jezdez** [comment]
@yeraydiazdiaz Apologies for the confusion, this isn't purely a transfer but also a request to add pip-compile to the list of blocked package names following @ewdurbin's comment in the original comment.

**Comment by graingert** [comment]
@ewdurbin yeah please could you blacklist the package "pip-compile", and if https://github.com/pypa/warehouse/issues/7840 is accepted could you add a redirect to "pip-tools"

**Comment by ewdurbin** [comment]
okay, the project has been removed and added to the prohibited name list for re-registration.

**Comment by jezdez** [comment]
Thank you @ewdurbin!

**Comment by ewdurbin** [comment]
@jezdez if pip-tools maintainers would like to control the `pip-sync` and `pip-compile` projects on PyPI, another issue can be opened.

**Comment by jezdez** [comment]
And thank you @graingert! :)
