### ISSUE TITLE
Limit Request: HUMAnN - 65 MB

### ISSUE THREAD

**Issue by ljmciver** [pypa/pypi-support#337]
**HUMAnN**

Repository: https://pypi.org/project/humann

**Size of release**
 65 MB

**Which indexes**
PyPI

**Reasons for the request**
With the version 3 release one of our mapping files has increased in size and we are just a bit above the current 60 MB limit. We removed some example files to fall back to the max size. With updates to the software we will need more space.

Could you please increase our size to at least 65 MB but ideally 75 MB if possible to give us a bit more space for more data files?

**Comment by jamadden** [comment]
The limit has been set to 100MB on PyPI.
