### ISSUE TITLE
Limit Request: pgAdmin4 - 100MB

### ISSUE THREAD

**Issue by dpage** [pypa/pypi-support#338]
**Project**
https://test.pypi.org/project/pgadmin4/

**Size of release**
Todays full build came in at 76MB, so I'd appreciate an increase to 100MB.

**Which indexes**
Both

**Reasons for the request**
pgAdmin 4 is the leading Open Source web based management tool for the PostgreSQL database server. Recent packages have been around 70-80MB (though that does increase as features are added), and we're now looking to include them on PyPi due to user demand. The most recent of our monthly releases can be found at https://www.postgresql.org/ftp/pgadmin/pgadmin4/v4.20/pip/. The website is at https://www.pgadmin.org/

Thank you!

**Comment by jamadden** [comment]
Hi,

The project needs to be created before any limits can be changed. It doesn't yet appear to exist on PyPI.

**Comment by dpage** [comment]
Sorry, I'd created it on test but didn't realise it needed to be in both. I've uploaded my dummy package to PyPi to create the project, and then immediately deleted the release so people don't install it by mistake. Is that enough to proceed?

**Comment by jamadden** [comment]
Sure was. The limit has been set to 100MB on both indexes.

**Comment by dpage** [comment]
Thank you!
