### ISSUE TITLE
PEP541: Squatter on `fashion`

### ISSUE THREAD

**Issue by Miserlou** [pypa/pypi-support#34]
Hey all!

I'd like to use the package name 'fashion' for a new FaaS library I'm working on, but it looks like it is squatted (registered by a user who's email doesn't work, no other packages, no code submitted), can you please make it available so that I can register a package there?

This is my PyPI: https://pypi.org/user/miserlou/
This is the name I'd like to use: https://pypi.org/project/fashion/

There is no code or license or working homepage or working contact information, so I don't think this should be too much of a problem. Otherwise, I'll have to come up with another pun for "faas" but I'd rather not call my project "faascist" or "faascile"! 

Thanks!

**Comment by yeraydiazdiaz** [comment]
Hello @Miserlou, I can confirm at this point in time the project `fashion` has a single release with no files and can thus be considered invalid.

Can you confirm your PyPI username, please?

**Comment by yeraydiazdiaz** [comment]
@Miserlou, are you still interested in this transfer?

**Comment by Miserlou** [comment]
Yes! I'm miserlou on PyPi

**Comment by ewdurbin** [comment]
transfer complete.
