### ISSUE TITLE
Limit request: backend.ai-krunner-{ubuntu,centos,alpine} 120 MB for each

### ISSUE THREAD

**Issue by achimnol** [pypa/pypi-support#340]
**Project**

* https://pypi.org/project/backend.ai-krunner-ubuntu
* https://pypi.org/project/backend.ai-krunner-centos
* https://pypi.org/project/backend.ai-krunner-alpine

**Size of release**

120 MiB for each of the three packages

**Which indexes**

PyPI only.

**Reasons for the request**

These packages contains one or more xz-compressed tarball of "kernel runner environment" Docker volume archives for several Linux distributions optimized for running a small coordinator daemon ("kernel runner") inside arbitrary Docker images on [Backend.AI](https://github.com/lablup/backend.ai) clusters.

For instance, `backend.ai-krunner-ubuntu` package contains environment images for Ubuntu 16.04 and 18.04. Each tar.xz archives takes about 20-30 MiB, and we are going to add a few more in the near future (e.g., Ubuntu 20.04 / CentOS 8 / Alpine 3.11).

Of course, we won't accumulate the archives infinitely but keep only latest 2 or 3 versions of each Linux distributions. We also have been trying to minimize the size using Docker's multi-stage builds, xz compression, and bundling only the isolated Python and package directory (each volume archives are mounted as `/opt/backend.ai` in user containers).

Still, adding more packages and distribution supports to the environment volume archives may touch the package size limit of 60 MiB, and I believe that 120 MiB would be good for now. I am writing this request since our newly built `backend.ai-krunner-alpine` package just hit 60.1 MiB and I got upload failure.

**Comment by di** [comment]
I've set the upload limit for all three projects to 120 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by achimnol** [comment]
Thanks! I'll do my best to keep the package sizes small.
