### ISSUE TITLE
Issue: Limit Request: itk-core, itk-filtering - 100MB

### ISSUE THREAD

**Issue by thewtex** [pypa/pypi-support#341]
**Project**

Can we please get a 100 MB size limit increase for:

- [itk-core](https://pypi.org/project/itk-core/)
- [itk-filtering](https://pypi.org/project/itk-filtering/)

**Size of release**

We are requesting a size increase of 100 MB for both packages.

**Which indexes**

PyPI and Test PyPI.

**Reasons for the request**

These packages are for open source scientific image analysis, and they are built from a [large C++ codebase](https://github.com/InsightSoftwareConsortium/ITK). We currently have to build with `-Os` optimizations to achieve the size limit, but we would like to build with `-O2`. A 100 MB limit should suffice for the foreseeable future.

Thank you for maintaining and hosting PyPI. :pray:

**Comment by di** [comment]
I've set the upload limit for both projects to 100 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by thewtex** [comment]
@di thank you!
