### ISSUE TITLE
Name request: "gitlab-art"

### ISSUE THREAD

**Issue by JonathonReinhart** [pypa/pypi-support#342]
**Project to be claimed**
[`gitlab-art`](https://pypi.org/project/gitlab-art/)

**Your PyPI username**
[`jreinhart`](https://pypi.org/user/jreinhart/)

**Reasons for the request**
There is nothing visible on the PyPI project page. However, when I try to upload, I get the following error:
```
HTTPError: 403 Client Error: The user 'jreinhart' isn't allowed to upload to project 'gitlab-art'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

However, browsing to [`gitlab-art`](https://pypi.org/project/gitlab-art/) yields a 404 error.

Therefore, I must assume that either:
- Someone is somehow squatting on the name
- The 403 error I am receiving is a red herring

@kosma and I maintain this project on GitHub: [`gitlab-art`](https://github.com/kosma/gitlab-art) and even recently changed the name from `art` to `gitlab-art`, thinking it was available on PyPI.

**Maintenance or replacement?**
N/A -- As far as I can tell there is no existing `gitlab-art` package on PyPI.

**Contact and additional research**
I have no insight into the `gitlab-art` project on PyPI -- There is no visible information. We are aware of no existing project and therefore no other owner to contact.

**Comment by kosma** [comment]
I confirm we want to use this project name. I'd prefer to have the project on my own account (my pypi username is `kosma`) - I can add @JonathonReinhart as a maintainer.

**Comment by yeraydiazdiaz** [comment]
Hello @JonathonReinhart, I can confirm the project has no releases and can therefore be considered invalid.

I will attempt contact with the current owner `abandonedtools` via email, if I don't receive a reply we can proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
I have not recevied a response from the current owner so I will now ask an admin to perform the transfer.

**Comment by JonathonReinhart** [comment]
Thanks @yeraydiazdiaz. As indicated above @kosma can be owner and I can be maintainer.

**Comment by ewdurbin** [comment]
project Owner role transferred to `kosma` user on PyPI.

**Comment by JonathonReinhart** [comment]
Thanks a lot, @yeraydiazdiaz and @ewdurbin.
