### ISSUE TITLE
PEP 541 Request: pyppeteer

### ISSUE THREAD

**Issue by Granitosaurus** [pypa/pypi-support#344]
**Project to be claimed**

`pyppeteer `: https://pypi.org/project/pyppeteer 

**Your PyPI username**

`granitas`: https://pypi.org/user/granitas 

**Reasons for the request**

The [last commit](https://github.com/miyakogi/pyppeteer) occurred in May of 2019, one year minus a couple weeks ago. The last release was in late September of 2018. Since then, it has accrued more than 20 open pull requests, all with no response from the single maintainer, @miyakogi. The most critical PR fixes a bug where the library would fail after 20s of communication with the browser process, making nearly unusable in its current state.

**Maintenance or replacement?**

It is my intention to maintain the current project, providing updates in line with the original projects goal. A github organization and new namespace has been founded to continue work:  https://github.com/pyppeteer/pyppeteer2/

(Note: most work has been conducted on the `pup2.1.1` branch. See this PR: https://github.com/pyppeteer/pyppeteer2/pull/16)

**Contact and additional research**

Besides the many mentions from current GitHub repo, I've tried to email the old maintainer in January of 2020 with no response; additionally @Mattwmaster58 has personally emailed the maintainer at the end of February 2020, with no response either.   
@miyakogi appears to have a possibly [associated Twitter account](https://twitter.com/miyakogi?lang=en), which @Mattwmaster58 also tried to follow, but has thus far remained unsuccessful.

**Comment by Mattwmaster58** [comment]
Also worth noting that the last commit pushed by @miyakogi to any Github repo was on September 11 of 2019 to his dotfile repo.

**Comment by yeraydiazdiaz** [comment]
Hi @Granitosaurus, I'll attempt contact with the current owner as stated in the [reachability section of the PEP](https://www.python.org/dev/peps/pep-0541/#reachability). Sometimes us moderators have more luck in receiving a response.

**Comment by polyzen** [comment]
Will you change the project name back to `pyppeteer` from `pyppeteer2` if you get https://pypi.org/project/pyppeteer?

**Comment by Mattwmaster58** [comment]
@polyzen We are intending to take over the pyppeteer package (otherwise why would we be filing this request 😉)

**Comment by Granitosaurus** [comment]
Yes, pyppeteer2 isn't really a new package or api - its contiuation of the project with a bumped name because we couldn't get the hold of the original name.

The name pyppeteer would be much more suited for pyppeteer2 project.

-------- Original Message --------

**Comment by polyzen** [comment]
Sorry, I meant the GitHub project name. Have been working to add requests-html to the Arch repos as an optional dependency of urlwatch, which has led me to have to wrap my head around the pyppeteer situation 🥴. Wasn't sure if I should make a `python-pyppeteer2` package or just have the `python-pyppeteer` package use pyppeteer2. In that case I will do the latter.

Thanks for the quick responses!

**Comment by miyakogi** [comment]
I'm sorry for long absence. I have had a disease for a long time and it's difficult to keep maintaining the project. I apologize for not announcing that.
As I have already sent email to the moderator, I agree with the transfer of the project ownership.

I appreciate for you to continue the project, and I'm sorry again for inconvenience for a long time for the users.

**Comment by polyzen** [comment]
@miyakogi, if you're up for it, maybe you can hand over the PyPI project yourself to simplify things. I'm not familiar with the process.

I think it would also be a good idea to move your pyppeteer repo over to https://github.com/pyppeteer to avoid fragmentation, keep the stars, followers, issues, etc.

**Comment by polyzen** [comment]
Seems like it should be a simple process, though it doesn't explain the details:
https://pypi.org/help/#request-ownership

And https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by miyakogi** [comment]
Thank you for suggestion.
I'll follow the decision of the new maintainers and the moderator.

**Comment by Mattwmaster58** [comment]
@polyzen I think we'll actually pass on the GitHub repo transfer. The previous repo has a lot (most?) of issues that are un-reproducable and irrelevant at that point. Stars + Wiki don't matter all that much to me at the moment. Almost every (if not every) PR is moot by the work we've already done. So there would be little tangible benefit in doing so.

**Comment by polyzen** [comment]
Then, @miyakogi, please add something to the top of your readme to point people to the new repo and make the repo read-only.

**Comment by miyakogi** [comment]
@polyzen Sure. I'll do that after transferring the ownership.

**Comment by yeraydiazdiaz** [comment]
Hi @miyakogi, thanks for getting back to us about this issue.

Transferring ownership is as follows:

1. Log into pypi.org
2. Navigate to https://pypi.org/manage/project/pyppeteer/collaboration/
3. In the "Add collaborator" section add PyPI user `granitas` with the Role "Owner"

**Comment by miyakogi** [comment]
I did it.
Thank you!

**Comment by miyakogi** [comment]
@polyzen I have added a link to the new repo on the top of the readme of the old repo, and have archived the old repo.

**Comment by yeraydiazdiaz** [comment]
Thank you all for your collaboration.
