### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wmshort** [pypa/pypi-support#345]
Request for account recovery.

## PyPI Username

wmshort

---

##  Reason for request

  - Lost 2FA authentication app or security token
-->

Reason:
Switched phone and cannot log onto pypi to set up authentication app without first authenticating...

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by wmshort** [comment]
Thank you!

William Michael Short
Lecturer in Classics & Ancient History
University of Exeter
Phone: 01392 724794
E-mail: w.short@exeter.ac.uk
Amory Building, Rennes Drive, Exeter, Devon, EX4 4RJ
Ancient Greek WordNet<https://greekwordnet.chs.harvard.edu/> | Latin WordNet<https://latinwordnet.exeter.ac.uk/> | Cylleneus: Next-gen corpus search for ancient languages<https://github.com/cylleneus>
[http://www.exeter.ac.uk/codebox/email-sig/staff-sig.gif]
This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this email and its attachments.
