### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by chaitanyakasaraneni** [pypa/pypi-support#348]
Request for account recovery.

## PyPI Username

`chaitanya_k`

---

##  Reason for request

Reason: Lost 2FA authentication app or security token and did not generate security codes

**Comment by ewdurbin** [comment]
Hi @chaitanyakasaraneni! As this account was created after we implemented Recovery Codes, could you share why you did not generate Recovery Codes before we proceed with recovery? This will help us understand how we can better direct users to do so in the future and save valuable time spent on these sorts of account recovery related tasks.

**Comment by chaitanyakasaraneni** [comment]
Hi @ewdurbin. I got to know about the recovery codes after I lost access. In the future, it would be better if there is a prompt similar to 2FA or email them to generate recovery codes after successful activation of account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by chaitanyakasaraneni** [comment]
Hi I have replied to the email.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
