### ISSUE TITLE
PEP 541: transfer ownership of invalid `vision`

### ISSUE THREAD

**Issue by julien-c** [pypa/pypi-support#349]
## Project to be claimed

`vision`: https://pypi.org/project/vision

**Your PyPI username**

`chaumond`: https://pypi.org/user/chaumond

## Reasons for the request

**Package appears to be invalid in the sense of [PEP 541](https://www.python.org/dev/peps/pep-0541/#invalid-projects):**

> **project is name squatting (package has no functionality or is empty)**

Project has a single release with no files associated.

<br>

**Maintenance or replacement?**

At Hugging Face we publish the popular Transformers library for Natural language processing: 

- https://pypi.org/project/transformers/
- https://github.com/huggingface/transformers

We would like to publish a new package for computer vision under the `vision` name.

**Contact and additional research**

Contacted the current owner via email.

**Comment by yeraydiazdiaz** [comment]
Hi @julien-c, on 2020-04-29 23:27:14 PyPI user ` dhyahoo` created a new release. The [description](https://pypi.org/project/vision/#description) reads:

> This package defines the Verizon Media internal machine Vision packaging namespace.
This package is present in the Public PyPi repositories to prevent package conflicts between Open Source Python packages and Verizon Media internal packages.

Uploading empty packages to PyPI for this purpose is not allowed, however, we do have a list of disallowed names for different purposes like preventing typo-squatting or trademark violations. I'm not sure if this case would fall under that category, @pypa/pypi-moderators any thoughts?

Tagging who I believe the owner's GitHub user @dwighthubbard.

**Comment by pradyunsg** [comment]
I think we should consider this an invalid project.

I do not think namesquatting on PyPI, to prevent conflicts with a company's internal packages is reasonable, and I think we should actively discourage the same.

**Comment by aaugustin** [comment]
If I understand correctly:

- the purpose for which the empty `vision` package was created isn't allowed — and, in fact, should be discouraged;
- after six weeks, no dissenting opinion was expressed.

May I kindly request that you proceed with the transfer to user `chaumond`?

**Comment by yeraydiazdiaz** [comment]
There have been no further releases or replies from the owner, the transfer is now complete. Apologies for the delay.

**Comment by aaugustin** [comment]
Thank you!
