### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by d3vnu1l** [pypa/pypi-support#350]
Request for account recovery.

## PyPI Username

`d3vnu1l`

---

##  Reason for request

Reason:
I replaced my old phone through insurance and no longer have access to the 2FA device on it. Unfortunately I had not yet generated a recovery code.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@d3vnu1l did you receive the email with steps for recovery?

**Comment by d3vnu1l** [comment]
@ewdurbin Thanks, I've received the email and taken corresponding action.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
