### ISSUE TITLE
Issue: Limit Request: estnltk - 100MB

### ISSUE THREAD

**Issue by soras** [pypa/pypi-support#351]
**Project**

https://pypi.org/project/estnltk
https://test.pypi.org/project/estnltk

I ran into the "File too large" error in test.pypi.org . I haven't actually tried uploading to pypi.org , but I assume limits are same on both servers, and so I need the size to be increased on both.

**Size of release**

100MB

Note:  The current release itself will be smaller, but I do forsee that we will be approaching to 100MB in future as more models will be added to the package. So, I would be thankful if the size limit can be increased to 100MB.

**Which indexes**

PyPI
Test PyPI

**Reasons for the request**

Estnltk is a natural language processing package, and it needs to include some large lexicon and machine-learning model files required by the algorithms.

**Comment by di** [comment]
I've set the upload limit for `estnltk` to 100 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
