### ISSUE TITLE
PEP 541 Request: DenyHosts

### ISSUE THREAD

**Issue by josev814** [pypa/pypi-support#352]
**Project to be claimed**

`DenyHosts`: https://pypi.org/project/DenyHosts/

**Your PyPI username**

`josev814`: https://pypi.org/user/josev814/

**Reasons for the request**

The PyPi repository has been abandoned, and I'm currently unable to reach the maintainer of the project. https://pypi.org/user/criticalcore/  There is no contact information for the user, and they are not part of the GitHub repository used to maintain the Package.

**Maintenance or replacement?**

I'm currently one of the maintainers for the GitHub repo, and I plan to continue the maintenance of the package.  We are having instances where users are attempting to install our package from PyPi and end up with outdated configs, because of the package being out of date.  I'd like to ensure that the package is kept up to date and in sync with updates from our GitHub repository.
https://github.com/denyhosts/denyhosts

**Contact and additional research**

Current Maintainer: https://pypi.org/user/criticalcore/
The code originally produced by Phil Schwartz under GPL2, but all attempts to reach him have ended up being unresponsive. phil_schwartz@users.sourceforge.net.
All of the users maintaining the repo under GitHub have been unable to get ahold of Phil Schwartz or criticalcore.  Any search within google for "criticalcore" to find any additional information ends up show the DenyHosts PyPi repo or the a single message in ubuntu's IRC from 2011.  I'm unable to find any contact information for that user.

**Comment by hugovk** [comment]
Looks like @philschwartzsonos is the same person, but no public activity on that account.

To confirm, here's a Phil Schwartz with DenyHosts listed from 2005, now at Sonos: https://www.linkedin.com/in/philschwartz/

And perhaps this mailzilla.net email will work too:
https://web.archive.org/web/20180609145433/http://www.phil-schwartz.com/contact.spy

**Comment by josev814** [comment]
@hugovk Thank you for those links.  I sent him a connection request on LinkedIn asking for permission to get maintenance access to the PyPi package.  I'll post any response I get here.

**Comment by josev814** [comment]
This was the reply I got from Phil Schwartz
```Hey Jose.  I haven't had time to work on DH in years but don't recall it ever being a PyPi package at all.  Perhaps someone else maintained that?  Not really sure.```

Since criticalcore's contact info isn't listed anywhere, I think that should suffice in changing the DenyHosts PyPi ownership, right?

**Comment by yeraydiazdiaz** [comment]
Hi @josev814, it's good you got a response from Phil but unfortunately he's not the owner of the package so we'll have to abide by the [reachability rules in the PEP](https://www.python.org/dev/peps/pep-0541/#reachability).

Moderators do have access to the email associated with PyPI user `criticalcore`, I'll attempt contact now. Hopefully we'll hear back from `criticalcore` and move forward with your request.

**Comment by yeraydiazdiaz** [comment]
I have not received any reply from the current owner so the project is now considered abandoned. I will now ask an admin to perform the transfer for you.

**Comment by josev814** [comment]
Thank you so much!!

**Comment by ewdurbin** [comment]
Transfer complete.
