### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by omartin2010** [pypa/pypi-support#353]
Request for account recovery.

## PyPI Username

`omartin2010`

---

##  Reason for request

Reason:
restored phone and somehow the configuration wasn't restored for any of my 2FA, but I was able to, with some other systems, restore access using SMS or other methods, but I forgot to take the recovery codes for pypi...

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
