### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by AntoineToussaint** [pypa/pypi-support#356]
Request for account recovery.

## PyPI Username

`roardata`

---

##  Reason for request

Reason:

As part of a group inside JPM, we had created a roardata.com email address but the account has been deleted and I don't remember the password I used.

To show that I am the owner of this, I also uploaded another package today (maybe I can get my password from my local machine?): squig.

Please let me know what I can do.

Thank you.

**Comment by ewdurbin** [comment]
@AntoineToussaint if you were able to upload using the account and have not previously created API tokens for the account, then your password is stored locally somewhere (likely in a `.pypirc` file). If you're unable to recover the password from that or some other local keychain, please reopen and we'll proceed with account recovery.

**Comment by AntoineToussaint** [comment]
Thanks a lot! Indeed, I said `maybe I can get my password from my local machine`, the pypirc was right there! ;)
