### ISSUE TITLE
PEP 541 Request: deeptrack

### ISSUE THREAD

**Issue by BenjaminMidtvedt** [pypa/pypi-support#357]
**Project to be claimed**

`deeptrack`: https://pypi.org/project/deeptrack

**Your PyPI username**

`BenjaminMidtvedt`: https://pypi.org/user/BenjaminMidtvedt

**Reasons for the request**

The project is neither searchable nor installable, but the name is restricted. I argue that this falls under the abandoned projects clause / name-sqautting clause.

**Maintenance or replacement?**

I will replace the project with the following: 
`deeptrack`: https://github.com/softmatterlab/DeepTrack-2.0

**Contact and additional research**

I have been unable to contact the owner since the project is not indexed on PyPI. The is a project named deeptrackpytorch that claims to be a "PyTorch version of deeptrack", with no reference to the original deeptrack. I believe this is in reference to a GitHub called Deeptracking which has an issue requesting a PyTorch version, not a PyPI package deeptrack.

**Comment by yeraydiazdiaz** [comment]
Hello @BenjaminMidtvedt, I can confirm the project has no releases and is therefore considered invalid.

In these cases we send a courtesy email to the current owner and wait for a week before moving on with with request, I will do that now.

**Comment by bjudkewitz** [comment]
We are a research lab at the Charite in Berlin and have an ongoing project with pending releases. The project is not abandoned. Please do not transfer it.

**Comment by BenjaminMidtvedt** [comment]
Hi. I don't know how long this project has been running for but I would argue that if the name has been held for any relevant time, then this is still name-squatting. This is however up to the support to decide, and I would much prefer to come to an agreement. I would also like to note that this is a long-standing project of ours, with [published results from a year ago](https://www.osapublishing.org/optica/abstract.cfm?uri=optica-6-4-506). It may then be significantly easier for your group to reconsider the name. It may also not be ideal to develop a research package under a preexisting name, as this might lead to confusion. 

I hope we can come to an agreement.

**Comment by bjudkewitz** [comment]
The support can confirm that the project has been registered in the end of 2019. It's neither abandoned nor being squatted on. I believe this issue should be closed.

I am not sure what you mean by agreement. I am certainly not expecting anything in return for transferring a name, and although I didn't check, I'm pretty sure it's against the rules. If you are asking us for a favor then this is a strange way of doing that. Asking politely is usually the way to go and will often get you pretty far.

**Comment by BenjaminMidtvedt** [comment]
I apologize if I came off hostile, it was not my intent. An agreement would have been both of us finding a name we would be happy with. I wanted to open a dialogue to check if you would consider finding a different name for your project. If that did not come across, I once again apologize.

**Comment by bjudkewitz** [comment]
We will think of another name. I added you as owner. Feel free to remove me.

**Comment by BenjaminMidtvedt** [comment]
I sincerely thank you, I wish you the best of luck on your research project.

**Comment by bjudkewitz** [comment]
Good luck to you!
