### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Rahul-RB** [pypa/pypi-support#358]
Request for account recovery.

## PyPI Username

`Rahul-RB`

---

##  Reason for request

Reason: I had to factory reset my mobile to adhere with company policy. Before doing that, I did take recovery codes on for my account. But when I press "Login with Recovery code" button, I get taken back to login page with this error: "Invalid or expired two factor login. "

Please help me recover this account.

**Comment by ewdurbin** [comment]
Hi @Rahul-RB this is a bug that has now been resolved via https://github.com/python/pypi-infra/commit/9631d47c3738ddff7df064cb5fe34bbf9583c107. Thank you for your report.

You should be able to use your recovery code now.
