### ISSUE TITLE
PEP 541 Request: gyt

### ISSUE THREAD

**Issue by juanbenitopr** [pypa/pypi-support#359]
**Project to be claimed**
`gyt`: https://pypi.org/project/gyt/

**Your PyPI username**
`juanbenitopr`: https://pypi.org/user/juanbenitopr

**Reasons for the request**
The project was abandoned, the latest and unique release was in 2016. There is no repository attached, description or any additional information.

**Maintenance or replacement?**
I would like to publish another package, the repository is:

https://github.com/juanbenitopr/gyt

**Contact and additional research**
It was not possible contact the previous owner, he didn't specify any email, or other communication information.

**Comment by hugovk** [comment]
There's an email on one of their other recently-updated projects: https://pypi.org/project/gmsh-api/, you could try that?

And that links to https://github.com/lepy/gmsh_api, so ping @lepy.

**Comment by juanbenitopr** [comment]
Thanks hugovk, I didn't see the project. I have just sent him an email, I will post the upgrades :)

**Comment by juanbenitopr** [comment]
@hugovk I sent @lepy an email the last week, and I created a issue in the gmsh_api repository asking about the name a couple of days ago. I have not received any answer yet. What I should do?

**Comment by hugovk** [comment]
I expect the moderators here will try to make contact too per [PEP 541](https://www.python.org/dev/peps/pep-0541/), and if they hear nothing back after 6 weeks, and the other criteria are met, will likely transfer it over.

**Comment by yeraydiazdiaz** [comment]
Hi @juanbenitopr, I've emailed the author regarding your claim, hopefully we will hear back soon and move forward with your request.

**Comment by juanbenitopr** [comment]
Hi @yeraydiazdiaz , 

I have just decided to choose another name for my project, I thought transferred the name would be a simpler process.

Thank a lot for your work here!
Regards
