### ISSUE TITLE
Issue: Limit Request: VTK - 175MB

### ISSUE THREAD

**Issue by tjcorona** [pypa/pypi-support#360]
**Project**
[VTK](https://test.pypi.org/project/vtk/)

**Size of release**
175MB

**Which indexes**
both PyPI and Test PyPI

**Reasons for the request**
[The Visualization Toolkit (VTK)](https://vtk.org/) is an open-source, freely available software system for 3D computer graphics, modeling, image processing, volume rendering, scientific visualization, and 2D plotting. It supports a wide variety of visualization algorithms and advanced modeling techniques, and it takes advantage of both threaded and distributed memory parallel processing for speed and scalability, respectively.

VTK is a very large project that has been in active development for over 20 years, so it is large in size. There are also several dependencies that we include in the wheel to ensure that features work without implicit dependencies. We don't expect our release sizes to increase dramatically in the future.

**Comment by thewtex** [comment]
CC: @di

**Comment by tjcorona** [comment]
Are there any necessary next steps on our end for this request to be reviewed?

**Comment by banesullivan** [comment]
@larsoner - do you think you could help us ping the right people to help move this forward?

**Comment by larsoner** [comment]
@ewdurbin was who helped last time I had a PyPi package problem that needed manual intervention, not sure if they are still right person to ping though (apologies if not!)

**Comment by banesullivan** [comment]
Thanks for helping!!

**Comment by jamadden** [comment]
The upload limit has been set to 200MB on pypi.org and test.pypi.org. Please be mindful of the frequency of releases at that size.

**Comment by tjcorona** [comment]
Thanks!

**Comment by mathstuf** [comment]
Thanks!

> Please be mindful of the frequency of releases at that size.

We're looking at 6 months with possibilities for maybe 1 or (more rarely) 2 point releases for each for fixups. We can look at avoid uploading point releases that don't affect the wheels.
