### ISSUE TITLE
Limit Request: bpy - 150MB

### ISSUE THREAD

**Issue by TylerGubala** [pypa/pypi-support#362]
Currently, my project `bpy`, which ships [Blender 3d](https://www.blender.org/) built as a Python module has a file size limit on PYPI of 100MB.

The goal of providing users of my project with a `wheel` to install is to avoid the search for and eventual download of the source code & libraries for this project, which together are multiple gigabytes in size.

Since building this `wheel` involves packing an entire application (and a complex one at that) it is understandable that occasionally the app size will grow by several megabytes at a time. I don't have much control over that

For instance, when building version `2.82` on MacOSX, the resultant package is 112MB in size:

```
Uploading bpy-2.82-cp37-cp37m-macosx_10_11_x86_64.whl
100%|██████████| 112M/112M [00:45<00:00, 2.56MB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File too large. Limit for project 'bpy' is 100 MB. See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/
```

And on Windows the same version is 102MB:

```
Uploading bpy-2.82-cp37-cp37m-win_amd64.whl
100%|█████████| 102M/102M [00:48<00:00, 2.22MB/s] 
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File too large. Limit for project 'bpy' is 100 MB. See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/
```

Blender, when packaged in a quickly installable format for Python, has the potential to really assist in folks projects especially involving scripted or automated modeling and rendering, despite the large file size.

Please consider extending the file size limit for the `bpy` package on pypi and pypitest once more to 150MB.

Thanks in advance.

**Comment by TylerGubala** [comment]
If there is some other information I need to provide, please let me know. I'm not sure if the delay is caused by some info that I neglected to provide.

**Comment by TylerGubala** [comment]
Hi. Sorry to be a bother, but has anyone looked at this?

Blender 3d, the application that `bpy` is based on, ships at ~130Mb.

The `wheel` that I supply, weighs in at ~110Mb, give or take depending operating system and a number of other factors.

I imagine that `wheel`s of `bpy` that I supply will, in general, be ~90% the size of the full application.
For `bpy-cuda` it will probably be ~95% the size of the full application.
For `bpy-optix` it will probably be ~98% the size of the full application.

Blender is a big application, and to ship a working version of the Python API, I have to include `.dll`/`.so` binary files as well as a plethora of addon utilities and scripts (they help Blender's startup)

I'm just wondering if there is some other preference? Do you want me to self host something? I'd like to put the `wheel`s I have built up on pypi but I am sitting in the dark.

**Comment by jamadden** [comment]
The limit has been set to 150MB on pypi.org and test.pypi.org. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases.

**Comment by TylerGubala** [comment]
@jamadden I don't want to strain pypi or its resources; and would like users to have the best experience possible.

Maybe I just don't know what I don't know? Are there alternative packaging schemes that would suit a distribution of this size better?

**Comment by jamadden** [comment]
Common suggestions include:

- depend on platform-specific tags and system libraries instead of bundling binaries
- break the package into smaller packages that depend on each other as necessary
- side-load large models or datasets via downloads from elsewhere at runtime/installtime.

The last two are especially beneficial if the rate of change of the various pieces is very different.

**Comment by Chandler** [comment]
@TylerGubala is the new increased limit of 150mb enough to upload your first set of wheels to pip? Or are you still trying to make them smaller.
The ones on drive, https://drive.google.com/drive/folders/1uSiTQLvlUxu7PDT2TCT4XIrwGwn1WWph

**Comment by TylerGubala** [comment]
@Chandler Sorry for the late reply. 

I am still trying to make them smaller but the 150Mb is sufficient for the size they are currently.

The only issue is I cannot upload the linux ones since they are not `manylinux` compatible. More to come soon. Thanks all.

**Comment by TylerGubala** [comment]
@Chandler It has been a while.

I have successfully made a `manylinux` compatible `wheel` file but it is 185M in size.

I'm not sure of what to do at this point, the bloat is likely due to having to link all the necessary libraries into the installation.

I may just have to stick with Google Drive for now.
