### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mononobi** [pypa/pypi-support#363]
Request for account recovery.

## PyPI Username

`mononobi`

---

##  Reason for request

Reason:
I was using google authenticator app, when I wanted to add another application for 2FA into the app, an error occurred saying that barcode scanner is not available, then I googled the internet and the only way to overcome this error was to clear storage of the google authenticator, and when I did clear it, all my 2FA accounts were gone. I don't have any recovery codes either.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mononobi** [comment]
> Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

Thanks, replied to your email.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by mononobi** [comment]
Thank you, I logged in successfully.
