### ISSUE TITLE
bpy "File name has already been used" error

### ISSUE THREAD

**Issue by TylerGubala** [pypa/pypi-support#364]
I tried uploading an sdist of my `bpy` version 2.82, but got a file name reuse error.

I read https://pypi.org/help/#file-name-reuse and my understanding is that if you upload a file of the same name (even if the release no longer exists) you will always get the error.

I would have expected that deleting the release or even the project would have removed the file. I need the pypi release version number to match the version number of Blender (the external application that I am shipping as a Python Module). But now it seems I am stuck in permanent limbo?

Is there any way for my to upload this file to pypi, thus overwriting the old one?

**Comment by hugovk** [comment]
How about releasing as 2.82.1 or 2.82.post0?

https://www.python.org/dev/peps/pep-0440/

**Comment by TylerGubala** [comment]
@hugovk so effectively, the install command becomes

`pip install bpy==2.81.post0`?

While that's not the worst thing, it is still will be a pretty big point of confusion I think for folks trying to get a specific version of the API, by doing

`pip install bpy==2.81`

**Comment by hugovk** [comment]
Yeah, that is a bit of a downside.

Then perhaps using a patch version is better, like 2.81.1.

In my experience, there's always scope for a little packaging error warranting a patch version, and you wouldn't need to wait for a new Blender release to fix it. Same for any other improvements to the package.

**Comment by TylerGubala** [comment]
I'll just close this one down; this seems to be an issue people are familiar with even though I had no idea it existed.

Even though I try to stay as close as possible to Blender Application & API version, I think the suggestion provided by @hugovk is sufficient, given the great security considerations that I have read up on since then.

I wish that this was more in my face about how this could really mess me up though. The tutorials that I read and performed said nothing about version naming being an issue except to name the package based on [PEP 440](https://www.python.org/dev/peps/pep-0440/) but I guess I did not read enough. Oh well.
