### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by hoefling** [pypa/pypi-support#366]
Request for account recovery.

## PyPI Username

`hoefling`

---

##  Reason for request

Reason:
  - Lost 2FA authentication app or security token

AFter my old phone broke beyond any repair, I have now discovered I have stored wrong recovery codes for PyPI (presumably pasted from some other service). My TestPyPI account is accessible though, because no 2FA was activated.

**Comment by hoefling** [comment]
Actually, this doesn't quite sum up - I don't find a 2FA confirmation email from PyPI in my mailbox. I have one from TestPyPI because I have activated 2FA for my TestPyPI account (also `hoefling`). I am able to login to TestPyPI using generated TOTP. Right now, it looks like 2FA was activated both for PyPI and TestPyPI, but I can generate the token for TestPyPI only. Maybe a bug?

**Comment by ewdurbin** [comment]
PyPI and TestPyPI run as completely independent services, so enabling TOTP on one would not affect the other.

Your PyPI account does have a valid TOTP secret which wouldn't have been generated unless you enabled TOTP, so account recovery is necessary.

I've contacted the primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by hoefling** [comment]
@ewdurbin I've generated and stored recovery codes this time. Thank you for you help!
