### ISSUE TITLE
Limit Request: bpy-cuda - 150MB

### ISSUE THREAD

**Issue by TylerGubala** [pypa/pypi-support#367]
`bpy-cuda` is a project which ships [Blender 3d](https://www.blender.org/) built as a python module with CUDA cycles raytracing.

**Project**
`bpy-cuda`

**Size of release**
The current build is 125Mb. I expect that the size will increase with time, since new features are being added to Blender all the time

**Which indexes**
Both

**Reasons for the request**
Since the project bundles an entire application (.dlls and all) wheels can be quite large.
Wheels are provided so that users do not have to clone source code and libraries, together which are multiple Gigabytes in size.

**Comment by jamadden** [comment]
The limit has been set to 150MB on pypi.org [and test.pypi.org]. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases.
