### ISSUE TITLE
Limit Request: bpy-optix - 150MB

### ISSUE THREAD

**Issue by TylerGubala** [pypa/pypi-support#368]
`bpy-optix` is a python package providing wheels of [Blender 3D](https://www.blender.org/) built as a python module, with NVIDIA Optix hardware accelerated ray tracing enabled.

**Project**
`bpy-optix`

**Size of release**
The current wheel is 127Mb, but I expect that the size will increase because Blender is having features added all the time.

**Which indexes**
Both Please.

**Reasons for the request**
Because the package is the entire Blender application (.dlls and all), the wheels can be quite large. Wheels are provided so users do not have to clone source code and libraries, together which can be gigabytes in size.

**Comment by jamadden** [comment]
The limit has been set to 150MB on pypi.org [and test.pypi.org]. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases.
