### ISSUE TITLE
Limit Request: paddlepaddle - 150MB

### ISSUE THREAD

**Issue by DDDivano** [pypa/pypi-support#371]
Hi. We will release a new version for paddlepaddle recently.
We have added many new features in this new version. Our current size limit is 100M, and the last version is 110M. Can you please help to increase this to around 150MB.We really appreciate it.

Project:
https://github.com/PaddlePaddle/Paddle
https://pypi.org/project/paddlepaddle/

Which indexes
PyPI

**Comment by DDDivano** [comment]
any update on this?We have upload windows & mac wheel package.But we havn't upload the linux 
 wheel package.Your help would be most appreciated.Thanks!https://pypi.org/project/paddlepaddle/1.8.0/#files

**Comment by kolinwei** [comment]
Any update for this issue? Your help is most appreciated。
We will release a new version on May 15，and really need your help。

**Comment by pradyunsg** [comment]
Hi! Thanks for your patience on this and appreciate the nudges.

PyPI is moderated and maintained by volunteers, and operates on infrastructure donated to the PSF by our [sponsors](https://pypi.org/sponsors/). This means we don't really have "user support staff" who can provide fast response times, and it depends on availability of the volunteers.

---

I've gone ahead and bumped up the upload limit to 200 MB for `paddlepaddle` on PyPI. Please elaborate on why the wheel size has increased in future limit requests, if you make any. :)
