### ISSUE TITLE
PEP 541 Request: djitellopy

### ISSUE THREAD

**Issue by M4GNV5** [pypa/pypi-support#373]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/djitellopy/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/M4GNV5/

**Reasons for the request**

The old maintainer does not have time to work on the project anymore. He agreed on me taking it over and already made me a collaborator to the orginal github repository (see issue link below).

**Maintenance or replacement?**

Maintenance. I already have a fork of the repository with a couple of bug fixes & improvements: https://github.com/M4GNV5/DJITelloPy/tree/enhancements

**Contact and additional research**

https://github.com/damiafuentes/DJITelloPy/issues/38

**Comment by yeraydiazdiaz** [comment]
Hi @M4GNV5, it'd be ideal for @damiafuentes to log in to PyPI and add you as the owner himself in the [collaboration page of the project](https://pypi.org/manage/project/djitellopy/collaboration/) so as to not further burden administrators.

**Comment by yeraydiazdiaz** [comment]
The transfer is now complete, apologies for the delay.
