### ISSUE TITLE
PEP 541 Request: reapy

### ISSUE THREAD

**Issue by RomeoDespres** [pypa/pypi-support#374]
**Project to be claimed**
`reapy`: https://pypi.org/project/reapy

**Your PyPI username**
`romeo-despres`: https://pypi.org/user/romeo-despres

**Reasons for the request**
Package appears to be invalid in the sense of PEP 541:

> project is name squatting (package has no functionality or is empty)

Project is empty, hasn't moved since 2016, and cannot be installed with `pip`:
```
ERROR: No matching distribution found for reapy
```

**Maintenance or replacement?**
I intend to replace this project with a package called `reapy` (repo: https://github.com/RomeoDespres/reapy) and currently released on PyPI under the name `python-reapy` (https://pypi.org/project/python-reapy), which confuses several users that have trouble remembering the name.

**Contact and additional research**
No contact information can be found on the maintainer's page (https://pypi.org/user/ahlinc). I haven't been able to find a matching repo on GitHub and thus have not found any way to contact the maintainer.

**Comment by yeraydiazdiaz** [comment]
Hello @RomeoDespres, I can confirm the project has a single release but no files which classifies it as invalid. In these cases we send a notice to the current owner to let them know the removal and a courtesy period of one week, after that we'll proceed with the transfer.

**Comment by RomeoDespres** [comment]
Hello @yeraydiazdiaz, thanks for your quick reply! Let's wait and see then.

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by RomeoDespres** [comment]
Thanks a lot!
