### ISSUE TITLE
PEP 541 Request: protonvpn-gui

### ISSUE THREAD

**Issue by kaplun** [pypa/pypi-support#376]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/protonvpn-gui

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/kaplun

**Reasons for the request**

I represent ProtonVPN (https://protonvpn.com, and https://github.com/ProtonVPN). ProtonVPN is an online service constituted by an infrastructure and several clients implemented on different platforms. The Open source community has implemented different Linux clients GUIs that are implemented in Python. One of them has been chosen as the officially endorsed client:  https://github.com/ProtonVPN/linux-gui. Such package is a companion to the official Linux client CLI (https://github.com/ProtonVPN/linux-cli). The CLI is already hosted on Pypi correctly as: https://pypi.org/project/protonvpn-cli/ and we'd like for consistency to have the GUI hosted as https://pypi.org/project/protonvpn-gui/)

`protonvpn-gui` entry on Pypi is currently empty. It was previously owned by https://pypi.org/user/wutduk/, who is now maintaining the entry https://pypi.org/project/protonvpn-cli-gui/

**Maintenance or replacement?**

If the transfer is successful we intend to use it to host the official https://github.com/ProtonVPN/linux-gui and maintain it.

**Contact and additional research**

I tried to contact `wutduk` both via private email on 29/04/2020 and sent a heads up on 05/05/2020 without any reply. I also contacted him via chat through his Reddit handle on 30/04/2020 without any reply.

**Comment by yeraydiazdiaz** [comment]
I think there's a confusion here, I see no project named `protonvpn-gui` in PyPI nor user `wutduk` seems to have removed it recently.

Closing this as there's nothing to transfer but feel free to comment further if I've missed something.

**Comment by calexandru2018** [comment]
@yeraydiazdiaz he has deleted the project. 

https://pepy.tech/project/protonvpn-gui
https://libraries.io/pypi/protonvpn-gui

**Comment by yeraydiazdiaz** [comment]
No, the project name is available once deleted, however, the project that takes its place cannot upload releases with the same versions as the previous project, i.e. trying to upload new code under protonvpn-gui 1.5.4 will fail.

Closing as there is nothing to transfer. Good luck.

**Comment by calexandru2018** [comment]
@yeraydiazdiaz Oh gotcha, appreciate the help!
