### ISSUE TITLE
PEP 541 Request: pypm

### ISSUE THREAD

**Issue by deankarlen** [pypa/pypi-support#377]
**Project to be claimed**

`pypm`: https://pypi.org/project/pypm

**Your PyPI username**

`karlen`: https://pypi.org/user/karlen

**Reasons for the request**

It appears that pypm is not being used as a pypi an opensource package. The pypi project page points to a third party URL. It appears that the organization is simply preventing others from re-using an acronym that they wish to protect.

**Maintenance or replacement?**

This is a new package (Python Population Modeller). It is designed for the analysis and characterization of the CoViD-19 epidemic.

https://github.com/pypm/pypm

**Contact and additional research**

**Comment by yeraydiazdiaz** [comment]
Hi @deankarlen, I can confirm the project has a single release with no files and is therefore considered invalid.

Our policy is to contact the owner and give a one week courtesy period to raise objections to the transfer. If I receive no reply we will proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Seems both email addresses for the owner have been deactivated, tagging GitHub user @srid as the possible owner of the PyPI package.

**Comment by srid** [comment]
I relinquish ownership of it, but maybe check with activestate https://code.activestate.com/pypm/

**Comment by ewdurbin** [comment]
Transfer complete.
