### ISSUE TITLE
PEP 541 Request: pyimgflip

### ISSUE THREAD

**Issue by theceebee** [pypa/pypi-support#378]
**Project to be claimed**

`pyimgflip`: https://pypi.org/project/pyimgflip

**Your PyPI username**

`theceebee`: https://pypi.org/user/theceebee

**Reasons for the request**

- There was one release in September 2019.
- The links to the release are all dead, suggesting there was never an actual release or it has been deleted.
- There is no information on the project page about the project.
- The email address to the project maintainer bounces back.

**Maintenance or replacement?**

I intend to publish a different project.
My repository: https://github.com/theceebee/pyimgflip

**Contact and additional research**

I tried to email the user at the address attached to the project. The domain `oupbots.com` does not exist.

**Comment by yeraydiazdiaz** [comment]
Hi @theceebee, as you mention the domain does not exist and all emails associated with the owner in PyPI are under it so contact via email is not possible.

Tagging GitHub user @KingAizen even though there's little activity hoping for some response, I'll consider this the first reachability attempt.

**Comment by yeraydiazdiaz** [comment]
Tagging @KingAizen once again as a second attempt of contact.

**Comment by theceebee** [comment]
@yeraydiazdiaz Have you made any further progress in contacting @KingAizen?

**Comment by yeraydiazdiaz** [comment]
Hi @theceebee, unfortunately no. We are, however, obliged to wait 6 weeks from the initial attempt of contact. I'll consider your tag as a final attempt and move forwards in two weeks.

**Comment by theceebee** [comment]
Pumping this thread to see if we've satisfied the requirements.

**Comment by theceebee** [comment]
@yeraydiazdiaz have we satisfied the the requirements to claim the pyimgflip project?

**Comment by theceebee** [comment]
Pumping this thread to see if we've satisfied the requirements.

**Comment by theceebee** [comment]
Pumping this thread to see if we've satisfied the requirements.

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay, this project is now considered abandoned, I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
