### ISSUE TITLE
Request for maintainership of `frozendict` package

### ISSUE THREAD

**Issue by Marco-Sulla** [pypa/pypi-support#38]
Hello. I contacted the original author of `frozendict`, @slezica. He said to me there's no problem to transfer to me the ownership of the project. What we have to do?

**Comment by jamadden** [comment]
> Hello. I contacted the original author of frozendict, @slezica. He said to me there's no problem to transfer to me the ownership of the project. 

Great! If @slezica is also [the owner](https://pypi.org/user/slezica/) of the [frozendict](https://pypi.org/project/frozendict/) project on PyPI, then the preferred action would be for @slezica to login to PyPI and directly add your own PyPI account as a new owner on the project. You could then remove the existing owner, or you could continue to share ownership. There's nothing for pypi-support to do.

The PEP 541 process that requires administrator involvement only comes into play when the owner of a project is unreachable.

**Comment by yeraydiazdiaz** [comment]
@Marco-Sulla I am now closing this issue as contact has been made between you and @slezica.

As @jamadden suggests @slezica simply needs to log in to PyPI and add you as an owner of the project.

**Comment by Marco-Sulla** [comment]
Well, the last time I contacted @slezica was April 14. I suppose he have not enough time to add me as co-admin.

**Comment by Marco-Sulla** [comment]
Up
