### ISSUE TITLE
PEP 541 Request: PIE

### ISSUE THREAD

**Issue by prashanth-up** [pypa/pypi-support#381]
**Project to be claimed**

`pie 0.6`: https://pypi.org/project/pie

**Your PyPI username**

`prashanth_up`: https://pypi.org/user/prashanth_up

**Reasons for the request**

The Project has been abandoned since March 26, 2014. There has been no updates or publishes ever since that date.
I would like to publish my project under the name of `PIE`

**Maintenance or replacement?**
 
Replacement, as there is no files in that user's package.
My code repo : https://github.com/new-git-test/PIE

**Contact and additional research**

The User has given no contact information.

**Comment by hugovk** [comment]
Looking at the author's other packages (https://pypi.org/user/jgors/), looks like it's @jgors who has an email address at http://jgors.com.

**Comment by prashanth-up** [comment]
> Looking at the author's other packages (https://pypi.org/user/jgors/), looks like it's @jgors who has an email address at http://jgors.com.

Thankyou I'll look into it ASAP!

**Comment by prashanth-up** [comment]
@hugovk The user @jgors has not responded on any platforms that I've tried contacting him about this. Will the ownership of the Package Index name be transferred ?

**Comment by hugovk** [comment]
Probably, if there's also no reply when the PyPI maintainers get in touch after 6 weeks, and all the other criteria in PEP 541 are met.

**Comment by prashanth-up** [comment]
Ok Thanks, I'll wait for 6 weeks and verify the criteria in PEP 541 again.

**Comment by yeraydiazdiaz** [comment]
I have now emailed the onwer, hopefully we will hear back from him soon and move forwards with your request.

**Comment by prashanth-up** [comment]
Thankyou @yeraydiazdiaz I'll be looking forward to your reply.

**Comment by prashanth-up** [comment]
@yeraydiazdiaz  Okay Sure. Sorry forgot about that.

**Comment by prashanth-up** [comment]
@yeraydiazdiaz I believe the period of six weeks have completed. Is there an update on the issue?

**Comment by prashanth-up** [comment]
@yeraydiazdiaz Do I qualify for the Package Name Ownership now or not ?

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay, this project is now considered abandoned. I will now ask an admin to perform the transfer for you.

**Comment by prashanth-up** [comment]
Yes Thankyou

**Comment by ewdurbin** [comment]
Transfer complete.
