### ISSUE TITLE
Limit Request: scikit-hep-testdata - 120MB

### ISSUE THREAD

**Issue by eduardo-rodrigues** [pypa/pypi-support#382]
**Project**

Project `scikit-hep-testdata` at https://pypi.org/project/scikit-hep-testdata/.

**Size of release**

Present release (0.3.0), undeployed, is 81.6 MB.

**Which indexes**

Just PyPI.

**Reasons for the request**

This `scikit-hep-testdata` package is part of a relatively large project [Scikit-HEP](https://scikit-hep.org/
) of Python tools for High Energy Physics. Several of the org packages need test data, and we try and collect as much as possible in one location used by several packages, which is the `scikit-hep-testdata` package. Most files are very small but some are of order a MB. We are now above the default limit of 60 MB and think that a limit at 120 MB or so would do it. Indeed we intend to add more files but not that many.
We do not foresee to make many regular releases.

We would really appreciate if the limit could be increased to, say, 120 MB.
Thank you for considering this "request", on behalf of the Scikit-HEP org admins.

**Comment by eduardo-rodrigues** [comment]
Dear PyPI support team, could this request be kindly considered as otherwise we will be constrained to find an alternative way to support our organisation? Thank you.

**Comment by jamadden** [comment]
The limit has been increased on pypi.org.

**Comment by eduardo-rodrigues** [comment]
Thank you very much @jamadden, that's truly appreciated, and helpful!
