### ISSUE TITLE
PEP 541 Request: PyIMSL

### ISSUE THREAD

**Issue by haney** [pypa/pypi-support#383]
**Project to be claimed**

`PyIMSL`: https://pypi.org/project/PyIMSL/

**Your PyPI username**

`haney`: https://pypi.org/user/haney/

**Reasons for the request**

The PyIMSL project was developed and maintained by Rogue Wave Software (note the author email is listed as sales@roguewave.com), however the associated PyPI repository was maintained by a single user, SteveLang, who is no longer with the company. We (Rogue Wave Software) would like to publish an update to this project, however no longer have access to SteveLang's account. We would like to transfer ownership to an active member of the development team (me) so that we can manage the PyPI project again. I've associated and verified my @roguewave.com email address with my PyPI account to demonstrate my affiliation with the company. I've also associated my @perforce.com address for reference (Perforce acquired Rogue Wave in 2019).

**Maintenance or replacement?**

The plan would be to publish the latest version of the project under this name. PyIMSL is currently a closed source project so there is not a public repository to reference at this time.

**Contact and additional research**

sales@roguewave.com is an alias to the Sales organization at Rogue Wave Software and does not have direct knowledge of the PyIMSL repository on PyPI. The SteveLang account on PyPI does not have a public email address, so I have not been able to attempt to contact him directly to see if he would transfer the account. Assuming there is a non-@roguewave.com email address associated with it and there is a way I can get access to that email address, I can attempt to contact him directly.

**Comment by yeraydiazdiaz** [comment]
Hi @haney, unfortunately `SteveLang`'s associated email address is @roguewave.com.

A quick Google search yields what looks like his [LinkedIn profile](https://www.linkedin.com/in/stevelang), could you attempt contact through there?

**Comment by haney** [comment]
Thanks @yeraydiazdiaz, I'll attempt to connect with `SteveLang` on linkedin to see if he's willing to transfer the project directly. Assuming I don't hear back from him, how long should I wait before we can look at additional options?

**Comment by haney** [comment]
I was able to contact `SteveLang` via linkedin, and he was ammenable to migrating control of the project, however when he attempted to log in he found he didn't recall his password, and it looks like his recovery accounts were targeted at the `@roguewave.com` domain (which he no longer has access to). His recommendation was to look at the abandoned project process to migrate the project.

That brings me back here. The original owner is willing to transfer control, but is unable to. Is there additional work needed from my end to facilitate migrating this project.

**Comment by haney** [comment]
`SteveLang` and I were able to work with Rogue Wave's IT to reset the account and transfer ownership of the project. I think we can consider this issue resolved.

**Comment by yeraydiazdiaz** [comment]
Excellent, glad that worked out. Thanks @haney and Steve.
