### ISSUE TITLE
PEP 541 request: pymicro

### ISSUE THREAD

**Issue by heprom** [pypa/pypi-support#384]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/pymicro

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/heprom

**Reasons for the request**

I beleive this project can be considered abandoned as there have not been any release or activity from the last 3 years (apart from the issue I opened to reach the owner to request a name transfer), and the owners could not be contacted by any of the available emails.

**Maintenance or replacement?**

If the transfer is successful, the current pymicro project will be replaced by another project. The code repository is available at:
`NEW_PROJECT`: https://github.com/heprom/pymicro

**Contact and additional research**

Issue opened on the project repository on Dec 19, 2019 followed by two message to ask for an update https://github.com/GendoIkari/pymicro/issues/5. Owner also contacted by email at komradstudios@gmail.com

**Comment by yeraydiazdiaz** [comment]
Hello @heprom, tagging @GendoIkari in hopes he will get a notification about this issue. I have also sent emails to the addresses in PyPI and in the GitHub public profile.

Hopefully we wil hear back soon.

**Comment by heprom** [comment]
Thanks @yeraydiazdiaz.

**Comment by GendoIkari** [comment]
Hello, I don't know exactly what's going on, so let me catch up with all the emails and the things happening here, please, and I'll reply something meaningful soon. Thank you.

**Comment by GendoIkari** [comment]
Sorry for the delay, I don't see any problem in passing the name to the gentlemen here, @heprom :)

**Comment by yeraydiazdiaz** [comment]
Hi @GendoIkari, thanks for getting back to us.

So, to avoid having to ask an admin to perform the transfer, we'd appreciate it if you could transfer the project yourself by visiting https://pypi.org/manage/project/pymicro/collaboration/ and adding `heprom` as an owner to the project. You won't be able to remove yourself but @heprom can after that if he wishes.

**Comment by GendoIkari** [comment]
Can't I just delete the project?
```
 Warning Deleting this project will:

    Irreversibly delete the project along with 1 release
    Make the project name available to any other PyPI user
```

**Comment by yeraydiazdiaz** [comment]
Yes, but there will be a period of time where the project name will be available for everyone, it's more fair to transfer it directly to @heprom so we are sure he gets it.

**Comment by heprom** [comment]
Thank you very much @GendoIkari for accepting this transfer.

**Comment by GendoIkari** [comment]
```User 'heprom' does not have a verified primary email address and cannot be added as a Owner for project```

**Comment by heprom** [comment]
This is weird, my primary email is normally henry.proudhon@gmail.com
I've changed it to henry.proudhon@mines-paristech.fr
They are both verified normally.
Could you try again ?

**Comment by GendoIkari** [comment]
Same problem. Tried multiple times with ```heprom```.

**Comment by yeraydiazdiaz** [comment]
@heprom, your associated address in PyPI is the second one, it does not show up as verified and I don't see any record of any emails sent from PyPI to that address. Are you absolutely sure you received verification email? If so we might need to raise a bug in Warehouse.

**Comment by heprom** [comment]
Sorry my mistake, I got confused with my github emails. I just verified my email with PyPI. Sorry for the inconvenience. It should work now.

**Comment by GendoIkari** [comment]
Please confirm me that everything is done now, removing me from the owners of the project. Thank you.

**Comment by heprom** [comment]
It's all good now, I've just removed you from the project owners. Thanks.

**Comment by yeraydiazdiaz** [comment]
Excellent, thanks @GendoIkari and @heprom 💯

**Comment by heprom** [comment]
And thanks for your help @yeraydiazdiaz
