### ISSUE TITLE
PEP 541 Request: euler

### ISSUE THREAD

**Issue by m-hoff** [pypa/pypi-support#385]
**Project to be claimed**

`euler`: https://pypi.org/project/euler/

**Your PyPI username**

`m-hoff`: https://pypi.org/user/m-hoff

**Reasons for the request**

This project was created in September 2016 with no associated code or homepage and has not received any update since. 

**Maintenance or replacement?**

I intend to replace this package with one of my own that is actively maintained. 

**Contact and additional research**

Contacting the author via the email listed on other PyPI projects results in a bounceback email stating the message is undeliverable. There is no additional contact info on the author's github profile.

**Comment by yeraydiazdiaz** [comment]
Hi @m-hoff, I can confirm the project has a single release with no associated files and is therefore considered invalid.

In these situations we attempt contact with the owner once allowing a one week courtesy period. If we don't hear back we will move forward with your request.

**Comment by yeraydiazdiaz** [comment]
The email bounced immediately. From the other projects related to that PyPI account it seems GitHub user @gregoil might the current owner, tagging as a final means of contact.

**Comment by yeraydiazdiaz** [comment]
The courtesy period has now passed. I will now ask an admin to perform the transfer for you.

**Comment by ewdurbin** [comment]
Transfer complete.
