### ISSUE TITLE
please help me recover my account

### ISSUE THREAD

**Issue by szborows** [pypa/pypi-support#387]
Hi,
I registered in PyPI in 2016. Back then I used some email address that I don't remember. I'm locked out of my account. Obviously I have tried all of my emails on pypi website without luck.

Is there a way to reset my email address?
username: szborows

https://pypi.org/project/unrtf/ was uploaded from https://github.com/szborows/python-unrtf/
Is it good enough proof that I'm who I tell I am?

**Comment by di** [comment]
Hi @szborows, looks like this is a `@hotmail.com` address, does that sound familiar?

**Comment by szborows** [comment]
@di thanks for quick response. It sounds familiar. I was trying to use this email without success. If I remember correctly, pypi was saying that this email doesn't exist. But I'm not sure.

Nevertheless to publish my other package I created another account **zborro** and used the same email address. And it worked? So I assume email addresses for both accounts are the same?

**Comment by di** [comment]
Ah, looks like you had a typo in your original account's email address, it was actually `@hotmail.om`.

What would you like to do here? You actually can't share an email address between multiple PyPI accounts, so if you'd like me to correct the typo you'll need to change the email associated with the new account.

**Comment by szborows** [comment]
Is it possible that you

1. Transfer babla project from zborro to szborows
2. Remove zborro account
3. Fix typo in szborows account

Hopefully I'm not asking for too much.

**Comment by di** [comment]
Done.

**Comment by szborows** [comment]
Thanks @di  !!
