### ISSUE TITLE
PEP541: Squatter on `idem`

### ISSUE THREAD

**Issue by thatch45** [pypa/pypi-support#39]
I have a project called `idem` that I would like to upload to pypi but the name is being squatted - https://pypi.org/project/idem/ .

The current owner has not published any code and has no contact information. Can I please take over ownership of the `idem` name on pypi as user `thatch45`?

Thank you all again for your work!

**Comment by yeraydiazdiaz** [comment]
Hello @thatch45, I can confirm the project `idem` has a single empty release and therefore it can be considered invalid.

I will now ask an admin to perform the transfer to you.

**Comment by thatch45** [comment]
Wooohoo! Thanks!

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by thatch45** [comment]
Thanks!!!
