### ISSUE TITLE
Issue: Limit Request: metas-unclib - 110MB

### ISSUE THREAD

**Issue by wollmich** [pypa/pypi-support#391]
**Project**

https://pypi.org/project/metas-unclib/

**Size of release**

110 MB

**Which indexes**

PyPI

**Reasons for the request**

I'm using Intel MKL custom dlls for Win 32-bit, Win 64-bit, Linux 64-bit and macOS 64-bit.
I added additional functions to those dlls. That's why the size has increased.

**Comment by jamadden** [comment]
The project https://pypi.org/project/metas-unclib/ seems to be distributing native binary libraries for a multitude of platforms in a single generic wheel file:

```console
$ wget https://files.pythonhosted.org/packages/.../metas_unclib-2.2.7-py2.py3-none-any.whl
...
$ unzip -l ./metas_unclib-2.2.7-py2.py3-none-any.whl
...
 34712728  11-04-2019 13:37   metas_unclib/mkl_custom/linux/intel64/custom_mkl.so
  2171569  03-01-2019 15:37   metas_unclib/mkl_custom/linux/intel64/libiomp5.so
 25587148  11-04-2019 21:11   metas_unclib/mkl_custom/macos/intel64/custom_mkl.dylib
  2800544  04-12-2019 04:26   metas_unclib/mkl_custom/macos/intel64/libiomp5.dylib
 17610752  11-01-2019 14:56   metas_unclib/mkl_custom/win/ia32/custom_mkl.dll
      381  11-01-2019 14:56   metas_unclib/mkl_custom/win/ia32/custom_mkl.dll.manifest
     9454  11-01-2019 14:56   metas_unclib/mkl_custom/win/ia32/custom_mkl.exp
    16292  11-01-2019 14:56   metas_unclib/mkl_custom/win/ia32/custom_mkl.lib
  1527528  01-17-2019 08:39   metas_unclib/mkl_custom/win/ia32/libiomp5md.dll
 27343360  11-01-2019 14:56   metas_unclib/mkl_custom/win/intel64/custom_mkl.dll
      381  11-01-2019 14:56   metas_unclib/mkl_custom/win/intel64/custom_mkl.dll.manifest
     9310  11-01-2019 14:56   metas_unclib/mkl_custom/win/intel64/custom_mkl.exp
    15944  11-01-2019 14:56   metas_unclib/mkl_custom/win/intel64/custom_mkl.lib
  1717480  01-17-2019 07:45   metas_unclib/mkl_custom/win/intel64/libiomp5md.dll
```

If that was separated into proper platform-specific distributions (`macos` wheels for macOS, `win32` wheels for 32-bit Windows, `manylinux_x86_64` wheels for 64-bit Linux, etc), it seems likely that each artifact would fit within the size limit.

**Comment by wollmich** [comment]
Thanks you for  comment.  Can you help how to do that? At the moment the native binary libraries are specified in the `MANIFEST.in` file. Can have multiple manifest files for each platform?

**Comment by jamadden** [comment]
The desired goal is to have platform-specific wheels containing only the platform-specific files. Usually these variant files are named identically (with the exception of platform-specific suffixes, e.g., .dll vs .so vs .dylib). Often this is accomplished by building the binaries on each platform; [cibuildwheel](https://github.com/joerick/cibuildwheel) has some examples of that, and searching the web can find more. 

In the event that binary files currently exist and can't be rebuilt as part of creating the wheel, one could use imperative code in `setup.py` to choose which files are included in the distribution. The [`package_data`](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files) keyword argument might do the job. That may take some care to get the wheel platform tags (the final wheel filename, which is how installers recognize what platforms the wheel works on) correct.

**Comment by wollmich** [comment]
I've added platform specific wheels, see https://pypi.org/project/metas-unclib/2.3.1.1/

So this issue can be closed.
