### ISSUE TITLE
PEP 541 Request: requests-aws4auth

### ISSUE THREAD

**Issue by tedder** [pypa/pypi-support#393]
**Project to be claimed**

`requests-aws4auth`: https://pypi.org/project/requests-aws4auth

**Your PyPI username**

`tedder`: https://pypi.org/user/tedder

**Reasons for the request**

The project hasn't been updated in 4 years and I can't contact the author. Their last public activity on github was in early 2016.

**Maintenance or replacement?**

Maintenance; I want to take [the current repo](https://github.com/sam-washington/requests-aws4auth) and update it with [my forked copy](https://github.com/tedder/requests-aws4auth); I've started making small changes, and added automated testing, and copied all of the open PRs over.

I know this lib is still in use, it's [officially unofficially endorsed by AWS](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-python) and I hope a few other users pop up so the bus factor can be increased. Note my primary email hasn't changed since 1999 and I've used my github account since 2009.

**Contact and additional research**

[Here's my github issue about forking and/or contacting the author](https://github.com/sam-washington/requests-aws4auth/issues/40). No response after ~5 weeks.  Here's the email I sent:
```
MIME-Version: 1.0
Date: Wed, 8 Apr 2020 18:07:40 -0700
Subject: is this account alive? is this human alive?
From: Ted Timmons <ted@perljam.net>
To: codegreen@aethris.net
Content-Type: text/plain; charset="UTF-8"

Wondering if it is, it'd be nice to have you simply turn over your
pypi details for aws4auth, rather than going through a complicated
process. Details here:
https://github.com/sam-washington/requests-aws4auth/issues/40
```

**Comment by yeraydiazdiaz** [comment]
Hello @tedder, I've attempted contact with @sam-washington who I'm tagging here as well.

Hopefully we will hear back soon and move forwards with your request.

**Comment by yeraydiazdiaz** [comment]
Sam replied to my email and was kind enough to perform the transfer himself.

@tedder is now an owner of `requests-aws4auth`.

Thanks all!

**Comment by tedder** [comment]
Confirmed- even better, there's dual ownership, so the bus factor should be better on this.
