### ISSUE TITLE
PEP 541 Request: Datum

### ISSUE THREAD

**Issue by n3011** [pypa/pypi-support#396]
**Project to be claimed**
`datum`: https://pypi.org/project/datum/

**Your PyPI username**

`USER_NAME`: n3011

**Reasons for the request**
The existing project is dormant, and no actual code release is found.  It is abandoned in July 2014. 
 

**Maintenance or replacement?**
I have developed a new library for tensorflow input pipeline with the same name as this project. I want to publish this package. 

link to the project: https://github.com/openAGI/datum

**Contact and additional research**
Could not reach the current owner.

**Comment by yeraydiazdiaz** [comment]
Hi @n3011, I can confirm `datum` has a single release with no associated files and is therefore considered invalid.

In these cases we attempt contact with the owner and allow a one week courtesy period before transferring the project. I've emailed the owner now.

**Comment by yeraydiazdiaz** [comment]
The owner replied accepting the transfer. I will now ask an admin to perform it for you.

**Comment by n3011** [comment]
@yeraydiazdiaz thank you

**Comment by n3011** [comment]
@yeraydiazdiaz any update on this?

**Comment by n3011** [comment]
@jamadden it would be great if the transfer is completed.

**Comment by ewdurbin** [comment]
Transfer complete.
