### ISSUE TITLE
Claim package looper

### ISSUE THREAD

**Issue by nsheff** [pypa/pypi-support#4]
I originally made this claim request almost a year ago in pypi-legacy: https://github.com/pypa/pypi-legacy/issues/789 -- That claim was never resolved and has since been archived, and now that PEP 541 is official, I wanted to give this another try.

I would like to claim the name `looper` for my project. The current [looper package on pypi](https://pypi.python.org/pypi/looper/1.1) has only one release and the code hasn't been updated in 5 years: https://github.com/CryptoPunk/looper

I have e-mailed the author and started an [issue on GitHub](https://github.com/CryptoPunk/looper/issues/1) but have not received a response from the original author in almost a year. The author is not reachable and I believe the lack of updates fill the requirements for _abandonment_ in PEP 541. In fact it also borders on being an invalid project due to lack of utility ('name squatting'), and only 1 release.

I would like to use the pypi name `looper `for my existing project, (https://github.com/pepkit/looper) which has been under development for several years and is actively used at several research institutions. It would be nice to distribute this via pypi under the existing name. It is not practical to change the name due to widespread use. How can I go about claiming the name?

**Comment by yeraydiazdiaz** [comment]
Hello @nsheff, I've emailed @CryptoPunk regarding this issue, hopefully he will answer soon and we can move forwards with your claim.

Thank you for your patience.

**Comment by yeraydiazdiaz** [comment]
Hello @nsheff, I have received no response from the author after several attempts so this project is now considered abandoned.

Could you confirm your PyPI username so we can proceed with the transfer, please?

**Comment by nsheff** [comment]
@yeraydiazdiaz My username on pypi is the same: `nsheff`.

thank you!

**Comment by ewdurbin** [comment]
Transfer complete.
