### ISSUE TITLE
Limit Request: spacy-lookups-data - 100MB

### ISSUE THREAD

**Issue by ines** [pypa/pypi-support#400]
**Project**

https://pypi.org/project/spacy-lookups-data

**Size of release**

78MB currently, but we'd ideally need 100MB

**Which indexes**

PyPI

**Reasons for the request**

[spaCy](https://pypi.org/project/spacy) is a popular Python library for Natural Language Processing. To provide additional language-specific data (mostly static tables) and to keep the main installation small, we use a separate optional package `spacy-lookups-data`. We want to implement a different system in the future to avoid this large package, but for now, we'd need to be able to upload slightly more data to support additional languages. Thanks a lot in advance!

**Comment by jamadden** [comment]
Hi! The current distribution published on April 28 is just under 30MB. Can you explain why the jump from 30MB to more than twice that? (I would look for changes in the source, but sadly there's no [link to the repo](https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=project_urls#project-urls) on the published page. )

**Comment by ines** [comment]
@jamadden Thanks for getting back and sorry, here's the repo: https://github.com/explosion/spacy-lookups-data/

It mostly comes down to a lot of new languages being added, including more complex languages that require more data (e.g. Polish). As I said, shipping the large resources is unideal and we're working on a better system to avoid this alltogether in the future.

**Comment by pradyunsg** [comment]
Oh hey! A nice round issue number! ^>^

I've gone ahead and set the upload limit on space-lookups-data to 100MB on PyPI. :)

**Comment by ines** [comment]
Thanks a lot, much appreciated! Keep up the good work 🙌
