### ISSUE TITLE
PEP 541 Request: sparky

### ISSUE THREAD

**Issue by NikhilPeri** [pypa/pypi-support#403]
**sparky**

`sparky`: https://pypi.org/project/sparky

**Your PyPI username**

`NikhilPeri`: https://pypi.org/user/nikhilperi

**Reasons for the request**

 - The project has one release in 2013 with no updates since
 - the `setup.py` on this package fails
 - the source code has syntax errors

**Maintenance or replacement?**

- publish a new package containing a framework for building applications with Apache pySpark

**Contact and additional research**

- contacted owner and maintainer by email
-  @lukin0110

**Comment by docyx** [comment]
Your request has been denied.

**Comment by yeraydiazdiaz** [comment]
@docyx are you associated with the `sparky` project at all? Your name doesn't match the owner or author of the project.

**Comment by lukin0110** [comment]
Hey,


*Context*Sparky was a project years ago at the company that I was working
for. Back then decisions were made and the project was abandoned. I was not
even aware I was still on pypi.

I've deleted the project.

Best Regards
Maarten

**Comment by yeraydiazdiaz** [comment]
@lukin0110 thanks for your reply!

**Comment by NikhilPeri** [comment]
Thanks @lukin0110 :)
