### ISSUE TITLE
PEP 541 Request: kivy3

### ISSUE THREAD

**Issue by rnixx** [pypa/pypi-support#407]
**kivy3**

`PROJECT_NAME`: https://pypi.org/project/kivy3

**rnix**

`USER_NAME`: https://pypi.org/user/rnix

**Reasons for the request**

This package has been developed by several individuals for some years. To avoid further cluttering the project has been forked into kivy organization from the most recent fork.

You can find the related discussion here https://github.com/kivy/kivy/issues/6004

The officially maintained repo is now https://github.com/kivy/kivy3

**Maintenance or replacement?**

Package maintenance will be continued

**Contact and additional research**

The developer (https://pypi.org/user/KeyWeeUsr, @KeyWeeUsr) who did the initial release on pypi not replies to requests for package access. I tried via email and via this ticket https://github.com/kivy/kivy3/issues/1 but got no reply for almost a month now.

**Comment by tshirtman** [comment]
As one of the kivy core devs, I can say that sadly KeyWeeUsr seems to have moved to other occupations (open source development was/is a hobby to him as far as i know), we are of course thankful for his help, but sadly while he did this work related to kivy, he apparently forgot to add other contributors to it, as we usually do for other projects, and he has been unresponsive. Hopefully it's possible to add @rnixx  or another contributor from the kivy project so we can give access to whoever is going to maintain this particular package.

**Comment by KeyWeeUsr** [comment]
Hello there. TL;DR: writing to an unmonitored mailbox.

[kivy3-mail-response.pdf](https://github.com/pypa/pypi-support/files/4672246/kivy3-mail-response.pdf)
[master...kivy master.txt](https://github.com/pypa/pypi-support/files/4672249/master.kivy.master.txt)
[master...JohnSumskas master.txt](https://github.com/pypa/pypi-support/files/4672250/master.JohnSumskas.master.txt)
[kivy3-in-org.pdf](https://github.com/pypa/pypi-support/files/4672251/kivy3-in-org.pdf)

**Comment by AndreMiras** [comment]
Thanks a lot we now have access to it. I think the task can be closed now

**Comment by yeraydiazdiaz** [comment]
Thank you for your quick reply @KeyWeeUsr

**Comment by rnixx** [comment]
@KeyWeeUsr 

> Regarding the fork under Kivy org account, well, there's no improvement

All the new work currently lives in development and housekeeping branches.
https://github.com/kivy/kivy3/tree/development
https://github.com/kivy/kivy3/tree/housekeeping

Anyway, thanks for taking action.
