### ISSUE TITLE
PEP 541 Request: elegant

### ISSUE THREAD

**Issue by dioph** [pypa/pypi-support#409]
**Project to be claimed**

`elegant`: https://pypi.org/project/elegant

**Your PyPI username**

`dioph`: https://pypi.org/user/dioph

**Reasons for the request**

We believe that, in terms of PEP 541, the current state of `elegant` fits the definition of an invalid project.
It seems like a case of name squatting, with no releases past version 0.0.0 and no functionality whatsoever. All other [projects by this author](https://pypi.org/user/Collie) indicate the same scenario.

**Maintenance or replacement?**

We intend to replace it with our package (https://github.com/dioph/elegant). We've already been hosting the documentation at https://elegant.readthedocs.io.

**Contact and additional research**

There is no email information on the current owner's PyPI profile and in none of their projects; also, we could not find a corresponding project repository and/or GitHub account.

**Comment by yeraydiazdiaz** [comment]
Hi @dioph, I can confirm `elegant` has no functionality as it consists only of a `setup.py` and an empty `__init__.py`, it is therefore considered invalid.

I will attempt contact with the owner and allow for a one week courtesy period before moving forward with your request.

**Comment by yeraydiazdiaz** [comment]
I have not received a reply in this courtesy period so I will now ask an admin to perform the transfer for you.

**Comment by dioph** [comment]
@yeraydiazdiaz, thank you for the help.

**Comment by dioph** [comment]
Hello there! Any updates on this?

**Comment by jamadden** [comment]
This has been flagged for the admins to transfer. Please keep in mind that there are a large number of these requests and a very small number of admins. Thank you!

**Comment by ewdurbin** [comment]
Transfer complete.
