### ISSUE TITLE
PEP541: squatter on `dryice`

### ISSUE THREAD

**Issue by rscottbailey** [pypa/pypi-support#41]
I have a project called dryice that I would like to upload to pypi but the name is being squatted - https://pypi.org/project/dryice/ .

The current owner has not published any code and has no contact information. Can I please take over ownership of the dryice name on pypi as user rscottbailey?

Thank you all again for your work!

**Comment by yeraydiazdiaz** [comment]
Hello @rscottbailey, I can confirm the project `dryice` has no functionality and is therefore considered invalid.

I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
transfer complete.
