### ISSUE TITLE
Limit Request: analytics-zoo - 250MB

### ISSUE THREAD

**Issue by qiuxin2012** [pypa/pypi-support#410]
**Project**
https://pypi.org/project/analytics-zoo/

**Size of release**
215MB

**Which indexes**
both

**Reasons for the request**
Perviously, we increase the limit to 200MB by https://github.com/pypa/warehouse/issues/6140, but after one year's development, the size increased to 215MB. So if it is possible to increase the limit of https://pypi.org/project/analytics-zoo/ to 250MB?

Analytics Zoo (https://github.com/intel-analytics/analytics-zoo) is a unified analytics + AI platform for distributed TensorFlow, Pytorch, Keras and BigDL on Apache Spark; and the reason for the large size (esp. for the upcoming releases) is that it will include more .so files for hardware accelerations, model optimizations, etc.

**Comment by qiuxin2012** [comment]
Could some one help?

**Comment by jamadden** [comment]
Let me make sure I understand. [The current release](https://pypi.org/project/analytics-zoo/0.8.1/#files) of this project has a maximum wheel size of 186MB, which is below the 200MB limit. You're saying that the next release will grow by at least 215 - 186 = 29MB?

One year ago, the largest wheel in the 0.5 release was 120MB, so there was a growth of over 60MB in a year. Do you expect the project to continue to grow at this rate?

**Comment by di** [comment]
Closing due to lack of response.
