### ISSUE TITLE
Issue: Limit Request: Nighres - 163MB

### ISSUE THREAD

**Issue by juhuntenburg** [pypa/pypi-support#411]
**Project**
Nighres
https://pypi.org/project/nighres/

**Size of release**
163MB

**Which indexes**
PyPI

**Reasons for the request**
This is a processing toolbox for high-resolution data processing. While we keep all example data separate to be downloaded upon request, there are a few essential atlas files that currently ship with the package. 
We plan to change this structure to keep atlas files on a seperate server, but would like to make this release before fixing that issue

**Comment by jamadden** [comment]
Just so I understand, the project publishes a single source distribution (.tar.gz). It is currently 16MB. That source distribution will temporarily increase in size to 163MB, but in the future, new distributions will again be smaller. Is that right?

**Comment by di** [comment]
Closing due to lack of response.
