### ISSUE TITLE
PEP 541 Request: darts

### ISSUE THREAD

**Issue by TheMP** [pypa/pypi-support#412]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/darts

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/unit8

**Reasons for the request**

We are working on a timeseries library and would like to publish it open-source. Darts would be a perfect name although uploading the package fails - seems like the name is registered but there is no package currently placed in that location, so it doesn't look like the pypi register is being used.

**Maintenance or replacement?**

Replacement, we intend to publish our library https://github.com/unit8co/u8timeseries that we plan to maintain and keep updating.
**Contact and additional research**

Since the package is not visible on PyPi it is not possible for us to track the current owner of the repo.

**Comment by yeraydiazdiaz** [comment]
Hi @TheMP, I can confirm `darts` has no releases and is therefore considered invalid.

I've contacted the owner and will allow for a one week courtesy period before moving on with the transfer.

**Comment by TheMP** [comment]
Hi @yeraydiazdiaz, any news on the `darts` repo name?

**Comment by yeraydiazdiaz** [comment]
Hi @TheMP, I have not received any reply from the owner so I will now ask an admin to perform the transfer for you.

There's a bit of a backlog on these, so please bear with us.

**Comment by TheMP** [comment]
Hi @yeraydiazdiaz, thanks for the info! Sorry for rushing, we are trying to make it work for our release that's coming soon :). 

Are you maybe able to guess if it is approximately going to take a few more days or rather weeks?

**Comment by TheMP** [comment]
Hi @yeraydiazdiaz , any news on this ticket? Is there a chance it is going to be applied in the nearest weeks?

**Comment by ewdurbin** [comment]
Transfer complete.
