### ISSUE TITLE
Limit Request: ort-gpu-nightly-training - 120MB

### ISSUE THREAD

**Issue by edgchen1** [pypa/pypi-support#414]
**Project**

ort-gpu-nightly-training
https://test.pypi.org/project/ort-gpu-nightly-training/

**Size of release**

The size is currently 112 MB. However, it would be nice to have a limit like 120MB to have some extra headroom to allow for minor increases.

**Which indexes**

Test PyPI

**Reasons for the request**

ONNX Runtime is a performance-focused scoring engine for Open Neural Network Exchange (ONNX) models. This package has training functionality enabled. It requires some additional libraries like NCCL and MPI so the size is larger compared to other ONNX Runtime packages. It is possible that the size will increase again in the future if additional dependencies are added.

**Comment by jamadden** [comment]
The limit has been increased on Test PyPI. Keep in mind there is an overall limit for all files in the project as well; removing old files may sometimes be necessary.
