### ISSUE TITLE
PEP 541 Request: pyweb - resume development into my new PyPI user account

### ISSUE THREAD

**Issue by davidmcnabnz** [pypa/pypi-support#416]
**pyweb**

`PROJECT_NAME`: https://pypi.org/project/pyweb

**davidmcnabnz**

`USER_NAME`: https://pypi.org/user/davidmcnabnz

I am the original author of this project, which I worked on between 2003 and 2009. At the time, I used the email address david@freenet.org.nz.

However, I mistakenly allowed the registration of domain freenet.org.nz to lapse into the possession of a domain squatter, so am unable to regain the david@freenet.org.nz email address.

I expect you will not accept this claim at face value, so if necessary I would be willing to provide you with photographic ID such as passport or driver license through a private channel to authenticate my identity.

It is very important to me to be able to revive this project and take control of it into my new pypy user account of davidmcnabnz. With the economic changes resulting from COVID19, I have re-intensified my development work, and have a major project requiring the pyweb code.

However, pyweb needs some critical care to make it Python3.6+ ready, plus a whole range of other maintenance, to get it into shape for a new release.

**Maintenance**

I intend to get the code into shape for current Python versions, and to regularly publish new releases.

**Contact and additional research**

I am the original author.

**Comment by yeraydiazdiaz** [comment]
Hi @davidmcnabnz, `pyweb`'s owner is PyPI user `ubuntu` who published the project's only release in 2009. Could you confirm that was not your previous account? If it is we can resolve this via an account recovery request.

Otherwise I can start the reachability process for you.

**Comment by davidmcnabnz** [comment]
Hi yeraydiazdiaz,

Thanks for commencing investigations into this. I can confirm that I have never used the user account 'ubuntu'. Please start the reachability process as soon as you can.

My best estimation is that someone using the account name 'ubuntu' has benevolently uploaded the pyweb package to share, because it previously was just sitting on my own private website, which (due to expiry and loss of freenet.org.nz domain) I am no longer able to revive.

I'd almost forgotten about this package, but I'm now in a project situation (large web app for a major university) where it'll be very useful. Also, I think it would be a great inclusion in pypy but desperately needs 'modernisation' to current Pythons and practices. I'm doing this modernisation right now with my most recent copy of the code on my old disks.

**Comment by yeraydiazdiaz** [comment]
Thanks for confirming that @davidmcnabnz, I've emailed PyPI user `ubuntu`, hopefully we'll hear back soon and move forward with your transfer.

**Comment by yeraydiazdiaz** [comment]
I have not received any reply from the current owner, as such this project is now considered abandoned. I will now ask an admin to perform the transfer for you. Apologies for the delay.

**Comment by davidmcnabnz** [comment]
Hi Yeray,
Thanks for that. Much appreciated. I look forward to receiving control and
reviving the project to its next levels.
David

**Comment by ewdurbin** [comment]
Transfer complete.
