### ISSUE TITLE
PEP 541 Request: pyproject

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypi-support#417]
**Project to be claimed**

`pyproject`: https://pypi.org/project/pyproject

**Your PyPI username**

`pradyunsg`: https://pypi.org/user/pradyunsg

**Reasons for the request**

Currently, the project is Invalid, and also satisfies the requirements for being Abandoned (other than the reach-ability criterion).

**Maintenance or replacement?**

Replacement, with a (to be written) library for processing pyproject.toml files.

**Contact and additional research**

None -- project has had no releases since 2014.

**Comment by hugovk** [comment]
Which of the criteria for an invalid project is met? 

https://www.python.org/dev/peps/pep-0541/#invalid-projects

**Comment by yeraydiazdiaz** [comment]
Hey @pradyunsg, I don't think `pyproject` can be considered invalid as there's some clear functionality there, it's also worth mentioning the project also has had [roughly 1K downloads in the past 30 days](https://pepy.tech/project/pyproject). That being said it certainly hasn't been updated so it _could_ be considered abandoned but not sure if a complete replacement would be a good idea.

Looks like Github user @vmalloc is the current owner of the project, hopefully he can clarify his position regarding `pyproject`.

**Comment by vmalloc** [comment]
Wow, I'm fairly surprised this has just been opened as a claim without even talking to me once before opening it. I think it's a bit rude tbh.

I have several projects that are not being made into releases often and some of them are still in production use in all sorts of places. I hate the fact that the moment I don't pay enough attention to my GH inbox some of them can just be yanked like that based on requests such as this one.

@yeraydiazdiaz thanks for cc'ing me and getting my attention...

**Comment by yeraydiazdiaz** [comment]
> I hate the fact that the moment I don't pay enough attention to my GH inbox some of them can just be yanked like that based on requests such as this one.

Just to be clear, nobody's yanking anything. A request was made under PEP 541 which clearly reads the owner is entitled to deny the request, which you have just done. It's all part of the process: creating a dialogue between claimer and owner.

I will now close this issue based on your reply, thanks for getting back to us.

**Comment by vmalloc** [comment]
@yeraydiazdiaz Yeah, sorry I came off like that. Of course it wasn't directed at you :-)

Thanks!
