### ISSUE TITLE
PEP 541 Request: colout

### ISSUE THREAD

**Issue by stdedos** [pypa/pypi-support#418]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/colout/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/stdedos

**Reasons for the request**

Author has authorized me to update the package https://github.com/nojhan/colout/pull/108#issuecomment-634754631
Current author https://pypi.org/user/dongweiming/ has no e-mail address listed in his profile.

I can add any or both of them as a side-maintainer if/when they request so at any time.

**Maintenance or replacement?**

Maintain

**Contact and additional research**

**Comment by nojhan** [comment]
OK for letting @stdedos update the package, while being a side maintainer.

**Comment by yeraydiazdiaz** [comment]
I believe GitHub user @dongweiming is the owner of the `colout` PyPI project, tagging as first attempt of contact.

**Comment by stdedos** [comment]
Good catch! Maybe I should've tried a bit more to track him down.

However, he doesn't seem to own `colout` _per se_, but rather `colout-ppa` (https://github.com/dongweiming?tab=repositories&q=colout&type=source&language=)

Of course, if this helps resolve it with a out-of-PEP-541 settlement, fine by everyone I guess

**Comment by dongweiming** [comment]
@stdedos I'm very sorry that I took this package name, it was indeed created by me. I agree to hand it over. Could you tell me your pypi username?

**Comment by stdedos** [comment]
> @stdedos I'm very sorry that I took this package name, it was indeed created by me.

No worries! It's just that there are updates available, and the package (nor the PPA) were updated - I thought you were off-the-grid or something.

> I agree to hand it over. Could you tell me your pypi username?

Same as here, https://pypi.org/user/stdedos/

**Comment by dongweiming** [comment]
@stdedos I have added the owner role to you, and now you should have all permissions. Please contact me if you have any questions, you are welcome

**Comment by dongweiming** [comment]
@stdedos  I have added the owner role to you, and now you should have all permissions. Please contact me if you have any problems, you are welcome

**Comment by jamadden** [comment]
Confirmed the new rights are in place. Closing.

**Comment by stdedos** [comment]
I have asked (via a different medium this time), for rights to the test.pypi.com project.

I would've closed soon after.

**Comment by stdedos** [comment]
Ping @Code0x58

**Comment by Code0x58** [comment]
@stdedos Nice to see a release :D I set you as the owner of the test pypi repo, feel free to remove me
