### ISSUE TITLE
Limit Request: kukolex - 62MB

### ISSUE THREAD

**Issue by nlpai-lab** [pypa/pypi-support#420]
We uploaded kukolex=0.0.0 file.

**Project**
 kukolex=0.0.0

**Size of release**
 We need at least 62MB due to lots of dictionary files for morpheme analyzing.

**Which indexes**
 PyPI

**Reasons for the request**
 We expect size limit of 0.0.1 version of our file to be increased to 62MB, so that we can upload our whole file. Thank you!

**Comment by jamadden** [comment]
The [source repository linked as the homepage](https://github.com/nlpai-lab/KU_KoLex/) of the project currently contains compiled Linux binaries for an executable, [data/kmat/bin/kmat](  https://github.com/nlpai-lab/KU_KoLex/commit/da5928aa3a3eaea79906f08d629478bb4ab6ac52#diff-f5ed059f4585af58525d8aacfb5a483d). The source .py files [attempt to execute this binary](https://github.com/nlpai-lab/KU_KoLex/blob/18310c31872254a886b3fa70c22fc69942daecde/KUKoLex/kukolex.py#L7): 
```python
def pos_tagging(sentence):
    # korea univ morpheme analyzer
    sentence.encode('utf-8').decode('utf-8')
    m_command = "cd data/kmat/bin/;./kmat <<<\'" + sentence + "\' 2>/dev/null"

    result = subprocess.check_output(m_command.encode(encoding='cp949', errors='ignore'), shell=True,
                                     executable='/bin/bash')
```

I'm trying to understand what the space usage will be like. Do you expect to re-compile this executable for different platforms and distribute multiple binary wheels, or will you only distribute a single `manylinux` wheel? How often do you expect this package to be updated?

If I may offer some advice, it's unlikely that a wheel built with the setup.py and setup.cfg currently committed to master in that repository will work when installed, even when a platform compatible with the executables is used. The current working directory of the user is unlikely to be one that contains `data/kmat/bin` and `data/kmat/bin/../rsc` (where `../rsc` is hardcoded into the `kmat` executable). Even if the wheel has the appropriate options set to install that data, it may wind up in some `site-packages` directory of a virtual environment or some other place out of the way.  This means that the Python code will not be able to find and execute that binary. To fix things like this, one common way is to arrange for setuptools to install data files as "package data" alongside the .py files, and then use `__file__` to determine their location relative to the .py file.

**Comment by di** [comment]
The per-file limit is now 100MB for all of PyPI.
