### ISSUE TITLE
PEP 541 Request: gym-sawyer

### ISSUE THREAD

**Issue by geyang** [pypa/pypi-support#423]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/gym-sawyer

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/episodeyang

**Reasons for the request**

Looking at the files, this package is empty: the original wheel upload is only 1.0 kb in size. At the same time, the standard Sawyer environment we use is about 40 MB in size.

**Maintenance or replacement?**

There is current no code living in this package. The package I intend to publish is already open sourced (complete w. license) and is functional. For details of this package that I intend to publish, please refer to this GitHub repository: 

https://github.com/geyang/gym-sawyer

**Contact and additional research**

I just contacted the owner, would update when I hear back.

**Comment by yeraydiazdiaz** [comment]
Hi @geyang, I can confirm the project has no functionality and is therefore considered invalid.

Looks like user GitHub user @ryanjulian is the owner of the package, tagging him as a means of contact for the one week courtesy period before proceeding with the transfer.

**Comment by geyang** [comment]
@yeraydiazdiaz Ryan has gotten back to be couple of days ago, and this is right before the deadline for one of the major machine learning conferences so he might be super busy :)

**Comment by ryanjulian** [comment]
@geyang @yeraydiazdiaz Thanks for @'ing me! The project name gym-sawyer is actively maintained, on GitHub but we never finished crafting and uploading our PyPI distribution for it. 

Since I'm not personally actively maintaining the project, I'm not categorically opposed to handing off the PyPI name, but I want to make sure I understand the impact on existing users and maintainers first.

There were several active users of the GitHub project as of a year ago, but I have not checked recently whether usage has increased or trailed off since then, and will go do that now by contacting our active users. There are also a couple maintainers to whom I handed off maintenance, who I will contact to ask about their future plans. I'll check out @geyang 's package to see if it offers the same functionality as ours to existing users, in case we decide to retire ours.

I should be able to get back to @geyang within a week.

**Comment by geyang** [comment]
@ryanjulian Just to confirm, the `gym-sawyer` project you mentioned is a private Git project, so it currently bears no relationship to the PyPI project we are talking about here, is this correct?

> The project name gym-sawyer is actively maintained on GitHub, but we never finished crafting and uploading our PyPI distribution for it.

Yeah, I definite feel that hesitation in releasing my own code :)

> I want to make sure I understand the impact on existing users and maintainers first.

In this case, the existing users would be of that private project, as opposed to this PyPI package. There does not seem to be existing users of this package because the package is empty.

**Comment by ryanjulian** [comment]
@geyang it's a public project here https://github.com/rlworkgroup/gym-sawyer

**Comment by ryanjulian** [comment]
@geyang I think you might be mistaken about the features of our package.

While ROS integration is a feature of our package, the package can be run without ROS at all as a standalone simulation environment, just as yours can. If you look closely, the set of available environments in our package is very similar to yours, including support for multitask learning. 

While we never uploaded the package to PyPI (our mistake), it's pretty obvious that most users assume a nearly 1:1 correspondence between GitHub project names and PyPI project names. Users installing from https://github.com/rlworkgroup/gym-sawyer, who discover `pip install gym-sawyer` would be right to be surprised that they end up with a different package.

Again, please give me some time to talk to maintainers about how they feel about the future of the package, and if they'd like to hand over usage of the name to you. My goal is ensuring that users have access to the best, most well-maintained software the community can provide.

**Comment by yeraydiazdiaz** [comment]
@ryanjulian thanks for getting back to us on this. I'm going to close this issue for housekeeping and since contact has been made, but feel free to keep commenting if you wish.

**Comment by geyang** [comment]
> Hi @geyang, I can confirm the project has no functionality and is therefore considered invalid.
> 
> Looks like user GitHub user ryanjulian is the owner of the package, tagging him as a means of contact for the one week courtesy period before proceeding with the transfer.

@yeraydiazdiaz is there a timeline for resolution, given the current status of this package?

**Comment by yeraydiazdiaz** [comment]
@geyang once contact with the owner has been established it's a matter of the two parties coming to a resolution. @ryanjulian asked for some time to speak to the other maintainers to decide the next steps.

Us moderators don't intervene beyond that, which is why I closed this issue.

**Comment by geyang** [comment]
@yeraydiazdiaz Sound good! In that case I will check back in couple of weeks with @ryanjulian to see if there is any update. Is this issue still going to be here? I noticed that the last issue on PEP541 was sometime in May, so I wonder if these issues are periodically removed.

**Comment by geyang** [comment]
> Again, please give me some time to talk to maintainers about how they feel about the future of the package, and if they'd like to hand over usage of the name to you. My goal is ensuring that users have access to the best, most well-maintained software the community can provide.

Hi @ryanjulian, is there any update to this issue? Thanks!
