### ISSUE TITLE
PEP 541 Request: ar

### ISSUE THREAD

**Issue by vidstige** [pypa/pypi-support#425]
**Project name**

`ar`: https://pypi.org/project/ar

**Your PyPI username**

`vidstige`: https://pypi.org/user/vidstige

**Reasons for the request**
I'm quoting my old claim from over here: https://sourceforge.net/p/pypi/support-requests/754/
Hi,
I've got a small python package for handling the ar file format used in e.g. .a files on linux, etc. The name 'pyar' seems suitable, hower it's used by some other package that seems unrelated. It not being updated and there is no email available. I downloaded the source code from pypi and found an email inside one of the source files, however, I've gotten no reply. Also the name 'ar' seems suitable. It's even in worse shape. No documentation, no email, no links, no nothing. Further more the code seems useless and contains symbols containing the word "lol", etc. It seems mostly like a troll package of sorts.

The reason I would like either one of these names is to keep with the friendly python idea of pip - Things are easy to find. As I see it, I've fulfilled the criterions listed under PEP-0541 and would like to claim ownership of either 'pyar' or 'ar' to myself. My username on pypi is "vidstige".

name: Samuel Carlsson
email: samuel.carlsson@gmail.com
pypi: vidstige

Thanks in advance for helping me contribute to the awesome python community.

**Maintenance or replacement?**

I intend to replace the package.

**Contact and additional research**

I've found no mail or other way to contact the current owner.

**Comment by yeraydiazdiaz** [comment]
Hello @vidstige, I can confirm the `ar` project has no functionality and is thus considered invalid.

I will attempt contact with the owner for a courtesy period of one week before moving forwards with the transfer.

**Comment by vidstige** [comment]
Thanks for keeping me updated

**Comment by yeraydiazdiaz** [comment]
I have not received any response from the owner so I will now ask an admin to perform the transfer for you.

**Comment by vidstige** [comment]
That's good news. Thank you very much!

**Comment by vidstige** [comment]
Hi,
Any news on the admin transfer?

**Comment by vidstige** [comment]
Hi @yeraydiazdiaz, what did the administrator say? What's the latest update on this issue?

**Comment by vidstige** [comment]
Monthly ping on this issue. :) Thanks in advance

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by vidstige** [comment]
:raised_hands: :champagne: 

Thanks guys! Let's see if I can find that code I wanted to push three years ago somewhere... :see_no_evil:

**Comment by vidstige** [comment]
Alright found the code on my old mac. Added a few tests and a travis build. The python community is one utility library richer - `ar`! :-D :champagne: 

https://pypi.org/project/ar/
