### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Ilyushin** [pypa/pypi-support#426]
Request for account recovery.

## PyPI Username

`ilyushin`

---

##  Reason for request  
  - Lost 2FA authentication app or security token

Reason:
Bought a new phone. Didn't generate security tokens.

**Comment by Ilyushin** [comment]
Guys, help me, please.

**Comment by Ilyushin** [comment]
Up

**Comment by Ilyushin** [comment]
@ewdurbin please, recovery access to my account. It blocks us.

**Comment by Ilyushin** [comment]
Guys, why can't you help?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
