### ISSUE TITLE
Limit Request: ling-gender - 250MB

### ISSUE THREAD

**Issue by ksdkamesh99** [pypa/pypi-support#427]
**Project**
ling-gender 2.0.0

**Size of release**
220MB

**Which indexes**
both

**Reasons for the request**
Sir/Mam
I am deploying a natural language processing model which is of large size which is a project to classify gender of a person based on the first name so please increase my size

**Comment by jamadden** [comment]
The project `ling-gender` does not exist on PyPI. You'll need to create it first before a limit can be changed.

That said, moderators are encouraged to help packages find alternatives to distributing such large files on PyPI, especially if they will be updated often. One such alternative is to side-load (e.g., download, possibly from HTTP(S)) the data file. This can be done at installation time, or on-demand; providing a tool to do this with your library could let users independently update the model.

**Comment by ksdkamesh99** [comment]
ok, I will definitely try it out @jamadden . Thanks for responding to my issue
