### ISSUE TITLE
PEP 541 Request: Claim ownership of magic project

### ISSUE THREAD

**Issue by zoulasc** [pypa/pypi-support#429]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/magic

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/zoulasc

**Reasons for the request**
I am the owner/maintainer of the file(1) package for Unix which has python language bindings for libmagic(3). I distribute those bindings at: https://pypi.org/project/file-magic/
The "magic 0.1" package seems abandoned (not updated since 2003). 

**Maintenance or replacement?**
Yes, I will continue to maintain it.

**Contact and additional research**
I have tried to contact "jpetrone" jp-py@jsnp.net who owns the "magic" package, but have gotten no response.

**Comment by eli-schwartz** [comment]
See also my original upstream report: https://bugs.astron.com/view.php?id=15

Archived ticket at https://github.com/pypa/pypi-legacy/issues/802

@zoulasc you forgot to replace "PROJECT_NAME" with the name itself. :D

**Comment by zoulasc** [comment]
fixed :-)

**Comment by eli-schwartz** [comment]
Can you fix the issue title as well as the issue description? :)

**Comment by yeraydiazdiaz** [comment]
I can confirm the project `magic` has a single release with no associated files and as such it is considered invalid and thus subject for transfer.

In these cases we moderators attempt contact with the current owner and allow a courtesy period of one week before proceeding.

**Comment by yeraydiazdiaz** [comment]
I have not received response so will now ask an admin to perform the transfer.

**Comment by zoulasc** [comment]
Is there anything you need me to do?

**Comment by ewdurbin** [comment]
Transfer complete.
