### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kornicameister** [pypa/pypi-support#430]
Request for account recovery.

## PyPI Username

kornicameister

---

##  Reason for request

Reason:

- Lost 2FA authentication app or security token
- Broken phone restored to factory settings.

**Comment by kornicameister** [comment]
nearly a month and no action?
this is quite low level quality service? sorry for being not exactly polite, but I am waiting and waiting for someone to help out.
I've lost access to account because of the broken phone and would really like to get back on track here.

**Comment by kornicameister** [comment]
@yeraydiazdiaz sorry for pinging you here, but I really really really would like to get my account back. Is there any way you could ping someone to help me out?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@kornicameister do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: kornicameister" to proceed

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
