### ISSUE TITLE
PEP 541 Request: winpdb

### ISSUE THREAD

**Issue by bluebird75** [pypa/pypi-support#431]
**Project to be claimed**

`winpdb`: https://pypi.org/project/winpdb/

**Your PyPI username**

`bluebird75`: https://pypi.org/user/bluebird75/

**Reasons for the request**

My request is related to the project page of Winpdb, a standalone portable WxPython debugger. It has been developed by Nir Aides, initially on google code. See ( http://www.winpdb.org and https://pypi.python.org/pypi/winpdb ). The last release of winpdb is version 1.4.8, in 2010.

Since 2013, I have been maintaining a bug-fixed version on Github, which fixes a few annoying bugs, removes a few annoyances and provides more compatibility with latest versions of Python. A kind of a friendly fork, which I properly reference the history of the project.

In 2014, I exchanged a few emails with Nir Aides, the author, to have my version reviewed and possibly published. Unfortunately this never happened, despite several reminders.

This could have been fine, but lately, with google code shutdown, the packaged version on PyPi no longer works: it pulls a previous buggy version of winpdb due to dead google code links (see bluebird75/winpdb#6 ).

My multiple attempts to contact the author to fix this issue have been unanswered.

I therefore would like to become the de facto author on the PyPi page, in order to fix the issue above, and even release the latest bugfixed version.

Note that in the mean time, I have released winpdb-reborn to have at least a working version available in the wild.

**Maintenance or replacement?**

Several emails, as soon as I noticed the unmaintained status in 2010. Many more until 2015 to try to resurrect this, but no answer.

**Comment by bluebird75** [comment]
Note that even the website of windpb is no longer maintained : http://www.winpdb.org/

**Comment by yeraydiazdiaz** [comment]
Hello @bluebird75, the project does seem to be in an odd state with the last two releases not having any associated files.

Seems GitHub user @nir might be the current owner of the package, I will also attempt contact via email.

**Comment by nir** [comment]
Hi, I'm the owner of the winpdb pypi package page. I have corresponded with Yeray and Philippe about this request. Philippe has been maintaining his fork of Winpdb over the past decade! 

Since I have no plans to resume development of Winpdb I believe it is a good idea to give him control over the pypi package page under the following condition, that the current GPL license remains and that I remain listed as the copyright owner of the code that I have written. Philippe may add his name to mine as the copyright owner to the changes that he made and will do to the code. 

I will contact Yeray by email to grant permission to this change.

Good luck Philippe!

**Comment by bluebird75** [comment]
I am ok with that. The copyright and readme are already giving proper attribution to both of us for the respective periods.

**Comment by nir** [comment]
As I agreed with @bluebird75 in private correspondence, I have made him a co-owner of the winpdb pypi package page. Good luck with the project!

**Comment by bluebird75** [comment]
Since we resolved the issue together with Nir about package ownership, this request is no longer useful. I am closing it.
