### ISSUE TITLE
Limit Request: peak-finder - 130MB

### ISSUE THREAD

**Issue by GabePoel** [pypa/pypi-support#432]
**Project**

Project Name: peak-finder
PyPI Page: [https://pypi.org/project/peak-finder/](https://pypi.org/project/peak-finder/)

**Size of release**

The new release is just under 130MB. I would like the limit increased to at least that. Ideally, it would be increased more since I suspect the project size to grow in the future as more models are added (see "Reasons for the request").

**Which indexes**

Just PyPI for now.

**Reasons for the request**

The project detects Lorentzian (Cauchy) distributions in resonant ultrasound spectroscopy data. To do this, it uses several machine learning models to detect the Lorentzian resonances under different conditions. Those models are decently large and have previously been packaged separately. But, I would like to start including them in the release.

**Comment by jamadden** [comment]
> Those models are decently large and have previously been packaged separately. But, I would like to start including them in the release.

In general, PyPI encourages distributing large models/datasets separately (especially if they can change independently of the code). This project is still small enough that PyPI could accommodate it, but if there is already a working data distribution mechanism, it might be better to continue with that. Would that be possible?

**Comment by GabePoel** [comment]
It would be _possible_, but would also be somewhat inconvenient. I don't expect the included models to keep changing. So, if PyPI could accommodate, that would definitely be the most preferable option. Thank you!

**Comment by di** [comment]
I've set the upload limit for `peak-finder` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
