### ISSUE TITLE
PEP 541 Request: loupe

### ISSUE THREAD

**Issue by andykee** [pypa/pypi-support#433]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/loupe

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/andykee

**Reasons for the request**
Based on PEP 541 the current state of ``loupe`` is invalid as it has no functionality/is empty. Attempting to install loupe results in the following error:

```
$ pip install loupe
ERROR: Could not find a version that satisfies the requirement loupe (from versions: none)
ERROR: No matching distribution found for loupe
```
**Maintenance or replacement?**
I intend to replace it with my own library, which I was recently approved to be open sourced by my employer (NASA Jet Propulsion Lab). The library is currently used by NASA scientists and engineers to evaluate imaging performance of astronomical telescopes. The library is currently called `monocle` at JPL but will be renamed `loupe` if this request is approved. (PyPi already hosts a package called monocle)

I have not uploaded the source/docs/tests to my GitHub repo yet as I am waiting until I have a valid name for the package, but I am happy to upload everything if that will help move this process along.

**Contact and additional research**
The current owner does not have an email address listed on their profile. There is no accompanying `loupe` GitHub repo.

**Comment by jamadden** [comment]
I agree that https://pypi.org/project/loupe is an invalid project by the PEP definition, making it subject to transfer. 

We like to give the current owner a week's notice before doing so. Often the current owner is happy to perform the transfer themself. Based on other projects, I think that the PyPI owner https://pypi.org/user/r.elsmore/ is the github user @rhyselsmore. Tagging that account here since it seems active on GitHub.

**Comment by andykee** [comment]
Hi, just wanted to check in on the progress of this request.

Thanks!

**Comment by jamadden** [comment]
Thanks for the prod. No response has been received. This issue has been tagged for the admins to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
