### ISSUE TITLE
PEP 541 Request: odyssey

### ISSUE THREAD

**Issue by GodwinneLorayne** [pypa/pypi-support#434]
**Project to be claimed**

`odyssey`: https://pypi.org/project/odyssey

**Your PyPI username**

`GodwinneLorayne`: https://pypi.org/user/GodwinneLorayne

**Reasons for the request**

- No releases have been published for this name
- Because of this, the owner is unlisted and therefore unreachable
- I cannot tell when the name was reserved

**Maintenance or replacement?**

I intend to publish my own repository from github under this name.
https://github.com/python-odyssey/odyssey

**Contact and additional research**

- Owner cannot be contacted because the project has no listed releases.
- Potential existing owning repositories:
https://github.com/alan97/odyssey
last commit 2 years ago
https://github.com/austinbenincasa/Odyssey
last commit 3 years ago

**Comment by yeraydiazdiaz** [comment]
Hello @GodwinneLorayne, I can confirm the project has no releases and is therefore considered invalid and to be transferred.

I will now send an email to the owner letting them know of this and wait a courtesy period of one week before proceeding.

**Comment by GodwinneLorayne** [comment]
@yeraydiazdiaz Thank you for your help on this! After you sent your email I got into contact with the project owner and they most graciously transferred it to me on their own. Closing this issue.
