### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mastrobirraio** [pypa/pypi-support#437]
Request for account recovery.

## PyPI Username

`mastrobirraio`

Reason: I've lost my device with 2FA application and recovery codes.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by mastrobirraio** [comment]
@ewdurbin sorry, can u link me something?
pypi login doesn't allow to login via email

**Comment by ewdurbin** [comment]
@mastrobirraio The message was sent via email.

**Comment by mastrobirraio** [comment]
@ewdurbin ok, I followed the instructions

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
