### ISSUE TITLE
PEP 541 Request: Marker

### ISSUE THREAD

**Issue by mustafaquraish** [pypa/pypi-support#438]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/marker

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/mustafaquraish

**Reasons for the request**

 I have recently developed a package consisting of utilities to automate and assist marking coding exercises. The package name of `marker` would be great for this, and it doesn't seem like there has been anything with this name recently.
```
mustafa$ pip3 install marker
ERROR: Could not find a version that satisfies the requirement marker (from versions: none)
ERROR: No matching distribution found for marker
```

**Maintenance or replacement?**

I don't know the purpose of the original package since it is not available to download, so I intend to replace it.

**Contact and additional research**

I have found no way to find or contact the previous owner

**Comment by yeraydiazdiaz** [comment]
Hello @mustafaquraish, I can confirm the project has no releases and is therefore considered invalid and to be transferred.

I will now contact the owner letting them know of this fact and allow a courtesy period of one week before proceeding.

**Comment by mustafaquraish** [comment]
Hey! Any updates from the owner of the repo? If not - any idea how long it would take for the transfer to take place? I see there's a bit of a backlog... are we talking days or weeks?

**Comment by mustafaquraish** [comment]
@jamadden tagging you since you seem to be more active here. Any update on this?

**Comment by jamadden** [comment]
Assuming that @yeraydiazdiaz did not receive any response, I've flagged this for admin attention and transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
