### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vputz** [pypa/pypi-support#439]
Request for account recovery.

## PyPI Username

`qcware on test.pypi.org`

---

##  Reason for request

Reason:
Lost access to the email address for the qcware account on test.pypi.org (we can access the one on pypi.org, and the replacement account `qcwaretest` on test.pypi.org!  The individual with the email address used for the `qcware` account on test.pypi.org has left us and we can no longer contact them.  You can contact myself or any of the verified email addresses for `qcware` (pypi.org) or `qcwaretest` (test.pypi.org).

cheers!

**Comment by ewdurbin** [comment]
Both addresses associated with the account on PyPI have been added to the account on TestPyPI with a `+testpypi` appended since they are currently associated with another account on test.pypi.org.

You should now be able to process a password reset to regain access to the account.
