### ISSUE TITLE
Limit Request: tr - 200MB

### ISSUE THREAD

**Issue by myhub** [pypa/pypi-support#44]
Hi all
My project is tr (https://pypi.org/project/tr/)
it is a deep learning based OCR system which include many .so files and big deep learning model parameter files(for text line detection and text recognition), 
I want a size around 200Mb to store so many files, Thanks

**Comment by myhub** [comment]
@jamadden I have some trouble to make tr many-linux compatible because I use libtorch which is not many-linux compatible. But I now make tr run on windows https://github.com/myhub/tr/tree/windows

**Comment by di** [comment]
Hi @myhub, do you still need the limit increase, or can this issue be closed?

**Comment by myhub** [comment]
Yes, I want a limit increase to 200MB.
