### ISSUE TITLE
PEP 541 Request: vilib

### ISSUE THREAD

**Issue by mitch3x3** [pypa/pypi-support#440]
`vilib`: https://pypi.org/project/vilib

**Your PyPI username**
`mitch3x3`: https://pypi.org/user/mitch3x3

**Reasons for the request**
There hasn't been a new release since May 24, 2011. Definitely abandoned. I could pick a new name but I feel that it would be best for me to use this one since my newer code is so similar to this original package in scope, but with a few additions. My first attempt to contact the maintainer received a response that didn't address this name change request. My next attempts were ignored. That was 8 weeks ago.

**Maintenance or replacement?**
I am filing this request since I am essentially continuing maintenance of the original package. Technically it is not an actual fork of the original, but it is very similar and definitely addresses the same needs from a user point of view.

This is my current package that I plan on maintaining going foreward: https://github.com/mitch3x3/vilib

**Contact and additional research**

_Email 1 (4/12/2020):_

> Hi Sat Tomer,
> 
> I've spent the last few years in the GIS / Ag tech field and would like to create a dedicated vegetation index library for python. From what I can see, your "vilib" would be the best option due to its name and the fact that it looks abandoned. Would you be interested in transferring ownership of the vilib python package to me so I can pick up where you left off back in 2011?
> 
> Here's my linkedin so you know I'm a real person and not spam: 
> < I pasted my linkedin profile link here >
> 
> - Mitchell

_RE: Email 1 (4/12/2020):_

> Hi,
> I can move the codes to Github and you can contribute there.
> Will it work for you?
> 
> Best regards,
> Sat

_RE: RE: Email 1 (4/13/2020):_

> Hi Sat,
> 
> Thanks for responding so quickly. I already have a similar repository called vilib on my own github account that I'd like to link to this PyPI name.
> 
> https://github.com/mitch3x3/vilib
> 
> After becoming a bit more familiar with the PyPI interface I realize now that all I need you to do is set me as an "Owner" or "Collaborator" so I can update and push new versions without needing to contact you. I would prefer the "Owner" role so that I have autonomy to add new collaborators going forward.
> 
> Let me know what you think or if you have any other questions.
> 
> - Mitchell

_Email 2 (4/19/2020):_

> Would this be doable for you?
> 
> - Mitchell

_Email 3 (4/30/2020):_

> Hi Sat Tomer,
> 
> I don’t want this email chain to get buried. What do you think about setting me as the “Owner” of the vilib PyPi package?
> 
> I’d really like to use the name and pick up where you left off with this package. Using another name is possible but I really think this name works the best for the use case.
> 
> - Mitchell

**Comment by yeraydiazdiaz** [comment]
Hello @mitch3x3, there seems to be _some_ [download activity](https://pepy.tech/project/vilib) for `vilib`. You mention your project is not technically a fork, does that mean there are API differences? I'm worried there are enough API differences to break end user's code.

I will attempt contact with the owner regardless to get his input on this issue.

**Comment by yeraydiazdiaz** [comment]
The owner replied stating he would like to keep control of the project as it is being actively used. As such I'm closing this issue.

He did reiterate his offer for collaboration, you may want to try and contact him again if you're interested, otherwise I suggest you publish your project with a different name.
