### ISSUE TITLE
PEP 541 Request: forge

### ISSUE THREAD

**Issue by seandstewart** [pypa/pypi-support#442]
**Project to be claimed**
`forge`: https://pypi.org/project/forge/

**Your PyPI username**

`seandstewart`: https://pypi.org/user/seandstewart

**Reasons for the request**

This project was registered over 10 years ago and never received an update or release.

I attempted to contact the original maintainer as listed in the package meta data but never received a response.

At some point it appears maintainership of the `forge` package was passed to PyPI user `dfee`, who maintains the package `python-forge`: https://pypi.org/project/python-forge/

This package has not seen a release in 2 years, but the user appears to have some other active projects, so I attempted to contact the current maintainer, first by email, then by opening an [issue on the repository](https://github.com/dfee/forge/issues/8) for the `python-forge` project, but have never heard back.

I believe holding onto the name `forge` in the package index constitutes name-squatting, as the particular entry is completely unused and un-maintained.

**Maintenance or replacement?**

I intend to publish a new package, which is currently encapsulated within a project I actively maintain. You can see the basis for this new package [here](https://github.com/seandstewart/typical/blob/master/typic/gen.py). It provides an intuitive, context-manager-based API for generating code, similar to the interface which [yattag](https://pypi.org/project/yattag/) provide for HTML generation.

**Contact and additional research**

As mentioned above, I have:
1. Emailed the original publisher of the `forge` entry on PyPI.
2. Emailed the current maintainer of the `forge` entry on PyPI.
3. Opened an issue on the current maintainer's GitHub repo.

**Comment by seandstewart** [comment]
I don’t want to step on anyone’s toes here, but we’re now approaching 2 weeks without triage or updates on this ticket. I notice most issues under this label have gone un-triaged for the last 13 days (except the hot-button `install` request).

@yeraydiazdiaz - apologies for the direct tag, but is there anything I can do to get this ticket moving forward?

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay. I can confirm the project `forge` has a single release with no associated files and as such it is considered invalid and thus subject for transfer.

In these cases we moderators attempt contact with the current owner and allow a courtesy period of one week before proceeding.

**Comment by yeraydiazdiaz** [comment]
I have not received any response so I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
