### ISSUE TITLE
Request transfer of python-awips and mkdocs-unidata

### ISSUE THREAD

**Issue by dopplershift** [pypa/pypi-support#443]
**Project to be claimed**

`python-awips`: https://pypi.org/project/python-awips/
`mkdocs-unidata`: https://pypi.org/project/mkdocs-unidata/

**Your PyPI username**

`dopplershift`: https://pypi.org/user/dopplershift/

**Reasons for the request**

Michael James (@mjames-upc), the developer previously responsible for these projects, passed away last June. We are finally in a position where we need control over the packages again.

**Maintenance or replacement?**

We plan to continue maintenance of the projects.

**Contact and additional research**

[Michael's obituary](https://obits.oregonlive.com/obituaries/oregon/obituary.aspx?n=michael-r-james&pid=193824579) if it helps.

cc: @srcarter3 @tiffanycmeyer13

**Comment by ocefpaf** [comment]
@ewdurbin apologies for pinging you directly but maybe you can help here. 

hese packages are part of the Met/Ocean stack and are maintained by ucar/unidata. @dopplershift is the best person to keep maintaining them.

**Comment by dopplershift** [comment]
Gentle ping?

**Comment by dopplershift** [comment]
We managed to find the appropriate credentials lurking around in a `.pypirc` on a machine somewhere (that really was a security flaw). We have ownership/control of these packages once again.
