### ISSUE TITLE
Issue: Limit Request: intel-tensorflow - 350MB

### ISSUE THREAD

**Issue by chuanqi129** [pypa/pypi-support#444]
**Project**: intel-tensorflow

**Size of release**: 330M

**Which indexes**: both

**Reasons for the request**:  intel-tensorflow is intel optimized tensorflow, which has better performance on intel platform. We'd like increase the limit to 350MB caused by new component added in this package.

**Comment by chuanqi129** [comment]
Hi @jamadden , could you help on it?

**Comment by chuanqi129** [comment]
Hi @jamadden and @pradyunsg could you give some help on it? Very appreciated

**Comment by chuanqi129** [comment]
Our release processes are blocking on this size limitation, hi @jamadden could you please help us on it? Thank you very much

**Comment by jamadden** [comment]
Could you please explain why this release needs to be nearly one third larger than the current release, and how you expect it to grow in the future? 

Is there any possibility of separating this new component into a separate distribution to keep the size of individual artifacts down?

**Comment by chuanqi129** [comment]
Thanks @jamadden , there are two reasons for this increase in size, one is that we have the problem of component replacement and coexistence in this release, the old component will be removed in the future release. The other possible reason is that the bug https://github.com/bazelbuild/bazel/issues/9254 of bazel build caused us to adopt a workaround with `BAZEL_LINKLIBS=-l%:libstdc++.a` . For this version release, we have try our best to reduce the size, but still increased one third.  The `intel-tensorflow` package is based on Google's `tensorflow` with a lot of intel optimization, we may can't decide the direction of this package directly. But I think the next version will don't have such big size. Thanks again~

**Comment by jamadden** [comment]
The limit for the individual files has been set to 350MB on both indexes. Please be mindful of the impact such large releases have across the board as you make releases.

**Comment by chuanqi129** [comment]
Thanks @jamadden for your help. Very very appreciate 😄
