### ISSUE TITLE
Limit Request: casaplotms - 200MB

### ISSUE THREAD

**Issue by vsuorant** [pypa/pypi-support#446]
**Project**
https://pypi.org/project/casaplotms/

**Size of release**

200MB
**Which indexes**

PyPI
**Reasons for the request**

CASA PlotMS tool is a plotter/interactive flagger for visibility data. More information about CASA is available here: https://casa.nrao.edu

**Comment by jamadden** [comment]
Can you tell us please what makes it so big, how often new releases are expected (and for how many platforms if it's not pure-Python), and if it is likely to grow over time?

**Comment by vsuorant** [comment]
The size of casaplotms is primarily due to large C++ framework dependencies (Qt,grpc, casacore). Releases are infrequent, perhaps one or two per year. We plan to support 3 platforms (2 Macos variants and manylinux2014) per release. The size is not expected to grow. The Macos variants are somewhat smaller in size (<100MB) than the Linux variant.

**Comment by di** [comment]
I've set the upload limit for `casaplotms` to 400 MB on PyPI. Please be mindful of the frequency of releases at that size.
