### ISSUE TITLE
Account recovery request - need for making new release

### ISSUE THREAD

**Issue by sfdye** [pypa/pypi-support#447]
Request for account recovery.

## PyPI Username

`sfdye`

---

##  Reason for request

Reason:
	- Lost 2FA authentication app

I may have deleted the 2FA token when migrating from Google authenticator to Authy. Now this is blocking me from making a new release for https://github.com/PythonCharmers/python-future, as the owner has given me the maintainer access on PyPI.

![image](https://user-images.githubusercontent.com/1016390/84500391-046e9400-ace7-11ea-95d5-d412906c7161.png)

**Comment by sfdye** [comment]
bump

**Comment by sfdye** [comment]
gentle ping @jamadden @hugovk @yeraydiazdiaz

**Comment by sfdye** [comment]
gentle bump

**Comment by sfdye** [comment]
Gentle mid-week bump, if anyone can help or direct me to the right place to expedite this request. Thank you!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by sfdye** [comment]
Yes, I regain access now, thanks a ton!
