### ISSUE TITLE
PEP 541 Request: pf9-saml-auth

### ISSUE THREAD

**Issue by pshanbhag** [pypa/pypi-support#449]
**Project to be claimed**
`pf9-saml-auth`: https://pypi.org/project/pf9-saml-auth

**Your PyPI username**
`pshanbhag`: https://pypi.org/user/pshanbhag

**Reasons for the request**
The project is a key library used by some users to perform SAML authentication for my company [Platform9](https://github.com/platform9)'s product. The project's GitHub repository is available under Platform9's GitHub account here: https://github.com/platform9/pf9-saml-auth. 

This project has not received any refresh in over 2 years. My team at Platform9 is ready to release a new version of this library where we deprecate Python2 support and add Python3 support.

This project was initially developed by one of our ex-employees at Platform9. He has since moved on to a different company in a different role. As part of the transition, transferring ownership of this project in pypi was missed out. Platform9 would like to take back ownership of this project to release newer versions of the project as soon as possible.

**Maintenance or replacement?**
We will continue to maintain this project. 

The code repository is https://github.com/platform9/pf9-saml-auth. There are changes already in the repository with regards to Python3 support.

**Contact and additional research**
* Reached out to the current author/maintainer by email and other contact information available in the company but there has been no response.
* The author's email under this project is the author's Platform9 email address which has since been deactivated, ruling out me reaching them through the project's registered method.
* It is unclear if the author is active in any other pypi projects to try to contact them. Only listed project under that username is this orphaned pypi project.

**Comment by pshanbhag** [comment]
It has been almost a month since I raised this request. Can I get some help with this, please? We want to do new release on this project fairly soon. 

Thanks

**Comment by jamadden** [comment]
The owner of the project, `blakegc`,  was active on PyPI within the last month, and has a verified email address. I've contacted them there, but was unable to locate any other means of contact. Hopefully we get a response.

**Comment by pshanbhag** [comment]
Did we get any response from `blakegc`? What is the typical duration we want to wait before we decide alternate options for handling this?

**Comment by jamadden** [comment]
The owner has been reached via email, even though they haven't responded in public yet. I received an email response from the project owner stating that they would look at this issue. That was 7 days ago.

**Comment by blake** [comment]
> Reached out to the current author/maintainer by email and other contact information available in the company but there has been no response.

I have actually corresponded with folks at Platform9 about this over the past few months. They requested I transfer the package to them, and my response was that I did not see a way to do that within PyPI.

I see it is possible to add collaborators to a project, however I have not been provided the name of an account to add so thus far I have been unable to exercise that option.

**Comment by pshanbhag** [comment]
> I see it is possible to add collaborators to a project, however I have not been provided the name of an account to add so thus far I have been unable to exercise that option.

Hey @blake, can you add `pshanbhag` as an owner of the pypi project? Thanks.

**Comment by pshanbhag** [comment]
Hey @blake, any updates on this?

**Comment by pshanbhag** [comment]
@jamadden given the above conversation and lack of response from @blake, can we consider this as an intent of transfer of ownership? Could you please help initiate the transfer of ownership?

**Comment by jamadden** [comment]
No, the owner has been contacted. This means that PEP 541 does not apply. Please work out any details with the owner.

**Comment by yeraydiazdiaz** [comment]
Closing as contact between parties has been established.
