### ISSUE TITLE
PEP 541 Request: manim

### ISSUE THREAD

**Issue by eulertour** [pypa/pypi-support#450]
**Project to be claimed**

`manim`: https://web.archive.org/web/20190502071551/https://pypi.org/project/manim/#files

**Your PyPI username**

`eulertour`: https://pypi.org/user/eulertour

**Reasons for the request**

The project has been abandoned as described at https://www.python.org/dev/peps/pep-0541/#id23, and the current owner hasn't left behind any means of contacting them. It seems that the name is still taken despite the fact that there are no releases (the situation described at https://pypi.org/help/#project-name).
The archived releases from web.archive.org appear to be malware; the programs contain a base64 string which is converted into an exe and executed. We haven't run it for obvious reasons, but we did find that it contains the strings `Soochow Securities Encrypted Channel` and `https://a.cbin.top/`. We're currently developing a project which is called manim but is currently on pypi under the name `manimlib`. We'd consider it very dangerous to leave open the possibility for someone to download and run malware while trying to use our code.

**Maintenance or replacement?**

Publish a new package: https://github.com/ManimCommunity/manim

**Contact and additional research**

The current owner didn't leave any means of contacting them.

**Comment by kilacoda** [comment]
*It's been 31 days....* can we get a response on this please?

**Comment by jamadden** [comment]
Thank you for your patience! All the moderators are volunteers with other jobs. We do the best we can.

The project name `manim` was banned as malware on May 10, 2019 by @dstufft. I'm not aware of any documented policies for reversing malware bans, so I want to surface this to the attention of @pypa/pypi-moderators. It seems fine to to me to unban it for this purpose?

**Comment by pradyunsg** [comment]
Yes, I think we can/should unban this name and transfer this as requested.

**Comment by eulertour** [comment]
Do you have any estimate as to how long it will be before this is finished?

**Comment by kilacoda** [comment]
Any update on the transfer?

**Comment by pradyunsg** [comment]
Not really; PyPI's admins are volunteers. We're basically waiting for one of PyPI's admins to have enough free time to action on the tickets that have been processed.

Given the current... uhm... *gestures at everything*, I imagine there's not been a lot of free time where volunteer work like processing these requests can be done. :)

**Comment by ewdurbin** [comment]
The project name has been unprohibited and can now be registered @eulertour. If someone registers it before you are able, I will proceed to transfer.

**Comment by pradyunsg** [comment]
I see there has been a release since the last message, and eulertour is listed as a maintainer. https://pypi.org/project/manim/

Closing, as this is now resolved!
