### ISSUE TITLE
PEP 541 Request: kelp

### ISSUE THREAD

**Issue by bmorris3** [pypa/pypi-support#452]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/kelp

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/bmmorris

**Reasons for the request**

This project has not been updated since its initial version in 2015.

**Maintenance or replacement?**

I intend to replace the package with a different one, also called [kelp](https://github.com/bmorris3/kelp). This package is the subject of two forthcoming academic papers (in prep).

**Contact and additional research**

No docs are available online for the original `kelp` package: google search yields precisely one result for `"pip install kelp"`, which is the PyPI page.

**Comment by bmorris3** [comment]
Any chance I can ping you for this one again? Thanks!

**Comment by yeraydiazdiaz** [comment]
I can confirm the project kelp has a single release with no associated files and as such it is considered invalid and thus subject for transfer.

In these cases we moderators attempt contact with the current owner and allow a courtesy period of one week before proceeding.

**Comment by yeraydiazdiaz** [comment]
I have not received any response so I will now ask an admin to perform the transfer.

**Comment by bmorris3** [comment]
Hi @yeraydiazdiaz – any progress update? Thanks!

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by bmorris3** [comment]
Thank you @ewdurbin!
