### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by moilerat** [pypa/pypi-support#453]
Request for account recovery.

## PyPI Username

`martigan35`
`fotonower`

---
##  Reason for request

Reason:
I am the CEO of Fotonower, my employee Martin Gaspaillard, login martigan35, left one year ago and we have no more contact with him.
Can you transfer the ownership of https://pypi.org/project/fotonower/ package to : `fotonower`.
We already duplicate it in https://pypi.org/project/ftn/ but would like to get it back.

Kind Regards
Victor Reutenauer
+33(0)609094354
Fotonower, CEO

**Comment by ewdurbin** [comment]
transfer complete based on verification of domains of existing users, package contents, and project history.
