### ISSUE TITLE
PEP 541 Request: shuttle

### ISSUE THREAD

**Issue by meherett** [pypa/pypi-support#454]
**Project to be claimed**

`shuttle`: https://pypi.org/project/shuttle

**Your PyPI username**

`meherett`: https://pypi.org/user/meherett

**Reasons for the request**

The project has been abandoned as described at https://www.python.org/dev/peps/pep-0541/#id23, and the current owner hasn't left behind any means of contacting them. It seems that the name is still taken despite the fact that there are no releases (the situation described at https://pypi.org/help/#project-name).

**Maintenance or replacement?**

I intend to replace this package with https://github.com/meherett/shuttle

**Contact and additional research**

I try to reached out to the current author/maintainer by email but it dosen't work. the response was: 
> This message was created automatically by mail delivery software.
> A message that you sent could not be delivered to one or more of its recipients. This is a permanent error.

> nathan@eventbrite.com INVALID_ADDRESS, ERROR_CODE :550, ERROR_CODE :5.1.1 The email account that you tried to reach does not exist. Please try
            5.1.1 double-checking the recipient's email address for typos or
            5.1.1 unnecessary spaces. Learn more at
            5.1.1 https://support.google.com/mail/?p=NoSuchUser u18si8171467edy.272 - gsmtp

It is unclear if the author is active in any other pypi projects to try to contact them. Only listed project under that username is this orphaned pypi project.

**Comment by hugovk** [comment]
Looks like two of the maintainers are @nyergler and @delainewendling on GitHub, and they have email addresses on their profiles.

**Comment by nyergler** [comment]
To the best of my knowledge Shuttle is still deployed and in use by Eventbrite and others. @delainewendling may have more current information; I'll also email `eb-pypi` (a service account used by the IT team at Eventbrite) to see if they have more up to date information.

Please let me know if there's additional information I can provide to assist with resolving this issue.

**Comment by delaine-eb** [comment]
@nyergler That is correct, Eventbrite is still using this library. I don't recall seeing an email come through but it may have slipped through the cracks. Is there something that needs to be done on our end?

**Comment by nyergler** [comment]
@delaine-eb Based on the quoted email in the original issue, it appears that I was the only maintainer the petitioner attempted to contact. I am, obviously, _no such user_. 

I don't pretend to be completely fluent in PEP-541, but I believe this demonstrates the project does not meet the requirements for _abandoned_ status.

**Comment by yeraydiazdiaz** [comment]
Thanks for your replies @nyergler and @delaine-eb.

It would be good to update the contact email in the project in the next release so as to avoid confusions.

Closing as the project is not abandoned.
