### ISSUE TITLE
Increase in xmlrpc API timeouts recently

### ISSUE THREAD

**Issue by cooperlees** [pypa/pypi-support#455]
**Describe the bug**
bandersnatch's CI has been failing a lot more to the XMLRPC API calling `list_packages_with_serial`

Log:
```
Call to list_packages_with_serial @ https://pypi.org/pypi timed out: Timeout on reading data from socket
```

Timeout settings is 10 seconds for read timeout, so I think the latency with the call has got real bad? Is there data that shows this? This is call for the full package list, I can't easily get around that.

**Expected behavior**
~1 second return with the response starting to download

**To Reproduce**
Code is here:
https://github.com/pypa/bandersnatch/blob/master/src/bandersnatch/master.py#L186

Could write a small utility to call that function for testing. Happy to do so if it helps.

**My Platform**
Latest Ubuntu GitHub actions environment with Python 3.8 

- Example failed run: https://github.com/pypa/bandersnatch/pull/573/checks?check_run_id=766752506

**Comment by ewdurbin** [comment]
Looks like we have a overzealous user/cluster flooding the XMLRPC backends with search requests every hour... I'm gonna track that down and prohibit their IP, which should resolve the issue.

**Comment by cooperlees** [comment]
> Looks like we have a overzealous user/cluster flooding the XMLRPC backends with search requests every hour... I'm gonna track that down and prohibit their IP, which should resolve the issue.

Thanks for looking into it Ernest! Is it easy to add a data dog alert or something to look for this behavior (lots of slow responses)?

@fridex I would use another API if I could. This API was added to Warehouse / Cheeseshop for the code I maintain, in bandersnatch :) 

I have also personally tried to replace the XMLRPC API. I don’t “want” to be using it at all :).

**Comment by ewdurbin** [comment]
> > Looks like we have a overzealous user/cluster flooding the XMLRPC backends with search requests every hour... I'm gonna track that down and prohibit their IP, which should resolve the issue.
> 
> Thanks for looking into it Ernest! Is it easy to add a data dog alert or something to look for this behavior (lots of slow responses)?

Unfortunately not. We track average, 95th percentile, and max backend response times in DataDog, but there isn't a clear enough signal there to alert on without driving someone (me) batty: 

![95th Percentile and Average Pyramid Request Duration xmlrpc](https://user-images.githubusercontent.com/1200832/84663284-f0937f80-aeea-11ea-8932-f0b55a233735.png)

**Comment by pradyunsg** [comment]
Closing this, since I'm pretty sure we don't have the same overzealous cluster hitting our API.
