### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by lisael** [pypa/pypi-support#456]
Request for account recovery.

## PyPI Username

`lisael`

---

##  Reason for request

  - Lost access to email address

Reason:

I've lost the email account associated with my pypi account. I'm the owner of https://github.com/lisael/fastidious/ that I want to release, now.

Note that because of this situation, I did create the account `lisae1` with my default github email address, too. (fyi, if the default github email address has something to do in the recovery process).

Thank you. (and... sorry for that).

**Comment by lisael** [comment]
Please, any update on this? I understand it's volunteer work to help light-minded users, and didn't want to push before, but it's been 4 month and I really need this account :/ Thank you.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, if it bounces or no response is heard within 7 days we will proceed with recovery.

**Comment by ewdurbin** [comment]
The address bounced and the projects do appear to be maintained by your user on GitHub as well.

Unfortunately since you've associated that address with another user on PyPI we cannot use it for the existing account.

How would you like to proceed?

**Comment by lisael** [comment]
@ewdurbin I've just changed the primary address in the other account and (removed the old address altogether). Can you set this address: `lisael@lisael.org` on the `lisael` account, please?

**Comment by ewdurbin** [comment]
This is complete. You should be able to recover the account via standard password recovery method now.

**Comment by lisael** [comment]
Account recovered! Thank you :)
