### ISSUE TITLE
Issue: Limit Request: tensorflow-directml - 500MB

### ISSUE THREAD

**Issue by jstoecker** [pypa/pypi-support#457]
**Project**: https://pypi.org/project/tensorflow-directml/

**Size of release**: 500MB

**Which indexes**: PyPI and Test PyPI

**Reasons for the request**:
TensorFlow is an open source machine learning framework created by Google. Microsoft is adding support for cross-vendor hardware acceleration using DirectML in Windows and the Windows Subsystem for Linux. 

We've kept our initial release as small as possible, but TensorFlow distributions are large by nature (binary only; ~60-120 MB per wheel depending on platform). Our initial release targets 1.15.3; for reference, the [upstream release](https://pypi.org/project/tensorflow/1.15.3/#files) is slightly less than 900MB. Release sizes _may_ increase slightly as we add additional features (on the order of tens of megabytes at most) or support additional versions of Python (each wheel ~60-100MB). We expect our release size to always be smaller than the upstream releases.

More info: 
- [RFC submitted to TensorFlow project](https://github.com/tensorflow/community/pull/243)
- [GPU acceleration in WSL](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gpu)

**Comment by jamadden** [comment]
The limits have been updated.

A 500MB distribution is a burden on PyPI, its CDN and mirrors, and users. Please be mindful of that and limit release frequency (i.e., please do not upload nightly or frequent dev builds; that has [been a condition for large limits in the past](https://github.com/pypa/pypi-support/issues/50)).

**Comment by zooba** [comment]
Thanks @jamadden!

**Comment by crahrig** [comment]
Seconding @zooba, thanks @jamadden greatly appreciated!
