### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sergiors** [pypa/pypi-support#458]
Request for account recovery.

## PyPI Username
`sergiors`

---

##  Reason for request
Hi I did not have access my old email `sergio@inbep.com.br` and I can not reset the password.

Reason:

How Could I change my email to new? osergiosiqueira@gmail.com

**Comment by ewdurbin** [comment]
Because there are no projects associated with the account, this can proceed.

However the address that you supplied is already associated with another PyPI account and cannot be used for `sergiors`.

How would you like to proceed?

**Comment by sergiors** [comment]
@ewdurbin I already deleted the account that was using `osergiosiqueira@gmail.com`. Is it possible change now?

**Comment by ewdurbin** [comment]
This has been completed.

**Comment by sergiors** [comment]
Thank u @ewdurbin
