### ISSUE TITLE
Package name isn't allowed

### ISSUE THREAD

**Issue by tfcollins** [pypa/pypi-support#459]
**Describe the bug**
I'm trying to push a new package named 'libiio' but I get the error:
```
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: tfcollins
Enter your password: 
Uploading libiio-0.21.tar.gz
100%|████████████████████████████████████████████████████████████████████████████| 19.8k/19.8k [00:00<00:00, 21.2kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The name 'libiio' isn't allowed. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/

```
**Expected behavior**
I was able to push the same package with this name to pypi testing, and I expected the same to work on mainline pypi. I don't think this breaks any of the naming rules. Correct me if I'm wrong.

**To Reproduce**
```
Build library with bindings 
...
python3 setup.py sdist
twine upload dist/*
```

**My Platform**
- Python 3.6.9
- Twine 3.1.1

**Additional context**

pypi testing variant: https://test.pypi.org/project/libiio/

**Comment by ewdurbin** [comment]
This name was reserved at the request of the Fedora project, as it conflicts with the name of one of their packages (https://src.fedoraproject.org/rpms/libiio).

You can read the background on this request and discussion at https://github.com/pypa/pypi-support/issues/355

**Comment by encukou** [comment]
The purpose of the reservation is mainly to make sure the Python package name `libiio` is not used for anything else than [libiio](https://github.com/analogdevicesinc/libiio). If you wish to maintain the bindings on PyPI, I don't see a problem with unblocking the name.
@tfcollins, do you want to do that? If so, could you—as a courtesy—ask `libiio` maintainers if they are OK with you maintaining the PyPI entry? (Unless if you're affiliated with them already, of course.)

**Comment by tfcollins** [comment]
@encukou We've already uploaded a package with an alternative name pylibiio.

-Travis
