### ISSUE TITLE
PEP 541 Request: pyspace-package

### ISSUE THREAD

**Issue by sahinbatmaz** [pypa/pypi-support#461]
`PROJECT_NAME`: https://test.pypi.org/simple/pyspace-package

`USER_NAME`: https://test.pypi.org/user/sahinbatmaz/

I had created a different account:
`OLD_USER_NAME`: https://test.pypi.org/user/mavera/
I created pyspace-package with my account.
Then I removed my project and removed my account.

Now I created a new account, and I want to use the same project name.
I will continue to the same project. I will continue to maintanance of the package.

I don't want to share the code repository.

**Comment by yeraydiazdiaz** [comment]
Hello @sahinbatmaz, `pyspace-package` does not exist in test.pypi.org or in pypi.org as such there's nothing to transfer.
