### ISSUE TITLE
PEP 541 Request: WTForms-SQLAlchemy, WTForms-Django

### ISSUE THREAD

**Issue by davidism** [pypa/pypi-support#462]
**Project to be claimed**

`WTForms-SQLAlchemy`: https://pypi.org/project/WTForms-SQLAlchemy
`WTForms-Django`: https://pypi.org/project/WTForms-Django

**Your PyPI username**

`davidism`: https://pypi.org/user/davidism

**Reasons for the request**

I am the owner of WTForms, the previous owners left years ago and are not available. They transferred all the projects to me, but it looks like they only set me as maintainer, not owner, for two minor projects that I'm only now noticing.

**Maintenance or replacement?**

We still maintain all WTForms projects. I need access to these because we're ready to make some new releases.

**Contact and additional research**

**Comment by di** [comment]
I've reached out to @crasta and @prencher via email, hopefully they can respond here.

**Comment by davidism** [comment]
That would be @crast, not crasta

**Comment by prencher** [comment]
Hey friends, I've made @davidism an owner on wtforms-alchemy. I don't have access to wtforms-django, so @crast will have to do that.

Feel free to remove me as an owner as well, I don't appear to have the ability to remove myself.

**Comment by davidism** [comment]
Thanks @prencher! Got the new permissions set up for WTForms-SQLAlchemy and we'll make a new release soon.

**Comment by davidism** [comment]
@di following up on this, it's been over six weeks now, which I think is the cutoff for a response.

**Comment by davidism** [comment]
@di following up again, this is well over the time limit now.

**Comment by di** [comment]
Done, thanks for your patience.
