### ISSUE TITLE
Office365-REST-Python-Client grant access

### ISSUE THREAD

**Issue by domdinicola** [pypa/pypi-support#463]
**Office365-REST-Python-Client**
`Office365-REST-Python-Client`: https://pypi.org/project/Office365-REST-Python-Client/

**dom.dinicola - vgrem **
`dom.dinicola`: https://pypi.org/user/dom.dinicola/
`vgrem`: https://pypi.org/user/vgrem

**Reasons for the request**
current pypi maintaner doesn't upload packages on pypi (2.1.8, 2.1.9, 2.10 have been released on github, but package has not been uploaded on pypi.

vgrem is the owner of github project,
dom.dinicola is currently a contributor of the project.
first release on pypi has been performed by kgadek (https://pypi.org/user/kgadek/)

**Maintenance or replacement?**
maintenance and development
https://github.com/vgrem/Office365-REST-Python-Client

myself and vgrem have been trying to contact unsuccessfully kgadek several times by email and tagging him on issues
- https://github.com/vgrem/Office365-REST-Python-Client/issues/75#issuecomment-638529498
- https://github.com/vgrem/Office365-REST-Python-Client/issues/174

meanwhile there's another pypi project ad interim https://pypi.org/project/office365-rest-client/

**Comment by domdinicola** [comment]
@vgrem @kgadek

**Comment by domdinicola** [comment]
does anyone know how much it take to get updates on these issues?

**Comment by jamadden** [comment]
The PyPI moderators are volunteers, sometimes with very limited time and a lot on our plates. 

I see previous contact attempts, and in https://github.com/vgrem/Office365-REST-Python-Client/pull/184#pullrequestreview-407608014 I see @kgadek agreeing to provide access, though this never happened.

The email address associated with @kgadek on github is the same as the one associated with user `kgadex`, the owner of PyPI project Office365-REST-Python-Client. I have now also attempted contact via email at that address.

We now enter the six-week waiting period mandated by PEP 541 to allow the project owner to be reached.

**Comment by kgadek** [comment]
Hi. Sorry guys for long hiatus, been offline for a bit. Thanks @jamadden for reaching out to me.

I've added `vgrem` as co-owner for PyPI repo.

**Comment by jamadden** [comment]
Thank you @kgadek .  @domdinicola , once you've had a chance to confirm, could you please close this issue?

**Comment by domdinicola** [comment]
Yay, confirm!
Thanks @jamadden
