### ISSUE TITLE
Limit Request: h2o-pysparkling-3.0 - 200MB

### ISSUE THREAD

**Issue by jakubhava** [pypa/pypi-support#469]
Hello folks and,
  we have released PySparkling for Spark 3.0, the same library we have for Spark 2.1 up to Spark 2.4, but we are hitting the size issue we had also for the aforementioned libraries. Could I please ask to increase the size limit for the package to the same size, as for example, https://pypi.org/project/h2o-pysparkling-2.4/.

Right now we can't do a release do PiPy because we exceed the 60mb package size.

Thank you!

Kuba

**Comment by jakubhava** [comment]
Hello, any update, please? Our release pipeline is currently blocked by not being able to publish the mentioned project to PiPy.

Thans a lot for your help!

**Comment by di** [comment]
Hi, it doesn't seem like this project currently exists, https://pypi.org/project/h2o-pysparkling-3.0/ is 404.

I can't raise the limit on a project that doesn't exist. You'll need to publish a small pre release or dev release that you can later delete once the limit is added.

**Comment by jakubhava** [comment]
Thank you @di! I just created the dummy project https://pypi.org/project/h2o-pysparkling-3.0/

**Comment by di** [comment]
I've set the upload limit for `h2o-pysparkling-3.0` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by jakubhava** [comment]
Thank you very much @di!
