### ISSUE TITLE
Limit Request: CamAi - 500MB

### ISSUE THREAD

**Issue by castleguarders** [pypa/pypi-support#47]
Hi. I'm requesting a size limit increase of the PyPI package CamAi's wheels to 300MiB. The most trimmed down version stands at 260MiB right now, and once a few features are enabled in the near future, it will go to 450MB. Ideally it would be good to have the limit at 500MiB to avoid another request in the next few months.

The CamAi package uses deep learned models to do security and event monitoring on premises with complete control and ownership without having to rely on a cloud based service. Instead of of motion detection it uses object detection (people, cars, bicycles) as the baseline and recognizes instances of each (people by face, cars by position etc.) In order to do these, it has to use deep learned model files, including..

    Object Instance detection models 
    Face recognition models
    Other instance detection models.

It would be great to be able to make this 100% python package available via the most intuitive distribution mechanism possible instead of requiring separate hosting and downloads. 

Thank you!

**Comment by castleguarders** [comment]
Hello, Could you please take a look at this request? It would be helpful to get a decision either way.

**Comment by di** [comment]
Sorry for the delay.

Since this package seems to include some relatively large pre-trained models, I'm going to opt to decline this request. We recommend hosting your models externally and either have your package download them at runtime, or allow your users to install them separately.
