### ISSUE TITLE
Limit Request: oif - 150 MB

### ISSUE THREAD

**Issue by mjuric** [pypa/pypi-support#470]
**Project**

https://test.pypi.org/project/oif
https://pypi.org/project/oif

**Size of release**

150MB

**Which indexes**

both PyPI and Test PyPI

**Reasons for the request**

This is a simulator for astronomical surveys of solar system objects (asteroids, KBOs, dwarf planets, etc.). To function, it needs large precomputed data (ephemerides) files. For the time being, we don't expect the compressed file size to grow beyond 150MB.

**Comment by jamadden** [comment]
The limit has been changed on both indexes. 

However, if you have a working system to download large data files now, and there is any possibility they could change with a frequency different than the code, it can improve end user experience and reduce load on PyPI and its mirrors if that system remains available. (PyPI isn't designed to distribute data files, especially not those that change frequently.)
