### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by RainingComputers** [pypa/pypi-support#475]
Request for account recovery.

## PyPI Username

`RainingComputers`

---

##  Reason for request

Reason:
Broke my phone and lost access to 2FA authentication app. Still have access to email.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by RainingComputers** [comment]
Sorry I missed your e-mail on 21 Nov. I followed the instructions for 2FA reset verification.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
