### ISSUE TITLE
Issue: Limit Request: extract-sfm 1.0 - 135 MB

### ISSUE THREAD

**Issue by Panmani** [pypa/pypi-support#476]
**Project**
https://pypi.org/project/extract-sfm/1.0/

**Size of release/project**
135

**Which indexes**
PyPI

**Reasons for the request**
There are two files for two machine learning models that I'd like to include along with the package

**Comment by jamadden** [comment]
The Homepage links on the project are invalid (it points to a Github repository that does not exist). Could you please provide the correct homepage?

**Comment by Panmani** [comment]
Sorry, it was pointing to a private repo. I have updated the link, which now should be pointing to a public one.

**Comment by jamadden** [comment]
The limit for extract-sfm has been increased on pypi.org
