### ISSUE TITLE
Limit Request: watchmaker - 38 MB

### ISSUE THREAD

**Issue by lorengordon** [pypa/pypi-support#477]
**Project** - watchmaker

**Size of release** - ~38MB
**Size of project** - ~38MB - I've deleted all but one release, and am still getting an error due to the size of the project.

**Which indexes** - Test PyPI

**Reasons for the request**

We have our project configured to push development releases to Test PyPi, and it has been working for years, but just in the last few days it began failing with the message:

> HTTPError: 400 Client Error: Project size too large. Limit for project 'watchmaker' total size is 10 GB. See https://test.pypi.org/help/#project-size-limit for url: https://test.pypi.org/legacy/

So, I went in and deleted all but one release from Test PyPi. The project total size is now under 40MB. However, we are still getting the same error, even though the error indicates a 10 *GB* limit.

Kinda just looking for some help understanding what I need to do to get this working again...

**Comment by di** [comment]
Looks like we have a bug (https://github.com/pypa/warehouse/issues/8213). I've temporarily increased the limit to 100GB while we sort this out -- once we do, this limit will be reset to 10GB.

**Comment by di** [comment]
FYI, the bug was fixed and the `watchmaker` package is now at less than 1 GB, so I've reset the limit to 10GB. Sorry for the hassle!

**Comment by lorengordon** [comment]
Thanks @di!
