### ISSUE TITLE
Removed many release, but still hitting size limit

### ISSUE THREAD

**Issue by maloel** [pypa/pypi-support#478]
**Project**
https://test.pypi.org/project/pyrealsense2/

**Size of release/project**
How can I know?? I have no idea except that I get an error when uploading:
HTTPError: 400 Client Error: Project size too large. Limit for project 'pyrealsense2' total size is 10 GB. See https://test.pypi.org/help/#project-size-limit for url: https://test.pypi.org/legacy/

**Which indexes**
Test PyPI

**Reasons for the request**
Intel RealSense SDK test releases & nightlies

**Comment by di** [comment]
Hi @maloel, thanks for filing an issue. We recently implemented a limit on the total size of a project on PyPI/TestPyPI.

Looking at https://test.pypi.org/stats/, `pyrealsense2` is near the top of the list, with a total project size of 53.6 GB.

What's the reason for the large project size on TestPyPI?

**Comment by maloel** [comment]
Hi @di 
Is it still that high? We went ahead and removed quite a few releases (>500) -- by my calculation we should be below the 10 GB limit, but I'm not sure.

One of the problems is that we have no way of knowing thru the web interface that I can see. There also doesn't seem to be any retention policy that I can easily change (keep only last two weeks' worth, etc.).

**Comment by lorengordon** [comment]
I am running into a similar issue with not being able to upload to Test PyPi, despite deleting all but one release. See #477

**Comment by lorengordon** [comment]
#480 is reporting similar problems...

**Comment by maloel** [comment]
Hi @di , I just tried again and the stats on this page don't seem to be updated:
https://test.pypi.org/stats/

I don't know if those numbers are the ones used to decide whether an upload can go thru or not, but it certainly seems that way: we still cannot upload, and this is a major problem for us.

**Comment by Dancho80** [comment]
any update on that? Appears like https://test.pypi.org/stats/ is not updated for several days and we cannot upload any files due to a size limit despite the fact that we deleted almost all releases there: project `pyrealsense2`

**Comment by di** [comment]
Hi all, looks like we might have a bug, I filed https://github.com/pypa/warehouse/issues/8213 in case anyone is interested in figuring out why this isn't working as expected.

For now I've increased the limit for `pyrealsense2` to 100GB while we sort this out -- once we do, this limit will be reset to 10GB.

**Comment by di** [comment]
FYI, the bug was fixed and the `pyrealsense2 ` package is now at 4.4 GB, so I've reset the limit to 10GB. Sorry for the hassle!
