### ISSUE TITLE
PEP 541 Request: smrf

### ISSUE THREAD

**Issue by scotthavens** [pypa/pypi-support#479]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/smrf

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/scotthavens

**Reasons for the request**

- This is also an invalid project for name squatting as the package has no code or functionality and does not show up in the PyPi  search.
- The `smrf` project appears to have been abandoned with the last commit over 4 years ago.
- The owner has left an email on the project page but there has been no response and the owners website is not current.
- We have a broad research and user base that is desiring to use this package from PyPi

**Maintenance or replacement?**

We will be publishing our own actively maintained package through our organization: https://github.com/USDA-ARS-NWRC/smrf.

**Contact and additional research**

Have reached out to author on 6/23/2020 but no response. Project appears to be a graduate student that no longer is with the college.

**Comment by scotthavens** [comment]
I still have not received any contact from the original author of `smrf` after 9 weeks.

**Comment by jamadden** [comment]
I confirm that the project has no releases and no way to be installed, thus making it an invalid project under PEP rules. PyPA moderators like to provide a one week notification to owners of such projects before performing a transfer. I've emailed the verified address PyPI has on file for the owner of `smrf` letting them know the project will be subject to transfer after September 29th.

**Comment by ewdurbin** [comment]
Transer complete.
