### ISSUE TITLE
Limit Request: torch-rocm - 300MB

### ISSUE THREAD

**Issue by iotamudelta** [pypa/pypi-support#48]
In order to publish the ROCm-enabled PyTorch wheel, we need a file size limit bump (current wheel size is 231 MB, so 300 MB would be good. ROCm is AMD's open source heterogeneous computing stack.

Link to project: [PyTorch for ROCm](https://github.com/ROCmSoftwarePlatform/pytorch)

This request would apply to both testpypi and regular pypi.

No prior upload of the wheel.

Thanks!

**Comment by ewdurbin** [comment]
In order to apply limits, the projects must be created on test.pypi.org and or pypi.org.

**Comment by di** [comment]
Closing due to lack of response.
