### ISSUE TITLE
Limit Request: ort-gpu-nightly - 20480 MB

### ISSUE THREAD

**Issue by snnn** [pypa/pypi-support#480]
**Project**
ort-gpu-nightly 

https://test.pypi.org/project/ort-gpu-nightly/

**Size of release/project**

The [stat](https://test.pypi.org/stats/) shows we have used 17.8 GB, but indeed I've deteted all the old releases, it shoudn't be so large now.

**Which indexes**

Test PyPI

**Reasons for the request**

We can't publish new any package, even after deleting the old ones. I don't know how to proceed, please help me!

**Comment by di** [comment]
Looks like we have a bug (https://github.com/pypa/warehouse/issues/8213). I've temporarily increased the limit to 50GB while we sort this out -- once we do, this limit will be reset to 10GB.

**Comment by snnn** [comment]
Thank you!

**Comment by di** [comment]
FYI, the bug was fixed and the `ort-gpu-nightly` package is now at less than 1 GB, so I've reset the limit to 10GB. Sorry for the hassle!

**Comment by snnn** [comment]
Thank you!
