### ISSUE TITLE
Issue: Limit Request: wmp-face - 35 MB

### ISSUE THREAD

**Issue by fredcorpuz06** [pypa/pypi-support#481]
**Project**
wmp-face https://test.pypi.org/project/wmp/

wmp-face version 0.1.1 is under the file limit

**Size of release/project**
Exceeding upload file size limit by 35 MB

**Which indexes**
Test PyPI

**Reasons for the request**
`wmp-face` is a Python module for face detection & recognition built on top of dlib's facial recognizer. I'll be needing additional project size limit eventually because I'll be including more pre-trained face recognition models.

**Comment by pradyunsg** [comment]
@fredcorpuz06 What is the exact size being requested for this project? It is currently at 60MB.

**Comment by di** [comment]
Closed due to lack of response.
