### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by valmar** [pypa/pypi-support#482]
Request for account recovery.

## PyPI Username

`omdevteam`

---

##  Reason for request

Reason: Lost 2FA authentication app

**Comment by valmar** [comment]
Sorry I created the account today, turned on 2FA but then deleted the token from my authentication app

**Comment by valmar** [comment]
Is there any deadline to get back access? I am asking because otherwise I will consider changing the name of my package

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by valmar** [comment]
Done, and answered the email.

Here are the branches:

https://github.com/omdevteam/omdevteam.github.io/tree/UpyFaAAyzuUBNqh7
https://github.com/omdevteam/om/tree/UpyFaAAyzuUBNqh7

Valerio

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
