### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dev-11** [pypa/pypi-support#485]
Request for account recovery.

## PyPI Username

`dev-11`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:
Phone broke and I didn't generate recovery codes unfortunately.

**Comment by dev-11** [comment]
It has been two weeks since I have raised this request. Pretty slow support. As far as I see, no account has been recovered since 18 May. 

Could somebody unlock my account please? @di @ewdurbin

**Comment by dev-11** [comment]
It’s been more than a month now guys... @di @ewdurbin

**Comment by ewdurbin** [comment]
Because there are no projects associated with the account, TOTP has been disabled and a password reset issued.
