### ISSUE TITLE
PEP 541 Request: nest

### ISSUE THREAD

**Issue by gnarayang** [pypa/pypi-support#486]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/nest

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/NeST

**Reasons for the request**
The project has been inactive for a long time i.e, no releases since 2012 
and we currently have a project with the same name and would like a 
name transfer.

**Maintenance or replacement?**
Replacement
https://gitlab.com/nitk-nest/nest

**Contact and additional research**
We sent a mail to hfpython@headfirstlabs.com, the author of the current
project but the email ID doesn't exist
![Screenshot from 2020-07-02 12-22-15](https://user-images.githubusercontent.com/43825655/86326046-bce08580-bc5e-11ea-8ecc-bcf2030ebb05.png)

**Comment by yeraydiazdiaz** [comment]
The project does have releases and [some downloads](https://pepy.tech/project/nest), however, it seems it's functionality is quite limited:

```python
def print_list(the_list, level=0):

    for each_item in the_list:
        if isinstance(each_item, indent = False ,list):
            print_list(each_item, indent, level +1)
        else:
            if indent:
              for tab_stop in range(level):
                pritn("/t", end='')
            print(each_item)
```

Personally I do not think this is enough to consider this project valid, but I'd like to hear opinions from other moderators, @jamadden, @pradyunsg, @ewjoachim?

**Comment by yeraydiazdiaz** [comment]
I'm moving this request forward into reachability.

**Comment by yeraydiazdiaz** [comment]
I have not received a reply, the transfer is now complete.
