### ISSUE TITLE
Issue: Limit Request: code-aster-win - 150MB

### ISSUE THREAD

**Issue by Command2017** [pypa/pypi-support#489]
code-aster-win
https://pypi.org/project/code-aster-win/

**Size of release/project**
My current project is around 100 to 150 MB

**Which indexes**
I need PyPI

**Reasons for the request**
Actually my program is small (3 commands), but my dependencies are big. I want to make the FEM simulation program code_aster easy installable and accessible via python. And the simulation program is around that size. I really often need this program for with python automated simulations. Because the program is under active development, it is likely that in future it will need more space.

I hope you now have all information. Otherwise, please ask.

Regards 
Daniel

**Comment by pradyunsg** [comment]
Thanks for filing this issue @Command2017!

> my program is small (3 commands), but my dependencies are big. [snip] Because the program is under active development, it is likely that in future it will need more space.

I understand these dependencies are non-Python dependencies that you want to distribute along with your code. Is there a rough estimate of how much more space might be needed in the future? Would it be feasible to have a manual, post-install step (like [NLTK handles their data](https://www.nltk.org/data.html)) for this?

**Comment by di** [comment]
Closed due to lack of response.
