### ISSUE TITLE
PEP 541 Request: skeletor

### ISSUE THREAD

**Issue by schlegelp** [pypa/pypi-support#490]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/skeletor

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/observing

**Reasons for the request**

The project does not appear to exist and I don't know why that name would be disallowed.

**Maintenance or replacement?**

New package. Repository: https://github.com/schlegelp/skeletonizer

**Contact and additional research**

Project does not exist and name `skeletor` does not conflict with any Python Standard library module as best as I can tell.

**Comment by jamadden** [comment]
There was briefly a release of that project back in 2012. I have used the registered email address for the project owner and contacted them with a courtesy notification. Unless the status of the project has changed, the name will be available for transfer after July 21.

**Comment by schlegelp** [comment]
Brilliant! Anything I need to do now or after July 21?

**Comment by jamadden** [comment]
Assuming the current owner doesn't object, then after that date someone should move this ticket to the 'awaiting admin transfer' status. If that hasn't happened, then please feel free to ping this ticket as a reminder.

**Comment by schlegelp** [comment]
Hi @jamadden. Any news on this? :)

**Comment by jamadden** [comment]
Thanks for the ping. No response was received so I've asked the admins to complete the transfer.

**Comment by schlegelp** [comment]
Hi @jamadden, thanks for flagging the repo for transfer! Can I ask you for a timeline on this?

**Comment by schlegelp** [comment]
Hi @jamadden. Just a quick ping regarding the pending transfer. I'd love to get my library out there :)

**Comment by jamadden** [comment]
Please do not ping individual PyPI moderators at this stage. We're all just volunteers and have no power to complete the transfer. Likewise, the admins are also very short of time and will handle the issues based on their availability.

**Comment by schlegelp** [comment]
A quick ping to indicate that I'm still very keen to take on this project name.

**Comment by ewdurbin** [comment]
Transfer complete.
