### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by BharatKalluri** [pypa/pypi-support#491]
Request for account recovery.

## PyPI Username

`bharatkalluri`

---

##  Reason for request

Reason:

  - Lost 2FA authentication app or security token

Since the last time I logged in, I have changed my phone and laptop. I have been using andOTP on android and since I have replaced my phone, I have lost the 2FA app. 😭

I do have the username/password and the access to my github account which contains code for the pypi packages I published. I have been planning a release of a new package on PyPI, and have been working on it for a while, only to find out that I am locked out because of my mistakes

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by BharatKalluri** [comment]
@ewdurbin Sent an reply email :+1:

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
