### ISSUE TITLE
Limit Request: minerl - 350 MB

### ISSUE THREAD

**Issue by minerllabs** [pypa/pypi-support#492]
This is a follow-up size increase request from (https://github.com/pypa/warehouse/issues/6241)

Our project minerl is a reinforcement learning simulator which allows its users to train AI agent in Minecraft. We package several jars along with minerl which the python library communicates with to start the simulator, but we need a size increase to enable our next release. **The size target is 350 MB.** We are currently at 100 MB.

PyPi: https://pepy.tech/project/minerl
Index: PyPi
You can read more here: http://minerl.io
Here is our github repo: https://github.com/minerllabs/minerl

**Comment by pradyunsg** [comment]
@minerllabs Please elaborate on why the size on this package has increased, and why distributing the additional files/content as part of the PyPI package would be appropriate.

**Comment by minerllabs** [comment]
Many of our users run MineRL in an environment where Gradle builds (sdist) are not possible. We're trying to distribute wheels with built natives for manylinux, mac-osx, and windows.

**Comment by MadcowD** [comment]
Just following up here.

**Comment by jamadden** [comment]
The limit has been set to 350MB on pypi.org.
