### ISSUE TITLE
Limit Request: SINGA - 450 MB

### ISSUE THREAD

**Issue by nudles** [pypa/pypi-support#493]
**Project**
Project: Apache SINGA
https://test.pypi.org/project/singa/
https://pypi.org/project/singa/

**Size of release/project**
450 MB

**Which indexes**
Both

**Reasons for the request**

[Apache SINGA](singa.apache.org/) is a library focusing on distributed deep learning.
Our project depends on external C++ libs which are not available in pypi repo; therefore, we bind them into the wheel package, which increases the wheel file size.

**Comment by jamadden** [comment]
The limit has been set to 450MB on pypi.org and test.pypi.org. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases.
