### ISSUE TITLE
My project name simpleline is rejected

### ISSUE THREAD

**Issue by jkonecny12** [pypa/pypi-support#495]
Hello,

I have a project named simpleline and I wanted to release it on PyPi. However, I've got a message:

```
HTTPError: 400 Client Error: The name 'simpleline' isn't allowed. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

Unfortunately, I don't know why it is not allowed. I can't see the project on PyPi search and I don't think it has a conflict with Python library. Unfortunately, I wasn't able to find a list of prohibited words or how to find out if name was registered if there is no release.

Could you please help me to resolve this issue? I would like to avoid renaming of the project because of PyPi.

**Comment by ewdurbin** [comment]
This is due to a conflict with a Fedora distribution name, see #355.

**Comment by jkonecny12** [comment]
I'm maintainer of the package in Fedora and also upstream developer.

Hi @hroncok, could you please tell me what to do now?

**Comment by jkonecny12** [comment]
Also shouldn't I get meaningful message with the link the to issue as proposed on https://github.com/pypa/pypi-support/issues/355#issuecomment-621641055 ?

**Comment by hroncok** [comment]
I can attest that https://src.fedoraproject.org/rpms/python-simpleline is maintained by @jkonecny12.

**Comment by di** [comment]
(CC @encukou)

**Comment by encukou** [comment]
That's right! Please make the name available to @jkonecny.

**Comment by di** [comment]
@jkonecny12 Can you let us know your PyPI username?

**Comment by jkonecny12** [comment]
*jkonecny* is my username. Thanks!

**Comment by di** [comment]
@jkonecny12 Should now be available for you to publish.

**Comment by jkonecny12** [comment]
Simpleline project is now published on pypi. Thanks a lot for your help!

Feel free to close this issue.
