### ISSUE TITLE
PEP 541 Request: django-filters (with an s)

### ISSUE THREAD

**Issue by carltongibson** [pypa/pypi-support#497]
**Project to be claimed**

`django-filters`: https://pypi.org/project/django-filters/

**Your PyPI username**

`carltongibson`: https://pypi.org/user/carltongibson

**Reasons for the request**

Both from a long time ago there are two packages: django-filter, which is still going and widely used, and django-filter**s** with the "s", which is long since inactive. 

This is the cause of some confusion in the community: `r"Install django-filters?"` — but which one? 

@baskoopmans who is the owner of django-filters very kindly/responsibly/magnanimously emailed to suggest giving up the name. 

It's too late to change django-filter, but is it possible to set up a redirect? At this late stage there's no reason for a new package to be named so similarly to django-filter, and it would clear up the namespace. 

**Maintenance or replacement?**

We'd like to roll-up the project, and if possible set it to redirect to https://pypi.org/project/django-filter/ (without the "s)

**Contact and additional research**

@baskoopmans made initial contact with me. We're both in accord with the proposal. 

I would just suggest @baskoopmans transfer the name, but I don't know about the redirect bit, hence the issue — Thanks so much for your time and energies! 🥇

**Comment by jamadden** [comment]
Currently, the only way I know of to to handle a "redirect" from project A to project B is to have project A publish a new release containing nothing but a dependency on project B. That is, publish a new release of `django-filters` that has nothing but a trivial `setup.py` (details about an informative long-description, etc, left out):
```python
from setuptools import setup
setup(
   name='django-filters`,
   install_requires=['django-filter',],
   …
)
```

The [ZODB3](https://pypi.org/project/ZODB3/) project is one example of this.

**Comment by baskoopmans** [comment]
That might bring in more confusion, if you install django-filters==1.0 (depends on django-filter) it doesn't force the latest version of django-filter and that means keeping the django-filter and django-filters releases in sync. Maybe not a viable solution :)

**Comment by jamadden** [comment]
I don't see how it would require that at all. The redirect project would not specify any version pins. Only one release of it would ever be published.

**Comment by carltongibson** [comment]
I think we might be able to add a warning to the setup.py too (Django does, or used to do, this for Python 2 compatibility IIRC.)

Possibly there's not the an active issue here... 🤔

**Comment by yeraydiazdiaz** [comment]
Closing as @carltongibson is an active owner of `django-filters`.
