### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rtibbles** [pypa/pypi-support#498]
Request for account recovery.

## PyPI Username

`rtibbles`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

Phone bricked itself, and I had not generated recovery codes. Still have access to my email address if needed for verification.

**Comment by rtibbles** [comment]
Anything I can do to help this process along? If it is easier, I could probably handle this account being deleted, so I can recreate the account on the same username and email address - I have checked that all the projects I maintain have other maintainers associated with them.

**Comment by rtibbles** [comment]
Is there any process in place for these to be dealt with?

@ewdurbin I see you were the last person to respond to a recovery request, what do I need to do to proceed here?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@rtibbles do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: rtibbles" to proceed

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
