### ISSUE TITLE
Limit Request: intel-tensorflow - 400 MB

### ISSUE THREAD

**Issue by rsketine** [pypa/pypi-support#499]
Project: intel-tensorflow

Size of release:  386 MB 

Which indexes: both

Reasons for the request: intel-tensorflow is intel optimized tensorflow, which has better performance on intel platform. We'd like increase the limit to 400MB caused by new component added in this package. We are trying to release 2.3 intel-tensorflow.

Issues causing this problem are not resolved yet:
https://github.com/tensorflow/tensorflow/issues/35867
https://github.com/bazelbuild/bazel/issues/9254  - not resolved in Bazel 3.1.0 but resolved in bazel3.4.0 which is not used in building TF 2.3 release.

**Comment by rsketine** [comment]
previous request submitted from our team https://github.com/pypa/pypi-support/issues/444. Hoping once the Bazel issue is fixed we might be able to see the size improvements.
Hi @jamadden and @pradyunsg could you please look into this.? Very appreciated

**Comment by jamadden** [comment]
The limit has been set to 450MB on pypi.org and test.pypi.org. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases.

**Comment by rsketine** [comment]
Thank you very much for the increase.
