### ISSUE TITLE
claim package confu

### ISSUE THREAD

**Issue by grizz** [pypa/pypi-support#5]
I would like to claim the project name `confu` on PyPI our package https://github.com/20c/confu.

The current package looks like an abandoned alpha and hasn't been updated in 4 years:

https://pypi.org/project/confu/
https://github.com/neithere/confu

I emailed the author @neithere about 9 months ago and still haven't heard a response.

Thanks

**Comment by yeraydiazdiaz** [comment]
Hello @grizz, I've emailed @neithere in order to clarify his position regarding the package. Hopefully we will hear from him soon and move forward with your claim.

**Comment by yeraydiazdiaz** [comment]
Hello @grizz, I have received no response from the author so the project can now be considered abandoned.

Could you please confirm your PyPI username so we can proceed with the transfer?

**Comment by grizz** [comment]
Awesome, thank you. Username on pypi is `20c`

**Comment by grizz** [comment]
@yeraydiazdiaz any update on when this will happen? No rush, was just about to do a release :)

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by grizz** [comment]
@ewdurbin thanks!
