### ISSUE TITLE
Issue: PEP 541 Request: pypen

### ISSUE THREAD

**Issue by EriKWDev** [pypa/pypi-support#500]
PEP 541 https://www.python.org/dev/peps/pep-0541/ describes the workflow for
any project claiming issues and conflict resolution.  Make sure you read and
understand the PEP to set your expectations on the possible outcomes.

**Project to be claimed**
`pypen`: https://pypi.org/project/pypen

**Your PyPI username**
`ErikWDev`: https://pypi.org/user/ErikWDev

**Reasons for the request**
The current owner of pypen has abondonded it and opened a new project called wryte. Pypen's official website points to his wryte github page. I tried to find the original author's mail, but it wasn't presented anywhere. I tried to click on his twitter on his github, but the account is deleted. I beleive pypen is a dead project and hence I think it reasonable to request the name.

**Maintenance or replacement?**
(I want to replace it)
I currently try to co-establish and maintain apackage called pypen, but since pypen was already taken, we had to change the name to pyper. (https://pypi.org/project/pyperlib/) I most certainly intend to maintain my own package, but preferably under the name pypen. Hence, I request to replace it with my own project.

**Contact and additional research**
I have tried to contact him on twitter, but his twitter account was deleted. 

The official github repo for pypen points to a different project, wryte
https://pypi.org/project/pypen/ -> https://github.com/strigo/wryte

wryte already has a different pypi page https://pypi.org/project/wryte/

I think it would be fair to assume that pypen is just an old and abandoned name of his project wryte.

edit: clarifications

**Comment by jamadden** [comment]
Have you tried emailing the address listed at https://pypi.org/project/pypen/?

It seems likely that @nir0s here is the same as https://pypi.org/user/nir0s/, the owner of pypen. Perhaps @nir0s will be good enough to comment on this issue.

**Comment by EriKWDev** [comment]
Hi! Thanks for pointing out the email. It was hidden under a hyperlinnk that I now found. 
I have now mailed him and asked about the state of pypen and linked to this request. I also asked if he could join the discussion here :)
@nir0s

**Comment by nir0s** [comment]
Heh. By all means. Have fun.

**Comment by jamadden** [comment]
@nirOs: Would you be willing to transfer the name on PyPI yourself by adding `ErikWDev` as another owner? `ErikWDev` can then remove you as an owner. This is much faster than waiting for an admin to find the time to deal with it, and it leaves a clear audit log showing these actions.

**Comment by jamadden** [comment]
@Nir0s: Would you be willing to transfer the name on PyPI yourself by adding ErikWDev as another owner? ErikWDev can then remove you as an owner. This is much faster than waiting for an admin to find the time to deal with it, and it leaves a clear audit log showing these actions.

**Comment by EriKWDev** [comment]
Thank you for your kindness @nir0s :) My friend and I will both be very happy to get the name we envisioned our project to have.

**Comment by EriKWDev** [comment]
@nir0s, could you add me as the owner of pypen on pypi.org?

**Comment by nir0s** [comment]
Done.

**Comment by EriKWDev** [comment]
I can confirm that it worked and that I am now the owner of pypen. Thank you @nir0s for you cooperation and @jamadden for your quick response.
