### ISSUE TITLE
PEP 541 Request: krake

### ISSUE THREAD

**Issue by mgoerens** [pypa/pypi-support#502]
**Project to be claimed**

`krake`: https://pypi.org/project/krake

**Your PyPI username**

`mgoerens`: https://pypi.org/user/mgoerens

**Reasons for the request**

The current `krake` package on PyPI is unmaintained since 2017. The referenced code base (https://github.com/lmittmann/krake) does not exist anymore (or is private). The maintainer `lmittmann` did not provide any means to contact him (no public email neither on PyPI nor GitHub, I was therefore not able to contact him.

I'm a maintainer of a project with a similar name. See the krake project on GitLab: https://gitlab.com/rak-n-rok/krake. This has nothing to do with the current `krake` package on PyPI. I'd like to publish python packages under this name. 

**Maintenance or replacement?**

I will use this name for another project: https://gitlab.com/rak-n-rok/krake

**Contact and additional research**

The maintainer didn't provide a public email address, neither in PyPI, nor in GitHub. I also couldn't find the email address from his commit messages. Therefore I couldn't contact him.

**Comment by mgoerens** [comment]
Actually I just realized I can try to summon @lmittmann here.

@lmittmann: TL;DR: would you be willing to abandon ownership of the name `krake` on PiPY ? I have a project with a similar name and it looks like your project is not existing anymore.

**Comment by lmittmann** [comment]
@mgoerens There haven't been any new releases in the past years. However, the package is still used by a few projects. I don't want to change the package name.

**Comment by mgoerens** [comment]
@lmittmann That's too bad.. Please let me know if you change your mind. This would be very helpful for our project. This is causing some confusion as some users already downloaded the wrong package, and we'll now have to come up with a clever name for the python package (different than the project name obviously).

Anyway, thanks for taking the time to answer. Please consider of updating this issue (or contact anyone from https://gitlab.com/rak-n-rok/krake) if you ever decide to abandon the `krake` name on PyPI.

**Comment by jamadden** [comment]
Closing since the request has been answered by the project owner.
