### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yjlch1016** [pypa/pypi-support#504]
Request for account recovery.

## PyPI Username

yjlch1016

##  Reason for request

Reason: Lost 2FA authentication app or security token

**Comment by yjlch1016** [comment]
When can I take care of it?

**Comment by ewdurbin** [comment]
This account has generated valid recovery codes on 2020-03-13. Please use one of those recovery codes to regain access to your account.

**Comment by yjlch1016** [comment]
Where is the valid recovery codes?I didn't receive it！
