### ISSUE TITLE
Acpype - 120 MB

### ISSUE THREAD

**Issue by lkagami** [pypa/pypi-support#506]
**Project**

https://pypi.org/project/acpype/
**Size of release/project**

60MB
**Which indexes**

PyPI
**Reasons for the request**

A tool based in Python to use Antechamber to generate topologies for chemical compounds and to interface with others python applications. The Ambertools package absence for pype implies the addition of Antechamber binaries for the script execution. Please increase the upload capacity of the Acpype package to 120MB. Thanks a lot!
Luciano Porto Kagami

**Comment by jamadden** [comment]
Do I understand that Antechamber is a third-party binary (native) program of around 120MB that you wish to distribute via PyPI?

If so, do you plan to compile and distribute wheels for each of your supported platforms? Right now there's a single wheel (acpype-0.1.1-py2.py3-none-any.whl)[https://files.pythonhosted.org/packages/6b/ab/b4c31082ae8f86eb160c8632a320fdac9e29b48ed65d7629d6c99797c987/acpype-0.1.1-py2.py3-none-any.whl] that specifies it runs on both Python 2 and Python 3 on any platform. 

Distributing wheels containing binaries for Linux platforms may be somewhat complicated; the [manylinux PEPs and docker images](https://github.com/pypa/manylinux) help with that.

In the future, PyPI [may reject uploads containing Linux binaries if they are not manylinux compliant](https://github.com/pypa/warehouse/issues/5420).

**Comment by lkagami** [comment]
Thanks for your response!  The Ambertools package cannot be installed via yum, apt or similar command.  It is necessary to add pre-builded binaries and assign environment variables.  I am trying to use the suggested methods.  I will contact you if I am unsuccessful.  Thank you!

**Comment by di** [comment]
Closed due to lack of response. (Let us know if you were unsuccessful and this needs to be reopened).
