### ISSUE TITLE
Limit Request: casatools - 150 MB

### ISSUE THREAD

**Issue by vsuorant** [pypa/pypi-support#507]
**Project**

https://pypi.org/project/casatools

**Size of release/project**
150MB

**Which indexes**
PyPI

**Reasons for the request**
Casatools has a lot of compiled C++ backend code. Releases will be provided for Linux, and two recent Macos versions. Current package sizes range from 105MB to 120MB depending on the platform so 150MB should be sufficient for the foreseeable future.

**Comment by jamadden** [comment]
Done.
