### ISSUE TITLE
Limit Request: aText - 300MB

### ISSUE THREAD

**Issue by sjskdas** [pypa/pypi-support#51]
https://pypi.org/project/atext

It needs to be extended to 300MB because I'm uploading a jar file on which I have developed a python wrapper. Thanks, Subrata

**Comment by di** [comment]
Sorry for the delay.

Since this package seems to wrap a relatively large JAR file, I'm going to opt to decline this request. If you're able to reduce the size of the JAR file contained in your distribution, please let us know the reduced size and we can reconsider this request.
