### ISSUE TITLE
PEP 541 Request: wikiextractor

### ISSUE THREAD

**Issue by attardi** [pypa/pypi-support#510]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/wikiextractor

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/attardi

**Reasons for the request**
I am the developer of the Wikiextractor package (https://github.com/attardi/wikiextractor) from which mAboshokor created the PyPi project. 

**Maintenance or replacement?**
I would like to replace the project with a newest version, with better description and uptodate releases.

**Contact and additional research**
I could not find an email for contacting mAboshokor.

Thanks for your help.

**Comment by hugovk** [comment]
https://pypi.org/project/wikiextractor/ links to https://github.com/MouhamadAboShokor/wikiextractor, so let's ping @MouhamadAboShokor.

I also see a PR of the package files at https://github.com/attardi/wikiextractor/pull/180, so hopefully @MouhamadAboShokor will be happy to give PyPI access too :)

**Comment by attardi** [comment]
Thanks for the suggestion. I wrote a comment on the PR to @AboShokar.

**Comment by attardi** [comment]
I got no answer from AboSokar on https://github.com/attardi/wikiextractor/pull/180.
Please proceed to give me ownership of the wikiextractor project.

Thank you.

**Comment by jamadden** [comment]
I have emailed @mAboshokor at the email address PyPI has on file. It was verified as of a year ago. However, the email immediately bounced. 

I have no other way to contact this user. Accordingly, I will ask the admins to initiate the transfer.

**Comment by attardi** [comment]
Than you.

**Comment by attardi** [comment]
Any progress on this?

**Comment by attardi** [comment]
Please proceed to give me the ownership of the wikiextractor project.
Thanks.

**Comment by ewdurbin** [comment]
Transfer complete.
