### ISSUE TITLE
PEP 541 Request: google-cloud-functions

### ISSUE THREAD

**Issue by busunkim96** [pypa/pypi-support#512]
**Project to be claimed**

`google-cloud-functions`: https://pypi.org/project/google-cloud-functions

**Your PyPI username**

`gcloudpypi`: https://pypi.org/user/gcloudpypi/

**Reasons for the request**

This project uses the "Google Cloud" trademark.

**Maintenance or replacement?**

We will publish a different package. https://github.com/googleapis/python-functions

**Contact and additional research**

https://github.com/devkomarek/google-cloud-functions/issues/1 An issue was filed on the repository in February but the owner has not responded.

**Comment by ewdurbin** [comment]
transfer complete on basis of trademark and lack of functionality.

**Comment by busunkim96** [comment]
@ewdurbin Thank you!
