### ISSUE TITLE
PEP 541 Request: mmdet

### ISSUE THREAD

**Issue by hellock** [pypa/pypi-support#513]
**Project to be claimed**

`mmdet`: https://pypi.org/project/mmdet

**Your PyPI username**

`openmmlab`: https://pypi.org/user/openmmlab

**Reasons for the request**

The user `651juan` published a pypi package using the name mmdet based on our project [mmdetection](https://github.com/open-mmlab/mmdetection), but it has not received updates for 8 months. We would like to maintain it and publish new versions.

**Maintenance or replacement?**

We would like to continue maintenance, and we are the maintenance team of the repo https://github.com/open-mmlab/mmdetection.

**Contact and additional research**

There is no email for the user either on pypi or github, or other public websites.

**Comment by hellock** [comment]
@di @jamadden Tens of thousands of users are expecting the package. Could you kindly help with this? Thanks for your time!

**Comment by jamadden** [comment]
I have emailed the address that PyPI has on file for 651juan. Note that PEP 541 allows up to 6 weeks to wait for a response.

**Comment by hellock** [comment]
Thanks!
