### ISSUE TITLE
PEP 541 Request: sib

### ISSUE THREAD

**Issue by assaftibm** [pypa/pypi-support#514]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/sib

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/assaftibm

**Reasons for the request**
The current `sib` project on PyPI was registered in 2016 and has never been used. There were no releases (see https://libraries.io/pypi/sib) and running `pip install sib` fails.  

Also, it has been abandoned by the registered maintainers: aikchar and startinblox. See more details below. There is no code base for this project, and no link to its purpose. 

**Maintenance or replacement?**

Since the current package is just a name without any releases, no one has ever installed it and no maintenance is required to keep it alive. 

I would like to use the name for a new open source project that I created:
https://github.com/IBM/sib
As you can see, it is backed up by an active code repository and a build system. 

**Contact and additional research**
I spent time contacting the owners and my conclusion is that they abandoned the project.

**aikchar**:
His full name is: Hamza Sheikh
I found this by looking up other projects that he created, such as: https://pypi.org/project/mity/
I sent him an email at: code@codeghar.com and aikchar@codeghar.com but received no answer.
I also found his home page - http://www.aikchar.me/contact/ in which he mentions that his preferred way of communication is Twitter. I tried to reach out to him on Twitter by received no answer. See screenshot below:
![twitter](https://user-images.githubusercontent.com/28494432/88513725-7ed24980-cff1-11ea-8c5f-2cb98be1999b.png)

**startinblox**:
I contacted them in various ways: using the 'contact' form on their website: https://startinblox.com/en/ and by looking up people that work in this company using linkedin. I managed to receive one response from a co-founder, but he wasn't sure why they have registered this project, and said that he "thinks" that they did that to reserve the name. However, they never used it, and it 's been 4 years already. I asked if they have any plan to use it and he did not reply. See screenshot below:

![linkedin](https://user-images.githubusercontent.com/28494432/88513953-e8525800-cff1-11ea-9c8d-51008d052d75.png)

**Comment by assaftibm** [comment]
Could you please provide a resolution on this?

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay. I can confirm the project `sib` has a single release with no associated files and as such it is considered invalid and thus subject for transfer.

In these cases we moderators attempt contact with the current owner and allow a courtesy period of one week before proceeding.

**Comment by yeraydiazdiaz** [comment]
I have not received any response so I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
