### ISSUE TITLE
transfer the name

### ISSUE THREAD

**Issue by kaldan007** [pypa/pypi-support#515]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/PROJECT_NAME

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/USER_NAME

**Reasons for the request**

**Maintenance or replacement?**

**Contact and additional research**

**Comment by jamadden** [comment]
Seems to have been opened by mistake, the template was not filled out.
