### ISSUE TITLE
Request to be added as maintainer on pynvim

### ISSUE THREAD

**Issue by norcalli** [pypa/pypi-support#517]
My pypi username is `ashkankiani`. I'm one of the core maintainers on Neovim. Previously, the `pynvim` releases were being maintained by `bfredl` (which is his username on Github and on pypi). Unfortunately, right now he's unavailable, and we'd like to publish a bugfix, but no one has publish rights. I wanted to see if I could be added as a maintainer, and then from there I could add other core devs so we have more redundancy.

I'm not sure if this kind of thing happens often, and I understand there could be security concerns, but I think I could prove my identity and lack of ill intention from my github activity and public profile.

Thank you,
Ashkan Kiani

**Comment by jamadden** [comment]
The only official process in place for something like that is outlined in [PEP 541](https://www.python.org/dev/peps/pep-0541/). There's a separate issue template for that process. Note that it takes a minimum of 6 weeks to complete that process.

**Comment by norcalli** [comment]
Understood, I see the conditions on there and I'll see about preparing it, but obviously getting in touch with the original maintainer would be preferred.

**Comment by jamadden** [comment]
It would probably help organization efforts if you just refer to this issue from the new one, and close this one.

I've gone ahead and emailed the verified email address that PyPI has on file for @bfredl to get the clock started. I wasn't able to find any other contact information besides the github profile.

**Comment by ewdurbin** [comment]
@norcalli if this request is still valid, please open a PEP 541 request using the issue template.
