### ISSUE TITLE
Limit Request: cufinufft - 122 MB

### ISSUE THREAD

**Issue by garrettwrong** [pypa/pypi-support#518]
**Project**
https://test.pypi.org/project/cufinufft/1.0/

**Size of release/project**

122 MB per wheel, I believe we have 6 manylinux2010 wheels at this time.

**Which indexes**

Both PyPI and Test PyPI

**Reasons for the request**

We are trying to deploy a manylinux2010 based distribution of CUDA C/C++ accelerated code.  Our CUDA library is approximately 50MB alone because it contains code for all compliant CUDA chips compatible with that CUDA version (10), for maximum compatibility.  Additionally because it is scientific code, it naturally depends on some additional libraries yielding a rather large size.

**Comment by jamadden** [comment]
The limit has been set on test.pypi.org, but you'll have to create the project on pypi.org before the limit can be set there.

**Comment by garrettwrong** [comment]
Hi thanks! I've confirmed we can stage the wheels on the testing index after the change.

I've pushed an sdist to PyPI: https://pypi.org/project/cufinufftpy/1.0/

Can we increase that limit too? Thanks!

**Comment by jamadden** [comment]
The limit has been increased on pypi.org.
