### ISSUE TITLE
Limit Request: ANTsPy - 300MB

### ISSUE THREAD

**Issue by stnava** [pypa/pypi-support#52]
Hi - 

https://github.com/ANTsX/ANTsPy this project uses a bunch of templated C++ to generate 2, 3 and 4-dimensional processing routines for medical imaging and related types of data.   it wraps the (large) C++ project https://github.com/ANTsX/ANTs using pybind11.   As such, the project installation files are rather large:  

* OSX 10.14.5    -  224M for *tar.gz  and 219M for *whl
* Ubuntu 18.04 -  267M and 262M
* the majority of the space is *.so files.

I would love to be able to distribute this project more easily and on more platforms via pypi.  thank you for considering this request and thank you for this generous project.

best,

BA

**Comment by stnava** [comment]
any update?

**Comment by jamadden** [comment]
The upload limit has been set to 300MB. 

At that size, please be mindful of the burden new releases place on PyPI and end users, and be judicious releasing new versions.
