### ISSUE TITLE
PEP541 Request: Jank

### ISSUE THREAD

**Issue by LennyPhoenix** [pypa/pypi-support#520]
**Project to be claimed**

`jank`: https://pypi.org/project/jank

**Your PyPI username**

`DoAltPlusF4`: https://pypi.org/user/DoAltplusF4

**Reasons for the request**

The project has no description, no licence, and no functional release. It cannot be downloaded via PIP.
The author's email address is invalid (sam@keen.io, see below) and the github page (https://github.com/keenlabs/canteen) is also invalid.

![image](https://user-images.githubusercontent.com/57148878/88844433-90c31080-d1da-11ea-80e3-c281a47ea9fd.png)

It should also be noted that the owner (https://pypi.org/user/samg/) has many other empty projects, including [junk](https://pypi.org/project/junk/), [ally](https://pypi.org/project/ally/), [alloy](https://pypi.org/project/alloy/) and [wooly](https://pypi.org/project/wooly/).

**Maintenance or replacement?**

I wish to publish a different package, which can be located [here](https://github.com/DoAltPlusF4/Jank-Engine).

**Contact and additional research**

The owner's email address is invalid, and the github page linked is also invalid. Note that that the owner (Sam Gammon) is not listed in that [github page](https://github.com/keenlabs/canteen)'s [organisation's member list](https://github.com/orgs/keenlabs/people).

![image](https://user-images.githubusercontent.com/57148878/88845226-be5c8980-d1db-11ea-9112-b68c88b05890.png)

**Comment by DoAltPlusF4** [comment]
@keenlabs Is the organisation that apparently owns the project, despite Sam Gammon not being listed with their members.

**Comment by DoAltPlusF4** [comment]
@jamadden @ewdurbin 

Please can I get some kind of info about if/when this can be transferred?
It has been over a month since this ticket was opened with no information.

**Comment by jamadden** [comment]
PEP 541 specifies a process that begins with PyPI moderators or admins doing research and attempting to contact the project owner. After that, there's a six week waiting period.  Only after that can the project go on the list to be transferred; that list is processed as admins have the opportunity. 

I hadn't had the time to do any of the research yet...

**Comment by jamadden** [comment]
I believe this constitutes an invalid project under the PEP rules. PyPI policy in that case is to contact the owner and provide a one-week courtesy notification before allowing a transfer. 

I've emailed the project owner at the email address PyPI has on file to inform them of this. The project can be slotted for transfer after September 7th if it remains invalid.

**Comment by DoAltPlusF4** [comment]
Cool! I would also recommend looking into their other projects as the majority also seem to fall under the same category.

**Comment by DoAltPlusF4** [comment]
@jamadden 
Hey, any response from the owner?

**Comment by jamadden** [comment]
I have received no response. I will ask the admins to perform the transfer at their convenience.

**Comment by ewdurbin** [comment]
Transfer complete.
