### ISSUE TITLE
Limit Request: tensorflow-neuron - 300 MB

### ISSUE THREAD

**Issue by awsjoez** [pypa/pypi-support#521]
**Project**
tensorflow-neuron
https://pypi.org/manage/project/tensorflow-neuron

**Size of release/project**
300MB

**Which indexes**
PyPI

**Reasons for the request**
tensorflow-neuron is a TensorFlow version that supports the Amazon AWS Inferentia machine learning accelerator.
The package is bigger than the current PyPI limit.
We were not able to upload the initial release because of the size limit.
Could you please increase the package size limit? Thank you.

**Comment by jamadden** [comment]
In order to set a limit, the project must first exist. You can try uploading a source distribution or other small artifact to create the project.

**Comment by di** [comment]
Closed due to lack of response (the project still does not exist).
