### ISSUE TITLE
Limit Request: mxnet-neuron - 200 MB

### ISSUE THREAD

**Issue by awsjoez** [pypa/pypi-support#522]
**Project**
mxnet-neuron
https://pypi.org/project/mxnet-neuron/

**Size of release/project**
200MB

**Which indexes**
PyPI

**Reasons for the request**
mxnet-neuron is a MXNet version that supports the Amazon AWS Inferentia machine learning accelerator.
The package is bigger than the current PyPI limit.
We were not able to upload the initial release because of the size limit.
Could you please increase the package size limit? Thank you.

**Comment by jamadden** [comment]
In order to set the limit, the project must first exist. You'll need to upload a source distribution or other artifact to create the project.

**Comment by awsjoez** [comment]
Hi @jamadden thank you for your response. What's the best way to create the project when the file size is over the limit? We don't want to upload invalid files since it might be exposed to the public.

**Comment by jamadden** [comment]
Sorry, I know of no other options than the one I mentioned, uploading a distribution. I think you can then immediately remove that *release* (but not the project).

**Comment by di** [comment]
Closed due to lack of response. Let us know if you're able to go ahead and create an empty project so we can set the limit for it and we'll reopen.

**Comment by awsjoez** [comment]
Hi @di, what's the best way to create an empty project, without uploading the file?

**Comment by di** [comment]
Hi @awsjoez, you'll need to upload something unfortunately. You can create an absolutely minimal `setup.py` like so:

```python
from setuptools import setup

setup(name="mxnet-neuron", version="0.0.0")
```

And build it with `python setup.py sdist`. Upload that and immediately delete it and we'll be able to increase the limit. Sorry for the trouble!

**Comment by di** [comment]
Closed due to lack of response. Let us know if you're able to go ahead and create an empty project so we can set the limit for it and we'll reopen.
