### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by pafonta** [pypa/pypi-support#523]
Request for account recovery.

## PyPI Username

`pafonta`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

Hello there. I got a phone update which has reset my 2FA App and, due to the pandemic, I haven't generated recovery codes when it became available in March. Sorry for this chain of events and this situation. Thank you in advance for taking time to consider my request.

**Comment by pafonta** [comment]
Hello,
I hope you are doing well.
Would it be an update on my request?
Thank you :)

**Comment by pafonta** [comment]
Thank you very much @ewdurbin for having had a look at it and having it moving forward!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by pafonta** [comment]
Thank you very much @ewdurbin for your time! I confirm I have recovered my account 💯
