### ISSUE TITLE
Trying to register my package at pypi

### ISSUE THREAD

**Issue by csalazar-rj** [pypa/pypi-support#524]
**Describe the bug**
I am trying to register my package with command below:

> python3 setup.py register

I inform the login and password, then:

Registering validador to https://upload.pypi.org/legacy/
Server response (500): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

**Expected behavior**
Get my package registered

**To Reproduce**
> python3 setup.py register

**My Platform**

I have a MacBookPro 13"

**Additional context**

**Comment by di** [comment]
Hi @csalazar-rj, thanks for filing an issue. Can you tell us what tutorial/guide you're following? It seems to be fairly outdated.

I'd recommend following https://packaging.python.org/guides/distributing-packages-using-setuptools/ instead, specifically:

* You don't need to `register` a package anymore
* You should upload with https://pypi.org/project/twine/ instead.

**Comment by di** [comment]
@csalazar-rj Can you try following the answer provided here? https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version

**Comment by csalazar-rj** [comment]
Hi Did
I already figure it out. I had to use pip3 for my python 3 

Thanks and Regras

**Comment by di** [comment]
Great, is it working now? If so please feel free to close this issue.

**Comment by csalazar-rj** [comment]
> Great, is it working now? If so please feel free to close this issue.

Yes it is Di.
Thanks 
I will close it now.

**Comment by csalazar-rj** [comment]
The issue was happening because i was using an old statement to register and upload the package.
