### ISSUE TITLE
I had the package name Py2DF on the test division

### ISSUE THREAD

**Issue by UP929312** [pypa/pypi-support#525]
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
This filename has already been used, use a different version. See https://test.pypi.org/help/#file-name-reuse for more information.

But now, I can't upload anything, and I can't claim the repository either, anyway that you can reset the package so it's brand new and I can upload from fresh? (Py2DF - 0.0.1)

**Comment by di** [comment]
Sorry for the trouble! You'll need to publish a new version. Any version that you've previously used will be unavailable.

**Comment by SkezzaB** [comment]
So I used version 0.0.1, but when I also use 0.0.2 it doesn't work, I can't
seem to change the version to anything and it still work?

**Comment by di** [comment]
Did you rebuild your distribution after changing the version? Are you trying to upload a specific file, or doing something like `twine upload dist/*`? If so, the latter might be trying to upload old distributions, you should do `twine upload --skip-existing dist/*` instead.

**Comment by di** [comment]
Closing due to lack of response.
