### ISSUE TITLE
Python pip: What are the ports and IP address ranges in use / that need to be allowed

### ISSUE THREAD

**Issue by dr-dolittle** [pypa/pypi-support#527]
I have a Python Azure Function that is integrated in a subnet in a virtual network. Additionally there is a network security group associated to the subnet that controls inbound and outbound traffic to / from the subnet.

The requirement is to restrict traffic as much as possible what requires me to set rules that restrict the ports and destination addresses (for outbound traffic).

Network Security Groups need IP(s/ranges) - urls can't be specified.

Which ports and IP(s/ranges) are used by pip? Respectively do you have certain (static) IP ranges at all that can be used?

Thanks

**Comment by crwilcox** [comment]
Someone else may have an exact answer, but I think you will have a mix of addresses as PyPI is deployed to a number of services described at https://pypi.org/sponsors.

[fastly (CDN)](https://api.fastly.com/public-ip-list) is almost certainly needed to be allowed, but it is possible that, [aws (Compute)](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html), and [google cloud (object storage)](https://cloud.google.com/compute/docs/faq#find_ip_range) would also need to be allowed.

**Comment by pradyunsg** [comment]
Closing, since the question seems to have been answered; given the lack of discussion.
