### ISSUE TITLE
Issue: clear all releases from test PyPI:  torchani

### ISSUE THREAD

**Issue by zasdfgbnm** [pypa/pypi-support#528]
**Project**
https://test.pypi.org/project/torchani/

**Reason**
Hi, our project hits the size limit on testing PyPI, because we upload it often for testing. We don't need an increase in the project size, but could someone delete all existing releases so that there is room for future upload?

**Note**
This request is about testing PyPI, please don't touch the normal PyPI.

**Comment by di** [comment]
Hi, you should be able to do this yourself as the project owner, is there a reason why you can't?

**Comment by zasdfgbnm** [comment]
@di I do have the permission to clear it, but there are so many releases, and it ask me to type the version for each delete...

**Comment by di** [comment]
@zasdfgbnm You can delete the entire project, which will permanently remove all releases. This will require that you make a new upload immediately afterwards to regain ownership of it. Note that you will not be able to reuse previously published versions.

**Comment by zasdfgbnm** [comment]
@di Yes, this approach works. Thanks for the suggestion. Closing now.
