### ISSUE TITLE
Please allow kliment to upload Printrun

### ISSUE THREAD

**Issue by hroncok** [pypa/pypi-support#529]
Hello, due to https://github.com/pypa/pypi-support/issues/355 the name Printrun is not allowed.

Could you please allow the user @kliment (also "kliment" on PyPI) to upload the project? They are the author of the software packaged in Fedora.

CCing @encukou for completes.

Thanks.

**Comment by di** [comment]
@encukou Can I get a 👍 ?

**Comment by encukou** [comment]
Yes, I trust Miro.

On August 2, 2020 6:53:58 PM GMT+02:00, Dustin Ingram <notifications@github.com> wrote:
>@encukou Can I get a 👍 ?>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/pypa/pypi-support/issues/529#issuecomment-667698123

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by di** [comment]
The project has been removed from the blocklist, please publish a release at soon as you are able.

**Comment by hroncok** [comment]
Thank You.
