### ISSUE TITLE
PEP 541 Request: frozendict

### ISSUE THREAD

**Issue by Marco-Sulla** [pypa/pypi-support#530]
**Project to be claimed**
`frozendict`: https://pypi.org/project/frozendict/

**Your PyPI username**
`Marco.Sulla`: https://pypi.org/user/Marco.Sulla

**Reasons for the request**
The project has no update by 4 years. 

**Maintenance or replacement?**
Maintenance: https://github.com/Marco-Sulla/python-frozendict

**Contact and additional research**
I forked the project on Github and started to address some issue. Than I contacted the author, @slezica, about 9 months ago privately. He was open to add me as co-admin, but the last time I had some news was in April. See also https://github.com/pypa/pypi-support/issues/38

**Comment by Marco-Sulla** [comment]
ping

**Comment by Marco-Sulla** [comment]
ping...

**Comment by Marco-Sulla** [comment]
ping...

**Comment by Marco-Sulla** [comment]
Any news? There are many people that moved away from that project because is unmaintained, and another one is flying away:
https://github.com/digitalbazaar/pyld/pull/140

**Comment by yeraydiazdiaz** [comment]
Hi @Marco-Sulla, I'm tagging @slezica and attempting contact via email as well thus starting the reachability process. Hopefully we will hear back soon and move forward with the transfer.

**Comment by Marco-Sulla** [comment]
@yeraydiazdiaz Hello, some news?

**Comment by yeraydiazdiaz** [comment]
Hi @Marco-Sulla, not yet, PEP 541 requires moderators to attempt contact with the current owner at least 3 times for a period of 6 weeks though.

**Comment by yeraydiazdiaz** [comment]
@slezica if you are indeed the owner of the project we'd appreciate you taken a few seconds to clarify your position regarding this project.

**Comment by yeraydiazdiaz** [comment]
The owner replied saying he accepts the transfer, I will now ask an admin to perform it for you.

**Comment by Marco-Sulla** [comment]
Any news?

**Comment by Marco-Sulla** [comment]
Well, it's passed over than a month and I do not any access on my Pypi account. What's happened, @yeraydiazdiaz ? :)

**Comment by yeraydiazdiaz** [comment]
If you don't have access to your PyPI account you'll need to open an [account recovery issue](https://github.com/pypa/pypi-support/issues/new?labels=account-recovery&template=account-recovery.md&title=Account+recovery+request).

Regarding your PEP 541 request, it's been placed in the queue for admin transfers, remember this is a volunteer driven effort and there's limited resources for these tasks.

**Comment by Marco-Sulla** [comment]
No, I have access to my account. I'll wait.

**Comment by ewdurbin** [comment]
Transfer complete.
