### ISSUE TITLE
PEP 541 request: dbfread

### ISSUE THREAD

**Issue by ptvirgo** [pypa/pypi-support#534]
**Project to be claimed**
`dbfread`: https://pypi.org/project/dbfread/

**Your PyPI username**
`CatalystCooperative`: https://pypi.org/user/CatalystCooperative

**Reasons for the request**

Hello!

My name is Pablo, I'm a software developer working with the (Catalyst
Cooperative)[https://catalyst.coop/] out of Philadelphia, PA.  We'd like to
take up maintenance of an abandoned project:
(DBFRead)[https://pypi.org/project/dbfread/]

Our attempts to contact the author are attached, if you review the github
repository you will also note a lack of updates and several open issues and
pull requests that further demonstrate a lack of ongoing maintenance.

Current improvements include several bugfixes based on pull requests submitted
to the original project, as well as a backward compatible interface allowing
DBF filess to be loaded via a file-like object in addition to the file name on
disk.  Looking forward, we intend to:

1. Maintain compatibility with newer versions of Python
2. Clean up and standardize the test suite
3. Provide a clear path for community-sourced code submissions and issue
resolution.

Our work depends upon this library, so we are motivated to ensure ongoing
maintenance is effective and responsive.

With regard to the option of forking and changing the name, our experience was
that trying to find a DBF library for Python that has not been overtaken by
bit-rot is already frustrating due to the age of the format and the proliferation
of abandoned projects that reference "DBF" in their name.  It will be a better
experience for people who still need to access the DBF format if we can carry
this project forward under the same name rather than leave yet another for them
to have to sort through.

We intend this proposal as a service to other people who need an up-to-date
library for parsing DBF files.  If there are gaps in our plan or better
approaches to sharing our work, please let us know so that we can be as
supportive of the broader community as possible.

Thank you,

~ Pablo

**Maintenance or replacement?**
Maintenance, as visible here: https://github.com/catalyst-cooperative/dbfread

**Contact and additional research**

Here is the third email sent to the listed owner, which includes the contents and dates of the previous two messages.  I'm happy to send along complete source of the other two messages separately if need be.

BCC: Zane Selvans <zane.selvans@catalyst.coop>,
 Christina Gosnell <cgosnell@catalyst.coop>
Subject: Re: dbfread
From: Pablo Tao Virgo <mailbox@pablovirgo.com>
To: ombdalen@gmail.com, ole.martin.bjorndalen@uit.no
References: <88da86ff-1457-2c6f-7510-56259d230f94@pablovirgo.com>
 <2d71d00f-80c7-a7a9-7f54-ae25a420fe02@pablovirgo.com>
Message-ID: <7a27cffa-596e-bd8e-a372-dc7efd9e3c57@pablovirgo.com>
Date: Fri, 10 Jul 2020 15:37:11 -0400
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101
 Thunderbird/68.9.0
MIME-Version: 1.0
In-Reply-To: <2d71d00f-80c7-a7a9-7f54-ae25a420fe02@pablovirgo.com>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: 8bit

Hey there,

Thought I'd give it one last go - any plans to keep up the maintenance 
on dbfread?  I'm glad to help if I can.

On 6/26/20 3:58 PM, Pablo Tao Virgo wrote:
> Hi again,
> 
> Following up from the Catalyst Coop;Â  we've worked on a fork of your 
> dbfread project that allows it to handle file-like objects (useful in 
> streaming, for example).
> 
> We'd like the chance to help out with maintenance and keeping the 
> library updated.
> 
> Are you open to that?
> 
> 
> On 4/22/20 8:29 PM, Pablo Tao Virgo wrote:
>> Hello!
>>
>> My name is Pablo, I'm a software developer working with the Catalyst 
>> Cooperative (https://catalyst.coop/).Â  We've been using your dbfread 
>> library to access some data that is not otherwise available.Â  Thanks 
>> for your work putting dbfread together, it's very helpful.
>>
>> We've noticed there are several outstanding pull requests but no 
>> recent development activity from you.Â  Totally understandable if 
>> you're busy elsewhere!
>>
>> Since there are a number of people dependent on your project, 
>> including ourselves, we'd like to offer to take on some of the 
>> maintenance.Â  We can't devote a lot of time to coding changes, but we 
>> can cover some of it, as well as address pull requests from other users.
>>
>> What do you think?
>>
>> ~ Pablo

**Comment by yeraydiazdiaz** [comment]
Hi @ptvirgo, it seems @olemb is the author and owner of the project and is active in GitHub, I will also attempt contact via email as described by PEP 541. Hopefully he can clarify his position regarding this project.

**Comment by ptvirgo** [comment]
Yes, I think he's back to working on it - probably best to close out this request.

**Comment by yeraydiazdiaz** [comment]
Closing as requested.
