### ISSUE TITLE
PEP 541 Request: django-easy-audit

### ISSUE THREAD

**Issue by jheld** [pypa/pypi-support#535]
**Project to be claimed**

`django-easy-audit`: https://pypi.org/project/django-easy-audit

**Your PyPI username**

`snoopy1497`: https://pypi.org/user/snoopy1497

**Reasons for the request**

I've been contributing for years and am now maintaining the project with permissions to merge as well as release to PyPI; I have released several versions. We haven't been able to communicate with the maintainer since sometime in 2019, despite the project being active. Overall we've had a good relationship, but I do worry about long term support/management, since I don't have full permissions on PyPI, which I would have if the project was transferred to me.

**Maintenance or replacement?**

Maintenance. I have been a maintainer/contributor for years.

**Contact and additional research**

Communication via github has not been successful.

He cares about the project but has indicated in the past (via email) that his time with the project has become very limited. I don't wish for this request to be negative in the slightest: he built a great package and his guidance & openness has further cultivated what has become a healthy/active and useful project.

**Comment by yeraydiazdiaz** [comment]
Hi @jheld, I can see your PyPI user is set as a maintainer for the project. I will attempt contact with @soynatan and start the reachability process. Hopefully we'll hear back soon.

**Comment by yeraydiazdiaz** [comment]
The owner replied to my email saying that he thanks the contributors but does not wish to transfer ownership at this time. He also mentions that, while his time is limited, he can be reached if anything pressing comes up.
