### ISSUE TITLE
PEP 541 Request: prelude

### ISSUE THREAD

**Issue by ToToL** [pypa/pypi-support#537]
**Project to be claimed**
`prelude`: https://pypi.org/project/prelude/

**Your PyPI username**
`totol`: https://pypi.org/user/totol/

**Reasons for the request**
I wrote an email to Michel Alexandre Salim to ask him if the project is abandonned and if I can take over it.
His response was clear : "Certainly, I wouldn't want to hog the namespace unnecessarily."
Prelude is a SIEM (https://www.prelude-siem.org) and is available is most Linux distribution. The python part is under libprelude packages.

**Maintenance or replacement?**
Replacement
Code: part of https://github.com/Prelude-SIEM/libprelude

**Contact and additional research**
Yes, Michel Alexandre Salim. And I have an email from him saying he is OK with this.

Thanks

**Comment by jamadden** [comment]
If you're in contact with the owner, can you ask the owner to perform the transfer (assign your account as an additional owner)? That's much faster than going through the PEP 541 process. Transfers that require admin action may take some time.

**Comment by michel-slm** [comment]
I'm the current owner, I'll try and transfer the project now

**Comment by jamadden** [comment]
This transfer appears to have been completed.
