### ISSUE TITLE
PEP 541 Request: fun

### ISSUE THREAD

**Issue by mattmezza** [pypa/pypi-support#538]
**Project to be claimed**

`fun`: https://pypi.org/project/fun

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/mattmezza

**Reasons for the request**

I believe this project is abandoned.

**Maintenance or replacement?**

I intend to publish a different one. It's a set of tools for functional programming in python that we want to open source at my company. We do not have a public repository yet.

**Contact and additional research**

There is no email address listed on the project and I could not find any valid user via the username.

**Comment by jamadden** [comment]
There's also an argument to be made that the project contains no functionality. It's only contents (in `fun.py`) are:
```python
"""
    Just for fun.
    Yoohoo!
"""

def fun():
    print("Hello,man.")

def okay():
    print("All done!")
```

I'm emailed the address PyPI has on file for the project owner. That was the only means of contact I could find.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. The transfer is complete. Apologies for the delay.
