### ISSUE TITLE
PEP 541 Request: elegant

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypi-support#539]
**Project to be claimed**

`elegant`: https://pypi.org/project/elegant

**Your PyPI username**

`pradyunsg`: https://pypi.org/user/pradyunsg

**Reasons for the request**

The project is an invalid project, as far as I can tell.

**Maintenance or replacement?**

Replacement, with a [Sphinx theme](https://github.com/pradyunsg/materialism) that I'm working on. Currently using the name "materialism" for it, but I would really prefer to use the name "elegant" instead. :)

**Contact and additional research**

No attempt at contacting the author by me. This project has an empty `__init__.py` and a really low version number. The user seems to have name-squatted *many* other names as well: https://pypi.org/user/Collie/

**Comment by jamadden** [comment]
Hi @pradyunsg ! I concur that this project (along with many others published by that user) is invalid. As such, it can be transferred.

The moderators have a policy of trying to provide a one-week courtesy notification to the project owner before that happens. As such, I've emailed the verified address PyPI has on file for the project owner letting them know the project will be transferred on or after August 12, and set the status of this issue to reflect that. I've requested the owner make any comments they have on this issue.

**Comment by pradyunsg** [comment]
Awesome! Thanks @jamadden! :)

**Comment by pradyunsg** [comment]
@jamadden Did we get a response?

**Comment by jamadden** [comment]
I have not had a response. I'll update the status to reflect that the transfer should go through.

**Comment by pradyunsg** [comment]
Closing since I've found a different name, that actually available. Thanks for the help here @jamadden! ^>^
