### ISSUE TITLE
Limit Request: kotlin-jupiter-kernel - 100MB

### ISSUE THREAD

**Issue by belovrv** [pypa/pypi-support#54]
link: https://test.pypi.org/project/kotlin-jupiter-kernel/0.6.0/
size: 100 Mb
both: PyPI and Test PyPI
It's Kotlin Jupiter Kernel and it bundles the whole kotlin compiler obviously. Please increase the upload limit

**Comment by di** [comment]
I've set the upload limit for `kotlin-jupiter-kernel` to 100 MB on TestPyPI. The project doesn't exist on PyPI, you'll need to create a project there before I can increase the limit.
