### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by zomGreg** [pypa/pypi-support#541]
Request for account recovery.

## PyPI Username

`zomgreg`

---

##  Reason for request

Reason:

I think the email associated with the zomgreg username is tied to my old work account, which no longer exists, something like zomgreg@enstratus.com or zomgreg@enstratius.com is the most likely. Reset password will not work because those companies no longer exist (startups).

**Comment by zomGreg** [comment]
is this thing on?

**Comment by ewdurbin** [comment]
I was able to find reasonable record of an address matching your public GitHub profile in a longstanding release of the `ascention_kit` project. Unfortunately this address is currently associated with another PyPI user and cannot be used for the `zomgreg` User.

How would you like to proceed?

**Comment by ewdurbin** [comment]
Checking in for a response to the above @zomGreg

**Comment by zomGreg** [comment]
Hi Guys,

Sorry for the delay in my response. What are my options? I am 99% sure this repo is tied to an account I held while working at a startup years ago. The company no longer exists.

**Comment by ewdurbin** [comment]
@zomGreg because the new user has no projects associated with it, the account could be deleted and the address reassigned to the `zomgreg` User.

**Comment by zomGreg** [comment]
Hi ewdurbin,

Well, that seems reasonable. My concern is the user experience for the owner of the other account. You probably can't tell me who owns it (which makes sense) but how can we be sure they will not have a bad experience as a result of such an action? Thanks for helping with this.

**Comment by ewdurbin** [comment]
@zomGreg as far as I can tell the new user registered with the email address publicly displayed on _your_ GitHub profile. Is that not you?

**Comment by zomGreg** [comment]
Okay, so maybe my initial request was somewhat poorly worded. Yes, the email on my github is my email address.

When I try to login to pypi with that email, I get the message:  No user found with that username

However, when I run through the resetting password process, I am able to get a link sent to that email address and reset my password. After doing that, I get the message No user found...

I initially thought the problem was related to me setting the wrong email address. Can you see from your end what is going on with my PyPi account?

Thanks and sorry for the confusion.

**Comment by ewdurbin** [comment]
@zomGreg there currently exits a `pygreg` user associated with your gmail account that has no projects associated with it, and a `zomgreg` user associated with a couple projects that has the the enstratius.com address you noted.

If you would like to recover access to the `zomgreg` account by replacing the `enstratius.com` email with your `gmail.com` email, we can do that but `pygreg` user needs to either be deleted or you need to update it to use another address.

**Comment by zomGreg** [comment]
I'm okay with deleting the pygreg account and replacing the enstratius.com email with the gmail one. 

Thanks.

**Comment by ewdurbin** [comment]
This is complete. The `zomgreg` user has now been updated to use the gmail address from your public GitHub profile which matches metadata from historical releases of projects associated with the account.

You can preform a password reset to regain access to your account.

**Comment by zomGreg** [comment]
I tried recovering the account for the email on my github account. The password recovery process appears to work, but the error: "No user found with that username" is the error when I try to login.
