### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by richard-scott** [pypa/pypi-support#542]
Request for account recovery.

## PyPI Username

`sourcedefender`

---

##  Reason for request

Reason:  Lost 2FA authentication app and haven't created recovery codes.

**Comment by richard-scott** [comment]
Is there any update on this? All I need is the 2FA removing from my account. I have the password to get in and re-set this up.
@di Any chance you could help out?

**Comment by richard-scott** [comment]
I have the same username and email address setup on test.pypi.org if that would help speed up the verification process.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
