### ISSUE TITLE
Limit Request: intel-tensorflow-avx512, 450 MB

### ISSUE THREAD

**Issue by shwetaoj** [pypa/pypi-support#543]
Project: intel-tensorflow-avx512

Size:  450MB on pypi.org and test.pypi.org

Which indexes: both

Reasons for the request: intel-tensorflow is intel optimized tensorflow, which has better performance on intel platform. We are trying to release 2.3 intel-tensorflow. Going forward along with avx whls(default) we would like to release avx512 whls which are for another hardware. Hence we created a new  project called intel-tensorflow-avx512 to release avx512 whls. Please increase the limit for this project to match our other project intel-tensorflow.

Please see previous request submitted from our team: #499 .

**Comment by shwetaoj** [comment]
Hi @jamadden and @pradyunsg could you please look into this.? Very appreciated

**Comment by rsketine** [comment]
AVX512 packages are complementary to the regular Intel TensorFlow releases. These are required for a good user experience on all new releases of Intel HW. We would like to expand our package publishing to 2 types one default AVX and AVX512. Can you please help increase the size for these package publishing. @jamadden can you please check this out and also let us know if you have any questions.

**Comment by shwetaoj** [comment]
Hi @jamadden and @pradyunsg could you please look into this.? Please let us know if you need any additional information from us.

**Comment by shwetaoj** [comment]
Hi @pradyunsg please let us know if you need any additional information. Thank you.

**Comment by shwetaoj** [comment]
@jamadden  can you please help. This is blocking our 2.3 release. 
Issues causing large size are not resolved yet:
bazelbuild/bazel#9254 - not resolved in Bazel 3.1.0 but resolved in bazel 3.4.0 which is not used in building TF 2.3 release.

**Comment by jamadden** [comment]
The limit has been set to 450MB on pypi.org and test.pypi.org. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases.

**Comment by rsketine** [comment]
Thank you very much.
