### ISSUE TITLE
instabot-py seems like abandoned

### ISSUE THREAD

**Issue by ice1x** [pypa/pypi-support#544]
**Project**
https://pypi.org/project/instabot-py/

**Size of release/project**
it's not mine

**Which indexes**
it's not mine

**Reasons for the request**
https://pypi.org/project/instabot-py/ seems like abandoned
No any worging link on the page

As well - it stop works because of "Bad request" and 400 http status code by login() command on code:
`                login = self.s.post(
                    self.url_login,
                    data=login_post,
                    allow_redirects=True
                )`

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install instabot-py`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/instabot-py`). In this case, I see that `instabot-py` was last released a few months ago, so it does not seem to be abandoned.
