### ISSUE TITLE
PEP 541 Request: pymor (on test.pypi.org)

### ISSUE THREAD

**Issue by renefritze** [pypa/pypi-support#545]
`pymor`: https://test.pypi.org/project/pymor

**Your PyPI username**

`koshi`: https://test.pypi.org/user/koshi/

**Reasons for the request**
Being able to test our releases on test.pypi.org would greatly help with an automated release process.
We've been releasing pyMOR regularly on pypi.org proper since 2014: https://pypi.org/project/pymor/#history 
The pymor project on test.pypi.org had one upload in 2015.

**Maintenance or replacement?**
This would be a replacement, the projects are unrelated.

**Contact and additional research**
I've tried to contact @timCF via email a few months back and again via GitHub ticket 2 weeks ago: https://github.com/timCF/pymor/issues/1

**Comment by renefritze** [comment]
Can I do something to improve my request?

**Comment by yeraydiazdiaz** [comment]
Hello @renefritze, IIRC, and other moderators please correct me if I'm wrong, requests for projects in test.pypi.org to be transfered to the owner of the project in PyPI are exempt from reachability are to be transferred directly upon request.

As such I will ask an admin to perform the transfer.

**Comment by renefritze** [comment]
Is there anything I can do to move this along @yeraydiazdiaz?

**Comment by ewdurbin** [comment]
Transfer complete.
