### ISSUE TITLE
Limit Request: grblas - 200 MB

### ISSUE THREAD

**Issue by eriknw** [pypa/pypi-support#547]
**Project**
grblas
https://pypi.org/project/grblas/

**Size of release/project**
200MB

**Which indexes**
PyPI

**Reasons for the request**
`grblas` is a Python wrapper around [GraphBLAS](https://github.com/DrTimothyAldenDavis/GraphBLAS), which is a C library for doing sparse linear algebra and is well suited for graph algorithms.  The wheels we create that contain the GraphBLAS C library range between 140MB-170MB.  It is not yet reasonable to expect the user to install the C library externally, so we would really like to bundle it in the wheel that we can guarantee will work.

Can you please update the package size limit?  We currently have a broken dev version on PyPI.  Thanks.

CC @jim22k

**Comment by jamadden** [comment]
The limit has been set to 200MB on pypi.org
