### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rajeshisnepali** [pypa/pypi-support#548]
Request for account recovery.

## PyPI Username

`rajeshisnepali`

---

##  Reason for request

Reason: I recently factory reset my phone. Unfortunately, there was no recovery codes saved in my password manager. Please disable my 2FA or provide some recovery codes for my account.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by rajeshisnepali** [comment]
So much disappointed that this took more than 3 months to happen. Is issuing an "Account Recovery Request" only the solution to recover who forget or lost their access codes? 

What will be the best suggestion to other users who have gone through the same problem as mine but want quick access?

**Comment by ewdurbin** [comment]
The best method would be to provision multiple 2FA methods (TOTP, WebAuthn) as well as generate and securely store recovery codes.

**Comment by rajeshisnepali** [comment]
Yes, that's correct. Unfortunately, I forgot to save recovery codes.  

How does anyone request for account recovery instead of issuing over here?

**Comment by ewdurbin** [comment]
Filing an issue on this tracker is the only procedure for recovery.

**Comment by rajeshisnepali** [comment]
Oh, I see. I'm not sure but still want to know a bit more. I received an email from PyPI when the password was reset and I saw that they had written to email "[admin@pypi.org](mailto:admin@pypi.org)" to communicate with the PyPI administrators. Won't PyPi admins also recover the password?

**Comment by ewdurbin** [comment]
If you email admin@pypi.org regarding account recovery, you will be directed to file an issue here.

**Comment by ewdurbin** [comment]
I am one of the members of that team, along with di and dstufft who have not had time to participate in these recovery issues.

**Comment by ewdurbin** [comment]
I understand it is disappointing. But it's just the reality of the effort that's been available for these kinds of tasks.

I'm working through the backlog, I'm sorry.

**Comment by rajeshisnepali** [comment]
> If you email [admin@pypi.org](mailto:admin@pypi.org) regarding account recovery, you will be directed to file an issue here.

Oh, if that's the case, that's fine.
