### ISSUE TITLE
Can't delete badly-versioned release

### ISSUE THREAD

**Issue by osvenskan** [pypa/pypi-support#55]
**Describe the bug**
I'm the author & maintainer of sysv_ipc. Ten years ago I accidentally uploaded a release  that contained the description in the version field, so instead of a standard version string like this --
```
3.2.1
```

the version is this --
```
Sysv_ipc gives Python programs access to System V semaphores, shared memory 
and message queues. Most (all?) Unixes (including OS X) support System V IPC. 
Windows+Cygwin 1.7 might also work. 

Sample code is included.

This extension is released under the GPL. 

You might also be interested in the similar POSIX IPC module at:
http://semanchuk.com/philip/posix_ipc/
```

Apparently this mess I created causes problems for some automated tools and I would like to delete this one release. (The `sysv_ipc` package as a whole is fine, I just want to delete this one release.) However, deleting the release requires me to enter the version for confirmation, and I can't seem to enter the multi-line version into the single-line text field, even via copy&paste.

**Expected behavior**
To be able to delete this release

**To Reproduce**
1. Go to https://pypi.org/manage/project/sysv-ipc/releases/#modal-close
2. Try to delete the release with the ridiculous version string

**Comment by osvenskan** [comment]
If I can help (other than "don't do this again!"), please LMK.

**Comment by ewdurbin** [comment]
completed.

**Comment by osvenskan** [comment]
Thank you so much @ewdurbin!
