### ISSUE TITLE
PEP 541 Request: dry-rest-permissions

### ISSUE THREAD

**Issue by RignonNoel** [pypa/pypi-support#551]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/dry-rest-permissions/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/RignonNoel/

**Reasons for the request**

The project is abandoned since January 2018

**Maintenance or replacement?**

We intend to continue the exact same package and just maintain it and enhance it with time.

**Contact and additional research**

We tried to contact the maintainer on Github issue on January 2018: https://github.com/dbkaplan/dry-rest-permissions/issues/60

Since there is no answer we decided to fork the project and to update it to match new environments in June 2020.

Django-Rest-Framework already accepted the new ownership in their documentation: https://github.com/encode/django-rest-framework/pull/7374

 - [x] the project has been determined abandoned by the rules described above;
   - No communication since January 2018.
   - Package is out-of-date since a long time and no communication has been made answer community requests
- [x] the candidate is able to demonstrate their own failed attempts to contact the existing owner;
   - [No answer of the issue since more than two years](https://github.com/dbkaplan/dry-rest-permissions/issues/60)
- [x] the candidate is able to demonstrate improvements made on the candidate's own fork of the project;
   - The package was out of date, now it's working
   - We tested and validated new version of DRF with it
   - We include new TravisCI build and refreshed all the supported version of Python and DRF
- [x] the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround; and
   - All the system already using this package does not know about the new fork
   - The old name is used in a lot of personal documentation and tutorial, out-of-date because of the pypi name
   - Community seems to ask for it [in our issues](https://github.com/FJNR-inc/dry-rest-permissions/issues/11)
- [ ] the maintainers of the Package Index don't have any additional reservations.
   - You're the boss for this check

**Comment by RignonNoel** [comment]
@jamadden Sorry to bother you, but do you have some informations, i just want to know if your team tried to contact the old maintainer with an email in your file or something like that ? 

We began some public presentations of the package like in Montreal-Python and some peoples ask us if this transfer will be done or not. I just want to know what to answer.

**Comment by jamadden** [comment]
As far as I can see, no one has looked into this yet. If they have, you should see the ticket added to a project in a particular state.

**Comment by yeraydiazdiaz** [comment]
Hello @RignonNoel, apologies for the delay, I'm moving your request to reachability and attempt contact with either of the current maintainers, hopefully we'll hear from one of them soon and move forward with the transfer.

**Comment by RignonNoel** [comment]
> Hello @RignonNoel, apologies for the delay, I'm moving your request to reachability and attempt contact with either of the current maintainers, hopefully we'll hear from one of them soon and move forward with the transfer.

No problem, i guess that everybody have delay these times :p

Thanks for the commitment, hope to fix that soon !

**Comment by rodrigondec** [comment]
> Hello @RignonNoel, apologies for the delay, I'm moving your request to reachability and attempt contact with either of the current maintainers, hopefully we'll hear from one of them soon and move forward with the transfer.

Is there a max limit time for the await? Or this stays on hold until the contact is made?

**Comment by yeraydiazdiaz** [comment]
PEP 541 states that moderators need to attempt contact with the owner at least three times for a period of 6 weeks.

**Comment by yeraydiazdiaz** [comment]
I have not received any reply on my attempts to contact the owner. Transfer complete.
