### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by munshkr** [pypa/pypi-support#556]
Request for account recovery.

## PyPI Username

`munshkr`

---

##  Reason for request

Reason: Lost both 2FA authentication app and recovery codes.

**Comment by munshkr** [comment]
Thanks @ewdurbin for getting into this, I know you have a lot of requests. Let me know if I can do something from my side.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by munshkr** [comment]
Hi. Thank you for replying. I've just pushed the branches on both repositories.

**Comment by ewdurbin** [comment]
please follow all instructions in the email, including responding to the email :)

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
