### ISSUE TITLE
Can't delete release named `.`

### ISSUE THREAD

**Issue by ecordell** [pypa/pypi-support#56]
**Describe the bug**

I have a release named `.` that I can't view or delete.

This may or may not be a dupe of pypa/pypi-support#55

**Expected behavior**

I'm not sure how it got there in the first place, but there's a release named `.` for one of my projects. I'd like to delete it but I can't. When I try to delete it, I see a 404. When I try to view it, it redirects to the project home page.

**To Reproduce**
https://pypi.org/project/pymacaroons/#history (scroll to the bottom)

**Comment by ewdurbin** [comment]
release removed.
