### ISSUE TITLE
Claim for `mason` pypi package

### ISSUE THREAD

**Issue by kyprifog** [pypa/pypi-support#570]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/mason/

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/kprifogle

**Reasons for the request**
I have a mature project called "mason" which I plain on maintaining for a while.  Hope to make it an apache project as well.  The existing project has not been updated for several years:  https://github.com/vail130/mason

**Maintenance or replacement?**
I plan to maintain and keep active a new mason project.  This would be a replacement.
I hope to open source the code shortly, trying to clean it up first.  If you need the source code to be open sourced sooner rather than later let me know, but I planned on open sourcing at the same time as releasing the mason pypi project.

**Contact and additional research**
Attempted to contact the current owner but didn't receive any reply.

**Comment by jamadden** [comment]
The owner of `mason` appears to be @vail130. Hopefully @vail130 will see this notification and respond to this issue.

**Comment by kyprifog** [comment]
Totally agree, I reached out to vail by email, but happy to talk it over with him first.

**Comment by kyprifog** [comment]
@jamadden just curious how long do you guys typically wait on requests like this?

**Comment by jamadden** [comment]
PEP 541 specifies a six-week period to contact the owner. After that, if the owner isn't contacted, it depends on when the admins can make time to perform transfers.

**Comment by vail130** [comment]
Hey, sorry for the delay, it's fine with me. Do I need to do something?

**Comment by jamadden** [comment]
@vail130 If at all possible, it's best if you were to add the requested user as an owner of the project on PyPI. This keeps a clear audit log of the transfer, and avoids having to wait on the admins (which can take a few months).

**Comment by kyprifog** [comment]
@vail130 Thanks a ton!   This will make my life alot easier as I try to get this package out the door.   I'll wait to be added as an owner.

**Comment by vail130** [comment]
done
