### ISSUE TITLE
Transfer of name FLIP

### ISSUE THREAD

**Issue by divait** [pypa/pypi-support#571]
**Project to be claimed**

Flip
`PROJECT_NAME`: https://pypi.org/project/FLiP

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/divait

**Reasons for the request**

It looks like the project has been abandoned, last release is around 9 years ago: Released: Jul 7, 2011. and have only 2 releases.
And last commit in the [github repo](<https://github.com/jon-jacky/FLiP>) is on Jul 11, 2011.

**Maintenance or replacement?**

If the domain is transfer it will be replace we our new project for data augmentation: https://github.com/LinkedAi/flip

**Contact and additional research**

I try to contact Jonathan the owner via email a couple of times, but have no answer from him at the moment.

**Comment by jamadden** [comment]
[PEP 541 states](https://www.python.org/dev/peps/pep-0541/#abandoned-projects):

> Under no circumstances will a name be reassigned against the wishes of a reachable owner.

Since the owner was reached, does not wish to give up the name, and the project is valid, there's nothing more that can be done under this process.

**Comment by divait** [comment]
Thanks @jamadden , I understand.
