### ISSUE TITLE
Re: PEP 541 Request: marker

### ISSUE THREAD

**Issue by mustafaquraish** [pypa/pypi-support#573]
Hey, I just wanted an update on my previous request #438 (from more than 2 months ago at this point), which was put in the invalid courtesy period but has been stuck in limbo since. I know you all are pretty busy, but is there any chance to get this processed?

> **Project to be claimed**
> `PROJECT_NAME`: https://pypi.org/project/marker
>
>
> **Your PyPI username**
> `USER_NAME`: https://pypi.org/user/mustafaquraish
>
>**Reasons for the request**
 >I have recently developed a package consisting of utilities to automate and assist marking coding exercises. The package name of `marker` would be great for this, and it doesn't seem like there has been anything with this name recently.
> ```
> mustafa$ pip3 install marker
> ERROR: Could not find a version that satisfies the requirement marker (from versions: none)
> ERROR: No matching distribution found for marker
> ```
>
>
> **Maintenance or replacement?**
> I don't know the purpose of the original package since it is not available to download, so I intend to replace it.
> 
> **Contact and additional research**
> I have found no way to find or contact the previous owner

Thanks again for the help!

**Comment by jamadden** [comment]
Please do not open new issues when the original issue is still open. Thank you.
