### ISSUE TITLE
PEP541  Request: User `iotserv` Squatting, Transfer `ngrok`

### ISSUE THREAD

**Issue by alexdlaird** [pypa/pypi-support#574]
**Project to be claimed**
`ngrok`: https://pypi.org/project/ngrok/

**Your PyPI username**
`alexdlaird`: https://pypi.org/user/alexdlaird

**Reasons for the request**
The user `iotserv` is squatting on eleven project names, all of which are identical, empty projects not updated since first publishes two years. Specifically as it pertains to `ngrok`, however, I maintain `pyngrok`, which maintains the `ngrok` binary. It would make a lot more sense if I were able to name this package what it is, `ngrok`.

**Maintenance or replacement?**
The package will be replaced with this: https://github.com/alexdlaird/pyngrok.

**Contact and additional research**
I reached out to yu@iotserv.com, no response.

**Comment by alexdlaird** [comment]
The linked GitHub user in all the projects, [nat-cloud](https://github.com/nat-cloud), also 404s, and the domain name for the associated email is a non-existent website.

**Comment by di** [comment]
Thanks for filing this. Given that [`ngrok`](https://ngrok.com/) is a trademark, I think we'd prefer to release this particular project name to someone affiliated with that company in order to avoid name disputes in the future. Are you affiliated with them in any way? Would you be opposed to continuing to call your project `pyngrok` instead?

**Comment by alexdlaird** [comment]
Ah, I hadn't considered that. No, I am not officially affiliated with them, just maintain the only Python package that provides a robust API to their product. So by installing `pyngrok`, you _are_ installing `ngrok` (the package manages their binary as well), but I can understand why you'd want to give it to someone who is actually affiliated with the trademark. My intent was based off [this package](https://www.npmjs.com/package/ngrok), which is also not owned or maintained by the trademark holders but provides a similar API for Node.

Anyway, I'll leave the decision to you, I understand either way.

**Comment by alexdlaird** [comment]
I don't know if ya'll have a way to lock names in cases like this then, though, because I've accidentally downloaded this package more times than I'd care to admit _trying to download my own package_ 😂. So, it still feels like this `ngrok` package should be deleted and the name locked until the actual trademark owner comes along, assuming you have a way to do that.

**Comment by di** [comment]
We can definitely do that for all of this users squatted packages.

You might want to consider reaching out to ngrok to see if they'd be interested in "blessing" your project under that name, since it doesn't seem like they publish anything similar.

**Comment by alexdlaird** [comment]
I'll get back to you and reopen this ticket if that happens, otherwise I'll continue on my merry way with `pyngrok` as-is. Thanks!

**Comment by pradyunsg** [comment]
Marked as awaiting response, based on @alexdlaird's last comment. :)

**Comment by pradyunsg** [comment]
Closing this out, since @alexdlaird hasn't gotten back. :)
