### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tjingrant** [pypa/pypi-support#575]
Request for account recovery.

## PyPI Username

`tian_jin`

---

##  Reason for request

- Lost access to email address

Reason:

Lost access to my old email address tian.jin1@ibm.com.

**Comment by ewdurbin** [comment]
With the transfer in issue #581 complete this user now has no projects associated with it. As such I've updated it to use the public email address on your GitHub profile. You can proceed with a password reset to regain access to the account.
