### ISSUE TITLE
Limit Request: paddlepaddle_gpu: 600MB

### ISSUE THREAD

**Issue by kolinwei** [pypa/pypi-support#576]
**Project:**
https://github.com/PaddlePaddle/Paddle
https://pypi.org/project/paddlepaddle-gpu/

**Size of release/project**

600MB

**Which indexes**

PyPI

**Reasons for the request**

We will release a new version for paddlepaddle_gpu recently. Our current size limit is 450M, and the last version is 420M. Because a few new features are enabled in this version, and most of the new feature is new  operate op (200 new api )with cuda and cudnn, so the size  increase quickly. the package size will go to 520MB. Can you please help to increase this to around 600MB.

**Comment by kolinwei** [comment]
Any update for this issue? Your help is most appreciated。
We will release a new version on Sep 11，and really need your help

**Comment by jamadden** [comment]
The limit has been set to 600MB on pypi.org. This is one of the larger limits and files of that size produce a poor experience for end users as well as stressing PyPI, its mirrors and CDNs. Please be aware of this when planning releases. 

In the future, you may wish to consider splitting the release into separate projects with discrete functionality so as to remain below the limit and provide a better experience for users.
