### ISSUE TITLE
PEP 541 Request: pythonista

### ISSUE THREAD

**Issue by sk-** [pypa/pypi-support#578]
**Project to be claimed**

`pythonista`: https://pypi.org/project/pythonista/

**Reasons for the request**

This project was created with the sole purpose of reserving the name. In fact the user https://pypi.org/user/leesoar/ has created in bulk 53 projects, many of which are even trademarked names like `adidas`, `bbc`, `dell` and some others which can generate confusion to users.

**Maintenance or replacement?**

I plan on publishing soon a `pythonista` package.

**Contact and additional research**

No, as the user clearly is misusing the index.

**Comment by hugovk** [comment]
See also https://github.com/pypa/pypi-support/issues/557

**Comment by sk-** [comment]
Closing as duplicate of #557.

**Comment by hugovk** [comment]
Ah sorry, I think you could reopen this as a concrete request for `pythonista`. That issue is more general and for some background info.

**Comment by sk-** [comment]
Reopening as per @hugovk suggestion.

To give some more context, the package I plan to update is an automatic linter/code transformer which provides a much simpler user interface for `libcst`. Hence the chosen name `pythonista`.

The idea is that instead of dealing with an AST, transformations are written as:

```py
class NoneEquality(PythonistaTransform):
  def equality_before(x):
    x == None

  def equality_after(x):
    x is None
```

The package is almost there, but I'm cleaning up the code a little bit more before releasing the initial version.

**Comment by sk-** [comment]
Closing, as I finally chose a new name.
