### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by TomChavez** [pypa/pypi-support#580]
Request for account recovery.

## PyPI Username

`tomchavez`

---

##  Reason for request

Reason:
System won't let me register for username tomchavez after I created and then deleted an account with this username as it had the wrong primary email address. Should have been tom.chavez@comcast.net but accidentally used tom.chavez@splunk.com, which is a hard bounce. My work email is tchavez@splunk.com though I'd prefer to use my personal account. Trying to register again causes a page crash of 429 Too Many Requests

**Comment by ewdurbin** [comment]
@TomChavez please try registering again. Our systems have rate limiter for account registration attempts that will certainly have been expired by now.
