### ISSUE TITLE
PEP 541 Request: onnx-tf ownership transfer

### ISSUE THREAD

**Issue by chinhuang007** [pypa/pypi-support#581]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/onnx-tf

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/chinhuang007

**Reasons for the request**
The current project owner https://github.com/tjingrant has taken a new job and responsibilities. The transfer of ownership is to ensure the continued development and maintenance of the onnx-tf project. We created and tagged a new release 1.6 a few weeks ago, but we are unable to publish to Pypi due to owner's loss of account access. An issue is opened to track the onnx-tf release, https://github.com/onnx/onnx-tensorflow/issues/738. And an issue is opened to recover owner's account, https://github.com/pypa/pypi-support/issues/575.

**Maintenance or replacement?**
I will continue to maintain the project

**Contact and additional research**
I have contacted the current owner and got agreement to transfer project ownership.

**Comment by hugovk** [comment]
If possible, it would be much quicker for @tjingrant to directly add you as a maintainer or owner on PyPI.

**Comment by tjingrant** [comment]
@hugovk thanks! I consent to this ownership transfer.

**Comment by chinhuang007** [comment]
@hugovk We are stuck for several weeks. I wonder you would be able to help the ownership transfer? Or direct us to someone who has the permissions to help? very much appreciated!

**Comment by hugovk** [comment]
I'm just a passerby trying to help out, the admins are very busy, hopefully one will check this soon.

**Comment by chinhuang007** [comment]
@ewdurbin I know all admins are extremely busy. Just wonder if you can help to transfer the project ownership? The current owner Tian (tjingrant) lost his account access and the recovery issue #575 has not being addressed. He has agreed with the ownership transfer, as seen in this thread, so we can continue to publish onnx-tf releases to pypi. Thank you very much for your help.

**Comment by ewdurbin** [comment]
This transfer has been complete.

**Comment by chinhuang007** [comment]
@ewdurbin thank you!
