### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Drakovek** [pypa/pypi-support#582]
Request for account recovery.

## PyPI Username

`Drakovek`

---

##  Reason for request

Reason: I lost the device that I had used to set up my two factor authentication, and I forgot to create recovery codes for this type of situation.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@Drakovek do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: Drakovek" to proceed

**Comment by Drakovek** [comment]
Sorry yes. I've followed the instructions on your original email and sent a reply. I think I see what the problem was before.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
