### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Eric-Arellano** [pypa/pypi-support#585]
Request for account recovery.

## PyPI Username
`EricArellano`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

I wiped my iPhone in an attempt to fix an issue it was having. To my horror, the iCloud backup did not include backups for Microsoft Authenticator. I also realized I had not set up recovery codes for PyPI, as I didn't know it was an option when setting up 2FA.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Eric-Arellano** [comment]
https://github.com/pantsbuild/pants/tree/6zO9p1WAJznesv9s and https://github.com/pantsbuild/pex/tree/6zO9p1WAJznesv9s. Thank you! I appreciate your help.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
