### ISSUE TITLE
PEP 541 Request: aws-iot

### ISSUE THREAD

**Issue by Janluak** [pypa/pypi-support#587]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/aws-iot/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/janluak

**Reasons for the request**

The project seems only to be a one-time commit with blocking the name. It is only very limited code available. Additionally, a further versioned (`v0.1.3`) project from the same author is https://pypi.org/project/awsiot/ (missing `-` in name).

**Maintenance or replacement?**

I intend to replace the `v0.0.1` package with a much more sophisticated package for high-level interaction with aws iot (e.g. crossing out boto3 raw commands), currently under refactoring from a private business related repo. When scanning through the available names I came across this unmaintained package with very general name fitting quite well.
If code is necessary I believe to have refactoring finished by end of week.

Sure, the possibility to publish under a different name is given. Yet, a general name like `aws-iot` laying around unmaintained and instead forcing every body else to use other, longer and not describing as good don't seem to make a lot of sense to me...

**Contact and additional research**

I tried to contact the previous owner via email but did not receive a response.
With missing links to a repository and both accounts for a `cruizer` on gitlab and GitHub not having any public repos, I have no further idea of contacting the author.

**Comment by yeraydiazdiaz** [comment]
Hello @Janluak, apologies for the delay. I'm moving your request to reachability and attempt contact with the author, hopefully we will hear back soon.

**Comment by yeraydiazdiaz** [comment]
GitHub user @cruzer seems to be owner of the project and the [awsiot GitHub repo](https://github.com/adamsondelacruz/awsiot) which matches the code in PyPI.

@cruzer, would you mind clarifying your position in regards to your package? I suggest reading [PEP 541](https://www.python.org/dev/peps/pep-0541/) to have a better idea of the process and its motivation.

**Comment by Janluak** [comment]
@yeraydiazdiaz @cruzer is there any update so far?
I further developed the potentially replacing library and would like to clarify if going public by this vital name will be possible.

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay @Janluak, the transfer is now complete.
