### ISSUE TITLE
PEP 541 Request: hdwallet

### ISSUE THREAD

**Issue by meherett** [pypa/pypi-support#588]
**Project to be claimed**

`hdwallet`: https://pypi.org/project/hdwallet

**Your PyPI username**

`meherett`: https://pypi.org/user/meherett

**Reasons for the request**

This project has clearly been abandoned. The package has no description, and efforts to contact the maintainer via email have not succeeded because there is no email address to contact the maintainer.

**Maintenance or replacement?**

Currently, the project is almost done. Now, I'm waiting hdwallet namespace to intend to replace this package with https://github.com/meherett/python-hdwallet.

**Contact and additional research**

I have attempted to contact the maintainer but there is no email address provided.

**Comment by meherett** [comment]
Hi @jamadden, Any updates, or is there any response from the owner? Still, this package did not have any available versions.

**Comment by meherett** [comment]
Hi @jamadden @hugovk @yeraydiazdiaz, Any response from the owner? pending...

**Comment by hugovk** [comment]
There's now a 404 for https://pypi.org/project/hdwallet/. Maybe the original owner deleted it?

**Comment by meherett** [comment]
Yeah, It's also deleted but name is still under taken by the owner. (403)

<img src="https://raw.githubusercontent.com/meherett/hdwallet/master/hdwallet.png"/>

**Comment by meherett** [comment]
Hello @hugovk @di @jamadden @yeraydiazdiaz, Any updates? Or how can I contact the owner?

**Comment by meherett** [comment]
I don't know why someone says me nothing? Please @hugovk, Is there any updates? It's also for almost 6 weeks.

**Comment by hugovk** [comment]
@meherett I'm not an admin or maintainer here, unfortunately they're quite busy but hopefully someone will check it soon.

**Comment by meherett** [comment]
Okay @hugovk, Thanks!

**Comment by meherett** [comment]
Hello @jamadden @di, Could you please help us with project transferring?

**Comment by meherett** [comment]
Hello @jamadden @di, Is there any updates? It's also for almost six weeks.

**Comment by jamadden** [comment]
The project appears to be hosted in the archived github repository https://github.com/FelixWeis/python-hdwallet owned by @FelixWeis who also appears to own the project on PyPI. All its releases were removed in December 2018. Perhaps @FelixWeis would consent to transfer the project or delete it to release the name?

**Comment by jamadden** [comment]
@meherett You write:

> Currently, the project is almost done. Now, I'm waiting hdwallet namespace to intend to replace this package with https://github.com/meherett/hdwallet.

But that repository is nearly empty, it contains no source code, no tags or branches besides the default, and no releases.

![Untitled](https://user-images.githubusercontent.com/1256082/95574483-9f0b8500-09f2-11eb-895b-844717f46883.png)

**Comment by meherett** [comment]
@jamadden,

Yes, The repository is empty. I think it's compulsory, Ok I will release it the source code within hours.

**Comment by meherett** [comment]
Hello @jamadden @ewdurbin, How much day I will be waiting? It's for more than 6 weeks. This project is no longer update. The latest update of this project is 8 years ago. It has clearly been abandoned.

**Comment by jamadden** [comment]
I've sent a final notice to the email associated with the project owner warning them that the project is now considered invalid under PEP 541 and is subject to transfer on or after November 19th.

**Comment by meherett** [comment]
Hi @jamadden, Is there any response from the owner?

**Comment by meherett** [comment]
Hi @jamadden, Is there any response from the owner?

**Comment by meherett** [comment]
@jamadden pending...

**Comment by meherett** [comment]
@jamadden any response?

**Comment by meherett** [comment]
@ewdurbin @jamadden Any responses? Today is Dec 1.

**Comment by meherett** [comment]
@ewdurbin @jamadden Any responses? It's for more than 12 weeks. IDK, It doesn't make sense to waiting for a deleted project.

**Comment by meherett** [comment]
Hello @jamadden, Can I get it now? Is there any response from the owner?

**Comment by meherett** [comment]
@ewdurbin @jamadden @pradyunsg @di ... ?

**Comment by ewdurbin** [comment]
transfer complete.

@meherett just want to let you know that endlessly pinging volunteers is a fairly rude and excessive tactic.
