### ISSUE TITLE
Please remove the `distro-info` project. 

### ISSUE THREAD

**Issue by verhovsky** [pypa/pypi-support#589]
https://pypi.org/project/distro-info/#history

`distro-info` is a Python tool used for upgrading Ubuntu. https://packages.ubuntu.com/groovy/distro-info

If you use the standard way of upgrading all pip dependencies (as far [as I can tell](https://github.com/pypa/pip/issues/988), a bash command copy-pasted from stackoverflow https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip is still the canonical way to do that) this causes pip to install `distro-info` which was uploaded to PyPI in 2013 and hasn't been used since which causes the Ubuntu `do-release-upgrade` command to break https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1874250

I haven't actually verified this is what causes `do-release-upgrade` to break, but when I do `sudo pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U` I see

```
$ sudo pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U
Processing /root/.cache/pip/wheels/70/41/44/7433bd9e251aed01842961adf793059948d1de98d25877c5b8/distro_info-0.0.0-py3-none-any.whl
Installing collected packages: distro-info
  Attempting uninstall: distro-info
    Found existing installation: distro-info 0.0.0
    Uninstalling distro-info-0.0.0:
      Successfully uninstalled distro-info-0.0.0
Successfully installed distro-info-0.0.0
[...]
```

**Comment by pradyunsg** [comment]
> If you use the standard way of upgrading all pip dependencies (as far [as I can tell](https://github.com/pypa/pip/issues/988)

As a pip maintainer, I suggest not using commands like that because they'll certainly break your environment in weird ways. There's a reason pip doesn't have a pip upgrade-all command, and it's due to complexities around doing it properly. None of the answers on that question are robust enough to not break things. :)

---

IIUC, @paulproteus is the owner of that package -- perhaps they might have context to bring into this discussion.

**Comment by di** [comment]
I don't think users running unsupported workflows is grounds to remove what appears to be a legitimate package.

Furthermore, the `distro-info` project has [gotten a new release as of Oct 2021](https://pypi.org/project/distro-info/1.0/), which might help with the breakage experienced here.
