### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by eraymann** [pypa/pypi-support#591]
Request for account recovery.

## PyPI Username
`elias.raymann@gmail.com`

---

##  Reason for request
- Lost 2FA authentication app or security token

Reason:
After reinstalling Microsoft Authenticator on my iPhone, 2FA no longer works. Apparently the iCloud Sync was disabled. Therefore I obviously lost the connection with pypi. Unfortunately I don't have any account recovery codes either.
What I still know are username, password and token.
I have this problem at pypi.org and at test.pipy.org

It would be great if you could help me.
Thank you very much and best regards, Elias

**Comment by ewdurbin** [comment]
I located an account with username `elias.raymann` based on that email address.

Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by eraymann** [comment]
Replied to the email. Many thanks for the help.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
