### ISSUE TITLE
Add redirect to flask-babel pythonhosted documentation

### ISSUE THREAD

**Issue by TkTech** [pypa/pypi-support#592]
In the same nature as #203, the flask-babel documentation has moved to https://flask-babel.tkte.ch. However, the old, out of date documentation is still on pythonhosted as the #1 search result, and there are many existing links pointing to it. We used to be able to upload an index.html with a redirect, but this appears to be gone and all we can now do is destroy it.

Flask-Babel issue at https://github.com/python-babel/flask-babel/issues/176.

**Comment by TkTech** [comment]
Apologies for the incorrect issue label.

**Comment by TkTech** [comment]
Is this still possible @ewdurbin?

**Comment by ewdurbin** [comment]
Yes it is.

@TkTech should the URL be preserved on redirect?

**Comment by TkTech** [comment]
Awesome! Nope, just the root, since the structure will likely change.

**Comment by ewdurbin** [comment]
redirect is configured
