### ISSUE TITLE
PEP 541 Request: ebel

### ISSUE THREAD

**Issue by brucetony** [pypa/pypi-support#598]
**Project to be claimed**

`ebel`: https://pypi.org/project/ebel/

**Your PyPI username**

`bschultz`: https://pypi.org/user/bschultz/

**Reasons for the request**

The project was created on April 17, 2020 as a "placeholder" for their upcoming code release. They blocked both `ebel` as well as `e-bel` for their project and it has now been almost 5 months and there have been no changes on either project, nor has any code been released in relation to the proposed package. This is clearly a case of name squatting.

**Maintenance or replacement?**

I intend to publish our our own software package. It will be located in the same repository as our REST API interface software: https://github.com/e-bel/. The proposed `ebel` package is currently hidden until I have submitted the corresponding publication.

**Contact and additional research**

I have attempted to contact the maintainer @mmebel1234, but there has been no reply.  

Additionally, this "placeholder" package was created on the exact same day that our first package was released on PyPI: [ebel_rest](https://pypi.org/project/ebel-rest/). The [`ebel-rest` package](https://github.com/e-bel/ebel_rest) is a package for interfacing with the API of our upcoming eBEL software package. 

I believe the "maintainer" of the above listed `ebel` package is a disgruntled former employee of my company attempting to block my group from using the `ebel` name, especially given the timing of the creation of this "placeholder" package as well as the creation of the account of the "maintainer". @mmebel1234 has not had any other activity since the account's creation.

**Comment by brucetony** [comment]
It has been a month and none of the admins have addressed this issue. There has been no change to the current PyPI package nor has the user had any other activity. Can the name be released?

**Comment by hugovk** [comment]
@brucetony I'm not an admin or maintainer here, unfortunately they're quite busy but hopefully someone will check it soon.

**Comment by brucetony** [comment]
It has been nearly 2 months, is it possible to get an update?

**Comment by yeraydiazdiaz** [comment]
Hi @brucetony, apologies for the delay, I can confirm this project has no functionality and is thus considered invalid. I will now attempt to contact the owner and allow a one week courtesy period for any response, after which we will proceed to transfer the project.

**Comment by brucetony** [comment]
Thank you so much!

**Comment by yeraydiazdiaz** [comment]
I've not heard back from the current owner so I will now ask an admin to perform the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
