### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by muabnesor** [pypa/pypi-support#599]
Request for account recovery.

## PyPI Username

`adrosenbaum`

---

##  Reason for request

Reason: Lost access to email address used to create account. account was connected to email from previous employer. I do no longer have access to the email, and forgot my password 🤦

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, if that bounces or no response is received after 1 week we will proceed with recovery.

**Comment by ewdurbin** [comment]
I have seen no response or bounce from the primary email address on the account.

@muabnesor please email support@pypi.org with the address you'd like associated with the account.

**Comment by ewdurbin** [comment]
Email address for account has been updated as requested. You may now proceed with a password reset to regain access to the account.
