### ISSUE TITLE
Add maintainer to eccodes - maintainer not reachable PEP 541 

### ISSUE THREAD

**Issue by StephanSiemen** [pypa/pypi-support#6]
Hi,
The eccodes PyPi repo (https://pypi.org/project/eccodes/) is limited, out-of-date and the documentation is missing. We tried to contact user "hcsoftcn" - but there are no contact details and we failed to make contact.

ECMWF develops the ecCodes software and we maintain successfully other PyPi repos. We already receive bug/feature reports for this repo, but are not able to fix these. If we could be added as maintainer we will take an active role to support the ecCodes repo and add the missing parts.

Could I please be added as maintainer?

For PEP 541, perhaps we could suggest that every account has to be associated with a valid email address?

Thanks
Stephan

**Comment by yeraydiazdiaz** [comment]
Hello @StephanSiemen, I've emailed PyPI user `hcsoftcn` to clarify the situation. Hopefully we will get an answer soon and move forwards with your claim.

**Comment by StephanSiemen** [comment]
Hi @yeraydiazdiaz,
thanks for following this up. Any news from "hcsoftcn"?
Cheers

**Comment by yeraydiazdiaz** [comment]
Hello @StephanSiemen I have not received any reply from `hcsoftcn` so we will proceed with the transfer.

Could you confirm your PyPI username please?

**Comment by StephanSiemen** [comment]
Thanks @yeraydiazdiaz . My account name for PyPi is "StephanSiemen" (https://pypi.org/user/StephanSiemen/).

**Comment by ewdurbin** [comment]
Transfer complete.
