### ISSUE TITLE
PEP 541 Request: broker

### ISSUE THREAD

**Issue by JacobCallahan** [pypa/pypi-support#601]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/broker/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/jacobcallahan/

**Reasons for the request**
The project listed above has not been updated since 2011. Additionally, I cannot find either the source of the repository or the author's profile. However, our team has an identically named project that is actively developed and will be for the foreseeable future. Our team will also like this project to be pip installable to our 20+ members as well as numerous CI and automation systems.

**Maintenance or replacement?**
`Replacement:` https://github.com/SatelliteQE/broker

**Contact and additional research**
I am unable to find any active users with the name used in the pypi profile. There was a potential reference to this individual in a tweet, but that account no longer exists as far as I can tell.

**Comment by hugovk** [comment]
Looks like @zacharyvoase is the maintainer, perhaps Zachary would like to comment here?

There's also an email address on his GitHub profile, and possibly older ones at https://pypi.org/project/broker/#data and https://pypi.org/project/URLObject/#data

**Comment by JacobCallahan** [comment]
@hugovk thanks for finding that! I wasn't able to determine that just from his pypi username.

**Comment by JacobCallahan** [comment]
@zacharyvoase @hugovk I'm still interested in taking over this name :)

**Comment by jamadden** [comment]
@JacobCallahan Were you able to make contact with the project owner via email?

**Comment by jamadden** [comment]
I've emailed the verified email address PyPI has on file for the owner of the project, as well as the author email listed in the package (which bounced), and I'll again ping @zacharyvoase in hopes they'll get the notification. This starts the official six-week period of reachability attempts before we can determine the project to be abandoned.

**Comment by zacharyvoase** [comment]
Oh, I’m happy for you to take that project name! Is this GitHub comment sufficient to authorize this?

**Comment by jamadden** [comment]
Hi @zacharyvoase! Thanks for the response. 

Ideally, you would login to PyPI and add the requested user (`jacobcallahan`) as an owner of the project. At that point, they could then remove your account as an owner. Once that's done, @JacobCallahan could close this issue. In this way the audit log is clear, and it avoids the need to have an admin perform the same steps (which has to wait for an admin to have the time).

**Comment by JacobCallahan** [comment]
@zacharyvoase fantastic, thank you!! It is a great name :)
