### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by hdoupe** [pypa/pypi-support#602]
Request for account recovery.

## PyPI Username

comp-org

---

##  Reason for request

Reason: I don't recall setting up two factor auth, but when I tried to login today, pypi wouldn't let me sign in. I am the owner of the account and can prove that I have access to the email address associated with it.

**Comment by hdoupe** [comment]
Hi, I'm checking in here. I've *lost* access to my pypi packages. I can still upload packages but I cannot sign in. Please help.

**Comment by ewdurbin** [comment]
@hdoupe our records indicate that:

- TOTP 2FA was provisioned at `2019-09-09 19:55:32.40418`
- Recovery codes were generated at `2020-09-30 22:24:08.649077`

Which are all _after_ this issue was filed and that this account has been active on PyPI since.

It appears you resolved your issue.
