### ISSUE TITLE
PEP 541 Request: alice

### ISSUE THREAD

**Issue by geyang** [pypa/pypi-support#603]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/alice

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/episodeyang

**Reasons for the request**

The project contains 1 release from 2010 that does not appear to contain actual code. I have an opensource command line tool that is under active development, and will continue to be so for the foreseeable future. You can find this project here: https://github.com/geyang/alice

The intended use case for this library is to be used in conjunction with `Jaynes` and `ml-logger`, both modules have downloads in the quarter millions, so I expect this library to catch up soon enough as well.

**Maintenance or replacement?**

replacement, with an opensource project hosted here: https://github.com/geyang/alice

**Contact and additional research**

I have not managed to reach the original author.

**Comment by yeraydiazdiaz** [comment]
Hello @geyang, I can confirm this project has a single release with no associated files and is thus considered invalid. I will now attempt contact with the owner once and allow a courtesy period of one week before transferring the project.

**Comment by geyang** [comment]
Thank you!

**Comment by yeraydiazdiaz** [comment]
I have not heard back from the owner so I will now ask an admin to perform the transfer.

**Comment by geyang** [comment]
Thank you @yeraydiazdiaz!

I just tried to publish but it looks like I am still not allowed to upload to this project yet. 

I will wait for your confirmation of the complete of the transfer. Thank you!

**Comment by geyang** [comment]
@yeraydiazdiaz Thank you for your help with the package name! It has been almost a week, and it looks like the package name still has not been released. Should I keep waiting, or there are specific admins I can ping to get this resolved? Thanks!

My worry is  that once it is release I might miss the window to register for it, so I have been manually checking this everyday.

**Comment by yeraydiazdiaz** [comment]
Hi @geyang, the process is not to release the package name but to transfer it to you directly, so there's no chance of missing a window. However, it is an admin-only process and, as you know, it's purely a volunteer effort and there's [some backlog](https://github.com/pypa/pypi-support/projects/1#column-7602956).

Please be patient, I'm sure an admin will go over your request soon.

**Comment by geyang** [comment]
Thanks @yeraydiazdiaz !

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by geyang** [comment]
Thank you!
