### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kevinzakka** [pypa/pypi-support#606]
Request for account recovery.

## PyPI Username

`kevinzakka`

---

##  Reason for request

Reason:

2FA not working correctly (getting Invalid TOTP code)

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@kevinzakka do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: kevinzakka" to proceed

**Comment by kevinzakka** [comment]
Responded to the email, thank you!

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
