### ISSUE TITLE
PEP 541 Request: cs-storage and cs-kit

### ISSUE THREAD

**Issue by hdoupe** [pypa/pypi-support#607]
**Project to be claimed**

`PROJECT_NAME`: 
  - `cs-kit`: https://pypi.org/project/cs-kit 
  - `cs-storage`: https://pypi.org/project/cs-storage

**Your PyPI username**

`compute-studio`: https://pypi.org/user/compute-studio

**Reasons for the request**

I have lost access to my account. I got a new phone and lost the ability to sign in. See #602. I am good doing ownership transfer or account recovery--whatever is easiest for the PYPI team.

**Maintenance or replacement?**

- https://github.com/compute-tooling/compute-studio-kit
- https://github.com/compute-tooling/compute-studio-storage

**Contact and additional research**

I *am* the original owner--I just can't sign in.

**Comment by hdoupe** [comment]
Thank you so much in advance for your help!

**Comment by pradyunsg** [comment]
xref: #602

**Comment by hdoupe** [comment]
Thanks @pradyunsg. When convenient, please let me know what I can do to get this straightened up.

**Comment by hdoupe** [comment]
Hi @pradyunsg, I just wanted to follow up on this to see if there is anything I can do to help. I'm very motivated to get this account back. If you or anyone else has time to help out, I would greatly appreciate it.

**Comment by ewdurbin** [comment]
Given that you appareled to be in control of the `hdoupe` and `comp-org` accounts on PyPI, you should be able to resolve this. I see that collaboration has been updated on both these projects since (on 2020-09-30).

Please reopen if you still need assistance.
