### ISSUE TITLE
Need manual password/email reset

### ISSUE THREAD

**Issue by evilmrhenry** [pypa/pypi-support#61]
I no longer have access to my PyPI account, and need a manual fix.
Username: evilmrhenry
PyPI email evilmrhenry@emhsoft.net

I no longer have access to the email address on file. New email address is the same, but at emhsoft.com instead.

Let me know what proof you need; a quick look at those two websites should make things obvious, though.

**Comment by ewdurbin** [comment]
@evilmrhenry as both releases for the only project associated with your account (Endgame-Singularity) have URLs pointing to emhsoft.com, I've added evilmrhenry@emhsoft.com as an address on your account. You can now proceed with a password reset to regain access.
