### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tbetcke** [pypa/pypi-support#610]
Request for account recovery.

## PyPI Username

`tbetcke`

---

##  Reason for request

Reason:

A few months ago my telephone broke with 2FA app on it and I just noticed that I did not create recovery keys for PyPI. I would be grateful if you could reenable account access. My e-mail address has not changed.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
