### ISSUE TITLE
PEP 541 Request: DATAPY

### ISSUE THREAD

**Issue by xanderyzwich** [pypa/pypi-support#612]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/datapy

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/XanderYzWich

**Reasons for the request**

The project listed shows status as planning and has been held since 2014. I believe that this is either abandoned or squatting.

**Maintenance or replacement?**

The existing project does not seem to include any code. I can promise to include an extra bit of white space to be considered as the 'maintenance' if that is desirable, but I would prefer not.

**Contact and additional research**

I have performed searches on github and google and found nothing that appears to be related to this person or time frame.

**Comment by hugovk** [comment]
Clicking to the maintainer's page (https://pypi.org/user/rasbt/), we can see some other projects, including https://pypi.org/project/biopandas/ released last month, indicating the maintainer is also @rasbt on GitHub.

Would @rasbt like to comment here?

---

> **Maintenance or replacement?**
>
> The existing project does not seem to include any code. I can promise to include an extra bit of white space to be considered as the 'maintenance' if that is desirable, but I would prefer not.

Are you suggesting you have a replacement?

**Comment by xanderyzwich** [comment]
I have a light file based db that I would like to replace it with.

**Comment by jamadden** [comment]
The project `datapy` does not include any releases. That makes it an invalid project under the definition of PEP 541. Invalid projects are subject to removal or transfer at any time. 

The PyPI moderators like to give a one-week courtesy period for project maintainers (@rasbt) to correct the issue, or transfer the project themselves. If nothing is done by September 17th, the project will become subject to admin transfer.

**Comment by rasbt** [comment]
Hi all,

whoa, 2014, that seems like ages ago and I can't remember what I was thinking back then / what I had planned for this repo :P. I think it was the original name I had in mind for mlxtend (https://github.com/rasbt/mlxtend) but I don't know.

In any case, I deleted the repo from my PyPI account, @xanderyzwich , please feel free to use the "datapy" handle for your project!

Cheers,
Sebastian

**Comment by xanderyzwich** [comment]
Thanks @rasbt 
I've tried pushing again, but I suspect there may be some maintenance that has to happen overnight. I'll retry tomorrow.

**Comment by rasbt** [comment]
no problem. It seems deleted on my end, but yeah, maybe that change has to propagate through the different servers. Maybe the problem will solve itself by tomorrow.

**Comment by xanderyzwich** [comment]
@jamadden is there any other process that needs to happen before I will be allowed to upload my project?

**Comment by jamadden** [comment]
From the PyPI logs, it seems that the project has not actually been deleted. What happened was that its one release was removed, but that's not the same as actually deleting the project. @rasbt can you try deleting the entire project?

**Comment by jamadden** [comment]
> Should I submit a release to PyPI again, which might restore that page, and then delete the project?

If it doesn't show up for you at https://pypi.org/manage/projects/, then that seems like its worth a try. (If there's a better way, I'm not sure what it is. This isn't a workflow that I've ever really used.)

**Comment by rasbt** [comment]
Sounds good! I just pushed a new release and was then able to delete it. @xanderyzwich Can you give it another try?

![Screen Shot 2020-09-11 at 6 00 11 PM](https://user-images.githubusercontent.com/5618407/92979562-bc334f00-f458-11ea-9245-14caafb7fe96.png)

**Comment by xanderyzwich** [comment]
Thanks @rasbt and @jamadden 
I have uploaded my first alpha and https://pypi.org/project/datapy/ is showing my project information.
