### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ml394** [pypa/pypi-support#613]
Request for account recovery.

## PyPI Username

`ml394`

---

##  Reason for request

Reason:

The phone with my 2FA authentication app has broken and will not switch on. For some reason I had no recovery codes generated. Is there any way I can verify my identity in order to regain access to my account?

**Comment by ml394** [comment]
Anything I can do to help facilitate this account recovery? Thanks

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ml394** [comment]
@ewdurbin have replied via email with the relevant branch pushed. Thanks again for the assistance

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
