### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yozik04** [pypa/pypi-support#615]
Request for account recovery.

## PyPI Username

yozik04

##  Reason for request

**Reason:** Lost 2FA authentication app or security token.

Actually I do not remember configuring 2FA on PYPI. Did not found any emails regarding that as well.

Thank you in advance.

**Comment by ewdurbin** [comment]
2FA was provisioned at `2019-12-12 13:11:26.468239`. This is can't really be done on accident.

In order to complete recovery, I've contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by yozik04** [comment]
Thank you for replying. Done.

**Comment by ewdurbin** [comment]
Please read the email and perform all steps (including responding to the email).

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
