### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tao625** [pypa/pypi-support#616]
Request for account recovery.

## PyPI Username

`username`
RayVision
---

##  Reason for request

Reason:I got a new cell phone and lost it

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
@tao625 do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: RayVision" to proceed

**Comment by foxrenderfarm** [comment]
> @tao625 do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: RayVision" to proceed

I'm really sorry to see the message so late. The PyPI account still needs to be restored. The contents have been restored according to the requirements of the email

**Comment by tao625** [comment]
> @tao625 do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: RayVision" to proceed

I'm really sorry to see the message so late. The PyPI account still needs to be restored. The contents have been restored according to the requirements of the email

**Comment by tao625** [comment]
> @tao625 do you still want to attempt recovery of your PyPI account? Please see email with subject "PyPI Account Recovery Request: RayVision" to proceed

@ewdurbin I'm really sorry to see the message so late. The PyPI account still needs to be restored. The contents have been restored according to the requirements of the email

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
