### ISSUE TITLE
PEP 541 Request: cmdtools

### ISSUE THREAD

**Issue by axsk** [pypa/pypi-support#619]
**Project to be claimed**

`cmdtools`: https://pypi.org/project/cmdtools

**Your PyPI username**

`axsk`: https://pypi.org/user/axsk

**Reasons for the request**

The project is empty. It contains no code besides the setup.py for more then a year.
I believe it to be a deprecated stub for the same authors pacakge [`cmdargs`](https://github.com/Mister7F/cmdargs).

**Maintenance or replacement?**

I would like to replace the package with https://github.com/zib-cmd/cmdtools.

**Contact and additional research**

I wrote two mails to the package author without any response for four months now.
I also opened an issue to contact the author in the alleged sibling package `cmdargs`: https://github.com/Mister7F/cmdargs/issues/1 without any response.

**Comment by axsk** [comment]
I'm soon to publish a paper referencing my package and I would be glad if we could get it registered to pypi until then.
Could someone look into this please :)

The current project is still empty and theres still no answer from the author.

Thanks in advance.

**Comment by yeraydiazdiaz** [comment]
Hello @axsk, apologies for the delay. I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow a courtesy period of one week in case there's any allegations.

**Comment by yeraydiazdiaz** [comment]
Also tagging GitHub user @Mister7F as the project's homepage link points to his profile.

**Comment by yeraydiazdiaz** [comment]
I received no response so placing in the queue for admin transfers.

**Comment by axsk** [comment]
Kind bump :)

**Comment by ewdurbin** [comment]
Transfer complete.
