### ISSUE TITLE
My project cffi, existing since a long time on pypi.org, was taken and abandoned on test.pypi.org

### ISSUE THREAD

**Issue by arigo** [pypa/pypi-support#621]
**Project to be claimed**

`cffi`: https://test.pypi.org/project/cffi

**Your PyPI username**

`Armin.Rigo`: https://test.pypi.org/user/Armin.Rigo

**Reasons for the request**

I'm the project owner of https://pypi.org/project/cffi.  Now I'm trying to set up a test.pypi.org instance for the future release workflow.  However I find that this name on test.pypi.org is already taken.  It was apparently taken by someone who just used it to upload the current version of my own cffi project, at the time, and then abandoned.

**Maintenance or replacement?**

Given that it's currently containing an old version of cffi and I'll use it to upload and test new versions, I suppose I have to tick "maintenance".

**Contact and additional research**

I have no connection to the current owner, and I don't see his mail address anywhere on https://test.pypi.org/user/dxiri/, so I am having a hard time contacting him.  It seems he did the same thing with a few other projects too.

**Comment by hugovk** [comment]
Looks like @dxiri is the same person on GitHub (same name given at https://test.pypi.org/user/dxiri/ and https://github.com/dxiri/OAT).

There's also the same email at https://github.com/dxiri/OAT/blob/master/setup.py and (https://pypi.org/user/dxiri/ ->) https://pypi.org/project/open-answerx/

@dxiri Would you like to comment here? Thanks!

**Comment by dxiri** [comment]
Hi! I have no recollection of doing any of this but that is indeed me listed as a maintainer. Is there something you need me to do to remove myself as a maintainer and add @arigo ?

**Comment by hugovk** [comment]
Hi! Yes, it's usually quickest if you add @arigo first, and then remove yourself (or @arigo can remove you). Thank you!

**Comment by dxiri** [comment]
Done @arigo , I just sent you an invite to become owner, feel free to remove me after accepting!

**Comment by arigo** [comment]
Thank you!
