### ISSUE TITLE
Limit Request: Ray - 100 GB (total project size)

### ISSUE THREAD

**Issue by robertnishihara** [pypa/pypi-support#623]
Hi! I'd like to request an increase to our total project size limit. We're hitting the project total size limit for [Ray](https://github.com/ray-project/ray). See our [release history](https://pypi.org/project/ray/#history) on PyPI.

**Project**
The project is **Ray**.
https://pypi.org/project/ray

**Size of release/project**
Current size is 10GB, we'd like to request an increase to 100GB.

**Which indexes**
We primarily want to increase **PyPI**. Both would be good, but we can delete old releases from Test PyPI if necessary.

**Reasons for the request**
Ray is a library for parallel and distributed Python. It includes
- primitives for scaling Python applications across clusters
- an ecosystem of libraries targeting scalable machine learning (training, hyperparameter search, reinforcement learning, deploying ML models in production, etc)
- tools for launching clusters on any cloud provider (AWS, GCP, Azure, Kubernetes, etc)

We do monthly releases, and each release is is around 500MB-1GB currently, which is why we're running into the project size limits.

We expect to continue doing releases at least once per month. Counting all Python versions and OS versions, each release should be under 1GB, so we would likely use around 10GB/year. If we increase our release frequency, it could be as much as 25-50GB/year.
 

Thanks a lot for your help!

**Comment by di** [comment]
I've set the project size limit for `ray` to 100 GB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by yifeif** [comment]
Thank you so much @di :)

**Comment by pcmoritz** [comment]
Awesome, thanks for increasing the limit @di :)

**Comment by barakmich** [comment]
@di Thank you! Also, does this apply to `test.pypi.org` as well?

**Comment by di** [comment]
Sorry, it wasn't clear to me if you wanted it increased on TestPyPI or not. I've set the limit to 100 GB there as well.

**Comment by robertnishihara** [comment]
Thanks a lot @di!
