### ISSUE TITLE
PEP 541 Request: torchsparse

### ISSUE THREAD

**Issue by kentangSJTU** [pypa/pypi-support#625]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/torchsparse/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/kentang/

**Reasons for the request**

The project is an empty one and I'm maintaining the Github repository [torchsparse](https://github.com/mit-han-lab/torchsparse) that happens to share the same name as this project.

**Maintenance or replacement?**

I'll publish a different one: [torchsparse](https://github.com/mit-han-lab/torchsparse).

**Contact and additional research**

I failed to find E-mail address of the current owner. The Github account with the same name as the PyPI account doesn't belong to the PyPI project owner.

**Comment by jamadden** [comment]
Based on matching email addresses, I believe @willbengtson is the owner of the PyPI project `torchsparse`. Hopefully they'll see this notification and respond to this issue.

**Comment by willbengtson** [comment]
This project is a typosquat protection for torch-sparse. 

The project is not empty. Perhaps you namespace the project to something like mit-torch-sparse instead to prevent confusion and collision to an existing project.

**Comment by jamadden** [comment]
Note that ["PyPI does not permit typosquatting for any purpose"](https://github.com/pypa/pypi-support/issues/526#issuecomment-666661367). As such, this is an invalid project, subject to removal at any time. However, if the danger is considered very great, PyPI may take the additional step of permanently blocking the project name.

**Comment by willbengtson** [comment]
Note Donald and other maintainers are aware of my work and will be transferring the projects from me

**Comment by kentangSJTU** [comment]
Hi @jamadden,

Thanks a lot for dealing with this issue and inviting @willbengtson into discussion!

Hi @willbengtson,

I'm not sure who "Donald and other maintainers" refer to, would you mind kindly pointing it out? Also, I failed to find such a repository that is written in Python and has name "torch-sparse" on GitHub. Will it be possible for you to also pointing out the non-empty repo you mentioned previously? Thanks a lot!

**Comment by yeraydiazdiaz** [comment]
@kentangSJTU the repo for `torch-sparse` is https://github.com/rusty1s/pytorch_sparse as indicated in [its PyPI project page](https://pypi.org/project/torch-sparse/), as you can see it's maintained [fairly popular](https://pepy.tech/project/torch-sparse).

I think given how similar the names of the two projects are there would be quite a bit of confusion on the users on either side. if we were to proceed with this request. Personally I would suggest @kentangSJTU to consider a change of name.

**Comment by yeraydiazdiaz** [comment]
I'm temptatively closing this issue as contact has been made, feel free to reopen it if you need any further assistance.
