### ISSUE TITLE
PEP 541 Request: herbie (test.pypi)

### ISSUE THREAD

**Issue by ruimbribeiro** [pypa/pypi-support#626]
**Project to be claimed**

`herbie`: https://test.pypi.org/project/herbie/

**Your PyPI username**

`herbie`: https://test.pypi.org/user/herbie/

**Reasons for the request**

The project seems to be abandoned -  returning 404 (https://github.com/nickpeck/herbie)

We are using the same project name in the live Pypi (https://pypi.org/project/herbie/).

**Maintenance or replacement?**

We'll publish a new one (https://github.com/herbie/herbie).

**Contact and additional research**

Could not contact the owner as there is no email address provided in the Package Profile page (https://test.pypi.org/project/herbie/)

Pinging @nickpeck

**Comment by nickpeck** [comment]
Hi there, project is indeed no longer active - I'm happy for you to claim the name.
I've gone ahead and deleted the project from test.pypi so hopefully it should be free now.
Let me know if you have any trouble.

**Comment by ruimbribeiro** [comment]
Thanks a lot, closing this issue :+1:
