### ISSUE TITLE
Limit Request: casatools - 250 MB

### ISSUE THREAD

**Issue by vsuorant** [pypa/pypi-support#627]
**Project**

https://pypi.org/project/casatools/

**Size of release/project**

**Which indexes**

PyPI
**Reasons for the request**

The original size estimate for this project was based on "linux_x86_64" type wheel. Converting that wheel to "manylinux2010_x86_64" compatible wheel pushed the size to 197M. I would like to have the limit increased to 250MB which hopefully should suffice for the foreseeable future. My apologies for the oversight and thank you for your good work.

**Comment by di** [comment]
I've set the upload limit for `casatools` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.

And thanks for making manylinux releases! (manylinux2014 is now available, by the way: https://www.python.org/dev/peps/pep-0599/)
