### ISSUE TITLE
PEP 541 Request: tods

### ISSUE THREAD

**Issue by lhenry15** [pypa/pypi-support#629]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/tods

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/lhenry15

**Reasons for the request**
 The name has been abandoned by myself, but I want to reuse the name "tods".

**Maintenance or replacement?**

**Contact and additional research**

I am the owner.

**Comment by jamadden** [comment]
The project appears to have been deleted by the user `ihenry15` (the user mentioned here). If you upload a new distribution for that project you should be able to (re)claim it.

Note that you won't be able to re-use any version numbers that were previously used. You'll have to use something besides `0.0.1`.
