### ISSUE TITLE
Limit Request: awkward1 - 257 MB

### ISSUE THREAD

**Issue by jpivarski** [pypa/pypi-support#630]
**Project name:** awkward1

**Project URL:** https://pypi.org/project/awkward1/

**Size of release/project:** 257 MB

**Which indexes:** just PyPI

**Reasons for the request:**

This Python library has a compiled component. It does not statically link against any large libraries—it only has two header-only C++ dependencies—but the library contains a lot of templates that need to be instantiated to be able to handle any numerical type at runtime in Python. Also because it is compiled, there's a large matrix of Python versions and operating systems to provide as wheels.

This library is in active use by a scientific community that needs fast turn-around for bug-fixes, such as every few days. This, combined with the large size of a single release, means that the total release size easily reaches 10 GB.

I already deleted a lot of early releases a few months ago, keeping only minor version updates (e.g. 0.1 to 0.2) and one release per month. Just today, when I hit the limit again, I deleted releases up to but not including the first release I have pinned on a [tutorial for scientific users](https://github.com/jpivarski-talks/2020-04-08-eic-jlab/blob/master/2020-04-08-eic-jlab-EVALUATED.ipynb). If I cut further into the 2020 releases, I'm going to be taking away some releases that scientists depend on for reproducibility.

On my side, I can relieve the pressure by introducing more structure into the release process, calling the quick turn-around releases "alpha" and not guaranteeing their longevity. But it would also help if I could get a higher limit.

Another thing that's going to complicate this is that I'll soon be moving the [awkward1](https://pypi.org/project/awkward1/) package into the name [awkward](https://pypi.org/project/awkward/) (as version 1.0) and the old awkward will become awkward0. After that point, it's the "awkward" package that will need the higher limit, rather than "awkward1".

Thanks!

**Comment by jpivarski** [comment]
Oh, and it's not likely to increase in size much. The biggest change is adding new Python releases (3.9 on Linux, I'll be adding it to MacOS and Windows soon) and new hand-written code, but that's a slow way for a package to grow.

**Comment by jpivarski** [comment]
I found the place where I can count deleted releases. Since the project began (Aug 16, 2019), I've manually deleted 191 releases, leaving 43 (i.e. total without deletion is 191 + 43 = 234).

31 of those 43 were released after the point when this project "went public:" version 0.2.10 was pinned in the first tutorial for users. And they're using it:

![](https://raw.githubusercontent.com/jpivarski-talks/2020-10-26-as-blueprint-uproot-awkward/main/pip-github-anyone-awkward-uproot.svg)

The orange line is this package; top plot is number of `pip install`s per month, bottom plot is number of new Python/Jupyter files in GitHub per month matching the search string `import awkward1`. The above-mentioned tutorial was presented April 8, 2020, just before uses of `import awkward1` began to climb, now more frequent than `import awkward`.

This is what's motivating the transition of `awkward1` → `awkward` and `awkward` → `awkward0`. Pretty soon (deadline of December 1), these 257 MB releases will be going into the `awkward` package. (`awkward0` will always be small.)

**Comment by jpivarski** [comment]
I just deleted 8 more releases, _hoping_ that nobody needed them. (They're from April 2020, where you can see from the orange line that adoption was low.)

**Comment by di** [comment]
I've set the upload limit for `awkward1` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by jpivarski** [comment]
Thank you, but it wasn't the "project upload limit" (200 MiB → 300 MiB) that was the problem. (I was always under that and not likely to grow into it.) It was the "project total size limit" (10 GiB, unchanged). I think I know what the confusion was: each of these wheels is 5-10 MiB, but there are 37 wheels (and I haven't included PyPy yet).

As described above, this codebase is moving from the PyPI name `awkward1` to `awkward`. The date for that transition had been nebulously set at "the end of this year," but now it's concrete: I'm moving **next Monday** (November 30, 2020). This move is not motivated by PyPI quotas—it was planned from the beginning that this large change in interface would have a transition period lasting for most of 2020 (April to November, as it turns out).

So now the relevant PyPI name is `awkward`: could the "Project total size limit" for [awkward](https://pypi.org/project/awkward/) (currently 10 GiB, with 37.2 MiB full) be increased in anticipation of these large wheels being deployed there? Would 100 GiB be unreasonable?

Regardless, I'm planning a new release strategy in the new year: I'll still be responding quickly to user requests with frequent releases, but they'll be labeled as "release candidates" with non-RC releases once a month. Then the previous RC releases will be deleted. That way, I can be responsive but also slow down the rate of filling up PyPI.

Thanks again!
