### ISSUE TITLE
PEP 541 Request: DIRAC

### ISSUE THREAD

**Issue by chrisburr** [pypa/pypi-support#633]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/dirac

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/chrisburr

**Reasons for the request**

[DIRAC](https://github.com/DIRACGrid/DIRAC/#dirac) is a software framework for managing [distributed computing resources](https://en.wikipedia.org/wiki/Grid_computing). It is used many communities including [LHCb](https://lhcb-public.web.cern.ch/), [Belle 2](https://www.belle2.org/), [Juno](http://juno.ihep.cas.cn/), [EGI](https://www.egi.eu/), [GridPP](https://en.wikipedia.org/wiki/GridPP), [France Grilles](http://www.france-grilles.fr/home/) and others. I am one of the core developers of DIRAC and a member of the LHCb experiment.

Historically DIRAC releases have been distributed as tarballs containing a full Python installation and all of DIRAC's dependencies. We would like to move to also providing more conventional distribution methods (i.e. PyPI).

While the main page returns 404, I see this error when trying to claim it:

```python
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'chrisburr' isn't allowed to upload to project 'dirac'. See https://pypi.org/help/#project-name for more information.
```

Trying to access the management page I get a forbidden error instead of the "not found" message that an actually unregistered name returns so it appears something is there.

I have been able to successfully claim `dirac` on the PyPI test instance: https://test.pypi.org/project/DIRAC/7.2rc14/

**Maintenance or replacement?**

No package is currently available from PyPI so this doesn't appear to apply.

**Contact and additional research**

As the PyPI is currently empty it's hard to establish who controls it. I have tried to find the current owner of `dirac` on PyPI by:
* Searching for other Python projects named `dirac` which might have registered the name on PyPI
* Asked other DIRAC developers if they're aware of someone having tried to make releases to PyPI
* Checked archive.org for any copies of releases that may have existed in the past

I'm happy to contact the current owner if PyPI support is able to tell me who currently controls the `dirac` name.

Thank you in advance for the help and all of the time you invest in the Python ecosystem.

**Comment by jamadden** [comment]
That project existed, but all releases were removed in 2018. As such, it is an invalid project subject to transfer. PyPA policy is to attempt to contact the previous owner and allow a one-week courtesy window before transferring such projects. I've emailed the address PyPI has on file and notified them that the project can be transferred after September 29th.

**Comment by jamadden** [comment]
The owner of the email address replied directly to me: 

```
From: David Wilson <….@botanicus.net>
Date: Tue, 22 Sep 2020 11:37:14 +0100
Message-ID: <CABzuZRP-J2Q1kv5wtgMekLZjTr-os4_s2JS8T9QMQpiUUyxJoA@mail.gmail.com>
Subject: Re: PyPI project 'dirac': PEP541 Name Transfer
To: Jason Madden <...@nextthought.com>
Content-Type: multipart/alternative; boundary="000000000000c3a9b405afe48ea3"

--000000000000c3a9b405afe48ea3
Content-Type: text/plain; charset="UTF-8"

That's fine. It was one alternative name for a project that never got
released. All the best

```

**Comment by chrisburr** [comment]
Excellent, thanks for handling this promptly (and thanks to David for replying quickly as well).

**Comment by dw** [comment]
I sent you an owner invite in case it speeds things along. Feel free to remove me after accepting the invite.

**Comment by chrisburr** [comment]
Thank you very much @dw, I was just in the process of drafting a message for you to save the PyPI admins needing to get involved.

As this is now resolved I'll close.
