### ISSUE TITLE
PEP 541 Request: openvino

### ISSUE THREAD

**Issue by mryzhov** [pypa/pypi-support#636]
**Project to be claimed**

`openvino`: https://pypi.org/project/openvino

**Your PyPI username**

`openvino_pushbot`: https://pypi.org/user/openvino_pushbot

**Reasons for the request**

The requested project is invalid and doesn't contain any real packages. Looks like the project is name squatting. 

**Maintenance or replacement?**

I would like to use this project to upload official openvino package (https://github.com/openvinotoolkit/openvino)
For now, we will use openvino-python name (https://test.pypi.org/project/openvino-python)

**Contact and additional research**

I tried to contact the owners by mail (others@WTF.com) but this is a fake mailbox and I got a confirmation that this mailbox doesn't exist:

_The following message to <others@wtf.com> was undeliverable.
The reason for the problem:
5.1.0 - Unknown address error 550-"5.1.1 The email account that you tried to reach does not exist. Please try\n5.1.1 double-checking the recipient's email address for typos or\n5.1.1 unnecessary spaces. Learn more at\n5.1.1  https://support.google.com/mail/?p=NoSuchUser o36si1844686pgb.481 - gsmtp"_

**Comment by hugovk** [comment]
Their other projects look a bit squatty too:

![image](https://user-images.githubusercontent.com/1324225/94122670-854b3900-fe5b-11ea-877d-bd91c4728faf.png)

**Comment by jamadden** [comment]
I concur that the project is invalid under the PEP 541 rules. I've emailed the owner account's verified email address and informed them of this fact; the PyPI moderators allow one week before removing or transferring invalid projects, so this project will be subject to transfer on or after October 2nd.

**Comment by mryzhov** [comment]
Hi, do you have any updates? Is it possible to start transferring the project?

**Comment by moslex** [comment]
Hello, @jamadden and @hugovk 
Could you please help us with project transferring?

**Comment by jamadden** [comment]
The project has been marked for transferring. I don't know when the admins will find time to do so; it may take quite awhile.

**Comment by ewdurbin** [comment]
Transfer complete.
