### ISSUE TITLE
403 Forbidden when trying to upload a package

### ISSUE THREAD

**Issue by shreyansh-kushwaha** [pypa/pypi-support#637]
I want to publish a python package to pypi.org so i created a pypi.org account and when i try to pub lish it and i am getting a error 403 forbidden and then  i search for this error on google i got an result telling to make a new account and then i deleted the previous account.. after that i when i am trying to create a different account (with another email) i am continuously 429 requests error what should i do??

**Comment by ewjoachim** [comment]
Hello,

- 403 forbidden can mean a **lot** of things, and there's really not a lot of cases where you have to delete your account.
- HTTP 429 means "Too many requests" and it's likely that you tried to login so many times in a small time window that the system identified you as trying to bruteforce your way through authentication. Please wait a few hours and try again. Also, if you receive a 403, don't retry multiple times in the hope that it will work at some point: there must have been something wrong in the request.
- Have you tried our [documentation](https://packaging.python.org/guides/distributing-packages-using-setuptools/#uploading-your-project-to-pypi) ? Was there any point that didn't work for you before the 403 ? Have you tried resetting your password to make sure you type it correctly ? Are you sure that the package you're trying to upload is new, or if it is an existing package, that you have upload permissions on it ? What tool are you using ? ...

It's much easier to guide you if you can provide specifics (like the commands you typed, the full responses you got, etc)

**Comment by shreyansh-kushwaha** [comment]
i was trying to upload the package through twine

**Comment by ewjoachim** [comment]
So at this point, all I know is that:
- you're using twine
- you received an HTTP 403

I hope you understand that it's very hard to help you troubleshoot the issue based on this information only :)
Please state:
- the name of the package you're uploading
- the commands you typed and the full responses you got
- your pypi username
- whether you have tried to reset the password
- whether there was anything unclear in the documentation

**Comment by shreyansh-kushwaha** [comment]
yeah it worked thanks
