### ISSUE TITLE
PEP 541: Transfer ownership of unused `reuse`

### ISSUE THREAD

**Issue by carmenbianca** [pypa/pypi-support#64]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/reuse

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/carmenbianca

**Reasons for the request**

The `reuse` package is not used by anybody at all, but I am unable to use the package namespace myself:

```
HTTPError: 403 Client Error: The credential associated with user 'carmenbianca' isn't allowed to upload to project 'reuse'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

I use [fsfe-reuse](https://pypi.org/project/fsfe-reuse) instead, but I'd ideally be able to use `reuse`.

**Contact and additional research**

It is impossible to contact the owner myself, because there does not appear to be an owner.

Related to https://github.com/fsfe/reuse-tool/issues/75

**Comment by yeraydiazdiaz** [comment]
Hello @carmenbianca, I can confirm the project has no releases and is therefore name squatting. I've contacted an admin to perform the transfer.

**Comment by ewdurbin** [comment]
transfer complete.
