### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by americanhanko** [pypa/pypi-support#640]
Request for account recovery.

## PyPI Username

`erichanko`

---

##  Reason for request

- Lost access to email address

Reason:

I believe I created my PyPI account while I was working at Microsoft, so it should be associated with `v-erhank` at `microsoft.com`. Could we reassociate the account with `eric.hanko1` at `gmail.com`?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, if that bounces or no response is heard after at least 7 days, we will proceed with recovery.

**Comment by ewdurbin** [comment]
I received a bounce from the primary email address on the account.

@americanhanko please email support@pypi.org with the address you'd like associated with the account.

**Comment by ewdurbin** [comment]
email address associated with the user has been updated as requested. you can recover access to your account by proceeding with a standard password reset.

**Comment by americanhanko** [comment]
Thanks!
