### ISSUE TITLE
PEP 541 Request: tin

### ISSUE THREAD

**Issue by rileyhales** [pypa/pypi-support#642]
**Project to be claimed**

`tin`: https://pypi.org/project/tin

**Your PyPI username**

`rileyhales`: https://pypi.org/user/rileyhales

**Reasons for the request**

I believe the `tin` project is an invalid project because it is name squatting, based on the definition in https://www.python.org/dev/peps/pep-0541/#invalid-projects

The project has no content and was created 4.5 years ago according to the listed github repository (https://github.com/ahlfors/tin). 4 of the 5 projects owned by the project's pypi user are name squatting and look like they were automatically generated. The repositories each contain only 1 commit with a readme file that contains the repository name only. They contain the exact same version number and project description, were created about the same time, and are not installable as they contain no code.

**Maintenance or replacement?**

I intend to replace a pypi project i currently develop (https://github.com/rileyhales/geomatics) with the name tin. This is in conjunction with an academic paper publication. Geomatics no longer accurately describes the purpose of the code and tin, short for temporal informatics, is the subject of the pending journal article.

**Contact and additional research**

I have emailed the maintainer with no response. I also more recently also opened an issue on the github repo listed as the home for the project (https://github.com/ahlfors/tin/issues/1).

**Comment by yeraydiazdiaz** [comment]
Hello @rileyhales, I can confirm the project has a single release with no associated files and is therefore considered invalid.

I will attempt contact with @ahlfors and allow a one week courtesy period before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
I have not received any response from the owner, queuing for admin transfer.

**Comment by rileyhales** [comment]
Thank you!

**Comment by ewdurbin** [comment]
Transfer complete.
