### ISSUE TITLE
PEP 541 Request: Lumen

### ISSUE THREAD

**Issue by philippjfr** [pypa/pypi-support#643]
**Project to be claimed**
`Lumen`: https://pypi.org/project/lumen/

**Your PyPI username**
`pyviz`: https://pypi.org/user/pyviz

**Reasons for the request**
There was never a projected created under this name, it was created as a placeholder for a project that never seems to have come to fruition.

**Maintenance or replacement?**

We are planning on renaming our monitoring project to Lumen and therefore replace the (non-existent) project with this repo:

https://github.com/holoviz/monitor

**Contact and additional research**
The user who created it @gmflanagan does not appear active on GitHub and most of his projects have been abandoned. He can't be DMed on Twitter either.

**Comment by pradyunsg** [comment]
I've gone ahead and reached out to the user, over the private email available on PyPI.

As it stands, this project definitely counts as an invalid project, and will be eligible for transfer in 1 week (we try to have a courtesy period after the first contact by PyPI folks, for invalid projects, even though it's not _required_ per se).

If I don't get report back in the next 10 days, @ me and that'll make it much more likely that I see this in the trashfire that is my GitHub notifications. :)

**Comment by philippjfr** [comment]
Thanks @pradyunsg, I know this is probably a thankless job, so this is massively appreciated.

**Comment by averagehuman** [comment]
Hi @pradyunsg @philippjfr , I appreciate the courtesy mail.

Yes, I own that pypi username and project. There was actually code written and intended to be 'lumen', but it never came to anything very important. Mea culpa for not releasing it. In any case, I've deleted the project now and you are free to use it.

**Comment by philippjfr** [comment]
Thanks @averagehuman! Just uploaded a dev release.
