### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by yangwu91** [pypa/pypi-support#645]
Request for account recovery.

## PyPI Username

`yangwu91`

---

##  Reason for request

Reason:
I lost 2FA authentication app since I reset my phone. Although it has been backed up on iCloud, I couldn't recover it somehow. Would you mind to reset 2FA of my PyPI account, as well as my TestPyPI account please? Thanks!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
