### ISSUE TITLE
PEP 541 Request: Dragon

### ISSUE THREAD

**Issue by KritantaDev** [pypa/pypi-support#648]
**Project to be claimed**
`Dragon`: https://pypi.org/project/Dragon

**Your PyPI username**
`krit`: https://pypi.org/user/krit

**Reasons for the request**
The project appears to satisfy all requirements for abandonment or name squatting:

* Attempts to contact the listed email address have been unsuccessful
* The project is not used by any other project. A C++ RPG game and its forks appears to have been false flagged as depending upon it.
* The project seems to have no clear functionality. This may be a misunderstanding due to it also having no description or documentation.

**Maintenance or replacement?**
As I’m unsure of the intended functionality, and no projects depend on this one, I don’t intend to continue maintenance.

I have been looking into moving my fairly large development toolkit (https://github.com/DragonBuild/DragonBuild) to distribution via PyPi. I have avoided migration while attempting to contact the owner of this project to avoid confusing users about the package name.

Due to how long 541 requests can take, I may end up listing it and will update this issue accordingly if so.

The “DragonBuild” project is commonly branded and referred to as “dragon”, and as such, a package name consistant with the name of the script is desirable for simplicity.

**Contact and additional research**
I’ve tracked down the developer’s apparently inactive github account here: https://github.com/ofersadan85

I haven’t been able to find any other accounts ı can be even close to sure belong to them.

I’ve sent 3 emails over the past 4 months regarding the topic and haven’t heard any response thus far, unfortunately.

**Comment by yeraydiazdiaz** [comment]
Hello @KritantaDev, it seems the project has _some_ functionality and [a few downloads](https://pepy.tech/project/dragon). We usually err on the side of caution in cases of full replacement of the project since it can cause unexpected breakages on downstream users.

I'm closing this issue but tagging @ofersadan85, who seems more active recently, in case he's willing to give up the project voluntarily.

**Comment by KritantaDev** [comment]
Man, forgot I filed this issue; I did get in touch with them and they did agree to hand over the project name, but unfortunately, that was the last I've heard from them, so 😛

**Comment by ofersadan85** [comment]
@KritantaDev hi, like @yeraydiazdiaz  said i'm a bit more active now, i'll reply to the email you send me and we'll continue the discussion there

**Comment by ofersadan85** [comment]
I replied to kritantadevelopment@gmail.com, hopefully that's still your address, if not feel free to send me a new message at ofersadan85@gmail.com

**Comment by KritantaDev** [comment]
@yeraydiazdiaz We've gotten it transfered over, so this issue is definitely resolved;

However, is there any way for me to modify the capitalization of the project? Not horribly excited to risk the name getting sniped by deleting and recreating. Desired capitalizaiton is all lowercase `dragon`

**Comment by KritantaDev** [comment]
Turns out modifying the package itself was enough to change that, so this is entirely resolved, thanks all of you and have a wonderful day.
