### ISSUE TITLE
PEP 541 Request: rpl

### ISSUE THREAD

**Issue by rrthomas** [pypa/pypi-support#649]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/rpl

Apologies if I have misunderstood, but having successfully uploaded a test to test.pypi.org, I got the error:

```
HTTPError: 400 Client Error: The name 'rpl' isn't allowed. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

I read the URL given, and I can't see another project of this name, or a standard Python library, and the name doesn't appear to be confusing/malicious. The project has existed for many years (since 2006), but has not been uploaded to PyPI before as far as I can see.

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/rrt

**Reasons for the request**
This project does not appear to exist.

**Contact and additional research**
I have searched PyPI for this project and not found it, and successfully uploaded it to test.pypi.org.

**Comment by hugovk** [comment]
[Searching this repo](https://github.com/pypa/pypi-support/search?q=rpl+is%3Aissue&type=Issues) points to https://github.com/pypa/pypi-support/issues/355, showing `rpl` is a namesquatted Fedora package.

Click "Details" on the first post there to see the full list.

**Comment by rrthomas** [comment]
Thanks, @hugovk. I am indeed the upstream maintainer of this package, which is under the same name in Debian. So, what do I do?

**Comment by hugovk** [comment]
@encukou wrote at https://github.com/pypa/pypi-support/issues/355#issuecomment-655738640:

> These names are reserved mainly to prevent people from accidentally picking a name that is already used in Fedora.
> 
> If you maintain a long-standing project whose name was reserved for Fedora, and want to upload it to PyPI, please let me (or the PyPI admins) know so it can be unblocked for you.

**Comment by rrthomas** [comment]
OK, so does this issue let the PyPI admins know? Or do I need to contact @encukou specifically?

**Comment by encukou** [comment]
This issue lets them know but they'll ask me to confirm your connecrion to the project. I'll do that later today when I'm at a computer; sorry for the delay

On October 5, 2020 2:45:06 PM GMT+02:00, Reuben Thomas <notifications@github.com> wrote:
>OK, so does this issue let the PyPI admins know? Or do I need to
>contact @encukou specifically?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pypa/pypi-support/issues/649#issuecomment-703607453

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by encukou** [comment]
Dear admins, please release the name so @rrthomas can claim it.
The Debian package is indeed @rrthomas' fork, and looks well maintained.

**Comment by rrthomas** [comment]
I haven't had any other sort of notification, so I guess I'll hear here when the name has been released?

**Comment by rrthomas** [comment]
If you'd prefer to tell me privately, or release it directly to my PyPI account, feel free to contact me privately (various options in my GitHub profile).

**Comment by rrthomas** [comment]
Ping? Sorry to ask, I don't really mind how long it takes, I'd just like to know how long to expect, if that's possible! TIA!

**Comment by rrthomas** [comment]
Ping again? How long does an admin transfer take?

**Comment by mustafaquraish** [comment]
@rrthomas I've been waiting since June. There's some pending since May. I don't suspect it will be anytime soon.

**Comment by rrthomas** [comment]
Thanks, @mustafaquraish. Any ideas on people to prod? This namesquatting by Fedora is fine in principle, but not if it takes 6 months or more to perform transfers.

**Comment by mustafaquraish** [comment]
@rrthomas You might want to give this thread a look: #679

**Comment by di** [comment]
I've removed the project from the blocklist.

@encukou, please @-mention me in the future with regards to these Fedora package names, thanks!

**Comment by rrthomas** [comment]
Many thanks, @di!
