### ISSUE TITLE
PEP 541 Request: z

### ISSUE THREAD

**Issue by gastrodon** [pypa/pypi-support#650]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/z

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/basswaver

**Reasons for the request**

The pypi project `z` appears to have not been updated since `Jan 20 2015`, which is closing in on 6 years ago

**Maintenance or replacement?**

I would like to occupy the namespace with my own project, which will also go by `z`

https://github.com/gastrodon/z

**Contact and additional research**

I cannot find any contact information for either of the listed maintainers. The project itself does not appear to have any contact links

**Comment by hugovk** [comment]
By checking the maintainers' other projects and clicking through to GitHub, looks like @pyq-enlnt / @enlnt are the owners. Ping!

**Comment by gastrodon** [comment]
It looks like @pyq-enlint is an org that has been inactive, so hopefully @enlnt has something to say

**Comment by gastrodon** [comment]
@hugovk What sort of timeline might I look forward to if either of these maintainers do not respond?

**Comment by hugovk** [comment]
Check the PEP:

https://www.python.org/dev/peps/pep-0541/#abandoned-projects

It specifies a 6 week period over which PyPI maintainers try and make contact. Hopefully a maintainer can take a look soon.

**Comment by gastrodon** [comment]
Hi @hugovk, per your last comment it's been about 6 weeks. Any update on this?

**Comment by hugovk** [comment]
Hello, I'm not a maintainer/admin here, just trying to help out by sharing some info.

Hopefully one will check here soon, but they're currently very busy so it may take some time longer. See also https://github.com/pypa/pypi-support/issues/679.

**Comment by gastrodon** [comment]
I see, I had seen that you'd committed to this repo and thought that you were a maintainer. Thanks for the help, I'll wait on a maintainer to get to this.

**Comment by yeraydiazdiaz** [comment]
Hello @gastrodon, I can confirm the project has a single release with no associated files and is therefore considered invalid.

I will attempt contact with the owner informing them of this fact and allow one week for them to reply, otherwise we will proceed with the transfer.

**Comment by gastrodon** [comment]
Hello, Thanks for the update

**Comment by sashkab** [comment]
Please go ahead and release this project to the new owner.

Thanks.

**Comment by yeraydiazdiaz** [comment]
Hi @sashkab, thanks for you reply, and you're correct, it's best to allow us to transfer the project rather than deleting it.

I'll ask an admin to perform the transfer now.

**Comment by gastrodon** [comment]
Hey, any progress here?

**Comment by ewdurbin** [comment]
Transfer complete.
