### ISSUE TITLE
PEP 541 Request: river

### ISSUE THREAD

**Issue by MaxHalford** [pypa/pypi-support#651]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/river/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/MaxHalford/

**Reasons for the request**

The project is essentially empty has not been updated since 2013. It seems pretty much dead if I may say so.

**Maintenance or replacement?**

This is a replacement. I expect the new package to have a fair amount of visibility and impact in the machine learning community.

**Contact and additional research**

I would love to contact the user, but there is absolutely no contact information.

**Comment by jacobmontiel** [comment]
Pinging @pradyunsg who has participated in other `PEP 541` issues.

I am part of the team working with @MaxHalford.

**Comment by MaxHalford** [comment]
@ewjoachim friendly ping to see if you can help out :). Note that our [package](https://github.com/online-ml/river/) is ready to be published.

**Comment by ewjoachim** [comment]
Sorry, I do speak from times to times on PEP 541 issues, but I'm quite new as moderator, and not really sure what needs to be done...

**Comment by MaxHalford** [comment]
No worries! We're pretty sure we have a strong case. We appreciate any time you can put into this whatsoever.

**Comment by jacobmontiel** [comment]
For context, we have a package named [river](https://github.com/online-ml/river/). The first release ready and we would like to use the same name in PIP for consistency.

On our side, there is no much else that we can do. There is no way to contact the owner of the package "frpm". I searched in GitHub but only found [one profile](https://github.com/frpm) (seems abandoned) from 2015, but the package in PIP appeared in 2013.

Any help is more than welcomed.

**Comment by smastelini** [comment]
Hi everyone. Are there any updates on the status of our claim? I am also part of the team working on `river`.

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay. I can confirm the `river` project has a single release with no associated files, as such it is considered invalid and subject to transfer.

In these situations moderators attempt contact with the owner and allow a courtesy period of one week before transferring the project.

**Comment by yeraydiazdiaz** [comment]
I have not received any response so I will now ask an admin to perform the transfer.

**Comment by DPaletti** [comment]
Any updates on this? In order to use river with poetry without build headaches I would really need for this package to be published on pypi. Thanks in advance.

**Comment by smastelini** [comment]
Hi @yeraydiazdiaz, thanks for the feedback. Do you have any feedback about the transfer?

**Comment by MaxHalford** [comment]
Friendly ping to remind any PyPI admin to look at this.

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by MaxHalford** [comment]
Thanks you rock!
