### ISSUE TITLE
PEP 541 Request: Enrich

### ISSUE THREAD

**Issue by ssbarnea** [pypa/pypi-support#653]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/Enrich/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/ssbarnea
**Reasons for the request**

**Maintenance or replacement?**
The purpose is **replament**.

**Contact and additional research**

I already sent an email to DouglasFowler which is registered owner of the package but I was not able to identify if he has a github account.

**Comment by hugovk** [comment]
(Should the issue title read: "PEP 541 Request: Enrich"?)

**Comment by hugovk** [comment]
> `PROJECT_NAME`: [pypi.org/project/Enrich](https://pypi.org/project/Enrich/)

links to https://depts.washington.edu/sfields/software/enrich/ which has:

> Enrich has been replaced by Enrich2 so this software is no longer supported.
> [Download Enrich2](https://github.com/FowlerLab/Enrich2/releases/latest) from GitHub or read the Enrich2 manuscript in Genome Biology.

which links to:

https://github.com/FowlerLab/Enrich2/releases/tag/v1.3.1

Ping @FowlerLab @fowlerlab1 @afrubin @conorcamplisson

**Comment by dougfowler42** [comment]
We are no longer using the Enrich pypi name.  It can be recycled for a new use.

**Comment by jamadden** [comment]
@dougfowler42 Thank you for your response. The fastest way to enable that to happen would be for an owner of the project on PyPI to either delete it, or grant "owner" access to the PyPI user requested in this issue ("ssbarnea"). Otherwise, an administrator will have to perform the transfer, which can take some time.

**Comment by ssbarnea** [comment]
@dougfowler42 that is very easy, just go to https://pypi.org/project/Enrich/ login, press manage button and add me (ssbarnea) as owner.

And again, thanks for the help. If you no longer have access to your pypi account (like lost password combined with lost access to original email), mention it here, the admins will understand.

**Comment by dougfowler42** [comment]
Hi,

Done.  Sorry for the delay - busy week.

Doug

**Comment by ssbarnea** [comment]
Thanks!
