### ISSUE TITLE
PEP 541 Request: ssf

### ISSUE THREAD

**Issue by snoopyjc** [pypa/pypi-support#655]
**Project to be claimed**

`ssf`: https://pypi.org/project/ssf

**Your PyPI username**

`snoopyjc`: https://pypi.org/user/snoopyjc

**Reasons for the request**

Their project was never started.  I have a project ready to deploy, which is a port of ssf.js (SpreadSheet Format) to python.  I'd like to please use the same name as is used in the js version.

**Maintenance or replacement?**

Replacement, which I plan to maintain. Ref: https://github.com/snoopyjc/ssf

**Contact and additional research**

Sent email - no response!

**Comment by snoopyjc** [comment]
Sent the author an additional email - no response!

**Comment by jkyeung** [comment]
This would be a great boon to the Python Excel community! I hope the powers that be let your project use this name on PyPI.

**Comment by snoopyjc** [comment]
Just heard from him - related issue: https://github.com/pypa/pypi-support/issues/698

**Comment by yeraydiazdiaz** [comment]
Closing as it seems the transfer was completed.
