### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by GwendalRaoul** [pypa/pypi-support#657]
Request for account recovery.

## PyPI Username

`Wirepas`

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:

It was setup by an employee that left the company and the recovery codes were probably lost at that time.
We still have access to our registered address 'opensource@wirepas.com'

We received the email to reset the password but don't have the authentication code to validate it.

Could you help us to recover it?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
