### ISSUE TITLE
Issue: PEP 541 Request: mda

### ISSUE THREAD

**Issue by lingfeiwang** [pypa/pypi-support#658]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/mda

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/LingfeiWang

**Reasons for the request**

The project is invalid: project is name squatting (package has no functionality or is empty)

**Maintenance or replacement?**

I would like to replace it with a different package: "Maximal Discriminating Axes" (MDA). It has been published on github at https://github.com/lingfeiwang/mda and zenodo. Its companion journal publication will appear soon.

**Contact and additional research**

I could reach the contact author today by email (the only contact provided). The author replied promptly but refused to transfer without giving a reason. Based on my understanding of PEP541, the project remains invalid (name squatting) for over a year and at the time of writing and therefore should be transferred anyway.

**Comment by yeraydiazdiaz** [comment]
Hi @lingfeiwang, I can confirm the project has a single release with no files associated with it and is thus considered invalid.

I will attempt contact with the owner and allow a one week courtesy period before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
The owner responded saying they had forgotten to push the project to PyPI and it now holds the project https://pypi.org/project/mda/

Closing as the project is no longer invalid.
