### ISSUE TITLE
Limit Request: bert-serving - 300MB

### ISSUE THREAD

**Issue by MRXLT** [pypa/pypi-support#66]
Project link: https://pypi.org/project/bert-serving/
We need 300M for this project in both PypPI& Test PyPI
This project will provide the service of remotely calling the bert model for semantic understanding, but the exe is too large to upload the whole whl

**Comment by MRXLT** [comment]
This project will be a subproject of paddle serving, which is flexible, high-performance serving system for machine learning models using paddlepaddle. 
github link for paddlepadlle & paddle serving
https://github.com/PaddlePaddle/Serving
https://github.com/PaddlePaddle/Paddle

**Comment by di** [comment]
Hi @MRXLT, sorry for the delay. If the distribution does not contain models and calls them remotely, why is it so large?

**Comment by di** [comment]
Closing due to lack of response.
