### ISSUE TITLE
PEP 541 Request: km3astro

### ISSUE THREAD

**Issue by tamasgal** [pypa/pypi-support#661]
**Project to be claimed**

`km3astro`: https://pypi.org/project/km3astro

**Your PyPI username**

`tamasgal`: https://pypi.org/user/tamasgal

**Reasons for the request**

This is another project which I was working on together with Moritz Lotze and other developers in a scientific collaboration (the KM3NeT neutrino telescope project). Moritz left our collaboration more than a year ago and we have no possibility to contact him. The PyPI registration was done by Moritz and he always took care of the release process.
Here is the original Git repository where you can see that both me and Moritz have commited to https://git.km3net.de/km3py/km3astro/-/commits/master

Another PEP 541 request was made for a similar project called `km3sim`: https://github.com/pypa/pypi-support/issues/652

**Maintenance or replacement?**

Maintenance. Here is the repository: https://git.km3net.de/km3py/km3astro

**Contact and additional research**

I tried to reach him via E-Mail and direct messages but no response for almost a year.

**Comment by ewjoachim** [comment]
On his [website](https://mtzl.gitlab.io/), he has a publicly available email. Is it the one you tried ?

**Comment by tamasgal** [comment]
Yes of course, I tried many ways to contact him over the past months, we were very good friends back than (tried mobile phone, social networks, multiple email addresses, ...) but the number is not valid anymore and no response via other channels. I have no idea what happened, but from the links I provided you can hopefully see that it's a collaborative project and nothing personal for profit.
Both `km3astro` and `km3flux` are part of a series of Python tools  developed for the KM3NeT neutrino experiment and Moritz was one of the main contributors besides myself (https://git.km3net.de/km3py/km3pipe/-/graphs/master).

We now started the process to consolidate these projects and also created a PyPI user (`km3net`) which we added to existing projects as maintainer as well (you can see it here: https://pypi.org/project/km3pipe/ https://pypi.org/project/km3io/ https://pypi.org/project/km3db/ https://pypi.org/project/km3net-testdata/ ).

**Comment by tamasgal** [comment]
How long does this usually take when the original author is not responding?

I still have no luck reaching him...

**Comment by tamasgal** [comment]
Any progress on this? I still have no response from my ex-colleague...

**Comment by tamasgal** [comment]
@ewjoachim is there any chance that this issue will be targeted any time soon? We need to make new releases and now considering to rename the project, which however would cause a lot of changes and work downstream...

If you think it's not obvious that I am now the main author, please let me know.

**Comment by ewjoachim** [comment]
I'm sorry, I'm not able to help.

**Comment by tamasgal** [comment]
So, is there any other way to get a feedback, or are PEP 541 requests ignored?

**Comment by tamasgal** [comment]
Let me desperately ping @jamadden since he is the last commiter I can found who responded to a 541 request: is there any chance to get this going or do we really have to rename this project? This means a lot of changes downstream, so I really hope we can resolve this. I don't know what else I should provide. It's clear that it's an open source project and Moritz is simply not responding on any channels. I don't even know what happened to him...

**Comment by tamasgal** [comment]
Maybe the other moderators? @pradyunsg, @ewjoachim

**Comment by tamasgal** [comment]
Sorry but I don't know whom to write. I now dropped a mail to admin@pypi.org
I don't understand how this support is supposed to work. I see requests which are not answered for more than a year.

**Comment by tamasgal** [comment]
Managed to reach Moritz. Thanks for the great support and responsiveness.
