### ISSUE TITLE
PEP 541 Request: pycose

### ISSUE THREAD

**Issue by TimothyClaeys** [pypa/pypi-support#665]
**Project to be claimed**

`pycose`: https://pypi.org/project/pycose/

**Your PyPI username**

`Timothy`: https://pypi.org/user/Timothy/

**Reasons for the request**

The project has not been updated for a year. I have reached out multiple times to the current owner of the project, but the owner is not responding to my emails. I am the original author of the code that is stored in https://pypi.org/project/pycose/. The current owner has forked my code and uploaded it to PyPi more than a year ago but has not made any improvements or updates to the code. I have made significant improvements to the code and I wish to publish those (https://github.com/TimothyClaeys/pycose).

**Maintenance or replacement?**

I wish to further update and maintain the code in the pycose package.

**Contact and additional research**

I have tried to reach the current owner multiple times on the email address published on the github page, but I have never received any response: setrofim@gmail.com
Additionally I have tried to reach the owner on the email address used to open pull requests: sergei.trofimov@arm.com

**Comment by yeraydiazdiaz** [comment]
Hello @TimothyClaeys, apologies for the delay in processing your request. I've started the reachability process, hopefully we will hear from the owner and move on with the transfer.

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @setrofim matching PyPI user [`setrofim`](https://pypi.org/user/setrofim/)

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
