### ISSUE TITLE
Limit Request: bpy - 184 MB

### ISSUE THREAD

**Issue by TylerGubala** [pypa/pypi-support#666]
**Project**

`bpy`

**Size of release/project**

184MB

**Which indexes**

Both

**Reasons for the request**

I was just able to get a reproducible build working in the `manylinux2014` Docker image, a.k.a CentOS 7.

After running `audit_wheel` and `repair_wheel` on the `*.whl` file, which to my knowledge statically links dynamically linked libraries and packages them _in_ the `wheel`, the file size grew once more to the size it is.

New features are being added constantly to Blender, and because of the additional need (for `manylinux`) to package the libraries into the `wheel` like that, I think that Blender Foundation will continue to add libraries and the size of the package will continue to grow.

In light of that, if it is determined that it's unsustainable to host that stuff on PYPI, no big deal. I would in that case probably host the `*.whl` binaries as a "release" on [the github webpage](https://github.com/TylerGubala/blenderpy).

It's just easier for users to do it like `pip install bpy` like they are used to.

**Comment by di** [comment]
I've set the upload limit for `bpy` to 200 MB on PyPI and TestPyPI.
