### ISSUE TITLE
PEP 541 Request: Apache Thrift

### ISSUE THREAD

**Issue by Jens-G** [pypa/pypi-support#667]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/thrift

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/JensG/

**Reasons for the request**
Very similar to what i wrote [here](https://github.com/pypa/warehouse/issues/5346#issuecomment-511117112), we are now in that exact situation I wanted to avoid. We have again the case that the only active maintainer again became unresponsive and inactive. 

**Maintenance or replacement?**
Further maintenance planned, code base is https://github.com/apache/thrift

**Contact and additional research**
I solved the same issue before with other instances of our packages and during that I tried to contact both listed maintainers multiple time. Not one responded in any way, that's why I am here.

**Comment by Jens-G** [comment]
I'ts only a month so no need to rush, but may I ask how I can help with this?

**Comment by mibo** [comment]
Hi PyPa-Team, is there any progress?
I would appreciate that Jens is added as a maintainer.
As otherwise newer Thrift versions (like now `0.14.0`) may not be added.
Kind Regards, Michael

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay in processing this request. I've now added @Jens-G as an owner to the `thrift` project.
