### ISSUE TITLE
Limit Request: ort-gpu-nightly

### ISSUE THREAD

**Issue by faxu** [pypa/pypi-support#671]
**Project**
ort-gpu-nightly

**Size of release/project**
Request to double project size limit

**Which indexes**
Test Pypi

**Reasons for the request**
We use test pypi to upload nightly packages. Over time this accumulates and we anticipate hitting the limit about every month. Is there a suggested method to automate this cleanup (any APIs?) other than manual deletion on a regular basis? Alternatively, increasing the project size can help us decrease the frequency of cleanup. Looking for recommendations and/or project size limit increase. Thanks!

**Comment by di** [comment]
I've set the project limit for `ort-gpu-nightly` to 20 GB on TestPyPI. Thanks for taking care to delete old releases.

> Is there a suggested method to automate this cleanup (any APIs?) other than manual deletion on a regular basis?

Nope, sorry, not yet!

**Comment by di** [comment]
(You might be interested in chiming in on https://github.com/pypa/warehouse/issues/8792)
