### ISSUE TITLE
Limit Request: PixPlot - 200 MB

### ISSUE THREAD

**Issue by duhaime** [pypa/pypi-support#672]
**Project**
[PixPlot](https://pypi.org/project/pixplot/)

**Size of release/project**
200MB

**Which indexes**
Both

**Reasons for the request**
Our bundle size recently grew quite a bit because we wished to install a pose detection model with our package. We'd be grateful if you could grant us a slightly larger project size allocation!

**Comment by di** [comment]
I've set the upload limit for `PixPlot` to 200 MB on PyPI. This project doesn't exist on TestPyPI, you'll need to create it there before we can increase the limit there.

**Comment by duhaime** [comment]
Thanks so much! 🙏
