### ISSUE TITLE
PEP 541 Request: `metrix`

### ISSUE THREAD

**Issue by bdewilde** [pypa/pypi-support#673]
**Project to be claimed**

`metrix`: https://pypi.org/project/metrix

**Your PyPI username**

`bjdewilde`: https://pypi.org/user/bjdewilde

**Reasons for the request**

I believe that the project has been abandoned. There was only a single v0.0.1 release back in 2015, and nothing since. The project's homepage is a dead link. And as mentioned below, I've not been able to find the project's source code, and its owner hasn't responded to an email inquiring about a name transfer.

**Maintenance or replacement?**

I recently released an open-source Python package of the same name — https://github.com/bdewilde/metrix — and I would like to publish it to PyPi for others to use under that name. I have no way to compare its functionality to the other package currently occupying this name on PyPi, since I've not been able to find any details on what it does. So, I would like to replace it.

**Contact and additional research**

I emailed the current owner, but haven't received a response. I also tracked down both his GitHub and Bitbucket profiles, and did not see this `metrix` project among any of the associated repositories. Extensive web searching has also not tracked the original project down.

**Comment by bdewilde** [comment]
Hello again! Is there anything I can or should do to nudge this transfer along?

**Comment by yeraydiazdiaz** [comment]
Hello @bdewilde, apologies for the delay in processing your request. I can confirm the project is invalid since it has a single release with no files associated with it.

In these situations we attempt contact with the owner once allowing a one week courtesy period. If we don't hear back we will move forward with your request.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
