### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by VivianMonzon** [pypa/pypi-support#680]
Request for account recovery.

## PyPI Username

VivianMonzon

---

##  Reason for request

Reason: Loss access to email address

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, if that bounces or no response is heard after at least 7 days, we will proceed with recovery.

**Comment by ewdurbin** [comment]
The address associated with the account bounced.

@VivianMonzon please email support@pypi.org with the address you'd like associated with the account to proceed.

**Comment by ewdurbin** [comment]
email address associated with the user has been updated as requested. you can recover access to your account by proceeding with a standard password reset.
