### ISSUE TITLE
Limit Request: Semgrep - 110 MB

### ISSUE THREAD

**Issue by brendongo** [pypa/pypi-support#681]
Hi, we recently hit the 100MB upload limit for our project

**Project**
semgrep https://pypi.org/project/semgrep

**Size of release/project**
110MB

**Which indexes**
Pypi

**Reasons for the request**
Semgrep is a static analysis tool that runs on many languages. We include a statically linked manylinux binary of the core static analysis engine. As we support more languages the size of that binary will increase. For this release a limit of 110MB will be enough but I can forsee needing more depending on how soon we add support for more languages.

**Comment by di** [comment]
I've set the upload limit for `semgrep` to 200 MB on PyPI.
