### ISSUE TITLE
Limit Request: h2o - 200 MB

### ISSUE THREAD

**Issue by sebhrusen** [pypa/pypi-support#682]
**Project**

https://pypi.org/project/h2o/

**Size of release**

200 MB

**Which indexes**

PyPI

**Reasons for the request**

H2O is a popular open-source ML platform (https://github.com/h2oai/h2o-3/).
The python package comes with an embedded backend packaged as a jar.
The package size may increase over time but the increase between releases is usually relatively small. The latest release however, brought new features and dependencies to reach 157 MB. Requesting a 200 MB limit here to be comfortable for at least a year.

**Comment by di** [comment]
I've set the upload limit for `h2o` to 200 MB on PyPI.
