### ISSUE TITLE
PEP 541 Request: terminator

### ISSUE THREAD

**Issue by mattrose** [pypa/pypi-support#683]
**Project Name**

`terrminator`: https://pypi.org/project/terminator

**Your PyPI username**

`mattrose`: https://pypi.org/user/mattrose

**Reasons for the request**

The project which currently occupies the name "terminator" on pypi.org has had one release, and in fact, if you look at the source code repository https://github.com/HunterLarco/terminator it has only ever had one commit.  It looks like the user had an idea, released it on pypi, and then abandoned it, all in 2016.  It has only enough code to be published on PyPI, and nothing else.

**Maintenance or replacement?**

I plan to publish the Terminal Emulator [Terminator](https://github.com/gnome-terminator/terminator) in it's place, rather than the code that is currently in the terminator package.

[Terminator](https://github.com/gnome-terminator/terminator) is a very popular Terminal Emulator written in python using the vte library.  It has a history going back to 2006.  I'm not sure why it has never been on pypi before, but I have had numerous user requests to be able to install it through pip.

**Contact and additional research**

I attempted to contact the original maintainer 7 days ago via email, and have not heard back.

**Comment by mattrose** [comment]
Any word on this?  Anything more I need to do to get this going?

**Comment by pradyunsg** [comment]
@HunterLarco seems to be the relevant GitHub user for this.

In case the current owner is able to respond in the next 7 days for this, I'm comfortable saying that we should move ahead with a transfer to OP.

**Comment by HunterLarco** [comment]
Happy to transfer this! Just let me know if I need to do anything.

**Comment by mattrose** [comment]
Thank you so much @HunterLarco, is there a way for you to just transfer the project to me directly? I think you can just add me as a collaborator, according to https://github.com/pypa/warehouse/issues/1745#issuecomment-280370719 My username is mattrose on pypi.org as well.

**Comment by pradyunsg** [comment]
@HunterLarco can invite you to the project, as an "Owner". Once you accept the invitation, you'll have push access.

**Comment by HunterLarco** [comment]
@mattrose Invitation sent!

**Comment by mattrose** [comment]
Awesome, thank you so much @HunterLarco! and @pradyunsg 

I think we can close this now.

**Comment by yeraydiazdiaz** [comment]
Closing are requested, thanks @HunterLarco and @mattrose.
