### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kirankotari** [pypa/pypi-support#684]
Request for account recovery.

## PyPI Username

`kkotari`

---

##  Reason for request

Reason:
`Lost 2FA authentication app or security token`

**Comment by ewjoachim** [comment]
If I understand correctly what you stated in #679, you still have 2fa recovery codes ?

**Comment by kirankotari** [comment]
@ewjoachim sorry for confusion, I have just realised the 2FA recovery codes I have is GitHub not PyPI. I was looking for it but couldn't able to find them so far.

**Comment by kirankotari** [comment]
@ewjoachim Any updates. I saw a lot of similar request for "Account recovery" if you need any help let me know. Happy to help.

**Comment by kirankotari** [comment]
@ewjoachim @ewdurbin have your team done anything for group 3 issues? last time I was able to upload the lib via terminal today I am facing following issue.

```
Uploading distributions to https://upload.pypi.org/legacy/
  dist/decimaljs-0.0.1-py3-none-any.whl (2.3 KB)
  dist/decimaljs-1.0.0-py3-none-any.whl (2.3 KB)
  dist/decimaljs-0.0.1.tar.gz (35.6 KB)
  dist/decimaljs-1.0.0.tar.gz (35.6 KB)
Enter your username: kkotari
Enter your password:
  Skipping decimaljs-0.0.1-py3-none-any.whl because it appears to already exist
Uploading decimaljs-1.0.0-py3-none-any.whl
100%|██████████| 6.99k/6.99k [00:01<00:00, 4.25kB/s]
Content received from server:
<html>
 <head>
  <title>401 This password appears in a security breach or has been compromised and cannot be used. See the FAQ entry at https://pypi.org/help/#compromised-password for more information.</title>
 </head>
 <body>
  <h1>401 This password appears in a security breach or has been compromised and cannot be used. See the FAQ entry at https://pypi.org/help/#compromised-password for more information.</h1>
  This server could not verify that you are authorized to access the document you requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required.<br/><br/>
 </body>
</html> 
```

**Comment by ewjoachim** [comment]
I'm not sure I understand your question, given you showed the error message and I find it quite explicit. Have you tried looking at the links included in the message ?

Please let us know if there's something you need more information on, you should be able to reset your password.

This is completely unrelated to your 2FA issue. As you can see [here](https://github.com/pypa/pypi-support/projects/2#card-49692964), your issue is in the New/Triage column, and it's being handled by PyPI admins based on their volunteer time. Please be patient, many people are waiting too.

Also, please don't post the same messages in multiple issues :)

Thank you.

**Comment by kirankotari** [comment]
@ewjoachim got it. I was worried when it got rejected, So thought of informing in the other thread as well. If this was only for me I might not posted there.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account to proceed with 2FA recovery, please read the instructions and reply to proceed with recovery.

The other issue is unrelated, and will be resolved by the password reset after 2FA recovery is completed.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
