### ISSUE TITLE
PEP 541 Request: miso

### ISSUE THREAD

**Issue by geometrikal** [pypa/pypi-support#685]
**Project to be claimed**

`miso`: https://pypi.org/project/miso

**Your PyPI username**

`geometrikal`: https://pypi.org/user/geometrikal

**Reasons for the request**

Name is taken but no project exists

**Maintenance or replacement?**

New package from https://github.com/microfossil/particle-classification

**Contact and additional research**

Cannot find current owner or project

**Comment by yeraydiazdiaz** [comment]
I can confirm the project is invalid as it has no releases.

In these situations we attempt contact with the owner once allowing a one week courtesy period. If we don't hear back we will move forward with your request.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
