### ISSUE TITLE
PEP 541 Request: OpenPGP

### ISSUE THREAD

**Issue by kushaldas** [pypa/pypi-support#686]
**OpenPGP**

`OpenPGP`: https://pypi.org/project/OpenPGP

**kushaldas**

`kushaldas`: https://pypi.org/user/kushaldas

**Reasons for the request**

The project was last released (marked as alpha) back in 2005, and the [home page](http://www.aonalu.net/openpgp) says not to use in the real world. 

**Maintenance or replacement?**

I will publish a new Python module written in Rust, the current code is at <https://github.com/kushaldas/johnnycanencrypt> and will be renamed to `openpgp`. 

**Contact and additional research**

I emailed both the mail addresses provided in the project page, both seems to be invalid. The project homepage also says not to use the implementation.

**Comment by pradyunsg** [comment]
I can confirm that the owner is not reachable. All of the user's emails (as available on PyPI or the project pages) are bouncing. http://www.aonalu.net/sourpoi/ links to the repository, but that results in a 404: https://bitbucket.org/sourpoi/python-openpgp-2440. This project easily satisfies all the requirements for being considered "abandoned" (not reachable + no releases in an year + no updates on the home page).

---

As far as I can tell, this request falls under "Removal of an abandoned project" in PEP 541. Quoting the relevant section:

> An abandoned project can be transferred to a new owner for purposes of reusing the name when ALL of the following are met:
>
> - the project has been determined abandoned by the rules described above;

Satisfied.

> - the candidate is able to demonstrate their own failed attempts to contact the existing owner;

@kushaldas if you could forward the "bounce" notice sent by your email provider to pradyunsg@gmail.com, that'd confirm this. :)

> - the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;
> - the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;

These have to be demonstrated.

> - download statistics on the Package Index for the existing package indicate project is not being used; and

Can confirm, based on 26 downloads in the last week.

> - the maintainers of the Package Index don't have any additional reservations.

I don't.

**Comment by kushaldas** [comment]
> @kushaldas if you could forward the "bounce" notice sent by your email provider to pradyunsg@gmail.com, that'd confirm this. :)

Forwarding those bounced emails to the given address. Thank you.

**Comment by pradyunsg** [comment]
> Forwarding those bounced emails to the given address. Thank you.

ACK. Can confirm. :)

**Comment by kushaldas** [comment]
> > * the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;
> > * the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;
> 
> These have to be demonstrated.

The readme of the project says:

```
**This is an attempt at implementing OpenPGP in Python. The primary focus is on flexibility with respect to packet information and message composition.**
```
Also the home page says it is an *a somewhat acedemic OpenPGP implementation* and also using the old RFC 2440, <http://tools.ietf.org/html/rfc4880> is the newer one.

**Comment by ewdurbin** [comment]
Transfer complete.
