### ISSUE TITLE
test.pypi.org returning 502 Bad Gateway intermittently

### ISSUE THREAD

**Issue by hoffmang9** [pypa/pypi-support#688]
**Describe the bug**
At approximately 11:20AM PDST, twine uploads were receiving - `HTTPError: 502 Bad Gateway from https://test.pypi.org/legacy/`. This URL was also giving a 502 - https://test.pypi.org/help/

**Expected behavior**
Wheels should upload and website should vend pages.

**To Reproduce**
During the time window a twine upload or web request would reproduce this.

**My Platform**
GitHub actions from ARM64, MacOS runners. Website from Brave on MacOS

**Additional context**

![image](https://user-images.githubusercontent.com/30377676/97346009-18570480-1848-11eb-8635-4234e682753b.png)

**Comment by ewdurbin** [comment]
our monitoring/alerting is definitely more concerned with pypi.org itself.

not many resources are available to test.pypi.org, and even though we don't have any SLA for pypi.org itself... we _certainly_ do not have one for test.pypi.org.

it looks like test.pypi.org gets random spurts of traffic that overload the single pod that runs it's web interface. I've provisioned some additional capacity and will see how that goes for a few days.

generally, test.pypi.org carries no guarantees and should not be relied on for any specific workflows.

**Comment by hoffmang9** [comment]
I was already leaning toward re-ordering the workflow and making test failures non fatal.

I would add a small enhancement request that there be at least a token amount of monitoring on test.pypi.org added. It was not obvious where to reach out if there are issues with test (hence putting this issue in the wrong place initially.)

**Comment by pradyunsg** [comment]
Is this still an issue?

**Comment by hoffmang9** [comment]
We have only seen it one more time since then. Our monitoring noticed it so it works for us but it's not clear that means everyone else is prepared in the modern CI upload to test.pypi world.

**Comment by pradyunsg** [comment]
We can't do much to prepare the rest of the world for outages, and... as noted... test.pypi.org has basically no guarentees.

I don't think there's much point in keeping this issue open at this point, so I'll go ahead and close it.
