### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by twang817** [pypa/pypi-support#692]
Request for account recovery.

## PyPI Username

`twang817`

---

##  Reason for request

Reason: I forgot what email address I registered the account with (I may still have access).  I have several projects that need to have updates.

**Comment by ewdurbin** [comment]
@twang817 the account is registered with an `@joinem.com` email address. Please reopen if you need further assistance.

**Comment by twang817** [comment]
Unfortunately, that was my employer many years ago.  Furthermore, they are now out of business.

Is there any way we can recover this account?  Or transfer ownership of its pypi packages to another user?
