### ISSUE TITLE
PEP 541 Request: egret

### ISSUE THREAD

**Issue by bknueven** [pypa/pypi-support#697]
**Project to be claimed**

egret: https://pypi.org/project/egret

**Your PyPI username**

bknueven: https://pypi.org/user/bknueven

**Reasons for the request**

This project has not had an update in over a year, and only two versions have been released. The homepage points to the author's GitHub homepage, and I can find no repository associated with it. The current project has at most minimal functionality, consisting of approximately 100 lines of Python code.

**Maintenance or replacement?**

Replacement. I would like to distribute our open-source package of power systems optimization by the same name, available at https://github.com/grid-parity-exchange/Egret, on PyPI under the name `egret`.

**Contact and additional research**

I have emailed the author at the address listed on PyPI four times in the past six weeks without receiving a response. Since the author seems active on GitHub: @kougazhang, do you have objections to releasing the name `egret`?

**Comment by yeraydiazdiaz** [comment]
Hello @bknueven, the project has _some_ functionality so I am now starting the reachability process which will take six weeks, during that time I will attempt contact with the current owner, hopefully we will hear back and move on to transferring the project.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
