### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by refnode** [pypa/pypi-support#698]
Request for account recovery.

## PyPI Username

`refnode`

---

##  Reason for request

Reason:

Seems that I accidentially forget to update an email address from a previously owned domain refnode.com
Don't receive password reset emails anymore.

**Comment by ewdurbin** [comment]
Hello @refnode. I was able to find record of two email addresses in the metadata for past releases owned by this user.

One `@gmail.com` and one `@wiredobjects.eu`. Based on the existing historic metadata I would be comfortable updating the email address associated with the user to either address if you can provide a preference.

**Comment by refnode** [comment]
Hi @ewdurbin, 

thx for your support! The @gmail.com is perfect.

**Comment by ewdurbin** [comment]
email address associated with the account has been updated as requested. you can recover access to your account through the standard password reset procedure now.
