### ISSUE TITLE
Limit Request: opencv-contrib-python-headless - 150 MB

### ISSUE THREAD

**Issue by skvark** [pypa/pypi-support#699]
**Project**

https://pypi.org/project/opencv-contrib-python-headless

**Size of release/project**

150 MB

**Which indexes**

PyPI

**Reasons for the request**

This project provides pre-built wheels as well as a source distribution for certain OpenCV variant. Wheel packages are itself smaller than the default 100 MB limit, but the source distribution reaches currently 142 MB and therefore cannot be uploaded to PyPI. This leads to unexpected problems on platforms which do not have pre-built wheels available. Requesting a 150 MB limit to be on the safe side as I do not control the actual source code of OpenCV which might have additional data files added in any future release.

**Comment by di** [comment]
I've set the upload limit for `opencv-contrib-python-headless` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
