### ISSUE TITLE
claim project otter (PEP 541)

### ISSUE THREAD

**Issue by chuck1** [pypa/pypi-support#7]
I would like to claim the project name `otter` on PyPI. My project is [here](https://github.com/otterweb/otter), I'm just starting development.

[the pypi page](https://pypi.org/project/otter/) gives 404 but I believe there is an existing project with no uploads. I am unable to upload to upload.pypi.org but I am able to upload to test.pypi.org. Similar to pypa/warehouse#5503 

Thanks

**Comment by yeraydiazdiaz** [comment]
Hello @chuck1, I can confirm the `otter` project in PyPI has no releases and can therefore be considered name squatting.

Could you confirm your PyPI username, please?

**Comment by chuck1** [comment]
My PyPI username is chuck

**Comment by yeraydiazdiaz** [comment]
Thanks, I've contacted an admin to proceed with the transfer.

**Comment by ewdurbin** [comment]
transfer complete.
