### ISSUE TITLE
False claim as spam account (acue)

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#702]
See also #536:
I am a bit astonished about this story!

So as a long term contributor working on a large framework for which I am going to deploy the first parts it is irritating to be called a spammer or if this obviously not fits a troll, or whatever.

That is bullying - as I guess here in order to actually troll the name datafusion see #659.

So please assure that this thing stops immediately.

WKR

**Comment by pradyunsg** [comment]
Please raise a concern with PSF's conduct WG if you believe that there has been bullying here (which would be a CoC violation). You can find more information about the Code of Conduct here: https://www.python.org/psf/conduct/

**Comment by xavfernandez** [comment]
Actually since none of the PyPA responder is involved, the first email of https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md would apply IMHO.

**Comment by pradyunsg** [comment]
Ah, indeed. conduct@pypa.io would be appropriate.

**Comment by pradyunsg** [comment]
Closing this out, since it's been over an year since last activity here.
