### ISSUE TITLE
Trolling of a projectname - datafusion

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#703]
See also #659 and #536:
I am a bit astoinished about this story!

So as a long term contributor working on a large framework for which I am going to deploy the first parts it is irritating to be called a spammer or if this obviously not fits a troll, or whatever.

That is bullying - as I guess here in order to actually troll the name datafusion see #659.

The PEP-541 prohibits it's application on existing projects. And I am more as astonished that members of PyPA are suddenly in a rush to do so.

Trolling an existing project would naturally violate the copyright clause ant though force a backdrop via a follow-up issue. See text of #659 and #536.

So please assure that this thing stops immediatley.

WKR

**Comment by pradyunsg** [comment]
Merging into #702.
