### ISSUE TITLE
Falsely namecalling as a spammer by  Sviatoslav Sydorenko

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#704]
**S.th. went wrong when storing, so issued twice.**

The issue #536 was falsely changed and transfered to bullying and namebinding after my protest to the false claims.
Sviatoslav Sydorenko tried obviously bully me via search engines as a spammer which is false and may have even legal consequences. This is in most countries an offense / a criminal act.

So I request herein the immediat change and the public clarification of this issue.

See #536:

@webknjaz webknjaz changed the title [PEP 541] Spam account detected [PEP 541] Spam account detected (acue / @ArnoCan) 2 hours ago 

WKR

**Comment by pradyunsg** [comment]
Merging into #702.
