### ISSUE TITLE
Falsely namecalling (acue / @ArnoCan) as a spammer by  Sviatoslav Sydorenko

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#705]
See also #536 and #659 + #702 and #703:

After protesting against the false claim the title was changes by Sviatoslav Sydorenko aka. webknjaz obviously in order to namebinding via search engines.

This is in all countries a criminal offense which will have eventually legal consequences.

**See #536:**

@webknjaz webknjaz changed the title [PEP 541] Spam account detected [PEP 541] Spam account detected (acue / @ArnoCan) 2 hours ago 

(screenshots are available)

I can only repeat what I have already stated in #536:
#>>>
@webknjaz last comment
See bitbucket for a better solution concerning the search results :*), a limit of the query and search design could not interpreted by falsely incriminating some one as spammer and trying to troll it's assets. That is actually ridiculous. Definitely not appropriate for an open source foundation against it's comitters.
#<<<

I request an immediate reset and drop of that namebinding including a public statement of excuse with clarification.

Tanks for your understanding.

WKR

**Comment by webknjaz** [comment]
> obviously in order to namebinding via search engines

Just for the record: this is a shameless lie. I renamed it to identify this spam report among other things because the previous title was too broad and it needed to be more specific specifying what it's about more precisely.

**Comment by ArnoCan** [comment]
@xavfernandez: See "Trolling of a projectname - datafusion #342 

Which email for an CoC issue?

WKR

**Comment by ArnoCan** [comment]
@webknjaz
Read your own comments!

WKR

**Comment by pradyunsg** [comment]
@ArnoCan please don't file multiple issues and make managing the issue tracker more difficult.

Combining with #702.

**Comment by pradyunsg** [comment]
> email for CoC

Please see https://www.python.org/psf/conduct/ for details on the Code of Conduct for this space. You can find contact details there.
