### ISSUE TITLE
[PEP 541] User squatting 500+ packages (acue) - Incorrect issue still with public account/namebinding

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#706]
@pradyunsg

Dear Pradyun,
The change is basically OK, but still contains a name/account. Please drop this to:

- [PEP 541] User squatting 500+ packages #536

Which we can clarify mostly - though resultingly completely - soon.

WKR

**Comment by pradyunsg** [comment]
I understand your concern, however, I'd prefer to keep the account name in the issue title since it is the PyPI username involved and under discussion.

Please stop filing additional issues for the same topic. If you want to have further discussion, please do so in #702.

**Comment by ArnoCan** [comment]
I do not agree, it is enough to link within the issue text. This is the first case I saw such an issue.

So please fix this.

WKR
