### ISSUE TITLE
PEP 541 Request: Copyright infringment for non-deleteable package names

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#707]
After my recent experiences, your ownership policies of projects and their brands as demonstrated by your staff, I have actually problems in seeing the foundation as trustfull.

See:  #536 +  #659 + #702 + #703 + #704 + #705 + #706

So finally decided to stop publishing new packages on PyPI.
I am going to maintain some older packages for a while.

Apparently I have to see, that I can remove releases but no package names - e.g. in case of 'ctysng-doc'.
The new allocated packages to be removed are appended as ascii-file with one name each line, so should be easily processed by your admins.

I own the copyright for these all as proven by the fact itself - including this issue.
So due to the blocked deletion I request in accordance to PEP-541 a copyright infringement of the branded names I own the copyright for and I am using on a number of other repositories. 

0. please remove all listed projects including the releases
1. assure that no copyright infringment as assured by PEP-541 is possible in future

I have added a list of names - with exactly 500 package names to be completely removed.

Currently maintained packages:

- patches: these are planned to remain

  - namedtupledefs
  - namedtupledefs2
  - namedtupledefs3
  - xmlschema_acue

- own projects: these will be eventually removed after a relocation period

  - epyunit
  - filesysobjects
  - jsondata
  - platformids
  - pysourceinfo
  - pythonids
  - setupdocx
  - setupjavax
  - setuplib
  - setuplibcore
  - setuptestx
  - sourceinfo
  - yapydata
  - yapyutils

Thanks in advance.

WKR

[pypi-cancel.txt](https://github.com/pypa/pypi-support/files/5473702/pypi-cancel.txt)

**Comment by di** [comment]
@ArnoCan Please stop creating new issues in this tracker and other @pypa trackers. We will address this in #https://github.com/pypa/pypi-support/issues/536.
