### ISSUE TITLE
Stop blocking issues related to package removal - PEP-541: copyright infringement - see #707

### ISSUE THREAD

**Issue by ArnoCan** [pypa/pypi-support#709]
@di - Dustin Ingram

Dear Dustin,
as I said, after all I made the decision to finish my collaboration with PyPI as a publishing platform.

So the issue #707 has nothing to do with my issue due to false claims as stated in #702  + #536, in particular the mentioned namebinding and bullying #705. You can decide in this ecosphere whatever, first assure my rights in accordance to PEP-541!

So would you please be so kind to stop blocking my eligible request to remove my packages, and just proceed.

Anyhow, the issue #707 will also obsolete #536 and other claims.

So thanks in advance.

WKR

**Comment by di** [comment]
OK, since you seem to be unable to listen to my requests, I've now blocked you instead.

Nobody is preventing you from removing your own packages. You can do that at any point.

**Comment by pradyunsg** [comment]
> Nobody is preventing you from removing your own packages. You can do that at any point.

To be ridiculously clear, this can be done by:

- signing into PyPI
- Navigating to "Your projects" page: https://pypi.org/manage/projects/
- For each project that you wish to delete:
  - Navigate to a project's "Manage" page.
  - Go to "Settings" from the sidebar, and scroll down to the "Delete Project" button.
  - Click that and follow on-screen instructions.

This has to be done on a per-project basis, and there is no API to automate this.
