### ISSUE TITLE
Limit Request: swh.graph - 100MB

### ISSUE THREAD

**Issue by zacchiro** [pypa/pypi-support#71]
Heya, the [swh.graph PyPI package](https://pypi.org/project/swh.graph/) includes a front-end for the [WebGraph framework](http://webgraph.di.unimi.it/), which is developed in Java and accessed via Py4J (also available via PyPI). A so-called "fat JAR" with all Java dependencies is included to make deployment possible with a simple "pip install" and currently weights ~100 MB.

Would it be possible to increase the file size limit for swh.graph (for both PyPI and Test PyPI)?

**Comment by di** [comment]
I've set the upload limit for `swh.graph` to 100 MB on PyPI.

This project does not exist on TestPyPI, you'll need to create it there before I can increase the limit.

**Comment by zacchiro** [comment]
On Wed, Nov 13, 2019 at 08:49:44AM -0800, Dustin Ingram wrote:
> I've set the upload limit for `swh.graph` to 100 MB on PyPI.

Thanks a lot !
