### ISSUE TITLE
PEP 541 Request: gurobipy

### ISSUE THREAD

**Issue by rluce** [pypa/pypi-support#710]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/gurobipy/

**Your PyPI username**

`USER_NAME`: robertluce

**Reasons for the request**

I would like to have ownership of the PyPI project `gurobipy` transferred because:

1. The PyPI project `gurobipy` is a clear case of name squatting: [`gurobipy` is the Python interface](https://www.gurobi.com/documentation/9.0/quickstart_linux/the_grb_python_interface_f.html) to the commercial software [Gurobi](https://gurobi.com).
2. The meta data for the PyPI project `gurobipy` actually refers to our company's homepage, and clains the author name "Gurobi Optimization, Inc.".  But this project was created without the consent from our side, by a user apparently unknown to our company.  In view of PEP541 I think this would qualify for an *invalid project*.
3. The PyPI project `gurobipy` is an *abandoned project*, as the last interaction of the current owner with the project dates back to 2013.

**Maintenance or replacement?**

We will maintain the project under the "gurobipy" name, and provide up-to-date binary wheels for this package.

**Contact and additional research**

I did some basic research for contact data of the current "owner" of the PyPI gurobipy project (https://pypi.org/user/luig1987/), but couldn't find a reliable channel.

**Comment by rluce** [comment]
@luig1987 Do you happen to be the same person behind PyPI's 'luig1987', and if so, would you be willing to transfer the project?

**Comment by rluce** [comment]
@luig1987 Did you have a chance to figure out whether you had any prior ties to this PyPI project?  Please also confirm if this is totally unrelated to you, thanks!

**Comment by rluce** [comment]
@jamadden Thanks for triaging this issue on the project board!  Since it now resides in the "Pending user input" column, please let me know if there is any missing piece of information that I could provide.

**Comment by rluce** [comment]
In the meantime we contacted several people that use the handle 'luig1987', but in all cases either the ownership was denied, or we didn't get an answer. @jamadden Did you find a way to contact the owner using the data PyPI has on file?

**Comment by rluce** [comment]
I would appreciate if someone could give feedback on the state of this PEP 541 request, thanks!

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay @rluce.

I can confirm the project has a single release with no files and is therefore considered invalid. I can also confirm that @luig1987 is the owner and has been since the project's creation.

Us moderators give the current owner a courtesy period of one week before proceeding with the transfer. I'll consider this comment as a notice since the owner has replied previously. But we'd appreciate it if @luig1987 could transfer the ownership to @rluce himself to speed things up and reduce the burden on moderators and admins.

**Comment by rluce** [comment]
Thanks for moving this forward!

**Comment by rluce** [comment]
> Us moderators give the current owner a courtesy period of one week before proceeding with the transfer. 

It looks like the current owner did not react in the last four weeks -- would it be possible to queue this issue up for admin transfer now?

**Comment by yeraydiazdiaz** [comment]
Yes, since we've received no response I'll place this in the queue for admin transfers.

**Comment by gglockner** [comment]
Thanks for your help on this @yeraydiazdiaz. It's been 2 months since your last update - any news on this?

**Comment by ewdurbin** [comment]
Transfer complete.
