### ISSUE TITLE
PEP 541 Request: dtb

### ISSUE THREAD

**Issue by vincentlam** [pypa/pypi-support#711]
**Project to be claimed**
dtb
https://pypi.org/project/dtb

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/vincentlam

**Reasons for the request**

The home page https://github.com/getsentry/dtb leads to 404.

**Maintenance or replacement?**

Replace with https://github.com/vincentlam/dtb

**Contact and additional research**

I did some basic research for contact data of the current "owner" of the PyPI dtb project (https://pypi.org/user/mitsuhiko/), but couldn't find a reliable channel.

**Comment by yeraydiazdiaz** [comment]
Hello @vincentlam, I can confirm the project is invalid as it has a single release with no associated files. I will attempt contact with the current owner and allow a week for a reply, if I do not receive one we will proceed with the transfer.

**Comment by mitsuhiko** [comment]
Can be transferred

**Comment by yeraydiazdiaz** [comment]
Thanks for confirming @mitsuhiko, transfer complete.
