### ISSUE TITLE
Limit Request: opencv-python-headless - 30 GB

### ISSUE THREAD

**Issue by skvark** [pypa/pypi-support#712]
**Project**

https://pypi.org/project/opencv-python-headless/

**Size of project**

Current size 19,5 GB, requesting increase from 20 GB to 30 GB

**Which indexes**

PyPI

**Reasons for the request**

`opencv-python-headless` is the headless variant of OpenCV. It's used in computer vision applications for example in server environments. Currently there is a 20 GB limit for `opencv-python-headless` in PyPI and I hit that limit in the latest release. I already deleted 2 oldest releases to get new releases with Python 3.9 wheels uploaded. I would like to avoid that in the future since there might be users who are still using the old releases and pre-built wheels might be hard to come by otherwise. Therefore, requesting project size limit increase to 30 GB.

**Comment by di** [comment]
I've set the project size limit for `opencv-python-headless ` to 40 GB on PyPI.

**Comment by skvark** [comment]
@di 

I still see the 20 GB limit:

![pypi_limit](https://user-images.githubusercontent.com/695340/100233624-ac44ea80-2f32-11eb-8de2-9d77838f7a89.PNG)

**Comment by di** [comment]
Sorry, looks like I mixed this up with your other requests.

I've set the project size limit for `opencv-python-headless` to **30 GB** on PyPI.
