### ISSUE TITLE
PEP 541 Request: Nxt

### ISSUE THREAD

**Issue by MichaelAldrich** [pypa/pypi-support#714]
**Project to be claimed**

`Nxt`: https://pypi.org/project/Nxt/

**Your PyPI username**

`michaelaldrich`: https://pypi.org/user/michaelaldrich/

**Reasons for the request**

I believe the project is abandoned and also is invalid. It is completely empty with no functionality, `setup.py` contains only the minimum to specify package name and version. 

**Maintenance or replacement?**

Publish a different one. Based on my research(detailed below) there is no existing package to maintain. The code repository for the project that will replace it is not public yet.

**Contact and additional research**

The package is owned by `deleted-user` https://pypi.org/user/deleted-user/
Which based on my understanding is not an existing user, has no public email, and cannot be contacted.
Multiple web searches revealed no clear indicator who started this abandoned project.

**Comment by jamadden** [comment]
Projects owned by `deleted-user` are that way because of an administrative action taken to remove the project. I don't know why `Nxt` is that way (perhaps a trademark infringement?). @ewdurbin may have more information.

**Comment by ewdurbin** [comment]
This project was moved from a mass squatter account to the old 'deleted-user' user.

I've completed this transfer.
