### ISSUE TITLE
Limit Request: mpl-tc-fonts - 200 MB (File Size Limit)

### ISSUE THREAD

**Issue by Hsins** [pypa/pypi-support#715]
Hi! I'd like to request an increase in the total project size limit. I got the error message when uploading project:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File too large. Limit for project 'mpl-tc-fonts' is 100 MB. See https://pypi.org/help/#file-size-limit for more information.
```

**Project**

The project [`mpl-tc-fonts`](https://github.com/Hsins/mpl-tc-fonts)

**Size of release/project**

The current size is 100MB, I would like to request an increase to 200MB.

**Which indexes**

PyPI

**Reasons for the request**

`mpl-tc-fonts` is a package like [`mpl-font`](https://pypi.org/project/mpl-font/) for users to properly use Traditional Font in their `matplotlib` plots. There are a few Traditional Chinese fonts contained and the size of each font would be huge compared to other fonts due to the wide-range charsets should be supported.

There are no so many fonts could be used so that each release would be under 200 MB.

Thanks a lot for your help!

**Comment by di** [comment]
I've set the upload limit for `mpl-tc-fonts` to 200 MB on PyPI.
