### ISSUE TITLE
🚀 PEP 541 Request: hyperdrive 🚀

### ISSUE THREAD

**Issue by suchak1** [pypa/pypi-support#717]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/hyperdrive

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/suchak1

**Reasons for the request**

This project has not had any new releases in over two and a half years, and there are no downloads. I believe this project has been abandoned.

**Maintenance or replacement?**

Replacement with this project: [Github repo](https://github.com/suchak1/hyperdrive), [PyPi package](https://pypi.org/project/hyperdrive-quant/). Hyperdrive is an open-source python algorithmic trading platform that is sorely needed since Quantopian recently shut down unexpectedly. The project has been in active development for over 5 months with over 30 releases, and I also have the domain hyperdrive.pro for more docs and demos to be added later on.

**Contact and additional research**

I emailed the maintainer a week ago with no response. If you have any upcoming releases, let us know @mwilliammyers

**Comment by mwilliammyers** [comment]
@suchak1 you can have the hyperdrive name on pypi 😄  
I am not sure what, if anything, needs to be done by me...

**Comment by suchak1** [comment]
@mwilliammyers thx, I appreciate it! :) I believe all you have to do is to login to pypi.org > Your projects > hyperdrive > Manage > Settings > Delete project (it says on this page that the project name will then become publicly available).

**Comment by mwilliammyers** [comment]
@suchak1 done; good luck on your new project!

**Comment by suchak1** [comment]
@mwilliammyers thanks again, same to you w your endeavors!
