### ISSUE TITLE
PEP 541 Request: pypg

### ISSUE THREAD

**Issue by arianesasso** [pypa/pypi-support#719]
**Project to be claimed**

I could not find a valid project page, just this reference: https://libraries.io/pypi/pypg
pip search pypg returns nothing.
`PROJECT_NAME`: https://pypi.org/project/pypg

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/asasso

**Reasons for the request**

I think the old project has changed its name: https://pypi.org/project/plpygis/.

**Maintenance or replacement?**

Replacement by our library to process PPG signals (under development): https://github.com/hpi-dhc/pypg

**Contact and additional research**

I am not sure who to contact since it seems https://pypi.org/project/pypg is free.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project is invalid as it contains no releases. I will attempt contact with the current owner and allow a one week period before proceeding with the request.

**Comment by arianesasso** [comment]
Thank you!

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by arianesasso** [comment]
Thank you again for solving this!
