### ISSUE TITLE
Limit Request: pyserini - 150MB

### ISSUE THREAD

**Issue by lintool** [pypa/pypi-support#72]
Per [How do I get a file size limit exemption or increase for my project?](https://pypi.org/help/#file-size-limit)

I am filing a size limit increase request for both: [PyPI pyserini](https://pypi.org/project/pyserini/) and [Test PyPI pyserini](https://test.pypi.org/project/pyserini/).

Rationale is that my package needs to include Java (fat) jar dependencies, which currently total ~100 MB. A limit raise to 150 MB would be appreciated to give some headroom.

Thanks in advance for your help!

**Comment by jamadden** [comment]
The limit has been set to 150MB on pypi.org and test.pypi.org
