### ISSUE TITLE
PEP 541 Request: dune

### ISSUE THREAD

**Issue by somesam** [pypa/pypi-support#721]
**Project to be claimed**

`dune`: https://pypi.org/project/dune/

**Your PyPI username**

`samuel.burbulla`: https://pypi.org/user/samuel.burbulla/

**Reasons for the request**

I have contacted the maintainer. He is willing to transfer this project, but he has no access to its mail address any more.
He requested me to open this issue.

**Maintenance or replacement?**

I want to publish a different package under this project name.

**Contact and additional research**

Our mail conversation:

===
Dear Marwan Alsabbagh,

I have seen your project „dune" at pypi (https://pypi.org/project/dune/
<https://pypi.org/project/dune/>), because I am interested in the pypi
package name „dune“.

It looks like your project hasn’t seen a lot of development in the last
years.

Is there a chance that you move your package to another name and provide the
name „dune“ for my project?

Best regards,
Samuel Burbulla

===

Dear Samuel,
  Thanks for getting in touch. I loved the name dune because I'm a
big fan of the dune series of books. You should definitely use the
name. I have not use this dune package since 2011 and do not need it.
I'm sure it isn't used by anyone else either.
  I have faced one issue though I was using a different email address
in 2011 and no longer have access to the email or domain. It was
registered under marwan@djangodune.com back in the day. So I can't
reset the password for the pypi account or get in to rename or delete
it. I've contacted the admins of pypi and explained to them the
situation. I've asked them to delete the dune project as it is very
old and no longer in use.
  I'll keep you updated on what they say. Good luck with your project!

cheers,
Marwan

===

Dear Samuel,
  So on the pypi help page they have indicated when someone has an
issue resetting their password they can contact admin@python.org to
get help. I emailed that address and got back a failed to deliver
email. I'll forward you that email for your reference. I dug around
more on their help and they have a section related to our situation.
Check out the following link:

How do I claim an abandoned or previously registered project name?
https://pypi.org/help/#project-name-claim

 So it talks about contacting the owner to get permission. In your
case you were able to contact the owner and you have my consent to
transfer transfer ownership of the name to you. The old dune project
is abandoned. There is a link that let's you open an issue to make the
request. Please go ahead with the process. On github my username is
the same as on pypi it is marwano. Feel free to email me if they need
anything further from me.

 By the way my website is http://marwano.com/ and has links to my
email, github profile and has my same name of Marwan Alsabbagh. I have
given presentation at a number of Python conferences like EuroPython.
Links and details are on the website. In case they have any doubt of
my identity they are free to contact me on this email address.

cheers,
Marwan

**Comment by marwano** [comment]
This is Marwan Alsabbagh the author of the project to be claimed dune. I just wanted to confirm all the above. Feel free to contact me if you need anything further from my end.

**Comment by yeraydiazdiaz** [comment]
Thanks for confirming @marwano, the transfer is now complete.
