### ISSUE TITLE
PEP 541 request: ivy

### ISSUE THREAD

**Issue by ivy-seed** [pypa/pypi-support#722]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/ivy

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/ivyteam

**Reasons for the request**

Trademark Infridgement.
Our trademark is publically listed, and can be found [here](https://trademarks.ipo.gov.uk/ipo-tmcase/page/Results/1/UK00003521605).
Specifically, the name "ivy" is trademarked within class 9: open source software.

**Maintenance or replacement?**

Replacement

**Contact and additional research**

Sent an e-mail to current owner on 23rd Oct 2020.
Opened [an issue](https://github.com/dmulholl/ivy/issues/3) on the Github on 30th Oct 2020.

We have kept this issue brief, but can further elaborate if helpful.
We also welcome input from the current owner, [dmulholl](https://github.com/dmulholl), on this issue.

Your attention on this matter is appreciated.

Kind Regards,
The Ivy Team

**Comment by 983** [comment]
Am I reading this correctly? You claim trademark infringement on a project which existed 4 years **before** you registered that trademark?

**Comment by gaborbernat** [comment]
Well, this is a gray area. Feels to me you're using a loophole in our rules to do a (from what it looks like - hostile) takeover of a long-standing project name. Furthermore, the name ``Ivy`` is already a registered trademark per https://ant.apache.org/legal.html inside the USA. I'm not sure how US vs UK trademark priority goes but considering most infrastructure is hosted in the US, I think in this case Apache holds the actual trademark rights over you.

**Comment by ivy-seed** [comment]
We thank @gaborbernat for his comments.

We would like to follow up with two points:

1. We fail to see how requesting a name transfer on the grounds of trademark infringement is a loophole. We registered the trademark to protect our brand, and this falls under that category.

2. Regarding Apache, given that they are not requesting the name, we fail to see the relevance of this. Furthermore, we were unable to find their mark listed on the U.S. [Trademark Electronic Search System](https://www.uspto.gov/trademarks-application-process/search-trademark-database) (TESS). If you find a link to their published trademark in an official journal, please feel free to share this with us.

We kindly await official response from a member of the PyPI team with authority to make a decision on this matter, and we look forward to following up with them on any further issues or concerns.

Kind Regards,
The Ivy Team

**Comment by yeraydiazdiaz** [comment]
Hello @ivy-seed, please refer to the [intellectual property section of PEP 541](https://www.python.org/dev/peps/pep-0541/#intellectual-property-policy).
