### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thedrow** [pypa/pypi-support#723]
Request for account recovery.

## PyPI Username

`the_drow`

---

##  Reason for request

Reason:
Lost my phone and can't find recovery code.

**Comment by bagerard** [comment]
Hi @ewdurbin, this is currently blocking some tasks on our end related with releasing new versions of MongoEngine as we are migrating from travis to Github Actions (https://github.com/MongoEngine/mongoengine/issues/2411). Any chance to address this request any soon? Thanks for you understanding...

**Comment by ewdurbin** [comment]
@bagerard I'm working through the backlog oldest to newest, this will likely be triaged/addressed in the next batch. you can see an approximation of the queue and progress on the "Account Recovery" project in this repo.

**Comment by bagerard** [comment]
Awesome, thanks a lot for your hard work. I've seen #679 and understand that you are in a difficult situation due to limited amount of people with such access in Pypi.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
