### ISSUE TITLE
Limit Request ldcpy - 180 MB

### ISSUE THREAD

**Issue by pinarda** [pypa/pypi-support#725]
**Project**
https://pypi.org/project/ldcpy

**Size of release/project**

180 MB

**Which indexes**

PyPi

**Reasons for the request**

ldcpy is a utility for gathering and plotting metrics from NetCDF or Zarr files. We have a number of example datasets that are used in the documentation and tutorial, which hare taking up much of the space in the package. These are all necessary to showcase the different variables and file types the package supports. It is possible that the package size will grow in the future to ~ 250 MB.

**Comment by di** [comment]
I've set the upload limit for `ldcpy` to 200 MB on PyPI.
