### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kevwilde** [pypa/pypi-support#726]
Request for account recovery.

## PyPI Username

`kevwilde`

---

##  Reason for request

Reason:
It's a very old account and I've not used it in a while. Forget Password says it does not recognize my email address.
I still use the email address as used as the author on this package: https://pypi.org/project/cmsplugin-twcarousel/

Kind regards,

Kevin

**Comment by ewdurbin** [comment]
The account is currently associated with an @inuits.eu email address. If you have lost access to this address, please let us know and we can proceed with updating the email address associated with the account.

**Comment by kevwilde** [comment]
@ewdurbin I lost access to this email address. If possible it could be reassociated with the email address listed in my cmsplugin-twcarousel package?

**Comment by ewdurbin** [comment]
This is complete. You can now regain access to your account by performing a standard password reset.
