### ISSUE TITLE
radware-ansible-common-alteon ownership change

### ISSUE THREAD

**Issue by LeoBrider** [pypa/pypi-support#728]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/radware-ansible-common-alteon/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/leonidb

**Reasons for the request**

The previous project owner (https://pypi.org/user/leonmeguira/) left the company and didnt forward ownership on the project
I want to move the project management to myself

**Maintenance or replacement?**

i will continue to maintain the project

**Contact and additional research**

leonmeguira (leonm@radware.com) left the company and his email was closed, my email leonidb@radware.com and as u can see i am from the same company and want to continue to maintain it.

**Comment by LeoBrider** [comment]
Any news?

**Comment by yeraydiazdiaz** [comment]
Closing as `leonidb` appears to be the owner now.
