### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by hallazzang** [pypa/pypi-support#73]
My current username is [**HallaZzang**](https://pypi.org/user/HallaZzang/).
I'd like to change my username to **hallazzang**(all lowercase letters).
Is it possible?

**Comment by ewdurbin** [comment]
This is done.

Note: Only changes to usernames such as this, where the resulting username is a case insensitive match for the original. To track the status of arbitrary username changes see https://github.com/pypa/warehouse/issues/1190

**Comment by ewdurbin** [comment]
Note: Unfortunately it seem that these kinds of changes are no longer as easily accomplished, especially for users with many projects or a long history on PyPI. Changes to our schema have made it so the necessary update cascades through all JournalEntry objects for all Projects owned by the user.
