### ISSUE TITLE
Transfer project from my personal account to my work account

### ISSUE THREAD

**Issue by TrentDaniel** [pypa/pypi-support#730]
**Project to be claimed**
solace-pubsubplus or solace_pubsubplus is the name of the project and the top level package is called solace. I am the owner of the project on my personal account but I deleted the project because I thought that I could simply use the same name in my work account. The project was just a test for the real thing at work but I used the official name by accident. Since I deleted the project, I can't give a url to the actual project itself, but the url to my account page is https://test.pypi.org/user/TrentDaniel/ in case that helps at all.

`PROJECT_NAME`: https://pypi.org/project/PROJECT_NAME

**Your PyPI username**
The username for my personal account which holds the distribution name currently is https://test.pypi.org/user/TrentDaniel/. The username for my work account that needs to acquire the distribution name is https://test.pypi.org/user/solace/.

`USER_NAME`: https://pypi.org/user/USER_NAME

**Reasons for the request**
As stated previously, I created the project by accident under my own account using the official name of the distribution by accident while trying to test uploading methods for my work. Now I need to transfer the name of the distribution from my personal account to my work account so that my work can upload it's distributions properly.

**Maintenance or replacement?**
I intend to replace the project. Functionally it will be similar, but the project under my work account won't have any formal connection to or history with my personal account. I can't provide a code repository for the repo since it is private. 

**Contact and additional research**
I am the current owner, I just need to transfer the name across accounts. My contact information is trent.daniel@solace.com.

**Comment by jamadden** [comment]
If you deleted the project, then ownership is not the issue; it is now available for anyone to claim by uploading a new distribution. I would guess that you are trying to reuse the same file name (including version) for a new upload, which is never allowed. You’ll need a new name (version; you could use a .post signifier). The twine error message includes a link to more info. 

If you haven’t deleted the project, the you can add any other account as an owner yourself by visiting the projects page.

**Comment by TrentDaniel** [comment]
Thank you for the quick response! Also, should this affect our ability to publish to pypi.org at all? Can we not have the same version published to both test.pypi.org and pypi.org?

**Comment by jamadden** [comment]
The two sites are completely separate.

**Comment by TrentDaniel** [comment]
Thank you for clarifying :)

**Comment by jamadden** [comment]
If this issue is explained/resolved for you, would you please close it? Thank you.

**Comment by TrentDaniel** [comment]
I'm just testing it right now. As soon as I have proof that it is working again, I will be sure to close it.
