### ISSUE TITLE
Issue: Limit Request: gpam-pre-processing-ner - 115 MB

### ISSUE THREAD

**Issue by medeiroslucas** [pypa/pypi-support#732]
**Project**

gpam-pre-processing-ner
https://pypi.org/project/gpam-pre-processing-ner/

**Size of release/project**

I'm hitting the upload file size limit with a 115MB file

**Which indexes**

0.0.3a1.dev1, 0.0.3a1.dev2, 0.0.3a1.dev3, 0.0.3a1.dev4, 0.0.3

**Reasons for the request**

This project is a lib to named entity pre-processing to work with NLP. The reason the memory limit has been exceeded is that there is a tensorflow prediction model within the project. Probably later versions will also need memory expansion

**Comment by di** [comment]
I've set the upload limit for `gpam-pre-processing-ner` to 200 MB on PyPI.
