### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cboling** [pypa/pypi-support#735]
Request for account recovery.

## PyPI Username

cboling

---

##  Reason for request

Lost 2FA authentication app or security token

Reason:

Mobile phone change and lost my previous recovery app (google authenticator) and I had not saved off any recovery tokens.   I can still push uploads but cannot log into associated web account.  Existing email (chip@bcsw.net) is still valid for my account

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
