### ISSUE TITLE
PEP 541 request: PySLM

### ISSUE THREAD

**Issue by drlukeparry** [pypa/pypi-support#736]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/pyslm

**lukeparry**

`USER_NAME`: https://pypi.org/user/lukeparry

**Reasons for the request**
The project has been abandoned - there are no packages available or were subsequently removed. 

**Maintenance or replacement?**
Replacement - This will provide a replacement or substitution for an opensource project - https://github.com/drlukeparry/pyslm

**Contact and additional research**

I have attempted to contact the original two co-authors (University Academics at the University of Waterloo), however,  the second author and owner (Gilbert Shih) failed to respond to my request for transfer.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project is invalid as it contains no releases. I will contact the owner and allow a one week period for reply before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
