### ISSUE TITLE
Limit Request: Several projects. Up to 2000MB

### ISSUE THREAD

**Issue by prstrnn** [pypa/pypi-support#737]
Hello,

I'm from Intel corp. and we are preparing new releases in PyPi.
We are expecting that we will hit project limit size, so we are requesting to extend limits for these projects:

IntelAutomationEngineering - PyPI account we will use to upload packages.

**Size of release/project**
onemkl - 2000 MB
tbb_oneapi - 50 MB
ippcp_oneapi - 50 MB
oneapi_ccl - 50 MB
compiler - 500 MB
onemkl - 500 MB
ipp_oneapi - 1200 MB

**Which indexes**
both

**Reasons for the request**
It's Intel's software that contains a lot of optimizations for the different hardware, that's why it has so big size. 
Expected that future releases will be greater than current.

**Comment by pradyunsg** [comment]
Thanks for filing this issue!

I understand that this is a request for raising the per-file limit across these various projects. The projects with 50 MB requests should already be permitted.

2000 MB is definitely one of the larger (if not the largest) limit request I've seen here. Please elaborate further on why these packages need 500 MB or more, and why distributing the various optimised binaries via a different channel (such as nltk's data downloader) is not a viable solution for you.

Further, what is the expected size of future releases? Will they be 10% bigger? 50%? 2x?

**Comment by di** [comment]
In addition, it seems like the majority of these packages don't exist yet -- you'll need to create them (with a dummy/empty release) before we can increase the limit.

One of these does already exist, however it doesn't appear that you or Intel are the owner: https://pypi.org/project/compiler/

**Comment by prstrnn** [comment]
Hi, we'll create a dummy release, sure. Sorry for the late response, was on vacation,

> 2000 MB is definitely one of the larger (if not the largest) limit requests I've seen here. Please elaborate further on why these packages need 500 MB or more, and why distributing the various optimized binaries via a different channel (such as nltk's data downloader) is not a viable solution for you. 
I'm not sure about how this solution was done, but it was decided to distribute via PyPI

Further, what is the expected size of future releases? Will they be 10% bigger? 50%? 2x? I think it's about a 10% increase

**Comment by prstrnn** [comment]
Could you please extende file size up to 1g in projects ipp and mkl? 
No dummy releases needed, they are exists already? @di @pjenvey 
Please, it's a little bit urgent now

**Comment by pradyunsg** [comment]
@prstrnn 

> Please elaborate further on why these packages need 500 MB or more, and why distributing the various optimised binaries via a different channel (such as nltk's data downloader) is not a viable solution for you.
> 
> Further, what is the expected size of future releases? Will they be 10% bigger? 50%? 2x?

**Comment by di** [comment]
None of these projects (except for `compiler`) exist. We can't increase any limits until they exist.

**Comment by prstrnn** [comment]
@di I've sent wrong project list. 
We have update only this list now:

- mkl-dpcpp up to 500 MB
- mkl-static up to 500 MB
- onednn-cpu-tbb up to 300 MB
- ipp-static up to 400 MB
- opencl-rt up to 300 MB

**Comment by prstrnn** [comment]
I think we can close this wrong request, new one (https://github.com/pypa/pypi-support/issues/782) is correct. Sorry for spamming
