### ISSUE TITLE
Limit Request: tr - 200MB

### ISSUE THREAD

**Issue by myhub** [pypa/pypi-support#739]
**Project**
tr
PyPI page, i.e. https://pypi.org/project/tr/

**Size of release/project**
200MB

**Which indexes**
both

**Reasons for the request**
tr is a popular OCR SDK which support Windows/Linux,  https://github.com/myhub/tr
it is large because it contains deep learning train models and opencv/onnxruntime libs

**Comment by di** [comment]
I've set the upload limit for `tr` to 200 MB on PyPI. This project doesn't exist on TestPyPI, you'll need to create it there first before we can increase the limit there.
