### ISSUE TITLE
PEP 541: Transfer ownership of unmaintained `rip`

### ISSUE THREAD

**Issue by dschaller** [pypa/pypi-support#74]
**Project to be claimed**

`rip`: https://pypi.org/project/rip

**Your PyPI username**

`dschaller`: https://pypi.org/user/dschaller

**Reasons for the request**

This package has been abandoned. It has only had a single release 5 years ago and the source code for the project is no longer maintained as the last commit was over 2 years ago.

**Contact and additional research**

I contacted the project author numerous times over the last couple of months and one of the authors, @vedarthk, said he and the other devs are ok with transferring the name.

**Comment by jamadden** [comment]
We do not have a verified email address for the project owner, https://pypi.org/user/Girish.Redekar/, but we do have an address on file. It differs from the one listed at https://pypi.org/project/rip. I've emailed them both.

I've also opened https://github.com/Aplopio/django_rip/issues/54 (note that the PyPI page links to  https://github.com/Aplopio/rip but that redirects to  https://github.com/Aplopio/django_rip). 

Based on GitHub profiles, it appears that @greasematic could be the PyPI project owner. There's a different email listed for that account so I've also emailed it and tagged that account.

**Comment by jamadden** [comment]
I received a response from the email address published on the PyPI page:

> From: Vedarth Kulkarni <redacted>
> Subject: Re: PyPI Project rip: Name Transfer Request
> Date: November 15, 2019 at 09:14:54 CST
> To: Girish Redekar <redacted>, jason.madden
> 
> Hi Jason,
>
> I initially thought that `rip` was registered using Girish's company email address but looks like he has created the project with his own personal email.
> 
> Girish Redekar please can you transfer the ownership of https://pypi.org/project/rip/ to https://pypi.org/user/dschaller

**Comment by dschaller** [comment]
Thanks for looking into this @jamadden! Let me know if I can help.

**Comment by jamadden** [comment]
After a series of inexplicably private emails, it appears that @dschaller has been named an owner of this project.
