### ISSUE TITLE
PEP 541 Request: from (and related packages)

### ISSUE THREAD

**Issue by bmg-pcl** [pypa/pypi-support#745]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/from/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/bmg

**Reasons for the request**
Project conflicts with the python keyword *from* and thus will never be importable. 

This is one of fifty projects created by user tphp on 10-Aug-2020 (https://pypi.org/user/tphp/) , apparently all in error: it looks like they were created by script from a source file and  all should be removed. They are named:
isinstance
continue
false
true
def
from
host
localhost
global
smtp
title
cpu
begin
xing
number
apcu
laravel
tsql
ssql
odbc
num
hua
buy
sou
gou
mao
word
apache
nginx
pkill
oper
ktv
last
import
ico
info
set
lay
gun
fag
vim
yum
kapi
iapi
dapi
yuxing
phper
xcode
xxf
tphp

**Maintenance or replacement?**

Maintenance - removal of these packages is the goal, I think. 

**Contact and additional research**

Email to listed account @qq.com bounced.

**Comment by yeraydiazdiaz** [comment]
Thanks for the report @bmg-pcl, it looks like our admins have solved this already, the user has [no registered projects](https://pypi.org/user/tphp/) and the project names have been placed in our prohibited project names list.
