### ISSUE TITLE
PEP 541 Request: classy

### ISSUE THREAD

**Issue by ntessore** [pypa/pypi-support#746]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/classy

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/ntessore

**Reasons for the request**

The project appears abandoned since 2012. Attempts to contact the author and clarify status/ask for transfer have failed.

**Maintenance or replacement?**

Replacement by the `classy` package which is widely used in the field of cosmology.

Code repository for CLASS (of which `classy` is the Python binding) is https://github.com/lesgourg/class_public .

As part of the SkyPy project, we are providing pip-installable (from Git) packages at https://github.com/skypyproject/classy. If these packages were provided through PyPI, it would improve usage and testing.

**Contact and additional research**

Wrote to listed email address for maintainer without response.

**Comment by pbdeuchler** [comment]
Hello Nicolas, glad you pinged me here... it looks like your email got caught in my spam filter. I've removed my package from pypi, so the name should be free for the taking. Guess this means I also need to remove "Open Source Maintainer" from my resume 😔

**Comment by ntessore** [comment]
Thanks vv much @pbdeuchler for giving up your package name. I managed to claim the name. No need to change the resume, you will always be honorary maintainer!
