### ISSUE TITLE
PEP 541 Request: svg

### ISSUE THREAD

**Issue by ethanhs** [pypa/pypi-support#751]
**Project to be claimed**

`svg`: https://pypi.org/project/svg

**ethanhs**

`ethanhs`: https://pypi.org/user/ethanhs

**Reasons for the request**

It appears the user/owner has name-squatted several names, including SVG.

**Maintenance or replacement?**

Maintenance, I suppose? There isn't anything in the package right now :)

**Contact and additional research**

I have tried emailing the owner via the email associated with their account, but have yet to hear from them.

**Comment by yeraydiazdiaz** [comment]
Hello @ethanhs, thanks for the report. I can confirm `svg` is indeed invalid and the user has registered many projects that appear to be name squatting. I will contact the admins to solve this as I'm not sure what the steps would be.

**Comment by ethanhs** [comment]
Thank you for following up, I appreciate you spending time on this.

**Comment by yeraydiazdiaz** [comment]
`svg` has been placed in the prohibited projects names list.
