### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jsoucheiron** [pypa/pypi-support#754]
Request for account recovery.

## PyPI Username

`jsoucheiron`

---
##  Reason for request
  - Lost access to email address

Reason:
I created the account a long time ago when I was working for another company. I no longer have access to the email.
I'm fine losing access to any library I might have had access to.

**Comment by ewdurbin** [comment]
@jsoucheiron I have removed the only remaining project associated with the user, and will happily update the account to use whatever email you like. Please email support@pypi.org with the following information:

- confirm the domain of the existing primary email address
- the address you would like associated with the PyPI account

**Comment by ewdurbin** [comment]
Address has been updated as requested. You can recover access to your account by completing a standard password reset.
