### ISSUE TITLE
Limit Request: mx-cu* - 1G

### ISSUE THREAD

**Issue by szha** [pypa/pypi-support#755]
**Project**
mx-cu100, mx-cu102, mx-cu110, mx-cu111, mx-cu120

**Size of release**
1GB

**Which indexes**
PyPI

**Reasons for the request**
Same as #243. For compliance reasons we request the limits for the packages under new name. Thanks.

**Comment by ewdurbin** [comment]
@szha what will become of the old project names?

**Comment by szha** [comment]
(Tentatively) We keep them as is for now for old releases. Packages will be published to the new name.

**Comment by ewdurbin** [comment]
To confirm, new individual releases will not be cross published between the old/new name.

If that is correct, we can proceed.

**Comment by szha** [comment]
confirmed. we won't publish new versions to both packages simultaneously.

**Comment by ewdurbin** [comment]
limits increased, 1GB file limit, 24GB project limit for each of mx-cu{100,102,110,111,120}

**Comment by szha** [comment]
thanks for the quick turnaround!
