### ISSUE TITLE
PEP 541 Request: neuroglancer (on test.pypi.org)

### ISSUE THREAD

**Issue by jbms** [pypa/pypi-support#756]
**Project to be claimed**

`neuroglancer`: https://test.pypi.org/project/neuroglancer

**Your PyPI username**

`jbms`: https://test.pypi.org/user/jbms

**Reasons for the request**
I am the author of the Neuroglancer project (https://github.com/google/neuroglancer), and already own the non-test neuroglancer PyPI account and neuroglancer PyPI package, which are actively used.

This request is for solely for the `neuroglancer` account/package on the **test server**, test.pypi.org.  The account/package on the test server have not been used for several years, but it would now be useful to use the test server for automatically publishing development builds.

A collaborator on the project, @funkey, set up both the pypi.org and test.pypi.org neuroglancer accounts and packages several years ago, but unfortunately the password for the test.pypi.org account has been lost and the email address that is most likely associated with the account is one that he no longer has access to, now that he has moved to a different institution.

**Maintenance or replacement?**
Maintenance, see above.

**Contact and additional research**
I have contacted the person who set up the account/package, @funkey, and he is fully supportive of this request.  See above.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
