### ISSUE TITLE
PEP 541 Request: canlib

### ISSUE THREAD

**Issue by Cecron** [pypa/pypi-support#757]
**Project to be claimed**

`canlib`: https://pypi.org/project/canlib/

**Your PyPI username**

`Krunush`: https://pypi.org/user/Krunush/

**Reasons for the request**

The project does not seem to be updated and I have had no luck in contacting the current owner.
Beside being outdated, the project homepage also has invalid links which has caused some extra support for Kvaser.com, who is the author of the package.

**Maintenance or replacement?**

The intention is to keep the package up-to-date with the releases made at https://www.kvaser.com/download/

**Contact and additional research**

A feature request to be able to reach the maintainer has been filed https://github.com/pypa/warehouse/issues/8384

**Comment by Cecron** [comment]
Anything more I can do help solve this?

**Comment by yeraydiazdiaz** [comment]
Hello @Cecron, I have started the reachability process for your request, hopefully we will hear back soon and proceed with the transfer.

**Comment by AlwaysLearningMore** [comment]
I approve of the transfer

**Comment by yeraydiazdiaz** [comment]
@AlwaysLearningMore thanks for confirming, transfer complete.

**Comment by Cecron** [comment]
@AlwaysLearningMore Thanks for approving the transfer. And also a big thank you for creating the canlib project on PyPI!
