### ISSUE TITLE
Issue: Limit Request:  adme-predict  195 MB

### ISSUE THREAD

**Issue by zhuyang0925** [pypa/pypi-support#759]
adme-predict                   https://pypi.org/project/adme-predict

**Does this project already exist?**
yes

**Size of release/project**
adme-predict  195MB

**Which indexes**
PyPI

**Reasons for the request**
Many new models have been added, so I need to upload larger files

**Comment by di** [comment]
I've set the upload limit for `adme-predict` to 200 MB on PyPI.
