### ISSUE TITLE
Issue: PEP 541 Request: nupack

### ISSUE THREAD

**Issue by mfornace** [pypa/pypi-support#760]
**Project to be claimed**
`nupack`: https://pypi.org/project/nupack

**Your PyPI username**
`nupack`: https://pypi.org/user/nupack

**Reasons for the request**
The project in question was left at version 0.1 several years ago without development. It is a use of the nupack name without permission. It is an abandoned collection of scripts to automate job submission on nupack.org, which is not intended usage.

**Maintenance or replacement?**
We (the nupack.org development team) do not intend to continue maintenance of the prior package. We maintain a nupack python package which we are distributing via our own channels. We request also that a hold be placed on the `nupack` name on pypi linked to our user/email `nupack`/support@nupack.org.

**Contact and additional research**
The author's email is defunct and could not be found by other means.

support@nupack.org may be contacted for further questions or verification.

**Comment by yeraydiazdiaz** [comment]
Hello @mfornace, I can confirm the project has no releases and is therefore considered abandoned. I will attempt contact with the owner and allow one week for a reply after which we will proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
I have not received response and added the `nupack` user as an owner of the project, however, you mention:

> We (the nupack.org development team) do not intend to continue maintenance of the prior package. We maintain a nupack python package which we are distributing via our own channels. We request also that a hold be placed on the nupack name on pypi linked to our user/email nupack/support@nupack.org.

If you are not intending to publish a package with that name you are technically intending to keep the project as invalid, which sounds wrong to me. I think it'd be best to place `nupack` in the prohibited names list but I don't have permissions to do so, only @pypa/warehouse-admins can.

**Comment by yeraydiazdiaz** [comment]
I'll close since the transfer has been completed.

**Comment by ewdurbin** [comment]
This is complete.
