### ISSUE TITLE
PEP 541 Request: guilded

### ISSUE THREAD

**Issue by shayypy** [pypa/pypi-support#764]
Specifically: https://www.python.org/dev/peps/pep-0541/#invalid-projects

This package does not have any functionality and was never maintained to begin with. 

My personal theory is that it is name-squatting from `guilded-py`, which is maintained and functional. Judge its squatting-status as you will, but it is undoubtedly nonfunctional. 

Link to the package: https://pypi.org/project/guilded

**Comment by yeraydiazdiaz** [comment]
Hello @shayypy, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the current owner notifying them of the transfer and allow one week for a reply.

Am I correct to assume you'd like it to be transferred to your account https://pypi.org/user/shay/?

**Comment by shayypy** [comment]
> Am I correct to assume you'd like it to be transferred to your account https://pypi.org/user/shay/?

Yes @yeraydiazdiaz, that's correct. Thank you.

**Comment by yeraydiazdiaz** [comment]
The owner replied stating he's been working on the library but was not ready for release. He published a new version and expressed intend to continue with its development.
