### ISSUE TITLE
PEP 541 Request: skyline

### ISSUE THREAD

**Issue by ntessore** [pypa/pypi-support#765]
**Project to be claimed**

`skyline`: https://pypi.org/project/skyline

**Your PyPI username**

`ntessore`: https://pypi.org/user/ntessore

**Reasons for the request**

There does not appear to be a valid `skyline` package.

**Maintenance or replacement?**

Neither. A new standalone package for the [pipeline](https://github.com/skypyproject/skypy/tree/master/skypy/pipeline) module from [SkyPy](https://github.com/skypyproject/skypy).

**Contact and additional research**

I cannot find any reference to a previous `skyline` package.

**Comment by ntessore** [comment]
Any update on what's going on here?

**Comment by yeraydiazdiaz** [comment]
Hello @ntessore, I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owners and allow one week for a reply before proceeding with the transfer.

**Comment by ntessore** [comment]
Thanks @yeraydiazdiaz. [As far as I can tell](https://pypi.org/project/skyline), the project doesn't even exist?

**Comment by yeraydiazdiaz** [comment]
PyPI will return 404 if the project has no releases, but it does exist.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
