### ISSUE TITLE
Limit Request: megengine - 850 MB

### ISSUE THREAD

**Issue by xxr3376** [pypa/pypi-support#766]
**Project** https://test.pypi.org/project/MegEngine/

**Does this project already exist?** Yes

**Size of release/project** 850MB / 10GB

**Which indexes** Test PyPI

**Reasons for the request** This is a deep learning framework with the full support for CUDA, so it's huge. We have already request for 850MB limit in the PyPI index in this [issue](https://github.com/pypa/pypi-support/issues/289), we need a test index that having the same limit as the normal one to verify everything is OK before we upload to PyPI.

We only need to place one version in Test PyPI, so the size(also the total project size) won't increase. (This is only for Test PyPI, we need more project limit in PyPI, which is mention in https://github.com/pypa/pypi-support/issues/767

12 files will be included in one version:
* 4 of them are Linux package for 3.6 - 3.8, each one's size is around 820MB
* 4 of them are macOS package for 3.6 - 3.8, each one's size is around 30MB (No CUDA support)
* 4 of them are Windows package for 3.6 - 3.8, each one's size is around 820MB

**Comment by pradyunsg** [comment]
We don't need two separate issues for PyPI/TestPyPI.
