### ISSUE TITLE
Limit Request: megengine - 20GB

### ISSUE THREAD

**Issue by xxr3376** [pypa/pypi-support#767]
**Project** https://pypi.org/project/MegEngine/

**Does this project already exist?** Yes

**Size of release/project** 850MB / 20GB

**Which indexes** PyPI and Test PyPI

**Reasons for the request**

This is a deep learning framework with the full support for CUDA, so it's huge. We have already request for 850MB limit in the PyPI index at https://github.com/pypa/pypi-support/issues/289. We delete the old versions to leave some space for the newer version, you can find all releases at https://megengine.org.cn/whl/mge.html.

After we released the windows support, we found that we need 6.7GB for each version, and the project total limit is 10GB. We need at least double the size limit to upload the second version while the old version exists. Otherwise, our users may not able to download anything between deleting the old version and uploading the new version.

There are 12 files in one version, around 6.7GB in total.
* 4 of them are Linux package for 3.6 - 3.8, each one's size is around 820MB
* 4 of them are macOS package for 3.6 - 3.8, each one's size is around 30MB (No CUDA support)
* 4 of them are Windows package for 3.6 - 3.8, each one's size is around 820MB

**Comment by di** [comment]
I've set the total project limit for `megengine` to 20 GB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
