### ISSUE TITLE
Name change request

### ISSUE THREAD

**Issue by RDIL** [pypa/pypi-support#768]
Request for account recovery.

## PyPI Username

`jumbocakeyumyum`

---

##  Reason for request

Reason:
My PyPI account uses a really old username I used to go by, and I am trying to get it in sync across all platforms for the sake of keeping track of my accounts and just for being up-to-date.

Please, if possible, change it to `rdil`, `rdilpickle`, `reece`, or something like that.  

Thank you so much in advance!

P.s. if this can't be done, let me know, I can make a new account with the proper name and transfer my packages there.

**Comment by ewdurbin** [comment]
We do not currently support changing usernames directly, see https://github.com/pypa/warehouse/issues/1190.

You should proceed to create a new user and transfer packages as described.
