### ISSUE TITLE
PEP 541 Request: AutoGL

### ISSUE THREAD

**Issue by Frozenmad** [pypa/pypi-support#771]
**Project to be claimed**

`AutoGL`: https://pypi.org/project/autogl

**Your PyPI username**

`THUMNLab`: https://pypi.org/user/THUMNLab

**Reasons for the request**

If you click the project link above, you will find nothing there (page not found). However, if you search autogl in PyPI search engine, the project is listed there.  The project name `auto-gl`, `agl` has the same issue (No PyPI home page but exist in search engine).

We have tried uploading our AutoGL project directly but failed with errors saying that: `The user 'THUMNLab' isn't allowed to upload to project 'AutoGL'`. Can you help remove this empty project and transfer it to us?

**Maintenance or replacement?**

replacement

Our github: https://github.com/THUMNLab/AutoGL
Our docs: https://autogl.readthedocs.io/en/latest/

**Contact and additional research**

No contact information can be obtained since it is empty. The project even has no PyPI page.

**Comment by yeraydiazdiaz** [comment]
Hello @Frozenmad, I can confirm the project is invalid as it has no releases. I will now attempt contact with the owner and allow one week for reply before transferring the project.

**Comment by yeraydiazdiaz** [comment]
On second thought, this is part of mass squatter reported in https://github.com/pypa/pypi-support/issues/791, transfer complete.
