### ISSUE TITLE
PEP 541 Request: Maker

### ISSUE THREAD

**Issue by josephmancuso** [pypa/pypi-support#775]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/maker

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/josephmancuso

**Reasons for the request**

The project has been abandoned and meets all criteria for transfer of ownership:

> the candidate is able to demonstrate their own failed attempts to contact the existing owner;

I have contacted the owner and they have not responded to my requests. This email is the one on the package index

<img width="951" alt="Screen Shot 2020-12-02 at 8 50 07 AM" src="https://user-images.githubusercontent.com/20172538/100880985-667caa80-347b-11eb-802d-1bf91962e239.png">

I have had no response.

According to the PEP 541 requirements I have pasted and responded to each one here. I must meet all criteria for ownership and i believe that I do:

> the candidate is able to demonstrate their own failed attempts to contact the existing owner;

I have contacted the user as demonstrated above

> the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements?

The project for reuse is here and will be renamed to Maker instead of Masonite ORM. It has been in development for several months and in nearing the end of testing phase

ORM: https://github.com/MasoniteFramework/orm

It will be used as the primary ORM for the Masonite framework: https://github.com/MasoniteFramework/masonite

> the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;

The current name `maker` has never been in use and seems like a squatted package name

> download statistics on the Package Index for the existing package indicate project is not being used; 

Download statistics show that is has not been downloaded at all and is used in exactly 0 projects. It only has 4 releases all within the same day and according to library.io it is not being used or downloaded anywhere: https://libraries.io/pypi/maker

> the maintainers of the Package Index don't have any additional reservations.

There are no maintainers on this package index.

**Maintenance or replacement?**

I plan to release new code under the new name. It will be an ORM i have been working on for the Masonite community (https://github.com/MasoniteFramework/masonite) for several months. Repo is found here: https://github.com/MasoniteFramework/orm

**Contact and additional research**

I have contacted the PYPI user using the publicly available email address

<img width="951" alt="Screen Shot 2020-12-02 at 8 50 07 AM" src="https://user-images.githubusercontent.com/20172538/100880985-667caa80-347b-11eb-802d-1bf91962e239.png">

Thank you in advance. Hope to hear back soon

**Comment by josephmancuso** [comment]
As a quick follow up, they still have not answered my request

**Comment by yeraydiazdiaz** [comment]
Hello @josephmancuso, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for reply before proceeding with the transfer.

**Comment by josephmancuso** [comment]
@yeraydiazdiaz Thank you I appreciate it

**Comment by yeraydiazdiaz** [comment]
I have not received reply from the current owner. Transfer complete.
