### ISSUE TITLE
Issue: Limit Request: pyFAST - 350 MB

### ISSUE THREAD

**Issue by smistad** [pypa/pypi-support#777]
**Project**
Package name pyFAST https://pypi.org/project/pyFAST are python bindings for the FAST framework https://github.com/smistad/FAST.

FAST is an open-source cross-platform framework with the main goal of making it easier to do high-performance processing and visualization of medical images on heterogeneous systems utilizing both multi-core CPUs and GPUs. To achieve this, FAST use modern C++, OpenCL and OpenGL, and includes support for many different streaming and image formats, as well as inference engines which provides fast deep neural network image analysis.

**Does this project already exist?**
Yes, https://pypi.org/project/pyFAST

**Size of release/project**
I am hitting the upload file size limit. The size of the pip wheel with all features enabled is currently 293 MB, thus 300 MB should suffice for now.

**Which indexes**
Both

**Reasons for the request**

FAST includes several neural network inference engines and ultrasound/3d camera streaming through third party binaries which are quite large. Including all of these in the pip package leads to a size of up to 300 MB.

The release size might increase slightly in the future. Thus a limit of 350 MB would be even better.

**Comment by di** [comment]
I've set the upload limit for `pyFAST` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

**Comment by smistad** [comment]
While the windows wheel was less than 300 MB, the linux wheel was not. The linux wheel is 352 MB. Is it possible to get the limit increased to 360MB? 

To limit the amount of space usage, I have now compiled the wheels using the py_limtied_api abi3, so only one wheel is needed per OS, instead of one wheel per python version and OS.
