### ISSUE TITLE
Limit Request: Intel corp- up to 700MB

### ISSUE THREAD

**Issue by prstrnn** [pypa/pypi-support#779]
I'm from Intel corp. and we are releasing new software in PyPi.
We found that several projects hit project limit size, so we are requesting to extend limits for these projects:

**Exposure for us: Critical
Priority for us: Showstopper**

IntelAutomationEngineering - PyPI account we will use to upload packages.

Size of release/project
**dpcpp-cpp-rt up to 200MB
onednn-cpu-iomp up to 200MB
onednn-cpu-iomp up to 200MB
daal up to 700 MB
ipp up to 600 MB
mkl up to 800 MB**

Which indexes
both

Reasons for the request
It's Intel's software that contains a lot of optimizations for the different hardware, that's why it has so big size.
Expected that future releases will be greater than current.

**Comment by prstrnn** [comment]
@di @pjenvey can you please assist with that?

**Comment by di** [comment]
I've set the upload limit for the following on PyPI:

* `dpcpp-cpp-rt` to 200 MB
* `onednn-cpu-iomp` to 200 MB
* `ipp` to 600 MB
* `daal` to 700 MB
* `mkl` to 800 MB

Please be mindful of the frequency of releases at that size.
