### ISSUE TITLE
Limit Request: [multiple packages] -- 300-800 MB

### ISSUE THREAD

**Issue by prstrnn** [pypa/pypi-support#782]
I'm from Intel corp. and we are releasing new software in PyPI.

We found that several projects hit project limit size, so we are requesting to extend limits for these projects:

IntelAutomationEngineering - PyPI account we will use to upload packages.

**Size of release/project**

- mkl-dpcpp up to 500 MB
- mkl-static up to 500 MB
- onednn-cpu-tbb up to 300 MB
- ipp-static up to 400 MB
- opencl-rt up to 300 MB
- daal-static up to 800MB

**Which indexes**
both

**Reasons for the request**

It's Intel's software that contains a lot of optimizations for the different hardware, that's why it has so big size.
Expected that future releases will be greater than current.

**Exposure for us: Critical
Priority for us: Showstopper**

**Comment by prstrnn** [comment]
@di @pjenvey can you please assist with that?

**Comment by prstrnn** [comment]
Sorry, also daal_static up to 800MB

**Comment by pradyunsg** [comment]
This is the 3rd time I'm asking this.

> Please elaborate further on why these packages need 500 MB or more, and why distributing the various optimised binaries via a different channel (such as nltk's data downloader) is not a viable solution for you.
> 
> Further, what is the expected size of future releases? Will they be 10% bigger? 50%? 2x?

I'm not a PyPI admin, but I don't think they'll be raising these limits until we get a reasonable response that establishes more context, and provides more information than "It's Intel's software that contains a lot of optimizations for the different hardware".

**Comment by pradyunsg** [comment]
I've also taken the liberty to edit the first post, so that it better follows the issue template.

**Comment by prstrnn** [comment]
`Further, what is the expected size of future releases? Will they be 10% bigger? 50%? 2x?`

I've taken limits with expected size increasing, but to can be grouth in about 15% I guess

**Comment by prstrnn** [comment]
@pradyunsg I appreciate your such a big help in our situation!

**Comment by prstrnn** [comment]
> This is the 3rd time I'm asking this.
> 
> > Please elaborate further on why these packages need 500 MB or more, and why distributing the various optimised binaries via a different channel (such as nltk's data downloader) is not a viable solution for you.
> > Further, what is the expected size of future releases? Will they be 10% bigger? 50%? 2x?
> 
> I'm not a PyPI admin, but I don't think they'll be raising these limits until we get a reasonable response that establishes more context, and provides more information than "It's Intel's software that contains a lot of optimizations for the different hardware".

But previous request was approved, I've just missed names for some projects because of misunderstanding structure in our products. Dustin @di helped us with other request.

**Comment by psolovie** [comment]
Hello admins, it is an urgent request that blocks Intel corp bits delivery to the pypi.org. What exact information do you require from us to move forward with the request completion? 

@di @pradyunsg @pjenvey

**Comment by ewdurbin** [comment]
At this point in time, the `IntelAutomationEngineering` user is responsible for just over 10GiB of PyPI's current size. Given the criticality of this release pipeline as described, if the team responsible for it would like to contact the PSF regarding sponsorship of PyPI, we would love to hear from you at sponsors@python.org.

I've set the upload limit for the following on PyPI:

- mkl-dpcpp up to 500 MB
- mkl-static up to 500 MB
- onednn-cpu-tbb up to 300 MB
- ipp-static up to 400 MB
- opencl-rt up to 300 MB
- daal-static up to 800MB

Please be mindful of the frequency of releases at that size.
