### ISSUE TITLE
Limit Request: pyreportjasper - 200 MB

### ISSUE THREAD

**Issue by jadsonbr** [pypa/pypi-support#785]
**pyreportjasper**
https://pypi.org/project/pyreportjasper/

**Does this project already exist?**
Yes

**Size of release/project**
200 MB

**Which indexes**
PyPI, and Test PyPI

**Reasons for the request**
This library is useful for generating reports through jasperreport which is written in java so it is necessary to send the jasperreport jar files and their dependencies and they may increase in the future.

**Comment by jadsonbr** [comment]
@di Would you have a look at that?

**Comment by jadsonbr** [comment]
@ewdurbin Would you have a look at that?

**Comment by di** [comment]
Please do not make repeated comments or otherwise spam us with notifications on these issues. It does not help in any way whatsoever. If it continues in the future, we will not allow you to comment in this repository, please consider this a warning.

**Comment by jadsonbr** [comment]
I understand and accept. More should review the process of releasing these issues. I've seen cases here with more than 3 days to get to look. I apologize for the inconvenience, but I would not insist if it were not really necessary.

Thanks for understanding

**Comment by jadsonbr** [comment]
Can I help with something? This process is taking too long. Today is seven days

**Comment by di** [comment]
I've set the upload limit for `pyreportjasper` to 200 MB on PyPI and TestPyPI.
