### ISSUE TITLE
DMCA Report, Who to contact?

### ISSUE THREAD

**Issue by snooppr** [pypa/pypi-support#786]
A copyright infringing package has been placed on PyPi.  The only address I found for notification (code of conduct): conduct@pypa.io
I wrote a detailed report and signed it electronically.

There was a response that I should apply for this DMCA here (if I understood correctly).

Tell me where to go with a report on copyright infringement (my personal data is in the report).

**Comment by pradyunsg** [comment]
Based on https://www.python.org/dev/peps/pep-0541/#intellectual-property-policy, I believe you're looking for legal@python.org.

**Comment by snooppr** [comment]
Thank you, promptly.

**Comment by snooppr** [comment]
@pradyunsg 
Hey. Is there any other way to contact pypi to resolve the DMCA issue?
The letter sent to legal@python.org remains unanswered.

**Comment by pradyunsg** [comment]
Not that I'm aware of, no. I _think_ legal@python.org is the best point of contact for DMCA stuff -- it'd probably be a good idea to send them a nudge as a reply to the same email?

Beyond that though, I'm afraid I don't have much to help you with here.

**Comment by di** [comment]
Closing -- legal@python.org is the correct place to request DMCA takedowns for PyPI.
