### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by CyanBook** [pypa/pypi-support#788]
Request for account recovery.

## PyPI Username

`CyanBook`

---

##  Reason for request

Reason: I changed my phone and I lost all my one-time codes on my phone, I was using Google Authenticator and I thought they were synchronized with my Google account but they're not. Please help me recover at least this account!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by CyanBook** [comment]
@ewdurbin I created the branch you requested.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by CyanBook** [comment]
Thanks!
