### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by erfannariman** [pypa/pypi-support#789]
Request for account recovery.

## PyPI Username

`enariman`

---

##  Reason for request

Reason: 
Lost both access to 2FA app + recovery keys after phone got stolen.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by erfannariman** [comment]
Again, thank you for taking the time to reset my password and 2FA. I stored the recovery codes somewhere safe now.
