### ISSUE TITLE
PEP 541 Request: gloss

### ISSUE THREAD

**Issue by ucodery** [pypa/pypi-support#790]
**Project to be claimed**

`gloss`: https://pypi.org/project/gloss/

**Your PyPI username**

`ucodery`: https://pypi.org/user/ucodery/

**Reasons for the request**

Before creating this project, I searched PyPI and did not find anyone using the name. Great! So I uploaded my package to https://test.pypi.org/project/gloss/1.0/. This also worked, so I thought the name was mine; nope. After attempting an upload to the real pypi.org I get the error
```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'ucodery' isn't allowed to upload to project 'gloss'. See https://pypi.org/help/#project-name for more information.
```
The linked page lists three reasons to get this error

* The project name conflicts with a Python Standard Library module from any major version from 2.5 to present.
  * To my knowledge there was never a standard library module or in fact object named `gloss`. Checked in currently supported versions.
* The project name has been explicitly prohibited by the PyPI administrators. For example, pip install requirements.txt is a common typo for pip install -r requirements.txt, and should not surprise the user with a malicious package.
  * I do not know how to find a complete list. This seems most likely the cause but I don't know what malice this name would do.
* The project name has been registered by another user, but no releases have been created.
  * Again, I have searched PyPI and pip and come up empty. And if a user has claimed this name and not used it, they did not claim the test.pypi name and now I have that.
 
**Maintenance or replacement?**

A different package since none currently exists.
https://github.com/ucodery/gloss

**Contact and additional research**

The package page does not exist, so unable to lookup any author information/ homepage.

**Comment by yeraydiazdiaz** [comment]
Hello @ucodery, I can confirm the project exists but has no releases and is therefore considered invalid, in this situations PyPI returns a 404 but the project does exist.

I will attempt to contact the owner and allow one week for reply before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @jezdez who seems to be the owner of the project.

**Comment by jezdez** [comment]
@yeraydiazdiaz I've invited the ucodery PyPI user to the project as owner.

@ucodery Feel free to remove me from the project on PyPI after you accepted the invite. Thanks!

**Comment by yeraydiazdiaz** [comment]
Thanks @jezdez 👍🏻

**Comment by ucodery** [comment]
Yes, thank you @jezdez!
