### ISSUE TITLE
Mass name squat by user: Collie

### ISSUE THREAD

**Issue by hentai-chan** [pypa/pypi-support#791]
I'd like to submit multiple projects from the same user to the PyPI team for violating PEP 541 by accusing [`Collie`](https://pypi.org/user/Collie/) of being guilty of name squatting on more than one occasion. I don't wish to take ownership of any of these project names at the moment. My intention is to reclaim these names back for the community. 

**Project to be claimed**

1. `PROJECT_NAME`: https://pypi.org/project/solidarity
2. `PROJECT_NAME`: https://pypi.org/project/author
3. `PROJECT_NAME`: https://pypi.org/project/method
4. `PROJECT_NAME`: https://pypi.org/project/maintainer
5. `PROJECT_NAME`: https://pypi.org/project/sharper
6. `PROJECT_NAME`: https://pypi.org/project/sharpen
7. `PROJECT_NAME`: https://pypi.org/project/ue
8. `PROJECT_NAME`: https://pypi.org/project/cz
9. `PROJECT_NAME`: https://pypi.org/project/ce
10. `PROJECT_NAME`: https://pypi.org/project/vs
11. `PROJECT_NAME`: https://pypi.org/project/doer
12. `PROJECT_NAME`: https://pypi.org/project/lolita
13. `PROJECT_NAME`: https://pypi.org/project/strategy
14. `PROJECT_NAME`: https://pypi.org/project/nanshan
15. `PROJECT_NAME`: https://pypi.org/project/peking
16. `PROJECT_NAME`: https://pypi.org/project/shanghai
17. `PROJECT_NAME`: https://pypi.org/project/shenzhen
18. `PROJECT_NAME`: https://pypi.org/project/sz
19. `PROJECT_NAME`: https://pypi.org/project/luminary
20. `PROJECT_NAME`: https://pypi.org/project/victory
21. `PROJECT_NAME`: https://pypi.org/project/approach
22. `PROJECT_NAME`: https://pypi.org/project/apps
23. `PROJECT_NAME`: https://pypi.org/project/appx
24. `PROJECT_NAME`: https://pypi.org/project/prosperity
25. `PROJECT_NAME`: https://pypi.org/project/prosper
26. `PROJECT_NAME`: https://pypi.org/project/thrive
27. `PROJECT_NAME`: https://pypi.org/project/rios
28. `PROJECT_NAME`: https://pypi.org/project/prominent
29. `PROJECT_NAME`: https://pypi.org/project/eminent
30. `PROJECT_NAME`: https://pypi.org/project/fskit
31. `PROJECT_NAME`: https://pypi.org/project/ultra
32. `PROJECT_NAME`: https://pypi.org/project/fsk
33. `PROJECT_NAME`: https://pypi.org/project/extra
34. `PROJECT_NAME`: https://pypi.org/project/keysys
35. `PROJECT_NAME`: https://pypi.org/project/mainstream
36. `PROJECT_NAME`: https://pypi.org/project/filter
37. `PROJECT_NAME`: https://pypi.org/project/tough
38. `PROJECT_NAME`: https://pypi.org/project/tech
39. `PROJECT_NAME`: https://pypi.org/project/gradle
40. `PROJECT_NAME`: https://pypi.org/project/center
41. `PROJECT_NAME`: https://pypi.org/project/flyweight
42. `PROJECT_NAME`: https://pypi.org/project/pku
42. `PROJECT_NAME`: https://pypi.org/project/tbsi
43. `PROJECT_NAME`: https://pypi.org/project/sigs
44. `PROJECT_NAME`: https://pypi.org/project/tsinghua
45. `PROJECT_NAME`: https://pypi.org/project/innovator
46. `PROJECT_NAME`: https://pypi.org/project/innovation
47. `PROJECT_NAME`: https://pypi.org/project/creation
48. `PROJECT_NAME`: https://pypi.org/project/pepsys
49. `PROJECT_NAME`: https://pypi.org/project/expert
50. `PROJECT_NAME`: https://pypi.org/project/bazel
51. `PROJECT_NAME`: https://pypi.org/project/enter
52. `PROJECT_NAME`: https://pypi.org/project/soft
53. `PROJECT_NAME`: https://pypi.org/project/ide
54. `PROJECT_NAME`: https://pypi.org/project/scientific

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/hentaichan/

**Reasons for the request**
I believe this request is reasonable because the projects are all empty and contain no code. They all have been created between April 12, 2020 and September 26, 2020, which further reinforces my suspicion  that Collie is not acting in good faith.

**Maintenance or replacement?**
Since there is no code to maintain (and I don't have the time nor resources to create as many projects all on my own), I suggest to make these names available again to anyone that wants to distribute code via PyPI under any of these project names.

**Contact and additional research**
The author of these projects did not provide a way that would make it possible to reach out to him/her (see also: empty author tag in all these projects). None of these projects are hosted public (e.g. on GitHub or GitLab), which further increases the difficulty of contacting Collie.

**Comment by kinow** [comment]
This looks a lot like when people buy domains for parking, expecting to sell later. But not sure what's this user's intentions with so many empty repositories.

The folks working with security, could possibly run a weekly query, looking for users that created more than 2 or three empty repositories in the last week and flag them for inspection I think.

**Comment by jpic** [comment]
Confirming the issue, would like the apps namespace myself.

**Comment by hentai-chan** [comment]
In addition to my previous submission I'd like to point out that Collie is still adding uploading empty packages as we speak. For the sake of completeness, please consider also removing the following packages from PyPI. It may also be necessary to terminate his account and ban his IP to prevent him/her from registering a new account:

- 56: `PROJECT_NAME`: organization
- 56: `PROJECT_NAME`: organization
- 56: `PROJECT_NAME`: organization

**Comment by nathancooperjones** [comment]
I am hoping to open-source a library called `collie` to `PyPI` very soon, but the name is taken by this user. Just like all other 118 projects uploaded by this user, it is an empty library. 

I am hoping we can remove this package and user soon. 

https://pypi.org/project/collie/

**Comment by yeraydiazdiaz** [comment]
@nathancooperjones please open a separate PEP 541 request if you're interested in the name.

**Comment by nathancooperjones** [comment]
> @nathancooperjones please open a separate PEP 541 request if you're interested in the name.

I've gone ahead and made that issue [here](https://github.com/pypa/pypi-support/issues/1091) - thank you!!

**Comment by needs-coffee** [comment]
this user is still uploading dozens of empty projects

**Comment by di** [comment]
Invalid namesquatting packages have been removed.
