### ISSUE TITLE
Limit Request: cloudViewer - 100GB (total)

### ISSUE THREAD

**Issue by Asher-1** [pypa/pypi-support#795]
**Project**
cloudViewer

**Does this project already exist?**
yes

**Size of release/project**
100GB

**Which indexes**
both

**Reasons for the request**

**Comment by di** [comment]
Hi @Asher-1, can you provide a reason for this request? A 100GB total project size would make this one of the largest projects on PyPI.

**Comment by di** [comment]
Closing due to lack of response.
