### ISSUE TITLE
IBM Corporation Copyrighted Files

### ISSUE THREAD

**Issue by pinegar** [pypa/pypi-support#797]
I discovered 142 files in the decimaltestdata directory of the Python 3.7.8 product that are copyrighted by the IBM Corporation.  There is no clear licensing for these files.  
 
We would like to use these files, but there is no license in the  product download that permits us to do so.  Please provide terms of use for these files.

**Comment by ewjoachim** [comment]
If I understand your problem correctly, you're referring to files in the source code of cPython : https://github.com/python/cpython/commits/master/Lib/test/decimaltestdata

You're in the pypi-support repository, which relates to administrative issues on the [PyPI](https://pypi.org) website. See the [Readme](https://github.com/pypa/pypi-support/blob/master/README.md) for what this repository is for.

The help you need will likely be found in the Python user forum, https://discuss.python.org.
