### ISSUE TITLE
Projects disappeared from account

### ISSUE THREAD

**Issue by awsjoez** [pypa/pypi-support#798]
Request for account recovery.

## PyPI Username

`aws-neuron-pypi-admin@amazon.com`

---

##  Reason for request

Reason:
We created an empty project, `mxnet-neuron`, back in July, by uploading a wheel and then deleting it. Our intention was to claim the project name, until we are ready to push the real packages.

However, upon checking today, we realized the project is no longer visible from our account. Further, we can't upload new packages under the project name, using the account, as it shows the following error:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'mxnet-neuron' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

Please help us understand why the project disappeared, and who, if not us, owns the package now. Thank you!

**Comment by di** [comment]
It looks like this was accidentally interpreted as a typosquat and blocked (the volunteer was not aware of https://github.com/pypa/pypi-support/issues/522 it seems).

I removed the block, you should be able to upload now. Sorry for the inconvenience!
