### ISSUE TITLE
PEP 541 Request: rene

### ISSUE THREAD

**Issue by lycantropos** [pypa/pypi-support#799]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/rene

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/lycantropos

**Reasons for the request**

It is an empty project and haven't been updated since Sep 28, 2016.

**Maintenance or replacement?**

Since it is an empty one I would like to reuse this name for one of my computational geometry-related projects.

**Contact and additional research**

There is an email address on the [`morpy`](https://pypi.org/project/morpy/) project owned by this user, but I haven't had any response for a week now.
![image](https://user-images.githubusercontent.com/15193952/102611072-50d7d800-413f-11eb-9039-6597bd11c005.png)

**Comment by lycantropos** [comment]
Any update on this? There is still no answer from maintainer (who can be @samskillman, at least they have the same profile picture).

**Comment by lycantropos** [comment]
3 months have passed since I opened this issue, how can I find out if there were any progress and how long it may take?

**Comment by yeraydiazdiaz** [comment]
Hello @lycantropos, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Tagging GitHub user @samskillman who appears to be the owner of the project. I will consider this the attempt of contact.

**Comment by samskillman** [comment]
Apologies I just have missed previous contact. Happy to transfer or simply
delete the project. Let me know which you prefer.

**Comment by lycantropos** [comment]
We can transfer ownership if it's an option.

**Comment by samskillman** [comment]
Ok by me.

**Comment by yeraydiazdiaz** [comment]
Thank you @samskillman
