### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `cooltools`

### ISSUE THREAD

**Issue by nvictus** [pypa/pypi-support#8]
We @nvictus and @golobor would like to transfer the name of the abandoned project `cooltools` to both of us.

There is no email associated with the author on the Package Index, no documentation on the Index, and the listed Home Page (GitHub repo) has either been deleted or is publicly inaccessible. The source distribution and Github account do list a single gmail address (rtansf@gmail.com). We have attempted to contact @rtansf several times (by email and LinkedIn) with no response.

We are part of a research lab at MIT working on genome organization. Our project, called cooltools, was created before cooltools appeared on the Package Index. It is a package of tools for analyzing specialized genomic data stored in files with the extension “.cool”, following a tradition in bioinformatics of "file extension" + tools: e.g., samtools, vcftools, bedtools. Already, several colleagues have contacted us for troubleshooting because they pip-installed the cooltools on PyPI by accident.

Because we have not been able to reach the author, no releases have been made in over a year, and the listed homepage is unavailable, the cooltools project currently on the Package Index appears to be abandoned. The download statistics on the Package Index for the existing package indicate that project is not being used -- indeed a number of those downloads were intended to be for our package.

Thank you for considering our request.

**Comment by yeraydiazdiaz** [comment]
Given the lack of response from @rtansf I've contacted an admin to perform this transfer ourselves.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by nvictus** [comment]
@jamadden @yeraydiazdiaz @ewdurbin Thank you!!!
