### ISSUE TITLE
[mantis-ml-1.5.0]: update size limit to 75MB

### ISSUE THREAD

**Issue by dvitsios** [pypa/pypi-support#80]
**Project**
mantis-ml 1.5.0
[https://pypi.org/project/mantis-ml/1.5.0](https://pypi.org/project/mantis-ml/1.5.0)

**Size of release**
75MB

**Which indexes**
PyPI

**Reasons for the request**
This is a software tool used for research purposes, specifically for prioritising genes across various diseases with machine learning. That requires a rich feature set embedded in the tool for training the models, thus these data need to be part of it.

**Comment by jamadden** [comment]
The upload limit for mantis-ml has been set to 100MB on pypi.org
