### ISSUE TITLE
Account acquisition request

### ISSUE THREAD

**Issue by sgillies** [pypa/pypi-support#803]
Happy December Solstice, PyPI team!

I work at [Mapbox](https://mapbox.com) and would like to acquire the inactive `mapbox` account. 

## PyPI Username

`mapbox`

---

##  Reason for request

Acquiring the [`mapbox`](https://pypi.org/user/mapbox/) account helps give users of my team's software a little more protection against malicious packages.

My team at Mapbox has 25 projects at [`mapboxci`](https://pypi.org/user/mapboxci/) because `mapbox` was taken and in 2017 there was no supported process for acquiring inactive accounts. I sent an email to support-requests on Feb 13, 2017 pointing out that the account is inactive and that remains true.

```
>>> with ServerProxy("https://pypi.python.org/pypi") as proxy:
...     print(proxy.user_packages("mapbox"))
... 
[]
```

On May 29, 2020 I got an email from Sumana Harihareswara explaining that I should submit a new support request.

```
From: Sumana Harihareswara <brainwane@users.sourceforge.net>
Date: Fri, May 29, 2020 at 8:09 PM
Subject: [pypi:support-requests] #711 Acquiring the inactive account 'mapbox'
To: [pypi:support-requests] <711@support-requests.pypi.p.re.sourceforge.net>


status: open --> closed
Comment:
I'm sorry for the wait.

We no longer use this repository since it's about the legacy PyPI codebase. There's a new support ticket queue at https://github.com/pypa/pypi-support/ and I ask that, if you are still interested in this request, you re-open your issue there https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within the new ticket queue.

Until then, unfortunately, all I can advise you to do is wait. My apologies.
```

As I said in my original email, I believe the `mapbox` account was created by a former Mapbox employee, but cannot find any clue as to who or when.

**Comment by ewdurbin** [comment]
Hello @sgillies please email support@pypi.org with what email address you would like the User configured with.

**Comment by sgillies** [comment]
@ewdurbin I've emailed and will go through the password recovery process today. Thanks!

**Comment by ewdurbin** [comment]
The requested address is already in use by the `mapboxci` User on PyPI. We are unable to associate an address with multiple accounts.

**Comment by ewdurbin** [comment]
With updated email address, this is all set. A password reset has been issued, please complete that to gain access to the account.

**Comment by sgillies** [comment]
Thanks @ewdurbin ! :heart:
