### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by twang817** [pypa/pypi-support#805]
Request for account recovery.

## PyPI Username

`twang817`

---

##  Reason for request

Reason: Lost access to email address.  The joinem account was a company email.  That company is now out of business.

**Comment by ewdurbin** [comment]
Hello @twang817. I see that there are numerous references to your august8.net email address in the public metadata for historical releases of projects associated with this user, as well as your GitHub user profile.

Is this address acceptable?

**Comment by ewdurbin** [comment]
If so, the user `twang2` on PyPI will need to be deleted in order to associate the address with `twang817`.

**Comment by twang817** [comment]
I have pypi projects there as well.  If possible, it would be most preferable to merge the two accounts -- I only created twang2 because I lost access.

If not, then you can use "twang817@august8.net".

**Comment by ewdurbin** [comment]
I have updated the primary email address for the `twang817` User as requested.
