### ISSUE TITLE
PEP 541 Request: u

### ISSUE THREAD

**Issue by pavel-kirienko** [pypa/pypi-support#806]
Greetings,

I would like to transfer the project [**`u`**](https://pypi.org/project/u/) from its current owner over to https://pypi.org/user/uavcan/.

In this transaction, I represent the recipient, and the owner is reachable here on GitHub as @srid. Unfortunately, it does not appear to be possible for us to arrange the transfer on our own because the current owner of the project in question has lost access to his PyPI account. @srid can further verify this transaction if reached via email.

Thanks in advance!

**Comment by srid** [comment]
I authorize this transfer. Go ahead. I relinquish access to `u`.

**Comment by ewdurbin** [comment]
@srid please open an account recovery request in order to verify ownership of the account/project to proceed.

**Comment by srid** [comment]
Make it easier for me, folks. 

https://github.com/pypa/pypi-support/issues/377#issuecomment-629802909

**Comment by ewdurbin** [comment]
@srid it would be easiest for everyone if we proceeded to help you regain access to your account to perform these transfers. Please open an Account Recovery issue here and I will happily help you.

**Comment by pavel-kirienko** [comment]
@ewdurbin the project description links Sridhar's GitHub page since 2010:

> Just trying to see if single-name packages can be registered; also reserving 'u' for a potential package of mine. If you want this name, contact me at ***github.com/srid***

Would you not consider it to be adequate proof of ownership? Even if not, per PEP 541 it is an invalid project anyway. I'm hoping to get this resolved without involving Sridhar.

**Comment by pavel-kirienko** [comment]
@ewdurbin can we please advance this issue?

**Comment by ewdurbin** [comment]
@pavel-kirienko I generally don’t work on PEP 541 requests until they are processed by a moderator. As suggested earlier, I *can* help you recover access to your account if you file an appropriate issue.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
