### ISSUE TITLE
Issue: Limit Request: Open3D - File size

### ISSUE THREAD

**Issue by ssheorey** [pypa/pypi-support#809]
**Project**
Package Open3D
PyPI page: https://pypi.org/project/open3d/
Github page: https://github.com/intel-isl/Open3D/
Project homepage: http://www.open3d.org/

**Does this project already exist?**
Yes

**Size of release**
Current release: 189MB
Please provide a 300MB or higher limit since the next release (in a couple of months) will be larger.

**Which indexes**
PyPI

**Reasons for the request**
Open3D is an open-source library that supports rapid development of software that deals with 3D data. The Open3D frontend exposes a set of carefully selected data structures and algorithms in both C++ and Python. The backend is highly optimized and is set up for parallelization. We welcome contributions from the open-source community.

Open3D is a cross-platform library that provides optimized compiled binary code for both CPU and GPU (NVIDIA CUDA) hardware platforms in a single package. This allows users to seamlessly run software using Open3D both with and without GPUs. Open3D is a rapidly growing project and we are adding new functionality with each release. We have added major 3D machine learning, visualization and sensor interface functionality in this release. We also plan to add more functionality in future releases.

**Comment by di** [comment]
I've set the upload limit for `Open3D` to 300 MB on PyPI.
