### ISSUE TITLE
Limit Request: Panda3D - 150 MB

### ISSUE THREAD

**Issue by rdb** [pypa/pypi-support#810]
**Project**
https://pypi.org/project/Panda3D
https://www.panda3d.org/
https://github.com/panda3d/panda3d/

**Does this project already exist?**
Yes

**Size of release/project**
110 MB for macOS, 50-60 MB for other platforms

**Which indexes**
PyPI (but both is fine too in case we want to use Test PyPI)

**Reasons for the request**
Panda3D is a C++ game engine with Python bindings.

Our wheels are typically 50-60 MB, depending on the platform.  However, we want to start uploading universal2 wheels for macOS in our new release, supporting the new arm64 architecture as well as the x86_64 architecture.  Universal 2 binaries are twice as large as regular ones, so the wheels for macOS 11 became larger than 100 MB.

I do not expect major increases in the future, but 150 MB should be enough for now.

Thanks for your consideration!

**Comment by di** [comment]
I've set the upload limit for `Panda3D` to 200 MB on PyPI and TestPyPI.
