### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ParthS007** [pypa/pypi-support#811]
Request for account recovery.

## PyPI Username

`ParthS007`

---

##  Reason for request

Reason: Showing Invalid TOTP code on entering the 2FA code from Google authenticator app and don't have recovery codes.

Thanks for the help :)

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ParthS007** [comment]
Instructions followed and responded back. Thanks

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
