### ISSUE TITLE
PEP 541 Request: ed

### ISSUE THREAD

**Issue by eumiro** [pypa/pypi-support#813]
**Project to be claimed**

`ed`: https://pypi.org/project/ed

**Your PyPI username**

`eumiro`: https://pypi.org/user/eumiro

**Reasons for the request**

The project has apparently been abandoned. The project is described as a sample package, its last version is over one year old, the linked repo does not exist.

**Maintenance or replacement?**

Replacement. I plan to rename my repo https://github.com/eumiro/pyed to `ed` and release the package under that name.

**Contact and additional research**

I have sent an e-mail to the linked address of the maintainer over a week ago, but there was no reply although the author was active on his github account in the meantime.

**Comment by yeraydiazdiaz** [comment]
Hello @eumiro, I can confirm the project has no functionality and is therefore considered invalid. The project's setup.py mentions GitHub user @eduard93, I will consider this the attempt of contact and allow one week for a reply before transferring the project.

**Comment by yeraydiazdiaz** [comment]
I have not received reply from the current owner. Transfer complete.

**Comment by eumiro** [comment]
Thank you, @yeraydiazdiaz !
