### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Skyross** [pypa/pypi-support#814]
Request for account recovery.

## PyPI Username

`Skyross`

---

##  Reason for request

Reason:
  - Lost 2FA authentication app and recovery codes too :(

**Comment by Skyross** [comment]
Anyone can help?

**Comment by Skyross** [comment]
@ewdurbin sorry for bothering you but it a little bit urgent for me. How can I assist you to figure this issue out? What info do I need to provide you to prove myself as an owner?

**Comment by ewdurbin** [comment]
Unfortunately neither of the projects associated with the `Skyross` User have publicly accessible repositories listed in their metadata. This makes verification of ownership using our standard processes for 2FA reset impossible.

I've emailed the Primary email address listed on the account with further instructions.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by Skyross** [comment]
Thank you for the help!
