### ISSUE TITLE
Limit Request: MindSpore - 200 MB

### ISSUE THREAD

**Issue by leonwanghui** [pypa/pypi-support#818]
**Project**

Package name: **mindspore**, **mindspore-gpu**, **mindspore-ascend**
- https://pypi.org/project/mindspore
- https://pypi.org/project/mindspore-gpu
- https://pypi.org/project/mindspore-ascend

GitHub page: https://github.com/mindspore-ai/mindspore
Gitee page: https://gitee.com/mindspore/mindspore
Project homepage: https://www.mindspore.cn/en

**Does this project already exist?**

Yes

**Size of release/project**

* **mindspore**: 85.2MB for linux_x86_64, 30.9MB for win_amd64
* **mindspore-gpu**: 110MB for linux_x86_64
* **mindspore-ascend**: 99.6MB for aarch64

Please provide a 200MB or higher limit since the release size of `mindspore-gpu` has been hit the file size limit and the next release (in a couple of months) of `mindspore` and `mindspore-ascend` will be larger.

**Which indexes**

PyPI

**Reasons for the request**

MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios. MindSpore is designed to provide development experience with friendly design and efficient execution for the data scientists and algorithmic engineers, native support for Ascend AI processor, and software hardware co-optimization. At the meantime MindSpore as a global AI open source community, aims to further advance the development and enrichment of the AI software/hardware application ecosystem.

Our release would be published every three month with more functionalities, so the additional increase in the future would be appreciated.

Thanks for your consideration!

**Comment by di** [comment]
I've set the upload limit for `mindspore`, `mindspore-gpu`, and `mindspore-ascend` to 200 MB on PyPI.

**Comment by leonwanghui** [comment]
Thanks @di !!!
