### ISSUE TITLE
Recover access

### ISSUE THREAD

**Issue by scailer** [pypa/pypi-support#82]
Hello,

I lost access to my account https://pypi.org/user/scailer/
Then I confused in new UI and create new account https://pypi.org/user/Dmitry.Vlasov/ 

Can you help me - merge them or reassign projects to new account or setup email as in github account (it public).

As proof, all projects link with my projects on github.

Thank you,
Dmitrii Vlasov.

**Comment by ewdurbin** [comment]
Hello @scailer, please email ernest@python.org from the primary email address associated with your PyPI account to proceed with recovery.

**Comment by scailer** [comment]
Hello @ewdurbin. I'm sended email from scailer@veles.biz (my primary address) and scailer@yandex.ru.
I'm tried restore "scailer"-account with all my email addresses, and received "No user found with that username or email". I think, It created without email.

**Comment by ewdurbin** [comment]
Hi @scailer, I last sent a message on January 16, and again just now asking for confirmation to complete your account recovery. Please respond there.

**Comment by scailer** [comment]
Hi @ewdurbin, I apologize for delay, I have sent email from scailer@yandex.ru.

**Comment by ewdurbin** [comment]
Account primary email has been updated and a password reset initiated. You should be able to recover access to your account after completing the password reset.

Email was updated to a previously referenced email in multiple uploads.

**Comment by scailer** [comment]
Thanks a lot!
