### ISSUE TITLE
Size limit increase for tensorflow_cpu (total) to 60GB

### ISSUE THREAD

**Issue by mihaimaruseac** [pypa/pypi-support#822]
**Project**: https://pypi.org/project/tensorflow-cpu/
**Does this project already exist?**: Yes
**Size of release/project**: 60GB
**Which indexes**: PyPI

**Reasons for the request**:
We need to do patch releases for TensorFlow from 1.15 to 2.3 but we cannot upload the patched pips as we have reached maximum project size.

This is the CPU version of the project which has minimal code dependencies but it has reached previously configured limits (40GB)

The GPU and main versions of the project have limits in hundreds of GB, but increasing this project's limit to 60GB should be enough.

Thank you

**Comment by di** [comment]
I've set the total upload limit for `tensorflow-cpu` to 60 GB on PyPI.
