### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by e-kirkland** [pypa/pypi-support#823]
Request for account recovery.

## PyPI Username

`eddiekirkland`

---

##  Reason for request

Reason:

I'm sorry for the bother, I've lost access to my 2FA for my PyPI account and can no longer login. I can reset password and can see the email where I set up 2FA, but no longer have access to it or the recovery codes. Please help however you can. Thank you!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by brianmanderson** [comment]
Lost access to my original e-mail as well.. However! I was able to contact my institution and get access back, so I will begin changing (and creating recovery codes) now

All good, thank you, and feel free to close the ticket!
