### ISSUE TITLE
PEP 541 Request: rivet

### ISSUE THREAD

**Issue by Geoiv** [pypa/pypi-support#825]
`PROJECT_NAME`: https://pypi.org/project/rivet

**Your PyPI username**

`USER`: https://pypi.org/user/nhdsdatasci

**Reasons for the request**
I believe that the current `rivet` project has been abandoned, if it ever even had maintenance in the first place:
* The project has had a single release, version `0.0.0`, over three years ago and it has not been updated since.
* The released files of this single release contain close to nothing - no documentation, no code, just a template `setup.py` and empty text files.
* There is no linked home page or repository for the project.

These points seem to indicate that this package was either uploaded and then abandoned immediately, or was simply being used to reserve the name and never was followed up on.

**Maintenance or replacement?**
As part of a data science/engineering team, I have developed a Python cloud communication tool over the course of the last year or so. It is in active development, and my hope is that it may one day have a tangible user base. If the name transfer is successful, that project will be published under the transferred name.
Up until now, the project has been called `river`. I originally was going to open up a PEP 541 ticket regarding that project, as it is also abandoned, but then saw that #651 had recently already been opened for it and had been approved (congratulations to them!). So, wanting to keep the new name as similar as possible, a one-letter change to brought me to `rivet`. The repository and the files within it still use the name `river` for the time being, but if this transfer is successful, it will be renamed.

Repository: https://github.com/neighborhoods/river
Collaborators & team members: @frankiezeager, @freytheviking

**Contact and additional research**
I would be more than happy to contact the authors of the project, however, there is no contact information listed in the project or their user profiles. Additionally, the project has no linked homepage that I could search for additional contact info, and the project itself contains no files or documentation that provide contact info.

Author profiles: 
1. https://pypi.org/user/danlamanna/
2. https://pypi.org/user/kotfic/

**Comment by yeraydiazdiaz** [comment]
Hello @Geoiv, I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the current owner and allow one week for any replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
