### ISSUE TITLE
Issue: Limit Request: resmem - 500 MB

### ISSUE THREAD

**Issue by SoyBison** [pypa/pypi-support#829]
**Project**

Project is a pytorch wrapper for a model I've been working on at the Brain Bridge Lab at UChicago.

**Does this project already exist?**

Yes

**Size of release/project**

About 500MB, last upload attempt was 489MB

**Which indexes**

Just PyPI

**Reasons for the request**

This is a wrapper for a pytorch model. I don't intend to change the model any time soon, so I suspect that the file size will not change. The wrapper package is intended so that other scientists can easily implement the model in their own code, in contrast with previous similar projects that just uploaded their files in a very user unfriendly way. This way, everything is neat and ready-to-go, no fiddling around with pt files, no need to re-code the model description from the paper, no hassle.

Thanks so much in advance!

Edit: Wrong exact filesize

**Comment by SoyBison** [comment]
The github page is here, if you're interested. 
https://github.com/Brain-Bridge-Lab/resmem

**Comment by di** [comment]
I've set the upload limit for `resmem` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
