### ISSUE TITLE
PEP 541: Transfer ownership of unused `vipy`

### ISSUE THREAD

**Issue by jebyrne** [pypa/pypi-support#83]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/vipy/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/jebyrne/

**Reasons for the request**

Abandoned

**Maintenance or replacement?**

Replacement

**Contact and additional research**

I attempted to contact the owner at:

victor.ng@monkeybeanonline.com

and view the project homepage at:

http://poli-cms.googlecode.com/svn/vipy/

The email bounced, and the project home page no longer exists.

**Comment by crankycoder** [comment]
vipy is a long dead project - I still own the monkeybeanonline.com domain, but I don't have email setup on there anymore.  Is there something I need to do other than respond to this issue?

I'm totally ok with transferring the ownership of this package.

**Comment by jebyrne** [comment]
This has been resolved.  Thanks!
