### ISSUE TITLE
Issue: Limit Request: pai-blade-cpu - 300 MB

### ISSUE THREAD

**Issue by qiuxiafei** [pypa/pypi-support#833]
**Project**

pai-blade-cpu: https://pypi.org/project/pai-blade-cpu/

**Does this project already exist?**

yes

**Size of release/project**

300 MB

**Which indexes**

PyPI

**Reasons for the request**

PAI Blade is a general automatic deep-learning model optimizer developed at Platform of AI, Alibaba Inc. It's hosted in the cloud and also could be installed into user environment. This wheel package is the one that do CPU optimization in user environment. The wheel package contains lots of hand-crafted computing kernels and other complex automatic optimization solutions, so it's total size exceeds the original 100 MB limit. We'd like to increase the size limit to 300MB.

Thanks!

**Comment by yangjunpro** [comment]
@di  Hi Di, can you please kindly take a look at this issue? Thanks

**Comment by di** [comment]
I've set the upload limit for `pai-blade-cpu` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
