### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by VadVergasov** [pypa/pypi-support#837]
Request for account recovery.

## PyPI and Test PyPI Username

VadVergasov

Reason:
- Reset the phone with Google Authenticator.
- Didn't save recovery codes, only API token for the whole account.
- Didn't save export photos for Google Authenticator to recover after reset.

I know, that it's my bad, but it's very important for me. I've already reconfigured 2FA on most platforms and I'll be happy to recover PyPI and Test PyPI. Thanks!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
