### ISSUE TITLE
Limit Request: megengine - 2500MB

### ISSUE THREAD

**Issue by xxr3376** [pypa/pypi-support#838]
**Project** https://pypi.org/project/MegEngine/

**Does this project already exist?** Yes

**Size of release/project** 2500MB / 35GB

**Which indexes** PyPI and Test PyPI

**Reasons for the request**

This is a deep learning framework with full support for CUDA. We have already request for 850MB limit in the PyPI index at https://github.com/pypa/pypi-support/issues/289.

We are going to release a version that contains CUDA11, but it's too large to upload, around 2.2GB.  It's hard to compress the size, you could refer [PyTorch's CUDA11 package](https://download.pytorch.org/whl/torch_stable.html), `cu110/torch-1.7.0%2Bcu110-cp37-cp37m-win_amd64.whl` is about 2GB.

There are 12 files in one version, around 15GB in total.
* 4 of them are Linux package for 3.6 - 3.8, each one's size is around 1.5GB
* 4 of them are macOS package for 3.6 - 3.8, each one's size is around 30MB (No CUDA support)
* 4 of them are Windows package for 3.6 - 3.8, each one's size is around 2GB

I really hope PyPI could let the maintainer provide CDN URL, this will save lots of storage and bandwidth for PyPI. I have already send a proposal here https://github.com/pypa/warehouse/issues/8998

**Comment by di** [comment]
This is blocked on https://github.com/pypa/warehouse/issues/9057, the highest limit we are able to set right now is 2.14 GB.

**Comment by di** [comment]
Hi, thanks for your request. At this time we are only able to support a maximum file size of 1 GiB per distribution on PyPI. If you cannot compress the distribution further, we recommend doing the same as PyTorch and hosting these distributions externally.
