### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by eyal0** [pypa/pypi-support#841]
Request for account recovery.

## PyPI Username

`eyal0`

---

##  Reason for request

Reason:

Left it with an old job.  I still have access to my email address.

**Comment by ewdurbin** [comment]
@eyal0 it's not clear what the issue is with accessing your account. the address associated with it is not a corporate address, but what appears to be a personal gmail.

**Comment by eyal0** [comment]
Yes, my gmail was personal but my security key was the one that I got from work.  I got upgraded security keys but had to return the old ones and I didn't update pypi.

I still have access to the personal email.  If account recovery is possible that way, how do I do it?

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
