### ISSUE TITLE
The PEP 541 Request process is broken

### ISSUE THREAD

**Issue by Jens-G** [pypa/pypi-support#842]
The PEP 541 Request pipeline holds at the time writing exactly 75 open tickets, the oldest dating back to 2020-JAN-07. 
Even subsequent feedback (mostly people kindly asking what the can do to help with the process) is not answered.
So the obvious conclusion ist that the whole process to handle these is utterly broken.

**Comment by Jens-G** [comment]
Per today its 91 in the queue

**Comment by di** [comment]
There are currently 29 open requests: https://github.com/pypa/pypi-support/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A%22PEP+541%22

As mentioned before, this is a process handled entirely volunteers, so it limited by volunteer availability to process these requests.
