### ISSUE TITLE
Limit Request: marinvaders - 130 MB

### ISSUE THREAD

**Issue by rlonka** [pypa/pypi-support#843]
I would like to ask for increasing file limit to 130 MB

**Project**
https://pypi.org/project/marinvaders/

**Does this project already exist?**
Yes

**Size of release/project**
130 MB

**Which indexes**
PyPI

**Reasons for the request**
The data for this package requires some GIS shapefiles used to specify marine ecoregions.
The shapefiles specifies Polygons of this marine regions and they are calculated
per users requirements in realtime.

We do not expect any increase on this data files.

**Comment by di** [comment]
I've set the upload limit for `marinvaders` to 200 MB on PyPI.
