### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gpratt** [pypa/pypi-support#844]
Request for account recovery.

## PyPI Username

`gpratt`

---

##  Reason for request

Reason: Lost access to email address

Academic email (`gpratt@ucsd.edu`) was deactivated.  If you could replace with my personal email `gabriel.pratt@gmail.com` it would be much appreciated.

**Comment by ewdurbin** [comment]
Contacted via both email addresses referenced, please read the instructions and reply to proceed with recovery.

**Comment by gpratt** [comment]
Following up on this, any movement?

**Comment by ewdurbin** [comment]
Confirmation complete. Email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
