### ISSUE TITLE
PEP 541 Request: pySecp256k1

### ISSUE THREAD

**Issue by Moustikitos** [pypa/pypi-support#848]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/pySecp256k1

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/Toons

**Reasons for the request**
The name does not exists in pypi names and I can't publish mine.

**Maintenance or replacement?**
If any already existed : **replacement**
https://github.com/Moustikitos/elliptic-curve

**Contact and additional research**
I didn't find any reliable info to reach someone about former `pysecp256k1` package

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the current owners and allow one week for reply before proceeding with the transfer.

**Comment by Moustikitos** [comment]
Hi, thanks for the update.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
