### ISSUE TITLE
PEP 541 Request: pyHalo 

### ISSUE THREAD

**Issue by dangilman** [pypa/pypi-support#849]
**Project to be claimed**

`pyhalo`: https://pypi.org/project/pyhalo/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/gilmanda

**Reasons for the request**

The python package registered under the name pyhalo, hosted on github with the package name "PyHaloFour" (https://github.com/gitFurious/PyHaloFour), appears to be inactive, and has not had a code update in seven years. I have reached out to the owner of the repository via email, but received no response. I have my own python package pyHalo which I would like to register under the name pyhalo. 

**Maintenance or replacement?**

I would like to replace the package with my own: https://github.com/dangilman/pyHalo. The functionality is will be completely different. Several people are using my code already, so changing the package name would break all of their import statements. 

**Contact and additional research**

I have emailed the author of PyHaloFour using the email address pyhalo@damonpollard.com, but received no reply. I have also opened an issue on the PyHaloFour github repository (https://github.com/gitFurious/PyHaloFour/issues/1).

**Comment by yeraydiazdiaz** [comment]
Hi @dangilman , looks like you are the owner of the project already. Feel free to reopen if there's an error in your request.
