### ISSUE TITLE
Issue: Limit Request: SWAT - 90MB

### ISSUE THREAD

**Issue by kesmit13** [pypa/pypi-support#85]
**Project**
https://pypi.org/project/swat/

**Size of release**
90MB

**Which indexes**
Both

**Reasons for the request**
This package includes a subsystem that is shared between all of our software products.
The PPC version of the files are a bit larger than the other platforms and it puts us 
over the limit for those particular packages.  We are hoping to reduce the size of the 
packages over the next year, but at the moment we're just under 80MB.

**Comment by kesmit13** [comment]
Bumped size limit to 90MB just to be safe.  We're currently at 79.5MB.  I'd like to leave a little breathing room.

**Comment by jamadden** [comment]
The upload limit for swat has been set to 100MB on pypi.org and test.pypi.org
