### ISSUE TITLE
PEP 541 Request: dab

### ISSUE THREAD

**Issue by lphuberdeau** [pypa/pypi-support#850]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/dab/

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/lphuberdeau/

**Reasons for the request**
Project was a placeholder for spam pointing to a homepage that is no longer valid.

**Maintenance or replacement?**
Replacement.

Intent is to publish this package as a library. While it does not change very often, it is still being maintained.

https://github.com/delvelabs/dab

**Contact and additional research**
None attempted. Maintainer also appears to be a fake account created at the same time as the package was registered.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
