### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by poinot** [pypa/pypi-support#852]
Request for account recovery.

PyPI Username
----------------

`Marc.Poinot`

---

Reason for request
---------------------

  - Lost access to email address

Lost account:
https://pypi.org/user/Marc.Poinot/

The lost address is marc.poinot@onera.fr

Should be moved to: 

marc.poinot@safrangroup.com

TIA

**Comment by ewdurbin** [comment]
Contacted, please review and respond to that email.

**Comment by ewdurbin** [comment]
Confirmation complete. Email address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
