### ISSUE TITLE
PEP 541 Request: xontrib-autojump

### ISSUE THREAD

**Issue by wshanks** [pypa/pypi-support#854]
**Project to be claimed**

`xontrib-autojump`: https://pypi.org/project/xontrib-autojump

**Your PyPI username**
`wsha`: https://pypi.org/user/wsha

**Reasons for the request**
The project appears to have been abandoned.

**Maintenance or replacement?**
I intend to continue maintenance of the project. My repo is here: https://github.com/wshanks/xontrib-autojump

**Contact and additional research**

* Last PyPI release was August 2019.
* The project homepage linked from PyPI is a [GitHub repo link](https://github.com/sagartewari01/autojump-xonsh). That repo link is no longer valid. The user account associated with it has been removed as well.
* It is hard to show with the repo removed, but the original project was written by me and forked on GitHub by the user who posted the projec to PyPI. I never posted a version to PyPI. You can kind of see from [the commit history](https://github.com/wshanks/xontrib-autojump/commits/main) (I changed my GitHub username from willsALMANJ to wshanks in the meantime).
* A change to xonsh (which this package is a plugin for) resulted in the published version of the package making xonsh unusable. In the issue discussing the problem, it was suggested that I take over the PyPI package (see comments [starting here](https://github.com/xonsh/xonsh/issues/3725#issuecomment-682811239)).
* I sent an email to the address on the PyPI package and the other email address listed in his git commits at that time (August 2020) but have not received a reply. Here is the content of the email with addresses removed:
    > From: Will S <--->
    > Sent: August 28, 2020 12:51:21 PM EDT
    > To: ---@gmail.com, ---@gmail.com
    > Subject: Xonsh autojump
    > 
    > Hi Sagar,
    > 
    > I am writing to find out if you are interested in maintaining the autojump xontrib. It needs to be updated to work with the latest version of xonsh but your GitHub account and the xontrib repo were removed. If you don't want to maintain it, you could transfer ownership of the pypi entry to myself or someone on the xonsh team.

* Today [a new issue](https://github.com/wshanks/xontrib-autojump/issues/10) was opened on my repo about the bug in the PyPI package, so it is still affecting some users.
* Also, for what it's worth, my original code was released under the GPLv3 license and the version posted on PyPI is listed as using the MIT license which is not a permissible license for relicensing.

**Comment by yeraydiazdiaz** [comment]
Hello @wshanks, I will now start the reachability process for this transfer attempting to contact the owner. Hopefully we will hear back soon and move on with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
