### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by alkasm** [pypa/pypi-support#856]
Request for account recovery.

## PyPI Username

`alkasm`

---

##  Reason for request

  - Lost 2FA authentication app or security token
  
My phone stopped working and I had to get a new one, so I lost my 2FA access. I still have access to the email belonging to my account. Furthermore this GH account is associated to three PyPI packages for further verification (`cvtools-alkasm` and `pykasm-alkasm` and `timingdiagram-alkasm`). Let me know if you need anything else to restore the account.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
