### ISSUE TITLE
PEP 541: Transfer ownership of unused `nestor`

### ISSUE THREAD

**Issue by tbsexton** [pypa/pypi-support#86]
**Project to be claimed**

`nestor`: https://pypi.org/project/nestor

**Your PyPI username**

`tbsexton`: https://pypi.org/user/tbsexton

**Reasons for the request**

The `nestor` package has not been used since initial commit in 2012, as a "Head First Python" exercise. Attempts to contact user `drbetts` as the listed maintainer have been unsuccessful. 

Currently making use of [`nist-nestor`](https://pypi.org/project/nist-nestor/), but as we have a major release focusing on feature modularization coming up, the shorter name would make naming conventions of upcoming modules much easier. 

**Maintenance or replacement?**

Intend to replace package with [Nestor](https://github.com/usnistgov/nestor), which currently is accessed on Pypi via `nist-nestor`. 

**Contact and additional research**

Attempted to email since Aug 2018, with links to packages, etc. No response.

**Comment by yeraydiazdiaz** [comment]
Hi @tbsexton , I can confirm the `nestor` project has no functional code and can be considered invalid.

I will now ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
Transfer complete.
