### ISSUE TITLE
PEP 541 Request: transfer ownership of unused `merlin`

### ISSUE THREAD

**Issue by ben-bay** [pypa/pypi-support#87]
**Project to be claimed**

`PROJECT_NAME`: Merlin
`LINK`: https://pypi.org/project/merlin

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/ben-bay

**Reasons for the request**

The latest release for this package was in 2008. Its homepage link is broken, and its description is empty. We believe it is abandoned.

**Maintenance or replacement?**

We intend to publish a different package under the same name. Our project, Merlin, can be found [here](https://github.com/LLNL/merlin).

**Contact and additional research**

We emailed owner Leif Strand using his PyPI author emails (leif@geodynamics.org and leif@cacr.caltech.edu). The latter was broken, and the former has not responded.

**Comment by yeraydiazdiaz** [comment]
Hello @ben-bay, I've emailed the owner myself on 2nd Jan as sometimes as moderators we have more luck. If I receive no reply we will move forward with your claim.

**Comment by ben-bay** [comment]
> Hello @ben-bay, I've emailed the owner myself on 2nd Jan as sometimes as moderators we have more luck. If I receive no reply we will move forward with your claim.

Thanks for your help.

**Comment by ben-bay** [comment]
Hello again @yeraydiazdiaz --have you received any sort of response?

**Comment by yeraydiazdiaz** [comment]
Hi @ben-bay, I have not yet received response but I'm obliged by the PEP to try several times for 6 weeks.

**Comment by ben-bay** [comment]
> Hi @ben-bay, I have not yet received response but I'm obliged by the PEP to try several times for 6 weeks.

Yep I remember seeing that rule. I ask since it's been ~7 weeks since you first reached out to him.

**Comment by yeraydiazdiaz** [comment]
Hello @ben-bay, I have not received any response so this project is now considered abandoned.

I will now ask an admin to perform the transfer to you.

**Comment by ewdurbin** [comment]
transfer complete.
