### ISSUE TITLE
PEP 541 Request: pillar

### ISSUE THREAD

**Issue by graysonhead** [pypa/pypi-support#870]
**Project to be claimed**

`pillar`: https://pypi.org/project/pillar/

**Your PyPI username**

`graysonhead`: https://pypi.org/user/graysonhead/

**Reasons for the request**

I believe this project is invalid (name squatting). It only has one release from 2015, but I can't find any github repository for this project under the PyPi user's github.

I have attempted to download the only release on several computers, but receive the below error messages so I can't say for certain it has any functionality:

ERROR: Could not find a version that satisfies the requirement pillar
ERROR: No matching distribution found for pillar

Additionally, the package doesn't show up in a plaintext search for 'pillar': https://pypi.org/search/?o=&q=pillar&page=1

I have tried to push a package under that name, thinking that it may not actually exist as a result of the above issues, but am unable to do so.

**Maintenance or replacement?**

Replacement: https://github.com/graysonhead/pillar
**Contact and additional research**

No Email is listed for this user that I could find, and no Github repository exists under that username/name for this project. I attempted to contact them via Linkedin but they have not responded to my connection request.

**Comment by yeraydiazdiaz** [comment]
Hello @graysonhead, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for a response after which I will proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
