### ISSUE TITLE
PEP 541 Request: waves

### ISSUE THREAD

**Issue by mondeja** [pypa/pypi-support#873]
**Project to be claimed**

`waves`: https://pypi.org/project/waves

**Your PyPI username**

`mondeja`: https://pypi.org/user/mondeja

**Reasons for the request**
The project hasn't files, only one basic `setup.py`. It seems a test for PyPI upload.

**Maintenance or replacement?**
I want to publish https://github.com/mondeja/waves under `waves` name in PyPI, so this is a replacement.

**Contact and additional research**
The user is marked as deleted in PyPI and there is no contact information in the metadata of the project, so I can't contact nobody.

**Comment by yeraydiazdiaz** [comment]
Hello @mondeja, the project was previously owned by a mass name squatter and placed under admin control, I have transferred ownership to you.
