### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by coreylammie** [pypa/pypi-support#874]
Request for account recovery.

## PyPI Username

`coreylammie`

## PyPI Email Address 
`corey.lammie@jcu.edu.au`

---

##  Reason for request
Lost 2FA authentication app or security token.

Reason:
Unlocked bootloader on phone without recovery codes. I have access to the account's email address.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
