### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by bgkoussa** [pypa/pypi-support#875]
Request for account recovery.

## PyPI Username

`bgkoussa`

---

##  Reason for request

Reason: Lost 2FA authentication app or security token

**Comment by bgkoussa** [comment]
Lost access to my pypi account. Apparently I enabled multi factor authentication without ever creating recovery codes. Please help. PyPI username is bgkoussa.

**Comment by bgkoussa** [comment]
I need to access to be able to update a package.
https://pypi.org/project/easy-icm-runner/

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by bgkoussa** [comment]
Got your email and responded accordingly. Thanks.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
