### ISSUE TITLE
PEP 541 Request: altuscli (test.pypi.org)

### ISSUE THREAD

**Issue by bhavanki** [pypa/pypi-support#877]
**Project to be claimed**

`altuscli`: https://test.pypi.org/project/altuscli

**Your PyPI username**

`cloudera-cdp`: https://test.pypi.org/user/cloudera-cdp

This account is a new one maintained by my employer, Cloudera, and should be granted ownership of the project. I myself am able to use the account, but I do not want my own test.pypi.org account to be an owner.

**Reasons for the request**

Note that this request is for the project *on TestPyPI*. The "real" one on PyPI proper is already properly owned.

The project is abandoned because it is a CLI for a Cloudera SaaS product that has reached end of life and is no longer functional: https://docs.cloudera.com/common/html/altus-eol.html . The current owner, user "philipl", is reachable but has forgotten his TestPyPI password, and cannot receive password reset emails since they probably go to his Cloudera email address, which is inactive as he has left the company. Quoting him: "I have no idea what the password is. I tried a password reset but I bet it's emailed philipl@cloudera.com"

**Maintenance or replacement?**

This is more like a transfer for maintenance, although the goal is to retire the project, as it cannot work any longer, and its named product ("Altus") has been discontinued.

The equivalent CLI for its replacement product has already been published, with a different name: https://pypi.org/project/cdpcli/ It is a fork of "altuscli" and is under active development by the same team that the current TestPyPI owner of "altuscli" used to work for.

**Contact and additional research**

I contacted the current owner through another team member to see if he could transfer ownership to the "cloudera-cdp" account, but as described above, he doesn't remember his test.pypi.org password and reset emails won't reach him.

I can be contacted at bhavanki@cloudera.com. The primary email for the "cloudera-cdp" account, sre-svc@cloudera.com, will reach Cloudera's Site Reliability Engineering team. Feel free to use either email address if you need more information or confirmations. Thank you!

**Comment by philipl** [comment]
FWIW, I'm the former maintainer who can't remember his password. I have no objections.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
