### ISSUE TITLE
Limit Request: LearnBlock - 90 MB

### ISSUE THREAD

**Issue by pilarbachiller** [pypa/pypi-support#88]
### Project
https://pypi.org/project/learnblock/

### Size of release

90MB

### Which indexes

PyPI

### Reasons for request

LearnBlock is an educational programming tool for learning to program through robotics. It includes a wide functionality to create interactive programs that can run on several robots endowed with certain types of devices, such as cameras. Part of that functionality is implemented through deep learning, which requires the inclusion of files with several tens of MB. A previous version of this project (learnbot-dsl) already includes these files. We are creating this new package to give a new and more appropriate name to the project. If it were necessary, we would delete the previous project.

**Comment by jamadden** [comment]
The limit for learnblock has been set to 100MB on pypi.org
