### ISSUE TITLE
Project size over limit after removing old releases

### ISSUE THREAD

**Issue by cjdsellers** [pypa/pypi-support#882]
I'm encountering this even after deleting many old releases;

```
UploadError

  HTTP Error 400: Project size too large. Limit for project 'nautilus-trader' total size is 10 GB. See https://pypi.org/help/#project-size-limit
```

**Project**

https://pypi.org/project/nautilus_trader
https://github.com/nautechsystems/nautilus_trader/

**Does this project already exist?**

yes

**Size of release/project**

Each release consists of 6 binary wheels and a source distribution at approximately 183.4 MB

**Which indexes**

PyPI

**Reasons for the request**

Please free space from the removed projects and I will review the release cycle and endeavor to reduce total binary sizes.

Many thanks for your time!

**Comment by cjdsellers** [comment]
Still failing. I must have removed at least 1/3 of the releases since the first upload failure.

In addition to the above - given the total release size is getting close to 200MB, could I please request a per release increase to 250MB?

Many thanks!

**Comment by cjdsellers** [comment]
To potentially save some time, the reason for the large wheel sizes, and for the size increase requests, is that Cython compiles over 130 C extensions for a build - with all the corresponding `.so`s. 

This is what facilitates the projects value proposition. 

Cheers

**Comment by di** [comment]
Your current upload limit is 100MB and your releases (the size of each individual file) all seem to be under 10MB. I don't think you need a 250MB upload limit? Are we talking about the right project?

I can increase the total project size from 10 GB, but I'm curious why your project needs to release so frequently (with sometimes multiple releases a day).

**Comment by cjdsellers** [comment]
Ok I was just going off reported file sizes within the releases on PyPI - largest one there is 54.2MB.

The API was going through a lot of changes so I wanted people using the latest version, the release cycle will increase now.

When I delete a release in PyPI management, does it increase the available space within the total upload limit?

Many thanks

**Comment by cjdsellers** [comment]
The last three releases have failed to upload all wheels, that could be why you were seeing smaller releases? There should be 6 `.whl` and a `.tar.gz` per release.

**Comment by cjdsellers** [comment]
Ok, I understand now that the upload limit is per individual file. In which case 100MB is more than enough for now.

I think the only thing which needs resolving at this point is whether deleting old releases should free up space? and if not, if I'm able to increase total upload space.

Many thanks

**Comment by cjdsellers** [comment]
@di It would be great to come to a resolution on this as I'm unable to publish packages

**Comment by cjdsellers** [comment]
I had a closer look at the project and realized I was removing old releases which only include the `sdist` of about 1MB. So removing those releases was barely making a difference to total space available.

I've now removed more releases to free up 5GB of space and I'm able to release to PyPI again.

I'll review my release cycle and when I upload to PyPI and keep looking for ways I can reduce the size of the binary wheels.

However, it would still be great to increase total available size to 20GB just so I can have a longer tail in the release history.

Many thanks again for your time.

**Comment by di** [comment]
@cjdsellers I'm going to close this for now as it seems you don't actually need a 20GB limit right at this moment. Please feel free to reopen once you're closer to this limit and/or removing old releases does not continue to work for you.

**Comment by cjdsellers** [comment]
Ok good idea, thanks Di
