### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by danields761** [pypa/pypi-support#883]
Request for account recovery.

## PyPI Username

`danields`

##  Reason for request

Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by danields761** [comment]
Hello, @ewdurbin !

Thats were a lot of time ago, I missed this time, sorry for that. Eventually, I had repeated steps from the email you sent me. If it's not sufficient after so much time, could you send me new instruction?

**Comment by ewdurbin** [comment]
superseded by #2242
