### ISSUE TITLE
Pip throws timeouts and can't connect

### ISSUE THREAD

**Issue by royassis** [pypa/pypi-support#884]
Hey 

My issue is detailed at : 
https://stackoverflow.com/questions/65688006/pip-timing-out-on-multiple-computers-on-the-same-network/65747876#65747876

debugging files are attached. 
[curl -vvv -I --ipv4 https___files.pythonhosted.org_packages_ae_e8_2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02_pip-10.0.1.gz](https://github.com/pypa/pypi-support/files/5937125/curl.-vvv.-I.--ipv4.https___files.pythonhosted.org_packages_ae_e8_2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02_pip-10.0.1.gz)

[curl -vvv -I --ipv4 https___files.pythonhosted.org_packages_ae_e8_2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02_pip-10.0.1.txt](https://github.com/pypa/pypi-support/files/5937130/curl.-vvv.-I.--ipv4.https___files.pythonhosted.org_packages_ae_e8_2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02_pip-10.0.1.txt)
[curl -vvv -I --ipv4 httpspypi.orgpypipipjson.txt](https://github.com/pypa/pypi-support/files/5937131/curl.-vvv.-I.--ipv4.httpspypi.orgpypipipjson.txt)
[curl -vvv -I --ipv6 https___files.pythonhosted.org_packages_ae_e8_2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02_pip-10.0.1.txt](https://github.com/pypa/pypi-support/files/5937132/curl.-vvv.-I.--ipv6.https___files.pythonhosted.org_packages_ae_e8_2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02_pip-10.0.1.txt)
[curl -vvv -I --ipv6 https___pypi.org_pypi_pip_json.txt](https://github.com/pypa/pypi-support/files/5937133/curl.-vvv.-I.--ipv6.https___pypi.org_pypi_pip_json.txt)
[dig files.pythonhosted.org A.txt](https://github.com/pypa/pypi-support/files/5937134/dig.files.pythonhosted.org.A.txt)
[dig files.pythonhosted.org AAAA.txt](https://github.com/pypa/pypi-support/files/5937135/dig.files.pythonhosted.org.AAAA.txt)
[dig pypi.org A.txt](https://github.com/pypa/pypi-support/files/5937136/dig.pypi.org.A.txt)
[dig pypi.org AAAA.txt](https://github.com/pypa/pypi-support/files/5937137/dig.pypi.org.AAAA.txt)
[echo -n  openssl s_client -4 -connect files.pythonhosted.org.txt](https://github.com/pypa/pypi-support/files/5937138/echo.-n.openssl.s_client.-4.-connect.files.pythonhosted.org.txt)
[echo -n  openssl s_client -4 -connect pypi.org443.txt](https://github.com/pypa/pypi-support/files/5937139/echo.-n.openssl.s_client.-4.-connect.pypi.org.443.txt)
[echo -n  openssl s_client -6 -connect files.pythonhosted.org.txt](https://github.com/pypa/pypi-support/files/5937140/echo.-n.openssl.s_client.-6.-connect.files.pythonhosted.org.txt)
[echo -n  openssl s_client -6 -connect pypi.org443.txt](https://github.com/pypa/pypi-support/files/5937141/echo.-n.openssl.s_client.-6.-connect.pypi.org.443.txt)
[traceroute files.pythonhosted.org.txt](https://github.com/pypa/pypi-support/files/5937142/traceroute.files.pythonhosted.org.txt)
[traceroute pypi.org.txt](https://github.com/pypa/pypi-support/files/5937143/traceroute.pypi.org.txt)
[traceroute6 files.pythonhosted.org.txt](https://github.com/pypa/pypi-support/files/5937144/traceroute6.files.pythonhosted.org.txt)
[traceroute6 pypi.org.txt](https://github.com/pypa/pypi-support/files/5937145/traceroute6.pypi.org.txt)

**Comment by ewdurbin** [comment]
closing as stale.
