### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by trevorphillipscoding** [pypa/pypi-support#885]
Request for account recovery.

## PyPI Username

`Philzeey`

---

##  Reason for request

Reason:
 Lost 2FA authentication app or security token

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by trevorphillipscoding** [comment]
@ewdurbin replied back that i completed the steps required on Feb 17th and haven't heard back yet so just checking in. Thank you.

**Comment by ewdurbin** [comment]
There is limited time available for processing these rather tedious and delicate requests and no strict timeline. They are generally handled in batches as time allows.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
