### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by khaeru** [pypa/pypi-support#886]
Request for account recovery.

## PyPI Username

`khaeru`

---

##  Reason for request

Reason:

I lost the Android phone on which I had Google Authenticator installed and 2FA configured.
This applies to the same username for *both* PyPI and TestPyPI.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by khaeru** [comment]
@ewdurbin all good for pypi.org, thank you. I have not yet received a password reset for test.pypi.org:

>  This applies to the same username for _both_ PyPI and TestPyPI.

Did you send it already?

**Comment by ewdurbin** [comment]
test pypi handled.
