### ISSUE TITLE
PEP 541 Request: duet

### ISSUE THREAD

**Issue by maffoo** [pypa/pypi-support#889]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/duet

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/mneeley

**Reasons for the request**
The existing duet project seems to fall under the definition of [invalid projects](https://www.python.org/dev/peps/pep-0541/#invalid-projects): "package has no functionality or is empty". We have a newly open-sourced package that is internally called "duet" that we would like to publish on pypi under the name "duet": https://github.com/google/duet

**Maintenance or replacement?**
This will be a new package since no code or packages have been published yet under the existing name. The code for the new package is linked above.

**Contact and additional research**
I attempted to contact the existing maintainer https://pypi.org/user/gregoil/ at the maintainer email address listed under other projects owned by this user, such as https://pypi.org/project/pytest-rotest/. However, the emails were returned with an error indicating the address was no longer active.

**Comment by yeraydiazdiaz** [comment]
Hello @maffoo, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact with the owner and allow one week for a response after which I will proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
