### ISSUE TITLE
Manual Reset of 2FA

### ISSUE THREAD

**Issue by blink1073** [pypa/pypi-support#89]
Hi,
username: blink1073
email: steven.silvester@gmail.com

Request: a reset of the 2FA for the above account info.
Reason: Changed phones and lost my key

**Comment by ewdurbin** [comment]
Hello @blink1073, please email ernest@python.org from the primary email address associated with your PyPI account to proceed with recovery.

**Comment by ewdurbin** [comment]
This has been verified and completed.
