### ISSUE TITLE
PEP 541 Request: ansible-test

### ISSUE THREAD

**Issue by ssbarnea** [pypa/pypi-support#891]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/ansible-test

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/ssbarnea
`USER_NAME`: https://pypi.org/user/gundalow
`USER_NAME`: https://pypi.org/user/ansible-community

**Reasons for the request**

This package is confusing and is a possible security risk as there is an already existing `ansible-test` command line which is installed by `ansible` package itself.

Assuring that this package is owned by Ansible team, will prevent possible hijacking of it.

**Maintenance or replacement?**

We did not decide yet, if we will only remove all releases or if we will re-use it but we do want to be sure users to not endup with a surprise.

**Contact and additional research**

**Comment by ssbarnea** [comment]
Maybe we can sort this out with direct help from @nylas or @lowks

**Comment by gundalow** [comment]
For the record, we've attempted to make contact with the original maintainers on 18th November 2020 via https://github.com/nylas/ansible-test/issues/20

**Comment by lowks** [comment]
Can I know why I was named here ? Don't think I am involved with this project.

**Comment by yeraydiazdiaz** [comment]
Closing in favour of https://github.com/pypa/pypi-support/issues/892 simply because there's more context there.
