### ISSUE TITLE
Limit Request: taxoniq - 250 MB

### ISSUE THREAD

**Issue by kislyuk** [pypa/pypi-support#893]
**Project**
taxoniq (https://pypi.org/project/taxoniq/)

**Does this project already exist?**

Yes

**Size of release/project**

160 MB (expected to grow slightly over time)
**Which indexes**

PyPI

**Reasons for the request**

The taxoniq project (https://pypi.org/project/taxoniq) is an offline index of the NCBI Taxonomy database and its related data, an authoritative resource for biological taxonomy information. I am seeking to extend this functionality with an offline index mapping of the NCBI BLAST nucleotide accession IDs (specifically, the accession IDs found in the refseq and Betacoronavirus databases) to the taxonomy IDs in taxoniq. Despite using a compact suffix array data structure for this index, I am unable to reduce the file size further, so I would like to request a limit increase to 250 MB to accommodate this package.

**Comment by di** [comment]
I've set the upload limit for `taxoniq ` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
