### ISSUE TITLE
services project title to be claimed

### ISSUE THREAD

**Issue by mtejada25** [pypa/pypi-support#894]
**Services**

`services`: https://pypi.org/project/services

**mtejada25**

`mtejada25`: https://pypi.org/user/mtejada25

**I asked for this because I have a project named this too. I really would like to upload it to pypi as my first library. That person has probably made lots of libraries (a lot more than me)**

**Replacement**

**None**

**Comment by yeraydiazdiaz** [comment]
Hello @mtejada25, you have not completed the information [required for the transfer](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME). Please provide this information in full, either here or in a new issue.
