### ISSUE TITLE
Reclaim (or permanently disable) bravado-decorators package, claimed by a security researcher

### ISSUE THREAD

**Issue by danielpops** [pypa/pypi-support#897]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/bravado-decorators

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/danielpops
I am an on the Security Team at Yelp

**Reasons for the request**
This package is similar to the ones created in https://github.com/pypa/pypi-support/issues/526 where they have malicious code run during setup.py install that collects information about the hosts that installed the package. While we don't feel that we are at risk of accidentally installing this in our infrastructure, we do feel that this package is malicious and should be taken down.

**Maintenance or replacement?**
We intend to effectively disable this package so that the malicious code cannot be installed

**Contact and additional research**
They have contacted us through our bugbounty program and told us that they registered this one. We plan to register other unclaimed packages to prevent this going forward, but we missed this one.

**Comment by yeraydiazdiaz** [comment]
This package was placed in the prohibited project names list.
