### ISSUE TITLE
Limit Request: itk-core - 20 GB

### ISSUE THREAD

**Issue by thewtex** [pypa/pypi-support#899]
**Project**

`itk-core`

https://pypi.org/project/itk-core/

**Does this project already exist?**

Yes. We have released on PyPI since 2017.

**Size of release/project**

We are hitting the total size limit, currently at 9.6 GB.

**Which indexes**

PyPI.

**Reasons for the request**

To help ensure uploads for the years ahead, we are requesting a total project size increase to **20 GB**. Thank you!

**Comment by di** [comment]
Hi @thewtex, looking at your project now, the total size is 8.7GiB which is well below the 10GiB limit. It seems like you don't need a 20GiB limit increase, can you explain?

Can you also give us some details about why this project's releases are larger than average? Thanks!

**Comment by thewtex** [comment]
Hi @di , the total size had been reduced because older releases were deleted so new releases could be published. A limit increase to 20 GB will allow us to keep releases available while they are still in use.

This is a large, compiled project which makes the releases larger than average. The project is 20+ years old, 300+ contributors, 1.7 million lines of code.

**Comment by di** [comment]
I've increased the total project size limit to 20GiB.

**Comment by thewtex** [comment]
@di thank you!
