### ISSUE TITLE
PEP 541: Transfer ownership of empty 'pen' package

### ISSUE THREAD

**Issue by pspeter** [pypa/pypi-support#90]
**Package Name**

`Pen`: https://pypi.org/project/pen

**Your PyPI username**

`pspeter`: https://pypi.org/user/pspeter

**Reasons for the request**

The project seems to be completely empty. The link to the project page just shows a 404. 
pip also doesn't find the package. This might be a case of name squatting.

I have been working on my own app for a while now and was going to publish an alpha version today. It is a CLI journal-keeping app in case that matters. Pen seemed like a very fitting name: it is short, easy to remember, and quick to type, while still relating to writing/journaling. 

The source is currently private on my profile, but I can make it public on request here.

**Maintenance or replacement?**

Replacement, since nothing is there to maintain.

**Contact and additional research**

I have no way of contacting the owner of the package on pypi.org (that I know of). 

I did, however, contact the owner of the pen package on test.pypi.org, which turns out to be a different person than the owner of the real one. He came back to me and told me that he ran into the same issue that the name was already taken a month ago. He has since then moved on and renamed his project but still kept the release on test.pypi.org. I believe he would transfer the test package to me on request.

**Comment by jamadden** [comment]
The project had one distribution added and immediately removed on 2016-10-20. I believe this qualifies it as an [invalid project](https://www.python.org/dev/peps/pep-0541/#invalid-projects) under the clause "project is name squatting (package has no functionality or is empty)". I will ask the admins to perfom a transfer.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by pspeter** [comment]
Thanks guys!
