### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jumel-lycee** [pypa/pypi-support#900]
Request for account recovery.

## PyPI Username

`vincentxavier`

---

##  Reason for request

Reason:
  - Lost access to email address : in fact, the address is mispelled. It reads vxjumel@tuxfamilyv.org but it should be vxjumel@tuxfamily.org without the final `v`

**Comment by ewdurbin** [comment]
None of the email addresses associated with the account match what you have described.

I have contacted via primary email address on the account from an @pypi.org email address with the subject "PyPI Account Recovery Request: vincentxavier". That should help you track down your account.

**Comment by ewdurbin** [comment]
The address associated with the account bounced. Please email support@pypi.org to proceed.

**Comment by ewdurbin** [comment]
Address has been updated and a password reset issued, you should be able to regain access to your account after completing the password reset.
