### ISSUE TITLE
PEP 541 Request: ape

### ISSUE THREAD

**Issue by fubuloubu** [pypa/pypi-support#902]
**Project to be claimed**
`PROJECT_NAME`: https://pypi.org/project/ape/

**Your PyPI username**
`USER_NAME`: https://pypi.org/user/fubuloubu

**Reasons for the request**
This project seems to be abandoned. The last release was Apr 5, 2014, and the [GitHub](https://github.com/henzk/ape) for the project was last updated in the end of 2017. I had made an attempt to reach the listed email address of the maintainer on Janurary 1st and got no response. It appears that the [company](https://github.com/schnapptack) this user was working for when the package was created had stopped being around some time in 2018.

**Maintenance or replacement?**
We (myself and @iamdefinitelyahuman) are intending to rebrand [this existing framework](https://pypi.org/project/eth-brownie/) to `ape` as part of a larger effort to revamp our tool for our community of open source developers. The existing tool is located [here](https://github.com/eth-brownie/brownie), and the new tool is located [here](https://github.com/ApeWorX/ape). I had reserved [this name](https://pypi.org/project/eth-ape/) for potential use if I was unable to claim `ape` for this project, but as we are intending on pursuing a plugin-based architecture for our revamped tool, I think it would be easier for our users if `ape` were the base package for this project as it will lerverage the package ecosystem of `ape-*` packages.

**Contact and additional research**
Here is the email I sent on Janurary 1st (blacked out my name):
![pypi](https://user-images.githubusercontent.com/3859395/107864819-17b1a080-6e2e-11eb-8740-48d42679dc97.png)

**Comment by fubuloubu** [comment]
cc @henzk on this request, in case he responds here instead.

**Comment by henzk** [comment]
Hi,

me and my company are still around; we are still using this!
Sorry for not responding to the email; I get lots of email; must have overlooked this somehow.

I would prefer to keep this name.
Changing it would require lots of effort for ~100 customer projects where we would have to change stuff around.
We do not have the resources to do this atm.

Why rebrand to ape at all? eth-brownie sounds much more serious.

Best!
