### ISSUE TITLE
PEP 541 Request: pytest-diff

### ISSUE THREAD

**Issue by sondrelg** [pypa/pypi-support#903]
**Project to be claimed**
`pytest-diff`: https://pypi.org/project/pytest-diff/

**Your PyPI username**
`sondrelg`: https://pypi.org/user/sondrelg

**Reasons for the request**
I believe this project has been abandoned.

**Maintenance or replacement?**
Replacement

**Contact and additional research**
No contact details seems to exist on the project page, and all links to github are invalid.

**Comment by sondrelg** [comment]
Hi, 

I have an unpublished package that I would like to occupy this namespace. It's more or less ready to publish now.

Totally understand that you may not have the capacity to handle this ticket right away, but is it possible to give an indication of what the processing time on this will be?

**Comment by yeraydiazdiaz** [comment]
Hello @sondrelg, the links may be invalid but the package does seem to have some functionality and there are [some downloads](https://pepy.tech/project/pytest-diff). I will try contacting the owner to try and get more context on their intention towards the package maybe have them update the related information, but if unsuccessful we err in the side of caution and deny the transfer to avoid breaking any potential users of the package.

**Comment by sondrelg** [comment]
To be honest I was 99% sure it was completely dead since the github user *and* project seems to have been deleted, and it was only worked on for 1-2 days from a cookiecutter template.

Hope you managed to contact them 🤞 and thank you very much for the update 👍

**Comment by yeraydiazdiaz** [comment]
No worries. The owner replied to my email stating he wishes to continue developing the package.
