### ISSUE TITLE
PEP 541 Request: paypay

### ISSUE THREAD

**Issue by solancer** [pypa/pypi-support#904]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/paypay/

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/paypay

**Reasons for the request**

This is an unofficial package misleading our PayPay merchants into installing a bogus payment SDK. 

**Maintenance or replacement?**

We intend to publish our original PayPay SDK 
https://github.com/paypay/paypayopa-sdk-python

**Contact and additional research**

Yes but no response

**Comment by yeraydiazdiaz** [comment]
Hello, I can confirm the project has very little functionality and, while not strictly invalid, I will consider it so unless the owner proves otherwise. I will attempt contact and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
