### ISSUE TITLE
PEP 541 Request: TwitchWebsocket

### ISSUE THREAD

**Issue by tomaarsen** [pypa/pypi-support#907]
**Project to be claimed**

`TwitchWebsocket`: https://pypi.org/project/TwitchWebsocket

**Your PyPI username**

`CubieDev`: https://pypi.org/user/CubieDev

**Reasons for the request**

There is currently no project on https://pypi.org/project/TwitchWebsocket/. I would like to upload [my TwitchWebsocket project](https://github.com/CubieDev/TwitchWebsocket) which I started years ago, so users can (easily) download it via pip. 
I did manage to upload it to testpypi: https://test.pypi.org/project/TwitchWebsocket/1.1.0/
I suspect someone created a project named `TwitchWebsocket` on PyPI and then deleted it?

**Maintenance or replacement?**

I would continue development of my package. There is no previous package to maintain or replace.

**Contact and additional research**

The project page https://pypi.org/project/TwitchWebsocket/ is empty, and there are 0 results for it on PyPI when searching. There is also only one project named `TwitchWebsocket` on GitHub, and it's mine.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no releases and is therefore considered invalid. I will attempt contact with the owner and allow one week for reply before proceeding with the request.

**Comment by tomaarsen** [comment]
@yeraydiazdiaz
Have you gotten any update? I'm still quite interested in pushing my project to PyPI.
Thanks in advance.

**Comment by tomaarsen** [comment]
@yeraydiazdiaz 
Have you managed to contact the owner? If not, I am still interested in publishing my project. 
Thank you.

**Comment by yeraydiazdiaz** [comment]
Hi @tomaarsen apologies for the delay I mislabeled the ticket and it slipped through the cracks. The transfer is now complete.
