### ISSUE TITLE
PEP 541 Request: roblox

### ISSUE THREAD

**Issue by jmkd3v** [pypa/pypi-support#909]
**Project to be claimed**
`roblox`: https://pypi.org/project/roblox/

**Your PyPI username**
`jmkdev`: https://pypi.org/user/jmkdev/

**Reasons for the request**
I maintain the Roblox-Python API wrapper known as ro.py, which has its own PyPI repository at https://pypi.org/project/ro-py/.  
I was originally planning to release under https://pypi.org/project/roblox/, however I soon realized that the package name had already been taken. 
The last release of the `roblox` package was August 3rd, 2019, and we believe we can actively publish our package under this name in the future.

**Maintenance or replacement?**
If we do gain access to this package, we will begin to push our own project under the `roblox` package name.
The package is available at https://pypi.org/project/ro-py/ or https://github.com/rbx-libdev/ro.py.

**Contact and additional research**
I have attempted to contact the original owner, but was told that the package was being held for future use, seemingly because of the name.

**Comment by jmkd3v** [comment]
This is still an issue.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for reply before proceeding with the transfer.

**Comment by xomien** [comment]
I've decided to just give the package to the requester.

**Comment by yeraydiazdiaz** [comment]
Thanks @zomien
