### ISSUE TITLE
PEP 541: Transfer ownership of unused `rpa` 

### ISSUE THREAD

**Issue by kensoh** [pypa/pypi-support#91]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/rpa

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/kensoh

**Reasons for the request**

Above package name and URL is not in use (thus no contact information of owner). However when I try `twine upload` I'm denied access. I have read through PyPI and Python FAQ before raising this issue, and I believe that if this package name has been registered, it might be an abandoned name.

I maintain an active Python general purpose tool for RPA (robotic process automation). Its GitHub homepage is here https://github.com/tebelorg/TagUI-Python and I intend to keep it general purpose both in usage and branding (for eg by intention no logo is used for the project, just a snake emoticon). From pypistats.org, there is an estimated >2000 installations through pip.

This is the PyPI home page of my project https://pypi.org/project/tagui - I did not put readme there because there is problem displaying tables in the markdown here, which is required to list the functions offered in the tool's API.

**Maintenance or replacement?**

Replacement. I intend to publish my Python project so that users can `pip install rpa` to use this general purpose RPA tool. For continuity reasons, for a start I'll probably do a simple setup.py that includes the `tagui` package as a dependency. Or maybe the other way round is better. The stable end state would be publishing as `rpa` package with the project name being 'RPA for Python' and the Python object being invoked using `import rpa as r`.

**Contact and additional research**

I can be reached at opensource@tebel.org but due to the invalid URL page for https://pypi.org/project/rpa I am not able to contact the registered owner or find out any other info about it, thus raising this issue for your kind review and help.

I'm a RPA specialist, the Python project that I'm maintaining is a full-featured tool which I'm keeping it free and not commercialising it. Purely supporting and maintaining it as voluntary open-source work. So I hope to make it even more accessible for users who would like to make use of RPA to automate their digital processes and tasks, by renaming my project appropriately as `rpa` package. RPA in today's mainstream context would unquestionably mean robotic process automation, so doing this would bring greater benefits to the Python ecosystem of users.

Thank you very much for reading and reviewing this request!

**Comment by yeraydiazdiaz** [comment]
Hello @kensoh, I can confirm the project is invalid as it's got no releases.

I will now ask an admin to perform this transfer for you.

**Comment by kensoh** [comment]
Hi @yeraydiazdiaz thank you so so much! This will really help me make open-source, full-featured and free RPA software for Python much more accessible to the Python ecosystem. I appreciate it!

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by kensoh** [comment]
Thank you so much Ernest @ewdurbin ! 😄
