### ISSUE TITLE
PEP 541 Request: DAPPER

### ISSUE THREAD

**Issue by patricknraanes** [pypa/pypi-support#910]
**Project to be claimed**
`DAPPER`: https://pypi.org/project/DAPPER
The corresponding repository is here
https://github.com/markrwilliams/dapper

**Your PyPI username**
`patricknraanes`: https://pypi.org/user/patricknraanes/

**Reasons for the request**
The project is Squatting.

**Maintenance or replacement?**
Replacement, with
https://pypi.org/project/DA-DAPPER
https://github.com/nansencenter/DAPPER

**Contact and additional research**
I have tried contacting the developer several times by email, but he does not respond.

**Comment by patricknraanes** [comment]
Is there anything else I should do to enable this process?

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has no functionality and is therefore considered invalid. I will attempt contact with the owner and allow one week for reply before proceeding with the request.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
