### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by espositomarco** [pypa/pypi-support#911]
Request for account recovery.

## PyPI Username

marcoesposito

---

##  Reason for request

  - Lost 2FA authentication app or security token

Reason:
My phone stopped working and I had to reset it. So I lost the access to the 2FA authentication app, which was Google Authenticator. 
I had not generated the recovery codes.

I have full access to everything else, including my email address.

**Comment by ewdurbin** [comment]
Contacted via email addresses on the account, please read the instructions and reply to proceed with recovery.

**Comment by espositomarco** [comment]
I followed the instructions, now I'm waiting for the password reset.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
