### ISSUE TITLE
Limit Request: PANDARE- 120MB

### ISSUE THREAD

**Issue by AndrewFasano** [pypa/pypi-support#912]
**PANDAre**

**Does this project already exist?**

Yes at https://pypi.org/project/pandare.

**Size of release/project**

120mb, please. We do not anticipate frequent releases to PyPI so I don't think we'll need to update the total project size limit.

**Which indexes**

Just PyPI, please.

**Reasons for the request**

[PANDA](https://github.com/panda-re/panda) is an open-source whole-system dynamic analysis platform with support for a number of different CPU architectures (x86, arm, mips, etc). The project has 1.8k starts on GitHub. We recently created a Python interface for PANDA. To get this working, we distribute 7 distinct shared objects (one for each supported architecture). With the default PyPi size limit, we've only been able to squeeze 4 into a release.

In the long term, I'm hoping the PANDA maintainers will release an APT package including these libraries. If that happens, we'll be able to add a dependency on that package and reduce the space we need on PyPi.

Thanks and let me know if there's any other info you need,
Andrew

**Comment by di** [comment]
I've set the upload limit for `pandare` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
