### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Vlad-clou** [pypa/pypi-support#914]
Request for account recovery.

## PyPI Username

- username: giladotan
- name: Gilad Dotan
- gmail: gilad.dotann@gmail.com

##  Reason for request

- Lost 2FA authentication app or security token

Reason:
I formatted my phone and I lost my 2FA authentication security token and now I'm locked outside of my account

I have full access to my phone and email

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Vlad-clou** [comment]
hello Pypa/Pypi-Support, i lost my 2FA and i would like to get into my
account to generate recovery keys
the thread post: https://github.com/pypa/pypi-support/issues/914

**Comment by Vlad-clou** [comment]
where are the instructions?

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
