### ISSUE TITLE
Recover a deleted testpypi project

### ISSUE THREAD

**Issue by fpicetti** [pypa/pypi-support#916]
Hello,

Not sure where to issue this.
I am going to publish a project, thus I registered and played a bit on testpypi.
The project is named `occamypy`.

As I was getting errors from building on Mac and installing on linux (some required packages were missing in the builds), after some experiments I decided to delete the project to start from scratch. I did it on testpypi website, and then tried to upload another version.

Unfortunately, I get `This filename has already been used, use a different version`.
I thought the name keeping was active for pypi only; is it active also for testpypi? Is there a way I can create a new project with the same name?

Thanks a lot.

**Comment by di** [comment]
Hi @fpicetti, like the error message states, if you use a different version you should be able to publish to the project name again.

**Comment by fpicetti** [comment]
Thanks a lot!
