### ISSUE TITLE
PEP 541 Request: adt

### ISSUE THREAD

**Issue by LewisGaul** [pypa/pypi-support#918]
**Project to be claimed**
`adt`: https://pypi.org/project/adt/

**Your PyPI username**
`LewisGaul`: https://pypi.org/user/LewisGaul

**Reasons for the request**
The project was created on Apr 14th 2016 and appears to have no releases (I'm a little confused by a version '0.0.1' showing up at https://pypi.org/project/adt/#history but it seemingly having no contents/being impossible to pip install?).

**Maintenance or replacement?**
Replacement (not really applicable as existing project is unused). My project is: https://github.com/LewisGaul/python_adt.

**Contact and additional research**
No links on the existing project, no public contact details for the user.

This appears to be the same issue as in https://github.com/pypa/warehouse/issues/8964, in which it was recommended by @di to "file a PEP 541 request to acquire the project name" here, so here I am! :)

Thanks in advance.

**Comment by LewisGaul** [comment]
Hey, any chance with this request or is it not likely to happen?

**Comment by yeraydiazdiaz** [comment]
I can confirm the project has a single release with no associated files. I will contact the owner now and allow one week for reply before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Apologies for the delay, the transfer is now complete.
