### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by tm-schwartz** [pypa/pypi-support#919]
Request for account recovery.

## PyPI Username

tm-schwartz

---

##  Reason for request

Reason:
  *  Lost 2FA due to complete phone destruction.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by tm-schwartz** [comment]
Have replied to email and am waiting for next step. Thank you for your time, I see how many of these you get over a short period of time.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
