### ISSUE TITLE
Issue: Limit Request: fastlmm - 250MB

### ISSUE THREAD

**Issue by CarlKCarlK** [pypa/pypi-support#92]
**Project**
fastlmm
https://pypi.org/project/fastlmm/
https://test.pypi.org/project/fastlmm/

**Size of release**
250 MB

**Which indexes**
Both indexes

**Reasons for the request**

We need to include a non-standard MKL static library file (libmkl_intel_ilp64.a) to get around a matrix limitation in the default MKL (namely, it silently fails on SVD operations larger than about 14K x 14K). That library, in turn requires libmkl_core.a, which is large. (When we started working on this update, we had hoped to use the PyPi mkl project, but it is out of date and doesn't include libmkl_intel_ilp64.*)

Thanks,
Carl

**Comment by di** [comment]
I've set the upload limit for `fastlmm` to 250 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
