### ISSUE TITLE
PEP 541 Request: cog

### ISSUE THREAD

**Issue by arun1729** [pypa/pypi-support#920]
**Project to be claimed**
`cog`: https://pypi.org/project/Cog/

**Your PyPI username**
`arun1729`: https://pypi.org/user/arun1729/

**Reasons for the request**
This project has been abandoned, the last revision was done more than 15 years ago in June, 2004. I don't mind contacting the owner but I could not find any contact info. I had made this request back in 2017 and have been waiting for the past 4 years to get the ownership transferred, I hope it happens soon. Here is the link to the original ticket: https://sourceforge.net/p/pypi/support-requests/777/

**Maintenance or replacement?**
I would like to publish this project there: https://github.com/arun1729/cog

**Contact and additional research**
I could not find any contact information about the current owner.

**Comment by yeraydiazdiaz** [comment]
I can confirm the project's releases have no associated files and is therefore considered invalid. I will attempt to contact the current maintainer and allow one week for reply before proceeding with the request.

**Comment by yeraydiazdiaz** [comment]
The owner replied saying they intend to release a project under than name very soon.
