### ISSUE TITLE
Limit Request: vc2-conformance-data - 238 MB

### ISSUE THREAD

**Issue by mossblaser** [pypa/pypi-support#921]
**Project**: [vc2-conformance-data](https://pypi.org/project/vc2-conformance-data/)

**Does this project already exist?**: Yes (though currently only as a placeholder empty package)

**Size of release/project**: 238 MiB

**Which indexes**: PyPI

**Reasons for the request**:

*Project description:* This package accompanies the (soon to be released) `vc2-conformance` package which implements conformance testing routines developed by [BBC R&D](https://www.bbc.co.uk/rd) for implementations of the VC-2 video codec (a.k.a. [SMPTE ST 2042-1](https://ieeexplore.ieee.org/document/7967896)). This package (`vc2-conformance-data`) contains pre-computed algebraic analyses of signal filters used by VC-2 codecs which are essential to the conformance testing process.

*Reason for additional size:* The included analyses are extremely computationally expensive to produce (requiring many CPU-years and tens of GB of RAM). As such, pre-computing this data is essential. Special care has been taken to minimise the size of this package and the data it contains, including use of efficient binary encodings and maximising compressibility, however this is as small as we have managed to make it.

*Expected future size increases:* It is expected that the initial release of this package will be the only release for a long time since the underlying maths is unlikely to change. Should any further releases be produced, it is expected that the size will remain roughly the same. It is also likely that it would be acceptable to only retain a copy of the latest release on PyPI if necessary.

**Comment by di** [comment]
I've set the upload limit for `vc2-conformance-data` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
