### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mdazam1942** [pypa/pypi-support#922]
Request for account recovery.

## PyPI Username

mdazam1942

##  Reason for request

  - Lost 2FA authentication app

Reason:
Lost 2FA application access due to phone reset and unfortunately haven't generated any recovery codes.

**Comment by mdazam1942** [comment]
@ewdurbin Thanks for updating the issue. Is there anything I can do to accelerate the process? I would really appreciate your help.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
