### ISSUE TITLE
Issue: Limit Request: phylodeep - 500 MB

### ISSUE THREAD

**Issue by JakubVoz** [pypa/pypi-support#924]
**Project**
Project name: phylodeep
Project link on pypi: https://pypi.org/project/phylodeep/

**Does this project already exist?**
The project already exists (vs 0.0.80 hit the size limit)

**Size of release/project**
Today, the release has a size of >300 MB (vs 0.0.80), I would like to ask for a limit of 500 MB for the final fully functional version of the project.

**Which indexes**
PyPI

**Reasons for the request**
The project enables to obtain estimates of epidemilogical parameters (such as R_0, infectious period...) from phylogenetic data using pretrained machine learning models. To assess confidential intervals, I use a pre-predicted values on simulations that must be stored in the project.

Today they are compressed (csv.gz format) and contain only values that are needed for computation.

**Comment by di** [comment]
I've set the upload limit for `phylodeep` to 500 MB on PyPI. Please be mindful of the frequency of releases at that size.
