### ISSUE TITLE
PEP 541 Request: django-doctor

### ISSUE THREAD

**Issue by richtier** [pypa/pypi-support#930]
**Project to be claimed**

`django-doctor`: https://pypi.org/project/django-doctor

**Your PyPI username**

`richtier`: https://pypi.org/user/richtier

**Reasons for the request**

The project has not bee updated in over 5 years and is broken on all the currently supported versions of Django. I would like to release my django linter with that name as that's the name of my existing thing: https://django.doctor/

**Maintenance or replacement?**

Replacement

**Source code repositories URLs**

_No response_

**Contact and additional research**

I could not find a way to contact the current owners

**Code of Conduct**

- [X] I agree to follow the PSF Code of Conduct

**Comment by richtier** [comment]
contributors to the project include @jonklo and @benoitbryon

A few months ago I tried contacting one via Twitter and even paid £30 a month to message another via LinkedIn :laughing:

**Comment by benoitbryon** [comment]
Hi, **I was "just a contributor" of django-doctor. @jonklo is the creator/owner** of the package. I've not been using Django for a while, so I cannot tell about project's status. I'm not planning to update django-doctor. So far, it is kind of "I have no objection" from me (and  again: I'm not the owner).

**Comment by jonklo** [comment]
Sorry for not getting back to you sooner on this, @richtier

We've deleted the project on Pypi now, best of luck with your project!

**Comment by richtier** [comment]
wonderful, thanks :)
