### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by joeldodge79** [pypa/pypi-support#933]
**PyPI Username**

joeldodge_looker

**Reason for request**

Lost 2FA authentication app or security token

**Code of Conduct**

- [X] I agree to follow the PSF Code of Conduct

**Comment by joeldodge79** [comment]
I'm still able to publish packages because my API tokens still work but I really need to get in and add another owner, halp please! Many thanks, Joel

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
