### ISSUE TITLE
PEP 541 Request: portage

### ISSUE THREAD

**Issue by zmedico** [pypa/pypi-support#934]
**Project to be claimed**

`PROJECT_NAME`: https://pypi.org/project/portage

**Your PyPI username**

`USER_NAME`: https://pypi.org/user/zmedico

**Reasons for the request**

The project page returns 404, but I am not able to create it. It fails like this when I try to upload:
```
$ python -m twine upload --verbose dist/*
Uploading distributions to https://upload.pypi.org/legacy/
  dist/portage-3.0.16-py3-none-any.whl (1.6 MB)
  dist/portage-3.0.16.tar.gz (1.3 MB)
Enter your username: zmedico
Enter your password: 
Uploading portage-3.0.16-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.65M/1.65M [00:01<00:00, 997kB/s]
Content received from server:
<html>
 <head>
  <title>403 The user 'zmedico' isn't allowed to upload to project 'portage'. See https://pypi.org/help/#project-name for more information.</title>
 </head>
 <body>
  <h1>403 The user 'zmedico' isn't allowed to upload to project 'portage'. See https://pypi.org/help/#project-name for more information.</h1>
  Access was denied to this resource.<br/><br/>
The user &#x27;zmedico&#x27; isn&#x27;t allowed to upload to project &#x27;portage&#x27;. See https://pypi.org/help/#project-name for more information.


 </body>
</html>
/usr/lib/python3.8/site-packages/twine/__main__.py:32: ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.39', 59202), raddr=('18.224.42.42', 443)>
  result = (
ResourceWarning: Enable tracemalloc to get the object allocation traceback
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'zmedico' isn't allowed to upload to project 'portage'. See https://pypi.org/help/#project-name for more information.
```

**Maintenance or replacement?**

Replacement

**Source code repositories URLs**

* https://gitweb.gentoo.org/proj/portage.git/
* https://github.com/gentoo/portage (mirror)

**Contact and additional research**

I have been the primary maintainer of this project for many years, so I am sure that there is no other active owner. The official project page is here:

https://wiki.gentoo.org/wiki/Project:Portage

All of the previous source distributions for the project are hosted in my dev space here:

https://dev.gentoo.org/~zmedico/portage/archives/

These are the first files that I plan to publish on pypi.org:

https://dev.gentoo.org/~zmedico/portage/archives/portage-3.0.16.tar.gz
https://dev.gentoo.org/~zmedico/portage/archives/portage-3.0.16-py3-none-any.whl

I've created this wiki page where I'm posting status on the topic:

https://wiki.gentoo.org/wiki/Project:Portage/Releases-On-PyPi

**Code of Conduct**

- [X] I agree to follow the PSF Code of Conduct

**Comment by webknjaz** [comment]
@zmedico AFAIK PyPI has a list of forbidden names to prevent malicious actors from abusing popular names. This is probably what's happening. I think @di / @pradyunsg could check my guess.

@zmedico out of curiosity, what is the use-case for having portage on PyPI? Is there a similar plan for emerge?

**Comment by zmedico** [comment]
> @zmedico AFAIK PyPI has a list of forbidden names to prevent malicious actors from abusing popular names. This is probably what's happening.

Yes, that's reasonable for popular names that aren't reserved.

> @zmedico out of curiosity, what is the use-case for having portage on PyPI? Is there a similar plan for emerge?

There are various cases where a person might want to manipulate gentoo packages (source or binary) within a context where pip is an attractive means to install portage (and portage does include **emerge**). One of the most obvious applications would be a tool to fetch files for an offline gentoo system ([bug 629048](https://bugs.gentoo.org/629048)). I imagine that we will find plenty of other applications as we move forward with this.

**Comment by pradyunsg** [comment]
This seems to be a registered package with 0 releases.

I don't think we need to reach out to the original author for this, since it is definitely an invalid project. I've marked this for an admin transfer. Sadly, I can't provide an estimate for when a PyPI admin would be able to perform the transfer though (All PyPI admins are volunteers).

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by zmedico** [comment]
Thank you! It works:

https://pypi.org/project/portage/3.0.18/

**Comment by webknjaz** [comment]
> Thank you! It works:
> 
> [pypi.org/project/portage/3.0.18](https://pypi.org/project/portage/3.0.18/)

Nitpick: you should really upload an sdist too. The best practice is to have both a tarball and a wheel. Plus the metadata needs some love (repo URL in project_urls + mark long description as markdown). Also, having cexts you probably need to produce manylinux wheels.
But yeah, that's out of scope of this issue :)

**Comment by zmedico** [comment]
> > Thank you! It works:
> > [pypi.org/project/portage/3.0.18](https://pypi.org/project/portage/3.0.18/)
> 
> Nitpick: you should really upload an sdist too. The best practice is to have both a tarball and a wheel. Plus the metadata needs some love (repo URL in project_urls + mark long description as markdown). Also, having cexts you probably need to produce manylinux wheels.
> But yeah, that's out of scope of this issue :)

Thanks for your feedback! Yes, I will work on improving this. The cexts are entirely optional, and I don't have plans to install them yet.
