### ISSUE TITLE
PEP 541 Request: esm

### ISSUE THREAD

**Issue by tomsercu** [pypa/pypi-support#936]
**Project to be claimed**

`esm`: https://pypi.org/project/esm

**Your PyPI username**

`tomsercu`: https://pypi.org/user/tomsercu

**Reasons for the request**

Project name seems available, but "Receiving 403 Forbidden - The user 'tomsercu' isn't allowed to upload to project 'esm'.". Most likely the name is taken by a removed project.

**Maintenance or replacement?**

Maintenance

**Source code repositories URLs**

https://github.com/facebookresearch/esm

**Contact and additional research**

On test.pypi I got the ownership transfer from user `konstin`, who has been helpful and has confirmed they are not able to publish on the real index either.

**Code of Conduct**

- [x] I agree to follow the PSF Code of Conduct

**Comment by tomsercu** [comment]
Checking in if this would be moving forward any time soon? This seems a relatively clear-cut case.

**Comment by yeraydiazdiaz** [comment]
Hello, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
