### ISSUE TITLE
PEP 541 Request: innertube

### ISSUE THREAD

**Issue by tombulled** [pypa/pypi-support#937]
### Project to be claimed

`innertube`: https://pypi.org/project/innertube

### Your PyPI username

`tbulled`: https://pypi.org/user/tbulled

### Reasons for the request

Hi, the current `innertube` package that was released Sep 30, 2020 contained no functionality then, and has continued to [contain no function](https://github.com/eriknw/innertube/blob/master/innertube/core.py) for over 5 months now. Under PEP 541, I believe this constitutes an *Invalid Project*, namely falling under *project is name squatting (package has no functionality or is empty)*. I would very much like to claim the name to upload my fully functioning `innertube` package. Many thanks, Tom

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Their repository: https://github.com/eriknw/innertube | My repository: https://github.com/tombulled/innertube

### Contact and additional research

I couldn't find an email address on PyPi so instead created an issue on their repository [here](https://github.com/eriknw/innertube/issues/1), however since the package appears to be considered invalid, I decided to file an issue here as well

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by eriknw** [comment]
I am the current author of `innertube` and no impropriety was intended.  I have done substantial (unpublished) design that I wish to have the opportunity to continue to develop under the project name `innertube`.  I have pushed minimal functionality (and more is in progress).  I am sorry for not doing so sooner as I had intended.  My only defense is that this has been a very, *very* stressful and anxious few months, and I ask for a bit of grace and understanding.

@tombulled has made a reasonable request, and has been very courteous while doing so.  If I fail to make much more progress with `innertube` this year, then I will happily and voluntarily relinquish the name on PyPI (but feel free to ping me again as you feel appropriate).

**Comment by tombulled** [comment]
Hi @eriknw,

Thanks for the taking the time to reply and justify your use of the package name.

My understanding is that package names should only be claimed when there is actually something to upload (e.g. beyond *Coming soon*). Otherwise this is technically name-squatting and constitutes an invalid package. As in your case, due to Covid, your development got stunted, whereas this may not have affected other developers such as myself as much. As such, this wouldn't have been an issue had you registered the namespace *after* developing some functionality to use it for, not in anticipation thereof.

Whilst I appreciate your reasons, these have definitely been stressful times for us all, I would recommend that in future you only reserve names when you are 100% ready to make use of them. I appreciate you updating the package to now contain functionality and find your offer of voluntarily relinquishing the package name in the future subject to a lack of progress being made over the coming year very generous.

For the time being I'll register an alternate package name, and will close this issue as your package is no longer invalid. 

All the best with your project,
Kind regards,

Tom
