### ISSUE TITLE
PEP 541 Request: icdff

### ISSUE THREAD

**Issue by jeffkaufman** [pypa/pypi-support#938]
### Project to be claimed

`icdiff`: https://pypi.org/project/icdiff

### Your PyPI username

`jefftk`: https://pypi.org/user/jefftk

### Reasons for the request

The maintainer has stopped pulling new versions.  I am the upstream author, and would be happy to start packaging for pypi.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/jeffkaufman/icdiff

### Contact and additional research

The current maintainer is not responding (ex: https://github.com/jeffkaufman/icdiff/issues/164), and hasn't pulled updates in over a year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jeffkaufman** [comment]
@vnitinv as current maintainer

**Comment by vnitinv** [comment]
@jeffkaufman Sorry Jeff, I have not been able to give time to this. If anything is needed from my end, do let me know.
Also, the subject line says `icidff`, it should be `icdiff`

**Comment by jeffkaufman** [comment]
@vnitinv if you would like to continue as maintainer I'd still be happy for you to do that; I just released 2.0.0

On the other hand, if you're done you could transfer it to me, and we could close this ticket?

**Comment by jeffkaufman** [comment]
@vnitinv could you do one of:

1. Respond here saying you are OK giving up pypi maintainership
2. Transfer pypi maintainership to me
3. Resume maintenance of icdiff on pypi

**Comment by vnitinv** [comment]
I am OK giving up the maintainership.

**Comment by vnitinv** [comment]
![Uploading image.png…]()

**Comment by vnitinv** [comment]
![image](https://user-images.githubusercontent.com/767016/111338573-0f52bc80-869d-11eb-805e-bb348f86fe42.png)

**Comment by jeffkaufman** [comment]
@vnitinv Sorry, I'm jefftk on pypi!

**Comment by vnitinv** [comment]
@jeffkaufman I added you as owner. Sorry that I was not able to contribute.

**Comment by jeffkaufman** [comment]
Thanks!  Accepted!
