### ISSUE TITLE
Limit Request: cupy-cuda112 - 250 MB

### ISSUE THREAD

**Issue by kmaehashi** [pypa/pypi-support#939]
### Project

cupy-cuda112

### Does this project already exist?

- [X] Yes

### Size of release/project

250 MB

### Which indexes

PyPI

### Reasons for the request

We're developing [CuPy](https://github.com/cupy/cupy), which provides an implementation of NumPy-compatible multi-dimensional array accelerated by CUDA. The limit increase is needed to include dependent libraries (NVIDIA NCCL, etc.) to wheel packages.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Limit increased to 250 MiB.

Note current total project size is 401 MiB with a 10.0 GiB limit for all uploads.

**Comment by kmaehashi** [comment]
@ewdurbin Thank you for your help as always! :pray:
