### ISSUE TITLE
test.pypi.org - paramiko being squatted

### ISSUE THREAD

**Issue by bitprophet** [pypa/pypi-support#94]
This doesn't feel 100% PEP-541 accurate, since it's the test index. Please advise if that's wrong and I'll use the template in future!

I am `bitprophet` on both PyPI instances, but some of my projects that exist on production PyPI have been squatted by other users on `test.pypi.org`. The one that I bumped into today is `paramiko`:

- Prod: https://pypi.org/project/paramiko/
- Test: https://test.pypi.org/project/paramiko/ - notice how this is owned by https://test.pypi.org/user/gene1wood/ and not https://test.pypi.org/user/bitprophet/

There may be others like this too, I haven't iterated all my projects yet. Expecting to file separate tickets later if it comes up. Thanks!

**Comment by ewdurbin** [comment]
Transfer complete. For test.pypi.org, 541 doesn't itself apply... but yeah we need the same information. It's not super common we get test.pypi.org requests... but I suppose a separate template could be created.
