### ISSUE TITLE
PEP 541 Request: vapi-client-bindings

### ISSUE THREAD

**Issue by anusha94** [pypa/pypi-support#946]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/vapi-client-bindings

### Your PyPI username

`USER_NAME`: https://pypi.org/user/anushah

### Reasons for the request

`vapi-client-bindings` was earlier reclaimed by VMware Eng team in 2019. Details in this issue - https://github.com/pypa/pypi-support/issues/105

I am from VMware engineering team and would like to claim the project-name. Even though the project name is up for grabs, I get the following error
```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'anushah' isn't allowed to upload to project 'vapi-client-bindings'. See https://pypi.org/help/#project-name for more information.
```

Kindly advise on how to proceed further.

Thanks!

### Source code repositories URLs

https://github.com/vmware/vsphere-automation-sdk-python/

### Contact and additional research

This is not a transfer related issue. So I did not contact the previous owner yet. Please let me know how to proceed further

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by anusha94** [comment]
@shwetapurohit @vmehtavmware

**Comment by yeraydiazdiaz** [comment]
Hello, the project name `vapi-client-bindings` was placed in the prohibited name list by @pypa/warehouse-admins, I don't see a problem making it available again but I don't have the permissions to do so.

**Comment by di** [comment]
I've removed the prohibition.
