### ISSUE TITLE
Handled similarly. Our only other recourse would be to disable new project registration... but that seems untenable.

### ISSUE THREAD

**Issue by s1dsmack** [pypa/pypi-support#947]
Handled similarly. Our only other recourse would be to disable new project registration... but that seems untenable.

_Originally posted by @ewdurbin in https://github.com/pypa/pypi-support/issues/935#issuecomment-788972435_

**Comment by s1dsmack** [comment]
Just wanted to know what the current status was on the user RemindSupplyChainRisks uploading files and impacting PyPI? My understanding is that I should be careful using pip install. Since I use pip install a lot, just wanted to get some clarity and/or certainty that I can continue using pip install again without worrying about accidentally loading something nefarious. TIA

**Comment by ewdurbin** [comment]
This user and others are able to upload projects with any project name, so long as that project name is not registered by another user or has not been prohibited by the PyPI administrators. We continue to monitor for such project uploads as well as respond to reports when they are discovered, generally by removing the project and often by prohibiting the project name.

Users should _always_ be careful when installing projects from PyPI via pip or other tools to ensure that they are installing what they intended.
