### ISSUE TITLE
PEP 541 Request: smp 0.0.1

### ISSUE THREAD

**Issue by jacobmiller22** [pypa/pypi-support#949]
### Project to be claimed

`smp`: https://pypi.org/project/smp

### Your PyPI username

`jacobmiller22`: https://pypi.org/user/jacobmiller22

### Reasons for the request

I  believed that this project was abandoned. There has been only one upload of the project since December of 2017. I also have been granted permission by the current owner. Please see below.

### Maintenance or replacement?

Replacement

### Contact and additional research

Below I have contacted the owner of the project 3 times. This morning they confirmed that I can use the package name.

Jacob Miller <jacobmillerdev@gmail.com>
Sun, Feb 7, 2:06 AM
to zgwcome

Hello zgwcome,

  My name is Jacob and I have developed a python project that would benefit greatly if I could use the name "smp" for the project. Seeing that there was only ever one version of your "smp" project and it was over 3 years ago. Additionally, there is no working link to any source code and your homepage is not a registered domain name, which leads me to believe that you check off most of the boxes for an abandoned project according to PEP 541. If you wouldn't mind, I would like to initiate a name transfer unless you have any reservations to do so. 

  If there is no response, the PEP 541 guidelines indicate that I must attempt to make contact at least 3 times before the project can be determined abandoned.

  I look forward to hearing from you.

Thank you,
Jacob
---------------------------------------------------------------------------------------------

Jacob Miller <jacobmillerdev@gmail.com>
Sat, Feb 20, 1:14 AM
to zgwcome

Hello zgwcome,

  My name is Jacob and I have developed a python project that would benefit greatly if I could use the name "smp" for the project. Seeing that there was only ever one version of your "smp" project and it was over 3 years ago. Additionally, there is no working link to any source code and your homepage is not a registered domain name, which leads me to believe that you check off most of the boxes for an abandoned project according to PEP 541. If you wouldn't mind, I would like to initiate a name transfer unless you have any reservations to do so. 

  If there is no response, the PEP 541 guidelines indicate that I must attempt to make contact at least 3 times before the project can be determined abandoned.

  I look forward to hearing from you.

Thank you,
Jacob
------------------------------------------------------------------------------
Hello zgwcome,

  My name is Jacob and I have developed a python project that would benefit greatly if I could use the name "smp" for the project. Seeing that there was only ever one version of your "smp" project and it was over 3 years ago. Additionally, there is no working link to any source code and your homepage is not a registered domain name, which leads me to believe that you check off most of the boxes for an abandoned project according to PEP 541. If you wouldn't mind, I would like to initiate a name transfer unless you have any reservations to do so. 

  If there is no response, the PEP 541 guidelines indicate that I must attempt to make contact at least 3 times before the project can be determined abandoned.

  I look forward to hearing from you.

Thank you,
Jacob
------------------------------------------------------------------------------

zgwcome
10:46 AM (22 minutes ago)
to me

ok, you can use it

	
zgwcome
zgwcome@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @jacobmiller22, thanks for the detailed report, as you can imagine moderators need confirmation from the owner so I still need to attempt contact, hopefully I will get a reply quickly and proceed with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
