### ISSUE TITLE
PEP 541 Request: Transfer ownership of empty 'compose' package

### ISSUE THREAD

**Issue by mentalisttraceur** [pypa/pypi-support#95]
**Project to be claimed**
`compose`: https://pypi.org/project/compose

**Your PyPI username**
`mentalisttraceur`: https://pypi.org/user/mentalisttraceur

**Reasons for the request**
The project link leads to a 404.
`pip install compose` does not find it either.

But trying to upload causes a permissions error saying my user does not have permissions for that project, as if it does exist.

It appears this is a case of an empty project, which seems to make it an [invalid project according to PEP-541](https://www.python.org/dev/peps/pep-0541/#invalid-projects).

I have my own little package that I started which I think is a good fit for the name, so I'd like to take it since nothing is being done with it.

**Maintenance or replacement?**
Neither? Replacement? There is nothing there.

**Contact and additional research**
Since the package does not show up, there is no contact information to be found.

Another author did upload a package named `compose` to test.pypi.org, but then picked a different name (`composeml`) instead for the official pypi.org release.

**Comment by mentalisttraceur** [comment]
Apologies, I accidentally clicked submit early (I blame mobile devices and touch screens in general) - I will finish editing the issue momentarily.

**Comment by mentalisttraceur** [comment]
I have [contacted](https://github.com/FeatureLabs/compose/issues/91) the maintainer listed on the test.pypi.org `compose` package, in order to learn

1. if they have anything to do with the `compose` on pypi.org, or if they hit the same issue I did, and

2. if they still wanted the `compose` pip name for their project or if they were fine with me having it since they already released under `composeml`.

I think that's all the due diligence I can do for now.

**Comment by jamadden** [comment]
The test.pypi.org `compose` package appears to be unrelated to the empty package on pypi.org.

I confirm that https://pypi.org/project/compose is empty (its sole distribution has been removed). It was uploaded at version 0.0 and then immediately marked hidden. It appears to be name squatting.

I'll ask the PyPI admins to initiate a transfer.

**Comment by ewdurbin** [comment]
transfer complete.
