### ISSUE TITLE
Limit Request: torch - 850 MB

### ISSUE THREAD

**Issue by seemethere** [pypa/pypi-support#950]
### Project

torch

### Does this project already exist?

- [X] Yes

### Size of release/project

850 MB

### Which indexes

PyPI

### Reasons for the request

We've found a regression in our latest release for `v1.8.0` of our binaries and cannot make it under our current limit of 750MB without cutting critical CUDA functionality.

Related issues: https://github.com/pytorch/pytorch/issues/53336

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by seemethere** [comment]
cc @malfet, @soumith

**Comment by jspisak** [comment]
@di - is this something you can help with?

**Comment by jspisak** [comment]
cc @webknjaz - can you help here as well?

**Comment by webknjaz** [comment]
@jspisak I'm not a PyPI admin, I don't have the power to help you. Also, the admins are volunteers that do this when they have spare time. My understanding is that the requests are processed FIFO style so you may have to fail until they get to your case.

**Comment by jspisak** [comment]
got it. thanks @webknjaz  - we're investigating alternatives but we could definitely use help here if possible..

**Comment by jspisak** [comment]
cc @rgommers

**Comment by rgommers** [comment]
@pradyunsg or @di this is quite pressing, it's a blocker for a new PyTorch release that fixes a regression in 1.8.0 Sorry to ping again, but could one of you please approve this request?

This is also a nice illustration of the issues discussed in https://discuss.python.org/t/what-to-do-about-gpus-and-the-built-distributions-that-support-them/7125. The PyTorch 1.8.0 wheels are ~40 MB smaller than the 1.7.0 ones despite adding a lot of new functionality, because the PyTorch team made an effort to reduce the amount of pre-compiled code for different GPU architectures. This is the cause of the regression, and due to limitations in CUDA itself. I plan to expand on this on the Discourse thread.

**Comment by ewdurbin** [comment]
limit increased to 850 MiB.

Note current total project size on PyPI is 54.9 GiB with a total limit of 80.0 GiB

**Comment by rgommers** [comment]
Thanks @ewdurbin!

**Comment by malfet** [comment]
Thanks @ewdurbin !

**Comment by cooperlees** [comment]
PyTorch maintainers - How useful is it having the yanked + < 1.0.0 versions still on PyPI? Is it worth deleting them to create more headroom?

Long tern too, is it worth putting an expected Lifetime on a version so it can be purged from PyPI infra eventually and help everyone?

**Comment by jspisak** [comment]
thanks!!!!

**Comment by rgommers** [comment]
> Long tern too, is it worth putting an expected Lifetime on a version so it can be purged from PyPI infra eventually and help everyone?

I asked about exactly this on the Discourse thread linked above, and @di said there:

_I think I can speak on behalf of the other PyPI maintainers: generally our goal is for PyPI to have whatever exists on PyPI exist exactly as it was uploaded, ~indefinitely (unless the owner chooses to remove it)._

_This is why we don’t allow releases to be overwritten, don’t change metadata on existing releases, and don’t have a “cleanup” policy like this. There is undoubtedly some users that such a policy would be disruptive_

That Discourse thread has some more thoughts. If despite the above you want to look at this, I suggest starting with old nightlies - you can get rid of about 1 TB without too much trouble. Old official releases (even if `<1.0.0`) is much less interesting, and unlike old nightlies those have actual historical value.
