### ISSUE TITLE
Limit Request: apache-flink-libraries - 300 MB

### ISSUE THREAD

**Issue by HuangXingBo** [pypa/pypi-support#952]
### Project

apache-flink-libraries

### Does this project already exist?

- [X] Yes

### Size of release/project

300MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

The existing apache-flink package contains some platform-independent libraries. We extract them and put them into the apache-flink-libraries project, which can effectively reduce the growth rate of the entire apache-flink project. The size of apache-flink-libraries packages are over limit 200MB, so we want to extend the file limit size to 300MB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by HuangXingBo** [comment]
Hello, any update on this issue？This will block the release of Apache Flink 1.13. Thanks a lot for your help!

**Comment by HuangXingBo** [comment]
cc @di

**Comment by di** [comment]
I've set the upload limit for `apache-flink-libraries` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
