### ISSUE TITLE
PEP 541 Request: pyrets

### ISSUE THREAD

**Issue by SDesch** [pypa/pypi-support#953]
### Project to be claimed

`pyrets`: https://pypi.org/project/pyRETS/

### Your PyPI username

`SDesch`: https://pypi.org/user/SDesch/

### Reasons for the request

The project has not seen a release since 2012 and does not contain any code besides a defunct `setup.py`. I'd like to use the name *pyrets* for open-sourcing an internal project in the near future. 

### Maintenance or replacement?

Replacement

### Contact and additional research

I tried contacting the author via email using the address listed on the project page (same one as in the `setup.py`) but the email could not be delivered because apparently the email address does not longer exist. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello, I can confirm the project has a no functionality and is therefore considered invalid. I will attempt contact and allow one week for replies before proceeding with the transfer.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
