### ISSUE TITLE
PEP 541 Request: ratelimiter

### ISSUE THREAD

**Issue by gear4s** [pypa/pypi-support#954]
### Project to be claimed

`ratelimiter`: https://pypi.org/project/ratelimiter

### Your PyPI username

`aquelle1`: https://pypi.org/user/aquelle1

### Reasons for the request

It needs to be updated for Python 3.9, which I've done. Its repository has not been updated for 3 years and I believe the maintainer has abandoned it.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

https://github.com/gear4s/ratelimiter

### Contact and additional research

Single response on the issue: https://github.com/RazerM/ratelimiter/issues/10
Outstanding PR fixing the issue: https://github.com/RazerM/ratelimiter/pull/11

No PR has been merged to fix the issue, but the maintainer is aware and not merging.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello, I will now start the reachability process to contact @RazerM, hopefully we will hear from him soon.

**Comment by RazerM** [comment]
I would like to refuse the PEP 541 transferral, but I'll happily grant you (@gear4s) maintainer/collaborator status to take the project forward.

I have invited you as a maintainer on PyPI and collaborator on GitHub. Contact me by email if you're missing any permissions or there's something you need me to do. I would prefer we keep using my version of the repository which has old issues etc, although feel free to deal with those as you see fit.

(I'd like to stay as owner, just as a precaution.)

**Comment by gear4s** [comment]
Sounds good. It's just maintenance that needs to be done, anyway.

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @RazerM , closing as contact has been made.
