### ISSUE TITLE
Limit Request: humann - 150 MB

### ISSUE THREAD

**Issue by ljmciver** [pypa/pypi-support#955]
### Project

https://pypi.org/project/humann

### Does this project already exist?

- [X] Yes

### Size of release/project

150

### Which indexes

PyPI

### Reasons for the request

We are working on a new release v3.0 which will complete our beta testing phase. We last released v3.0.alpha versions. With the upcoming non-alpha release we will add a couple more data files that will put us over our current 100MB limit.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ljmciver** [comment]
Hi @di , Sorry in advance for pinging you about this increase as I am sure you are swamped. We would like to tag a new release this week and we need the additional space (even just 10MB more, so 110MB, would be great) would allow us to do so. We have totally used up our existing 100MB and need to add two more files.

Please let me know if you need any additional information from me.

Thank you in advance for your time!

Thank you,
Lauren

**Comment by di** [comment]
Hi @ljmciver, the "Reasons for the request" is for us to understand why the project is larger than average. Can you explain what your project is, what "data files" you are including, why they need to be included, etc? Thanks!

**Comment by ljmciver** [comment]
Hi @di , Yes, sorry I did not include that! 

HUMAnN v3 is a pipeline for efficiently and accurately determining the coverage and abundance of microbial pathways in a community from metagenomic data. It incorporates a tool named MetaPhlAn that answers the question "What microbes are there?" while the HUMAnN tool answers the question of "What are the microbes doing (with respect to function)?".

For our HUMAnN v3 release we upgraded our databases to reflect a newer UniRef reference and also updated our pathways to use the latest MetaCyc database. These two databases have increased in size over the last few years so the information that we pull from them to create our databases has also increased. We package some of our database files separately, those that a user might want to optionally use, in a ~2Gb tar archive that the user can download after installing the tool with pip. However, there are some database files that we want to include with the pypi package by default because they are always needed by the tool. These database files are not small and have increased in size a bit which requires us to ask for a bit more data.

Please let me know if you need any other information!

Thank you!
Lauren

**Comment by ljmciver** [comment]
Hi @di , I just finished building our new release with the new databases. It looks like we are at 153MB in total. 

If we could increase our max size to 175MB that would be great.

Please let me know if you need any other information from me.

Thank you,
Lauren

**Comment by di** [comment]
I've set the upload limit for `humann` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
