### ISSUE TITLE
PEP 541 Request: SCALE

### ISSUE THREAD

**Issue by jsxlei** [pypa/pypi-support#956]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/scale

### Your PyPI username

`USER_NAME`: https://pypi.org/user/jsxlei

### Reasons for the request

The orignal project has been abandoned:
1. cannot install via pip install scale
2. the source code neither available in the PyPI website nor in the Github.
3. all the links the owner provide is invalid.
4. never update since first release from 2014.
5. I have developed tools for single-cell analysis also called SCALE (Single-cell ATAC-seq analysis via Latent feature Extraction) since 2018 and recently developed an upgraded version SCALE v2. I expect there will be a lot of users applying my open source tool SCALE. For their convenience download and installation through pip install scale to make it more popular. Here is my github: https://github.com/jsxlei/SCALE  .

### Maintenance or replacement?

Replacement

### Source code repositories URLs

previous repository: https://pypi.org/project/scale/

My two repositories: https://pypi.org/project/scale-atac/   &  https://pypi.org/project/scale-v2/

### Contact and additional research

I have sent a email to the current owner: Jasper Danielson, email: gwenndragon@gmail.com, but get no reply.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello, I can confirm the project has a single release with no associated files and is therefore considered invalid. I will attempt contact and allow one week for replies before proceeding with the transfer.

**Comment by jsxlei** [comment]
Thank you very much. It really helps a lot.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by jsxlei** [comment]
Thank you very much!
