### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by norosa** [pypa/pypi-support#958]
### PyPI Username

noromo

### Reason for request

I have access to my account. however, I am trying to change my email. unfortunately, I entered my new email wrong several times (and thus could not receive the confirmation messages). I deleted the requests in case they went to valid email accounts I do not control

now I am trying to add a new email and I am getting a "too many requests" message saying I have tried to add too many emails and that I should verify them (which I can't because of the error)

I am creating this issue a second time, because I thought the issue would be private and my request included private information. I redacted the old issue description and closed it. sorry for the noise

perhaps it would be a good idea to explicitly warn people on this page that details they submit will be viewable on the public internet

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Any rate limiter you were up against is likely expired at this point. If you're still unable to add your new address please re-open.
