### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Vlad-clou** [pypa/pypi-support#959]
### PyPI Username

giladotan

### Reason for request

I formatted my phone (I deleted everything and reinstalled only the operating system) and I forgot to recover my 2FA and now I'm locked out of my account.

my email: gilad.dotann@gmail.com

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Duplicate #914
