### ISSUE TITLE
Account Recovery: pradyunsg

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pypi-support#96]
My previous phone has died a sad death, and I lost access to my 2FA application with it. I've switched to a new device, and setup my new 2FA authenticator application on it.

I'd like to request a 2FA reset on my account, so that I can switch to my newer 2FA setup.

PyPI Username: pradyunsg

Context: https://mobile.twitter.com/pradyunsg/status/1200343878353580032

**Comment by pradyunsg** [comment]
A gentle nudge on this @ewdurbin

**Comment by ewdurbin** [comment]
@pradyunsg thanks for verifying this request out of band. TOTP has been reset for your user.

**Comment by pradyunsg** [comment]
Hurray! Many thanks @ewdurbin!
