### ISSUE TITLE
Limit Request: vice - 200 MB

### ISSUE THREAD

**Issue by giganano** [pypa/pypi-support#960]
### Project

https://pypi.org/project/vice/

### Does this project already exist?

- [X] Yes

### Size of release/project

116 MB 

### Which indexes

PyPI, TestPyPI

### Reasons for the request

This package provides calculations of chemical evolution in galaxies for researchers in my field. There are some data files that it stores internally which are causing the size issue, but the largest is only 16 MB over the 100 MB default limit. 

Note: I'm not sure which numbers to put where. The largest wheel in the upcoming release is 116 MB, but if 200 MB would be possible, it'd allow me to expand some of the included data a little more comfortably. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `vice` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
