### ISSUE TITLE
PEP 541 Request: datahub

### ISSUE THREAD

**Issue by hsheth2** [pypa/pypi-support#962]
### Project to be claimed

`datahub`: https://pypi.org/project/datahub

### Your PyPI username

`hsheth2`: https://pypi.org/user/hsheth2

### Reasons for the request

The existing "datahub" project is abandoned - nobody has touched it in over 10 years. 

I'd like to replace it with a Python package for LinkedIn DataHub (https://github.com/linkedin/datahub/), which has a vibrant and active community.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

I was able to find this source code: https://code.launchpad.net/~szybalski/datahub.main/trunk.

### Contact and additional research

The existing "datahub" package seems to be a set of scripts for pulling data from the US NHTSA. The URL listed at https://bazaar.launchpad.net/~szybalski/datahub.main/trunk/view/head:/datahub/setup.py#L214 yields a 404. 

There's a related package (https://pypi.org/project/datahub.gov.dot.nhtsa.recall/) with an analogous source repository (https://code.launchpad.net/~szybalski/datahub.gov.dot.nhtsa.recall/trunk). The demo website for that package (http://lucasmanual.com/recall) also no longer works/exists. 

I've already twice emailed the listed maintainer, Lukasz Szybalski, at the address listed on the PyPI site. The first email was sent a month ago, on Feb 14, and neither email has received a response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by hsheth2** [comment]
It's been 6 weeks since I first attempted to contact the listed maintainer, and I've attempted three times over that period. See here for the emails I sent: [Gmail - Datahub project name on PyPI.pdf](https://github.com/pypa/pypi-support/files/6223547/Gmail.-.Datahub.project.name.on.PyPI.pdf).

As per PEP 541, I believe the author should be considered unreachable, and hence the project considered abandoned.

**Comment by hsheth2** [comment]
@ewdurbin @di would love if one of you could take a look at this when you get a chance - thanks!

**Comment by yeraydiazdiaz** [comment]
Hello @hsheth2, I will now start the reachability process with the owner, I believe his GitHub user is @lszyba1 although there's not much activity. Hopefully we will hear back soon and move forward with the transfer.

**Comment by hsheth2** [comment]
Thanks @yeraydiazdiaz!

**Comment by hsheth2** [comment]
@lszyba1 awesome!

My pypi username is also `hsheth2`

**Comment by lszyba1** [comment]
Hello,
I have added you as maintainer. 
Feel free to delete current releases and upload a new one based on a project.
I've added myself to slack project. and msg'ed you on there as well with my contact info.
I will request this ticket be closed.

Goodbye old datahub project : http://lucasmanual.com/mywiki/DataHub
Welcome new datahub project: https://datahubproject.io/

Talk to you there.
Lucas

**Comment by yeraydiazdiaz** [comment]
Thanks for replying @lszyba1.
