### ISSUE TITLE
Limit Request: ldcpy - 300 MB

### ISSUE THREAD

**Issue by pinarda** [pypa/pypi-support#963]
### Project

ldcpy

### Does this project already exist?

- [X] Yes

### Size of release/project

273 MB

### Which indexes

PyPI

### Reasons for the request

ldcpy is a utility for gathering and plotting metrics from NetCDF or Zarr files. We have a number of example datasets that are used in the documentation and tutorial, which hare taking up much of the space in the package. These are all necessary to showcase the different variables and file types the package supports.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `ldcpy ` to 300 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
