### ISSUE TITLE
PEP 541 Request: cardano

### ISSUE THREAD

**Issue by emesik** [pypa/pypi-support#966]
### Project to be claimed

`Cardano`: https://pypi.org/project/Cardano

### Your PyPI username

`emes`: https://pypi.org/user/emes

### Reasons for the request

I have started a project of Python module for Cardano blockchain. Unlike already existing Python tools, this one is intended to be a comprehensive library handling all possible features of the underlying platform. The project has been also proposed for a development grant (https://cardano.ideascale.com/a/dtd/Python-module/333770-48088) and received very positive feedback.

The project has already the first release (0.1) and a roadmap for further milestones.

The module name `cardano` which I request to take over has been squatted by a user who performed a spamming attack on PyPi. The user's account has been deleted already and there's no way of initiating contact.

Also, I requested similar name takeover for `monero` module name from the same user and received a positive decision back in 2019.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/emesik/cardano-python

### Contact and additional research

Initiating contact is not possible as the user's account has been deleted.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by emesik** [comment]
Just FYI, the release 0.2 of the project has been published.

**Comment by yeraydiazdiaz** [comment]
Transfer complete.

**Comment by emesik** [comment]
Taken over. Thank you.
