### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mphillipson** [pypa/pypi-support#967]
### PyPI Username

mphillipson

### Reason for request

Lost 2FA authentication app or security token

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mphillipson** [comment]
Just a follow-up to clarify that I lost 2FA authentication to my account when I upgraded my phone; the security token did not carry over when I migrated apps to the new phone. Also lost access to my Test PyPI account, so I expect I will have to submit similar request for that too.

I will take every precaution to prevent this from occurring in the future, but at present I'm just desperate to recover access to these accounts. Many thanks in advance for your assistance!

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
