### ISSUE TITLE
Limit Request: neqsim- 100MB

### ISSUE THREAD

**Issue by EvenSol** [pypa/pypi-support#97]
I get an error because the size of the neqsim package is larger than 60 MB.

**Project**
The project is neqsim
https://pypi.org/project/neqsim/

**Size of release**
100 MB

Please update the size from "60MB" in the issue title as well. 
-->

**Which indexes**
both

**Reasons for the request**
The neqsim project is used by students in thermodynamics. and it the size can not be reduced.

**Comment by jamadden** [comment]
The limit for neqsim has been set to 100mb on pypi.org
