### ISSUE TITLE
Limit Request: mxnet-cu112 - 1G

### ISSUE THREAD

**Issue by szha** [pypa/pypi-support#970]
### Project

mxnet-cu112

### Does this project already exist?

- [X] Yes

### Size of release/project

1G

### Which indexes

PyPI

### Reasons for the request

Same request as #243 #755, for a new variant (cc @ewdurbin)

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
complete.
