### ISSUE TITLE
PEP 541 Request: useragents

### ISSUE THREAD

**Issue by Animenosekai** [pypa/pypi-support#972]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/useragents

### Your PyPI username

`USER_NAME`: https://pypi.org/user/animenosekai

### Reasons for the request

I don't see it appearing on PyPI but it keeps telling me that this name has been taken by another project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/Animenosekai/useragents

### Contact and additional research

I tried but didn't find any information on the current owner.

PyPI is giving 404 when I go to the project page.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @Animenosekai, this project name was placed in the prohibited names list by @pypa/warehouse-admins, moderators do not have permissions to release it.

**Comment by Animenosekai** [comment]
Ok thank you for your response! I'm using `pyuseragents` and it works perfectly for now!
