### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by libinruan** [pypa/pypi-support#973]
### PyPI Username

`Li-Pin Juan`

### Reason for request

I reinstalled Android OS on my cellphone. Since I am new to the 2-step authentication procedure for account security, I was unaware to generate a recovery code to access my PyPI account again. Would you please help me with this issue? Thank you very much in advance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by libinruan** [comment]
I am sorry that I entered my PyPI Username incorrectly. The correct one is `libinruan`. Thanks for the help.

**Comment by ewdurbin** [comment]
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment]
Confirmation complete. 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
