### ISSUE TITLE
Limit Request: `cupy-cuda{102,110,111,112}` - +10 GiB for each (total limit)

### ISSUE THREAD

**Issue by kmaehashi** [pypa/pypi-support#975]
### Project

`cupy-cuda102`, `cupy-cuda110`, `cupy-cuda111`, `cupy-cuda112`

### Does this project already exist?

- [X] Yes

### Size of release/project

Total limit:
* 50 GiB for `cupy-cuda102`
* 20 GiB for `cupy-cuda110`, `cupy-cuda111`, `cupy-cuda112`

(please refer to the discussion below for the detailed estimate)

### Which indexes

PyPI

### Reasons for the request

We're developing [CuPy](https://github.com/cupy/cupy), an implementation of NumPy-compatible multi-dimensional array accelerated by CUDA. This limit increase is needed to provide wheel packages including GPU binaries.

Please allow me to mention that we are continuously working to reduce the package size. In CuPy v9.0.0rc1+ (which is planned to be released tomorrow), we implemented a mechanism to dynamically download dependent shared libraries, reducing a wheel size from 170 MB to 60 MB (https://github.com/cupy/cupy/issues/4850).

Thanks as always for your support!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
Hi @kmaehashi, I'm a little confused by this request. Where does the "100GB" number come from? Do you need a 100GB limit on each of these projects? Or across all these projects?

For the record, `cupy-cuda102` currently has a 40GiB limit set. The rest have the default 10GiB limit. Do you just need this project limit raised for those remaining projects? If so, to what value?

**Comment by kmaehashi** [comment]
Hi @di, thank you for the response, and I'm sorry that my "100 GiB" request was too rough.

Currently, we are estimating the size as follows:

* 80 MiB per wheel x 5 Python versions x 2 platforms (Linux/Windows) = 800 MiB per release
* Two monthly releases (e.g., v9.0.0rc1 and v8.6.0 in March)
* Maintain 2 years for each `cupy-cuda*` project

So our plan is to use 40 GiB for all these projects in the next two years.
It would be great if you could increase the limit size as follows:

|Project|Current Limit|Current Size|Requesting Limit|
|------|----------|----------|---------------------------|
|cupy-cuda102|40 GiB|37.8 GiB|**80 GiB**|
|cupy-cuda110|10 GiB|9.9 GiB|**50 GiB**|
|cupy-cuda111|10 GiB|9.6 GiB|**50 GiB**|
|cupy-cuda112|10 GiB|3.2 GiB|**45 GiB**|
|cupy-cuda120|10 GiB|0.0 GiB|**40 GiB**|

**Comment by di** [comment]
@kmaehashi I can add 10GiB to each limit and we can revisit when you get close again, does that work for now?

Long-term, I think we need to think more about how we can reduce the overall size of projects that depend on CUDA. This type of growth isn't going to be sustainable in two years. There's a discussion happening at https://discuss.python.org/t/what-to-do-about-gpus-and-the-built-distributions-that-support-them/7125 that is relevant, you might want to chime in.

**Comment by kmaehashi** [comment]
@di Thank you, 10GiB for each sounds reasonable and it works for now.

I left a comment on the discussion pointed. I'm happy to join the discussion regarding the design if needed.

**Comment by kmaehashi** [comment]
I've updated the original issue comment.

> 50 GiB for cupy-cuda102
> 20 GiB for cupy-cuda110, cupy-cuda111, cupy-cuda112

**Comment by leofang** [comment]
Friendly ping @di 🙂

**Comment by kmaehashi** [comment]
Hi @di, I'm sorry to pinging you again. I don't want to bother you, but it would be great if we can get a response of any kind.
We are tentatively putting wheels to GitHub Releases page for these 6 months (https://github.com/cupy/cupy/issues/4971), but we're getting reports from users regarding compatibility issues with poetry (https://github.com/cupy/cupy/issues/5664).

We're always taking the wheel size issue seriously. In the short term,
* We decided to remove old pre-release wheels from PyPI. (https://github.com/cupy/cupy/issues/5667)
* We are going to drop support of legacy CUDA versions to reduce the number of wheels.
* We are continuously working on reducing wheel sizes; for example, cupy-cuda92 cp36 Linux wheel size reduced from 355 MB (v8.6.0) to 55 MB (v9.3.0, the latest).

and in the mid/long term:
* We are going to stop building wheels for each CUDA minor release by adopting [CUDA Python](https://nvidia.github.io/cuda-python/overview.html), which is a recently-released NVIDIA's Python binding that supports multiple CUDA versions in a single binary. (https://github.com/cupy/cupy/pull/5638)
* We are discussing whether we should stop uploading pre-release wheels to PyPI.

Many of our users are relying on PyPI distributions and we would like to provide users a better installation experience.
Thank you for your continuous support and understanding. :bow:

**Comment by pradyunsg** [comment]
Thanks for the update, and the updated (lower) file size requests.

For future reference, in case things change again, the current requests are:

- cupy-cuda102: 40 -> 50
- cupy-cuda110: 10 (default) -> 20
- cupy-cuda111: 10 (default) -> 20
- cupy-cuda112: 10 (default) -> 20

> We are continuously working on reducing wheel sizes; for example, cupy-cuda92 cp36 Linux wheel size reduced from 355 MB (v8.6.0) to 55 MB (v9.3.0, the latest).

Since you've reduced the individual file sizes, does this mean it would be OK to update the per-file limit on each of these projects back down to 100 MB? Would this also work for other cupy-cuda.* projects?

> We are going to stop building wheels for each CUDA minor release by adopting CUDA Python, which is a recently-released NVIDIA's Python binding that supports multiple CUDA versions in a single binary. (cupy/cupy#5638)

This sounds great. :)

This is the exact problem I was hoping CUDA Python would solve, and I'm happy to hear that it's able to cater to CuPy's needs.

---

Assuming that you do move to CUDA Python, I'm inclined say that we should update these limits. I'll wait for other PyPI admins/moderators to weigh in on this before I actually go ahead and do that though.

**Comment by kmaehashi** [comment]
@pradyunsg Thanks for the response!

> For future reference, in case things change again, the current requests are:
> * cupy-cuda102: 40 -> 50
> * cupy-cuda110: 10 (default) -> 20
> * cupy-cuda111: 10 (default) -> 20
> * cupy-cuda112: 10 (default) -> 20

Yes.

> Since you've reduced the individual file sizes, does this mean it would be OK to update the per-file limit on each of these projects back down to 100 MB? Would this also work for other cupy-cuda.* projects?

Yes, all newly released wheels are under 100 MB for all `cupy-cuda*` projects.

**Comment by di** [comment]
I've increased the limits as listed in https://github.com/pypa/pypi-support/issues/975#issuecomment-902808459.

**Comment by pradyunsg** [comment]
And, I've gone ahead and updated the per-file limits to 100 MB.

**Comment by kmaehashi** [comment]
Thank you so much @di and @pradyunsg, I really appreciate your help!
