### ISSUE TITLE
Limit Request: mAdvisor - 2000 MB

### ISSUE THREAD

**Issue by rahulmarlabs** [pypa/pypi-support#976]
### Project

https://pypi.org/project/mAdvisor/

### Does this project already exist?

- [X] Yes

### Size of release/project

2000 MB

### Which indexes

PyPI

### Reasons for the request

The existing mAdvisor package available in pypi is plain python code without any code security, now we are doing code obfuscation using cython. Using cython we create compiled binaries for different python versions and OS's, but this process drastically increases the total source code size. On creating the compiled binaries for Linux OS alone, executable in python 3.6, 3.7, and 3.8 had created file of 160 MB, on creating binaries for Windows and Mac will increase the size file size again. So we want to extend the file limit size to 600MB and the project size to 2GB.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rahulmarlabs** [comment]
Hi, any update on this

**Comment by di** [comment]
I'm a little confused by this request. It looks like your individual file sizes are less than 200MB, so we can increase the upload limit to 200MB and you should be able to upload all your distributions.

In addition, the default total project size on PyPI is 10GiB, so 2GB would be well below that limit.

Does increasing the upload limit to 200MB sound like what you actually want?

**Comment by rahulmarlabs** [comment]
Okay, I didn't know the default project size is 10GB, in that case, it is fine for me. If you can increase the upload limit to 200MB, that will be helpful

**Comment by di** [comment]
I've set the upload limit for `mAdvisor` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
