### ISSUE TITLE
PEP 541 Request: gfspy

### ISSUE THREAD

**Issue by jagoosw** [pypa/pypi-support#977]
### Project to be claimed

`gfspy`: https://pypi.org/project/gfspy

### Your PyPI username

`jagoosw`: https://pypi.org/user/jagoosw

### Reasons for the request

The project has been abandoned for a very long time and nothing appears.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

github.com/jagoosw/getgfs

### Contact and additional research

https://github.com/pypa/warehouse/issues/9145#issuecomment-803696191

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
There is no project with that name in PyPI and it is not in the prohibited project names list. It possible the project was removed at some point.
