### ISSUE TITLE
Limit Request: megengine - 950 MB

### ISSUE THREAD

**Issue by xxr3376** [pypa/pypi-support#979]
### Project

megengine https://pypi.org/project/MegEngine

### Does this project already exist?

- [X] Yes

### Size of release/project

950MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

Refer to https://github.com/pypa/pypi-support/issues/838 , We encounter the size limit problem too in CUDA10 package. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `megengine` to 1000 MiB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

Please also note that this is the *maximum per-file upload limit* and we are currently unable to support larger upload sizes.

**Comment by xxr3376** [comment]
Thanks a lot, @di.

We have already put all legacy versions to [external CDN](https://megengine.org.cn/whl/mge.html), Only the 2 latest versions will be kept on PyPI.
Larger packages will be put into external CDN directly in the future (e.g. CUDA11 related packages).
