### ISSUE TITLE
Request reset of 2FA access for my account

### ISSUE THREAD

**Issue by nicoddemus** [pypa/pypi-support#98]
username: nicoddemus
email: nicoddemus@toasttab.com

Request: reset of the 2FA for the above account 
Reason: Had to format my android phone and lost my auth app

Unfortunately I need to access the account to create tokens to upload my open source projects.

**Comment by ewdurbin** [comment]
hello @nicoddemus, can you please email ernest@python.org from the primary email address associated with your PyPI account.

**Comment by nicoddemus** [comment]
Done, thanks!

**Comment by nicoddemus** [comment]
@ewdurbin gentle ping. 😁

**Comment by ewdurbin** [comment]
2FA has been reset and a password reset issued after verifying via repository access.

**Comment by nicoddemus** [comment]
Confirmed, thanks!
