### ISSUE TITLE
PEP 541 Request: capa

### ISSUE THREAD

**Issue by williballenthin** [pypa/pypi-support#984]
### Project to be claimed

`capa`: https://pypi.org/project/capa/

### Your PyPI username

`williballenthin`: https://pypi.org/user/williballenthin

### Reasons for the request

We believe that the PyPI project `capa`: https://pypi.org/project/capa/ has been abandoned.

We believe for the following reasons:
  - the project homepage, hosted on Github, has been removed: https://github.com/Vinh-thuy/capa .
  - the project had a single release on Mon, 19 Dec 2016 at 21:17:42 GMT with no subsequent activity.
  - on 2020/07/22, we emailed the contact listed on the project page and never received a response.

We have distributed our project via the name `flare-capa` (derived from the authors' team at FireEye and the desired name); however, we've been receiving reports that many potential users attempt to `pip install capa` and end up with the wrong code installed on their machine. As the existing PyPI project name `capa` had a single, mostly undocumented, release, we ask to replace this abandoned project.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The existing project (to be replaced) was hosted here (no longer available): https://github.com/Vinh-thuy/capa 

The replacement project is hosted here: https://github.com/fireeye/capa
This is an active project with a dozen contributors and supported by FireEye.

### Contact and additional research

  - on 2020/07/22, we emailed the contact listed on the project page and never received a response.
  - the github user https://github.com/Vinh-thuy is rarely active, though they have shown some activity in the past year.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by williballenthin** [comment]
Now that there's a communication channel opened here on Github

@Vinh-thuy, we would like to use the PyPI project name `capa` that you registered back in 2016. Do you plan to continue development on this project? If not, would you be willing to transfer the PyPI project name to us?

**Comment by Ana06** [comment]
@williballenthin 

> the github user @Vinh-thuy is rarely active, though they have shown some activity in the past year.

I think the @Vinh-thuy GitHub user may not even be the same one who owns the [capa PyPI project](pypi.org/project/capa). The [capa PyPI project](pypi.org/project/capa) was uploaded in 2016 and according to [@Vinh-thuy GitHub's profile page](https://github.com/Vinh-thuy?tab=overview&from=2020-12-01&to=2020-12-31), the account was created in May 2020:
![Screenshot 2021-03-25 at 10 27 09](https://user-images.githubusercontent.com/16052290/112450401-aa5e2d00-8d54-11eb-9fe3-4d5370d5bf5d.png)

This could mean that the owner of [capa PyPI project](pypi.org/project/capa) had deleted his account (including https://github.com/Vinh-thuy/capa) and someone else owns it now.

**Comment by Vinh-thuy** [comment]
Hi

I'm pretty busy at the moment but I'll give this capa project back to you. I created it when I started in Data Science

Regards




________________________________
De : Ana María Martínez Gómez ***@***.***>
Envoyé : Thursday, March 25, 2021 10:33:01 AM
À : pypa/pypi-support ***@***.***>
Cc : Vinh-thuy ***@***.***>; Mention ***@***.***>
Objet : Re: [pypa/pypi-support] PEP 541 Request: capa (#984)


@williballenthin<https://github.com/williballenthin>

the github user @Vinh-thuy<https://github.com/Vinh-thuy> is rarely active, though they have shown some activity in the past year.

I think the @Vinh-thuy<https://github.com/Vinh-thuy> GitHub user may not even be the same one who owns the capa PyPI project<pypi.org/project/capa>. The capa PyPI project<pypi.org/project/capa> was uploaded in 2016 and according to @Vinh-thuy GitHub's profile page<https://github.com/Vinh-thuy?tab=overview&from=2020-12-01&to=2020-12-31>, the account was created in May 2020:
[Screenshot 2021-03-25 at 10 27 09]<https://user-images.githubusercontent.com/16052290/112450401-aa5e2d00-8d54-11eb-9fe3-4d5370d5bf5d.png>

This could mean that the owner of capa PyPI project<pypi.org/project/capa> had deleted his account (including https://github.com/Vinh-thuy/capa) and someone else owns it now.

**Comment by yeraydiazdiaz** [comment]
Thanks for confirming @Vinh-thuy, transfer complete.
