### ISSUE TITLE
Limit Request: sage-conf - 950MB

### ISSUE THREAD

**Issue by mkoeppe** [pypa/pypi-support#985]
### Project

sage-conf - https://pypi.org/project/sage-conf/

### Does this project already exist?

- [X] Yes

### Size of release/project

950MB

### Which indexes

PyPI

### Reasons for the request

SageMath (https://www.sagemath.org/) is a mature, comprehensive, free (open-source) mathematics software system based on Python, licensed under the GNU General Public License, that integrates computer algebra facilities and general computational packages. In addition to the SageMath Python library (https://pypi.org/project/sagemath-standard/), it requires about 140 other Python packages and 170 non-Python libraries/packages - see https://repology.org/projects/?inrepo=sagemath

We wish to distribute Sage as a wheel on PyPI so that it becomes easier and more flexible for users to install it, compared to the traditional way of installing Sage through its distribution. The wheel is currently about 950MB. We have a project to modularize Sage (https://trac.sagemath.org/ticket/29705), so in the future we hope to be able to make smaller wheels. But for now I would like to request an increase of the upload file size limit to 950MB. 

The project makes 2-3 releases every year. With space for release candidates, a total project size limit of 8GB would be workable.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `sage-conf` to 1000 MiB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.

Please also note that this is the *maximum per-file upload limit* and we are currently unable to support larger upload sizes. I would strongly advise finding ways to reduce the overall distribution size if possible.

**Comment by mkoeppe** [comment]
Thank you!
