### ISSUE TITLE
Limit Request: MiMSI - 200 MB

### ISSUE THREAD

**Issue by john-ziegler** [pypa/pypi-support#987]
### Project

MiMSI

### Does this project already exist?

- [X] Yes

### Size of release/project

176 MB

### Which indexes

PyPI, TestPyPI

### Reasons for the request

MiMSI is a deep learning utility that analyzes genomic sequencing results to identify a phenotype call microsatellite instability in cancer patients. The additional space is needed because we would like to package large trained model files in the tool so that other research institutions and hospitals do not need to train/validate their own models. More detailed information on the tool and methods is available on our github - https://github.com/mskcc/mimsi 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `MiMSI` to 200 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
