### ISSUE TITLE
Limit Request: mkl-devel-dpcpp - 200MB

### ISSUE THREAD

**Issue by prstrnn** [pypa/pypi-support#989]
### Project

mkl-devel-dpcpp

### Does this project already exist?

- [X] Yes

### Size of release/project

200MB

### Which indexes

PyPI

### Reasons for the request

I'm from Intel corp. and we are releasing new software in PyPI.
IntelAutomationEngineering - PyPI account we will use to upload packages.
Reasons for the request
It's Intel's software that contains a lot of optimizations for the different hardware, that's why it has so big size.
Expected that future releases will be greater than current. Current sile is 103MB, so 200MB is extra buffer for future releases

Exposure for us: Critical

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by prstrnn** [comment]
Hello, any update on this issue? The release of math kernel library is currently blocked by not being able to publish artifacts to PyPi.

Thanks a lot for your help!

@di  @pjenvey can you please assist with that?

**Comment by di** [comment]
I've set the upload limit for `mkl-devel-dpcpp` to 200 MB on PyPI. Please be mindful of the frequency of releases at that size.
