### ISSUE TITLE
Issue: Limit Request: python-terrier - 120MB

### ISSUE THREAD

**Issue by A-Tsolov** [pypa/pypi-support#99]
**Project**
python-terrier
https://pypi.org/project/python-terrier/

**Size of release**
120 MB

**Which indexes**
PyPI

**Reasons for the request**
Terrier is an open source search engine developed in Java. 
Python-terrier is a python wrapper for it but the jar file is around 100MB, which is why I am requesting the file limit increase. Thanks.

**Comment by jamadden** [comment]
It seems that the "Homepage" link on the project page, https://github.com/A-Tsolov/Pyterrier , is not valid. Could you please share an updated repository URL?

**Comment by A-Tsolov** [comment]
Sorry about that. The repository was private until now. You should be able to view it now.

**Comment by jamadden** [comment]
The limit for python-terrier has ben set to 150MB on pypi.org.
