### ISSUE TITLE
Limit Request: tensorflow-rocm-enhanced - 20 GB (in total)

### ISSUE THREAD

**Issue by sunway513** [pypa/pypi-support#990]
### Project

https://pypi.org/project/tensorflow-rocm-enhanced

### Does this project already exist?

- [X] Yes

### Size of release/project

20 GB (in total)

### Which indexes

PyPI

### Reasons for the request

We've been maintaining Tensorflow support for AMD GPUs via ROCm.
The size of each whl package is about 320 MB, for 3 different flavors that's about 1 GB.
For this project, we want to keep the whl packages that have been released within the last 2 years. Therefore, we would like to increase the total package size limit to 20 GB, thanks for your support. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the total project size limit for `tensorflow-rocm-enhanced` to 20GiB on PyPI. Please be mindful of the frequency of releases at that size.

**Comment by sunway513** [comment]
Hi @di , great! Thanks for the support.
