### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by mxmeinhold** [pypa/pypi-support#991]
### PyPI Username

`mxmeinhold`

### Reason for request

Lost access to email address `mmeinhold@syncurity.net`, as I am no longer employed with the company and the account has been deactivated.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Given that the account has no projects associated with it, we can update the email address. Please email support@pypi.org with your preferred email address.

**Comment by mxmeinhold** [comment]
Oh, sorry, I sent an email from `mxmeinhold@gmail.com` 30 March, but neglected to mention it here. Please let me know if there's anything else you need from me.

**Comment by ewdurbin** [comment]
Address has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.
