### ISSUE TITLE
Limit Request: mkl-devel-dpcpp - 300MB

### ISSUE THREAD

**Issue by nikkidreamt** [pypa/pypi-support#992]
### Project

https://pypi.org/project/mkl-devel-dpcpp/

### Does this project already exist?

- [X] Yes

### Size of release/project

300 Mb

### Which indexes

PyPI

### Reasons for the request

Hi! I am support engineer from Intel, we exceed 100 Mb size limitation for this project. Please increase it as soon as possible. Because it is release time and soon the user will be announced that packaged are publicated.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by di** [comment]
I've set the upload limit for `mkl-devel-dpcpp` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size.
