### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by gward** [pypa/pypi-support#993]
### PyPI Username

gward

### Reason for request

I'm pretty sure my old account (gward) is associated with `gward@python.net`, which I lost access to many years ago.

I forgot about my old account, and created a new account (gregward) associated with two email addresses that I can use. However, there's nothing of value in the new account. If I can recover gward, there's no need for gregward, and you can delete the new account.

Sorry for the bother!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by ewdurbin** [comment]
Email address has been updated to the @gmail.com address (it was removed from the new user in the process). You can now complete a password reset to regain access to your account.
