### ISSUE TITLE
PEP 541 Request: mk on test.pypi.org (already ok on production)

### ISSUE THREAD

**Issue by ssbarnea** [pypa/pypi-support#995]
### Project to be claimed

`PROJECT_NAME`: https://test.pypi.org/project/mk

### Your PyPI username

`USER_NAME`: https://pypi.org/user/ssbarnea

### Reasons for the request

It seems that I am unable to upload mk package to https://test.pypi.org/project/mk and there is no visible package ever published there, so I cannot see who owns the namespace on test instance.

I already have ownership of `mk` on production, but I want both because part of the testing pipelines is to first attempt to upload on test instance.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/pycontribs/mk

### Contact and additional research

Unable to contact owner as this is not visible for packages without releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Transfer complete.
