### ISSUE TITLE
PEP 541 Request: cabinet

### ISSUE THREAD

**Issue by davidstyers** [pypa/pypi-support#996]
### Project to be claimed

`cabinet`: https://pypi.org/project/cabinet

### Your PyPI username

`davidstyers`: https://pypi.org/user/davidstyers

### Reasons for the request

We believe the PyPI project `cabinet`: https://pypi.org/project/cabinet/ has been abandoned.

We believe for the following reasons:

- The package has not received any new releases since 2010.
- The project homepage, hosted on Github, https://github.com/bickfordb/cabinet, has not had any activity since 2010.
- The project maintainer, https://github.com/bickfordb, has not had any activity within the past year.
- I emailed the project maintainer, and as of 3/30/21, have received no response

`cabinet` is the name of my existing project, https://github.com/avoco/cabinet, and to avoid confusion I'd like the package name to be the same as the repo name.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

The existing project: https://github.com/bickfordb/cabinet
My project: https://github.com/avoco/cabinet

### Contact and additional research

I have tried contacting the project maintainer/owner via email and have received no response.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hello @davidstyers, I will now start the reachability process with the owner, hopefully @bickfordb will reply soon and we can move forward with the transfer.

**Comment by bickfordb** [comment]
I went ahead and deleted the project

 - Brandon

**Comment by yeraydiazdiaz** [comment]
Thanks @bickfordb
