### ISSUE TITLE
PEP 541 Request: Reclaim nglview-js-widgets project

### ISSUE THREAD

**Issue by hainm** [pypa/pypi-support#998]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/nglview-js-widgets

### Your PyPI username

`USER_NAME`: https://pypi.org/user/pycpptraj

### Reasons for the request

This project was created and removed immediately by another unknown user. I would like to reclaim it.
This package is the Jupyterlab extension of `nglview`, which I am the leader developer (https://github.com/nglviewer/nglview). Thanks.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/nglviewer/nglview/tree/master/js

### Contact and additional research

~I don't know who is owning the project, because it's not existing anymore:~
The original author created the project by mistake: https://github.com/nglviewer/nglview/pull/955#issuecomment-811495115

https://pypi.org/project/nglview-js-widgets/

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by kawaidev** [comment]
I had registered `nglview-js-widgets` by mistake in my project, and I deleted it just a while ago.

**Comment by yeraydiazdiaz** [comment]
Thanks for confirming @kawaidev, I can confirm there is no project with that name on PyPI.
